### ISSUE TITLE
{name} isn't correctly rendered in test email

### ISSUE THREAD

**Issue by sumobi** [WordImpress/Give#100]
When using the `Send Test Email` feature, the name is properly outputted in the email:
![screen shot 2015-04-09 at 7 45 34 pm](https://cloud.githubusercontent.com/assets/52581/7079994/04ba54b8-def1-11e4-84a1-feee5046d133.png)

result:
![screen shot 2015-04-09 at 7 46 29 pm](https://cloud.githubusercontent.com/assets/52581/7079999/2ae4b282-def1-11e4-85df-827b29ded1e7.png)

The `Preview Donation Receipt` button works fine because it can get the currently logged in user:

![screen shot 2015-04-09 at 7 47 23 pm](https://cloud.githubusercontent.com/assets/52581/7080013/44a60ebe-def1-11e4-89d0-180863089151.png)

In `give_email_test_donation_receipt()` it seems you should be running the body through `give_email_preview_template_tags()` as opposed to the `give_do_email_tags()` function. This is then able to send the test email with the {name} correctly shown.

**Comment by DevinWalker** [comment]
Thanks for catching this :+1:
