### ISSUE TITLE
Remove "Form Labels" functions from translation strings

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#1003]
Give has those two functions: `give_get_forms_label_singular()` and `give_get_forms_label_plural()`.

**From a developer point of view** it's easier to update the labels in one place and to see all the labels in all the strings updated accordingly.

BUT, **from a translator point of view** it can be a nightmare. We use `%s` placeholder in translation strings for the form labels. But it's a bad practice. In many cases it's makes it hard to understand what the plugin is trying to say and how to translate the string.

Two examples I encountered when translating to Hebrew:
* When using placeholders, in some languages it's hard to translate the string without the gender of the placeholder.
* In other translation strings, you use singular placeholders (for English), but in other languages we should use plural placeholders.

I'm not saying we need to deprecate those functions, I'm just saying we need to remove them from translation strings.

**Comment by DevinWalker** [comment]
I agree, let's keep the functions around so other add-ons using them won't cause issues.
