### ISSUE TITLE
Use filters for all front-end text on Give Forms

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1010]
User really like to be able to customize the text of the form, whether it's the "Personal Info" legend title, or  just adding "Your First Name" instead of "First Name". 

The problem is that some things have filters and others are just localized. It would be easiest if all front-end text had filters so we (in Support) could provide PHP snippets for any text customization because Localization edits are much more challenging for end-users.

@DevinWalker Do you agree?

**Comment by DevinWalker** [comment]
I think this is a subtask of #380 which we pass all string through an array that is filtered via one hook, similar to how we are doing with the the validation strings

**Comment by mathetos** [comment]
You sure you mean #380 ?

**Comment by DevinWalker** [comment]
No not #380 - my bad I mean #1038

**Comment by mathetos** [comment]
@DevinWalker I agree that there's overlap between this issue and #1038 but I don't think this issue has to wait until version 2.0. Couldn't this get done before 2.0 in order to make #1038 a bit easier?

**Comment by DevinWalker** [comment]
I'd rather do it the right way than adding a bunch of one off filters.

**Comment by DevinWalker** [comment]
Closing this one out. https://codex.wordpress.org/Plugin_API/Filter_Reference/gettext has proven an effective solution.
