### ISSUE TITLE
STOP USING `global $pagenow`

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#1017]
We need to start using the `get_current_screen()` function.

Before deprecating the use of `global $pagenow`, we need to investigate how it will that effect our code.

This will also improve our scrutinizer score at #675.

**Comment by DevinWalker** [comment]
How's this going @ramiy ?

**Comment by ramiy** [comment]
@DevinWalker Forgot about this ticket.... I'll fix all the occurrence of this global.

**Comment by ramiy** [comment]
Done!

**Comment by DevinWalker** [comment]
@ramiy I'm still seeing `global $pagenow` in a few spots:

https://github.com/WordImpress/Give/blob/release/1.7/includes/admin/EDD_SL_Plugin_Updater.php#L72
https://github.com/WordImpress/Give/blob/release/1.7/includes/admin/admin-pages.php#L77
https://github.com/WordImpress/Give/blob/release/1.7/tests/unit-tests/tests-scripts.php#L100

**Comment by ramiy** [comment]
- **EDD_SL_Plugin_Updater.php** - it's an external file, the next time you upgrade this file you will override all my changes.

- **tests-scripts.php** - it's a test. not critical.

- **admin-pages.php** - I don't understand why we need the `give_is_admin_page()` function? why not use `get_current_screen()` where it's needed.

**Comment by ramiy** [comment]
I will update the test.

**Comment by DevinWalker** [comment]
`EDD_SL_Plugin_Updater.php` should be updated, we hardly ever update this file and will take precaution if we do.

Tests are part of the plugin, if we're going to stop usage, let's do it throughout.

To be honest, I'm not a big fan of `give_is_admin_page` either. It's a giant conditional mess. The thought behind it was to simplify checking whether an admin page or not is Give related. I created an issue to tackle this: https://github.com/WordImpress/Give/issues/1091

**Comment by ramiy** [comment]
Where is the `EDD_SL_Plugin_Updater.php` source? I can update the source file in EDD repo, and then update the file in Give plugin.

**Comment by ramiy** [comment]
The new PR updates **EDD_SL_Plugin_Updater.php** and **tests-scripts.php** files.
