### ISSUE TITLE
Sending test email doesn't notify user that anything was sent

### ISSUE THREAD

**Issue by sumobi** [WordImpress/Give#102]
When a test email is sent it reloads the page but doesn't show any indication of whether or not the email was sent. A admin notice would help here.

**Comment by DevinWalker** [comment]
Agreed

**Comment by NikV** [comment]
How would we like to tackle this? I would be willing to help add this feature :)

**Comment by DevinWalker** [comment]
Oh yeah? I'm thinking an admin notice on the backend once the button has been clicked. Any other ideas?

**Comment by NikV** [comment]
Got a little stuck, I'm not quite sure how to check if the button was clicked and fire off 'admin_notices', do you have any idea how I could start with this?

**Comment by DevinWalker** [comment]
I'm guessing it would have to be a parameter in the URL that gets triggered when the button is clicked and then triggers the notification. That's what I initially thought about when I was going to take this one on.

**Comment by NikV** [comment]
Ah seems I made a mistake in my code, i think I'm getting somewhere with it now!

**Comment by DevinWalker** [comment]
Props to @NikV for taking this one on.
