### ISSUE TITLE
Use i18n module

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#1021]
We can add [Yoast i18n module](https://github.com/Yoast/i18n-module) to increase translators involvement. But we won't use external glotpress, we will use wp translate.

It's a nice class. Simple integration.

**Comment by ramiy** [comment]
@DevinWalker What do you think?

**Comment by DevinWalker** [comment]
I like it, I reviewed over the weekend during WordCamp and Yoast mentioned this to us. It would definitely help us get more involvement.

**Comment by DevinWalker** [comment]
If this isn't too difficult to implement why don't we roll it into the next point release @ramiy - it looks like it's simply a class we fork, customize the class name and prefixes, swap out the logo for ours and touch up the CSS. What do you think?

**Comment by DevinWalker** [comment]
@ramiy can you hop on this when you get a chance? LMK if you want to discuss.

**Comment by ramiy** [comment]
It's in my TODO list.
