### ISSUE TITLE
Prefix .icon class to prevent conflicts

### ISSUE THREAD

**Issue by stevengliebe** [WordImpress/Give#103]
Give is looking great, guys.

A user of one of my old themes is using it. Both the plugin and theme are using a class named .icon. As a result, the question mark icon tooltips are not showing correctly.

Ideally all plugins and themes should prefix all classes but my theme is several years old with thousands of users, many of whom are using a child theme. I'm not planning on prefixing classes this late in the game so that I do not break the work people have done with their child themes.

Could you please prefix the .icon class in Give? I assume it's using an icon font that dictates the class name. If that's the case, maybe modify the icon font to use Give-prefixed classes for icons. I've done this with my newer themes to avoid conflicts and it has worked well. Just have to remember to re-add the class prefixes when updating the icon font.

This will eliminate conflicts with other themes and plugins using a generic .icon class, of which I'm sure there are several given that prefixing classes is not as common as it ought to be.

**Comment by BurlesonBrad** [comment]
nice :+1:

**Comment by DevinWalker** [comment]
Definitely! I'll get right on that. Expect it soon. :+1:

**Comment by stevengliebe** [comment]
Fantastic, thank you!
