### ISSUE TITLE
Email Tags Issues Across Several Add-ons

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1030]
We currently have a few open issues related to email tags. This affects primarily 
- Form Field Manager
- PDF Receipts
- Recurring Donations

Here's a quick list:
## CORE
1. https://github.com/WordImpress/Give/issues/611
## FFM
1. https://github.com/WordImpress/Give-Form-Field-Manager/issues/35
2. https://github.com/WordImpress/Give-Form-Field-Manager/issues/39
## PDF Receipts
1. https://github.com/WordImpress/Give-PDF-Receipts/issues/43
2. https://github.com/WordImpress/Give-PDF-Receipts/issues/65
## Recurring
1. https://github.com/WordImpress/Give-Recurring-Donations/issues/233
2. https://github.com/WordImpress/Give-Recurring-Donations/issues/198

I'm wondering if there's something we can do in Core to help resolve all these issues and prevent issues like these from cropping up in the future. Perhaps the way we render email tags in email content areas or PDF receipts can be consolidated into one base helper function. Not sure, just seems like we can be smarter about this.

**Comment by DevinWalker** [comment]
Closing in favor of: https://github.com/WordImpress/Give/issues/1346

We will address and explain conditional email template tags and their usage across various emails within that issue.
