### ISSUE TITLE
Unifying the addons action-links in "plugin" screen

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#1033]
We need to standardize the action links in all our addons.

Currently, some addons have links to the the addon site, other don't. Some have links to the settings page, other don't. Some addons link back to Give.com documentation and support, others don't.

![addon-action-link](https://cloud.githubusercontent.com/assets/576623/18583832/b70b46d2-7c15-11e6-863f-b197e71a303c.png)

I'm currently reviewing all the addons. I can make the changes. But we need to have a standard set of links.

**Comment by mathetos** [comment]
Good point. @ramiy Do you think we could just create a class in Give Core that each of the Add-ons extend to make that as consistent and easy as possible?

**Comment by ramiy** [comment]
@mathetos, some links come from the plugin header, others use filters. Give core has those filters in a separate file: https://github.com/WordImpress/Give/blob/master/includes/admin/plugins.php we can just copy&paste this files to each addon.

**Comment by DevinWalker** [comment]
Consistency is definitely a good idea. Rather than a core issue, let's add this per Add-on. Also, let's not use `Docs` but rather `Documentation` for consistency. :)

**Comment by ramiy** [comment]
Ok, I'm on it.

**Comment by ramiy** [comment]
The **Author** and **Plugin** links are controlled from the plugin header using:

```
 * Plugin URI:  https://givewp.com/addons/.../
 * Author URI:  https://wordimpress.com
```

![author-and-plugin-links](https://cloud.githubusercontent.com/assets/576623/18686665/609cb768-7f85-11e6-80f6-5c2ac6cda045.png)

**Comment by DevinWalker** [comment]
Looking good!

**Comment by ramiy** [comment]
Mission accomplished!

![addon-action-and-meta-links](https://cloud.githubusercontent.com/assets/576623/18694903/9d5f1214-7fb6-11e6-8f1c-ca2dcd3fc28f.png)

**Comment by ramiy** [comment]
I should say that each addon has a new **plugins.php** file with a set of unique action links and row meta links.
