### ISSUE TITLE
New Display Options: Display "Donate Now" button

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1037]
We should allow admins to create "Donate Now" buttons - with customizable button text so that they can embed donate now buttons easily within posts and pages.

Further details on task:
- should work with both the widget and shortcode
- basic styles so that the button displays nicely within posts and pages, sidebars, widget zones, etc.

**Comment by mathetos** [comment]
Is this a duplicate of #520

**Comment by DevinWalker** [comment]
Derp, yeah.
