### ISSUE TITLE
Better handling for form template layout creation - Form Building API

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1038]
This file https://github.com/WordImpress/Give/blob/master/includes/forms/template.php is getting to be a mess and the DOM for the donation forms is not ideal.

Ideas:
- OOP structure with field creation API similar to the new settings API
- Add a better method to switching form field
- We should standardize the classes within the donations forms
- Dynamic filter for form text based on field type: Use filters for all front-end text on Give Forms

**Comment by mathetos** [comment]
Was this going to be bumped up to 1.8?

**Comment by DevinWalker** [comment]
Nope, plan is still 2.0

**Comment by DevinWalker** [comment]
@ravinderk how about we pivot the settings field API into an abstract class that's the core of the "Give Fields API" then the wp-admin settings can extend / override where needed and the frontend form building can as well. Why? The settings fields API already has so many simple and advanced fields and would lessen the bloat of the plugin. Cons: we haven't done much research yet on how this would work with tabbed sections, form field builder integration, current custom snippets, etc. https://github.com/oomphinc/WP-Forms-API

**Comment by kevinwhoffman** [comment]
Closing due to overlapping concerns with epic #2905. Adding this issue to the epic's Related section.
