### ISSUE TITLE
Show message on form edit screen if form single view is disabled

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1049]
<img width="1067" alt="screen shot 2016-09-22 at 4 01 01 pm" src="https://cloud.githubusercontent.com/assets/1784821/18744955/e0965740-80dd-11e6-8b85-95706d4f684c.png">

<img width="1209" alt="screen shot 2016-09-22 at 4 02 06 pm" src="https://cloud.githubusercontent.com/assets/1784821/18744976/fa585fa2-80dd-11e6-9e34-2b750f9969e3.png">

I think if form single view is disabled, then user should not able to see `visit form` link in admin bar in `wp-backend` or We can also display a message on form edit screen which inform user that form single view is disabled with a link which will take user to setting page where user can change that setting.

**Comment by Benunc** [comment]
I made an issue about this a while back. I think what we found is that this is a "bug" in WP core, since that code is generated when a CPT is saved or published. I agree that it needs to go away, because clicking it is confusing.

**Comment by mathetos** [comment]
@ravinderk If there's a hook available in that success alert, then by all means change that message, but I'm fairly certain there isn't unfortunately.

**Comment by ravinderk** [comment]
@mathetos Yes, We can update that message. Please take a look.
https://github.com/WordImpress/Give/blob/master/includes/post-types.php#L374

**Comment by mathetos** [comment]
That looks great. Definitely would love to customize that smartly so there's no confusion for the user. Thanks!

**Comment by ramiy** [comment]
@ravinderk @mathetos It was an easy fix, see the PR.
