### ISSUE TITLE
Dynamically update giving form Amount

### ISSUE THREAD

**Issue by ingageco** [WordImpress/Give#1057]
Team - thanks for the great plugin. I have need to dynamically update the form total (via js, after adding some figures in a form beforehand). I'm successfully updating the total amount field, but the form continues to fail, giving the "There's a minimum donation amount of 0.00" error. Any help? Is there a recommended process to update that field that I could use?

**Comment by mathetos** [comment]
Hi @ingageco Can you provide a snippet of the code you are using as a reference?

**Comment by ingageco** [comment]
`        $("input#give-amount", form).attr('value', finalTotal);

        $("#give-final-total-wrap .give-final-total-amount").attr("data-total", finalTotal);
        $("#give-final-total-wrap .give-final-total-amount").html("$" + finalTotal);`

**Comment by ingageco** [comment]
Here's a link to the page: http://alpha.sites.websitemocks.com/give/ (test mode)

**Comment by ingageco** [comment]
Any help? Changed some stuff up last night, still same result.

**Comment by DevinWalker** [comment]
@ingageco are you using the latest version 1.6.1?

**Comment by ingageco** [comment]
Yes I am. The donation total input is updating correctly, but the form still won't submit (minimum error). I have no minimum set on the form and really the only thing I'm doing is setting the donation total using JS - so I dont see why it wouldn't submit. Is there a hidden field or some sort of JS in Give that runs when the total is added that negates the minimum that I might be missing?

**Comment by ingageco** [comment]
Here's my updated JS

` $("input#give-amount", form).attr('value', finalTotal);

        $("#give-final-total-wrap .give-final-total-amount").attr("data-total", finalTotal);
        $("#give-final-total-wrap .give-final-total-amount").html("$" + finalTotal);

         $(".give-donation-amount .give-text-input").trigger('blur');
         $(document).trigger('give_donation_value_updated');`

**Comment by DevinWalker** [comment]
Hey @ingageco there's most likely something going on with your jQuery. I tested this with a quick implementation using the following code:

```
/**
 * Testing #1057
 */
function my_test_output() {
	echo '<input class="give-text-input designation-item-value" name="desvalue_new1" id="desvalue_new1" type="tel" placeholder="" value="0.00" autocomplete="off" style="margin-right: 5px;">';
	?>
	<script>


		jQuery('#desvalue_new1').on('blur', function(){

			var form = jQuery('.give-form');
			var finalTotal = jQuery('#desvalue_new1').val();
			console.log(form);
			console.log(finalTotal);
			jQuery("input#give-amount", form).attr('value', finalTotal);
			jQuery("#give-final-total-wrap .give-final-total-amount", form).data('total', finalTotal);
			jQuery("#give-final-total-wrap .give-final-total-amount", form).html("$" + finalTotal);
		});

	</script>

	<?php

}

add_action( 'give_pre_form_output', 'my_test_output' );
```
You should set the `data` attribute using jQuery's `data` method rather than `attr` which I believe may be causing the problem.

Here's how it appears on my end:

![j0h83i9v9m](https://cloud.githubusercontent.com/assets/1571635/18972529/601abdec-864e-11e6-8fe9-86710848cb9d.gif)

Since this is more of a support request than an issue with the plugin I'm going to close this out. Please post any additional support related requests here: https://wordpress.org/support/plugin/give

**Comment by ingageco** [comment]
Devin - thanks, your code does work great for me. I'll use it as a foundation to refactor our code.

**Comment by DevinWalker** [comment]
Sounds good @ingageco I'm interested in what you're building. Would you like to join our Slack developer channel?

**Comment by ingageco** [comment]
Devin - absolutely would. I think this would be a nice addition as an add-on. Additionally, i have preliminary work done for Give as an add-on that makes saved cards in Stripe available as a payment method.

**Comment by DevinWalker** [comment]
That Stripe feature sounds like a great feature. Let's chat it up! Will the email on your GitHub work for the invite?

**Comment by ingageco** [comment]
jay [at] weingage.com

**Comment by ingageco** [comment]
I'm doing a lot of work over the next month with Give so i'll probably have something to present to you guys for scrutiny (I'm sure my code will need help) late October!

**Comment by ingageco** [comment]
Devin - found the issue. I did not know that a disabled input does not submit. I was disabling the total input to keep the user from inputting an amount that didn't match the designation totals.

**Comment by DevinWalker** [comment]
Interesting, I didn't know that either. Glad you uncovered it!
