### ISSUE TITLE
All setting notices should be dismissible

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1061]
I noticed some notices are dismissible and other are not:

![screenshot at sep 30 14-33-32](https://cloud.githubusercontent.com/assets/1571635/19007656/eab502b0-871a-11e6-8def-5fdb2feff855.png)

- [x] Ensure all Settings notices are dismissable

Thought: For the main update message, I feel this should disappear after 5 seconds. It serves no purpose sitting there. What do you think?

**Comment by ravinderk** [comment]
@DevinWalker Like your idea 👍 . This is not so much important message, so we can hide this in 5seconds.
