### ISSUE TITLE
Fix API request log count

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1069]
## Issue Overview

API request log count is not correct.

<img width="1229" alt="screen shot 2016-10-03 at 4 53 30 pm" src="https://cloud.githubusercontent.com/assets/1784821/19035892/0b4c1d9e-898a-11e6-8378-18372329b239.png">

## Steps to Reproduce (for bugs)

1. Goto report --> Logs tab
2. Submit form before log table to see only api logs
3. Check api request log count

**Comment by malayladu** [comment]
![log-count](https://cloud.githubusercontent.com/assets/708174/22101284/ccff9eac-de58-11e6-88ba-cbf8f3bb8db9.png)

@ravinderk Are you referring to this?

**Comment by malayladu** [comment]
![log-count](https://cloud.githubusercontent.com/assets/708174/22101334/09586546-de59-11e6-86cb-920afe0941f2.png)

@DevinWalker  Are you referring to this?

**Comment by ravinderk** [comment]
@malayladu Yes

**Comment by malayladu** [comment]
Ok.

**Comment by malayladu** [comment]
I am not able to see Logs in Give release/1.9. (see attachment). Am I missing anything?

![screen shot 2017-01-19 at 4 32 43 pm](https://cloud.githubusercontent.com/assets/708174/22104525/8cd30d2a-de65-11e6-9d55-8e163364da9a.png)

**Comment by DevinWalker** [comment]
@malayladu it has been moved to under tool.

**Comment by malayladu** [comment]
@ravinderk Thanks for the info

**Comment by malayladu** [comment]
When I tried to use Give API using [](http://localhost/Projects/wordpress/wp/give-api/v1/donations/?key=<KEY>&token=<TOKEN>&format=json) at that time it gives Page Not Found error. Why is it so?

Do I need to do any settings to make Give API work?

**Comment by DevinWalker** [comment]
@malayladu you may have to refresh your permalinks.

**Comment by malayladu** [comment]
@DevinWalker Yeah...that's what I missed. 

It's working now.

**Comment by malayladu** [comment]
I have tried to reproduce the issue. But it seems display correctly. (see attachment). @ravinderk Is there any other steps available to reproduce the same issue?

![give tools apps magnet wordpress](https://cloud.githubusercontent.com/assets/708174/22195741/7ae151e6-e16f-11e6-9eba-7b6533d8e059.png)
