### ISSUE TITLE
Give - Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by monecchi** [WordImpress/Give#107]
Hi there. I'm quite interested about using Give on my next project. In order to contribute to Give I've forked the project and I've just finished the translation of the plugin to the Brazilian Portuguese language "pt_BR". It was a pleasurable translation process (not automated), based on the human understanding of the plugin's donation flaw and settings.

However, I'm not a Git expert user and I simply don't know how to let you guys know about the translation files, so I opened this "issue ticket" just to set for you guys who created Give a notification about it.

Here are the translation files anyway: https://github.com/monecchi/Give/tree/master/languages

**Comment by DevinWalker** [comment]
Hey @monecchi thanks a lot for your help translating the plugin! That's exciting to know we have Brazilian Portuguese ready to roll. 

We'd LOVE for you to do a Pull Request so you can get credit for your translation within the plugin and on our website. Here's some help:

https://help.github.com/articles/using-pull-requests/

Essentially, you're going to 'fork' Give, drop in your translation file, commit it, and then create the PR using the instructions above.

If this is all foreign to you, no worries, we can still incorporate your translation. Just let me know!

**Comment by monecchi** [comment]
Hi there @DevinWalker. Thanks for your quick help on pointing me out how to make a Pull Request. I'm sure I'll soon become an advanced Git user, but for now, I think I was able to submit the PR with the translation files.

Have a nice day!
Adriano Monecchi

**Comment by DevinWalker** [comment]
I just merged your PR thanks for that! https://github.com/WordImpress/Give/pull/108
