### ISSUE TITLE
To include a picture.

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#111]
Hey

I noticed that when not adding a featured image a placeholder image would be inserted.
It would be nice to add the option to have or have not - to include an image.
Text by a checkbox could be "To use your own image add a featured image." If you do not want to use an image on your donation page then click the disable image check box.

I have just scratched the surface of the plugin.
I am working on setting up a donation for my web site
http://easywebdesigntutorials.com/ and a video tutorial and screenshots as well for a blog post.
I'll let you guys know about it.

**Comment by DevinWalker** [comment]
I don't think it's necessary to have an option for that. The user can simply remove the single post type option altogether. BUT, I do think it need to be documented on our website for users to easily know how to customize the featured image and what their options are there.

**Comment by paaljoachim** [comment]
I noticed the single donation page will include a placeholder or a featured image.
Including a shortcode on a page the image will not be included.

Adding/removing an image how do I control this? As in
Removing image from single donation page.
Adding image to the page where a shortcode is added. 
Got some easy tips on this matter?

**Comment by DevinWalker** [comment]
There is now an option as of commit c6af9bad4ea9363c84baf19f97e7cdd137f069bf to disable the featured image - It's under Give > Settings > Display Options > Disable Form Feature Image
