### ISSUE TITLE
Profile Editor Template

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#1111]
## Issue Overview

Field alignment issues.

## Current Behavior

![give-profile-current](https://cloud.githubusercontent.com/assets/576623/19279680/05677a10-8feb-11e6-8c9e-7b3b3f73c00c.png)

## Expected Behavior

![give-profile-new](https://cloud.githubusercontent.com/assets/576623/19279673/fa9e6b34-8fea-11e6-9a52-350dcb28208c.png)

## Possible Solution

- The billing address fields should use the same class as all the other fields. 
- The password notice should have `clear:both`.

**Comment by mathetos** [comment]
Good catch! Your annotations made me chuckle.

**Comment by ramiy** [comment]
Seems like the password notice fixed in #998 .
