### ISSUE TITLE
Address fields are not being passed to the API

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1112]
## Issue Overview

The Give API is not picking up Donor Address data in either the Donor endpoint or the Donation endpoint.
## Expected Behavior

When a donation is processed, the Donation and Donor endpoints should include donor address data.
## Current Behavior

Currently on the Donation Endpoint, there are the following fields:

```
"ID"
"transaction_id"
"key"
"total"
"gateway"
"name"
"fname"
"lname"
"email"
"date"
"form" {
   "id"
   "name"
   "price"
            },
"payment_meta": {
   "fees": [],
   "currency": "USD"
            }
```

Currently on the Donor endpoint there are the following fields:

```
"info": {
   "user_id"
   "username"
   "display_name"
   "customer_id"
   "first_name"
   "last_name"
   "email"
            },
"stats": {
   "total_donations"
   "total_spent"
            }
```
## Steps to Reproduce
1. Create a form with address required
2. Submit a donation
3. Check the API URL donation endpoint here: http://yoursite.com/give-api/donations/?key=YOURPUBLICKEYHERE&token=YOURTOKENHERE and the Donor endpoint here: http://yoursite.com/give-api/donor/?key=YOURPUBLICKEYHERE&token=YOURTOKENHERE following the instructions in the API reference: https://givewp.com/documentation/developers/give-api-reference/
4. No Address field is there.

**Comment by mathetos** [comment]
@Benunc Did you also check the /donation endpoint instead of just the /donor endpoint?

**Comment by Benunc** [comment]
Yes, as noted in the issue. Neither endpoint is functional for addresses.

**Comment by DevinWalker** [comment]
The `donor address` and `billing address` are separate from each other. See  https://github.com/WordImpress/Give/issues/370 for details. Despite this, the `billing address` should be included within the `payment_meta` array

**Comment by kevinwhoffman** [comment]
@DevinWalker I just left feedback on https://github.com/WordImpress/Give/issues/370#issuecomment-254569739. Do you think that issue needs resolved before fixing the API here? If the location of where donor addresses are saved within the database changes, that will affect where the API retrieves them from.

**Comment by DevinWalker** [comment]
@kevinwhoffman please review my comment on #370 and LMK what you think. If you agree the location of the billing address in `_give_payment_meta` stays in place then we can proceed here.

**Comment by kevinwhoffman** [comment]
@DevinWalker I agree that billing address stays within `_give_payment_meta`, so I can fix the Donations endpoint, but the Donor endpoint should wait until the changes mentioned in #370 are complete. Agree?

**Comment by DevinWalker** [comment]
Agree, yes. Ideally we'll loop through the `_give_payment_meta` array and output the contents within the API response.

**Comment by DevinWalker** [comment]
@emgk can you take care of this for me?

**Comment by emgk** [comment]
Sure, @DevinWalker I will check

**Comment by emgk** [comment]
I have reproduced this issue and found that `\donations` endpoint containing payment `billing_address` but not `donor_address` and `\donor` has no address in it. 

> Despite this, the billing address should be included within the payment_meta array on the both endpoints

@DevinWalker as mentioned in above line, do we need to include `payment_meta` array in `/donor` endpoint as well?  Because `billing_address` may vary for each donation created by any particular donor, so how would we determine which `billing_address` it should contain for the specific donor?

**Comment by DevinWalker** [comment]
Hey @emgk - the `/donations/` endpoint should only have the billing address for that payment. The `/donor/` endpoint should loop through all the addresses attached to the donor and output them. You don't need to include all the payment meta info.

**Comment by mathetos** [comment]
Just tested and this works perfectly. Just wanted to confirm. See here:

![image](https://user-images.githubusercontent.com/930724/34633932-608a28aa-f234-11e7-9455-529912272cae.png)
