### ISSUE TITLE
Clicking outside modal should not close the modal

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1116]
## Issue Overview
When you have a donation form set to open the payment fields within a modal window and the user clicks on the dark outside area it closes the modal. It's really easy to accidentally click on the outside and the donor has to then click again to open it. This lowers conversion rates and leads to donor frustration.

## Possible Solution
Adjust the modal functionality so that only clicking on the close button will close the window.

## Screenshot

![screenshot at oct 12 12-27-01](https://cloud.githubusercontent.com/assets/1571635/19324617/64ab56a4-9077-11e6-8873-4b04b0f6bd0d.png)

**Comment by ramiy** [comment]
Ref: http://dimsemenov.com/plugins/magnific-popup/documentation.html
