### ISSUE TITLE
Function to clear `give_stats_*` transients created by `get_earnings`

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1117]
## Issue Overview

If I make a number of donations in an hour and check the stats using the `get_earnings` method within an Add-on for the given day

This cropped up when developing the [Email Reports Add-on](https://github.com/WordImpress/Give-Email-Reports).
## Expected Behavior

`get_earnings` pulls the most recent data when you need it
## Current Behavior

`get_earnings` pulls data up to an hour old due to the transients being set:

![stats-transients](https://cloud.githubusercontent.com/assets/1571635/19326631/2a7e3272-9080-11e6-91af-0b0305ae8da1.png)
## Possible Solution

The transient usage is good to minimize server impact on large sites but we should still provide a way to fetch the latest content. I suggest we add a parameter to `get_earnings` called `new_query` to query fresh data whether or not the transient exists. Applicable line numbers: https://github.com/WordImpress/Give/blob/master/includes/payments/class-payment-stats.php#L147-L149 
## Steps to Reproduce (for bugs)
1. Create several test transactions
2. Pull stats for today using `get_earnings`:

```
    $stats = new Give_Payment_Stats();
    $start_date = 'today';
    $end_date   = false;
    echo give_format_amount( $stats->get_earnings( 0, $start_date, $end_date ) );
```
1. View the reports (click refresh reports button)
2. Reports will be correct, the return from step 2 above will not
## Todos
- [ ] Determine best approach, parameter or separate function
- [ ] Implement code and test
- [ ] Submit PR

**Comment by ravinderk** [comment]
@DevinWalker I think it is already done in `1.8.7` release.
For ref: #1617
