### ISSUE TITLE
If only one payment gateway is enabled the "Select Payment Method" fieldset should be hidden 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1122]
## Issue Overview

I've seen multiple websites only using PayPal Standard or Stripe, no other gateways. In this case, the donor has no choice as to what their payment method is. 
## Possible Solution

We should hide the "Select Payment Method" fieldset if only one payment gateway is enabled.
## Screenshot

![screen shot 2016-10-14 at 10 22 56 am](https://cloud.githubusercontent.com/assets/1571635/19396490/2fa3bb0e-91f8-11e6-8504-e91bb8cc19de.png)

**Comment by ramiy** [comment]
@DevinWalker I was playing with this issue, and I had several solutions.

We can only hide the section from the user. Or we remove the HTML code entirely.

When removing the code entirely, the radio "payment-mode" radio field is missing, this is why I decided only to hide the DIV from the user.

**Comment by DevinWalker** [comment]
that's perfect, hiding the div is the way to go

**Comment by DevinWalker** [comment]
Reopening, I see some issues with how this is functioning currently. The `<legend>` is wrapping the entire payment gateways fieldset. I've fixed it, PR coming.

**Comment by mathetos** [comment]
This isn't totally resolved. 

# How to Replicate

* Enable only one payment gateway
* Create a form with the "Display on Click" method
* Hit the "Donate" button and the Payment Method section will be forced to display
* Set that same form to the "Show on Page" method and the Payment Method section is hidden completely and correctly.
