### ISSUE TITLE
TinyMCE icon?

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#113]
Hey

I notice the button is fairly huge for adding a donation form to a page/post. (It looks pretty nice next to the Add Media button though..:)

What about adding an icon to the TinyMCE bar instead? To the right of the kitchen sink icon.

**Comment by DevinWalker** [comment]
TinyMCE is a pain to work with and we're happy with the button and it's placement currently. It makes it really easy to see and is much easier to code outside TinyMCE (we're working with their API with another plugin and it's tough sledding).

**Comment by paaljoachim** [comment]
Gotcha! Seems you found a good route to follow..:)
