### ISSUE TITLE
Build correct redirect url in give_send_back_to_checkout if request url already has query param

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1130]
## Issue Overview
Simple url for donation form is `http://give.dev/donations/form-testing/`

If we will get error once then it will become `http://give.dev/donations/form-testing/?form-id=2120&payment-mode=iatspayments&give-iats-message=22#give-form-2120-wrap`

If we will get error twice then it will become `http://give.dev/donations/form-testing/?form-id=2120&payment-mode=iatspayments&give-iats-message=15#038;payment-mode=iatspayments&#038;give-iats-message=22#give-form-2120-wrap`

## Possible Solution

Process url carefully who has query param in `give_send_back_to_checkout` https://github.com/WordImpress/Give/blob/master/includes/forms/functions.php#L165

## Steps to Reproduce (for bugs)

Keep getting error on donation form page ( check with any error who redirect you back you donation form page).

**Comment by DevinWalker** [comment]
@kevinwhoffman can you check out @ravinderk's comments on PR #1136 and revise the logic to merge query params rather than replace. Example: https://github.com/WordImpress/Give-iATS/blob/master/includes/give-iats-payment-processing.php#L174#L183

**Comment by kevinwhoffman** [comment]
Will do. Thanks for the example, @ravinderk.

**Comment by kevinwhoffman** [comment]
Resolution of this issue is roadblocked by #1146. In order to maintain multiple query params after redirect, we need to fix the way we are escaping URLs.
