### ISSUE TITLE
Updating donor profile results in email error

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#1131]
## Issue Overview

The following error seems to prevent any type of update to donor info from the donor profile screen.

Attempting to edit donor information using the `Edit Donor` button results in a server-side error upon submission: `Error: Please enter a valid email address.`

I thought that possibly the email field farther down the page was triggering the error, but entering a valid email in that field still results in the same error. This error occurs when attempting to edit registered and unregistered donors.

## Expected Behavior

User should be able to update donor info from donor profile screen.

## Current Behavior

Clicking `Update Donor` results in an error that references a valid email address. User is left confused because an email field is not part of the form they are updating.

## Possible Solution

Investigate server-side validation to remove the condition causing the error.

## Steps to Reproduce (for bugs)

1. Make a donation with address fields.
2. View donor profile.
3. Click `Edit Donor` button at top of profile.
4. Change address fields.
5. Click `Update Donor`
6. Error appears: `Error: Please enter a valid email address.`

The same error occurs for unregistered users that only have a `User ID` field to edit.

## Screenshots

Error when attempting to update regisered user's address.

![image](https://cloud.githubusercontent.com/assets/1938671/19485300/bef3cd66-9528-11e6-9a9e-8130e549517f.png)

Error when attempting to update unregisered user's name.

![image](https://cloud.githubusercontent.com/assets/1938671/19485458/3fdfb4ee-9529-11e6-935b-81dde2881caa.png)

## Context

Discovered while investigating address fields for #1112.

## Your Environment

* Give version used: 1.7
* Browser Name and version: Chrome 53.0.2785.143 (64-bit)
* Operating System and version (desktop or mobile): OS X Yosemite 10.10.5

**Comment by DevinWalker** [comment]
Interesting. I think this may be a bug related to https://github.com/WordImpress/Give/issues/999

**Comment by kevinwhoffman** [comment]
I confirmed this is only an issue in Give 1.7+ related to Donor Email functionality.

## 1.6.3

Email field exists at the top of the form.

![image](https://cloud.githubusercontent.com/assets/1938671/19500873/243727d6-956f-11e6-99e0-fbb80ff5423e.png)


## 1.7

Email field has been moved from the top form to its own meta box.

![image](https://cloud.githubusercontent.com/assets/1938671/19500839/e1d33f42-956e-11e6-83c1-9b5f1a5f55a4.png)

I believe the form validation is still looking for that Email field that is no longer part of the top form.

**Comment by DevinWalker** [comment]
👏  All fixed 🎉
