### ISSUE TITLE
User Integration with Events Calendar

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1133]
## Issue Overview

Our Team received feedback from WordCamp Cincinnatti that users would like closer integration with The Events Calendar.

Because we have a separate table for Give Donors, other plugins like the Events Calendar can't share information easily. It would be nice to be able to have a closer connection with user who register through Events Calendar, and potentially to pay for events with a Give Form as the registration option.

This is most likely Add-on territory, but I think it should have these main features:

1. User activity is shared between both The Event Calendar and the Give Donor screens. So When viewing Give Donor Details, you could toggle a "Events" tab and see events that that specific Donor registered for via Events Calendar.

2. When creating an Event, Admins could choose an existing Give Form to serve as a payment method for registering for an event.

## To-dos
* Research more potential ways these plugins can benefit each other.
* Get feedback from community members on what they'd like to see.
* Put together mock-ups for what the integration might look like.

**Comment by DevinWalker** [comment]
I created an entry in our Give Plugin Add-on ideas spreadsheet. I like this integration idea, but I don't think we need an issue created on the core repo for it.
