### ISSUE TITLE
Change the "Completed Donations" language on the Donor Profile tab of the Donor admin page

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1134]
## Issue Overview

The language is confusing here:

<img width="559" alt="screen shot 2016-10-19 at 10 35 55 am" src="https://cloud.githubusercontent.com/assets/9629102/19523223/dc96dd4e-95e7-11e6-83d8-26a2bbdec995.png">

"Donations" refers to transactions, and what we are tying to do is focus on "Causes," "forms," or something else.

## Current Behavior
Users want to see which forms the donor has completed, but currently they are potentially distracted by the language here.

## Possible Solution
Change the language in customers.php, line 554 (in the 1.7 branch)

**Comment by ramiy** [comment]
@DevinWalker can be closed.
