### ISSUE TITLE
oEmbed of Give Blog Posts on GiveWP.com

### ISSUE THREAD

**Issue by gidgey** [WordImpress/Give#1138]
## Issue Overview

So, an oEmbed should be styled to make it easy for people to navigate to the new post without distracting from the actual post. Our current oEmbed formatting is too long. 

## Expected Behavior

I would expect the oEmbed to include title, featured image, and meta description only.

## Current Behavior

It includes way more including our newsletter signup.

![screen shot 2016-10-19 at 3 34 26 pm](https://cloud.githubusercontent.com/assets/22923622/19540058/d0990394-9611-11e6-99e1-3296ef83e028.png)

## Possible Solution

I have no idea.

## Steps to Reproduce (for bugs)

Not sure.

## Related PRs
List related PRs against other branches:

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
How can I reproduce this?

**Comment by gidgey** [comment]
Just a link to a blog post in a blog post rendered that way.

It's the same way a link to a tweet shows a live preview.

**Comment by DevinWalker** [comment]
Issue moved to [WordImpress/Give-Website #137](https://github.com/WordImpress/Give-Website/issues/137) via [**ZenHub**](https://www.zenhub.com/)
