### ISSUE TITLE
Orphans

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#114]
The question is what is left behind after deactivating and deleting the plugin?
I noticed the donation pages are not removed.

Some plugins have options saying on removal of the plugin also remove the following or something like that. In this case it would be the donation pages, and whatever else that I can not see but might still be there....

**Comment by paaljoachim** [comment]
Another comment. -bug-
As I was going to create a video tutorial I deleted the plugin and then manually deleted the orphan donation pages.

I reinstalled the plugin and no donation pages where added. No donation pages are available.
Which also means that I have to wait with creating the video tutorial. 
O'well it is getting late here anyhow. Let me know when the bug has been fixed.

**Comment by DevinWalker** [comment]
@paaljoachim I've just fixed this bug - thanks for reporting it.

**Comment by paaljoachim** [comment]
Your welcome Devin!
