### ISSUE TITLE
Give form action URL needs escaped differently

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#1146]
## Issue Overview

`give_get_current_page_url()` escapes the return value using `esc_url()`. As a result, the form's `action` attribute receives an escaped version of the URL with encoded ampersands that prevent multiple query parameters from being passed. This is problematic when handling errors and attempting to maintain multiple query parameters after a redirect (see #1130).

There are two points to address here:

1. **Escaping too early** - `give_get_current_page_url()` returns an escaped value. In order to escape as late as possible, we should escape the value when it is displayed in the form template rather than when it is returned by the function.

2. **Wrong escape function** - When outputting the URL in the form's `action` attribute, `esc_url_raw()` should be used instead of `esc_url()`. These two functions encode the `&` character differently.
    - `esc_url_raw()` encodes `&` as `&amp;` which is fine when working with query vars.
    - `esc_url()` encodes `&` as `&#038;` which causes problems with query vars due to the `#`.

## Expected Behavior

All `&` characters in the form's `action` attribute should be encoded as `&amp;`.

`<form id="give-form-31" class="give-form give-form-31 give-form-type-set" action="http://give-core.dev/donations/test-form/?foo=bar&amp;baz=qux&amp;payment-mode=stripe" method="post">`

## Current Behavior

The second `&` is encoded as `&#038;`, which prevents any query parameters that follow from being properly passed in the form action.

`<form id="give-form-31" class="give-form give-form-31 give-form-type-set" action="http://give-core.dev/donations/test-form/?foo=bar&amp;payment-mode=stripe&#038;baz=qux" method="post">`

## Possible Solution

1. Remove `esc_url()` from the return value of `give_get_current_page_url()`.
2. Instead, use `esc_url_raw()` when outputting the value in [`includes/forms/template.php`](https://github.com/WordImpress/Give/blob/release/1.6.3/includes/forms/template.php#L101).

## Steps to Reproduce (for bugs)

1. Visit a Give form URL with at least two custom query parameters (e.g. `/donations/test-form/?foo=bar&baz=qux`).
2. Inspect the form's `action` attribute using Dev Tools.
3. Confirm that `&` has been improperly encoded as `&#038;`.

## Related PRs

In order to resolve #1130 by maintaining multiple query parameters after redirect, we need access to those query parameters. The current escaping does not allow for that to happen.

## Todos
- [x] Before removing the escape function from return value, we should confirm that all uses of `give_get_current_page_url()` in Give core and add-ons are being properly escaped prior to output. @DevinWalker

**Comment by DevinWalker** [comment]
@kevinwhoffman we're in agreement to remove the `esc_url` from the `give_get_current_page_url()` function in favor of late escaping wherever the returned value is output.
