### ISSUE TITLE
Template styles

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#115]
The really nice Give demo uses a template style one is not able to use today.
It would be nice if the templates used for the demo were available for download at the site with an doc explanation on how to use and create templates.

Down the road it might be a good idea to include template styles to the Display Settings section.
Showing a thumbnail of a style. Selecting an default style. Having a way for an individual form to connect with a form template somewhat similar to todays page templates.

Another way...
Today we have the standard WP page templates. No option shows up if there is only one. But when one adds another then the option to select a page template shows up.
Having a folder called templates with one default Give style template one can edit it and save it with another name by doing so the style template will show up in each form.

**Comment by DevinWalker** [comment]
I think we definitely need a style doc explaining how to customize the templates and what not. We don't want to get into styling for YOU the theme admin though. We want Give to flexibly fit into your theme and look good with ease of customization with minor CSS. We also want other theme developers to support Give with basic styles to help it fit.

**Comment by paaljoachim** [comment]
Sounds great Devin.

**Comment by DevinWalker** [comment]
@mathetos put together a nice theming documentation section here: https://givewp.com/documentation/developers/themeing-with-give/

This should suffice until we release the Add-ons allowing for more advanced theme options.

**Comment by mathetos** [comment]
The docs are a good start, but there's functions that control the majority of the markup that need a lot clearer docs still in order to be really usable for users who want advanced customizations to even the single page. It's a work in progress for sure!
