### ISSUE TITLE
PayPal Standard Payment Being Incorrectly Set to Failed

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1152]
## Issue Overview

Many users are reporting that payments accepted through PayPal Standard are being recorded as failed even though, in most reported cases, they succeed.

Here is the relevant thread on WordPress.org: https://wordpress.org/support/topic/payment-status-failed-2/#post-8355587

## Expected Behavior
After the donor returns to the website (the Donation Confirmation page) from making a donation via PayPal Standard they are shown a processing message while the website waits form the IPN confirmaton ping. Once it's received the page refreshes and they are shown the payment is completed. 

## Current Behavior
The page is refreshing and the 

## Possible Causes & Solutions
- Review history of gateway (I made some changes in recent version I need to re-review to see if maybe I inevertiently introducted a bug)
- Process several test transactions on our sandbox site, test live if need be with micro-donations
- Perhaps the IPN request from PayPal has changed or our code changed how we process the message.

... I will post more to this as I find additional information.

## Steps to Reproduce (for bugs)
1. Give Core w/ PayPal Standard activated
2. Process donations
3. Review for failed statuses

## Todos
- [x] Review code
- [ ] Tests
- [ ] Development of fix if bug found

**Comment by DevinWalker** [comment]
## Progress Update 

**Reproducing:** I was able to reproduce when I made a live $1 donation on a customer's website. However, on the Sandbox accounts my payments went through fine.  
 
**Code Review:** I reviewed our past commits on https://github.com/WordImpress/Give/commits/master/includes/gateways/paypal-standard.php and am not seeing any breaking changes. 

**Note:** Donations will fail if the donor changes their mind and hits cancel:

![2016-10-25_22-23-45](https://cloud.githubusercontent.com/assets/1571635/19714309/fd07a0bc-9b01-11e6-9a66-fc22953da5da.gif)

I've asked the customer if she can review the Give Payment Error logs to see if there is anything of note there. I will post another update when I discover more information.

**Comment by pryley** [comment]
I came here looking for this issue...

**Comment by DevinWalker** [comment]
Thanks @pryley that's useful, I'm going to track it down.

**Comment by pryley** [comment]
Also no IPN Errors are found on the PayPal account, so it doesn't look like an issue with PayPal.

![image](https://cloud.githubusercontent.com/assets/134939/19736557/c3eb9d7a-9b7d-11e6-9d98-de490e8f5a00.png)

**Comment by DevinWalker** [comment]
More helpful information from a savvy customer:

>I've confirmed that the IPN message from PayPal does not contain the md5 "InvoiceID" when being sent to PayPal in these broken transactions. This doesn't happen with all transactions, yet it does with a significant number of them. I've begun doing a review of the Give source code to see if I can identify what may be the issue.

**Comment by DevinWalker** [comment]
## Progress Update

1. PayPal Standard set to accept *Donations*: 
![2016-10-26_11-46-19](https://cloud.githubusercontent.com/assets/1571635/19739971/c7156154-9b71-11e6-9147-13ab36515fcd.png)

- I just ran a transaction through confirmed that my IPN response contains no `invoice` variable in the array. This means our check: https://github.com/WordImpress/Give/blob/master/includes/gateways/paypal-standard.php#L462 will fail every time this value is not present.

2. PayPal Standard set to accept *Standard Transactions*:
![2016-10-26_11-47-37](https://cloud.githubusercontent.com/assets/1571635/19740022/f6d11b04-9b71-11e6-9c59-29ad5276f49e.png)

- My IPN history contains *does* container a the `invoice` parameter and does not fail.

---

It appears that now donations send through PayPal standard do NOT contain the pass-through `invoice` variable as documented here https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNandPDTVariables/ 

![2016-10-26_11-50-12](https://cloud.githubusercontent.com/assets/1571635/19740102/4ec49fa2-9b72-11e6-8e57-dc4e743cfd23.png)

Note that there is not mentioned that it is not sent through when sending donation payments through...

## Suggestions

**Option A:** We simply remove this conditional check: https://github.com/WordImpress/Give/blob/master/includes/gateways/paypal-standard.php#L282 
*Considerations:*
- the IPN has already been verified here unless the user disabled the option
- we already verify the payment matches 

**Option B:** We check if the user has set to "Donations" or "Standard Transactions" - if the latter we proceed with the check, if "Donations" we skip the additional check.
*Considerations:*
- Possibly can run into future complications with the `invoice` parameter
- Less stringent verification checks prior to payment completion

@pryley @kevinwhoffman what do you think?

**Comment by pryley** [comment]
Yeah, you should need to verify the `invoice` data key if the transaction is a donation. Also at this point the IPN has already been verified, so further checks are only needed to determine the payment status.

**Comment by DevinWalker** [comment]
If the
