### ISSUE TITLE
Import/Export

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#116]
As one creates forms, modifies pages and template styles etc etc. It would be good to have a way to export all of it and then import it to another site. It would also be a way to back up all the data.

**Comment by DevinWalker** [comment]
@paaljoachim have you tested the WordPress Importer/Exporter? It works very nicely to import and export forms.

**Comment by paaljoachim** [comment]
I have, but not lately. I will keep that in the back of my mind and test it out with Give at some stage.

**Comment by DevinWalker** [comment]
I've tested and it brings over all fields expected. I'm adding docs to the site right now.

**Comment by paaljoachim** [comment]
Great. If you can add a comment in the issues I made with a link to the docs when they are in place that would be great.

**Comment by DevinWalker** [comment]
Here's the import/export one: https://givewp.com/documentation/core/give-forms/importing-and-exporting-forms/

**Comment by paaljoachim** [comment]
Looks good Devin!
That takes care of the donation forms.

Down the road one might want to export Transactions and Reports and whatever else..:)
