### ISSUE TITLE
Add support for CMB2 custom fields

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1166]
## Issue Overview

When I was doing work on Zapier and Recurring I noticed our nice welcome texts are missing in the setting tabs:

**Branch 1.7:** Nice welcomes :)

![2016-10-27_17-26-19](https://cloud.githubusercontent.com/assets/1571635/19790115/6960f79a-9c6a-11e6-9d55-88b5f42e4654.png)
![2016-10-27_17-26-10](https://cloud.githubusercontent.com/assets/1571635/19790116/6aff5b28-9c6a-11e6-92f1-b009c1fe1878.png)

**Branch 1.8:** No welcomes :(

![2016-10-27_17-18-02](https://cloud.githubusercontent.com/assets/1571635/19790091/37a2785a-9c6a-11e6-8b57-3b72aab2baa7.png)
![2016-10-27_17-17-53](https://cloud.githubusercontent.com/assets/1571635/19790092/396c1146-9c6a-11e6-9e46-4d6be6efff01.png)

**Comment by DevinWalker** [comment]
@ravinderk I know  you're not able to reproduce...from debugging I was able to narrow it down to `get_filtered_addon_settings`: https://github.com/WordImpress/Give/blob/release/1.8/includes/admin/settings/class-settings-cmb2-backward-compatibility.php#L259

When the `$settings` for in the fields look OK, but then nothing is output. I'd like to dig into why this is happening for Zapier. I can't find any difference between the other Add-ons in how it registers it's settings.

**Comment by ravinderk** [comment]
@DevinWalker  CMB2 backward compatibility breaks because WordPress updated there hook system.
For ref: https://make.wordpress.org/core/2016/09/08/wp_hook-next-generation-actions-and-filters/

**Comment by DevinWalker** [comment]
@ravinderk it's still not working for me :( 

![2016-12-07_10-51-49](https://cloud.githubusercontent.com/assets/1571635/20981886/2a6f1690-bc6b-11e6-9fe1-1c1a9366a990.png)

**Comment by DevinWalker** [comment]
I just reviewed again and my Add-on settings pages appear working nicely albeit minor CSS that needs to be addressed with Zapier:

![2016-12-28_20-14-39](https://cloud.githubusercontent.com/assets/1571635/21536653/47ea3116-cd3a-11e6-9707-778ce40483fd.png)

Closing.

**Comment by DevinWalker** [comment]
@mathetos I'm seeing this when I click on the doc links:

![2016-12-28_21-56-12](https://cloud.githubusercontent.com/assets/1571635/21537592/907de1b2-cd48-11e6-97d8-112398dca176.png)
