### ISSUE TITLE
Jetpack style for activating addons?

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#117]
Hey

One thing that is neat about Jetpack is all the functions built into it.
One just activates one plugin and looks through the list and selects which function to activate.

It would be nice if one could click an addon purchase it and go back to the site and see a activated addon text below the addon image. This way one can see which addons one has activated. This is a feature I really would like to see various other plugins use as well. Especially Ninja Forms. 

Nice and clean. See an addon one would like to know more about. Click and a new tab opens to give info on the addon. Click purchase and create an account. Link the e-mail to the account. Select the first tab and the page is automatically refreshed (or the user refreshes the page) The word activated is now listed below the addon image. Seems like a good and simple way to purchase an addon. (Perhaps not as easy to code but that is another matter..)

**Comment by DevinWalker** [comment]
That would be nice I agree. I believe WordPress.org doesn't allow "dormant" code to sit in the plugin until it's activated. I'm not sure how JetPack does this, I think a lot of the code communicated with outside APIs, but am not entirely possible. Thanks for the suggestion, it's a good one, and eventually we may shift in this direction. For now, I'm going to close this out but will keep it in mind. :+1:
