### ISSUE TITLE
Inconsistent naming of class-setting-system-info.php

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#1173]
## Issue Overview

In Give `1.8.0`...

`class-setting-system-info.php` should be `class-settings-system-info.php` for consistency.

![image](https://cloud.githubusercontent.com/assets/1938671/19823075/bf757bae-9d34-11e6-815c-47704a90d3fc.png)

**Comment by DevinWalker** [comment]
I see this is fixed now... closing.
