### ISSUE TITLE
Refactor Income Reports to be DRYer

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#1174]
## Issue Overview

Between Give core and the Recurring Donations add-on, the same Income Report is used in three different scenarios. The problem is that the template and logic for these reports are defined three different times, and much of that code is redundant.

The three scenarios are:
- Income Report (Give core)
  - Location: `wp-admin/edit.php?post_type=give_forms&page=give-reports`
  - Function: `give_reports_graph()`
- Detailed Income Report (Give core)
  - Location: `/wp-admin/edit.php?post_type=give_forms&page=give-reports&tab=forms&form-id={FORM_ID_GOES_HERE}`
  - Function: `give_reports_graph_of_form()`
- Renewal Donations Report (Recurring Donations add-on)
  - Location: `/wp-admin/edit.php?post_type=give_forms&page=give-reports&tab=subscriptions`
  - Function:  `display_subscriptions_report()`

Note the changes to Income Report formatting in Give `1.8.0`. Any refactoring should reflect the formatting from `1.8.0` which is pictured below:

![1114-income-custom-after-2](https://cloud.githubusercontent.com/assets/1938671/19787253/d1e3d152-9c6f-11e6-943a-fe89c5db0346.jpg)
## Expected Behavior

Any change in formatting should be reflected across all three scenarios.
## Current Behavior

Any change in formatting must be made in three different locations across Give core and the Recurring Donations add-on. If developer doesn't have prior knowledge of the three scenarios, it's easy for inconsistencies in formatting to appear.
## Possible Solution

Determine what is uniquely required by each report and what stays the same. Perhaps define a class in Give core that can be extended in the Recurring Donations add-on, so the same report can be used with a few tweaks.
## Related

https://github.com/WordImpress/Give/pull/1162#issuecomment-256844697
## Todos
- [ ] Determine the unique requirements of each type of Income Report.
- [ ] Refactor to put the base functionality in Give core, but make it extensible by add-ons.

**Comment by DevinWalker** [comment]
Because of the future direction we're taking the reports section I would like to limit time spent refactoring the current implementation like we discussed. Thus, I'm going to close this issue out and open an issue for the future reports improvements.
