### ISSUE TITLE
a11y: fieldset hierarchy

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#1181]
## Issue Overview

The `<fieldset>` hierarchy in the donation form needs some love.

See the the screenshots and the proposed solution.

## Current Behavior

![screenshot 2016-10-31 09 49 07](https://cloud.githubusercontent.com/assets/576623/19847437/87576490-9f4f-11e6-8593-8a079cf3783c.png)

## Expected Behavior

![screenshot 2016-10-31 09 51 17](https://cloud.githubusercontent.com/assets/576623/19847470/c8b210ac-9f4f-11e6-9936-9be44fb5080e.png)

## Why that happens?

The `give_terms_agreement()` function, which displays terms agreement fields, hooks to the wrong action.

## Possible Solution

Replace this:

`add_action( 'give_donation_form_before_submit', 'give_terms_agreement', 10, 1 );`

With that:

`add_action( 'give_donation_form_after_cc_form', 'give_terms_agreement', 8888, 1 );`

**Why this Solution?**

Because we already use this action to display the "Checkout Submit" section with:

`add_action( 'give_donation_form_after_cc_form', 'give_checkout_submit', 9999 );`

This way, both sections use the same action hook but with different priority. Terms will use 8888, and the checkout will use 9999. This way we control the location of each item on the form.

**Comment by DevinWalker** [comment]
Yes, cleaning up the DOM like this is important. 👍
