### ISSUE TITLE
CLI Improvement: Export Donor List in Machine Readable Format

### ISSUE THREAD

**Issue by shawnhooper** [WordImpress/Give#1191]
## Issue Overview

The tabular format used for listing donors in the CLI integration isn't useful for much other than looking through the list with human eyes.  Exporting this data in a machine-readable format would be great!

## Expected Behavior

Being able to specify that you want the donor list exported in a machine-readable format.

## Current Behavior

Only a tabular format is available.

## Possible Solution

Adding a --format parameter to the donors command where you could specify the format you would like the data listed in.  Example:

`wp give donors --format=table` (default)
`wp give donors --format=csv` (comma-separated list)
`wp give donors --format=tab` (tab-separated list)
`wp give donors --format=json` (JSON string)

**Comment by ravinderk** [comment]
@shawnhooper what is `--format=tab`?
Can you explain more?
