### ISSUE TITLE
CLI Improvement: id parameter on report command unclear

### ISSUE THREAD

**Issue by shawnhooper** [WordImpress/Give#1192]
## Issue Overview

Without reading the help documentation, you may expect that the `--id` parameter on the `report` CLI command refers to a report ID (which isn't a thing). 

## Possible Solution

Rename the `--id` parameter to `--form-id` for clarity.

**Comment by DevinWalker** [comment]
Resolved via PR https://github.com/WordImpress/Give/pull/1202 merge
