### ISSUE TITLE
Dollar sign in modal doesn't always work

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#120]
Kind of hard to describe how this happens, but basically, if you click "Donate Now" the dollar sign appears in the total amount field no problem. But if you close the modal, pick a different amount and hit "Donate Now" again, you'll see "USD" instead of the dollar sign in the total amount inside the modal.

Here's a screencast showing the problem
http://screencast-o-matic.com/watch/cofOeufV9F

I also tested it by turning "Custom Amount" off, and it still did that. So it seems related to closing the modal and re-opening it.

**Comment by DevinWalker** [comment]
@mathetos how to did you get the "USD" to display? It should show the currency symbol, not the value, which is how the plugin prefixes the amount.

**Comment by mathetos** [comment]
I didn't attempt to have USD appear, it simply did. This is a live environment (though currently only accessible via IP address). This was a new Give installation, no Add-ons enabled. We can take a look together.

**Comment by mathetos** [comment]
Looks like this is related to not having a default set for the Currency settings. Once I went and saved the Settings page, the issue went away.
