### ISSUE TITLE
PayPal Standard Donation/Payment and Test/Live very different experiences all together

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1204]
Occasionally Give users report that their donors can't use PayPal with a normal credit card. When they get routed to the PayPal.com page, it simply doesn't provide them the link to choose "Pay with Credit Card", it only gives them the ability to pay with a PayPal account or Register for one.

I haven't been able to replicate that issue. But today another user reported that he couldn't get his PayPal custom landing page to work be applied correctly. So I tested that. It turns out that changing donation/payment and testmode/livemode in Give results in 4 different PayPal Standard experiences.

Here's what I just tested with URL's and screenshots. Keep in mind that all of these were with my personal PayPal account. NOTHING changed between tests except the settings. All were triggered from the same Give form with the same donor information and donation amount.

### Donation Payment 
https://www.sandbox.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION={deletedthisforsecurity}&dispatch=5885d80a13c0db1f8e263663d3faee8d333dc9aadeed3fe0b5b299d55fd35542
![paypal-testing-donations-landingpage](https://cloud.githubusercontent.com/assets/930724/19952415/4aeae714-a122-11e6-8e51-6bbf00ba3968.png)

### Standard Payment:
https://www.sandbox.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION={deletedthisforsecurity}&dispatch=50a222a57771920b6a3d7b606239e4d529b525e0b7e69bf0224adecfb0124e9b61f737ba21b0819862118003bc2f4b4f47f01ef0a11094f0
![paypal-testing-standard-landingpage](https://cloud.githubusercontent.com/assets/930724/19952417/4ed51afc-a122-11e6-84df-b230fb196377.png)

### Donation Payment
https://www.paypal.com/donate/?token={deletedthisforsecurity}

![paypal-live-donation-landingpage](https://cloud.githubusercontent.com/assets/930724/19952421/54665198-a122-11e6-971a-513f3864f47a.png)

### Standard Payment 
https://www.paypal.com/webapps/hermes?token={deletedthisforsecurity}&useraction=commit&rm=2&xclick_params=JTI2UERUJTNEdHJ1ZSUyNiUyNkF1dG9SZXR1cm4lM0R0cnVlJTI2JTI2SVBOJTNEdHJ1ZSUyNmxvZ2luX2VtYWlsJTNEc2FsZXMlMjU0MHdvcmRpbXByZXNzLmNvbSUyNmJ1c2luZXNzJTNEcmVhY2htZSUyNTQwbWF0dGNyb213ZWxsLmNvbSUyNmZpcnN0X25hbWUlM0RNYXR0JTI2bGFzdF9uYW1lJTNEQ3JvbXdlbGwlMjZlbWFpbCUzRG1hdHQlMjU0MHdvcmRpbXByZXNzLmNvbSUyNmludm9pY2UlM0Q2MTliODUzOGNjMWMzNzc2NjIyYmIzZGYwYjk2YzA5MCUyNmFtb3VudCUzRDI1JTI2aXRlbV9uYW1lJTNEVGl0bGUlMjZub19zaGlwcGluZyUzRDElMjZzaGlwcGluZyUzRDAlMjZub19ub3RlJTNEMSUyNmN1cnJlbmN5X2NvZGUlM0RVU0QlMjZjaGFyc2V0JTNEVVRGLTglMjZjdXN0b20lM0Q1NDkwJTI2cm0lM0QyJTI2cmV0dXJuJTNEaHR0cCUyNTNhJTJGJTJGZ2l2ZXBsdWdpbi5kZXYlMkZkb25hdGlvbi1jb25maXJtYXRpb24lMkYlMjUzZnBheW1lbnQtY29uZmlybWF0aW9uJTI1M2RwYXlwYWwlMjUyNnBheW1lbnQtaWQlMjUzZDU0OTAlMjZjYW5jZWxfcmV0dXJuJTNEaHR0cCUyNTNhJTJGJTJGZ2l2ZXBsdWdpbi5kZXYlMkZ0cmFuc2FjdGlvbi1mYWlsZWQlMkYlMjUzZnBheW1lbnQtaWQlMjUzZDU0OTAlMjZub3RpZnlfdXJsJTNEaHR0cCUyNTNhJTJGJTJGZ2l2ZXBsdWdpbi5kZXYlMkZpbmRleC5waHAlMjUzZmdpdmUtbGlzdGVuZXIlMjUzZElQTiUyNnBhZ2Vfc3R5bGUlM0REb25hdGlvbnMlMjZjYnQlM0RHaXZlJTI1MjBQbHVnaW4lMjUyMERldiUyNmJuJTNEZ2l2ZXdwX1NQJTI2JTI2d2FfdHlwZSUzREJ1eU5vdyUyNg==&mfid=1478132791258_6ebddda7b89e2#/checkout/login
![paypal-live-standard-landingpage](https://cloud.githubusercontent.com/assets/930724/19952423/5895c974-a122-11e6-9759-b113ed3e3b59.png)

## What to Do About It?

Naturally, we can just say "Well, this is PayPal... they're weird". But it seems like there must be something we can do to keep the user experience consistent, or to know what they should expect when they make settings changes. 

At minimum, we need to know why when the settings are set to Donation/Test Mode there are NO options to pay with a credit card.

**Comment by mathetos** [comment]
You'll also note that you see the WordImpress logo and a banner pic from my personal website. I chose both of those in my custom PayPal payment template, one as a logo and one as a background. It's interesting that they never appear at the same time, only either one or the other.

**Comment by DevinWalker** [comment]
So it sounds like the "PayPal Page Style" doesn't have any issue except that PayPal handles it differently between donations and standard transaction? 

I've looked into this a bit on why some PP accounts can accept credit cards and others cant. Here's a few findings:

1. Your account must be either Premier or Business.  Personal type accounts do not have this option.
2. PayPal Account Optional (a setting in your account) is turned on - this enables non-PayPal members to pay by Credit Card.
3. The email address you use to log into your PayPal Account must be verified.
4. Bank Account linked and verified.
5. Credit Card linked and verified.

Sources: 
https://www.j2store.org/blog/j2store/why-paypal-is-not-showing-credit-card-option-sometimes.html
https://www.paypal-community.com/t5/Merchant-services-Archive/Payment-Standard-no-credit-card-option/td-p/390490

As far as standardizing the experience of test/live standard/donation - we can't do much about it. Their sandbox sometimes actually shows the updated UI as well depending on the age of the account. However, it's terribly buggy. Thankfully the live site is pretty reliable albeit wonky in the various UIs. Don't forget that PayPal Express has a different UI as well... 😕
