### ISSUE TITLE
New User email producing issues. 

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1215]
## Issue Overview

New User email is plaintext, or otherwise broken. 

## Expected Behavior

It should either send a full html email, or not include html tags. 

## Current Behavior
When a new user is sent an email, the function here is broken. 
https://github.com/WordImpress/Give/blob/master/includes/user-functions.php#L405-L446

specifically the error appears to be in this line:
https://github.com/WordImpress/Give/blob/master/includes/user-functions.php#L434

Here's a user screenshot of this error: 
![screen-shot](https://cloud.githubusercontent.com/assets/9629102/20160512/645d651c-a6b5-11e6-9d52-ad2e0a76e8b6.png)

I was able to reproduce locally. Here's a screenshot
![screen shot 2016-11-09 at 7 36 05 pm](https://cloud.githubusercontent.com/assets/9629102/20160531/8b9cf6ec-a6b5-11e6-9d22-07d3a3dc55be.png)

and here's the source from mailcatcher:

```
Password: [Password entered during donation]
<a href=3D"https://givepress.dev/wp-login.php"> Click Here to Login &raqu=
o;</a>
```

## Steps to Reproduce (for bugs)
1. Ensure that new user registration is required (disable logged out donations)
2. complete a donation
3. check the email that is sent

It will be broken.

**Comment by DevinWalker** [comment]
Close in favor of: https://github.com/WordImpress/Give/issues/1346
