### ISSUE TITLE
Changing a payment's donation form breaks in 1.7+

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1220]
## Issue Overview
When you switch a donation's payment form in 1.7+ the change isn't saving properly.

## Expected Behavior
The donation form is set properly once saved.

## Current Behavior
Current release is working:
![2016-11-10_13-51-16](https://cloud.githubusercontent.com/assets/1571635/20195763/b1b992c6-a74c-11e6-8b6c-736e3c27f5ee.gif)

`release/1.7` branch - notice the ID isn't updated and the donation level (if applicable) doesn't save:

![2016-11-10_13-54-02](https://cloud.githubusercontent.com/assets/1571635/20195865/0a63d9ae-a74d-11e6-97a2-73d23011f312.gif)

## Steps to Reproduce (for bugs)
1. Checkout `release/1.7`
2. Go to an existing donation
3. Change the donation form 
4. Save

## Related PRs
List related PRs against other branches: https://github.com/WordImpress/Give/issues/429

## Todos
- [x] Review bug
- [x] Fix bug
- [ ] Test fix
- [ ] Submit PR

**Comment by DevinWalker** [comment]
This is nearly fixed. The last issue is when you change to a multi-level form with no level text:

![2016-11-14_19-06-24](https://cloud.githubusercontent.com/assets/1571635/20291786/86c5720c-aa9d-11e6-8ad1-9d17be2ae3f8.png)

The dropdown on the payment's form level doesn't appear properly:

![2016-11-14_20-26-02](https://cloud.githubusercontent.com/assets/1571635/20293143/93c106f0-aaa8-11e6-8b98-24a46cbe99d5.png)

**Comment by ravinderk** [comment]
@DevinWalker If a level text does not exist then can we show the amount in place of text? can you suggest me default title

**Comment by DevinWalker** [comment]
yeah show the amount rather
