### ISSUE TITLE
Add shortcode to display set of donation forms

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1230]
## Issue Overview

We should include a shortcode as described here: https://wordpress.org/support/topic/campaign-shortcode/

## Shortcode Explanation
I propose the `[give_forms]` shortcode which will display all donations forms. Then we provide attributes to filter by `IDs` such as `[give_forms ids="254,213,123"]` will output only those forms. It should also support pagination: `[give_forms paginate="10"]` which will show 10 forms at a time with the ability to switch through them.

**Comment by mathetos** [comment]
Would be great for it to work like so as well:

`[give_forms cat="id_or_slug" tax="id_or_slug"]`

Which would show the forms only in that specific category or taxonomy or even combo of both.

**Comment by mathetos** [comment]
We're going to close this in favor of https://github.com/WordImpress/Give/issues/1414
