### ISSUE TITLE
Add Google analytics ecommerce tracking code to donation confirmation page

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1238]
## Issue Overview

Customer request, to add a way to track donations in Google analytics

## Expected Behavior

When a donation is submitted, the pertinent information can be passed along to Google analytics ecommerce tracking.

## Current Behavior
Nothing happens currently.

## Possible Solution
See this snippet, essentially forked from https://wordpress.org/plugins/edd-google-analytics-universal-ecommerce/

https://github.com/WordImpress/Give-Snippet-Library/blob/master/useful-queries/add-google-analytics-ecommerce-tracking.php

Note that GA tracking code has to already be installed by some other means, and before this code.

This may work better as an add-on, but it could also be added to Core.

## Related 
https://developers.google.com/analytics/devguides/collection/analyticsjs/ecommerce

**Comment by DevinWalker** [comment]
Love this as a free plugin. I've created a repo for it here: https://github.com/WordImpress/Give-Google-Analytics-Ecommerce-Tracking

Let's put this bad boy on WP.org 👍
