### ISSUE TITLE
Offline Donation donation amount tag not displaying properly

### ISSUE THREAD

**Issue by tleifj** [WordImpress/Give#1247]
## Issue Overview

In the Offline Donation Instruction email, the {donation} tag isn't displaying properly

## Expected Behavior
I would expect the donation amount to be the amount selected or entered on the form. Ex: "Thank you for committing to a $50.00 offline donation!"

## Current Behavior
In the Offline Donation Instruction email, the {donation} tag has a "-" in front of the amount. When a donor chooses "Other" on a multi-select form, it doesn't show the custom amount, but instead "Other". Ex: (choosing a set donation amount) "Thank you for committing to a **-** $50.00 offline donation!"  Ex: (choosing "Other" and entering custom donation amount) "Thank you for committing to a **- Other** offline donation!" Is the "-" there to show that they still owe the donation? A client of ours brought this up because they think it doesn't look right. 

## Steps to Reproduce (for bugs)
1. Set up multi-select donation form with an Other option and the ability to make an offline donation
2. Include the {donation} tag in the instruction email template
3. Make a donation selecting an amount or choosing other and entering a custom amount
4. View Instructions email

**Comment by DevinWalker** [comment]
Hey @tleifj which version of Give are you using? `1.6.4`?

We recently resolved a bug with the `{donation}` email tag https://github.com/WordImpress/Give/pull/1209 which was released in the latest version. I just tested it out again and it's working on my end (I don't see a "-" in front of the amount). Does your donation form have a name? If not, then you will see a "-" in front without any form name. 

Essentially, the donation tag works by pulling first the form title, followed by the level chosen (if multi-level). For instance, "Save the Whales - Small Contribution". If the level does not have text, it will display the amount: "Save the Whales - $5.00". 

There is also a `{form_title}` tag which will only pull the title of the donation form used regardless of whether it's multilevel or not.

**Comment by tleifj** [comment]
@DevinWalker Great! I wasn't on the latest version and it looks better now. Any plan to have the "Other" amount be displayed in the offline email rather than just saying "Form Title - Other"?

**Comment by DevinWalker** [comment]
I think it's fine that it say "Save the Whales - Custom Amount" because then below you can use the `{amount}` tag to display that somewhere. You could also use `{form_title} - {amount}`.

You do uncover an interesting bug: if the donation form does not have a title:

![2016-11-16_20-15-17](https://cloud.githubusercontent.com/assets/1571635/20376719/0e7c3a54-ac3e-11e6-94aa-85add695d747.png)

Then it displays the `- $5.00` like you mentioned:

![2016-11-16_20-12-50](https://cloud.githubusercontent.com/assets/1571635/20376720/109b6b52-ac3e-11e6-8112-d4a04d1098db.png)

Rather, it should simply output the level without the ` - ` hyphen.

**Comment by DevinWalker** [comment]
@ravinderk says he's still noticing issues with this after my updates. I'm reopening until him and I touch base on it.
