### ISSUE TITLE
Add Download option as DEFAULT for System Info

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1260]
## Issue Overview
Our new implementation of the System Info tab is awesome!

Hattip to @kevinwhoffman 

But the workflow for our Support really encourages users to ATTACH the system info rather than paste it into the ticket. 

Currently we only have the copy/paste method. I'd really prefer to have a Download as the Primary option, and the copy/paste as secondary.

![image](https://cloud.githubusercontent.com/assets/930724/20413570/861aa2a4-ace2-11e6-9119-1484a6286da5.png)

## Related PRs
https://github.com/WordImpress/Give/pull/1214

**Comment by DevinWalker** [comment]
@mathetos what's the update on this? Are we going the route to convert a text area to .txt outside the plugin or also keeping the download functionality within the plugin?

**Comment by mathetos** [comment]
Based on the code @Shelob9 provided I think we can safely keep it as copy/paste only and convert the Support form textarea to a .txt file attachment. That really is the best of both worlds since copy/paste is much more intuitive for customers.

Thanks!
