### ISSUE TITLE
Add display settings to widget

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1269]
## Issue Overview
Like `give_form` shortcode, can we add display setting to widget code also.
<img width="487" alt="screen shot 2016-11-21 at 4 34 00 pm" src="https://cloud.githubusercontent.com/assets/1784821/20480423/749c5300-b008-11e6-8456-89aa5571f5e6.png">

**Comment by DevinWalker** [comment]
Good call, let's do it.
