### ISSUE TITLE
Give Compatibility with WPML

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1271]
## Issue Overview

According to a customer, Give has compatibility issues with WPML.

## Ticket: 
https://secure.helpscout.net/conversation/268508268/4234/?folderId=672197

## Details from the ticket:

Customer is having issues with WPML (various, like forms that are supposed be the same, but are not displaying correctly, especially totals, and add-on translations not showing up correctly), and reached out to their support, who say that there is a conflict with WPML and Give. The go-global team here is their proposed solution: https://wpml.org/documentation/theme-compatibility/go-global-program

**Comment by DevinWalker** [comment]
I have been in contact with the WPML team and they have spun up a site for us to check compatibility here: 

- English: http://give.compatibility.wpml.org/donations/save-the-rain-forest/
- Serbian: http://give.compatibility.wpml.org/sr/donations/save-the-rain-forest/

You can see the prefix of `[sr]` and `[serbian]` throughout the donation forms and shortcodes means that the plugin Core is indeed compatible with WPML. 

We are currently working to test compatibility with Recurring and Form Field Manager re #1283
