### ISSUE TITLE
Better support Multilanguage sites.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1283]
## Issue Overview

Currently strings like the labels for multilevel forms, which are entered by users, are not available for tools like WPML to translate. This means that while everything else on the form is translated based on WPML's settings, the user-entered strings are not. 

## Expected Behavior
One would expect that a string entered on the Form Settings would be available via the .po file or some other method for translating. 

## Current Behavior
Currently the string is just entered as a text string, and not using a translation function like  `__()`, and further, the text is generated far after all translation functions have run.

## Possible Solution
Since (at least in the case of the multilevel labels) the string is filtered using `give_form_level_text`, it may be possible to write a custom function utilizing that filter that stores the strings in a translatable way before delivering them to the core plugin( in the same way `wp_localize_script()` is used for JS translation) We could write a snippet for users who need this, if we aren't able to add the functionality to the core plugin. This could also be an add-on that is very attractive to multinational charities.

## Strings that need this support
1. multilevel labels
1. "Complete Donation" text (if it has been modified on the back end of the form)
1. "agree to terms" label (if it has been modified)
2. form field manager labels and other third party add-on labels form the front end.

## Todos
- [ ] Tests
- [ ] Documentation/custom snippet in the library

**Comment by DevinWalker** [comment]
Closing this as this will be part of the form revamp!
