### ISSUE TITLE
Add the ability to accept "pledges"

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1284]
## Issue Overview

Customer wants the ability to add pledges, where a donor commits to giving a certain amount, and then is reminded periodically to give. 

## Expected Behavior

It could piggyback off of offline donations, and instead of instructions for mailing, you could populate a form with reminder frequency, and then the reminder email would have a custom link back to the form that prepopulates the amount pledged, and only be sent when the donor specifies.

## Possible Solution

This would most likely work best as an add-on.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
This is a great idea for an Add-on. Check out what Wikipedia is doing: 

![2016-12-01_14-04-47](https://cloud.githubusercontent.com/assets/1571635/20808266/ec6e5f6c-b7cf-11e6-8eba-94f86d7b11e5.gif)

**Comment by DevinWalker** [comment]
New repo: https://github.com/WordImpress/Give-Pledges
