### ISSUE TITLE
Give Logs getting disconnected from their parent forms

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1286]
## Issue Overview
A [user reported](https://secure.helpscout.net/conversation/279736714/4634/?folderId=672197) that their goals were not updating, even when using all of our Tools. The form is a multi-level form. 

Looking at the "All Donations" Log showed that many of her donations were not being connected to their corresponding form, even though it showed correctly in the Transactions Details screen:

**Transactions Details Screen shows correctly**
![image](https://cloud.githubusercontent.com/assets/930724/20726464/9664ce5e-b62a-11e6-8c32-57b9100138e2.png)

**Same Transaction on the LOG shows NO Form**
![image](https://cloud.githubusercontent.com/assets/930724/20726434/6d06b1da-b62a-11e6-84fb-a9e5686c3804.png)

**Important Part**
A careful look into the Database showed that in `wp_posts` the affected `give_log` entries showed a `post_parent` of `0`. Manually changing that to `40` (the Donation Form ID) updated the Log correctly, but the donation total and progress for that form were still off. Running the Tools at that point resolved the issue completely. 

This suggests that somehow those transactions didn't record their `post_parent` correctly which had a cascading effect resulting in the donation totals and progress amount always being irrevocably wrong.

## Expected Behavior
All transactions should be connected to their appropriate donation form (via the `post_parent` id) and reflect the correct form in order to properly update the Goal progress.

## Possible Solution
I haven't been able to reproduce this behavior anywhere reliably. I have a feeling this has to do with updating from older versions of Give Core and the original form perhaps was buggy. All of the affected donations happened in September and older. That coincides with releasing Give 1.6 (roughly) which addressed many issues with transactions and how they are tied to forms. 

It's possible that this is resolved, but I think it's worth digging into the logic of how transactions are tied to their forms and "prices". Specifically if we can improve our Tools to account for a problem like this and correctly attach the donation at the LOG level, not just the transaction level.

**Comment by ravinderk** [comment]
@WordImpress/support I already reported a similar bug here: #1227. Please take a look.

**Comment by mathetos** [comment]
Thanks @ravinderk That does look very similar and when @DevinWalker and I chatted the other day we came to a similar conclusion that logs shouldn't be separated from payments. 

I'll leave this open for now in case in testing we find that there's multiple issues happening.
