### ISSUE TITLE
Deleting Test Transactions doesn't delete Donor or Subscription posts, and deletes un-related Pages

### ISSUE THREAD

**Issue by tleifj** [WordImpress/Give#1293]
## Issue Overview

Deleting test transactions under Reports > Tools doesn't delete all test data and instead deletes other non-Give data

## Expected Behavior
When selecting Delete All Test Transactions, I expect it to delete Transactions, Donors, and Subscriptions
## Current Behavior
Deletes Transactions, but not Donors or Subscriptions. Also Deleted 6 pages unrelated to Give (like the homepage :/)

## Steps to Reproduce (for bugs)

1. Enter Test Transactions
2. Go to Donations > Reports > Tools
3. Select Delete All Test Transactions
Note: Test Mode is still Active when I did this. Also retried three times with same results

**Comment by mathetos** [comment]
Hi @tleifj thanks for reporting this. I'm unable to replicate it though. Can you provide your System Info by going to "Donations > Settings > System Info"?

**Comment by tleifj** [comment]
Sure thing. Also, I should mentioned that I tried doing this after I migrated a site to a new server.

### Begin System Info ###

-- Site Info

Site URL:                 http://www.sv2.org
Home URL:                 http://www.sv2.org
Multisite:                No

-- Hosting Provider

Host:                     DBH: localhost, SRV: www.sv2.org

-- User Browser

Platform:                 Apple 
Browser Name:             Chrome  
Browser Version:          54.0.2840.98 
User Agent String:        Mozilla/5.0 (Macintosh; Intel Ma 
			  c OS X 10_12_1) AppleWebKit/537.
                          36 (KHTML, like Gecko) Chrome/54
                          .0.2840.98 Safari/537.36
                          
-- WordPress Configuration

Version:                  4.6.1
Language:                 en_US
Permalink Structure:      /%postname%/
Active Theme:             Silicon Valley Social Venture Fund 1.0
Show On Front:            page
Page On Front:             (#3)
Page For Posts:           Unset
Remote Post:              wp_remote_post() works
Table Prefix:             Length: 3   Status: Acceptable
Admin AJAX:               Inaccessible
WP_DEBUG:                 Disabled
Memory Limit:             40M
Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit, acf-disabled, refunded, failed, revoked, cancelled, abandoned, preapproval, give_subscription

-- Give Configuration

Version:                  1.6.4
Upgraded From:            1.6.4
Test Mode:                Enabled
Currency Code:            USD
Currency Position:        before
Decimal Separator:        .
Thousands Separator:      ,

-- Give Page Configuration

Success Page:             http://www.sv2.org/get-involved/donate/donation-confirmation/
Failure Page:             http://www.sv2.org/get-involved/donate/transaction-failed/
Give Forms Slug:           /donations

-- Give Gateway Configuration

Enabled Gateways:         Stripe - Credit Card, PayPal Standard, Offline Donation
Default Gateway:          Stripe - Credit Card

-- Must-Use Plugins


-- WordPress Active Plugins

Advanced Custom Fields PRO: 5.5.0
All-in-One WP Migration: 5.55
Breadcrumb NavXT: 5.5.2
Custom Post Type UI: 1.4.3
Duplicate Post: 3.0.3
Easy Updates Manager: 6.2.5
Enable Media Replace: 3.0.5
EWWW Image Optimizer: 3.1.3
Give - Donation Plugin: 1.6.4
Give - Form Field Manager: 1.1.1
Give - Recurring Donations: 1.2.2
Give - Stripe Gateway: 1.4.1
Google Analytics Dashboard for WP: 4.9.3.2
Gravity Forms: 2.1.1
Gravity Forms Salesforce Add-On: 3.1.2
Imsanity: 2.3.6
Intuitive Custom Post Order: 3.0.7
iThemes Security Pro: 3.2.0
MainWP Child: 3.2.1
Monarch Plugin: 1.3.2
Redirection: 2.4.5
Responsive Menu: 3.0.17
Rotating Tweets (Twitter widget & shortcode): 1.9
SearchWP: 2.8.6
Theme Check: 20160523.1
Ultimate Addons for Visual Composer: 3.16.7
Visual Composer Visceral Add-ons: 1.1
WPBakery Visual Composer: 5.0.1
WP Help: 1.5.1
WP Rocket: 2.8.23
Yoast SEO: 3.9

-- WordPress Inactive Plugins

Akismet: 3.2
Better Search Replace: 1.3
Broken Link Checker: 1.11.2
Hello Dolly: 1.6
Optimize Database after Deleting Revisions: 4.2.1
Password Protected: 2.0.3
Query Monitor: 2.13.1
WP Time Capsule: 1.5.3

-- Webserver Configuration

PHP Version:              5.6.28
MySQL Version:            5.5.5
Webserver Info:           Apache/2.4.23 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4

-- PHP Configuration

Safe Mode:                Disabled
Memory Limit:             256M
Upload Max Size:          24M
Post Max Size:            8M
Upload Max Filesize:      24M
Time Limit:               0
Max Input Vars:           1000
URL-aware fopen:          On (1)
Display Errors:           N/A

-- PHP Extensions

cURL:                     Supported
cURL Version:             7.29.0
zlib:                     Supported
GD:                       Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed
DOM:                      Installed
MBString:                 Installed

-- Session Configuration

Give Use Sessions:        Enabled
Session:                  Enabled
Session Name:             PHPSESSID
Cookie Path:              /
Save Path:                
Use Cookies:              On
Use Only Cookies:         On

### End System Info ###

**Comment by DevinWalker** [comment]
@tleifj Can you do me a favor a try to replicate in a new environment? This is the first I've heard this reported. Also, it's very odd it would remove non-plugin related pages.

**Comment by DevinWalker** [comment]
Closing until we can replicate

**Comment by tleifj** [comment]
Hi @DevinWalker I jus tried it again on a local environment and it did the same thing. This was the using the same original site content as the problem I had before. Another note: I used All In One WP Migration to move the content to the new sites. I'll try to migrate content from another site using Give and see if it does the same thing.

**Comment by DevinWalker** [comment]
@tleifj can you try in a new environment without migrating any content? I'm guessing the issue comes up when the content is migrated.

**Comment by tleifj** [comment]
@DevinWalker I just tried it on the original site without migrating the content. It did the same thing :/

**Comment by DevinWalker** [comment]
@tleifj ok I'll test it out

**Comment by DevinWalker** [comment]
Closing this since we've revamped the logs functionality. Payment data is no longer stored there in a deletable fashion.
