### ISSUE TITLE
donors as Give_Customer or WP_User?

### ISSUE THREAD

**Issue by drzraf** [WordImpress/Give#1296]
This is a documentation/project roadmap issue:

_Give_ currently bind payments to up to **two** identities sources:
* WP_User (through user_id if > 0), and its own metadata
* Give_Customer (though customer_id) and its own metadata

Give's export mechanism only fetch data from WP_User (Give_Customer is then unusable)
But most identity-related metadata (address & co) is currently bound to a Give_Payment (= neither of WP_User or Give_Customer is considered as an "identity" backend object).

It would help to know which direction the project is aiming for:
* Will it preferably use built-in WP_User (is it flexible enough, can it scale, won't this clutter WP admin UI, ...?
* Will it preferably use Give_Customer custom (_extended_) model, making these more Give-dependant and use specific semantics?

**Comment by mathetos** [comment]
Hi @drzraf thanks for your questions and feedback. Our Lead Developer @DevinWalker can give you more detailed info, but I just wanted to clarify WHY Give is using both WP_User and Give_Customer at the moment.  Here's the main points:

* The biggest reason why the Give_Customers table is necessary is to allow donors to give and see their donation history without having to additionall create a user account on the website. 
* That also allows Admins to be able to get their donor data based on donations and still not require a login.
* But tying Give_Customers to a WP_User account is additionally a feature which allows Admins to be able to do additional user-account related items (like restrict pages based on whether the logged-in user is a donor or not) and use other plugins that leverage the user account in various ways correctly.

Those are the main reasons why you see Give using both tables currently. And generally speaking we don't have plans to change that currently. 

But this point you raise here is interesting:
> Give's export mechanism only fetch data from WP_User (Give_Customer is then unusable)
> But most identity-related metadata (address & co) is currently bound to a Give_Payment (= neither of WP_User or Give_Customer is considered as an "identity" backend object).

You should absolutely be able to export all donor data in Give regardless of whether the donors have WP_User id's or not. They should ALL have Give_Customer id's. But Devin can speak to this issue with more detail. Thanks!

**Comment by drzraf** [comment]
any news on this. See for example #1287 and the overall complexity of managing data structures (see my comment in #744). Thanks

**Comment by DevinWalker** [comment]
@drzaf we're focussing on getting release 1.8 out the door then shifting our focus to simplifying and making managing, exporting, and adjusting payment data structures more intuitive and less painful. Are you a part of our Give community on Slack? We'd love to have you join us so we can chat further :)

**Comment by DevinWalker** [comment]
Hey @drzraf 

Apologies for the delay getting back to you on this one. We've buttoned up 2.0 and these are the following donor related updates we are doing in Give version 2.0 with backward compatibility: 

1. The donor related tables is renamed:

    1. {wp-prefix}_give_customer → {wp-prefix}_give_donor

    2. {wp-prefix}_give_customermeta → {wp-prefix}_give_donormeta

2. The Give_Customer class is deprecated. Use the Give_Donor class instead.

3. We are only storing donor ID to payment meta instead of user ID.

4. Moving forward we are going to store donor metadata to {wp-prefix}_give_donormeta instead of WP’s {wp-prefix}_usermeta

    3. Current donor metadata stored in the usermeta table will be copied to the donormeta table using an upgrade routine.

    4. Previous donor metadata stored in the usermeta table will not be deleted. This is for backwards compatibility and a failsafe should the data migration be interrupted.

5. Address updates:

    5. The donor's billing address is currently (pre-2.0) only being saved to the donation payment meta. Moving forward in 2.0 the data is now saved to *both* the payment meta *and* the donor meta. 

    6. If a repeat donor returns and enters a different billing address then it will save like before to the payment meta and *add* the new address to donormeta. In this case, the new address would be called "Billing Address 2" within the donor's profile.

    7. The donor can now have multiple types for addresses.

        1. Add-on like Gift Aid will now store the additional "Gift Aid Address" to the donor meta.

        2. This paves the road for the future enhancement of allowing the donor to have both a billing address and physical address should admins want to collect the additional information.

    8. You can access all donor addresses from the Give_Donor object.

6. A Give_Donor can connect to a WP_User for a variety of reasons including, but not limited to:

    9. Providing the user access to donors by using WordPress core functionality

    10. To increase the extensibility of Give with third-party plugins that creates user roles. Examples include:

        3. Membership plugins

        4. LMS platforms (course, study material)

        5. Content restriction plugins   

        6. Ecommerce platforms

---

Please let me know if you have any questions! I'll be posting this as well to developers.givewp.com
