### ISSUE TITLE
Require stronger password for Give Registration

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1305]
## Issue Overview

If a donor creates an acount, they can currently use the password "123" or "ABC" and it will be accepted. Even though the only data put at risk there is their own donation information, it is a best security practice to enforce strong passwords. Third party security plugins provide a way to enforce stonger passwords, and even core itself does not allow users to create accounts in some cases without more secure passwords. 

Core itself has a method to warn of weak passwords in wp-includes/script-loader.php line 403. (and I couldn't find one, but I know it prevents admins from creating weak passords in the setup/install process.)

## Expected Behavior
Users should be warned (at least) or prevented (at best) when using a weak password. 

## Current Behavior
Currently, any password is accepted.

## Possible Solution
see how Core handles it, and consider adding in the password-strength-meter found in Core.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Good call, I agree we'll want to support strong passwords.

**Comment by ravinderk** [comment]
@DevinWalker @mathetos Can we add strength meter to our password field.

<img width="433" alt="screen shot 2016-12-10 at 4 48 54 pm" src="https://cloud.githubusercontent.com/assets/1784821/21072951/af04890a-bef8-11e6-9da9-18bf8746c737.png">

**Comment by DevinWalker** [comment]
@ravinderk we should use the WordPress PW strength meter.

**Comment by ravinderk** [comment]
@DevinWalker I was also in favor of using WordPress core password related functionality. Check screenshot is it the strong password?

<img width="844" alt="screen shot 2016-12-12 at 8 22 40 am" src="https://cloud.githubusercontent.com/assets/1784821/21086649/8551df02-c044-11e6-84b3-06af51abbc10.png">

**Comment by mathetos** [comment]
@ravinderk What library are you using above? Also, we should just use the WP Core one just for best practices. And it would be an AWESOME way for you to contribute to WordPress Core if you can suggest how it can be strengthened.

**Comment by ravinderk** [comment]
@DevinWalker Do you want to resolve this in `1.8.9` because in `2.0` we are working on `field API` which will be used for generating every form in plugin including Donation forms.
for ref: https://github.com/WordImpress/Give/issues/1038

**Comment by mathetos** [comment]
I have a couple customers/users who are reporting spam user accounts regularly. So it would be great if we could do this soon and perhaps even implement integration with Akismet as well https://github.com/WordImpress/Give/issues/673

**Comment by ravinderk** [comment]
@mehul0810 Please continue on that, Let me know if you have further any question

**Comment by mehul0810** [comment]
@DevinWalker @mathetos  @ravinderk Here is how the password strength meter will look in the donation form having registration. Also, i think we should keep Donate button enabled even if the password entered is weak because it is the matter of choice for user so enforcing user to enter a strong password compulsory should not be the case. For such case, we can have a checkbox to fill in similar to default WordPress password strength meter. Please let me know you views on the same.
![password_strength_meter](https://cloud.githubusercontent.com/assets/1852711/26642562/d097ddbc-464b-11e7-846d-7a317949e441.png)

**Comment by mathetos** [comment]
I actually think we should just use WordPress' default Strong Password auto-generator, and implement this as part of this issue:
https://github.com/WordImpress/Give/issues/1517

At the end of the day, the donor shouldn't have to think about a password at all. If they CHOOSE to change the password, then these colored indicators can come into place.
