### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by michaelbeil** [WordImpress/Give#132]
It may be nice to add a CONTRIBUTING.md for further clarification on how to contribute to the project. Could include how to PR, what to do when a bug is found, etc.

Examples:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/CONTRIBUTING.md
https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/CONTRIBUTING.md
https://github.com/bradp/vv/blob/master/CONTRIBUTING.md

**Comment by BurlesonBrad** [comment]
LIKE!  
...wait, wrong platform.  my bad.

**Comment by DevinWalker** [comment]
Thanks @michaelbeil

**Comment by michaelbeil** [comment]
you bet!
