### ISSUE TITLE
WordPress 4.7 adds a grey border around our Welcome images

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1322]
## Issue Overview

![image](https://cloud.githubusercontent.com/assets/930724/20998512/36f42074-bcc3-11e6-957d-599cd9bd4734.png)

## Expected Behavior
There shouldn't be a border around those images.

## Current Behavior
There is a border around those images

## Solution
Update the Give Admin CSS.

**Comment by DevinWalker** [comment]
I noticed that today and fixed it in the `release/1.8` branch, I can merge it into 1.7.1

**Comment by mathetos** [comment]
Ya, that'd be great. Such a tiny thing might as well just resolve it.
