### ISSUE TITLE
Create autocomplete feature for email shortcodes

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1330]
## Issue Overview

Currently, I found it difficult to remember all email shortcodes and go up/down to get information about shortcode.

![azdijpzbwj](https://cloud.githubusercontent.com/assets/1784821/21036393/967f83ca-bdeb-11e6-8b2c-a6d98af784cf.gif)

**Comment by DevinWalker** [comment]
Yes, we can! 👍

**Comment by mathetos** [comment]
Um... wow. I've never seen that in WordPress. Might be worth considering more as a stand-alone plugin for all registered shortcodes in WordPress.

**Comment by ravinderk** [comment]
@mathetos @DevinWalker Check this https://github.com/ravinderk/shortcode-suggest

**Comment by mathetos** [comment]
@ravinderk You should absolutely submit this to WordPress Trac for consideration as a Feature Plugin for 4.8 or 4.9. I think it would need to be almost like a tree view, where you see shortcodes grouped by "Core" "Plugins" and "Themes" but man... this is a major improvement to the shortcode user experience.

**Comment by ravinderk** [comment]
@mathetos I know that. A while I also created a pull request for this plugin https://github.com/cftp/shortcode-suggest/pull/1, but there did not check it yet ( all most one year). Can you suggest me how can I take over this?

**Comment by mathetos** [comment]
I don't think you can actually take over the the GIthub Repo, only promote your fork as a better option. But for consideration with WordPress Core you should start by submitting it as a free plugin on WordPress.org, then we can chat with the Core team in WP Slack about it. I already pinged @JJJ to review it and provide his insight.

**Comment by ravinderk** [comment]
@mathetos thank you. You are welcome to open any issue on the forked repo. Lets do this.

**Comment by JJJ** [comment]
There's also the Shortcake plugin, which also requires an additional UI registration process to help with attributes and such. It has 10k installs, so a good amount of momentum already.

https://wordpress.org/plugins/shortcode-ui/

**Comment by kevinwhoffman** [comment]
Closing this out for now. It's a very cool feature similar to the block suggestions in Gutenberg, but I think it would primarily benefit power users and be difficult to discover for the average Give user.
