### ISSUE TITLE
Form Preview doesn't work while in Draft Status

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1343]
## Issue Overview

Form Preview doesn't work while in Draft Status

## Expected Behavior
The user should be able to Preview their Give Form regardless of the Post Status.

## Current Behavior
Currently, if the Form has not yet been Published, hitting "Preview" will show the sidebar, and the content (if the_content filter is not disabled), but no form whatsoever.

## Steps to Reproduce (for bugs)
1. Go to "Donations > Add Form"
2. Enter a title, then hit the Preview button.  You'll see something like this:
![image](https://cloud.githubusercontent.com/assets/930724/21207284/297f6602-c21c-11e6-844b-99c52d4e4ccc.png)
3. Even if you first click "Save Draft" and then "Preview" it'll still not show the form.
4. It will only show the form after hitting "Publish".

**Comment by DevinWalker** [comment]
This is likely due to changes made in #1288 - @ravinderk can you look into this?

**Comment by ravinderk** [comment]
@DevinWalker You are right, but it only works fine for all form status except `trash`. If a form has `trash` status then admin will not able to view the page but can see shortcode output, which can confuse admin.
