### ISSUE TITLE
Create custom wrapper for twenty seventeen

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1347]
## Issue Overview

Twenty seventeen calls the featured image in a way that puts it on the form twice.

## Expected Behavior
It should just be in the give sidebar

## Current Behavior
![screen shot 2016-12-16 at 2 02 24 pm](https://cloud.githubusercontent.com/assets/9629102/21275081/1e1ca300-c399-11e6-88a1-cd516f1e04a5.png)

It calls it above the form and also in the sidebar.

## Possible Solution
Creat a custom wrapper for twenty seventeen

## Steps to Reproduce (for bugs)
1. Install twenty seventeen on a stock give install (make sure to not disable the sidebar in Give settings)
2. Add a featured image to a post (twenty seventeen only calls the rogue code if there's a file there, doesn't use our placeholder)
3. View the single form

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mathetos** [comment]
I'll tackle this one. Thanks for reporting @Benunc

**Comment by DevinWalker** [comment]
Nice pic! Haha. "Donate or I'm gonna get you!"

**Comment by DevinWalker** [comment]
Oops, I created a duplicate for this... #1353 which I just fixed. Closing this.
