### ISSUE TITLE
Recurring donation email receipts should say they are a recurring donation 

### ISSUE THREAD

**Issue by tleifj** [WordImpress/Give#1348]
## Issue Overview

Feature request from a client: When a donor signs up for a recurring donation, the first email receipt should mention that it is recurring. This gives the donor feedback that they ticked the box and signed up for the recurring donation. 

## Expected Behavior
The email includes information about the donation (one time or recurring)

## Current Behavior
There is no way to differentiate between one-time and recurring donations.

**Comment by mathetos** [comment]
Hi @tleifj thanks for filing this issue. We track all our Recurring Donations issues in a private repo, but we have an open issue on this specifically. I'll leave this open and refer to it in the Recurring issue so you can see our progress from this issue as well (but you won't be able to see our communications).

Thanks!

**Comment by tleifj** [comment]
@mathetos Thanks for the info!
