### ISSUE TITLE
update_customer_email_on_user_update adds itself as an action

### ISSUE THREAD

**Issue by chtaylormeh** [WordImpress/Give#1358]
We were having an issue with our Active Directory Integration bulk import of users after adding Give (1.7.2) to our site, and I traced it to the following:

The Give_DB_Customers constructor adds a profile_update action, for the update_customer_email_on_user_update method of itself. When this action is called, it creates a new Give_Customer object. The constructor for Give_Customer creates a new Give_DB_Customers object, which adds another profile_update action. So next time, both get called, each of which end up adding yet more profile_update actions, so the actions keep on growing and growing every time the profile_update action is called.

This is a huge problem in long-running scripts such as the AD Integration bulk import (which updates users, triggering the profile_update action). The script quickly slowed down and hit the PHP memory limit, causing it to fail.

My quick fix was to have the Give_Customer take a Give_DB_Customers as an optional argument and use that instead of creating a new instance, if provided. Then modified update_customer_email_on_user_update to pass $this to it. This prevents new Give_DB_Customers instances from being created, and therefore multiple profile_update actions, and completely resolves the issue.

I hope this is descriptive enough, but I'm happy to provide more details if necessary to help this get fixed.

**Comment by mathetos** [comment]
Hi @chtaylormeh Thanks for reporting this. Can you provide a snippet of the code that you changed? Or even a Pull Request? That would help us understand best what you're referring to.

**Comment by chtaylormeh** [comment]
Sure thing. In class-give-customer.php, starting at line 147, we add a $db argument to the constructor:

```
    public function __construct( $_id_or_email = false, $by_user_id = false, $db = null ) {

        if ($db != null) {
            $this->db = $db;
        } else {
            $this->db = new Give_DB_Customers;
        }
```
This way we can pass an existing Give_DB_Customers instance instead of creating a new one.

Then, in class-give-db-customers.php, on line 320 in the update_customer_email_on_user_update method, we make use of that new argument to pass the current instance:

`$customer = new Give_Customer( $user_id, true, $this );`

There's probably a better way to solve the issue than this though, such as registering the profile_update action for update_customer_email_on_user_update somewhere besides the Give_DB_Customers constructor.

The real problem is that creating a new Give_DB_Customers instance registers a profile_update action (update_customer_email_on_user_update)... and when that action is triggered, another new Give_DB_Customers instance is created, which registers another profile_update action, and they keep building and building. I'll try to describe some more:

In class-give-db-customers.php:
```

	public function __construct() {
		/* @var WPDB $wpdb */
		global $wpdb;

		$this->table_name  = $wpdb->prefix . 'give_customers';
		$this->primary_key = 'id';
		$this->version     = '1.0';
		
		add_action( 'profile_update', array( $this, 'update_customer_email_on_user_update' ), 10, 2 );

	}
```

That adds the profile_update action to call update_customer_email_on_user_update. Now if we look at update_customer_email_on_user_update:
```
	public function update_customer_email_on_user_update( $user_id = 0, $old_user_data ) {

		$customer = new Give_Customer( $user_id, true );
```
A new Give_Customer instance is created. Now if we look at class-give-customer.php:
```
	public function __construct( $_id_or_email = false, $by_user_id = false ) {

		$this->db = new Give_DB_Customers;
```
It creates another Give_DB_Customers instance, which as we saw above calls "add_action('profile_update' ..." again. So when the profile_update action is triggered over and over (such as in a script that updates many users at once), the number of calls to update_customer_email_on_user_update increases exponentially. The real fix is to make sure this code

`add_action( 'profile_update', array( $this, 'update_customer_email_on_user_update' ), 10, 2 );`

only ever gets called once.

Hope this helps!
