### ISSUE TITLE
Invalid form control JS warning -  'Donate Now' not functioning

### ISSUE THREAD

**Issue by philwp** [WordImpress/Give#1373]
## Issue Overview

Warning message appears in firefox.  When 'Donate Now' button is pressed.
![img_2975](https://cloud.githubusercontent.com/assets/5949352/21594659/2a9b99c6-d0f3-11e6-88ef-3ba25e4ab359.JPG)

Here is the error I am getting in chrome:
![screen shot 2017-01-02 at 1 39 51 pm](https://cloud.githubusercontent.com/assets/5949352/21594672/4f431c2c-d0f3-11e6-8a6a-c33f4c42719d.png)

## Current Behavior

On the site I was working on it is using stripe add-on and recurring payments add-on.  I was able to make the error occur when I was making a single payment.  
## Possible Solution

Error message goes away when you select the 'Email Access' box in the settings->advanced menu tab. 
## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Related PRs
List related PRs against other branches:

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@philwp 
This is happing because somehow `registration form` or `login form` is loading in the form on the frontend but it is hidden.

Can you show us what is your form setting and system info settings ( Donation -> Settings -> system Info)?

**Comment by philwp** [comment]
Here are the system settings
### Begin System Info ###

-- Site Info

Site URL:                 http://rocktheworld.org
Home URL:                 http://rocktheworld.org
Multisite:                No

-- Hosting Provider

Host:                     DBH: localhost, SRV: rocktheworld.org

-- User Browser

Platform:                 Apple 
Browser Name:             Chrome  
Browser Version:          55.0.2883.95 
User Agent String:        Mozilla/5.0 (Macintosh; Intel Ma 
			  c OS X 10_11_2) AppleWebKit/537.
                          36 (KHTML, like Gecko) Chrome/55
                          .0.2883.95 Safari/537.36
                          
-- WordPress Configuration

Version:                  4.5.4
Language:                 en_US
Permalink Structure:      /%year%/%monthnum%/%day%/%postname%/
Active Theme:             Beaver Builder Theme 1.5
Show On Front:            page
Page On Front:            Coming Soon (#866)
Page For Posts:           Unset
Remote Post:              wp_remote_post() works
Table Prefix:             Length: 4   Status: Acceptable
Admin AJAX:               Accessible
WP_DEBUG:                 Disabled
Memory Limit:             40M
Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, preapproval, give_subscription

-- Give Configuration

Version:                  1.7.2
Upgraded From:            None
Test Mode:                Disabled
Currency Code:            USD
Currency Position:        before
Decimal Separator:        .
Thousands Separator:      ,

-- Give Page Configuration

Success Page:             http://rocktheworld.org/donation-confirmation/
Failure Page:             http://rocktheworld.org/transaction-failed/
Give Forms Slug:           /donations

-- Give Gateway Configuration

Enabled Gateways:         Stripe - Credit Card
Default Gateway:          Stripe - Credit Card

-- Must-Use Plugins

SSO: 0.1

-- WordPress Active Plugins

Beaver Builder Plugin (Agency Version): 1.8-alpha.7
Give - Donation Plugin: 1.7.2
Give - Recurring Donations: 1.2.2
Give - Stripe Gateway: 1.4.2
Redirection: 2.4.4

-- WordPress Inactive Plugins

Ajax Event Calendar: 1.0.4
Akismet: 3.1.11
Custom Post Donations: 4.1.1
Duplicator: 1.1.10
Easy Columns: v2.1.3
Gravity Forms: 2.1.1
Gravity Forms Authorize.Net Add-On: 2.2
Gravity Forms PayPal Standard Add-On: 2.6
Jetpack by WordPress.com: 4.0.3
NextGEN Gallery: 2.1.43
Simple Staff List: 1.19
WP Easy Paypal Payment Accept: v4.9

-- Webserver Configuration

PHP Version:              5.4.43
MySQL Version:            5.6.32
Webserver Info:           Apache

-- PHP Configuration

Safe Mode:                Disabled
Memory Limit:             256M
Upload Max Size:          64M
Post Max Size:            64M
Upload Max Filesize:      64M
Time Limit:               30
Max Input Vars:           1000
URL-aware fopen:          On (1)
Display Errors:           N/A

-- PHP Extensions

cURL:                     Supported
cURL Version:             7.24.0
zlib:                     Supported
GD:                       Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed
DOM:                      Installed
MBString:                 Installed

-- Session Configuration

Give Use Sessions:        Enabled
Session:                  Enabled
Session Name:             PHPSESSID
Cookie Path:              /
Save Path:                /tmp
Use Cookies:              On
Use Only Cookies:         On

### End System Info ###
![screencapture-rocktheworld-org-wp-admin-post-php-1483544100953](https://cloud.githubusercontent.com/assets/5949352/21647775/90544c78-d269-11e6-9f6e-07fec9dbc548.png)

**Comment by DevinWalker** [comment]
Hey @philwp - I have fixed this in Recurring here: https://github.com/WordImpress/Give-Recurring-Donations/commit/9d1c514ba114e5eced10e7ccbccbc88711c5ed9c#diff-d4300a209598a9fc2d9d0cacfe9c13f2R151

Essentially, this happens when a field with the HTML5 `required` attribute is hidden for view. We were not properly toggling this when the register fields were shown / hidden from view. I have just sent you an invite to this repository so you can access the fix pre-release.

Please let me know if you have any questions!
