### ISSUE TITLE
Add login notification upon successful login within donation form

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1384]
## Issue Overview
Add a notification in the donation form that says "Welcome {first_name}! You have successfully logged into your account." This would be added just within the donation form when donors login via that form.

## Current Behavior
Currently, upon logging in, it's almost impossible to notice that you are actually logged in to the site successfully. There is no indication at all.

## Expected Behavior
Users expect notification when they complete an action.

## Possible Solution
Use our default notifications, add one that appears in the form after they have successfully logged in.

**Comment by raftaar1191** [comment]
Working on the above issue
