### ISSUE TITLE
Add slack channel invite link to plugin about page

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1388]
## Issue Overview
I think, this will be good if we add slack channel link to plugin about page. This will help us to grow the community.

<img width="1158" alt="screen shot 2017-01-17 at 11 00 58 am" src="https://cloud.githubusercontent.com/assets/1784821/22008787/5521302c-dca4-11e6-8b58-6f39d277761c.png">

**Comment by DevinWalker** [comment]
I'd rather not invite everyone under the sun into our Slack channel for now. Rather, we're thinking about starting a Facebook group that we can add people to. Closing this one out for now.
