### ISSUE TITLE
Guest Donations description adds confusion to what the setting does

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1397]
## Issue Overview

Descriptions of settings should clarify what the different options do, but currently (in 1.8) the Guest Donations setting adds to the confusion rather than clarifies.

## Current Behavior
![image](https://cloud.githubusercontent.com/assets/930724/22089884/f8604b20-dda2-11e6-83a4-7c3b7e290394.png)

The title is "Guest Donations" and the options are "Enabled | Disabled", and the question in the description is:
> "Do you want to require users be logged-in to make donations?"

The description makes it sound like ENABLING that would require users to be logged-in. 

## Possible Solution
The description should be about what Guest Donations are and what having them ENABLED would mean. This is my suggestion:

> "Do you want to enable non-logged-in users to make donations?"

PR forthcoming with .POT file updates as well.

**Comment by mathetos** [comment]
@DevinWalker Somehow I ended up pushing my commit directly to 1.8 here instead of to my fork... not sure how that happened. Apologies! But this commit resolves this issue:
https://github.com/WordImpress/Give/commit/a578674639d014a21cc3037f1ba8c35f417fb688

**Comment by mathetos** [comment]
Also I didn't commit the POT file because it looks like there's quite a bit there that needs updating, so I'm assuming you're doing that later, pre-launch.

**Comment by DevinWalker** [comment]
Yeah we always generate the POT file prelaunch. It's not necessary to do it for little text changes. Please also tag the issues within your commits whenever possible.
