### ISSUE TITLE
Give Sidebar displays shop sidebar

### ISSUE THREAD

**Issue by ibndawood** [WordImpress/Give#140]
Hey @mathetos and @DevinWalker ,

Is there a specific reason behind displaying shop sidebar for give ? https://github.com/WordImpress/Give/blob/master/templates/global/sidebar.php

Thanks,
Ibrahim

**Comment by DevinWalker** [comment]
Not really currently. The plan is to register a sidebar for the single view when we add some widgets. It's going to be called something other than "shop" though.
