### ISSUE TITLE
Add a way to display custom fields to the bottom of the donation receipt shortcode output

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1406]
## Issue Overview

If a donation has custom field data, we should provide a way to display that on the shortcode output.

## Expected Behavior
If you add custom field data with Form Field Manager, you should be able to add additional table cells to the bottom of the shortcode output with that data in them.
## Current Behavior
Currently it's not possible to add that data to the shortcode output.

## Possible Solution
Add an action or filter to the bottom of https://github.com/WordImpress/Give/blob/master/includes/admin/shortcodes/shortcode-give-receipt.php#L98 so that additional fields can be added there. 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
You _can_ add them using the following action: https://github.com/WordImpress/Give/blob/master/templates/shortcode-receipt.php#L242

**Comment by DevinWalker** [comment]
Issue moved to [WordImpress/Give-Snippet-Library #22](https://github.com/WordImpress/Give-Snippet-Library/issues/22) via [**ZenHub**](https://www.zenhub.com/)
