### ISSUE TITLE
Settings tab UI improvement to prevent bumping to two lines

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1413]
## Issue Overview
@ravinderk and I have been discussing how we can prevent settings tabs from bumping to two lines, which looks pretty bad and is a bad user experience that too many WordPress plugins have. 

## Solution
ZenHub is a good example of a well thought out UI when a large number of tabs that exceed the container width are present:

![2017-01-20_18-04-23](https://cloud.githubusercontent.com/assets/1571635/22149643/f40ff19e-df3a-11e6-8203-771cf9bcd3ba.gif)
- Tabs present are displayed in a dropdown that is toggled via the down arrow caret
- When a tab clicked within the dropdown is clicked it is displayed in the main tab row displaying to the user that this tab is active.

### Dynamic Container Widths
Unlike Github, WordPress' container width can vary in width depending on the browser resolution:

![2017-01-20_18-10-09](https://cloud.githubusercontent.com/assets/1571635/22149789/ccf36fb8-df3b-11e6-97d1-c60d8a21a493.gif)
 I propose that to handle dynamic widths:
- When the container is reduced in width, tabs are dynamically added to the select _until_ WordPress' responsive breakpoint turns them into buttons for mobile.

**Comment by mathetos** [comment]
Yes! Love this idea.

**Comment by mathetos** [comment]
@ravinderk Also seeing the following issue:

![image](https://cloud.githubusercontent.com/assets/930724/22391435/fff08102-e4a5-11e6-824c-8e33461e6995.png)


Notice that the "Advanced" tab is appearing in the dropdown even though it's already visible in the main tabs.

**Comment by ravinderk** [comment]
@mathetos thank for reporting this. I am working on this.

**Comment by ravinderk** [comment]
Make responsive tab working for each setting page, currently, it is not working for tools and reports page

![Uploading Screen Shot 2017-02-10 at 2.17.31 PM.png…]()
