### ISSUE TITLE
feat(grid): display multiple forms in a grid

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1414]
## Issue Overview
We should have a `[donation_form_grid]` shortcode that display donation forms in a nice layout:
![grid](https://cloud.githubusercontent.com/assets/1571635/22156834/0d38dbd4-df5b-11e6-9790-e5e75ac330df.png)

### Grid Element Explanation
![2017-01-20_21-58-57](https://cloud.githubusercontent.com/assets/1571635/22157061/136981d8-df5c-11e6-933b-029bf7f47960.png)

### Shortcode Attributes
- `number`: Default = `3`
- `goal` (if applicable): Default = `true`
- `excerpt`: Default = `true`
- `featured_image` : Default = `true`

### Acceptance Criteria
- Grid should fill full width of container
- Grid should be responsive
- Grid should have minimal conflict with themes

## Tasks
- [x] Design Grid
- [x] Develop Shortcode
- [ ] Implement CSS Grid
- [ ] Test with Popular Themes (Avada, Divi, X, etc)
- [ ] Documentation

**Comment by mathetos** [comment]
This sounds like an Add-on to me, not a Core feature.

**Comment by DevinWalker** [comment]
Nope, not to me.

**Comment by mathetos** [comment]
@DevinWalker I think there's overlap here with issue https://github.com/WordImpress/Give/issues/1230

What do you think of moving this issue to be a feature of #1230 Basically, the `[give_forms]` shortcode proposed in #1230 could have a `display_style` attribute as follows:

* `[give_forms id="all" display_style="grid"]`
* `[give_forms id="5,6,7" display_style="list"]`

**Comment by Benunc** [comment]
Adding a "category" or "tag" parameter to this shortcode would be powerful, as well. Users have requested this. (one today)

**Comment by khan19** [comment]
Hello,

Are these shortcodes ready to use? I have used them on Avada theme. It didn't work.

Thanks,
Mazhar

**Comment by ravinderk** [comment]
@khan19 We are working on this and it will work on next release (`1.8.15`).

**Comment by khan19** [comment]
Alright, Thank you :) Good wishes for next release!

**Comment by mehul0810** [comment]
@DevinWalker I've tried to build the `[donation_form_grid]` shortcode. But, It seems that with current structure of donation forms. It will require to break lots of code related to donation forms and duplication of code as well. 
Also, If we build it now then we need to test the main functionality donation form as well and refactoring the donation forms and the shortcodes again when we release the Form API (i.e. https://github.com/WordImpress/Give/issues/1038).

I had the discussion for the same with @ravinderk and came to a conclusion that we should bump this issue after Form API so that we can work systematically with out any break and duplication of code.

Even, I've saved the WIP for this issue so that I can re-use it again. (Ref: https://github.com/mehul0810/Give/tree/issue/1414)

Let me know your thoughts.

**Comment by DevinWalker** [comment]
@mehul0810 I was thinking that rather than loading the structure of the donation form within each grid item that you could simply create your own structure and the "Donate Now" button would either:

A. Load the donation form in a modal via AJAX
B. Take the donor to the single donation form page

This will allow you to control the markup of the grid within the shortcode and you wouldn't be tied to the form structure. Let me know what you think and we can discuss.

**Comment by raftaar1191** [comment]
I also think the same @DevinWalker 

We can create our own structure than redirecting link to the single page this sound good an simple too.

**Comment by amjad** [comment]
I think the modal popup may not work very well on mobile devices. Its better to have it redirect to its own page. This is definitely a missing feature! Pretty sure many users have multiple forms and it gets hard not being able to show them all in one page in this nice grid layout. We have several clients already waiting for this feature! 

What's the status on this?

**Comment by mehul0810** [comment]
We can create a Gutenberg block for this shortcode and we can add the shortcode attributes in the presentation layout of Gutenberg which can be helpful for end user as discussed with @DevinWalker over call on Friday.

**Comment by raftaar1191** [comment]
yes @mehul0810 but there will be other user as well who are not going to install the Gutenberg as there default editor

**Comment by ravinderk** [comment]
@Sidsector9 Can you recreate a pr for this issue because the last pr merged into `WordImpress:feature/gutenberg-donation-form-block` which is `Gutenberg` block specific which is not a priority for `2.1`.

**Comment by amjad** [comment]
will this be a part of 2.1 ?

**Comment by ravinderk** [comment]
@amjad Yes.
If you need more information about `2.1` release planning then you can check this link: https://github.com/WordImpress/Give/wiki/Give-Release-Planning

**Comment by amjad** [comment]
Awesome, thanks!

**Comment by kevinwhoffman** [comment]
@Sidsector9 After discussing with @DevinWalker, I am going to work with you to get CSS Grid implemented in the Donation Form Grid prior to release. We want to make sure CSS Grid is our grid solution moving forward.

**Comment by Sidsector9** [comment]
@kevinwhoffman Are we focusing to implement Grid for just Donation Form Grid or the entire Give plugin?

**Comment by kevinwhoffman** [comment]
Closing in favor of #2943 which picks up where this issue left off.
