### ISSUE TITLE
"Create New Donor" Link not working on admin.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1417]
## Issue Overview

Currently, creating a new donor is not working on 1.7.2 or 1.8

## Expected Behavior
Clicking this link  (on the back end of a single donation) should do something:

<img width="682" alt="screen shot 2017-01-23 at 1 18 22 pm" src="https://cloud.githubusercontent.com/assets/9629102/22216799/7848219a-e16e-11e6-8e90-711734d0d517.png">

## Current Behavior
CUrrently it just adds #new to the slug and doesn't do anything. I tested on 1.7 and 1.8

## Steps to Reproduce (for bugs)
1. GO to the backend of a single donation 
2. click the link
3. nothing happens.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@DevinWalker  Renaming ID is cause of this bug.
https://github.com/WordImpress/Give/commit/d2e8041cd63fbc4aba1740ac1f3374517392fd2d#diff-ae5d42d35edee09a75b937efb622d946R480
