### ISSUE TITLE
Form Action Not Updating on Payment Gateway Change

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1418]
## Issue Overview

The Form Action should change when the payment gateway changes. That is currently not happening as expected.

## Expected Behavior
When on a form, you change the payment gateway, the form action should also change. For most Gateways that isn't a problem, the payment will go through regardless. But for the Stripe Modal the modal won't open at all, unless the ACTION is correct.

## Current Behavior
Currently it is not updating dynamically when the gateway is changed. 

![form-action-not-updating](https://cloud.githubusercontent.com/assets/930724/22219706/a9323268-e160-11e6-90fa-228f3f83bb00.gif)

## Steps to Reproduce (for bugs)

The bug can be seen by Inspecting Element on any form, then switch the gateway while highlighting the `<form>` element like the GIF above.

But to see how it is problematic for the Stripe Modal, do the following:
1. Activate Stripe, Enable it as a Gateway, and select the "Stripe Modal" option in Gateway settings.
2. On a specific form, make sure the default gateway is NOT stripe. Let's say OFFLINE for example.
3. Go to that form, Inspect Element and you'll see the action is like so: `http://giveplugin.dev/donations/new-form?payment-mode=offline`
4. Switch the Gateway on the form to STRIPE and you'll notice that the ACTION doesn't update.
5. Try to complete the donation and you'll see that the STRIPE MODAL does not open.
6. Now switch the form to have STRIPE as the default gateway. 
7. Repeat steps above and you'll see the ACTION is STRIPE and the Modal opens correctly.

**Comment by Benunc** [comment]
Confirmed in my tests as well.
