### ISSUE TITLE
Coding standards

### ISSUE THREAD

**Issue by michaelbeil** [WordImpress/Give#142]
Gonna submit a PR with a link to WordPress Coding Standards, and a few things on code docs.

What tab size do you all use @DevinWalker and @mathetos? 2 or 4?

**Comment by DevinWalker** [comment]
We're using PHP Storm's WordPress specs:

![phpstorm-specs](https://cloud.githubusercontent.com/assets/1571635/7785578/ed04caac-014a-11e5-9393-a95b42972a4d.png)

**Comment by michaelbeil** [comment]
Got it.

**Comment by michaelbeil** [comment]
Just changed tab size 2 to tab size 4.

**Comment by DevinWalker** [comment]
Cool thanks
