### ISSUE TITLE
Keep Names Email Populate upon Gateway Change

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1424]
## Issue Overview
If a user enters their first/last name and/or email address but then change their gateway, all that info should be kept and populated in the new gateway fields.

## Expected Behavior
If a user enters their first/last name and/or email address but then change their gateway, all that info should be kept and populated in the new gateway fields.

## Current Behavior
Currently those fields are getting erased when the gateway changes.

I tested this on 1.7.2 and 1.8 and it was consistent across both.

![name-email-gateway-change](https://cloud.githubusercontent.com/assets/930724/22305880/f0f3d4e8-e2f1-11e6-8fa9-eb8c44ce0a0f.gif)

## Possible Solution
We should be able to grab those values and put them into the new fields with the `give_load_gateway()` AJAX function.

## Steps to Reproduce (for bugs)
Replication steps are clear from the GIF above.

## Related PRs
I thought we addressed this previously and searched all over the Issues and couldn't find it anywhere.

**Comment by ravinderk** [comment]
@mathetos I think, I already created issue similar to this.
https://github.com/WordImpress/Give/issues/697
