### ISSUE TITLE
Make the forms really customizables => form builder

### ISSUE THREAD

**Issue by drzraf** [WordImpress/Give#1425]
## Issue Overview

give_user_info_fields is not extensible.
Although it fires 5 hooks it still fails to give the possibility to add custom fields.
Simple example. I need a "Sex" radio button, before the firstname but inside the fieldset. None of the hooks apply.
This is the role of form API/builders makes form extensible (input type definition (default values, validators, error handlers, weight, subfields/fieldset, ...). See https://github.com/oomphinc/WP-Forms-API for such a tool.

## Expected Behavior
I want to customize Give's form in an easy and natural though powerful way

## Current Behavior
I needs to inspects X hooks which often does not fit the one's specific/innovative or even common needs

## Possible Solution
Don't use hook to allow form extension/customization.
Rather, split this in form structuration / rendering step, use a form builder and give back the full power of their customizations

## Related PRs
#1359

## Todos
- [ ] Choose a solution
- [ ] Implement
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Hey @drzraf we definitely see this as a major priority for us. We have this open issue here: https://github.com/WordImpress/Give/issues/1038 which addresses a better way to build forms. Thank you for providing https://github.com/oomphinc/WP-Forms-API as a reference, that will be very helpful with how we proceed. Please following #1038 for updates.
