### ISSUE TITLE
"Export Donors" creating multiple instances of the same donor.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1426]
## Issue Overview

When you select a single form from the "Export Donors" tab, it creates multiple redundant lines if you've only got a single form selected, and one donor having given more than once to that form.

## Expected Behavior

If I want a list of all donors for a single form, I should not get duplicate lines.

## Current Behavior
If I leave the "Form" option unselected, I end up with the correct list, with no duplicates. But if I select a single form, since it is looping through payment IDs, and not through donor IDs, it is giving me multiple occurrences of each donor.

## Possible Solution
In https://github.com/WordImpress/Give/blob/master/includes/admin/reporting/export/class-batch-export-customers.php#L167 we should loop through donors, not through payments.

## Steps to Reproduce (for bugs)

1. create donations for a form where a single donor has given multiple times.
2. export donors in CSV for just that form.
3. there will be redundant lines in the CSV.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mathetos** [comment]
@Benunc What version did you test this on? 1.7.2 or also on 1.8?

**Comment by Benunc** [comment]
yes, tested on both 1.7 and 1.8
