### ISSUE TITLE
Offline Donation Confirmation page not updating after donation marked as Complete

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1429]
## Issue Overview

When a donation is marked complete on the backend that was initiated via a front-end Offline donation, the donation confirmation page is not showing the donation as complete

## Expected Behavior

Once the donation is manually marked as complete, it should show up as complete on the donation confirmation page.

## Steps to Reproduce (for bugs)
1. Initiate an offline donation. Donation confirmation will show up correctly, as pending.
2. Go in and mark the donation as complete on the back end.
3. Return to the Donation confirmation page. Even a hard refresh doesn't work to make it show as complete.
## Notes: 

- I also tested by visiting the link sent in the donation receipt in a different browser, and it still shows as pending.
- I have no caching running, and I tried manually using our refresh tools, to no avail.
- I confirmed this on both 1.7.2 as well as 1.8, both on fresh installs.

## Todos
- [ ] Tests

**Comment by kevinwhoffman** [comment]
Confirming this bug in 1.8. After marking an offline donation Complete and then clicking the link in the receipt email, the notice still says Payment Pending.
