### ISSUE TITLE
don't use custom (wrong) translation

### ISSUE THREAD

**Issue by drzraf** [WordImpress/Give#1452]
## Issue Overview

Don't recreate custom translation on top of WordPress ones
Here, in french language

## Expected Behavior
``wp eval "esc_attr_e( 'Last Name', 'give' );"``
> Nom

## Current Behavior
``wp eval "esc_attr_e( 'Last Name', 'give' );"``
> Prénom

## Possible Solution
``wp eval "esc_attr_e( 'Last Name' );"``
> Nom

## Consequence
People input their last name inside the firstname form input box = database is full of wrong data records.

**Comment by Benunc** [comment]
Hi there. 

This is actually a result of the official WordPress translation team's efforts. We've put in for a change to that translation (you can see it among many other strings waiting to be approved here: https://translate.wordpress.org/locale/fr/default/wp-plugins/give) but it has not been approved yet. I'll ping the french team leads on Slack and see if we can get that included.

Thanks for bringing this up!
