### ISSUE TITLE
Clean up form styles

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#1453]
## Issue Overview

There are some inconsistencies and display issues across the various types of forms.

- [x] Stack Mobile Fields on Small Viewports
- [x] Make Vertical Spacing and Button Font Sizing Consistent
- [x] Style Field Borders Consistently
- [x] Padding between radio buttons and labels is too small.
- [x] First Name/Last Name break into two lines in padded forms
- [x] Donation Total breaks into two lines in padded forms
- [x] Loading Animation Updates (Both on gateway change and form submit)
- [x] Featured image does not go full width at small resolutions.
- [x] Test with popular themes X, Divi, Avada, Twenty*
- [x] Ensure styles are compatible with `[give_profile_editor]`, `[give_register]`, and `[give_login]`
- [x] Style registration form that appears within form "Need to create an account? Register"

- [x] Cross-browser and device test (we can do Windows / IE)

### 1. Stack Mobile Fields on Small Viewports

This is the width of an iPhone 4/5.

![image](https://cloud.githubusercontent.com/assets/1938671/22657600/0ceec866-ec65-11e6-86fc-c60e90077421.png)

### 2. Make Vertical Spacing and Button Font Sizing Consistent

![image](https://cloud.githubusercontent.com/assets/1938671/22657083/3be38a96-ec63-11e6-97e5-095f65d710f5.png)

### 3. Style Field Borders Consistently

This one depends on the theme. Borders are consistent in Twenty Seventeen but not Give theme. We should style them explicitly.

![image](https://cloud.githubusercontent.com/assets/1938671/22657411/6037025a-ec64-11e6-95b0-9eaa4259a166.png)

**Comment by kevinwhoffman** [comment]
@DevinWalker Let's reopen this one. I found a few more issues that should be addressed as I was creating demos.

## Padding between radio buttons and labels is too small.

![image](https://cloud.githubusercontent.com/assets/1938671/22800452/70b1eee0-eed7-11e6-9133-24ca51fa989b.png)

## First Name/Last Name break into two lines in padded forms

Make them two rows for now as we did to resolve other multi-column issues.

![image](https://cloud.githubusercontent.com/assets/1938671/22800509/9deb3c2c-eed7-11e6-92cc-6a9cf3c5a641.png)

## Donation Total breaks into two lines in padded forms

Let's stack Donation total above the value and style the borders so it looks like a cohesive box.

![image](https://cloud.githubusercontent.com/assets/1938671/22800592/cd14ef3e-eed7-11e6-8c23-61ab45ab60de.png)

**Comment by DevinWalker** [comment]
Sounds good @kevinwhoffman

**Comment by DevinWalker** [comment]
## Loading Animation Updates
![2017-02-10_10-38-01](https://cloud.githubusercontent.com/assets/1571635/22839242/7a7164a0-ef7d-11e6-8785-ddbabbcc2f12.gif)

1. it doesn’t rotate perfectly 
2. there’s a slight imperfection in the pixels of the image itself if you look close 
3. The word “loading” causes the gateways to bump to two lines on tight resolutions and is redundant as the animation implies loading

![2017-02-10_10-44-37](https://cloud.githubusercontent.com/assets/1571635/22839370/f955b0e6-ef7d-11e6-824d-2c21942d285e.gif)

**Comment by DevinWalker** [comment]
## List of Items for this Issue
@kevinwhoffman please check these off as they're complete
- [ ] Stack Mobile Fields on Small Viewports
- [ ] Make Vertical Spacing and Button Font Sizing Consistent
- [ ] Style Field Borders Consistently
- [ ] Padding between radio buttons and labels is too small.
- [ ] First Name/Last Name break into two lines in padded forms
- [ ] Donation Total breaks into two lines in padded forms
- [ ] Loading Animation Updates (Both on gateway change and form submit)
- [ ] Featured image does not go full width at small resolutions.
- [ ] Test with popular themes X, Divi, Avada, Twenty*
- [ ] Cross-browser and device test (we can do Windows / IE)

**Comment by DevinWalker** [comment]
## Profile Editor
I noticed that the styles appear broken now for the `[give_profile_editor]` shortcode. Please ensure styles work for the profile editor as well.

![2017-02-10_16-31-58](https://cloud.githubusercontent.com/assets/1571635/22849071/7669f9fe-efae-11e6-9e0d-450d00e2f681.png)

**Comment by kevinwhoffman** [comment]
I enabled the Registration and Login Forms and found this. Confirmed it was like that since at least 1.7.2. Adding to list.

![image](https://cloud.githubusercontent.com/assets/1938671/22850299/28782762-efd5-11e6-96c6-4d6d4d793aa2.png)
