### ISSUE TITLE
Payment Gateway API Keys and sensitive fields should be a password field

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1455]
## Issue Overview
Currently API keys in Addon settings are stored with a simple text field. They should be a password field instead to prevent human readable keys. This is particularly important for larger websites that have a lot of Admins.

**Comment by Benunc** [comment]
also all payment gateway credentials. According to https://github.com/WordImpress/Give-Authorize-Gateway/issues/27 there is a field in 1.8 to handle this. We get this request a lot.

**Comment by DevinWalker** [comment]
![2017-02-07_08-19-15](https://cloud.githubusercontent.com/assets/1571635/22700064/2f262e20-ed0e-11e6-8c7c-d882053d4656.png)

**Comment by Benunc** [comment]
I think @mathetos original point was for Give API fields, for sites where multiple folks have API access. Don't want to hijack that original intent.

**Comment by mathetos** [comment]
@Benunc No, Devin's right, it was for Payment Gateway API keys/credentials. That's an actual monetary issue for some Admins. The Give API can't PUSH to the website so it's less of an issue. But it's probably worth adding a new issue about making the Give API keys password fields as well.

**Comment by mathetos** [comment]
@DevinWalker Isn't this resolved in 1.8 now?

**Comment by DevinWalker** [comment]
I'm going to close this one out because the Give API keys are only accessible within wp-admin to user roles with the proper access rights AND that there are no post capability. As well, we will eventually look into using the WP REST API in the future rather than rolling our own now that it is in core.
