### ISSUE TITLE
feat(form): identify areas of improvement for existing forms

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#1457]
# Issue Overview

Having just spent some time testing Give form styles across several themes in #1453, I'm starting this thread to track styling issues that should be considered as we approach 2.0. I'll start with a big idea here and we can add additional considerations in comments below.

## Big Idea: Offer levels of styling rather than binary on/off switch

Give should offer at least three settings regarding CSS.

1. No CSS.
2. Layout Only - Only layout CSS is output to arrange multi-column fields and handle vertical spacing. The rest of the form styles would be inherited from the theme (labels, inputs, etc.).
3. Layout + Styling - Similar to what we offer today with layout and styling of the Give form.

Note options 1 and 3 are currently offered.

#### Why Layout Only?

The reason "Layout Only" would be a great addition is that it would allow the form to inherit the theme's styles while still ensuring a consistent layout. I am finding that some themes (particularly ones that include color and design beyond black text on a white background) would benefit from an option to use their own styles in the Give form rather than clash with the styles that are pre-packaged.

There's still room to offer more opinionated styles like those in the GDI demo, but at minimum I think we should offer the three options above.

**Comment by kevinwhoffman** [comment]
We should also take a look at labels in terms of the language used, font size, and how we indicate required fields and tool tips. It's very difficult as of Give 1.8 to have any multi-column layouts on a mobile form because the required asterisk and tooltip icon take up so much space. See below.

![image](https://cloud.githubusercontent.com/assets/1938671/22800858/b7076a54-eed8-11e6-8397-08a8c3e81130.png)

**Comment by kevinwhoffman** [comment]
I've come across a few cases where Give is embedded in a container with `text-align: center;`. Regardless of whether this is good decision from a design perspective, we should honor the expectation that the form and its components should be centered. There's opportunity to replace some of these elements that currently use `float: left;` with `display: inline-block;` which will center as expected.

## Give 1.8 in container with text-align: center;
![image](https://cloud.githubusercontent.com/assets/1938671/22813654/3870366a-ef1b-11e6-8545-cfbc81931fa1.png)

**Comment by kevinwhoffman** [comment]
## Consider using theme's single.php template for single forms

As of Give 1.8, the single form template places a featured image in a side column. This can be problematic in theme's that already contain a side column, or where the content column is relatively narrow already (e.g. Twenty Fifteen shown below). By leveraging the theme's `single.php` template, we can improve theme compatibility.

![image](https://cloud.githubusercontent.com/assets/1938671/22847251/cb84776a-efb9-11e6-9029-6e520258058f.png)

**Comment by kevinwhoffman** [comment]
## Structure and style all radio button and checkbox lists consistently

As of Give 1.8, radio button lists are styled via their ID. Core fields use unordered lists while FFM uses a div. This creates consistency issues with spacing and font sizing across themes.

**Comment by kevinwhoffman** [comment]
## Consider using JS hook classes to prevent JS/CSS conflicts

See http://cssguidelin.es/#javascript-hooks

**Comment by kevinwhoffman** [comment]
## Use implicit association for form labels with radios/checkboxes

By nesting radio/checkbox inputs within the label, we gain more control over styling. This would be beneficial in situations where:

* Labels appear on a separate line from the input due to `display: block` in some themes.
* Themes that use faux radios/checkboxes expect the input to be nested within the label. If not, it's possible to see duplicate inputs such as in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/1938671/24623005/04966494-1875-11e7-84e6-a3c97b95a321.png)

See https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-implicitly

**Comment by drzraf** [comment]
See 
https://github.com/WordImpress/Give/issues/1425
https://github.com/oomphinc/WP-Forms-API
https://wordpress.stackexchange.com/a/48367

**Comment by kevinwhoffman** [comment]
Closing since many of the issues identified here will be addressed in epic #2905 where we will develop the new Give Form API.
