### ISSUE TITLE
New Metabox API data-type=decimal/currency needs to trigger formatting when not focused

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1460]
## Issue Overview
The new Metabox API has a nice feature that allows you to add currency formatting to text fields. But Give has some nice JS to force the formatting on focusout here:
https://github.com/WordImpress/Give/blob/d20d81e315ee2d05328774d7002b085593c4e43d/assets/js/admin/admin-scripts.js#L858

But it doesn't work if you're adding a text-field with `data-type=price`

Here's the metabox array I used for testing this:

```
array(
                'id'         => $prefix . 'min_amount',
                'name'       => __( 'Minimum Donation?', 'givera' ),
                'desc'       => __( 'If you want the Attachment available only if the donor donates a minimum amount, enter that here. Otherwise leave blank.', 'givera' ),
                'type'       => 'text_small',
                'data_type'  => 'price',
            ),
```

It correctly formats the number on save and page refresh, but not on focusout.

**Comment by ravinderk** [comment]
@mathetos You have to add some extra class to `price` or `decimal` field data types.
Check this for reference 
https://github.com/WordImpress/Give-Settings-API-Example/blob/master/includes/class-metabox-setting.php#L186
https://github.com/WordImpress/Give-Settings-API-Example/blob/master/includes/class-metabox-setting.php#L198

**Comment by mathetos** [comment]
Thanks @ravinderk THat's perfect.
