### ISSUE TITLE
Allow Custom Amount to be the default on Multi-level forms

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1473]
## Issue Overview
Admins sometimes want the Custom amount to be the default amount for their multi-level forms. This would clear the Amount field and auto-focus the cursor in the amount field on page load.

User-request here:
https://wordpress.org/support/topic/make-default-option-blank/

**Comment by ravinderk** [comment]
@mehul0810 To resolve this we can create an additional setting in form meta box panel which will visible to admin only if form type set to `multi` and with this setting, admin set custom amount as default field.

Let me know if you have better solution

**Comment by mathetos** [comment]
@DevinWalker brought up some good concerns about this idea. It might not be ideal to allow this option. But, we do currently have a JS snippet that auto-focuses on the amount field that we can refer users to that works just fine:

https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/auto-focuse-on-amount.php
