### ISSUE TITLE
Check plugin related configuration with give-cli

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1474]
## Issue Overview

It will be good if we have a command which checks required configuration of the plugin in `give cli` and suggests user the best configuration tips.
`wp give doctor`

For example:
1. check if user setup plugin related pages or not.
( I am working on this list :) )

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
This is assuming that we have ssh access to the server and that the server has WP-CLI created. If this is to be used for troubleshooting purposes I don't think it would be of much help and rarely used.
