### ISSUE TITLE
Give Donor Profile not updating First/Last Name correctly

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1481]
## Issue Overview

When a donor's first/last name is updated via the `give_profile_editor` shortcode, it changes correctly in their WordPress User Profile, but not on the Donor Profile in WP-Admin.

This is the case with both the first and last names. The email address updates correctly though.

See screencast here:
http://somup.com/cbnXcNN8c

**Comment by mathetos** [comment]
Also note that this is with a logged-in user who had donations attached to their donor profile. It's also an Admin account. Not sure whether any of that is relevant to the bug, but just additional information for replicating it locally.

**Comment by kevinwhoffman** [comment]
This appears to be more general than the shortcode. If I update my name in the WordPress User Profile screen, it's not reflected in the Donor Profile either. This [`profile_update`](https://developer.wordpress.org/reference/hooks/profile_update/) hook should provide what we need to make the connection to the Give donor and update accordingly.
