### ISSUE TITLE
Donate button does not reappear if login is cancelled

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#1482]
## Issue Overview

This would be rare, but if a user clicks Login, then cancels because they need to create an account, the Donate button remains hidden.

## Steps to Reproduce (for bugs)

1. Create form with Registration + Login enabled.
2. View form while logged out.
3. Click "Already have an account? Login"
4. Notice that Donate button diseappers when Login form appears. This is expected since the form setting requires a registration.
5. Click Cancel button below login fields.
6. The Donate button should reappear but it is still hidden, preventing the form from being submitted even if the user fills out registration fields.

Give version: 1.8
WP version: 4.7.2

**Comment by ravinderk** [comment]
@kevinwhoffman There are styling issue when you click on login or cancel button. Can we fix that?

**Comment by ravinderk** [comment]
@kevinwhoffman There is also registration form style issue on bigger screen.

![screen shot 2017-02-20 at 11 11 01 am](https://cloud.githubusercontent.com/assets/1784821/23113333/7a9320e4-f75d-11e6-90ba-568c5fe605e9.png)

**Comment by kevinwhoffman** [comment]
@ravinderk Thanks for catching that. It looks you are on Twenty Fifteen in the single form template. This is a rare case where the theme uses a sidebar and the single form template template displays a featured image, which causes the form column to be very narrow. I will fix this issue for 1.8.2.

Looking forward, this is further evidence why the single form template should leverage the theme template, which I described in https://github.com/WordImpress/Give/issues/1457#issuecomment-279090015. If Give was using the theme template, then Twenty Fifteen would display the featured image above the form and the form would have twice the amount of room to display.
