### ISSUE TITLE
Show error message while visiting receipt page without payment_key

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1484]
## Issue Overview

If you visit receipt page without `payment_key`, it will show you a receipt with some PHP notices.

<img width="1083" alt="screen shot 2017-02-13 at 2 33 36 pm" src="https://cloud.githubusercontent.com/assets/1784821/22877041/91f5d510-f1f9-11e6-9fe8-952ac2e9e9cd.png">
 

## Expected Behavior

Appropriate error message.

## Current Behavior

I can see a receipt with PHP notices.

## Related PRs
List related PRs against other branches:

## Todos
- [ ] Error message while no `payment_key` defind
- [ ] Test

**Comment by ravinderk** [comment]
@DevinWalker `payment_key` should not be equal to shortcode `payment_key` argument on this line https://github.com/WordImpress/Give/blob/master/includes/shortcodes.php#L253.
Can you explain this?

**Comment by ravinderk** [comment]
@DevinWalker Closing this issue in favor of #1763

**Comment by DevinWalker** [comment]
Thanks @ravinderk
