### ISSUE TITLE
Add a filter/option for separate email templates for donor receipts and admin notifications

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1493]
## Issue Overview

Currently, if a user follows our tutorial here to create a custom email template: https://givewp.com/create-dramatic-donation-email-receipts/ that template is added to both the donor receipt and the admin notification.

## Expected Behavior
We should be able to only add that custom template conditionally to the donor receipt.

## Current Behavior
There's only one set of templates, which can be overridden in a child theme, but not just for donor receipts.
## Possible Solution
A filter in the build_emails() function?
Or, add to that tutorial to show how to just target one of the two types of emails.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
I believe this is going to be taken care of in 1.9 email improvements. @ravinderk can you confirm?

**Comment by ravinderk** [comment]
@DevinWalker @Benunc You can overwrite default template with this filter in `release/2.0`

https://github.com/WordImpress/Give/blob/release/2.0/includes/admin/emails/abstract-email-notification.php#L518

**Comment by tw2113** [comment]
With 2.0.0 out the door, is this issue already covered and good to close?

**Comment by DevinWalker** [comment]
Yeah thanks @tw2113 - here's the updated link to the filter: https://github.com/WordImpress/Give/blob/release/2.0.1/includes/admin/emails/abstract-email-notification.php#L537
