### ISSUE TITLE
Metabox order

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#15]
The default "Author" and "Excerpt" metaboxes should appear at the very end of the page if possible.
![metabox-order](https://cloud.githubusercontent.com/assets/930724/6610531/cc42cd7a-c81d-11e4-95fb-95c1f8236af7.png)

**Comment by mathetos** [comment]
I wonder if it's better to just keep all Form creation metaboxes together in one box? Or maybe that would make it hard for Add-ons to extend that capability in the future. Still, needs some concerted thought.

**Comment by DevinWalker** [comment]
Yeah it's been a hassle to get them in the proper order. CMB2 doesn't handle it very well. I'll get them in the proper order though. Nice bug report.

**Comment by DevinWalker** [comment]
@mathetos I don't think it's wise to lump them all into one giant metabox. It's a better user experience for us to keep sections separated into separate metaboxes. That being said, we definitely want to limit it so the number of metaboxes doesn't get out of hand.
