### ISSUE TITLE
Form Metabox API should have the ability to set a Give icon or Dashicon class name

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1506]
## Issue Overview

Let's give Add-on authors the ability to set a classname for any custom Form metabox tabs they add via their Add-on.

## Current Behavior
Currently, there is a default tab icon that is a right-arrow. Customizing this must be done via CSS, which requires the Add-on author to enqueue an additional CSS file and target their tab correctly. This is the current way new tabs are registered:

```
function add_givera_setting_tab($settings) {

        $settings['givera_options'] = apply_filters('givera_options', array(
            'id' => $this->prefix . 'givera_attachment',
            'title' => esc_html__('Receipt Attachments', 'give'),
            'fields' => apply_filters('givera_metabox_fields', $this->get_fields( "{$this->prefix}givera_attachment" )),
        ));

        return $settings;
    }
```

## Possible Solution
I'd suggest instead that we add a class-name variable when registering metabox tabs. Here's what the above code would look like with the new argument:

```
function add_givera_setting_tab($settings) {

        $settings['givera_options'] = apply_filters('givera_options', array(
            'id' => $this->prefix . 'givera_attachment',
            'title' => esc_html__('Receipt Attachments', 'textdomain'),
            'fields' => apply_filters('givera_metabox_fields', $this->get_fields( "{$this->prefix}givera_attachment" )),
            'class' => esc_html__('dashicons dashicons-clock', 'textdomain'), 
        ));

        return $settings;
    }
```

**Comment by DevinWalker** [comment]
Rather than a `class` name argument, it should be `dashicon` and then pass the desired icons' class name: 
![2017-02-16_16-53-53](https://cloud.githubusercontent.com/assets/1571635/23048092/92a07512-f468-11e6-8d89-250c541ed94d.png)

**Comment by ravinderk** [comment]
@DevinWalker I think `icon-class` param name will be more generic.
