### ISSUE TITLE
Settings pages return errors w/ Hebrew

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#1510]
## Issue Overview

Non-English navigation returns error pages. Some tab URLs are using translation functions. They should not. It breaks the link.

## Steps to Reproduce (for bugs)
1. Change the site language (to any non-english language).
2. Go to Give settings page.
3. Navigate to any tab and sub-tab.

**Comment by ravinderk** [comment]
@ramiy I changed the language to `Hindi` and it is woking fine for me. Can you provide us a screenshot?

![9rvfgfxjgd](https://cloud.githubusercontent.com/assets/1784821/23070276/957da5be-f550-11e6-9d52-e97c7d2a0681.gif)

**Comment by mathetos** [comment]
@ravinderk I think he means languages that have active translations for those tabs. If those tabs are a different language then the hyperlink is wrong.

**Comment by ramiy** [comment]
@ravinderk It seems like the `Hindi` language is not fully translated. Try using the `Hebrew` language. you will see the errors.

**Comment by DevinWalker** [comment]
I found an issue when the you'll see an error page due to the URL including the translated language:

![2017-02-23_13-34-32](https://cloud.githubusercontent.com/assets/1571635/23280140/ebaf32f6-f9cc-11e6-9b65-0629e76241f4.png)

**Comment by ramiy** [comment]
As mentioned above, the tab value in the URL should not use translation functions.
