### ISSUE TITLE
System info tab info is not txt-file friendly.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1512]
## Issue Overview

Currently if a user copies and pastes the output of the new system info into a txt file, it is tough to read.
## Expected Behavior
All elements should easily copy to txt format (since that's the format our support form allows)
## Current Behavior
![screen shot 2017-02-17 at 8 56 50 pm](https://cloud.githubusercontent.com/assets/9629102/23089231/c72f7a30-f553-11e6-8bcd-bb8ec9765d19.png)

## Possible Solution
Make all output of that button txt friendly.

## Steps to Reproduce (for bugs)
1. Copy/paste output of the "get System Info" button into a txt file, and email it to yourself. :smile:

## Related PRs
#1214 

## Todos
- [ ] Tests

**Comment by kevinwhoffman** [comment]
@Benunc I was not able to recreate, so I'm wondering if it's a system font issue with your machine not supporting that character. The missing character is an `&ndash;` which could simply be replaced with a `-`.

Is that the only character that appears that way (are the X's  and checkmarks okay)?

![image](https://cloud.githubusercontent.com/assets/1938671/23147744/3d52f612-f7af-11e6-9908-3fcca1f120d3.png)

**Comment by DevinWalker** [comment]
@Benunc I just tried it out too and wasn't able to reproduce. 

@Benunc @mathetos how many customers have been submitting reports with the `?` character present in the system info?

**Comment by Benunc** [comment]
Here's an example of one: https://secure.helpscout.net/conversation/321371696/0/?folderId=848135 (scroll to the original ticket, and click their system info txt file)

Maybe it's how helpscout displays it in their modal that is screwing things up, but so far since 1.8 every one in Helpscout shows badly for me. Tried in both chrome and safari.

**Comment by Benunc** [comment]
now that the field on the form is a text area thanks to @mathetos, I think this can be closed as irrelevant. people are no longer going to be attaching a file.
