### ISSUE TITLE
Easier Registration Process

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1517]
## Issue Overview

When a form requires or asks for registration, it makes the donor enter additional information that I think can be automated. We should make the process of registering on the site much easier.

## Options/Suggestions

Currently, we already ask for their first and last names and email address. If registration is optional or required, we then also demand that they enter a username and password:

![image](https://cloud.githubusercontent.com/assets/930724/23100544/ef5573d0-f638-11e6-999f-0293797f1303.png)

WordPress already has a Strong Password generator built into it. We should auto-populate the password fields with that, and allow the donor to SEE that password (for saving purposes). 

We can also create their username automatically with a combo of their first and last name.

Honestly, the best of ALL words would simply be that all they had to do was check a checkbox acknowledging that an account is being created based on their information. Then WordPress sends them the confirmation email with the necessary info anyway.

**Comment by ravinderk** [comment]
@mathetos @DevinWalker 
I would recommend not to have registration form at all instead we can have a checkbox which will ask donor to create account.On basis of email and random password will will register donor and donor can update there profile after login to there account.

**Comment by mathetos** [comment]
@ravinderk Exactly. That's what I'm aiming for as well.

**Comment by tevyaw** [comment]
What about just using their email address as the username? Other than that, I completely agree with all this. Sounds much better to have just a checkbox or something.

At very least, put the "Already have an account?" stuff down to the right of the "Create an account" header.
