### ISSUE TITLE
design(admin-report): gather examples of useful reports

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1527]
## Issue Overview
The reports for Give can be improved greatly. They can display information more intuitively and have a better user experience overall. The code for the current reports is also difficult to read and understand. 

## Nice Report Examples

**Baremetrics** - I really like how they display graphs overviews that you can then click into:

![2017-02-21_11-57-59](https://cloud.githubusercontent.com/assets/1571635/23182319/ff6097fa-f82c-11e6-9c7c-f51e4f7ffee2.png)

![2017-02-21_11-58-51](https://cloud.githubusercontent.com/assets/1571635/23182348/1e19fb64-f82d-11e6-9b23-49cb32ee3d6b.png)

Check it out: https://demo.baremetrics.com/stats/

**Stripe** - These graphs are very simple to understand. You can't drill down into the reports like baremetrics, though. I believe it would best to try something like this as an MVP that we can then iterate upon to have more data points. 

![2017-02-21_12-00-01](https://cloud.githubusercontent.com/assets/1571635/23182410/4cc98470-f82d-11e6-8d7e-f50d3fe42996.png)

**Codepen 1** Really nice animations. 
http://codepen.io/deep1808/pen/yNQGZe 

![2017-02-21_13-38-30](https://cloud.githubusercontent.com/assets/1571635/23186269/582b73ba-f83b-11e6-9543-ebc04a4faeb5.png)

**Codepen 2** Nice dashboard overview http://codepen.io/Ruddy/pen/xbJXyQ
![image](https://cloud.githubusercontent.com/assets/1571635/23186337/a2f14f64-f83b-11e6-9412-9b4c78ee210b.png)

**HelloSales** Better WooCommerce reporting by iThemes:
![2017-08-02_13-47-18](https://user-images.githubusercontent.com/1571635/28894296-3cc44f20-7789-11e7-8caa-7c26e8308e1d.png)

**Comment by DevinWalker** [comment]
**Note:** The "Donors" report as it stands now is basically a less data-rich "report" than our donor's list view:

![2017-09-13_16-13-19](https://user-images.githubusercontent.com/1571635/30405070-aae9a3e8-989e-11e7-9d25-f7df6a45344d.gif)

We should probably just remove this until we can get around to the revamp since it's just taking up unnecessary space.

**Comment by marutim** [comment]
We should include a way to view stats/reports on recurring Donations. Should be able to see the total income made out of recurring donations.

**Comment by kevinwhoffman** [comment]
**Google Analytics** - I thought this was a clever way to show multiple sources contributing to a total while staying within a similar color palette. Consider this chart using Give green instead of blue.

One possibility would be Donations Per Day where each bar represents the total donations for that day broken down by donation size:

- < $10
- $10-$100
- $100-$500
- \> $500

![image](https://user-images.githubusercontent.com/1938671/34562882-488b4480-f11e-11e7-9a2c-2f71ddea0833.png)

**Comment by DevinWalker** [comment]
I think we've gathered enough reports to warrant closing this issue.
