### ISSUE TITLE
Hyphen in icomoon fonts triggers security warnings

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1535]
## Issue Overview

As reported here:
https://wordpress.org/support/topic/server-security-issues-ip-address-blocked-after-installation/#post-8837497

We had a similar issue with loading the icomoon TTF font:
https://github.com/WordImpress/Give/issues/794

According to the ticket, if we just remove the hyphens then we're good.

**Comment by DevinWalker** [comment]
Additional context: https://github.com/copyblogger/simple-social-icons/issues/19
