### ISSUE TITLE
Add filter to give_build_paypal_url() for extensibility

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1536]
## Issue Overview

Users might want to send additional info to PayPal Standard for every donation. Adding a filter to the paypal URL would make that fairly easy.

## Current Behavior

Currently, our PayPal URL does not have any filters, as seen here:
https://github.com/WordImpress/Give/blob/master/includes/gateways/paypal-standard.php#L647-L705

## Expected Behavior
Add a filter so additional information can be passed upon each donation.

**Comment by ravinderk** [comment]
@mathetos We can add extra data with this filter.
https://github.com/WordImpress/Give/blob/master/includes/gateways/paypal-standard.php#L718

**Comment by mathetos** [comment]
@ravinderk I wondered about that one, but does that actually SEND data to PayPal, or is that for redirecting back FROM PayPal?

If it sends data TO PayPal, what would a filter look like, if you wanted to send the `item_number` attribute to PayPal (that's a real attribute that PayPal supports that we don't currently send)?

**Comment by DevinWalker** [comment]
@ravinderk is right, that's the proper filter to use. With PayPal Standard you built a URL with query args and then PP interprets that. See: https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/
