### ISSUE TITLE
Consider removing dependency on admin-ajax.php

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1539]
## Issue Overview

Some hosts block access to admin-ajax.php on the front-end. This basically prevents those users from being able to use Give effectively. Can we look into ways we can avoid that dependency completely?

## Possible Solution
Here's a really great write-up from the Delicious Brains folks on using the REST API instead of admin-ajax.php:

https://deliciousbrains.com/comparing-wordpress-rest-api-performance-admin-ajax-php/

**Comment by mathetos** [comment]
I think this point here is the most important from that article:

> Unlike requests sent over admin-ajax.php, the REST API doesn’t load the WordPress admin section via /wp-admin/admin.php, nor does it fire the admin_init action hook. Based on that, it’s likely that any plugins or themes that don’t rely on admin-specific functionality – but are using admin-ajax.php – should see a slight performance boost by switching over to the REST API.

**Comment by DevinWalker** [comment]
I think this would be good to implement once the REST API has been rolled out further into the WP landscape. It has now just been included within WP 4.7+ and to dump admin-ajax.php could leave a good portion our users inoperable. It would also be a big overhaul of how our plugin works currently for a "slight performance boost". Seem like the best idea is for us to work to minimize the number of `admin-ajax.php` requests and for our customers to use a decent host on PHP7. We can revisit this in the future as well.

**Comment by mathetos** [comment]
@DevinWalker That makes sense. But just to clarify, my primary motivation for dumping `admin-ajax.php` isn't the performance boost, but that it creates serious support issues because of how it gets blocked on the front-end in weird and difficult to reproduce ways. Performance concerns are secondary.

**Comment by DevinWalker** [comment]
Sometimes those are false positives due to the admin warning which we are looking to improve in #1631
