### ISSUE TITLE
Registration + Login is not working when guest donation is enabled on 1.8.3

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1553]
## Issue Overview

If the user has set Guest donations to "enabled" and Registration to "Registration + Login" the form returns "Enter an Username" even though the fields are marked as "optional"

## Expected Behavior
The username field should be optional if guest donations are enabled.

## Current Behavior
The fields are not validating correctly.

## Steps to Reproduce (for bugs)
1. Fresh install of Give 1.8.3
2. set the fields like this: 
![screen shot 2017-02-28 at 10 37 52 am](https://cloud.githubusercontent.com/assets/9629102/23412034/45200076-fda2-11e6-95a7-d6f200e28dc3.png)

3. attempt a logged out donation and don't enter a username
4. You'll get this:
![screen shot 2017-02-28 at 10 40 47 am](https://cloud.githubusercontent.com/assets/9629102/23412061/6563500e-fda2-11e6-9de2-d9732135fb5a.png)

Also, shouldn't that be "A Username" not "An Username" http://english.stackexchange.com/questions/105116/is-it-a-user-or-an-user

**Comment by DevinWalker** [comment]
- [ ] Isolate validation issue 
- [ ] Fix validation issue
- [ ] Fix typo
- [ ] Test
