### ISSUE TITLE
Recalculate for ALL Forms doesn't work for All forms

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1554]
## Issue Overview

The "Recalculate Income Amount and Donation Counts for ALL Forms" doesn't affect the total donations or income shown on the "All Forms" screen.

## Current Behavior
Currently, if you run this tool it won't update the "Donations" column or the "Income" column on the "All Forms" screen. But if you instead use the "Recalculate Income Amount and Donation Counts for a Form" tool, it will work as expected.

## Expected Behavior
The expected behavior is that it will properly update all the donation counts and income for ALL forms.

## Steps to Reproduce (for bugs)
1. Install the Duplicate Post plugin
2. Duplicate one or two forms that have multiple donations on them
3. You'll see that the donation count and income are carried over, but if you click on those links they lead to ZERO results in the Report and/logs screens (which is correct because NO donations were made to those new forms)
4. Run the "Recalculate Income Amount and Donation Counts for ALL Forms" and see that it didn't work
5. Run the "Recalculate Income Amount and Donation Counts for a Form" and see that it DOES work as expected.

**Comment by DevinWalker** [comment]
Hmm, you sure that column data isn't cached?

**Comment by mathetos** [comment]
As I mentioned in the step to reproduce, it works correctly with the individual form tool, but not the ALL forms tool. I think that rules out caching.
