### ISSUE TITLE
Not compatible with php 7.0

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#1575]
Hi

I just downloaded the SiteGround SG Optimizer. It offers three features:
SuperCacher Config
HTTPS Config
PHP Config -

PHP Config
This tool will allow you to check if your website is compatible with the recommended by SiteGround PHP version and switch to it with a click. It is highly advisable to keep your WordPress running on the recommended PHP for best security and performance.

Notice: checking your site for PHP 7.0 compatibility....

One of the plugins not compatible is Give.

Error message:
FILE: /home/easyweb7/public_html/easywebdesigntutorials.com/wp-content/plugins/give/includes/libraries/fpdf/fpdf.php
--------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------
 1044 | ERROR | Function set_magic_quotes_runtime() is deprecated since PHP 5.3 and removed since PHP 7.0
--------------------------------------------------------------------------------------------------------------------

FILE: /home/easyweb7/public_html/easywebdesigntutorials.com/wp-content/plugins/give/includes/libraries/browser.php
------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------
 219 | WARNING | Use of deprecated PHP4 style class constructor is not supported since PHP 7.
------------------------------------------------------------------------------------------------------------------

**Comment by mathetos** [comment]
Hi @paaljoachim -- There are some functions in Give which are there specifically for backward compatibility. These types of compatibility checkers don't confirm or verify whether the plugin "works" on PHP7, they just scan for deprecated functions. In our case those functions are there specifically for users who are on older versions of PHP.

We develop Give on PHP7 daily and have done so for over a year. Test it out and you'll see it works great.

Thanks!

**Comment by paaljoachim** [comment]
Thanks Matt!
