### ISSUE TITLE
Not Obvious that Custom Text is Required

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#158]
If the "Custom Amount Text" field is empty, then the Custom field doesn't show on the form at all. I would suggest two things:
1) Having the field filled by default with the current placeholder text. Once they click "Yes" to Custom field, their intention is already clear, so we don't need them to verify again by inserting text. That way, at least the field will show and when they preview the form they'll see what they expect and know that they can customize the text
2) The wording for the label description should be something like this:
"Customize your Custom Amount label here. Removing the text will remove the Custom field completely." -- this keeps it short and sweet and very direct.

![2015-06-17 10_24_14-edit form mysite wordpress](https://cloud.githubusercontent.com/assets/930724/8214086/a5a8af12-14db-11e5-8e73-fa9660895dfe.png)

**Comment by DevinWalker** [comment]
The field should show regardless of whether the field has data in it or not. The user has selected "Yes" for the custom amount so it should display.

**Comment by mathetos** [comment]
That's a good option too. But what will show if there's no text in the field? You'll set the placeholder as the default output?

**Comment by DevinWalker** [comment]
Yeah, exactly
