### ISSUE TITLE
Give Plugin Breaks Eform Plugin Quizes

### ISSUE THREAD

**Issue by johnsie** [WordImpress/Give#1584]
## Issue Overview

When I activate the" Give" plugin it prevents pages which alreadt use the Eform plugin from loading

## Expected Behavior

When I activate Give plugin the quiz I have created with eform should load. Both plugins should be able to be used on the same site.

## Current Behavior
When I active the Give plugin and then go to a page which uses the eform plugin the eform quiz just says "loading" and never loads. The only way to prevent this from happening is by disabling the Give plugin.

## Steps to Reproduce (for bugs)

1. Install eform plugin and create a quiz. Test to make sure the quiz works
2. Install and activate Give plugin. 
3. Go to the page with the quiz on it and now it wont work.

## Related PRs
List related PRs against other branches:

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@johnsie Which version of Give you are using.

**Comment by DevinWalker** [comment]
@johnsie seeing as this is a paid plugin, would you mind providing a dropbox/drive link to download the zip? That way we can test with it. We will also remove the link once it's downloaded.

**Comment by johnsie** [comment]
Hi, I don't think I can give you a zip of that, but I'll contact the developers of that plugin to see if they are willing to help with that.

**Comment by johnsie** [comment]
Also, I don't know if this is related but I get this in the developer console in chrome:

```
Uncaught TypeError: jQuery(...).qtip is not a function
    at setup_give_tooltips (give.all.min.js:8)
    at HTMLDocument.<anonymous> (give.all.min.js:8)
    at i (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at Function.ready (jquery.js:2)
    at HTMLDocument.K (jquery.js:2)
```

**Comment by swashata** [comment]
Hi

I am the developer of eForm plugin and I will see what the issue is. If it is anything that can be solved from my end I will definitely sort it out.

@DevinWalker kindly provide an email address. I will add you to our private gitlab.

**Comment by DevinWalker** [comment]
Hey @swashata you can use sdtucson@gmail.com

**Comment by johnsie** [comment]
Any news on a fix yet? We're keen to get working with  the plugins that we bought (eform/paypal pro and recurring purchases)

**Comment by swashata** [comment]
Sorry for the delay. @DevinWalker I have added you to our gitlab project. It is hosted under iptlabz.com You should have received an email with password reset link.

**Comment by johnsie** [comment]
Hi.  Found the problem. Found two references to jquery.js that were conflicting with each other:.

I think one  plugin was printing this:
<script type='text/javascript' src='https://........./wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>



And we already had included jquery.js in our footer.php:

<script type="text/javascript" src="<?php bloginfo('template_directory'); ?>/js/jquery.min.js"></script>


So probably two versions conflicting with each other.  Removing the line from the footer.php resolved it.

**Comment by swashata** [comment]
@johnsie So basically it was coming from the theme? Not from any of the plugin. I am pretty sure that both Give and eForm shares the same jQuery by calling `wp_enqueue_script( 'jquery' );`

**Comment by johnsie** [comment]
Pretty sure it  was a jquery version conflict between the theme and plugins. The theme was trying to load jQuery v1.10.2  and I think the plugins wanted to use  jQuery v1.12.4

Hopefully this thread will be useful in case anyone runs into similar problems. Getting them all to use the version that comes with Wordpress (currently jQuery v1.12.4) and adjsuting the custom scripts with the theme work with that version resolved it.

Thanks four your help.

**Comment by ravinderk** [comment]
@johnsie Glad to see that your issue resolved.
