### ISSUE TITLE
Give API not sending Billing Fields

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1587]
## Issue Overview

The credit card billing fields are not sent over the Give API

## Current Behavior
Specifically with Stripe, the Give API is not outputting Billing field data at all.

## Expected Behavior
It should support those fields similarly to how we support custom fields.

## Steps to Reproduce (for bugs)
1. Do a test donation with Stripe
2. Check your API url
3, Note that billing fields are not returned there at all.

**Comment by DevinWalker** [comment]
Duplicate of https://github.com/WordImpress/Give/issues/1587

**Comment by mathetos** [comment]
@DevinWalker this is issue #1587 ... what is this a duplicate of exactly?

**Comment by mathetos** [comment]
Actually I see it now. Duplicate of #1112
