### ISSUE TITLE
give_get_current_page_url() should really trailing slash it

### ISSUE THREAD

**Issue by sc0ttkclark** [WordImpress/Give#1589]
## Issue Overview
give_get_current_page_url() should really be having a trailing slash, right now it untrailing slashes it

## Expected Behavior
Page at /my-page/ outputs a form action with /my-page/?xyz=12345 (xyz being whatever GiveWP adds for payment method, etc)

## Current Behavior
Page at /my-page/ outputs a form action with /my-page?xyz=12345 (xyz being whatever GiveWP adds for payment method, etc)

## Possible Solution
Add a trailing slash unless permalinks on site are not in use (?p=1234)

## Steps to Reproduce (for bugs)
1. Embed a form in a page
2. Go to the page (with the trailing slash)
3. Look at form HTML

## Why this is a problem
Some sites (like ours at Pods) have an .htaccess redirect to ensure all folder-looking paths have a trailing slash. This breaks the form submission process with GiveWP.

**Comment by DevinWalker** [comment]
Thanks @sc0ttkclark - I've been meaning to improve that function recently. I'll add this to the upcoming point release.
