### ISSUE TITLE
PHP notice

### ISSUE THREAD

**Issue by helgatheviking** [WordImpress/Give#159]
When viewing a form on the front end with `WP_DEBUG` enabled I am seeing

>Notice: Undefined index: _give_price in /wp-content/plugins/give/includes/forms/template.php on line 323

**Comment by helgatheviking** [comment]
Tracking that down, it seems like line 323 is

```
$output .= ( ! empty( $price['_give_text'] ) ? $price['_give_text'] : $price['_give_price'] );
```

and maybe should be

```
$output .= ( ! empty( $price['_give_text'] ) ? $price['_give_text'] : give_currency_filter( $price['_give_amount'] ) );
```

**Comment by mathetos** [comment]
Hi kathy,

Are you working from the latest master here, or from the WordPress repo version? We'd welcome a pull request if you'd like to be a contributor.

**Comment by helgatheviking** [comment]
I'm working from the repo version. For something this small it doesn't seem worth it to create my own fork.

**Comment by mathetos** [comment]
Sure. No problem. I need to double-check with @DevinWalker but I believe the current Master is ahead of the current Repo so that might be a new issue. Thanks!

**Comment by michaelbeil** [comment]
What is the status of the current master branch @mathetos in relation to the .org repo?

**Comment by helgatheviking** [comment]
On this issue at least, the master was the same as the .org version. PR sent #160.
