### ISSUE TITLE
Form doesn't change when user selects payment method

### ISSUE THREAD

**Issue by johnsie** [WordImpress/Give#1590]
## Issue Overview

When the user selects a payment gateway using the radio the form doesn't change.

## Expected Behavior
If the user selects Paypal or Offline then it shouldn't still be asking for payment details

## Current Behavior
It still asks for a credit card when offline or paypal has been selected by the user

## Possible Solution
Could be something javascript related

## Steps to Reproduce (for bugs)

1. Go on to the donate form to make a donation
2. Select which payment method you wish to use

![donate](https://cloud.githubusercontent.com/assets/1310690/24407526/121a28be-13c3-11e7-9d7a-b422533a81ad.gif)

**Comment by Benunc** [comment]
Hi there,

I am happy to help on the support ticket (which you have already submitted!) We will get to the bottom of this. Thanks!

**Comment by DevinWalker** [comment]
This is likely being caused by a JS error on page. @Benunc can help you with that over on our support side. Thanks!
