### ISSUE TITLE
Uncaught TypeError: jQuery(…).qtip is not a function

### ISSUE THREAD

**Issue by johnsie** [WordImpress/Give#1591]
## Issue Overview

JS console in Chrome gives the following message:

Uncaught TypeError: jQuery(...).qtip is not a function
    at setup_give_tooltips (give.all.min.js?ver=1.8.5:8)
    at HTMLDocument.<anonymous> (give.all.min.js?ver=1.8.5:8)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
setup_give_tooltips @ give.all.min.js?ver=1.8.5:8
(anonymous) @ give.all.min.js?ver=1.8.5:8
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2

## Expected Behavior
No error message

## Current Behavior
See above

![image](https://cloud.githubusercontent.com/assets/1310690/24413877/b335384a-13d4-11e7-9778-08b013623b30.png)

**Comment by DevinWalker** [comment]
Hey there - Try moving your scripts into the footer under WP-Admin > Donations > Settings > Advanced. We are also looking into removing qtip for a pure CSS solution. FInally, this is more of a  support request which should asked here: https://wordpress.org/plugins/give
