### ISSUE TITLE
FEATURE/ADDON REQUEST. Kiosk mode + Incorporating with a card swiper/chip reader.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1594]
## Issue Overview

Customer request. The idea is a way for Nonprofits at a booth to have a way for people to give on the spot, using a card reader or other technology to process the transactions, and also to be able to facilitate seamless transition from one donor to the next in terms of session management. 

## Expected Behavior
A few things to consider:
1. The actual collection of the payment info, and securely processing it while at the same time not storing it on the site's servers
2. How to deal with cookies/logged-in users/sessions for the kiosk. Might be as simple as using incognito mode on a browser, but we'd want to be able to ensure that users are directed to the correct donation confirmation page, etc.

## Possible Solution
It might also be worth exploring a Give-branded card reader in conjunction with Stripe or other gateway.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
I think the solution is really integrating with Square to begin with. I don't think it is realistic to have our _own_ card ready solution currently.  

Take a look at: https://squareup.com/pos/organizations and https://woocommerce.com/products/square/

Closing this one out.

**Comment by Benunc** [comment]
Another request for this functionality today.
