### ISSUE TITLE
The plugin outputs HTML that does not pass validation

### ISSUE THREAD

**Issue by chetzof** [WordImpress/Give#1604]
## Issue Overview
Great plugin, good work!
The problem is that it outputs HTML that does not pass validation.

## Expected Behavior
The plugin outputs HTML compliant code

## Current Behavior
![image](https://cloud.githubusercontent.com/assets/467230/24795668/d2609938-1b92-11e7-9054-7b62c0b18ed7.png)
![image](https://cloud.githubusercontent.com/assets/467230/24795678/deb457b0-1b92-11e7-9398-cbdd631afd27.png)
![image](https://cloud.githubusercontent.com/assets/467230/24795688/eac04e56-1b92-11e7-8b74-b4bcf3611a50.png)
![image](https://cloud.githubusercontent.com/assets/467230/24795698/f0b2a8e0-1b92-11e7-9508-d24f23ad48e3.png)

## Steps to Reproduce (for bugs)
1. Render the shortcode "[give_form id='1' show_title='true' show_goal='true' show_content='above' display_style='button']
2. Run W3C validator

**Comment by DevinWalker** [comment]
Will be resolved within #1038
