### ISSUE TITLE
Rendering two give forms shortcodes on the same page results in duplicated IDs and invalid code

### ISSUE THREAD

**Issue by chetzof** [WordImpress/Give#1605]
## Issue Overview

Rendering two give forms shortcodes on the same page results in duplicated IDs and invalid code

## Expected Behavior
The IDs are not duplicated

## Current Behavior

![image](https://cloud.githubusercontent.com/assets/467230/24795954/dbffe164-1b93-11e7-8eb5-d3110a01395a.png)

## Possible Solution
Use classes instead of ID's where possible, in other cases use IDs with form ID suffix
give-first -> give-first-403

## Steps to Reproduce (for bugs)
1. render two shortcode donation forms
2. run W3C check

**Comment by chetzof** [comment]
I realize it might results in some backward incompatibility, still hopefully there is a good solution for this.

**Comment by DevinWalker** [comment]
Hey @chetzof - we are working to resolve this issue with #1038 - yes, this will result in some custom CSS or JS breaking, but the form layouts will be semantically correct and you won't see those errors anymore like you see in the screenshot. It's a tradeoff I see worth it, as it's an easy fix for your custom code and will result in better accessibility as well. Thanks for your issue, I'm going to close it out in favor for the one we are currently working on. Please let me know if you have anymore questions!
