### ISSUE TITLE
can't extend statuses

### ISSUE THREAD

**Issue by drzraf** [WordImpress/Give#1606]
## Issue Overview

It's nowhere possible to add additionnal donation statuses
Implement:
* `init` (for register_post_type_statuses)
* `give_payment_statuses`
* `give_payments_table_views`
* `wp_enqueue_scripts` (for the `.give-donation-status.status-*` css directives)
* `give_update_payment_status`

## Expected Behavior
Should be able to fully use a brand new custom status

## Current Behavior
Won't work
Because most of this hooks apply to `includes/admin/payments/class-payments-table.php` and make use of a private ``$this->[STATUS]_count`` property of this class which can't (AFAIK be fully inherited)
The values of this attributes are set from the SQL Query inside ``give_count_payments()``.
And no hook allow us to create/set a new `STATUS_count` attribute inside this function neither inside ``get_payment_counts()``

## Possible Solutions
* Fix `includes/admin/payments/class-payments-table.php` so that it does not hardcode so much of the statuses.
* Use SQL group by + generic way of fetching statuses count
* Allow/suggest a recommended class inheritance procedure
* Provide useful hooks
* Make a Give_Status PHP interface and provide a way to register more of them
* ...

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Hi @drzraf I've created the following snippet that demonstrates how to add statuses: https://github.com/WordImpress/Give-Snippet-Library/blob/master/admin-functions/custom-payment-status.php 

Let me know what you think and how we may be able to improve how custom statuses are handled.

**Comment by drzraf** [comment]
thank you very much for the snippet.
I will look at it ASAP

**Comment by DevinWalker** [comment]
No problem
