### ISSUE TITLE
Access Link e-mails should be an editable e-mail template, not hard-coded.

### ISSUE THREAD

**Issue by Asparagirl** [WordImpress/Give#1607]
## Issue Overview
Most e-mails that Give sends out are customizable to some degree -- except for the Access Link e-mail, which is hard-coded.  This should be a template too.  Here's where the code lives: https://github.com/WordImpress/Give/blob/465f799aa756986dc7ece579302772dc28d79a39/includes/class-give-email-access.php#L198

## Expected Behavior
I should be able to edit at least the basics of this e-mail, like the text or the signature.

## Current Behavior
I can't edit it at all.

**Comment by ravinderk** [comment]
@Asparagirl We are working refactor email setting and after that, all emails will be editable from admin setting.

for ref: https://github.com/WordImpress/Give/issues/1346

**Comment by Asparagirl** [comment]
Great!
