### ISSUE TITLE
Translations don't seem to take

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#161]
A user contacted me about translating into Spanish. He couldn't get his first couple translations to appear in the plugin correctly. He sent me his files, I checked them in Poedit, then tested locally both with his translation files and with our Brazilian Portugese files and neither appeared on the front-end of the dev site at all. Here's his screencast:

http://www.screencast.com/t/Zir13kiaksp

I took a look at `load_textdomain()` and it seems all fine, so I'm a bit stumped.

**Comment by DevinWalker** [comment]
Ok so the translation files need "give-" prepended to it. I've prepended it for our Brazilian Portuguese and it's working well. I'd love to get spanish too!

Closed with 2ffa17e
