### ISSUE TITLE
Decimal Rounding bug in PHP 5.4

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1618]
## Issue Overview

Several customers have reported that their amounts are being rounded even when they have the Decimals setting set to "2". Each customer was on PHP 5.4 or older. Each customer reported that when upgrading their PHP version, it resolved the problem. 

## Expected Behavior
The decimals should always be respected regardless of PHP version.

## Current Behavior
It seems that users on PHP 5.4 are always having their amounts rounded to the nearest whole, regardless of the decimals setting. Here's an example:
https://secure.helpscout.net/conversation/345961586/6860/?folderId=672201

**Comment by DevinWalker** [comment]
I just tested in PHP 5.4:

![2017-04-14_10-54-05](https://cloud.githubusercontent.com/assets/1571635/25051357/025f783e-2101-11e7-9a55-4124573d70aa.png)

![2017-04-14_10-57-49](https://cloud.githubusercontent.com/assets/1571635/25051396/3c676316-2101-11e7-9ccc-4f4c2dc53b46.png)

Closing until reproducible.
