### ISSUE TITLE
Change the "placeholder" address for offline donations

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1620]
## Issue Overview

Customer reported this. When there's an error which causes the offline donation email to default to the boilerplate, the 123 G Street address looks too legitimate, and donors mail checks there.

We should have the placeholder address be something like "111 Not A Real St. Anytown, CA, 12345" or similar, to prevent checks being mailed to 123 G St.

## Expected Behavior
A placeholder address should not be deliverable.

## Current Behavior
Our placeholder address is deliverable.

## Possible Solution
Change the address here: https://github.com/WordImpress/Give/blob/master/includes/gateways/offline-donations.php#L401

**Comment by Benunc** [comment]
Ticket, for reference, where the developer got in hot water with the nonprofit Board: https://secure.helpscout.net/conversation/346360510/6871/?folderId=672199

**Comment by DevinWalker** [comment]
You said: 

> When there's an error which causes the offline donation email to default to the boilerplate

Can you describe this error? Do you mean user error or is it a bug? When does this error occur?

**Comment by Benunc** [comment]
It was related to not updating the DB after 1.8.x so mostly user error. I can't remember another time that it happened.

**Comment by DevinWalker** [comment]
Gotcha. Well, the developer should have ran the update but regardless we should update the address so it doesn't look so real. I just wonder how many donation checks went to 123 G Street... :(
