### ISSUE TITLE
Make New User Notification email filterable

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1623]
## Issue Overview
Currently when a new user is created in the process of a Give donation, Give sends out an email to both the donor and the site admin notifying them of their new account. These emails' contents should be filterable.

## Expected Behavior
Anything that Give sends out should ultimately be configurable/filterable. This Function is currently working the magic: https://github.com/WordImpress/Give/blob/3c0417945a510b5cf249ef17a60ed96daf9c275d/includes/user-functions.php#L552

## Current Behavior
Currently that content is hard-coded. 

## Possible Solution
Add an apply_filters() somewhere in here: https://github.com/WordImpress/Give/blob/3c0417945a510b5cf249ef17a60ed96daf9c275d/includes/user-functions.php#L552
 
## Related PRs
#1577 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
We used the new user notification email to use `Give_Emails` which contains filters like `give_email_message` so the admin can adjust the content of the email. As well, we will be adding a UI interface in `release/2.0` that @ravinderk is currently working on that will enable less code savvy admins to easily adjust it with an editor. For now though, use the filter which will be available once we release `1.8.7`.
