### ISSUE TITLE
Make "Email already in use" error more explanatory.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1624]
## Issue Overview

Give checks to see if a user who is logged in is trying to make a donation using an email that already exists in the Give donors database. If it does, it outputs this error:

![screen shot 2017-04-17 at 2 24 02 pm](https://cloud.githubusercontent.com/assets/9629102/25099268/8fac35cc-2379-11e7-8248-3c2c5cf7b5e5.png)

That error message is not clear as to why exactly that's a problem. I've been confused by it, and today got a support ticket from a confused customer.

## Expected Behavior
The error message should say something like 

> You are logged in as admin@example.com, and are submitting a donation as leroy@jenkins.com, which is an existing Give Donor. To ensure that the email address is tied to the correct donor, please submit this donation from a logged-out browser, or choose another email address.

Or, even better, Give should be able to tie the donation made to that already existing donor, as it does for a logged out donor. That's outside the scope of this issue, though I could write a separate one if that seems appropriate.

## Current Behavior
The error message is confusing.

## Possible Solution
Update this line with a more instructive error: https://github.com/WordImpress/Give/blob/3c0417945a510b5cf249ef17a60ed96daf9c275d/includes/process-donation.php#L191

## Steps to Reproduce (for bugs)
1. On a clean install, submit a donation as leroy@jenkins.com
2. Then log into an account other than the one associated with leroy@jenkins.com
3. Submit a new donation while logged in as the other user
4. You'll get the error message above.

**Comment by mathetos** [comment]
Great ticket @Benunc Totally agree.
