### ISSUE TITLE
User request: Implement Express checkout for PayPay Standard

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1629]
## Issue Overview

Paypal has a (new?) Express checkout flow that keeps donors on the site throughout the transaction.

https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/checkout-flow/

## Expected Behavior
This would involve loading the checkout.js along with GIve, and keep users on the site.

## Current Behavior
Currently, users are directed away from the site to Paypal

## Possible Solution
Follow the developer integration guide here: https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/checkout-flow/

We'd need to make this an opt-in feature to pretect backward compat as far as user experience goes.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Issue moved to [WordImpress/Give-PayPal-Pro #46](https://github.com/WordImpress/Give-PayPal-Pro/issues/46) via [**ZenHub**](https://www.zenhub.com/)

**Comment by DevinWalker** [comment]
This is called "PayPal Express" and we're planning on integrating it within the pro add-on. I'm going to move this issue over there.
