### ISSUE TITLE
Ability to Add Manual Transactions in the backend

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#163]
Several users have requested the ability to add manual transactions via the backend.

**Comment by DevinWalker** [comment]
I think this is Add-on territory

**Comment by mathetos** [comment]
No, I think it's pretty basic functionality, specifically for small orgs that get a lot of checks handed to them at the office or offering plate. WooCommerce, for example, allows you to create manual orders in the backend in their Core.

**Comment by DevinWalker** [comment]
@mathetos can you provide any examples of how this would function? I'm assuming this would be it's own menu item? Or would it be under Give > Settings?

**Comment by DevinWalker** [comment]
@mathetos I'm setting this on the 1.6 milestone - if you could expand upon the general idea how this would work when you have time that would be great!

**Comment by mathetos** [comment]
I think it would be just like adding a new post. From the user end, we basically add an "Add New Transaction" button next to the "Transactions" page title (just like it in with Pages and Posts),  and that takes them to the Add New CPT page.

On the code side, I think we'd have to do this:

* Add `'show_ui' => true` to the post type -- this enables the default ability to add new posts for that post type
* Hide the sidebar navigation menu item that shows up because of adding the `show_ui` argument
* Add all the relevant metaboxes to that new post type.

Things like the payment ID and Transaction ID should be generated automatically. Items like the Form and user should be drop-downs generated from the available forms and users, etc.

It's not "easy" to accomplish, but I think the functionality is really basic for e-commerce particularly for donations since many transactions would happen offline and forcing admins to add via Offline Donations isn't as intuitive or flexible.

**Comment by cklosowski** [comment]
@mathetos @DevinWalker Is this basically like adding the EDD Manual Payments extension into your Give core? If so, you might take some hints from https://github.com/easydigitaldownloads/edd-manual-purchases. It's what we've been using for quite a while on the EDD site.

**Comment by DevinWalker** [comment]
@cklosowski check that out! Cool!

**Comment by cklosowski** [comment]
:) It's an add-on for EDD, but might help you guys quickly get one integrated for Give wether you choose to go Add-On or Core enhancement.

**Comment by DevinWalker** [comment]
Personally, I think it should be an Add-on too... your price point is nice too for this type of functionality.

**Comment by mathetos** [comment]
The jury's still out on that. I think manual transactions for donations is much more common that for products, so there might be justification for Core still.

Thanks for having our back @cklosowski

**Comment by cklosowski** [comment]
@mathetos oh yeah I get that argument. I don't really have an opinion on your side wether it should be in core or an addon for the Give ecosystem...I just wanted to make sure you guy had starting point either way.

**Comment by DevinWalker** [comment]
Great, thanks for restarting the debate from October Chris! Jeez. Matt and I argue enough as it is! Jk jk :laughing:

**Comment by BurlesonBrad** [comment]
Use case would be **...infinite:** Old blue haired lady gives cash for kid's mission trip. Aunt Bertha writes check for kid's mission trip. Uncle LeeRoy gives Aunt Theresa a check for surgery. _...on and on and on_

**Un**solicited Opinion :stuck_out_tongue_winking_eye:  : For support and continued development, make it a very low priced add on.

**Comment by DevinWalker** [comment]
Thanks @BurlesonBrad I agree, cheap Add-on. I was thinking $15 for single site sounds good. What do you think?

**Comment by BurlesonBrad** [comment]
the _support_ aspect shouldn't be much....
#shipit

**Comment by DevinWalker** [comment]
Closing out since we're agreed this is Add-on territory
