### ISSUE TITLE
Fix admin ajax warning's false positives or remove altogether

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1631]
## Issue Overview
This has been a common support issue and I noticed it when developing locally:
![2017-04-19_17-28-00](https://cloud.githubusercontent.com/assets/1571635/25207798/abaa6a7a-2525-11e7-9c85-428b6d04526c.png)

## Expected Behavior
Warning only displays when an issue is definitely present. 

## Current Behavior
Warning displays when admin ajax is working in some cases.

## Possible Solution
- Determine issue
- Remove warning if not able to reliably detect issue
- Improve code detecting warning

**Comment by mehul0810** [comment]
@DevinWalker I'm unable to reproduce this issue. Can you provide the steps for the reproduction of this issue?
