### ISSUE TITLE
After Give + addons update, custom form fields are misplaced.

### ISSUE THREAD

**Issue by Jany-M** [WordImpress/Give#1645]
We use custom functions/logics to show the custor form in each campaign.
After updating to latest Give + addons, some of the campaign options reset (eg. Guest Donation was set to Disabled).
Most importantly, after updating any campaign (even without changing any settings inside), the custom form fields now display in a different location (different hook??).
The campaigns that have not been updated/saved, after the upgrade, dont have this issue (yet).

This is how it used to look like (correct):

![correct](https://cloud.githubusercontent.com/assets/4365842/25585330/4126e0e2-2e9a-11e7-8511-bcc5edf60dfe.png)

This is how it looks now (wrong):

![wrong](https://cloud.githubusercontent.com/assets/4365842/25585341/4fa8683e-2e9a-11e7-9c4c-4a4a8ec66eb2.png)

Here is a pastebin with the custom functions we used, to achieve the correct single campagin layout https://pastebin.com/ffhuq9vY (line 94 onwards)

 **UPDATE** 

After replacing some old hooks there, and even after removing completely those functions, the issue is still there and still only happens when we update a campaign, hence I do believe the issue goes deeper than this, or the non-updated campaigns would have the same issue.

Why is the form not displaying correctly simply if we update a campaign?

**Comment by DevinWalker** [comment]
Hey @Jany-M it appears what you want to do is add fields to the "personal info" fieldset along with customizing with the three column donation selector. That's pretty neat. I checked out the pastebin you posted and couldn't see any of the custom fields your show in your screenshot. Are you sure that's all the code? If not, please provide the entire code so we can help out further.

Note, that this also appears to be not an issue with the plugin and this question likely should be posted rather to wordpress.org or via our priority support channel on givewp.com if you are a customer of ours.

**Comment by Jany-M** [comment]
The fields are set in the Field Manager, no need to add them through code, they're in the campaign metabox.

![fields](https://cloud.githubusercontent.com/assets/4365842/25600047/6069d0a8-2ee1-11e7-9b94-c547c18a05ff.png)

The issue isn't with the customization itself it appears, since even when I disable fully all those functions, the issue is still there, but ONLY with campaigns that I have updated since Give upgrade. 
All the campaigns that have not been updated yet, still look ok.
How do you explain that?

Error log shows no signs of Give issues, nor I see any notice when WP_DEBUG is on.

**Comment by DevinWalker** [comment]
@Jany-M there must be something going on there that we'd love to help uncover. Would you mind using our priority support channel and we'll dig into it further through that channel? Please reference this issue and we'll jump right in: https://givewp.com/support/

**Comment by Jany-M** [comment]
I did, please check ticket #7350

**Comment by DevinWalker** [comment]
Thanks @mathetos or @Benunc will be on it asap. If needed, I'll jump in too 😄

**Comment by mathetos** [comment]
@Jany-M I sent you revised code before 2pm Pacific today, please check that. The issue is that your `remove_action` was not working with a high enough priority.

**Comment by Jany-M** [comment]
It looks like the issue was that after the upgrade, the Form Field Manager had reset to display Above all fields.
It took us a while to notice (you dont expect an upgrade to reset settings), that's why if we updated a campaign it would mess it up.
I didn't need to replace our code with yours, everything is fine now (actually, replacing with your code makes it quite messy).

Thank you for looking into this, but I advise you make sure campaign settings dont get reset, in the next upgrades (2 things reset in all campaigns: Guest Donations and Form Fields display).
