### ISSUE TITLE
Shortcode Attributes

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#165]
We should add a couple basic attributes in the shortcode and shortcode builder. Like:

- [x] goals="true/false"
- [x] form-title="true/false"
- [x] form-content="true/false"

**Comment by DevinWalker** [comment]
Moving to 1.2 since we're going to be doing the goal shortcode there as well.

**Comment by mathetos** [comment]
Updated list of attributes here:

- [ ] show_goals="true/false"
- [ ] show_title="true/false"
- [ ] show_content="true/false"
- [ ] display_style="onpage/reveal/modal"

**Comment by DevinWalker** [comment]
Closing due to many PRs regarding this issue - somehow this issue wasn't closed in the merging of those PRs you see above.
