### ISSUE TITLE
Metabox Panel styling issue

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1662]
## Issue Overview

<img width="809" alt="screen shot 2017-05-05 at 4 06 40 pm" src="https://cloud.githubusercontent.com/assets/1784821/25742415/01a43896-31ad-11e7-97b1-2df00e2bc867.png">

**Comment by ravinderk** [comment]
@DevinWalker This is the minor conflict with give-receipt-attachments addon (by matt).

**Comment by mathetos** [comment]
Hey @ravinderk If I remember correctly, I added that custom CSS into my extension because of an existing CSS issue with the tabbed interface before it was officially launched. Thanks for addressing that, I'll resolve that in my Addon now too.
