### ISSUE TITLE
Donor Log link goes to All logs, not filtered view of log

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#167]
When clicking on "Donation Log" under the Donors name on the main Donors page, it should take you to a filtered list of the Logs of only that one user (per the url that it goes to), but it's not filtering. It shows the logs of all donors instead. 

![2015-07-13 12_13_22-donation reports give wordpress](https://cloud.githubusercontent.com/assets/930724/8658494/f7f32130-2958-11e5-8abe-9975b4cf8f96.png)

**Comment by DevinWalker** [comment]
Fixed as of 01338e3463bdd75895e76f35dbbfec0908c85f27
