### ISSUE TITLE
Make Custom amount Label Filterable

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1677]
## Issue Overview
When we give out this snippet, folks want to also be able to add html after the custom amount label.

https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/add-html-after-multilevel.php

The custom amount label is not filterable, so it doesn't work.

## Expected Behavior
Users should be able to use a similar snippet for modifying the Custom Amount Label.

## Current Behavior
It's not possible without [Jugaad](https://en.wikipedia.org/wiki/Jugaad) of our core plugin.

## Possible Solution
Make the label filterable here. https://github.com/WordImpress/Give/blob/master/includes/forms/template.php#L489

**Comment by ravinderk** [comment]
@Benunc I have to look into what developer what to achieve, but at first glance, it looks like custom design. Instead to filtering custom amount text, the developer can filter whole output with [`give_form_level_output`](https://github.com/WordImpress/Give/blob/master/includes/forms/template.php#L579)

**Comment by DevinWalker** [comment]
Yeah you can simply append html using the `give_form_level_output` filter. Something like:

```
function my_custom_post_level_content($output, $form_id){
$post_output = '<p>lalala</p>'
return $output . $post_output;
}

add_filter('give_form_level_output', 'my_custom_post_level_content', 10, 2);
```
