### ISSUE TITLE
Investigate possible bug with default terms and conditions

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1679]
## Issue Overview
I noticed when watching the WP Crafter overview he had his default form set to "Global Option" and wasn't able to complete his donation because it was prompting him to "Please enter valid terms and conditions in the plugin settings".

This shouldn't have happened because the default terms and conditions were set. I would like to investigate whether this is a bug with our user flow preventing easy and quick publishing of donation forms. 

Here's a link to the video playtime where he has the trouble: 

https://www.youtube.com/watch?v=4rug6q-67M0#t=27m31s

Note: I have not tested and reproduced this yet. That's step 1 to this issue.

## Expected Behavior
The admin is expected to be able to publish forms without having to set t&cs.

## Current Behavior
If as the video appears, you will have to set or disable the t&cs.

## Possible Solution
Set the default t&cs so the prompt doesn't happen and admins can more easily create donation forms.

## Steps to Reproduce (for bugs)
1. Install Give on a fresh install.
2. Create a donation form
3. Make a test donation

**Comment by mathetos** [comment]
I wasn't able to replicate that at all. @ravinderk I see a PR, you were able to replicate it?

**Comment by ravinderk** [comment]
@mathetos That was not really a bug. By default term and condition is disabled on a global level and it is set to global on per form basis which fine.

But according to the video, he saved term and conditions enabled on the global level with empty agree to terms label and agreement text which cause of issue on the frontend.
@mathetos  @DevinWalker asked me to set default content for both. In PR you will see lorem Ipsum text and @DevinWalker will update it.

**Comment by mathetos** [comment]
Ah, I missed the part where he saved empty Terms. Thanks for the clarification @ravinderk
