### ISSUE TITLE
Automatically close Forms that reach their Goal

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#168]
This is a feature request. See here:
https://wordpress.org/support/topic/dynamic-donation-field?replies=1#post-7174339

Could be added to the "Goals" conditional field section to close the form. Would probably want to add a WYSIWYG field to it as well that allows you to have a Success! message when the goal is reached and the form is closed.

**Comment by DevinWalker** [comment]
This would be pretty simple to achieve :+1:
