### ISSUE TITLE
Investigate issue with minimum donation amount conflicting with levels

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1680]
## Issue Overview
Reviewing the video from WP Crafter is appears he had an issue where he set a very large min. donation amount and was unable to give at a level lower than that minimum amount. This should not happen.

See: https://www.youtube.com/watch?v=4rug6q-67M0#t=31m20s

## Expected Behavior
If the admin sets a high custom donation amount and provides lower levels, the donor can still give at those lower levels.

## Current Behavior
The minimum custom amount should never affect the multilevel amounts. This means it should not validate against a multilevel amount, only the custom amount given.

## Possible Solution
Modify the validation to have exceptions for levels.

## Steps to Reproduce (for bugs)
1. Create a new multilevel donation form with a high custom amount
2. Create levels lower than that amount
3. Try to give at a lower level
4.

## Todos
- [x] Reproduce
- [x] Develop fix
- [x] Test
- [ ] Submit PR

**Comment by ravinderk** [comment]
@DevinWalker it is working fine for me

![aaffwxynfq](https://cloud.githubusercontent.com/assets/1784821/25992073/1cb7a52a-3723-11e7-93f1-09b93811ed96.gif)

@mathetos Can you review this?

**Comment by DevinWalker** [comment]
@ravinderk what is your minimum donation amount set to? Also, did you try and actually complete the donation?

**Comment by ravinderk** [comment]
@DevinWalker My minimum amount was `20` and I was able to donation with any level.
With custom amount i will able to donation only more than `20`

**Comment by DevinWalker** [comment]
@ravinderk I was just able to reproduce the issue.

**Form Setup:**
![2017-05-24_12-05-41](https://cloud.githubusercontent.com/assets/1571635/26421021/55e333c8-4079-11e7-817b-20678d352d97.png)

**Giving Process:**
![2017-05-24_12-06-23](https://cloud.githubusercontent.com/assets/1571635/26421054/7644f8d6-4079-11e7-998c-0701273cc717.gif)

Note how I have a level that's $5, which is below the custom amount setting of $10. The custom amount minimum should not have any affect on the levels.

**Comment by ravinderk** [comment]
@DevinWalker reopen this issue because @mehul0810 able to reproduce it again

**Comment by DevinWalker** [comment]
Thanks @ravinderk for fixing and @mehul0810 for catching that!
