### ISSUE TITLE
Trunk Folder in Give source code at WordPress Plugin Repository

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#1685]
## Issue Overview
While exploring the source code of Give. I have stumbled upon the trunk directory in Give plugin which is downloaded directly from WordPress.org plugin directory. Also, confirmed downloading the ZIP file on https://wordpress.org/plugins/give/

## Expected Behavior
There should not be a trunk directory in the source code having public access. 

## Current Behavior
Trunk directory present in the source code of Give plugin is having duplication of whole Give plugin. Hence, doubled the file size as well.

## Possible Solution
Simplifying the commit using WordPress SVN repository of Give plugin.

## Steps to Reproduce (for bugs)
1. Download ZIP from https://wordpress.org/plugins/give/
2. Extract Files or Open the Zip File
3. You will see the trunk directory there. 

For Reference: https://www.dropbox.com/s/24njfmllpxup3dn/Give_trunk_dir.png?dl=0

**Comment by DevinWalker** [comment]
Thanks @mehul0810 - @mathetos is going to take care of this right now.

**Comment by mathetos** [comment]
@mehul0810 This is done. Thanks for noticing that!
