### ISSUE TITLE
fix(admin-form): ensure form always publishes in usable state

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1688]
## Issue Overview
I think every form that publishes should be able to accept donations in one form or another. While I admit this scenario would be highly unlikely we should be able to do something to avoid it from happening.

## Current Behavior
If you set a form to "Set Donation", set the amount to `0` and set Custom Amount to "Disabled" then the form is useless. 

![image](https://cloud.githubusercontent.com/assets/930724/26070882/178d3f26-395b-11e7-8d0f-5be362142fca.png)

## Possible Solution
1. Add validation in the Form Edit screen to prevent saving the form if this combo is selected.
2. Prevent `0` from being inserted into the "Set Amount" field at all. Maybe on blur it reverts to `1.00` and 
a tooltip appears saying "Setting this to `0` effectively disables the form. Please select at least $1 or more for this option".

**Comment by ravinderk** [comment]
@mathetos I agree that overall admin/form settings do not javascript validation.
For example: In multi-level donation form we must have levels.

**Comment by raftaar1191** [comment]
This featured is getting break after the post is published without adding the amount

See the Video for more description of the issues that I am facing

Video Link: http://screencast-o-matic.com/watch/cbXj1m2XAT

**Comment by raftaar1191** [comment]
https://github.com/WordImpress/Give/issues/2425

**Comment by raftaar1191** [comment]
https://github.com/WordImpress/Give/issues/2454

**Comment by kevinwhoffman** [comment]
@raftaar1191 Please confirm if this issue is resolved. We should have the basic validation in place that Devin describes in https://github.com/WordImpress/Give/issues/2425#issuecomment-347689478.

> 1. If form is published as _Set Donation_ and _Set Donation_ is `0` then set to `1`.
> 2. If form is published as _Multi-level Donation_ and _all_ levels are `0` then set to `1`. 

Once confirmed, close this out.

**Comment by raftaar1191** [comment]
@kevinwhoffman @mathetos 

## Testing Summary
I have tested this issues with [**Give Core 2.0.7**](https://github.com/WordImpress/Give/tree/release/2.0.7)

- [ ] Tested by creating a new donation form where the **Donation Option** is set as **Multi-level Donation** 

- [ ] Tested by creating a new donation form where the **Donation Option** is set as **Set Donation** and **Custom Amount** option is **Disable** 

- [ ] Tested by entering the donation  amount value less than zero or equal to zero

Video Link: https://screencast-o-matic.com/watch/cFe26JD3aE

**Comment by DevinWalker** [comment]
Nice testing and video @raftaar1191
