### ISSUE TITLE
Feature Request: Reoccurring donations (subscriptions)

### ISSUE THREAD

**Issue by pryley** [WordImpress/Give#169]
For $62 you can purchase the Stripe or Braintree add-on, but without subscription functionality (?).

For $90 you can purchase Gravity forms and a Stripe add-on with subscription functionality and get it to look something like this: https://donate.samahope.org/checkout/donation?cid=16728

The only thing keeping me from using this plugin is lack of subscription functionality for reoccurring donations. Has this been discussed yet? Can it be added to either the roadmap or existing gateway extensions?

**Comment by DevinWalker** [comment]
Hey there - this has been discussed and is currently in development. Check out: https://givewp.com/coming-soon 

Also, Gravity Forms has a lot of good features indeed and we like it as well. Give is built specifically for accepting donations and offers a lot of other great features like reporting, goals, donor lists, and more.

Thanks for stopping by!
