### ISSUE TITLE
Compatibility with Yoast SEO when Form Single Views are disabled

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#1690]
## Issue Overview
When Form Single Views are disabled from Settings > Display Options > Post Types, then still we can see URLs of those form single views under XML Sitemap of Yoast SEO. Also, tried refreshing permalinks.

## Expected Behavior
If Form Single Views are disabled, then XML Sitemap of Yoast SEO should not show those pages.

## Current Behavior
If Form Single Views are disabled, then XML Sitemap of Yoast SEO is showing all the form single view URLs which is redirecting to homepage with a non-homepage URL. 

## Possible Solution
Removing those URLs from XML Sitemap or 301 redirection to homepage. We need to investigate the best way around.

## Steps to Reproduce (for bugs)
1. Install Yoast SEO plugin
2. Disable Form Single View under Settings > Display Options > Post Types
3. Make Sure you have Donation Forms created
4. Generate XML Sitemap and visit give_forms-sitemap.xml, you will see a list of URLs of the donation forms

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mathetos** [comment]
Good issue @mehul0810 Thanks!

**Comment by mehul0810** [comment]
@DevinWalker @mathetos I have investigated in detail for this issue and discussed the same with @ravinderk based on which I have found few ways with which we can resolve it. However, trying it with accessing the module which is generating the sitemap directly doesn't worked.

**Here are the few ways worked:**
1. Converting `give_forms` CPT to private using `public:false` when Form Single Views are disabled, then sitemap for `give_forms` won't get generated.
2. Using a filter `wpseo_sitemap_exclude_post_type`, to skip `give_forms` CPT to while generating a sitemap.

Also, I have made sure that [give_forms] shortcake is working when `public` is set to `false` and it is perfectly working including complete donation process.

**Some References:**
https://wordpress.org/support/topic/automatically-remove-private-pages-from-xml-sitemaps/
https://kb.yoast.com/kb/sitemap-does-not-update/

Looking for you views and suggestions as well.

**Comment by mathetos** [comment]
Personally I'd prefer option (1) since it's the WP core way to resolve that and there may be other plugins that this issue may effect and the (2) option wouldn't resolve it for those plugins, only Yoast.

**Comment by DevinWalker** [comment]
@mehul0810 options #1 sounds good but as long as it doesn't change the visibility of the post items within wp-admin. I don't believe it will, but ensure you double-check.

**Comment by mehul0810** [comment]
@DevinWalker Sure. I'll do a complete testing after making the change so that none of the existing functionality will get affected.
