### ISSUE TITLE
Prioritze Donation Form Options metabox while using Yoast SEO plugin

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#1698]
## Issue Overview
When using Yoast SEO plugin, Yoast SEO metabox pushes down Donation Form Options metabox which contains core functionality of `give_forms` CPT.
 
## Expected Behavior
Donation Form Options metabox should have high priority so that other plugin can't affect core functionality of `give_forms`.

## Current Behavior
Yoast SEO metabox takes over the whole viewport of the browser screen so that user have to scroll down to configure donation form, which lead to bad User Experience.

## Possible Solution
Giving high priority to Donation Form Options metabox at https://github.com/WordImpress/Give/blob/master/includes/admin/forms/class-metabox-form-data.php#L55

## Steps to Reproduce (for bugs)
1. Create a new WordPress instance with Give plugin installed
2. Install Yoast SEO plugin
3. Go to Donations > Add Form

**Comment by DevinWalker** [comment]
Good catch
