### ISSUE TITLE
Frontend List of Donors with Gravatars & Opt-in/out

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#17]
Currently all Gravatar settings are global via the Settings panel. They should instead be available in each form for specificity.

**Comment by DevinWalker** [comment]
I've disabled the Gravatar functionality until this can be hashed out a bit more. I agree it should be form specific.

**Comment by DevinWalker** [comment]
Items needed for this:

- [ ] Donor opt-in/out of public display
- [ ] Columns attribute to display donors in 2/3/4/6 columns
- [ ] Form ID filter; if none specify pull globally

More consideration: Sidebar widget

**Comment by DevinWalker** [comment]
Related to #83

**Comment by Benunc** [comment]
Still regularly getting this request from users. is it still on track for this release?

**Comment by DevinWalker** [comment]
We're creating a free Add-on for this

**Comment by DevinWalker** [comment]
Follow along on the repo for this here: https://github.com/WordImpress/Give-Per-Form-Confirmation-Messages 

This will be a free plugin when released.

**Comment by mathetos** [comment]
@DevinWalker I think you linked to the wrong Repo for this issue. Isn't this one going to be called "Display Donors"? Or something to that effect?

**Comment by DevinWalker** [comment]
Yup, I fixed the link above.

**Comment by DevinWalker** [comment]
Reopening this as I'd really like to see a "Donor Wall" in core.

**Comment by Benunc** [comment]
Another request for this today. all requests will be tagged "anonymous donation" in help scout.
