### ISSUE TITLE
New data tool to delete all donors and their payments, keep the donation forms

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1700]
## Issue Overview
Currently, we can delete test transactions but the donor used to create that test transaction remains. We should provide admins the ability to bulk delete donors. We'll definitely have a prompt warning them of the implications. I'm creating a tool for this mainly out of a personal need on the GiveWP website.

**Comment by mathetos** [comment]
Would also be great to help our users delete SPAM donors, which we still don't know exactly HOW that is happening, but it is.
