### ISSUE TITLE
Modal close button gets hidden with some themes

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1709]
## Issue Overview
Some themes come with magnific pre-installed and they do all kinds of crazy things with it. Generally, Give handles that fine, with the exception of the CLOSE button. We need to tighen up the styles on it to prevent it from getting lost.

## Expected Behavior
The close button should always be visible in the top-right of the Give modal window.

## Current Behavior
Sometimes it gets bumped off the screen and is invisible which makes it virtually impossible for common users/donors to close it if they want.

## Possible Solution
Since our button is physically inside our Give form, we can target it very specifically:

We currently have some custom Give styles for the close button, but I don't think they have enough specificity:

`.give-modal .mfp-close, .give-modal .mfp-arrow, .give-modal .mfp-preloader, .give-modal .mfp-counter`

Updating those as follows should resolve it.

```
form.give-form button.mfp-close {
    position: absolute;
    display: block !important;
}
```

That means updating the wrapper element [here](https://github.com/WordImpress/Give/blob/master/assets/scss/frontend/modal.scss#L11) and the classes [here](https://github.com/WordImpress/Give/blob/master/assets/scss/frontend/modal.scss#L121-L128)

## Steps to Reproduce (for bugs)
I have a theme called "Impreza" which displays this behavior, and the above styles resolved it. And here's a customer which had the same issue with a different theme:
https://secure.helpscout.net/conversation/367248879/7722/

**Comment by mehul0810** [comment]
@mathetos I will require "Impreza" WordPress Theme to try and reproduce the issue to fix. Also, let me know which other WordPress themes are having issue. Please do the needful.

**Comment by mathetos** [comment]
@mehul0810 I pinged you in Slack. Thanks!

**Comment by marutim** [comment]
We received another ticket with this issue here: https://secure.helpscout.net/conversation/457276120/11260?folderId=1457790
