### ISSUE TITLE
Showing Labels for Form Featured Image dropdown

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#1713]
## Issue Overview
The dropdown of Form Featured Image under Settings > Display Options > Post Types is confusing to end user in case of `medium_large` which is showing a resolution of 768x0. Also, noticed that post-thumbnail is showing 1200x9999 where 9999 doesn't make sense.

## Expected Behavior
![featured image size](https://cloud.githubusercontent.com/assets/1852711/26233225/7df30914-3c79-11e7-86f8-6faf35640acf.png)

## Current Behavior
![featured image size - current](https://cloud.githubusercontent.com/assets/1852711/26233249/a3d22e26-3c79-11e7-826f-d70788a93698.png)

## Possible Solution
Need to implement required changes somewhere https://github.com/WordImpress/Give/blob/master/includes/admin/class-give-settings.php#L1121

## Todos
- [x] Tests

**Comment by mathetos** [comment]
I'm not sure I agree with this change. There are MANY image sizes that will show up in the dropdown and they will have very different sizes. The Give featured image is typically a specific size in pixels and the user is not going to know which image "name" works best with the Give sidebar width.

Personally, the best of both worlds would be for them to be formatted like this:

* Thumbnail (150x150)
* Medium (300x300)
* Medium Large (768x0 - responsive)
* Large (1024x1024)
* Post Thumbnail (1200x9999 - responsive)

**Comment by ravinderk** [comment]
`responsive` tag is not added correctly to image size. Twenty Seventeen themes register two new images sizes which set to crop (`true`), so `responsive` tag should not be added to them.


![screen shot 2017-05-25 at 6 04 07 pm](https://cloud.githubusercontent.com/assets/1784821/26450338/94f4b0a4-4174-11e7-868e-c29f86d1b415.png)

<img width="612" alt="screen shot 2017-05-25 at 5 59 40 pm" src="https://cloud.githubusercontent.com/assets/1784821/26450310/74635c64-4174-11e7-8da4-47c91a5263f3.png">
