### ISSUE TITLE
If user is disconnected from associated donor, an error should show when user tries to login

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#1721]
## Issue Overview
As discussed with @ravinderk today, we should restrict user to login with meaningful error message, if that user is disconnected with associated donor profile. Even, we can send an email to admin that user is trying to login which is disconnected from donor. Do you want to reconnect user again to donor? or need to create new donor profile for the user?

Related to #1720 

## Expected Behavior
User should not be able to access features of Give plugin when user is disconnected from donor as donor is the main entity representing donations for Give plugin.

## Current Behavior
User can login to his account even if user is disconnected from the donor profile.

## Possible Solutions
Need to investigate the issue in more detail and based on which we can come up with best possible solution. I think restricting user with after login action should work.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mehul0810** [comment]
@DevinWalker Today, I had a discussion with @ravinderk regarding this issue and had few questions related to this issue.

### Scenario
This issue will affect those users who are donors but user and donor are disconnected by admin from donor detail page.

![image](https://user-images.githubusercontent.com/1852711/30537553-b9a6d148-9c87-11e7-90fc-ebbf8b60a0d0.png)

### Questions
1. Do we need to restrict user with WP Admin Login as well as Donation Form Login ?
2. We will be sending an email to admin, if user will try to login and restricted to login due to this reason - We have discussed to have hardcoded email right now and later on in `release 2.0/2.1` we will provide flexibility to modify emails. Let me know your thoughts.
3. What should be the functionality of the `Reconnect User` button in the email and what page should open on clicking it?
4. Secondary CTA in the email will be `Create New Donor` and on clicking to it will redirect to `Create Donor` page so that admin can link the user to the newly created donor. Also, we don't have a separate page for creating new donor in admin. So, how do we think to manage this? Let me know your thoughts.

**My thought on point (3):** We can open the donor detail page when admin clicks the `Reconnect User` button and will be connecting the respective donor which was disconnected earlier and an admin notice will be displayed `We have successfully connected the user <email> to its respective donor.

**Comment by DevinWalker** [comment]
## Responses
1. No don't restrict the user from WP admin login
2. Hard coded is fine. I doubt people will want to edit it as it will be seldom sent.
3. It should go to the donor's profile page in wp-admin like you said - that sounds good.
4. Don't worry about creating a new donor for now.
