### ISSUE TITLE
Email Subject not changing

### ISSUE THREAD

**Issue by advancedwp** [WordImpress/Give#173]
See details here: https://wordpress.org/support/topic/how-to-customize-the-email-template?replies=9#post-7185107
Verified locally that the Email Subject does not change in the email preview. Haven't confirmed with the ACTUAL email yet.

**Comment by DevinWalker** [comment]
@advancedwp @mathetos can you confirm it doesn't change email? I'd be surprised if it didn't update properly.

**Comment by advancedwp** [comment]
It changes the subject line of the actual email correctly, but that is not reflected in the Title of the email at all. See here:

### Email Subject changed in Settings
![email-donation-subject-field](https://cloud.githubusercontent.com/assets/12474956/8711580/1e2cfbe0-2b08-11e5-963c-cdd7fea77f12.jpg)

### Email subject not reflected in title of the email
![email-subject-not-changed](https://cloud.githubusercontent.com/assets/12474956/8711611/5482401a-2b08-11e5-9e63-126da7cfe2a1.jpg)

**Comment by DevinWalker** [comment]
It's not really a bug because the email subject and title are not one in the same.

**Comment by DevinWalker** [comment]
I'm not convinced this is an actual problem just yet, need to discuss more

**Comment by mathetos** [comment]
Hmmm... I see what you're saying. This would be an improvement request. Might need an additional field to customize that separately from the subject line. Got it.

Since that title is so pronounced, and so central I think giving an easy way to customize it would be beneficial.

**Comment by DevinWalker** [comment]
I can't find a reason to allow the user to customize the test email subject. Seems more confusing than helpful.
