### ISSUE TITLE
Show Multi-level labels on confirmation page and reports

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#175]
Some users want to know which "level" a donor donated at, not just simply the amount. If we could add the labels to both the confirmation page/email and in the reports themselves that would be useful. 

I also don't think this needs to be a setting. We can add this safely without adding another "decision" to our users. Those who don't care whether it's there or not won't mind that it's there. Those who DO want it, will be happy they didn't have to configure anything to get it.

**Comment by DevinWalker** [comment]
Agreed

**Comment by DevinWalker** [comment]
@mathetos can you explain a bit more about this in more specific terms at the objective here? It's been awhile since July so maybe we should circle back around on this one and determine how to resolve the issue. For now, I'm going to bump this off the 1.3.2 milestone.

**Comment by mathetos** [comment]
When a form uses multi-level they always have labels. Sometimes users use the labels to describe a specific Fund, so they want a more "at-a-glance" way to see what transactions are designated to that fund. Here's screenshots:

When selecting "Mid-Level":
![choosing-level-on-form](https://cloud.githubusercontent.com/assets/930724/10889018/3acbcffa-8144-11e5-91b7-2b824a16594a.jpg)


They want that reflected in potentially two places

### Donation Receipt:
![add-level-to-donation-receipt](https://cloud.githubusercontent.com/assets/930724/10888987/fcfe8e56-8143-11e5-95ee-d148a8b6d3fb.png)

### Transactions Screen:
![add-levels-to-transactions-admin](https://cloud.githubusercontent.com/assets/930724/10888998/0cd2b140-8144-11e5-96ba-f6a598bc0b95.png)

**Comment by mathetos** [comment]
I added this to Milestone 1.4 since we're getting regular requests for it.

**Comment by mathetos** [comment]
This is a related request, but wanting the same feature extended to the donation email receipt:
https://wordpress.org/support/topic/reciept-in-email-with-multi-level-donation-content?replies=2#post-8108365
