### ISSUE TITLE
Notice: Undefined index in /wp-content/plugins/give/templates/shortcode-receipt.php on line 38

### ISSUE THREAD

**Issue by dixitadusara** [WordImpress/Give#1763]
## Issue Overview

Got error on donation confirmation page when donation deletes from admin side.

 Notice: Undefined index: first_name in wp-content\plugins\give\templates\shortcode-receipt.php on line 38

 Notice: Undefined index: last_name in \wp-content\plugins\give\templates\shortcode-receipt.php on line 38

![error](https://user-images.githubusercontent.com/24749815/26931824-5ddeab54-4c7f-11e7-809a-b985320f2f3c.png)

## Steps to Reproduce (for bugs)

1. Complete donation 
2. Now go to admin side and delete that donation
3. Refresh donation confirmation page

## Todos
- [ ] Tests

**Comment by DevinWalker** [comment]
Thanks for catching this bug @dixitadusara
