### ISSUE TITLE
Include "Donation Forms" within WP-admin Menus by Default On Install 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1765]
## Issue Overview
When you first install Give and go to add a donation form to your WP-Admin > Menus you don't see them by default. You have to click on "Screen Options" then select it, which is difficult for new users to understand.  

![2017-06-09_13-07-27](https://user-images.githubusercontent.com/1571635/26992808-2b5936ea-4d15-11e7-8b3d-870e6d35e9c9.gif)

## Expected Behavior
Donation forms pages can be added easily after install.

## Current Behavior
You have to first enable it as an option.

## Possible Solution
Add the option on install to the db that it's enabled.

## Steps to Reproduce (for bugs)
1. Install Give on a fresh WP install
2. Create a donation form
3. Go to add it to your menus using wp-admin

**Comment by ravinderk** [comment]
@DevinWalker Good catch

**Comment by DevinWalker** [comment]
Thanks @emgk
