### ISSUE TITLE
Add confirmation alert when deleting donations with hover link

### ISSUE THREAD

**Issue by amjad** [WordImpress/Give#1773]
Don’t want to be accidentally deleting a donation without confirming.

**Comment by DevinWalker** [comment]
There already is one... did you check it? 

![2017-06-12_11-21-25](https://user-images.githubusercontent.com/1571635/27048593-512df8a8-4f61-11e7-84dc-7900adec157a.png)

**Comment by amjad** [comment]
Perhaps it could be a browser specific issue? I do not see this in Safari on my Mac.

**Comment by amjad** [comment]
I was referring to the Delete button on hover. Not the dropdown.

![screen shot 2017-06-13 at 6 37 43 pm](https://user-images.githubusercontent.com/1428634/27115789-a323ba3a-5092-11e7-8900-51a14ea345e0.png)

**Comment by DevinWalker** [comment]
Ohhh, good catch then! Reopening.

**Comment by DevinWalker** [comment]
@mehul0810 can you add the alert trigger to the delete link @amjad mentioned as well?

**Comment by mehul0810** [comment]
Sure @DevinWalker
