### ISSUE TITLE
[Request] Filter by Payment Type

### ISSUE THREAD

**Issue by amjad** [WordImpress/Give#1783]
On the donations page, it would be nice to have a filter dropdown allowing to quickly find transactions grouped by payment types. 

What do you guys think?

**Comment by ravinderk** [comment]
@amjad I am closing this issue in favor of #621.
We will create a search API which you can integrate if you want to add any custom search otherwise after resolving #621 you will able to search payment with various type of filters (payment meta also).

**Comment by amjad** [comment]
makes sense. 👍🏻
