### ISSUE TITLE
Invalid text-domain "easy-digital-downloads"

### ISSUE THREAD

**Issue by jaydeeprami** [WordImpress/Give#1784]
## Issue Overview
There is a invalid text-domain used Give. To improve localization, we must have to remove it and replace with "give" text-domain.

## Expected Behavior
We must have to replace "easy-digital-downloads" with "give" text-domain for localization.

## Current Behavior
Few of the strings will not translate if we have  "easy-digital-downloads" text-domain.

## Possible Solution
Replace "easy-digital-downloads" with "give" text-domain for localization.

## Steps to Reproduce (for bugs)
Find "easy-digital-downloads" in Give plugin.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jaydeeprami** [comment]
@ravinderk , I am working on it and send PR.

**Comment by DevinWalker** [comment]
Thanks @jaydeeprami
