### ISSUE TITLE
Broken link to documentation within readme.txt

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1791]
## Issue Overview
![2017-06-25_10-54-35](https://user-images.githubusercontent.com/1571635/27514782-bc70ac72-5994-11e7-94e4-2f0abaf9efee.png)

This link is going to a bitly 404 page. Please check other links for 404s too. 

## Expected Behavior
The link works as expected. 

## Current Behavior
404 error

**Comment by mathetos** [comment]
Pushed fix to master and updated on wp.org as well. Thanks!
