### ISSUE TITLE
Email tag in emails are not converting.

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#1793]
## Issue Overview
All the email tags such as `{name}` , `{receipt_id}` are not getting converted into its respective value and this issue originated from `release 1.8.9`. Need to check with all the emails. I've checked it with `New Donation` email for admin and `Donation Receipt` email for user.

## Expected Behavior
All the email tags should get converted to its respective value

## Current Behavior
All the email tags are not getting converted to its respective value.

## Possible Solution
Not Sure, but it might be an issue with the new plugin load process.

## Steps to Reproduce (for bugs)
1. Create a fresh WP install
2. Install Give - release 1.8.9
3. Create a donation form
4. Submit the donation
5. Now, check the emails received

## Todos
- [ ] Investigate
- [ ] Fix
- [ ] Tests

**Comment by ravinderk** [comment]
I am opening this issue for https://github.com/WordImpress/Give/issues/1839
