### ISSUE TITLE
Add Setting to disable single posts

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#18]
If a user plans to only use Give with the shortcode, then they don't want the "donations" url showing up in their sitemap, so make a setting to disable the single post type.

**Comment by stegosource** [comment]
Is there a reason to offer donations as a CPT? I think leaving it a JUST a shortcode solve a lot of issues and streamlines the process a bit. A lot like how Gavity Forms works. What is the justification for the single post mode?

**Comment by DevinWalker** [comment]
@stegosource see my response over at #54
