### ISSUE TITLE
Fully test multisite compatibility and network settings

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#180]
We need to test on a multisite network as much as possible. Specifically:
- [ ] That Give Free works out of the box on multisite and can be globally activated properly
- [ ] That Add-ons can be globally activated properly
- [ ]  Potentially add actions/filters to disable license management at the child-site level so all management of licenses is handled at the Super Admin level only.

**Comment by BurlesonBrad** [comment]
Ok.I'm in.

**Comment by DevinWalker** [comment]
@BurlesonBrad any testing feedback you can tackle here would be much appreciated :)

**Comment by BurlesonBrad** [comment]
https://givewp.networksharedmedia.com/hey-look-a-post/
Ok, lemme get some more coffee, get some other things knocked out for the day, and I'll see where everyone's at.  It'll either be a few minutes before church or late this evening.

**Comment by BurlesonBrad** [comment]
http://wooimages.com/donations/f1-multi-level-buttons-custom-amount-above/
Warning: number_format() expects parameter 1 to be double, string given in /home/networks/public_html/wp-content/plugins/give/includes/formatting.php on line 98
**notice went away w/ a simple resave of the post**

https://givewp.networksharedmedia.com/donations/f1/
**no issues seen**

**Comment by DevinWalker** [comment]
:+1:

**Comment by MichaMcLain** [comment]
Hey guys. I'm the one that asked Matt about this functionality in your plugin. Has there been any progress in this yet? I'm hoping to have this feature available soon as I'll be launching this network very soon. 

Thanks,
Micha

**Comment by BurlesonBrad** [comment]
Micha, I'll not only tell 'ya it works in multisite, but I'll let you log in and see if you can _not_ make it work in multisite ;-) 
I'm even running nightly bleeds of WordPress on this particular multisite!! ...and Give still seems to be churning away just fine.
Shoot me an email to howdy@bradgriffin.me and I'll make 'ya a super admin to the network and you can mess with it all 'ya want.

**Comment by DevinWalker** [comment]
@mathetos what's the status on this issue? Have you tested and verified your items 1-3? I really don't want to bump this one to 1.4 and it seems nearly tested.

**Comment by mathetos** [comment]
I'll test more fully soon.

**Comment by BurlesonBrad** [comment]
@DevinWalker @mathetos Did I not send y'all the login?
Seriously, y'all shouldn't have to spend a ton of time setting up the environment just to test it! 
DRY!  ~or~ You can't replace time!
(either way, go spend time being awesome, b/c everything you need is already set up and waiting) :+1: 

Multisite | WildCard SSL | Run betas if needed | Run extensions through it | Test, Tweak, Twerk

I'll send the login's again

**Comment by mathetos** [comment]
Yep, we're all set actually. Keep us posted if that environment is no longer available. Thanks!

**Comment by BurlesonBrad** [comment]
Hosting, WildCard, EDD Licenses, .............yadda yadda ....all paid up for a year.
I don't really even want the headache of either the site nor the plugin anymore so....
![havefunstorminthecastle](https://cloud.githubusercontent.com/assets/6208757/9963402/b25538bc-5df0-11e5-971e-d1944294d173.gif)

**Comment by DevinWalker** [comment]
lol @BurlesonBrad :+1: love that movie

**Comment by DevinWalker** [comment]
@mathetos is this ready to be closed?

**Comment by mathetos** [comment]
Yep. Good to go for now.
