### ISSUE TITLE
Invalid entry created on bulk action under Donations

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#1801]
## Issue Overview
This issue generated for Donations when using bulk actions on it.

![invalid_donation_entry_on_bulk_action](https://user-images.githubusercontent.com/1852711/27672098-2d650382-5cb6-11e7-9b91-e03cb49913fa.png)

## Expected Behavior
Bulk actions should only apply if there is any checkbox from the list is selected.

## Current Behavior
Creates a invalid donor missing entry when bulk action "Set to {any status}" is applied and no checkbox is selected

## Possible Solution
Need to check what happens when a bulk action is triggered and no checkbox selected.

## Steps to Reproduce (for bugs)
1. Go to `Donations > Donations`
2. Make sure there is no checkbox ticked.
3. Change bulk action to "Set to completed"
4. Click `Apply`
5. Now, you will see a new entry with donor missing

## Todos
- [x] Fix
- [x] Tests

**Comment by mehul0810** [comment]
**For Reproduction of issue:**

![Invalid_donor_entry](http://g.recordit.co/6c2J3bsJwT.gif)

**Comment by jaydeeprami** [comment]
@ravinderk , I have fixed it.

**Comment by ravinderk** [comment]
@mehul0810 I think because of this issue fix, I am unable to search anything on payment listing page.
![gtdwtcmd47](https://user-images.githubusercontent.com/1784821/27854398-4bf9fabe-6184-11e7-8326-ec32cbeebb6f.gif)
