### ISSUE TITLE
Update message showing incorrectly on fresh WP + Give install

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1810]
## Issue Overview
I just installed WordPress and activated Give in a new environment and I see:

![2017-07-03_16-28-11](https://user-images.githubusercontent.com/1571635/27810232-b6cef318-600c-11e7-97d4-d65c139ca353.png)

Plus, there is a typo in the update text. It should read: 

> Give 1.8.9 needs to update the donation form's meta fields within the database, click here to start the upgrade.

## Expected Behavior
No upgrade is needed because I just installed the plugin and haven't created any meta-fields.

## Steps to Reproduce (for bugs)

1. Fresh WP Install
2. Install Give
3. Activate Give

## Todos
- [ ] Fix upgrade prompt displaying incorrectly for fresh installs
- [ ] Fix typo
- [ ] Test and confirm working as properly

**Comment by ravinderk** [comment]
@DevinWalker  Fixed.

For ref: https://github.com/WordImpress/Give/commit/bfd504b7e4e1eacfd2833cb463fcf0021a0cc58e

@mehul0810 Please add an upgrade to install.php by default
For reF: https://github.com/WordImpress/Give/blob/master/includes/admin/upgrades/upgrade-functions.php#L88
