### ISSUE TITLE
give_count_payments is not working when pass #{payment_id}

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1817]
## Issue Overview

When we search #{payment_id} or as pass argument to `give_count_payments()`, then we will not get desired result.
We also have a typo in the query. The query has `}` which is extra.
for reference: https://github.com/WordImpress/Give/blob/master/includes/payments/functions.php#L475
Check EDD issue also: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5857

## Expected Behavior

I expect correct payment count by status

## Current Behavior

Not getting the desired result.

## Possible Solution

Remove `give_log` dependency and improve query.

**Current query**
```
SELECT p2.post_status,count( * ) AS num_posts
		FROM wp_posts p
		LEFT JOIN wp_postmeta m ON m.meta_key = '_give_log_payment_id' AND m.post_id = p.ID INNER JOIN wp_posts p2 ON m.meta_value = p2.ID
		WHERE p.post_type = 'give_log' AND p.post_parent = 940
		GROUP BY p.post_status
```

**Improved query**
```
SELECT p.post_status,count( * ) AS num_posts 
		FROM wp_posts p
		
		WHERE p.post_type='give_payment'  AND p.ID = {payment_id} 
		GROUP BY p.post_status
```
## Steps to Reproduce (for bugs)

1. search by #{payment_id}
2. or check function with `give_count_payments( array( 's' => '#{payment_id}' ) )`

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Ravinder I'm seeing issue on this one. For instance, go check out a specific form's report and you'll see incorrect counts:

![2017-07-05_16-01-52](https://user-images.githubusercontent.com/1571635/27888534-5715814a-619b-11e7-8a7c-d13f98e3c529.png)

**Comment by ravinderk** [comment]
@DevinWalker I check it

**Comment by DevinWalker** [comment]
I'm still seeing issues after mergining
