### ISSUE TITLE
Font icons are block with SSL and ugly permalinks

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#182]
If the site does not use pretty permalinks and instead uses the default permalink style (resulting in a slug like `?page_id=992` AND the site is using SSL, the font icons receive a 403 (Forbidden) error.

Perhaps the SSL aspect is inconsequential. Here's an example:

https://haitiproject.org/?page_id=992

**Comment by BurlesonBrad** [comment]
Ok, I've been staring at this for about an hour now hoping that I could contribute on the 'code' side of things.... (screw it: lemme just stick with what I know)

Those tooltip things were making errors with Gliebe's themes as well, right? Plus...couldn't the whole *font icon* thing be seen as "one more aspect" for y'all to have to worry about?  And, when we look at what it's doing, we can see that it might be a bit pointlessly redundant. Lemme show 'ya:

http://screencast-o-matic.com/watch/coirDQfu9k

**Comment by BurlesonBrad** [comment]
I DID IT! 

http://screencast-o-matic.com/watch/coirDAfuRn

**Comment by DevinWalker** [comment]
Thanks for the screencasts @BurlesonBrad - I'm glad to see you contributing! 

About this issue... I'm trying to reproduce it on another site: https://beta.wordimpress.com/?page_id=421

![7-21-2015 11-47-44 am](https://cloud.githubusercontent.com/assets/1571635/8809590/7e7a3f72-2f9e-11e5-97c2-1105e09f3ebd.jpg)

They are showing up just fine. I think there's something up with the theme in use or the underlying hosting platform, which appears to be acting up in other places.
