### ISSUE TITLE
Don't display donation payment status if no payments are within that status

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1823]
## Issue Overview

@mehul0810 caught a good issue while testing `1.8.9` that we are displaying a list of statuses within the donation payment list screen even if there are no payments within that status:

![2017-07-05_14-17-51](https://user-images.githubusercontent.com/1571635/27885396-c16fa61a-618c-11e7-9059-46c0c12c9246.png)

## Expected Behavior

See how WP Core and WooCommerce do it handle bulk status updates:

**WooCommerce**

![2017-07-05_14-15-26](https://user-images.githubusercontent.com/1571635/27885342-8890db5c-618c-11e7-8e23-0a1885118aa4.gif)

**WP Core**

![2017-07-05_14-20-15](https://user-images.githubusercontent.com/1571635/27885504-1cde4cc2-618d-11e7-9a5c-5831a9e5e4f8.gif)

## Current Behavior
1. A long list of empty status appear. 
2. After updating a status, the number of payments containing the new status doesn't appear until refreshing the screen.

## Todos
- [ ] Refactor status filter list to be like WP core and Woo
- [ ] Test to ensure updating doesn't require refreshing to see update number

**Comment by raftaar1191** [comment]
Please used the below filter to show all the status bar inside the donation sub menu.
https://gist.github.com/raftaar1191/b8eb98aebe6edd43c675fc77f3f076cb

**Comment by DevinWalker** [comment]
@raftaar1191 can you PR that gist to our snippet library?

**Comment by raftaar1191** [comment]
@DevinWalker 
Here is the PR: https://github.com/WordImpress/Give-Snippet-Library/pull/36 for the above filter that is being added in the Give-Snippet-Library
