### ISSUE TITLE
Logged-out donations result in white screen in Divi 3.0.53

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#1834]
## Issue Overview

A recent Divi update appears to be causing a white screen for logged-out donations. Two Divi versions were tested under the same conditions:

- Divi 3.0.53 - white screen
- Divi 3.0.27 - successful donation

## Expected Behavior

User clicks "Donate Now" and ends up on Donation Confirmation page.

## Current Behavior

User clicks "Donate Now" and gets white screen. Even with debugging enabled, no errors are displayed.

## Steps to Reproduce (for bugs)

1. Install WordPress 4.8
2. Install Give 1.8.9 with no add-ons.
3. Install Divi 3.0.53.
4. Attempt a logged-out test donation and confirm white screen.

## Related Issues and/or PRs

https://secure.helpscout.net/conversation/389916588/8648/?folderId=672197

**Comment by DevinWalker** [comment]
Just confirmed. So strange.

**Comment by kevinwhoffman** [comment]
One thing I noticed is that even when the white screen occurs, the Donor is being stored in the database along with a partial donation. Below is an example of the full payment meta that should be saved compared to the partial payment meta that results from the white screen. This might help you track down where exactly the error is occurring.

## Logged-In Successful Donation
```php
array(
  'key' => 'ad1faf6019d7b7049db0a7cd8b5c1d84',
  'form_title' => 'General Giving Test',
  'email' => 'admin@local.dev',
  'date' => '2017-07-08 00:58:38',
  'user_info' => array(
    'first_name' => 'Kevin',
    'last_name' => 'Hoffman',
    'id' => 1,
    'email' => 'admin@local.dev',
    'address' => false,
  ),
  'form_id' => '44',
  'price_id' => '',
  'currency' => 'USD',
)
```

## Logged-Out Partial Donation (interrupted by white screen)
```php
array(
  'key' => '',
  'form_title' => 'General Giving Test',
  'email' => 'admin@local.dev',
  'date' => '2017-07-08 00:47:23',
  'user_info' => array(
    'email' => 'admin@local.dev',
  ),
)
```

**Comment by DevinWalker** [comment]
I just tested with Divi `Version: 3.0.62` and it worked fine. My suggestion would for uses to _update_ to the latest version.
