### ISSUE TITLE
Non-core email tags not working in Give 1.8.9

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1839]
## Issue Overview
Non-core email tags not working in Give 1.8.9

## Expected Behavior
All email tags should work correctly.

## Current Behavior
Currently, non-Core email tags are rendering naked in emails

## Steps to Reproduce (for bugs)
1. Install Give 1.8.8, confirm that `{all_custom_fields}` and `{pdf_receipt}` email tags render correctly in notification emails
2. Upgrade to Give 1.8.9
3. Confirm that both `{all_custom_fields}` and `{pdf_receipt}` are not rendering in the email and outputting naked instead, like so:

![image](https://user-images.githubusercontent.com/930724/28043036-df01872e-6584-11e7-8902-686b1a87602d.png)

**Comment by DevinWalker** [comment]
@mehul0810 @ravinderk I thought we tested for this? Please review and report on how we missed this.

**Comment by ravinderk** [comment]
@devinwalker, when Jaydeep came up email tag issue in fee recovery,  I told @mehul0810  to test related issue with the addon.


https://github.com/WordImpress/Give/issues/1793
You can clearly see that I added unit test related tag to it, but we never added test and close it.I was silent on this and busy with another task, it was my mistake and I will take care of that next time. But surely, we should not merge anything till it is not completed.

<img width="1078" alt="screen shot 2017-07-11 at 7 47 32 am" src="https://user-images.githubusercontent.com/1784821/28048238-3a084198-660d-11e7-9401-b4e8a023d6b0.png">

**Comment by mehul0810** [comment]
@DevinWalker I've tested this with Give Recurring, Give Per Form and Give Fee Recovery addon. I think few other addons are also having email tags due to which the email tags are not converted. Let me check and find out whether a Core update or individual update will work for this urgent issue.
