### ISSUE TITLE
Create Shortcode for Goals

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#184]
I'd suggest a few things. It could be simple like this:
[give-goal id="546"]

But a few attributes might be nice as well:
[give-goal id="546" show_text="false" show_bar="true"]

If we wanted to get really fancy we could add a "color" attribute, but users would have to know HEX for that.

**Comment by ibndawood** [comment]
I'd like to contribute to this.

**Comment by DevinWalker** [comment]
@ibndawood first priority is Form Field Manager BUT if you want to tackle this if you have time then no problem :+1:

**Comment by DevinWalker** [comment]
@ibndawood any word on this?

**Comment by DevinWalker** [comment]
Ok I've added this... 

@mathetos please test https://github.com/WordImpress/Give/tree/issue/184 when you can to verify it's ready to merge.

**Comment by mathetos** [comment]
Works as advertised. Looks really great, will be a very welcome addition.

I think adding one attribute (perhaps in a future version) would be helpful:

[give_goals markup="full/minimal/none"]

* full = exactly the output it has now. All spans and class names with styles applied
* minimal = All spans with alternate class names so NO styles are applied
* none = just the plain text with no markup is output

There are use cases for each of those.

**Comment by DevinWalker** [comment]
I'd rather provide options for styles like the color of the bar, etc. 

`[give_goal id="12" progress_color="#334219"]`

**Comment by mathetos** [comment]
Yep, that would be a good one too, just requires the user to know HEX colors. But, these aren't mutually exclusive ideas.

My suggestion is for users who want to display their goals throughout their site. I'm thinking more about the text spans since they are currently styled in a very unique way. If a user wanted to mention their goal within a paragraph of a post, things could get really messy.
