### ISSUE TITLE
Pagination for listing in admin is not working through a custom page number

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#1847]
## Issue Overview
Let's consider a scenario where list has 6 pages in total and we need to go to page 4 directly using text box of pagination. Then entering 4 in the text box and pressing `Enter` does nothing on most of the list pages.
![Pagination_Issue](http://recordit.co/nkwugRQHZm.gif)

## Expected Behavior
It should redirect to the page number entered.

## Current Behavior
It is not redirecting to the page number entered.

## Possible Solution
Pagination for Listing of Donation Forms is working. However, custom pagination using `WP_List_Table` is not working. 

## Steps to Reproduce (for bugs)
1. Go to `Donations > Reports > Forms` or any other list page
2. Make sure you have excess amount of data around 3-4 pages.
3. Enter page number in pagination and press `Enter`
4. Confirm whether it is redirecting or not.

## Todos
- [x] Tests
- [x] Documentation

**Comment by DevinWalker** [comment]
Thanks @mehul0810!
