### ISSUE TITLE
Add Reference field for PayPal Standard donations

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#185]
Some organizations have a parent 501c3 which owns the PayPal account. Funds are directed to the child-organization through a "Reference" that PayPal accepts and assigns that tag to the payment which makes it easier for the organization to designate payments to different funds or child organizations.

Here's a screenshot of the results: 

![2015-07-21 14_36_19-pay fast with paypal - paypal](https://cloud.githubusercontent.com/assets/930724/8813159/23befae2-2fb6-11e5-98ff-85a0226ed34c.png)

From the output of the PayPal Donation button generator, it looks like that is generated from the `hoseted_button_id` which is referenced here: https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/

But the developer doc mentions that that field is only supported if there is a donation button created and saved with that hosted_button_id in the account.

Will have to bug PayPal more to see if that is technically true, or if there is a way to incorporate this into Give reliably or not.

**Comment by DevinWalker** [comment]
This is only for hosted buttons - not applicable to Give's PayPal Standard implementations. Essentially, you can embed a PayPal donate button for another organization on other sites using this field. From my research, the same isn't possible with PP Standard.
