### ISSUE TITLE
Cron job: give_validate_license_when_site_migrated is running continually

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1851]
## Issue Overview
Cron job `give_validate_license_when_site_migrated` is running continually

As reported here:
https://secure.helpscout.net/conversation/395440683/8848/?folderId=672201

## Expected Behavior
It should only run once until triggered again.

## Current Behavior
It seems to be running continually. 

## Steps to Reproduce (for bugs)
1. Most likely need to migrate a site that had active licenses to trigger it
2. Use WP Crontrol plugin to monitor/replicate the issue as reported in the HelpScout ticket above

## Related Issues and/or PRs
Most likely related to recent licensing updates in versions 1.7-1.8
https://github.com/WordImpress/Give/issues/357

## Todos
- [ ] Replicate problem
- [ ] Identify solution and fix it
![fix it!](https://m.popkey.co/dbe8a5/eLkEw.gif)
- [ ] Migrate a site again to trigger the cron again, then confirm it no longer runs continually

**Comment by ravinderk** [comment]
@mathetos @DevinWalker Cron should run only once.
For Ref: https://github.com/WordImpress/Give/blob/master/includes/actions.php#L136

I will look into this.

**Comment by Vernal** [comment]
This happened on a site which was http and switched to https after installing give. I'm 90% certain the problem started when the url change occurred.

**Comment by kevinwhoffman** [comment]
@Vernal This reminded me of a [similar issue](https://wordpress.org/support/topic/give-fills-up-cron-with-32000-tasks/#post-9027479) from the .org support forums. The user was able to fix the issue with the following:

> I changed the `give_site_address_before_migrate` option so that it matched `home` and the extra cron jobs have stopped being created.

**Comment by Vernal** [comment]
Alright I gave that a try and it doesn’t seem to have worked. I did it at 18:18:50 and new jobs are still being created now at 19:31:27. If I see a change in that I’ll report back.

**Comment by DevinWalker** [comment]
Hey @Vernal any update here? I haven't seen any reports of this issue since your report. Just hoping we can reproduce it somehow.

**Comment by Vernal** [comment]
Hey Devin - I’m working with Matt on this via a ticket. We’ll update here when we have more to work with.

J

**Comment by mathetos** [comment]
Chatted with @Vernal today and it appears this has been resolved by clearing the licenses completely, clearing them from a second site as well, then adding them in new. There may still be a very niche issue here but it seems highly irregular and difficult (or impossible) to reproduce.

Closing for now until we get any other related reports from customers.

**Comment by DevinWalker** [comment]
I'm seeing this issue crop up again, reopening.
