### ISSUE TITLE
fix(admin-license): if Give license is a lifetime license in EDD it won't activate

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1853]
## Issue Overview
It doesn't happen often, but occasionally we give out a lifetime license or use it internally. When attempting to activate a license that is lifetime you see the following:

![2017-07-11_14-10-01](https://user-images.githubusercontent.com/1571635/28090859-a5fa906a-6642-11e7-8127-db380050a31f.png)

Note: the day is today's date. 

How the license looks in EDD:

![2017-07-11_14-10-38](https://user-images.githubusercontent.com/1571635/28090884-bcce772a-6642-11e7-9f6c-6d1d033751f3.png)

## Expected Behavior
Lifetime licenses can activate

## Current Behavior
They don't activate

## Steps to Reproduce (for bugs)
1. Give install
2. Use lifetime license to activate an add-on

## Related Issues and/or PRs
#1586 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@DevinWalker I was not able to reproduce it and I can see two different license key in the screenshots.

**Comment by ravinderk** [comment]
@DevinWalker My setup contains:
1)   Easy Digital Download: `2.7.11`
2)  EDD-Software-Licensing: `3.4.7`
3)  Edd Recurring: `2.4.11`
4) Give EDD Software Licensing API Extended: `0.2`

Can you tell me your setup info because with this setup I am getting correct `activate_license` and `check_subscription`:
```
From my local edd setup


activate_license
stdClass Object
(
    [success] => 1
    [license_limit] => 1
    [site_count] => 1
    [expires] => lifetime
    [activations_left] => 0
    [license] => valid
    [item_name] => PDF+Receipts
    [payment_id] => 72
    [customer_name] => Ravinder Kumar
    [customer_email] => ravinder.kumar.apj@gmail.com
)

check_subscription
Array
(
    [success] => 1
    [id] => 4
    [license_key] => dc1cf315d30773cbeb9cfee73ff91219
    [status] => active
    [expires] => 2018-07-14 23:59:59
    [payment_id] => 72
    [invoice_url] => http%3A%2F%2Fedd.dev%2Fcheckout%2Fpurchase-confirmation%2F%3Fpayment_key%3D9e0dea68b312d9ea2a4fc047d5c8b32d
)
```

But I am getting error in response for `check_subscription` from givewp.com

**Comment by DevinWalker** [comment]
Closing in favor of licensing revamp
