### ISSUE TITLE
Phpcs PHPCompatibility issues

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#1860]
## Issue Overview
Here will mention all the WARNING & ERROR when running Phpcs with <a href="https://github.com/wimg/PHPCompatibility" >PHPCompatibility</a> script
`phpcs --standard=PHPCompatibility -d date.timezone=Europe/Amsterdam  --extensions=php,inc,module,install --runtime-set testVersion 5.2-7.0 -pvs .`

The about script will produce all the error and warning about the function that are incompatible with which PHP version

List of error and warning when running PHPCompatibility version from 7.0 to 7.1
https://docs.google.com/document/d/10ajpp_Slpst0UhbXFK_zJSWwr2EmkyFCf80P6FuNQC0/edit?usp=sharing

Here are the following list of ERROR that should be looked first

> FILE: ...\Give\includes\admin\tools\views\html-admin-page-system-info.php
>  243 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed
>      |       | since PHP 7.0; Use mysqli instead
> 

> 
> FILE: ...\givewp\wp-content\plugins\Give\includes\libraries\fpdf\fpdf.php
>  1044 | ERROR | Function set_magic_quotes_runtime() is deprecated since
>       |       | PHP 5.3 and removed since PHP 7.0

**Comment by DevinWalker** [comment]
Please re-run with `phpcs --standard=WordPress`
