### ISSUE TITLE
The custom fields created with FFM always disappear when i switch payment type

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#1861]
## Issue Overview
The Custom fields that is created with FFM get disappear when payment method type is change.
Note: It was working well till version 1.8.8 but after release of version 1.8.9 the functionally get break 
See the video for more information <a href="https://drive.google.com/open?id=0B-lBGJ57pOVTR2oxaWRGbVQxVUk"> Video Link </a>

## Expected Behavior
The Feild should not get deleted when payment method is a change.

## Current Behavior
The Custom fields Add with FFM get disappear when payment method is changed.

## Steps to Reproduce (for bugs)
See the Video

## Todos
- [ ] Tests

- [ ] Documentation

**Comment by DevinWalker** [comment]
I think it may be due to actions being renamed, I need to investigate.

**Comment by raftaar1191** [comment]
The issue is in the **Give-Form-Field-Manager** Addon 

Please move this issue to Give-Form-Field-Manager

**Comment by ravinderk** [comment]
@DevinWalker Can you check this commit: https://github.com/ravinderk/Give/commit/33da01ccb36dcc86360584d59523e8d662ef0727

This is the cause of this issue. we renamed/replaced action hook with another.  @raftaar1191 already created a PR for that https://github.com/WordImpress/Give-Form-Field-Manager/pull/139
