### ISSUE TITLE
Admin Dashboard Donation form issues

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#1874]
## Issue Overview
Donation count is not getting properly calculated. We need to reload the page to get the right count of the donation status

## Expected Behavior
On Status change of the donation, the donation count should display proper number of status

## Current Behavior
On status change, we need to reload the page twice to get the proper counting of the donation status

## Possible Solution
Code Fix

## Steps to Reproduce (for bugs)
1. Login to admin dashboard goes to donations list in side the give tab.
2. Change the status of the donation by using the bulk action.
3. Now you will see the status has been changed but we need to reload the page twice to get the proper counting of the donation status

## MORE INFORMATION
Plese, see the attachment for more information.
https://drive.google.com/file/d/0B-lBGJ57pOVTRm9RUTJhWFdQODg/view?usp=sharing

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Good catch! 👏
