### ISSUE TITLE
Unable to submit priority support request on Give website

### ISSUE THREAD

**Issue by jeffreythompson70** [WordImpress/Give#1876]
## Issue Overview
I have tried numerous times to submit a priority support request while logged into the Give website: https://givewp.com/priority-support/. Each time when I hit the "Submit" button it grays out and just sits there. The request is never submitted.

## Expected Behavior
The page should refresh and say that the request has been submitted.

## Current Behavior
Each time when I hit the "Submit" button it grays out and just sits there. I have tried Safari, Firefox and Chrome with the same result. A colleague has also tried multiple browsers with the same result. 

Is there an alternate means of contacting your team? We are experiencing an issue with our recurring donation silent post URL on Authorize.net and need assistance. 

Please provide a WAY FOR ME TO CONTACT GIVE SUPPORT. If you prefer I submit the issue here, please let me know.

Thanks.

**Comment by mathetos** [comment]
Sorry to hear that @jeffreythompson70  -- we've been getting a constant stream of requests all day, so it's possible your email is getting flagged.

Please email me directly at matt at givewp dot com and I'll get you all setup. Sorry for the hassle!
