### ISSUE TITLE
Repeater amount field shows incorrect decimals for the amount field.

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1886]
## Issue Overview
I have decimals set to `0` and I still see decimals in the placeholder value:

![2017-07-18_11-15-41](https://user-images.githubusercontent.com/1571635/28332700-8f707cac-6baa-11e7-8195-5a0ece2ece06.png)

## Expected Behavior
- Placeholder value mimics decimal count

## Current Behavior
- It doesn't respect decimals when it is set to `0`. However, it does for `3`.

## Steps to Reproduce (for bugs)
1. Give Settings > Currency > Decimals > set `0` as value
2. Create a new multi-level donation form and add a repeater, look at the placeholder amount field

**Comment by jaydeeprami** [comment]
@DevinWalker  and @ravinderk , I have started to work on it but I have found that it's resolved in release/1.8.12 branch.
