### ISSUE TITLE
Should Transactions have a "Trash"

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#189]
Currently, when a Transaction is deleted, it's immediately gone from the database. Perhaps instead it should get labelled with a "Trash" status as a backup.

**Comment by DevinWalker** [comment]
While this would certainly add some complexities to the way the core functions... I can't think of a reason why not off the top of my head. Perhaps @pippinsplugins could shed some light as to why EDD doesn't have a trash for individual purchases.

**Comment by pippinsplugins** [comment]
There was a reason but it rather eludes me now. Might have had to do with
the complexity of reversing the reversal of sale logs if a payment is
untrashed.

**Comment by mathetos** [comment]
Ya, the person I dealt with this past weekend I mentioned that changing the status is a better practice anyway. Generally, in accounting you never delete anything. Of course, our "Transactions" page shouldn't be the go-to spot for Accounting anyway.

Still, we need the deletions to re-calculate correctly first, then re-evalutate whether a Trash is useful or necessary at all.

**Comment by DevinWalker** [comment]
Closing this until further considerations provided

**Comment by mathetos** [comment]
Well, a couple other things to consider then:

We talked about giving users the ability to bulk delete all Test Donations. Honestly, I think the "Trash" could be limited only to Test Donations safely specifically because of what I mentioned above about accounting NEVER trashing anything and preferring to change status instead.
