### ISSUE TITLE
Unable to view Renewal payment listing

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1891]
## Issue Overview

<img width="1138" alt="screen shot 2017-07-19 at 1 28 28 pm" src="https://user-images.githubusercontent.com/1784821/28356585-3f217a1c-6c86-11e7-9146-f554dd331c45.png">

Note: I am facing this issue with the current `master` branch and it was working fine till `1.8.8`.

## Expected Behavior

I should show renewals.

## Current Behavior

Empty list but the renewal count is correct.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Good catch!
