### ISSUE TITLE
Delete data on Uninstall prevents deletion

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1900]
## Issue Overview
When the "Delete data on Uninstall" setting is enabled, it prevents Give from being deleted.

## Expected Behavior
Give should be able to be deleted from a WordPress site correctly and all the data removed correctly.

## Current Behavior
When the "Delete data on Uninstall" setting is enabled, it prevents Give from being deleted.

You'll see this message currently:
![image](https://user-images.githubusercontent.com/930724/28441295-e8462420-6d5e-11e7-9053-dfd9421fa90b.png)

## Steps to Reproduce (for bugs)
1. Install Give 1.8.11 from wp.org
2. Go to "Donations > Settings > Advanced" and enable "Remove Data on Uninstall
3. Deactivate Give and try to delete it and you'll see the error message above.

## Potential Cause
My guess is that the uninstall.php functions are triggering a fatal error and preventing the process from happening correctly.

**Comment by DevinWalker** [comment]
@raftaar1191 can you take a look into this?

**Comment by raftaar1191** [comment]
Working on the about issue
