### ISSUE TITLE
Recalculate Income Amount and Donation Counts for All Forms tool is not working

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1905]
## Issue Overview

I faced this issue in `release/1.8.12` branch.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
@mehul0810 is this fixed with the merge of Recurring PR 360?

**Comment by mehul0810** [comment]
@DevinWalker Yes. this is fixed as the issue is with Give Recurring Addon.
