### ISSUE TITLE
Donor list on back end pagination affects the number of items.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1908]
## Issue Overview
The number of donors should not change on a second or third page. It currently does. Also, you can get to all donors by paging through the list, since the total is decreasing with each page.

![donor-pagination](https://user-images.githubusercontent.com/9629102/28533836-93978b74-706c-11e7-8fd0-8c4eebdcc8a7.gif)

## Expected Behavior
You should be able to page through them and not change the total number (or number of pages).

## Current Behavior
Note gif above.

## Steps to Reproduce (for bugs)
1. On a site with more than 70 donors, attempt to page through all donors at Donations > Donors.

**Comment by ravinderk** [comment]
@mehul0810 I think you already fixed. to sure that it is fixed test it with `release/1.8.12`

**Comment by mehul0810** [comment]
@ravinderk Yes. I've fixed the pagination issue on all the listing pages in `release 1.8.12`
