### ISSUE TITLE
Changing level of existing Multilevel donation is buggy

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#1911]
## Issue Overview

On a donation made to a multilevel form, once it is saved/created, going back in and changing the donation LEVEL is buggy. In my tests, switching to certain levels is impossible. I have not been able to pinpoint which levels, but I've been able to replicate the behavior.

## Expected Behavior
If you modify the saved level on the back end of the site at Donations > Donations > Individual donation it should save correctly. 

## Current Behavior
It doesn't save the level, but will change the amount.

## Steps to Reproduce (for bugs)
1. Set up a multilevel form with 3 levels, with unique names and amounts.
2. Submit a donation (front end) to the middle level.
3. Log into the admin area and modify the donation at Donations > Donations > View details
4. On the multilevel dropdown in the Donation information area, change the level to the lowest level, and save the donation.

The Amount of the donation will change, but the level will not. If it does not, try changing it over and over, and eventually it will stop saving.

## More info
On a user's site who reported this issue, it wasn't the lowest tier level that was not being allowed to change, but a different amount/level. It may be related to the fact that there are multiple lels at the same amount tier on that site:

<img width="231" alt="screen shot 2017-07-24 at 6 07 46 pm" src="https://user-images.githubusercontent.com/9629102/28547071-2524111a-709b-11e7-92aa-5404ed40ac99.png">

THe highlighted level is the one that no matter what we do, it won't save to that level. 

## Todos
- [ ] Tests

**Comment by DevinWalker** [comment]
I was able to reproduce this on my end with the first level being unable to be saved:

![2017-07-24_17-06-33](https://user-images.githubusercontent.com/1571635/28549946-88c04eea-7092-11e7-9c44-1ea64e440105.gif)

@mehul0810 please look into this for me.
