### ISSUE TITLE
New upgrades screen isn't running db updates on recurring.givewp.com

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1913]
## Issue Overview
While working on #1896 I tested the upgrades screen on recurring.givewp.com (test site). The site was using a much old version of Give that I updated it from. 

The db upgrades didn't seen to want to run:

![2017-07-24_16-03-32](https://user-images.githubusercontent.com/1571635/28548632-e488c12a-7089-11e7-8356-2de7a71199c5.gif)

## Expected Behavior
Db upgrades would run

## Current Behavior
The page refreshes, adds a query param, and the same options appear. No upgrade is run.

## Steps to Reproduce (for bugs)

1. Log in to recurring.givewp.com
2. Review updates screen
3. Copy to db if necessary
4. Test locally

**Comment by ravinderk** [comment]
@DevinWalker Maybe it was due to cached js file. It is working fine for me.

![z7yzl2pk51](https://user-images.githubusercontent.com/1784821/28569887-62acef2a-7159-11e7-9068-98e55e6aa1eb.gif)

Let me know if you will able to reproduce it again.

**Comment by DevinWalker** [comment]
Weird. Ok, closing until further evidence.

**Comment by drzraf** [comment]
1) upgrade is slow
2) progress does not show: ex the last, 147th step:
`{"data":{"message":"","heading":"Update 2 of {update_count}","percentage":0,"step":147,"update":2,"update_info":{"id":"v1812_update_amount_values","version":"1.8.12","callback":"give_v1812_update_amount_values_callback","type":"database"}}}`
3) After all upgrade successfully happens, the page is not refreshed, still showing the "please update" message.

**Comment by mathetos** [comment]
Hi @drzraf  -- if this is an issue you are having on your site currently, with a live version of Give 1.8.11 please submit a ticket either in our [Free Support Forum](https://wordpress.org/support/plugin/give), or if you are a customer in [Priority Support](https://givewp.com/support).

This particular issue is related to a feature which is not yet live at all.

Thanks!

**Comment by drzraf** [comment]
not live but... the git tag was there and available.
