### ISSUE TITLE
Add a setting to set the default User Role that donors get when registering and donating

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1918]
## Issue Overview
When a donor registers for the site through our donation forms, they are automatically assigned a role of "Subscriber".  Membership plugins and other user-related plugins depend on user roles a lot. It would be useful to allow admins to choose what default user role donors should get.

## Expected Behavior
A setting to set the default user role for donors who register for the site.

## Current Behavior
There is no setting, only a filter. Example filter here:
https://github.com/WordImpress/Give-Snippet-Library/blob/master/admin-functions/change-donor-role.php

## Possible Solution
I think the current best place for this setting is under "Advanced". Like so:
![image](https://user-images.githubusercontent.com/930724/28595476-e9637982-7148-11e7-9dc0-f5b055fc26cd.png)

I considered "Access Control" but that didn't seem to fit really. Open to suggestions for where this setting would make the most sense from a user perspective.

**Comment by ravinderk** [comment]
@DevinWalker @mathetos What do you think about creating a role for donor `Give Donor`?
It will be more easy to give manage donor'ss permission if we have separate role.

**Comment by DevinWalker** [comment]
I agree @ravinderk - like Woo has customer role we should have a donor role.

**Comment by mathetos** [comment]
I also agree @ravinderk I'm actually in the middle of working on a comprehensive issue to address our Give User Roles in general to make the capabilities match the role names better and to match the types of ways Give users actually use Give better as well.
