### ISSUE TITLE
Form Content Wrap doesn't go full width without Featured Image

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#192]
See ticket here: https://wordpress.org/support/topic/donation-form-1?replies=14#post-7246442

The form should go full width under these conditions
- [x] When NO featured image has been selected and there is no sidebar widgets
- [x] When the Featured image has been disabled and there is no sidebar widgets

**Comment by DevinWalker** [comment]
I've added an option to disable the sidebar entirely. Also,

* if feature image is disabled the placeholder will no longer display
* if sidebar is disabled the form goes full width
* if sidebar is disabled, the sidebar is unregistered
