### ISSUE TITLE
assets/js/frontend/give.all.min.js does not work

### ISSUE THREAD

**Issue by drzraf** [WordImpress/Give#1928]
## Issue Overview
After upgrading to 1.8.12, Give started using the assets/js/frontend/give.all.min.js in the production system (SCRIPT_DEBUG = FALSE), and the form stopped working

## Expected Behavior
The form's button should still work (clicking an amount would change the input showing the selected amount)

## Current Behavior
It does not, and no javascript error show up in Chrome's log

## Possible Solution
Workaround: set SCRIPT_DEBUG to TRUE (also it comes with obvious downsides)

## Steps to Reproduce (for bugs)
1. git checkout origin/release/1.8.12
2. go to one donation form page

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Hey @drzraf the `release/1.8.12` is not yet ready for production. You can run gulp and the scripts should work just fine. We'll be sure to test plenty with script debug off before releasing. Please run only the latest public release in production: https://github.com/WordImpress/Give/releases
