### ISSUE TITLE
{user_email} and {billing_address} does not reflect value within Email or Preview Donation Receipt

### ISSUE THREAD

**Issue by jaydeeprami** [WordImpress/Give#1929]
## Issue Overview

Currently, `{user_email}` and `{billing_address}` email tag does not reflect it's valued while previewing Donation receipt.

## Expected Behavior

As `{user_email}` and `{billing_address}`  get value if the Donor has filled their information while processing donation form.

I think we should have to display below value if Admin preview Donation receipt as a Default:
`{user_email}` => Admin email address. 
`{billing_address}`  => blank value.

## Current Behavior

Currently, It does not reflect default value and return email tag.

![screenshot-givewpcore dev1 in-2017-07-31-13-18-57 1](https://user-images.githubusercontent.com/15060983/28770405-ab92a7aa-75fc-11e7-9598-559f8ed4c5f0.png)

## Possible Solution
While preview default Donation receipt we need to show default value like below:
`{user_email}` => Admin email address. 
`{billing_address}`  => blank value.

## Steps to Reproduce (for bugs)

1. Go to  Settings > Donation Receipt
2. Add {user_email} and {billing_address} email tag into Donation Receipt and preview Donation receipt.
3. It will return email tag as it is.

## Related Issues and/or PRs

Working on PR.

## Todos
- [x] Tests

**Comment by jaydeeprami** [comment]
@DevinWalker and @ravinderk , I have fixed it.

**Comment by DevinWalker** [comment]
Reopening because this needs to work in the _actual_ email as well. Not just the preview.

**Comment by DevinWalker** [comment]
Actually @mehul0810 reviewing this gif you provided:

![zufbxbrrcd](https://user-images.githubusercontent.com/1571635/28844370-3e96cfe2-76b9-11e7-9c0a-8be278af8bd7.gif)

You are using the test gateway without the "Billing Details" fieldset included. Even though you have made a previous donation, it's not applicable to the current donation. Therefore, the billing address is not included. If you use a gateway with the billing details (like Stripe or Authorize) then you will see it working properly.
