### ISSUE TITLE
Spinner should be an icon font

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#193]
The current loading icon doesn't look sharp on dark backgrounds. We should swap it out for a font icon: http://www.flaticon.com/search/spinner

![spinner-not-awesome-dark-background](https://cloud.githubusercontent.com/assets/930724/9024016/d12706b8-386a-11e5-911a-596c03e55578.gif)

**Comment by DevinWalker** [comment]
Do we want to keep the WordPress style spinner though?

**Comment by mathetos** [comment]
Not married to it.
