### ISSUE TITLE
Ensure country required state/county conditional field is properly required or not required

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1935]
## Issue Overview
I noticed that for the United Kingdom that we are requiring the "County". This is incorrect and should not be required. We need to be **absolutely sure** the conditional country dropdown displays the appropriate related field as **required** _or_ **not required**. 

![2017-07-31_16-59-02](https://user-images.githubusercontent.com/1571635/28803457-9410d754-7611-11e7-9443-ce043a55043d.png)

## Expected Behavior
All countries state/county/province are appropriately required depending on the requirements of that specific country.

## Current Behavior
Some countries (like the UK) are incorrectly making the "County" field as required when it should not be. 

## Possible Solution
Review each country in comparison to WooCommerce to ensure it's working as expected. 

## Steps to Reproduce (for bugs)
1. Enable a gateway with the billing details fieldset
2. Switch to the UK
3. Notice that "County" is required. It should not be.

## Related Issues and/or PRs
#1050 

## Todos
- [ ] Test each country to ensure the subsequent field is require/not required appropriately.

**Comment by ravinderk** [comment]
@raftaar1191 On first time load form is good but when field show/hide by js, styling does not match. is it styling issue or did I miss something?


![u7wawoj8zo](https://user-images.githubusercontent.com/1784821/28818648-5629d61c-76c9-11e7-8342-f75fd79f534e.gif)
