### ISSUE TITLE
Checkbox for "Create Account"

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#194]
I think we can make the creating an account process much easier and require less fields.We can take some cues from [this EDD Extension](https://easydigitaldownloads.com/downloads/auto-register/) which generates the user account from their email address and auto-generates their password and emails it to them. 

We want to provide as few fields in our Donation forms as possible, this would be a good way to slim down.

**Comment by UaMV** [comment]
Personally, I've never been a fan of a site auto-creating a WP username according to my email, as WP does not currently allow users to change their username. I know too many people who still change email addresses somewhat regularly. This could cause headaches when they return to login. I do agree removing impediments is important, but I think this is one thing to consider.

**Comment by mathetos** [comment]
Thanks for chiming in. I wouldn't like it to create the username by email address either. But since all donations ask for first and last name it could be pretty easy to do something like `matt_cromwell-347` as the username.

**Comment by mathetos** [comment]
Not sure why I didn't clarify that in the original ticket though! Ha! Good catch!

**Comment by UaMV** [comment]
Good to hear ... so, yes, this sounds great!

**Comment by DevinWalker** [comment]
This is Add-on territory. I don't want Give core to get into auto generating usernames. This could lead to issues with larger sites with many users.
