### ISSUE TITLE
Cache direct queries and objects

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1944]
## Issue Overview

Direct queries made with `$wpdb', Give_Donor and Give_Payment do not cache automatically. We can cache them to improve performance.
For example, Donor related queries currently are uncached.
( I will update this after some more research )

Similar #2121

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mathetos** [comment]
@ravinderk Will we be able to clear this cache with a button similar to our "Refresh Reports" button? Users very often want to see the latest data accurately reflected pretty much everywhere in WP Admin. I love things to be able to load more quickly for sure, but users will want accurate data reporting as well.

**Comment by ravinderk** [comment]
@mathetos Cache will automatically get flush when an update occurs in form, donor, and donation. Currently, cache logic is limited to donations and donor only. I will ask you to review when PR will be ready then tell me if you still need cache flush button.

**Comment by ravinderk** [comment]
@DevinWalker Closing this PR for now. I will reopen this if I will find any issue related to it.
