### ISSUE TITLE
fix(donor): adding Multiple Shortcodes on same page should not ask for login multiple times

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#1945]
## Issue Overview
When you place `[give_subscriptions]` and `[donation_history]` shortcode on the same page and then access the page in incognito or non-logged in mode. You'll see two login forms. We need to handle this scenario.

Refer: https://fiddler.online/one-account-page-for-give-donations-woocommerce-to-rule-them-all/ and https://twitter.com/fiddleronline/status/892476319367397377

![image](http://g.recordit.co/5skqBp1JlV.gif)

## Expected Behavior
There should be a single login form.

## Current Behavior
There are multiple login forms for multiple shortcodes.

## Possible Solution
Either by giving an option to show login form or not to each shortcode will help.

## Steps to Reproduce (for bugs)
1. Install Give and Give Recurring Addon.
2. Create a new page/post
3. Add `[give_subscriptions]` and `[donation_history]` shortcodes to that page/post
4. Now, access the page in incognito mode.
5. You'll see that there are two login forms.

## Related Issues and/or PRs
https://github.com/WordImpress/Give-Recurring-Donations/issues/369

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by raftaar1191** [comment]
## Steps to Reproduce (for bugs)
1. Install Give and Give Recurring Addon.
2. Login to Admin and goto Donations > Settings > General > Access Control and Disable **Email Access** option
2. Create a new page/post
3. Add [give_subscriptions] and [donation_history] shortcodes to that page/post
4. Now, access the page in incognito mode.
5. You'll see that there are two login forms.


![image](https://user-images.githubusercontent.com/22215595/38596991-7ffbd8e4-3d72-11e8-96a4-1819c29b0934.png)


![image](https://user-images.githubusercontent.com/22215595/38596996-8640b88c-3d72-11e8-87e3-5db3eebdaf5a.png)

![image](https://user-images.githubusercontent.com/22215595/38597003-913775a0-3d72-11e8-8b41-c308c5ef5360.png)

**Comment by raftaar1191** [comment]
Slack Call Summary

Participants: @raftaar1191, @ravinderk
Topic: Tackling this Issue
Result: Has a call with @ravinderk on this and had a discussion on all the possible way to get this thing sorted and finally came to solutions that we are going to used [enclosing shortcodes](https://codex.wordpress.org/Shortcode_API#Enclosing_vs_self-closing_shortcodes) to get this thing sorted 


## Example
```
[donation_history]
   [give_subscriptions]
[/donation_history]
```


## Example if we want to change the donation history message
![image](https://user-images.githubusercontent.com/22215595/38618489-72315bae-3db7-11e8-918a-ca9b6cd12760.png)
->  We can use`give_donation_history_nonuser_message` filter to do that


## What if we want to change the placing of the shortcode
![image](https://user-images.githubusercontent.com/22215595/38618696-08c3672e-3db8-11e8-842a-ae784bd96c00.png)
-> we can do that by CSS easily
