### ISSUE TITLE
Amount column shows an incorrect price range in all forms table for multi level donation

### ISSUE THREAD

**Issue by marutim** [WordImpress/Give#1946]
## Issue Overview
The amount column shows an incorrect price range in all forms table for multi level donation

## Expected Behavior
It should always show the correct price range.

## Steps to Reproduce (for bugs)
Create a new multi level donation form.
Add levels such as (text/amount) level1/5$, level 2/500$, level 3/500$, level4/5000$ and then save it.
The Amount in the "All forms" table shows the correct price range which is 5.00$-5000.00$

This sets _give_levels_minimum_amount to 5.00 and _give_levels_maximum_amount to 5000.00

Now go back to the form and change the amount in level 1 to 60$ and save it.
Now you will see the Amount in the "All forms" table shows an incorrect price range, here it shows 5,000.00$  –  500.00$

This sets _give_levels_minimum_amount to 5000.00 and _give_levels_maximum_amount to 500.00

**Comment by ravinderk** [comment]
@marutim  Good catch. This is because we are not sanitizing amounts before comparisons.

**Comment by marutim** [comment]
@ravinderk Thank you :) and many thanks for the quick fix 👍

**Comment by DevinWalker** [comment]
I echo what @ravinderk says. Good catch @marutim

**Comment by marutim** [comment]
Thank You @DevinWalker 👍
