### ISSUE TITLE
Delete payment's log if admin delete payment with tools

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1954]
## Issue Overview

<img width="734" alt="screen shot 2017-08-04 at 8 26 01 am" src="https://user-images.githubusercontent.com/1784821/28952418-ae5c2ff2-78ee-11e7-8fd5-e6ef0212d650.png">
<img width="1056" alt="screen shot 2017-08-04 at 8 25 51 am" src="https://user-images.githubusercontent.com/1784821/28952419-ae5cee1a-78ee-11e7-8574-743765b7986b.png">

## Expected Behavior

All log associated with payment should be deleted.

## Current Behavior

They still exist in the database.

## Steps to Reproduce (for bugs)

Delete payment or donor + payment using tools and check log screen. You will not see log because of logic but you can see log count and pagination.

**Related Issue** #1700

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
I also find that donor stats is not updated of test transaction deletion.
<img width="1040" alt="screen shot 2017-08-04 at 7 34 43 pm" src="https://user-images.githubusercontent.com/1784821/28972132-22c828b6-794c-11e7-8a0e-d1826812f027.png">

**Comment by DevinWalker** [comment]
@raftaar1191 is this something you can handle?

**Comment by raftaar1191** [comment]
Thanks @DevinWalker 


Working on this

**Comment by DevinWalker** [comment]
Thanks @raftaar1191

**Comment by ravinderk** [comment]
@raftaar1191 Can we use `Give_Payment_Query` to get donations?
For Ref: https://github.com/WordImpress/Give/blob/release/1.8.13/includes/admin/tools/data/class-give-tools-delete-test-transactions.php#L237#L246

Currently, we are using `get_posts`.

And can we remove log also when we delete test donor and their payments?
For Ref: https://github.com/WordImpress/Give/blob/release/1.8.13/includes/admin/tools/data/class-give-tools-delete-test-donors.php

**Comment by raftaar1191** [comment]
Thanks @ravinderk 
That  an good idea as Give_Payments_Query internaly used WP_query 

Doing the Change
