### ISSUE TITLE
Calculate payment count on basis of active payment status

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1955]
## Issue Overview

`give_count_payments` function calctulate payment count with active payment status.

<img width="896" alt="screen shot 2017-08-04 at 12 23 24 pm" src="https://user-images.githubusercontent.com/1784821/28958093-8abed7e2-7912-11e7-9bae-e22479745120.png">

<img width="1031" alt="screen shot 2017-08-04 at 12 44 24 pm" src="https://user-images.githubusercontent.com/1784821/28958125-ae1e9ccc-7912-11e7-980b-0119ddf85e98.png">

## Expected Behavior

Enable/Disable recurring payment gateway add-on should affect `All` the count.

## Possible Solution

`All` payment count remain same

**Comment by DevinWalker** [comment]
Good catch @ravinderk
