### ISSUE TITLE
Consider alternatives to the browser popup for the upgrade script to run

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1959]
## Issue Overview
We've gotten a few users who are unable to upgrade Give properly since version 1.8.12. I've seen screencasts showing that our browser alert is not showing for them, which is preventing them from continuing the upgrade process. Let's consider alternatives.

## Expected Behavior
The upgrade process should be able to proceed reliably regardless of the browser or browser extensions.

## Current Behavior
The popup alert seems to be blocked relatively easily which gives the user no option to proceed with the upgrade unless they deactivate all extension and/or try a different browser completely.

## Possible Solution
1) A magnific popup instead?
2) No-popup, just a conditional button that first says "Before proceeding, make sure you've backed up your database. Have you done so already?    Yes   |   No"

Number 2 seems to me to be the most reliable option.

**Comment by ravinderk** [comment]
@mathetos We already has an issue for that but maybe we need to revisit it's priority because there are lots of updates also coming in `2.0` (  till 10 updates in `2.0` )

@DevinWalker What do you think

**Comment by DevinWalker** [comment]
@raftaar1191 Please implement this alternate UI until we get the modal update in place:

_When a user clicks the "Update" link they will see the following appear in the place of the JS confirmation._ 

![2017-09-25_21-37-34](https://user-images.githubusercontent.com/1571635/30844488-183df3dc-a244-11e7-8556-9f21d413be43.png)
