### ISSUE TITLE
Menu section should be called "Donation Forms"

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#196]
"Forms" is too generic for the Menu area. We should call it "Donation Forms".

![2015-08-03 13_40_25-menus give wordpress](https://cloud.githubusercontent.com/assets/930724/9047263/84051614-39e5-11e5-948b-32d3b2da3de2.png)

**Comment by DevinWalker** [comment]
I'm not sure this is a functionality right now... we may be running into limitations within WP core. I asked a question on AWP to find an answer.

**Comment by pryley** [comment]
This should do the trick:

```
function modify_nav_menu_meta_box_object( $post_type )
{
	if( isset( $post_type->name ) && $post_type->name == 'give_forms' ) {
		$post_type->labels->name = 'Donation Forms';
	}

	return $post_type;
}

add_filter( 'nav_menu_meta_box_object', 'modify_nav_menu_meta_box_object' );
```

**Comment by DevinWalker** [comment]
That does the trick nicely! Nice one. Great little function.
