### ISSUE TITLE
Twenty Seventeen "dark" theme colors default are just not good.

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1962]
## Issue Overview
If you have the Twenty Seventeen theme with the "Dark" color scheme applied, the Give forms natively just don't look nice.

![image](https://user-images.githubusercontent.com/930724/29044272-7bfc4416-7b73-11e7-9bdd-8a7c02ac96d4.png)

**Comment by kevinwhoffman** [comment]
Also note the placeholders for First Name, Last Name, and Email Address use the light gray color that requires more contrast. That becomes apparent if you're not logged in or delete the pre-filled values.
