### ISSUE TITLE
Add Donation Importer to allow for Bulk Adding of Donations

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1966]
@Benunc commented on [Mon Jan 30 2017](https://github.com/WordImpress/Give-Manual-Donations/issues/45)

## Issue Overview

User request: bulk adding donations manually. related to the WP ALL Import Add-on I suggested: https://docs.google.com/spreadsheets/d/1Zqgp_U6SNTvafRkQhtfUHc-6FSqQW5QtrHpqrGsi-ZA/edit#gid=0

## Expected Behavior
Drag and drop a csv into the manual donations field to import multiple donations at once.

## Current Behavior
It's currently one at a time.

## Possible Solution
a separate add-on would probably be easier, but since I got the request from a user of this add-on, I thought I'd put the issue here.

## Todos
- [ ] Tests
- [ ] Documentation

---

@DevinWalker commented on [Mon Jul 31 2017](https://github.com/WordImpress/Give-Manual-Donations/issues/45#issuecomment-319162513)

Hey @raftaar1191 here's what I'm going for here. 

## Overview

Basically, users want to be able to _import_ donations from a variety of systems into Give using manually donations and a CSV file.  

### Example CSV File

I have created an example CSV file here: https://docs.google.com/spreadsheets/d/1ighe7VM6f8oVACjPlL12qB8LdKoneIgo4fEyYxeUOt8/edit#gid=0

In this CSV you will see a variety of columns that allow donors to import custom data from a CSV file:

- Donation Form
- Donation Amount 
- Donation Level 
- Donation Date 
- Donor First Name 
- Donor Last Name 
- Donor Email 
- Donor ID 
- Donation Status 
- Payment Method 
- Notes 

The plugin should also allow the add _custom fields_ created using Form Field Manager into the system using the **metakey**  as the column heading.

### Functionality

An admin would be able to see a "Bulk Import donations" link when adding a "New Donation"

![2017-07-31_11-50-10](https://user-images.githubusercontent.com/1571635/28793036-8d2af210-75e6-11e7-90e1-7c8591c12b24.png)

The main importer would be located under **Tools > Import Donations**:

![2017-07-31_12-05-42](https://user-images.githubusercontent.com/1571635/28793711-bc71d03c-75e8-11e7-8b77-cdd3a6a8899f.png)

That screen would them take them to the "Importer Wizard", very similar to how Woo's works, where the donor is first asked:

1. Please upload a CSV containing your donation data. 
2. Once uploaded, they are then brought to another screen verifying the field mapping.
3. Once verified, they can then import the field data accordingly.

#### See Also:

Please reference how Woo's importer and WP All Import wizards work while working on this task. If you need any UI help please let me know. 

- WooCommerce importer: https://woocommerce.com/2017/06/3-1-release-product-importer-shipping-service/
- WP All Import: http://www.wpallimport.com/woocommerce-product-import/

---

@raftaar1191 commented on [Tue Aug 01 2017](https://github.com/WordImpress/Give-Manual-Donations/issues/45#issuecomment-319569130)

Other Note Links: https://docs.woocommerce.com/document/product-csv-importer-exporter/?_ga=2.183134883.422115568.1501619192-1375121155.1498799939

**Comment by raftaar1191** [comment]
Demo Video Link [VIDEO](http://screencast-o-matic.com/watch/cbjFrmlM1X)

**Comment by DevinWalker** [comment]
🎉

**Comment by ravinderk** [comment]
@raftaar1191 As we discussed over the call, we have lots of import functionality related specific functions which do not have the general use. Can you move them to import class?

**Comment by DevinWalker** [comment]
@raftaar1191 will you test this: https://wordpress.org/support/topic/export-donors-in-csv-and-csv-toolbox-do-not-export-any-address-information/ when you get a chance. And please if you can reproduce create an issue and respond on WP.org
