### ISSUE TITLE
PHP Notice Errors

### ISSUE THREAD

**Issue by farookibrahim** [WordImpress/Give#1973]
I found two notice errors.

1. Notice: A non well formed numeric value encountered in /wp-content/plugins/give/templates/shortcode-goal.php on line 46

2. Notice: A non well formed numeric value encountered in /wp-content/plugins/give/includes/formatting.php on line 238

I tested with PHP 7.1

Form edit page:
![edit donation form bethlehem wordpress](https://user-images.githubusercontent.com/10401366/29120953-2108c332-7d2a-11e7-985a-e2bf083b2fe5.png)

Single form output:
![help us build a new church bethlehem](https://user-images.githubusercontent.com/10401366/29120959-275f29f6-7d2a-11e7-8c3f-79ef2ca02ab1.png)

**Comment by ravinderk** [comment]
@farookibrahim Thanks for reporting the issue. 

Can you give us your system info?
![image](https://user-images.githubusercontent.com/1784821/29124230-f79f5630-7d35-11e7-9ee5-4499584cf7b8.png)

**Comment by farookibrahim** [comment]
![image](https://user-images.githubusercontent.com/10401366/29124484-ad7c57fa-7d36-11e7-830b-94b2aaa743ae.png)

**Comment by DevinWalker** [comment]
Hey @farookibrahim can you give us steps to replicate? 

@ravinderk and myself have been unable to do so and haven't received any other support request on it yet.

**Comment by DevinWalker** [comment]
Seems like we got some actionable info on this over here: https://wordpress.org/support/topic/php-notice-93/
