### ISSUE TITLE
Period as Decimal separator clearing the amount in multi-level fields

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#1981]
## Issue Overview
This screencast was provided by a customer:
https://screencast-o-matic.com/watch/cbjXoclmgT

## Expected Behavior
The amount shouldn't change when saving the form or choosing different settings in the tabs.

## Steps to Reproduce

1. Set the period as your thousands separator
2. Create a multi-level form with the levels being at least 1,000 or higher
3. Save the form
4. Go to the Display Options tab and save a different setting. Save the form again.
5. Go to the multi-level forms and the amount that was 1,000 will now be shown as 1.

**Comment by ravinderk** [comment]
@DevinWalker @mathetos  This is already fixed in `1.8.13`. Can you confirm?
For Ref: https://github.com/WordImpress/Give/pull/1983

**Comment by DevinWalker** [comment]
Looks resolved to me from my testing just now. @mathetos can you confirm?

**Comment by mathetos** [comment]
All clear now, thanks!
