### ISSUE TITLE
Add donor id support to email tags

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#1992]
## Issue Overview

Currently, most of the emails render on basis of `payment_id` and `user_id`. It will be good if we can add `donor_id` support.
For Ref: https://github.com/WordImpress/Give/blob/release/2.0/includes/emails/class-give-email-tags.php#L473

## Expected Behavior

We should be able to render email tags on basis of `donor_id`.

## Current Behavior

Not working.

## Todos
- [ ] Add `donor_id` support to email tags
- [ ] Use `donor_id` instead of `user_id` in code
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Absolutely. I'd like to start using `donor_id` more wherever possible.

**Comment by raftaar1191** [comment]
Need to work on this once this PR get merge

https://github.com/WordImpress/Give/pull/1885/
