### ISSUE TITLE
Create main "Dashboard" screen with high-level reports that lead to detailed reports

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#1993]
## Issue Overview
Currently there's no "Homebase" page like a Dashboard where you can see activity, high level stats, and quickly add donation forms, donors, etc. We should add that so people can easily get a perspective of what's going on within their fundraising.

**Question:** How does this interact with the "Reports" screen and the revamp of #1527 

## Related Issues and/or PRs
#1527 
#839 

## Todos
- [ ] Design Dashboard
- [ ] Develop Dashboard
- [ ] Test Dashboard

**Comment by ravinderk** [comment]
@DevinWalker We can create a generic dashboard, Which we can use to show a dashboard for single form as well.

<img width="467" alt="screen shot 2017-08-17 at 9 33 21 am" src="https://user-images.githubusercontent.com/1784821/29395559-4cbd24a4-832f-11e7-8041-aa23eba995e4.png">

**Comment by DevinWalker** [comment]
Hmm, I'm not sure I like that idea so much @ravinderk

**Comment by kevinwhoffman** [comment]
A dashboard would be a welcome addition and reason to check into Give more often.

## Ideas

1. **User Survey** - We should consider polling users to find out what type of information is most important for them to see at a glance. It would be a good opportunity to check our assumptions and get the community involved.
2. **Modules** - With Give's wide variety of use cases, the ideal dashboard will be different based on the scale and nature of the Give implementation. For this reason, we might consider designing a series of modules that can be arranged into a dashboard and activated by the user to suit their needs. A small non-profit with a single Give form would have different needs in their dashboard compared to large non-profit with multiple causes.
3. **Add-on Integration** - With a modular approach, add-ons could provide their own modules that can be mixed in with core modules.
    - Tributes could display the 5 most recent cards that need mailed with a link to the full report.
    - Form Countdown could display a form's goal progress and remaining time.
    - Recurring Donations could forecast the next month's donations based on subscriptions.
    - Fee Recovery could highlight the total amount of fees saved.
4. **Iterative Approach** - We might start with a static dashboard with a few modules that are locked in place. However if we approach it modularly we can lay the ground work for a more robust future where modules can be rearranged or toggled on/off.

## Examples
- [Wufoo](https://www.wufoo.com/reporting/) provides a modular report builder that allows each user to build a report that suits their needs. It has a cartoony style but the overall UX is worth exploring.
- [Infusionsoft](http://help.infusionsoft.com/userguides/get-started/initial-setup-checklist/customize-the-home-page-dashboard) also provides a modular dashboard builder. One of the ideas worth nothing here is that the dashboard modules also act as an onboarding device. If a Contacts module exists on the dashboard but you have no contacts, it prompts you to import them with a call to action in the module.

**Comment by mathetos** [comment]
Regarding a User Survey, I think the best for a "best of both worlds" approach would be to do the "Iterative Approach" that @kevinwhoffman mentioned (basically MVP get it out the door based on our own insight and experience) and include a link prominently that says "What info would you like to see here? Let us know" which links to a form on our site to get feedback continually for future development. This would be the most direct way to make sure we're getting feedback directly from users who care about this feature.

Regarding the actual Dashboard, I think it's a great idea for it to be it's own sub-menu item called either "Dashboard" or "Insights" and be the top sub-menu item under "Donations". 

Visually I think the Dashboard should be inspired by Baremetrics. 

In terms of usefulness, I would love for export and reporting functionality to be embedded in this Dashboard as well... potentially even replacing our main Reports screen. Basically, admin should be able to see their data in a visually striking manner but then immediately export that data to do what they like with it.

**Comment by mathetos** [comment]
Just as a reference, here's an example from Gravity Forms of their "Results" for one specific form.

![image](https://user-images.githubusercontent.com/930724/30227212-ac619538-948d-11e7-9f07-8d1109d42ff1.png)

**Comment by kevinwhoffman** [comment]
Closing this as I am setting up the epic for admin reports in #2889.
