### ISSUE TITLE
Suggest move banner, makes UI confusing

### ISSUE THREAD

**Issue by gingerling** [WordImpress/Give#1997]
## Issue Overview

On the settings page a banner displays between the two navigation areas (presumably not all the time, but it was there for me).

This makes the top navigation less visible than the should be, so, for example, I came to the settings page (having not used it in a while) and it wondered why there were only 3 settings tabs (General | Currency | Access Control ).

I later realised there were more tabs at the top (General, Payment Gateways, Display Options, Emails, Advanced) but only because I was looking for specifically the Payment settings as I had configured this before on a previous site. Would be confusing to a new user.
 
![screenshot from 2017-08-18 12-53-46](https://user-images.githubusercontent.com/2853040/29458123-7efa33e4-8415-11e7-93d3-27213089aa4b.png)

## Possible Solution

Suggest moving the banner to above the top tabs.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mathetos** [comment]
Thanks @gingerling -- totally agree. We'll look into it.

**Comment by gingerling** [comment]
Great

**Comment by DevinWalker** [comment]
Very nice UI/UX improvement here. Thanks @mehul0810 for the implementation and @gingerling for the suggestion!

**Comment by gingerling** [comment]
thanks :)
