### ISSUE TITLE
Changes to settings are lost if not saved when changing between tabs or sub-tabs, no notification gievn

### ISSUE THREAD

**Issue by gingerling** [WordImpress/Give#1998]
## Issue Overview

On the settings page, if you change something on Say, Emails > Email Settings then move to Emails > Donation receipt (without clicking save) then changes are removed. There is no "you are leaving the page do you want to save your changes" notification.

## Expected Behavior

To click save one time when making settings changes. I may choose to save multiple times, but I don't usually need to click save for every change or every tab etc. To be notified if unsaved changes will be deleted.

Users should be able to work through all the settings and click save once at the end. As a minimum I would suggest at least all changes on the sub-menu settings should be saved at once, but ideally the main tabs too. When moving away from unsaved changes which will be lost, the user should be notified.

## Steps to Reproduce (for bugs)

1. Go to Emails > Email settings
2. Change the from email 
3. Click to sub tab "donation recipient" (do NOT save)
4. Click back to email settings > email is back as it was before the edit.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mathetos** [comment]
Another good point @gingerling -- an elegant alert highlighting that changes have been made and are not yet saved makes good sense. We'll look into it.

**Comment by gingerling** [comment]
Yeah, I just went back through the 3 sites I set up and found things I would have changed that were not saved and should have been. 

To be clear though, it would be better if the stuff could be saved in one click at the end. Fairly sure that is how it is in many other plugins.

**Comment by mathetos** [comment]
We originally had ajax tabs (meaning all settings on one page, tabbing being seamless) but as Addons add more tabs and more settings it gets out of hand. We had to revert to tabs as pages instead. WooCommerce is another example of settings tabs like ours.

**Comment by gingerling** [comment]
thanks :)
