### ISSUE TITLE
Unsaved changes prompt on publishing a new form

### ISSUE THREAD

**Issue by mzak** [WordImpress/Give#20]
When trying to publish a new form, the unsaved changes warning appears.  Form appears to save correctly when opting to leave the page.

Example: http://www.screencast.com/t/b7Gh8bkr

UPDATE: Issue seems to be a conflict with Google Maps Builder, as it only occurs with that plugin active.  

Environment details:
### Begin System Info ###

	** WORDPRESS DATA **
Multisite:				No
SITE_URL:				http://mystaging.website
HOME_URL:				http://mystaging.website
WP Version:				4.1.1
Permalink:				/%postname%/
Cur Theme:				TwentyFourteen Child Theme 1.0.0
Post Types:				post, page, attachment, revision, nav_menu_item, give_forms, give_payment, give_log, google_maps
Post Stati:				publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, abandoned, active, inactive
User Count:				2

	** WORDPRESS CONFIG **
WP_DEBUG:				Disabled
WP Memory Limit:			40MB
Table Prefix:				wp_
Prefix Length:				Acceptable (3 characters)
Show On Front:				posts
Page On Front:				n/a
Page For Posts:				n/a

	** BROWSER DATA **
Platform:				Apple
Browser Name				Chrome
Browser Version:			41.0.2272.76
Browser User Agent:			Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36

	** SERVER DATA **
jQuery Version				1.11.1
PHP Version:				5.3.29
MySQL Version:				5.5.41-37.0-log
Server Software:			Apache

	** PHP CONFIGURATION **
Safe Mode:				No
Memory Limit:				256M
Upload Max:				128M
Post Max:				128M
Time Limit:				60
Max Input Vars:				1000
Display Errors:				On
Sessions:				Enabled
Session Name:				PHPSESSID
Cookie Path:				/
Save Path:				/tmp
Use Cookies:				On
Use Only Cookies:			On
FSOCKOPEN:				Your server supports fsockopen.
cURL:					Your server supports cURL.
SOAP Client:				Your server has the SOAP Client enabled.
SUHOSIN:				Your server does not have SUHOSIN installed.
OpenSSL:				Your server has OpenSSL installed.

	** PLUGIN INFORMATION **
Active Plugins: (3)
	- Give - Democratizing Generosity 0.7 beta
	- Google Maps Builder 1.0.3
	- System Snapshot Report 1.0.1

Inactive Plugins: (16)
	- Akismet 3.1
	- CMB2 2.0.2
	- Disable Comments 1.2
	- InfiniteWP - Client 1.3.10
	- Jetpack by WordPress.com 3.3.2
	- Limit Login Attempts 1.7.1
	- Magic Zoom Plus 5.12.24
	- Managed WordPress Migration 1.2
	- Matram 0.0.2
	- Pinterest "Pin It" Button Lite 2.0.8
	- Records Post Types 0.1-alpha
	- Registered Users Only 1.0.3
	- Safe Redirect Manager 1.7.6
	- Soliloquy 2.4.0.5
	- TablePress 1.5.1
	- WordPress Importer 0.6.1

### End System Info ###

**Comment by mathetos** [comment]
Hey Matt, thanks so much. You're FIRST! ;-)

Ya, we noticed in development that occasionally there's a weird JS error that is preventing WP from publishing correctly and also prevent Categories and Tags from being added. We're on it. Keep testing and keep filling out the issue. MUCH appreciated.

**Comment by mzak** [comment]
Ah, gotcha.  Yeah, I've actually since been to reproduce the issue without the GMB plugin, so apparently it's not specifically a conflict with that.

**Comment by mathetos** [comment]
OK, good to know, thanks for following up with that. We think it has more to do with the default installation out of the box. I have one install that has the error and another (both on Desktop Server) that has that behavior. We thought it was just a quirk with my one install. Now we know to look deeper an reproduce. Thanks!

**Comment by DevinWalker** [comment]
Upon fresh WP Install I am also able to reproduce. Thanks for mentioning this issue. @mathetos has mentioned it but we thought it was an anomaly.
