### ISSUE TITLE
Create a Form settings Import/Export functionality

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2012]
## Issue Overview
Our forms have more and more settings, particularly when you add all our Add-ons. Having the ability to export the form settings and import them into a new form would be very useful.

As an example, Caldera Forms does this really well. It allows you to export the form in its entirety either as a PHP file or JSON format. Then when you go to "Create new Form" there's an option to "Import". 

Adding this feature to our forms could happen in a couple different ways:

* **Option 1:** Related to Issue #2009 we could add a "Import Form Settings" option in the "Donations > Tools" section. You would choose which form the new settings would be imported into. Then there would be an alert that informs you that doing the import will override any existing settings in the existing form.
* **Option 2:** When creating a new form, you might first see a modal popup that says "Create new form || Import new Form". This option would be a more dramatic change, but it has the potential to open new options like "Create form from Template" for when we roll out Theme Styles.

**Comment by mathetos** [comment]
@DevinWalker I think this can be closed in favor of #2009 right?

**Comment by ravinderk** [comment]
@mathetos we can only import core setting. This is still left, for removing confusion I updated #2009 title.

**Comment by raftaar1191** [comment]
What I think so on this  at the time of importing the CSV( Which is created from export Form section ) if that CSV have same `Form ID` or Same `Form Title` then that form will be update else it will create an entirely new form 


So with this user also has the option of creating a new form directly from CSV like we do in Donations

**Comment by kevinwhoffman** [comment]
Closing as importing form configurations will be a major benefit of the new Give Form API in #2905. Adding this as a related issue in the epic.
