### ISSUE TITLE
perf: improve code by processing unrelated tasks as async jobs

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2020]
## Issue Overview

For Ref: https://github.com/WordImpress/Give/blob/release/1.8.13/includes/class-give-cron.php#L253

We can create an async job for following jobs:
1. create log for payment or other
2. create note for donor or payment
etc...

**Comment by DevinWalker** [comment]
@ravinderk I'm unclear as to what this issue entails. Please provide a better description.

**Comment by DevinWalker** [comment]
Closing due to lack of clarity.
