### ISSUE TITLE
"Give Accountant" user role should be able to access the admin dashboard after logging in with WooCommerce activated

### ISSUE THREAD

**Issue by marutim** [WordImpress/Give#2022]
## Issue Overview
With WooCommerce activated. The user with user role "Give Accountant" when logs in, is redirected to the front end of the website and can not access the admin dashboard, whereas the user roles like Give Worker and Give Manager can access the admin dashboard.

The "Give Accountant" user role can access the admin dashboard when WooCommerce is not activated.

## Expected Behavior
The user with "Give Accountant" user role should be able to access the admin dashboard with WooCommerce installed and activated.

## Current Behavior
The user with "Give Accountant" user role can not access the admin dashboard, instead redirected to the front end of the website.

## Steps to Reproduce (for bugs)
- Setup a website with Give and WooCommerce installed, activated and configured.
- Create users with user role Give Accountant and with other Give user roles.
- Logout and then try and login using the user with user role "Give accountant". You would be redirected to the front end with no option to access the admin dashboard.
- Logout and try login with user role Give Worker and you would be able to access the admin dashboard now.

## Support ticket where the issue is reported
https://secure.helpscout.net/conversation/415532353/9690/?folderId=672199

## Screenshots
![giveaccountant](https://user-images.githubusercontent.com/3498917/29825756-f56747b6-8cf2-11e7-8723-f8cc33753f72.png)
![frontend](https://user-images.githubusercontent.com/3498917/29825762-fb135272-8cf2-11e7-98eb-4de21d2cf067.png)
![giveworker](https://user-images.githubusercontent.com/3498917/29825768-fde2a886-8cf2-11e7-9369-d382d0bea9e4.png)

**Comment by mathetos** [comment]
@marutim You raise a good point here. I'm working on a bigger issue with our User Roles in general which will most likely supercede this issue. Just a heads up on that.

**Comment by marutim** [comment]
@mathetos Thanks for the heads up. Do you have a link to the issue  for the user role issue you are working on?

**Comment by mathetos** [comment]
I'm working on it in Google Docs currently. It's a bit comprehensive. I'll refer to it here once I have it created.

**Comment by marutim** [comment]
Okay Matt, that works for me :)
