### ISSUE TITLE
PHP Notice: undefined variable "new_public_key" and "new_secret_key"

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2024]
## Issue Overview
I received this when editing my WP user profile on Give 1.8.13 branch:

![2017-08-29_16-50-29](https://user-images.githubusercontent.com/1571635/29849259-67164218-8cda-11e7-9dfa-d1d11c41f20f.png)

I'm also seeing TWO "Give API Keys" fieldsets:

![2017-08-29_16-53-31](https://user-images.githubusercontent.com/1571635/29849303-b2543c08-8cda-11e7-918d-f65bab09f46c.png)

## Expected Behavior
No PHP warnings/notices appear

## Current Behavior
PHP warning appears

**Comment by DevinWalker** [comment]
I think this is due to my user being screwed up w/ the database on my test site. Let's keep an eye on it when testing but I spun up another environment and couldn't reproduce it.

**Comment by ravinderk** [comment]
@DevinWalker i was able to reproduce this error https://github.com/WordImpress/Give/pull/1885#issuecomment-326277051

**Comment by DevinWalker** [comment]
@ravinderk were you able to reproduce on the 1.8.13 branch too?

**Comment by ravinderk** [comment]
@DevinWalker I was able to reproduce this while saving user profile in `relesea/1.8.13`. I also got new issue, whenever you save user profile, `Give Core` will generate API keys for you even you do not want
![78xpthwthb](https://user-images.githubusercontent.com/1784821/29954017-4eb7f8dc-8ef2-11e7-9d86-3430be43cbe7.gif)

**Comment by Umangvaghela** [comment]
It is fine if we change this function:

```
public function generate_api_key( $user_id = 0, $regenerate = false ) {

		if ( empty( $user_id ) ) {
			return false;
		}

		$user = get_userdata( $user_id );

		if ( ! $user ) {
			return false;
		}

		$public_key = $this->get_user_public_key( $user_id );
		$secret_key = $this->get_user_secret_key( $user_id );

		if ( empty( $public_key ) || $regenerate == true ) {
			$new_public_key = $this->generate_public_key( $user->user_email );
			$new_secret_key = $this->generate_private_key( $user->ID );
		} else {
			return false;
		}

		if ( $regenerate == true ) {
			$this->revoke_api_key( $user->ID );
		}

		update_user_meta( $user_id, $new_public_key, 'give_user_public_key' );
		update_user_meta( $user_id, $new_secret_key, 'give_user_secret_key' );

		return true;
	}
```
```
**public function generate_api_key( $user_id = 0, $regenerate = false ) {

		if ( empty( $user_id ) ) {
			return false;
		}

		$user = get_userdata( $user_id );

		if ( ! $user ) {
			return false;
		}

		$public_key = $this->get_user_public_key( $user_id );
		$secret_key = $this->get_user_secret_key( $user_id );

		if ( empty( $public_key ) || $regenerate == true ) {
			$new_public_key = $this->generate_public_key( $user->user_email );
			$new_secret_key = $this->generate_private_key( $user->ID );
			
			update_user_meta( $user_id, $new_public_key, 'give_user_public_key' );
			update_user_meta( $user_id, $new_secret_key, 'give_user_secret_key' );
		
		} else {
			return false;
		}

		if ( $regenerate == true ) {
			$this->revoke_api_key( $user->ID );
		}
		return true;
	}**
```

**Comment by ravinderk** [comment]
@Umangvaghela We already fixed this issue. Please check this function and let me know if you face any issue https://github.com/WordImpress/Give/blob/release/1.8.13/includes/api/class-give-api.php#L1859

Thank you for the suggestion.
