### ISSUE TITLE
Customer meta value not getting deleted

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2028]
## Issue Overview
When deleting the customer information from the **donor single page** or from the **tools->data** drop-down the customer meta value did not get deleted 

## Expected Behavior
When deleting the customer, the custom meta row related to customer should also get deleted 

## Current Behavior
Only the customer row is getting deleted from the **give_customers** no row is getting deleted from the **give_customermeta**

## Possible Solution
Updating the class **Give_DB_Donors**

## Steps to Reproduce (for bugs)
See the video
http://screencast-o-matic.com/watch/cbjwcOInlD

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by raftaar1191** [comment]
PR Link https://github.com/WordImpress/Give/pull/2030

**Comment by DevinWalker** [comment]
Thanks for the video @raftaar1191
