### ISSUE TITLE
Fresh Give install default settings missing

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2035]
## Issue Overview
I noticed today when spinning up a fresh environment that some of the proper default values are not being set:

![2017-09-01_18-15-14](https://user-images.githubusercontent.com/1571635/29991753-9d275662-8f41-11e7-96ef-c78cd61d4716.png)

The number of decimals by default should be 2. As well, The decimal separator should be `.` - This is most common usage for us and if users have to change it themselves that's not good.

Please go back to pre-1.8 refactor of the install and determine which default settings are working and which are not being set. For instance, I noticed that `number_decimals` is set here: https://github.com/WordImpress/Give/blob/master/includes/install.php#L302 but it appears to not be setting this option correctly.

**Please include a unit test in the PR so we can be _sure_ it's working from hereon out.**

## Expected Behavior
Install defaults work as intended.

## Current Behavior
Some options are not saving properly.

## Possible Solution
Bug hunt + unit tests

## Steps to Reproduce (for bugs)
1. Fresh WP Install
2. Download Give from `master` or the WP.org repo
3. Activate
4. Notice currency formatting is incorrect

**Comment by ravinderk** [comment]
@mehul0810 this issue has been fixed. Please write a PHPHunit test to verify default settings.
