### ISSUE TITLE
Add setting to select default state

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2036]
## Issue Overview

Right now we can set the default country. But we should also allow admins to select the default _state_ if applicable.

For instance, if I run a nonprofit that's specific to California I would want the state to always be CA by default. This would allow easier donations for state residents because they wouldn't have to select their state. 

## Expected Behavior
Admins can select the default state in general settings.

## Current Behavior
There is no option to select the default state.

## Possible Solution
Create a new field below "Base country" that is "Default state/province" and have this field conditional based on the base country. If you change from the US for instance to another country with states/provides/whatever then it will update accordingly.

**Comment by ravinderk** [comment]
@DevinWalker What do you think about this setting on per form basis?
Because each single form can be dedicated to different state

**Comment by raftaar1191** [comment]
@ravinderk  like your idea

**Comment by raftaar1191** [comment]
@ravinderk  like the Idea
