### ISSUE TITLE
Rearrange address fieldset in more logical order

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2037]
## Issue Overview
Currently when completing an address fieldset it feels out of order from State > Zip. Typically, we see that the order should be:

1. Country
2. Address 1
3. Address 2
4. City
5. State
6. Postal / Zip

This trick on this PR will be to ensure the fieldset appears nice visually but is also in a logic and expected order. 

![2017-09-01_18-31-04](https://user-images.githubusercontent.com/1571635/29991856-bd61a336-8f43-11e7-81db-cf5ed7ace483.png)

## Expected Behavior
The address fieldset follows order. (See Woo's for instance).

## Current Behavior
Give's address fields are out of order and do not conform to ecommerce standards.

## Possible Solution
Reorder fields, ensuring tabbing works properly, and the layout looks good. For instance, Zip/Postal is a short field and should not be full width.

**Comment by raftaar1191** [comment]
@DevinWalker 

Will this be good
![from-deepak](https://user-images.githubusercontent.com/22215595/30126854-f07543c0-935a-11e7-9f55-36a4695b7178.jpg)

**Comment by DevinWalker** [comment]
I like how WooCommerce does it with the country first. 

It seems to be best like:

1. Country
2. Address 1
3. Address 2
4. City
5. State
6. Zip

Laid out nicely like you have it.

**Comment by mathetos** [comment]
It would be great if City | State | Zip could be on the same row, three columns. But I believe some countries have just a city/zip or just city/state so we'd have to dynamically swap between three and two columns.

**Comment by raftaar1191** [comment]
@mathetos 

Thanks for your suggestion, yes I also think it would look great

**Comment by DevinWalker** [comment]
@raftaar1191 can you put together another mockup for us to review?

**Comment by raftaar1191** [comment]
@DevinWalker @mathetos 

Here is the new mockup that I created for billing fields 

Please let me know if this looks good or not?


![billing-files](https://user-images.githubusercontent.com/22215595/30276301-011b6752-9722-11e7-9afc-3c83feec3e46.jpg)

**Comment by DevinWalker** [comment]
Hmm, the three fields together looks pretty tight. Especially for "City". Let me take a shot at it. I'll post back here.

**Comment by mathetos** [comment]
In the US, the "country" field would be at the very bottom. So, in my mind this would be a more logical flow:

Address 1
Address 2
City  |  State
Zip  |  Country

**Comment by DevinWalker** [comment]
@mathetos it makes more sense to have it at the top because changing the country modifies the state/province field. You wouldn't want users completing that field then switching the country and having to go back and edit the field again. Woo and a number of leading eComm sites have it as the first field in the address fieldset. I think we should follow suit.

**Comment by mathetos** [comment]
@DevinWalker that's a good point. Just thinking of ways to do only two per row instead of three.

**Comment by DevinWalker** [comment]
@raftaar1191 check out this layout: 

![address-layout](https://user-images.githubusercontent.com/1571635/30352844-3aa1c402-97d7-11e7-9d20-66c459e2aec4.jpg)

It's only slightly longer with the "City" field being full width now. I think it looks pretty decent and most donors will skip over the country field since likely they will be in the country of the cause.

**Comment by raftaar1191** [comment]
@DevinWalker 

But we are adding the two section into one then if we add the first name and the last name
![screenshot-localhost-2017-09-13-05-14-25](https://user-images.githubusercontent.com/22215595/30353253-774e0350-9842-11e7-96ac-4f3c1c9f2833.png)
 `Personal Info` and `Billing Details`

**Comment by DevinWalker** [comment]
@raftaar1191 you're totally right. I just removed those fields from the image. Don't know what I was thinking there... just wasn't paying attention I guess.

**Comment by raftaar1191** [comment]
@DevinWalker 

I think we should add City in place of State and vice verse. As State fields are sometimes invisible to the user ( Because it does not have a state init )

**Comment by raftaar1191** [comment]
There are other pages as well where I think we need to arrange the Address fields
1>Shortcode: `give_profile_editor` 
![image](https://user-images.githubusercontent.com/22215595/30479119-69d56862-9a31-11e7-8070-04108c86a211.png)


2> Admin DashBoard Donations Single Page 
![image](https://user-images.githubusercontent.com/22215595/30479153-90effcaa-9a31-11e7-8051-e6e9a723bb95.png)


3> In the `Give Tributes addon`
![image](https://user-images.githubusercontent.com/22215595/30479212-d43e5c90-9a31-11e7-9f6f-efd9b384f5bd.png)

**Comment by DevinWalker** [comment]
Yes, @raftaar1191 we need to update it wherever an address field is present for consistency.

1> Shortcode: give_profile_editor YES
2> Admin DashBoard Donations Single Page YES
3> In the Give Tributes addon - YES

And also within the new Gift Aid add-on as well.

**Comment by raftaar1191** [comment]
@DevinWalker 

Thanks, Will update that soon

One more question? 
I think we should add City in place of State and vice verse. As State fields are sometimes invisible to the user ( Because it does not have a state init )

**Comment by DevinWalker** [comment]
What's that @raftaar1191 - I didn't get what you said.

**Comment by raftaar1191** [comment]
@DevinWalker 

I think we should add city in place of state and state in place of city, As state in some cases may not be available to user

Example:
![image](https://user-images.githubusercontent.com/22215595/30516385-55229090-9b5b-11e7-9131-bdc46c6ceafe.png)

**Comment by DevinWalker** [comment]
Thanks @raftaar1191
