### ISSUE TITLE
Goal amount not respecting thousands separator

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#205]
If you change the decimal and thousands separator to the European format then the Goal amount doesn't respect it. I duplicated the problem locally. See this ticket here:

https://wordpress.org/support/topic/goal-amount-does-not-save-properly?replies=2#post-7296565

**Comment by ibndawood** [comment]
@WordImpress/owners - I have submitted the fix in a separate branch. Please test them from your site before merging into the master and delete the branch.

**Comment by DevinWalker** [comment]
@ibndawood checking it out now

**Comment by sebwinters** [comment]
I'm still having this issue? Anyt fix to be implemented?

![schermafbeelding 2019-02-24 om 11 58 41](https://user-images.githubusercontent.com/11393491/53298371-3d060800-382d-11e9-8905-efa2ecba150c.png)

**Comment by ravinderk** [comment]
@sebastienserre we already resolved this issue in `Recurring 1.8.4`.
Please update your plugin to the latest and Let us know if the issue persists after the update.

ref: https://github.com/impress-org/give-recurring-donations/issues/803

**Comment by sebwinters** [comment]
@ravinderk Thanks for the reply.
 I've donwnloaded the plugin from the givewp.com site yesterday and thus I'm running on 1.8.6.
Also your link is going to a 404 page.
Regards,

**Comment by mathetos** [comment]
Hi @sebwinters -- this sounds a bit more like a technical support issue because we have many hundreds of users using the Addon without this problem. Can you reach out to our Technical Support team and we'll dig into it right away?
https://givewp.com/support

Thanks!
