### ISSUE TITLE
Give Reports section no thousands separator

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2053]
## Issue Overview
In the give report section, there is no Thousands Separator user to diff between the amount 
See the video for more clarification 
http://screencast-o-matic.com/watch/cbQi30IQK4

## Expected Behavior
It should show the Thousands Separator sign that is being set from the give setting> currency tab

## Current Behavior
NoThousands Separator sign is used 

## Steps to Reproduce (for bugs)
1.Click on the Report tab if the give inside the income tab on the right side you can see that there is not NoThousands Separator sign is used 

## Related Issues and/or PRs
https://github.com/WordImpress/Give/issues/1981
https://github.com/WordImpress/Give/issues/1982

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Thanks @Sidsector9 !

**Comment by Sidsector9** [comment]
You're welcome @DevinWalker
