### ISSUE TITLE
Add new sub tab inside Donaitions > Setting Called CSS and JS

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2060]
## Issue Overview
There should be a textarea in the give setting sub menu page which adds CSS and JS to the sites directly.

## Expected Behavior
There should text box where user can enter the CSS directly that will be add in the sites directly and same for JS

## Current Behavior
I have to first download this plugin `https://wordpress.org/plugins/simple-custom-css/` add to the sites than open the page that this plugin creates and then paste the CSS code into it 

## Possible Solution
Add a sub Menu call CSS that will add the CSS in the Frontend of the Sites and Same for JS

Screenshot 
![image](https://user-images.githubusercontent.com/22215595/30243123-a8a22d84-95c0-11e7-953b-eac080a08431.png)

![image](https://user-images.githubusercontent.com/22215595/30243154-52280ebe-95c1-11e7-9823-bb0448cdb940.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
@raftaar1191 I'd rather recommend admins use the built in WP CSS editor within the customizer:

![2017-09-11_12-54-26](https://user-images.githubusercontent.com/1571635/30294025-855c6bd8-96f0-11e7-8fae-89a3f581ebad.gif)

- It's native to WP
- It updates live
- Many users are familiar with the customized
