### ISSUE TITLE
Give Importer: JS error after deleting previous imported donations

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2063]
## Issue Overview
Importing the same file a second time seems impossible currently. When attempting to do an import again from the same file after having used the "Delete Imported Donations" tool, there is a JS error that prevents the second import from finishing.

**JS ERROR**
![image](https://user-images.githubusercontent.com/930724/30246729-0ccfdec8-95b7-11e7-8c37-9e639751540d.png)

**SOURCE OF THE ERROR IN THE JS FILE**
![image](https://user-images.githubusercontent.com/930724/30246736-38f224c0-95b7-11e7-9a95-f6248c527eb3.png)

## Steps to Reproduce (for bugs)
1. Do an import
2. Use the "Delete Imported Donations" tool to delete everything
3. Try to do that same import again. You should see that JS error above

**Comment by mathetos** [comment]
Just tested again locally and on a live site. It's been consistent. The one factor I'm testing next is that my first successful import did NOT map the Donation Date field at all, so I'm testing that now.

**Comment by mathetos** [comment]
Just tested importing without mapping the Donation Date and still the same result.

**Comment by raftaar1191** [comment]
@mathetos 

Not able to regenerate the issues at my end. Can you please help me out to regenerate it at my ends

**Comment by mathetos** [comment]
@raftaar1191 I sent you my original CSV file to test with. Let me also clarify the reproduction steps:

## Steps to Reproduce (for bugs)
* Do an import == I added a new column called "Hurricane Harvey Relief Fund" to the CSV file to map to the Donation Form Title. I didn't map the Donation Date at all. The rest should be obvious, first name, last name, email, amount, etc...
* Use the "Delete Imported Donations" tool to delete everything
* Try to do that same import again. You should see that JS error above

**Comment by mathetos** [comment]
After testing again I'm also not able to reproduce this reliably. It bothers me because I replicated it in two different environments exactly the same each time. Not sure what happened, but closing for now until I can reproduce reliably again.
