### ISSUE TITLE
Give Importer: Add Cancel button and/or JS window alert if closing tab

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2064]
## Issue Overview
It's not totally clear to me what happens when you close a browser tab in the middle of an import. Does it continue going? Or is it 100% dependent on having that browser tab open?

Either way, having a stop/pause, or cancel button for the importer would be useful.

Additionally, adding a browser alert if the user attempts to close the tab while the importer is running would be useful as well.

I'm wondering if potentially this is related to https://github.com/WordImpress/Give/issues/2063 -- that maybe the importer is still running when I'm working on the second import and that's what is making the import JS script fail.

**Comment by raftaar1191** [comment]
It's not totally clear to me what happens when you close a browser tab in the middle of an import. Does it continue going? Or is it 100% dependent on having that browser tab open?
-> It is 100% dependent on that browser tab. It should be open.

**Comment by mathetos** [comment]
@raftaar1191 thanks for the clarification. Then I think a JS window alert is necessary for sure. If the import breaks when the window is closed then we need to alert the user and prevent the tab from closing.

**Comment by raftaar1191** [comment]
@mathetos 

Similarly issues `https://github.com/WordImpress/Give/issues/1998`
WIll fixed this once https://github.com/WordImpress/Give/pull/2067 PR get approved and merge

**Comment by raftaar1191** [comment]
@mathetos 

When Importer is running I don't think **stop/pause, or cancel button** will really be useful. In place of that, I have added Alert when the user tries to reload the page or close the tab. 

Let me know if **stop/pause, or cancel button** if required. I will add that to

**Comment by mathetos** [comment]
Sounds good. Ya, I'm not sure what effects a stop/pause/cancel might have on an import, so that's probably a good call. Thanks!

**Comment by raftaar1191** [comment]
@DevinWalker 

This is a valid issue and it's has been solved. Please see the video for information's http://screencast-o-matic.com/watch/cb6lIOIGBo

**Comment by DevinWalker** [comment]
Looks good thanks 👍
