### ISSUE TITLE
Give Importer: Add sample import file as an example

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2065]
## Issue Overview
We have a sample CSV file included with our Maps Builder Pro plugin and its very useful for our customers and for support purposes. We should do the same here.

**Comment by raftaar1191** [comment]
https://github.com/WordImpress/Maps-Builder-Pro

**Comment by DevinWalker** [comment]
@raftaar1191 I'll create the import sample file based off the one we've been working on but with a lot more relevant data.

**Comment by raftaar1191** [comment]
Okay @DevinWalker

**Comment by DevinWalker** [comment]
I'm bumping this... I haven't had time to create a thorough sample file yet and QA it with the importer.

**Comment by raftaar1191** [comment]
https://wordpress.org/support/topic/error-with-import/

**Comment by raftaar1191** [comment]
CSV file: https://docs.google.com/spreadsheets/u/2/d/1ighe7VM6f8oVACjPlL12qB8LdKoneIgo4fEyYxeUOt8/edit?ouid=108954553682340730163&usp=sheets_home&ths=true

**Comment by Sidsector9** [comment]
Call summary with Deepak
- Discussed issue 2065 and 689
- Discussed about how to prompt users to use the demo file
- Whether to include the demo file inside the Give's repository similar to WooCommerce's, or to directly give the Google Drive's link for users to download the sample CSV file
