### ISSUE TITLE
Give Tools>Data: Add JS window alert if closing tab or reload the page

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2069]
## Issue Overview
See the video
http://screencast-o-matic.com/watch/cbQI13I2d2

## Expected Behavior
Should put some sort of alert message when user try to reload or closed the tab

## Current Behavior
http://screencast-o-matic.com/watch/cbQI13I2d2

## Possible Solution
https://github.com/WordImpress/Give/pull/2067
Use the give alert function when Ajax start and closed when ajax get complete

## Related Issues and/or PRs
https://github.com/WordImpress/Give/issues/2064

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Nice video and good catch @raftaar1191

**Comment by mehul0810** [comment]
@raftaar1191 I can reproduce this issue in Give 2.0. There is no popup when i run the data tool and click on any tab or just change the data tool dropdown resulting in process getting stopped.

**Comment by mehul0810** [comment]
@raftaar1191 Here is the video link: https://drive.google.com/open?id=1GuVXWPoYDDFIRzvMMJvYZSyoEj2IsOm0

**Comment by raftaar1191** [comment]
Nice Catch @mehul0810 able to regenerated the issues 
Thanks fixing this

**Comment by raftaar1191** [comment]
In this https://github.com/WordImpress/Give/pull/2444 the condition is added that is should run on setting page only so that why it was not working 

Fixing this
