### ISSUE TITLE
Add proper text preferably donation amount to Paypal item title instead of custom amount text

### ISSUE THREAD

**Issue by marutim** [WordImpress/Give#2071]
## Issue Overview
It happens for both single or multi level forms. When a donation is processed with fee recovery checked and payment is done via paypal. The paypal item title is suffixed with the "custom amount text". This also happens even when the custom amount is disabled for the form.

For example if you set donation amount is $10 and fee recovery is $0.20 and Custom amount text is "More the better" the paypal item title will be Donation form name - "More
 the better". When custom amount is disabled or custom amount text is not set, it uses the default custom amount text which is "Custom Amount"

## Expected Behavior
Paypal item title should be suffixed with proper text, which can be the correct level for multi level form or no suffix or the donated total amount (including the recovery fee)

## Current Behavior
Paypal item title is suffixed with the custom amount text

## Possible Solution
In the function give_build_paypal_item_title(), the logic is set to consider the donation amount to custom when it doesn't match to any level amount. We need to make an exception for fee recovery addition.

## Steps to Reproduce (for bugs)
- Make a donation using the single or multi level form, check the fee recovery and process the donation via Paypal.
- In the Paypal page, check for the item title.
- Please review the screenshots for better understanding

## Screenshots
![paypal - multi level donation](https://user-images.githubusercontent.com/3498917/30373876-77e59130-98a0-11e7-99ae-0a98a126e0c0.png)
![paypal item title- multilevel](https://user-images.githubusercontent.com/3498917/30373881-7be52d72-98a0-11e7-8c2b-efcb55529ad9.png)
![paypal- single donation](https://user-images.githubusercontent.com/3498917/30373884-7f71ced2-98a0-11e7-9fb4-7cb08f5de496.png)
![paypal itemtitle - single donation](https://user-images.githubusercontent.com/3498917/30373888-83ddc8a4-98a0-11e7-8140-3b6255f3a23d.png)

**Comment by mathetos** [comment]
Excellently written issue @marutim Thanks!

**Comment by marutim** [comment]
Thanks @mathetos :)

**Comment by ravinderk** [comment]
@mehul0810 Improve as deprecated function described in comment https://github.com/WordImpress/Give/pull/2075/files#diff-becfcb2300911b460438043c3c352ba3R640

**Comment by DevinWalker** [comment]
Good call with deprecating the function. Don't want to cause errors for folks who may be using it.
