### ISSUE TITLE
`give_format_amount` method applied twice

### ISSUE THREAD

**Issue by ibndawood** [WordImpress/Give#208]
On Single form page, the method `give_format_amount` is applied twice. 

1. https://github.com/WordImpress/Give/blob/master/includes/forms/template.php#L233
2. https://github.com/WordImpress/Give/blob/master/includes/forms/template.php#L249

This is causing this error. The setting is thousand separator (.) and decimal separator (,) :

![image](https://cloud.githubusercontent.com/assets/179533/9269473/bd3e66ec-4287-11e5-9489-27bf0fc870e9.png)

**Comment by ibndawood** [comment]
@WordImpress/owners - I have submitted the fix in a separate branch. Please test them from your site before merging into the master and delete the branch.

**Comment by DevinWalker** [comment]
Seems to be good for single amounts, but not multi-level amounts
