### ISSUE TITLE
Bulk Actions for Donors

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2086]
## Issue Overview
Currently, there is an option to delete one donor at a time. However, site admin cannot delete donors in bulk. 

![image](https://user-images.githubusercontent.com/1852711/30538261-c9a6d3d8-9c8a-11e7-9f46-789d2fc22a88.png)

## Expected Behavior
There should be Bulk Actions with Delete right now and in future we can extend the Bulk Actions whenever required.

## Current Behavior
You can only delete donor one at a time.

## Possible Solution
Adding Bulk Actions to Donor Listing.

**Comment by ravinderk** [comment]
@mehul0810 Can you fix alignment of search box, bulk action, and pagination

Donor List Screen:
<img width="1104" alt="screen shot 2017-10-25 at 8 00 49 pm" src="https://user-images.githubusercontent.com/1784821/32004425-5c19e196-b9bf-11e7-86b9-ae7c8d2c1a89.png">

Form List Screen
<img width="1105" alt="screen shot 2017-10-25 at 8 01 07 pm" src="https://user-images.githubusercontent.com/1784821/32004426-5c6d1fa0-b9bf-11e7-8337-254d17abb72f.png">

**Comment by ravinderk** [comment]
@mehul0810 as discussed over the call I am reopening this issue.

> After deleting donor if I will reload the same page then I will get ` PHP Warning:  Cannot modify header information - headers already sent` warning.

**Comment by ravinderk** [comment]
@mehul0810 As discussed reopening issue, please remove unwanted query param

![image](https://user-images.githubusercontent.com/1784821/33160316-5293d562-d041-11e7-977d-0356c2fd2279.png)

**Comment by raftaar1191** [comment]
Getting JS error and the display message is also not correct 
http://screencast-o-matic.com/watch/cblhlC2gHP

Js error message:
![image](https://user-images.githubusercontent.com/22215595/33607934-b063b1b6-d9e8-11e7-9304-0ab8c5bc36ee.png)

**Comment by ravinderk** [comment]
@raftaar1191 Redirection is the default behavior of WordPress bulk action. But definitely, we must not get admin notice and js error.

**Comment by mehul0810** [comment]
@raftaar1191 I'm unable to reproduce the issue with latest release 1.8.17. Please check the video for the steps i've tried to reproduce it and let me know if you can still reproduce the issue. 

**Video:** https://drive.google.com/open?id=1rk5mHOCn3G4sREqFVQhCYFLmZfnYwUWr

**Comment by raftaar1191** [comment]
@mehul0810 please do not select the **delete** option from the drop-down please do not select it

**Comment by mathetos** [comment]
Just tested on latest 1.8.17 branch and getting repeating PHP Notices and cannot proceed:

`Notice: The give_decrease_sales_on_undo filter is <strong>deprecated</strong> since Give version 1.7! Use give_decrease_donations_on_undo instead. in ...\wp-content\plugins\give\includes\misc-functions.php on line 481`

The Donor had ONE donation on ONE form, and after doing the Bulk Action ALL the donations for that form were deleted, not just the one.

**Comment by mathetos** [comment]
This was an issue with an old version of Recurring Donations. Resolved for now.
