### ISSUE TITLE
Loading scripts in footer

### ISSUE THREAD

**Issue by ibndawood** [WordImpress/Give#209]
I notice that the give scripts are being loaded in header. I think it is best loaded in footer. Your thoughts ?

**Comment by DevinWalker** [comment]
I think an option to move to the footer under Settings > Advanced would be best

**Comment by DevinWalker** [comment]
The problem with loading scripts in the footer sometimes is a Flash of Unstyled Content (FOUC) - which can lead to more support requests... 

I think an advanced option would be a nice addition...

**Comment by mathetos** [comment]
Had a Twitter convo about this as well:
https://twitter.com/bendelaney/status/636930070842478592
