### ISSUE TITLE
The donation form should reset when go back from the donation confirmation page.

### ISSUE THREAD

**Issue by emgk** [WordImpress/Give#2091]
## Issue Overview
When the donation has been completed and we go back to the donation form page by the back button of the browser then, you will see the last transaction details already populated on that donation form without JS affected.

## Expected Behavior
When donor goes back from the donation confirmation page, the donation form should reset.

## Current Behavior
When we go back to the donation form page from the donation confirmation page, the last transaction values will be populated there.

## Possible Solution
The page which contains the donation form adding these below code snippet would help:
`document.getElementById("<give-form-id>").reset();` or we can use jQuery code.

## Steps to Reproduce (for bugs)
1. Create donation form.
2. Create donation using this donation form.
3. Once you have redirected to the "Donation Confirmation" page hit browser back button.
4. You will see the old values are already populated on this form which you have just used in the last transaction.

## Todos
- [x] Tests
- [x] Documentation

Let me know if there is any further detailed explanation needed.

**Comment by DevinWalker** [comment]
@emgk are you seeing this when logged in? I'm not experiencing this. Can you create a video to further describe?

**Comment by emgk** [comment]
@DevinWalker In my system(windows OS and Chrome) I am facing this issue for both logged-in or non-logged users. please check http://www.screencast.com/t/dx2XV8psuNr

**Comment by DevinWalker** [comment]
@emgk thank you for the explanatory video. 👍 I'm slotting this into the post-2.0 milestone so we can address it.

**Comment by raftaar1191** [comment]
I would Like if we can add the Donation From once Page is load with Ajax. It would also be helpful once pages is catch as the Donation Form HTML is added by ajax
