### ISSUE TITLE
Donor Name is not getting updated 

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2096]
## Issue Overview
The Donor name in `give_customers` table is not getting updated when users update their profile from GiveWP shortcode `give_profile_editor`

Please video the below video for issues overview 
Video Link: http://screencast-o-matic.com/watch/cbQYQvI3lx

## Expected Behavior
The Donor name should also get updated when users update their profile info

## Current Behavior
The Donor name is not getting updated 

## Steps to Reproduce (for bugs)
See the Video

## Note:
Have checked this in release/2.0 branch

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@raftaar1191 I tested this in https://github.com/WordImpress/Give/pull/1885 pr and it is working fine for me. I will reopen this issue if anyone open to reproduce this.
