### ISSUE TITLE
Recurring Donations Parent Payment link incorrect view parameter

### ISSUE THREAD

**Issue by butchewing** [WordImpress/Give#2098]
## Issue Overview
The link for the Parent Payment of a Recurring Donation is incorrect. If you click it, you get redirected to the donations list instead of the donation payment details.

## Expected Behavior
When clicking the Recurring Donations Parent Payment ID link, you should be directed to the donation payment details.
Expected link parameters: edit.php?post_type=give_forms&page=give-payment-history&view=view-payment-details&id=1234

## Current Behavior
Currently, the link gets redirected to the donations list.
Current link parameters: edit.php?post_type=give_forms&page=give-payment-history&view=view-order-details&id=1234

## Possible Solution
The link parameters should be: edit.php?post_type=give_forms&page=give-payment-history&view=view-payment-details&id=1234

The parameter that needs to be corrected is the view value. It should be **view-payment-details** instead of **view-order-details**.

## Steps to Reproduce (for bugs)
1. Navigate to Donations list
2. Click the eye to view Donation Details of a recurring donation
3. Click the Parent Payment ID link in the Recurring Donations

## Related Issues and/or PRs
Possibly related to [#1817](https://github.com/WordImpress/Give/issues/1817)

**Comment by DevinWalker** [comment]
Hey @butchewing I resolved this issue within recurring. It will be released in version `1.4` - thanks for reporting.
