### ISSUE TITLE
Custom Form Fields To Dropdown 

### ISSUE THREAD

**Issue by butchewing** [WordImpress/Give#2099]
## Issue Overview
The Custom Form Fields To Dropdown is not recognizing selected value on the recurring donation payment details page.

## Expected Behavior
The Custom Form Fields To Dropdown should be selected on the value assigned on the recurring donation payment details page.

The Custom Form Fields To Dropdown does work properly on the _Parent_ Payment Details page.

## Current Behavior
The Custom Form Fields To Dropdown is not recognizing the value assigned on the recurring donation payment details page.
 
The Custom Form Fields To Dropdown does work properly on the _Parent_ Payment Details page.

**Comment by DevinWalker** [comment]
I'm not sure I understand what you're saying @butchewing - can you describe further with screenshots?

**Comment by butchewing** [comment]
The dropdown on the recurring paying detail is not selected. The option is not set as selected.

![recurring-detail](https://user-images.githubusercontent.com/405072/30671024-839de90c-9e2a-11e7-8909-3385d15fad5d.jpg)

Notice the console. There is not an item selected.

![recurring-detail-console](https://user-images.githubusercontent.com/405072/30671035-92d52f98-9e2a-11e7-98d6-d648688b07af.jpg)

However, on the parent payment detail, the dropdown menu item is selected.

![parent-detail](https://user-images.githubusercontent.com/405072/30671058-a96038d4-9e2a-11e7-88bc-2c121742ecd5.jpg)

It is reflected in the console as selected.

![parent-detail-console](https://user-images.githubusercontent.com/405072/30671067-b7b465f4-9e2a-11e7-96d9-a2a724aa9ade.jpg)

**Comment by DevinWalker** [comment]
@butchewing I see the issue. I'm going to move this in the Form field manager repo and fix it. Thanks for reporting.

**Comment by DevinWalker** [comment]
Issue moved to [WordImpress/Give-Form-Field-Manager #174](https://github.com/WordImpress/Give-Form-Field-Manager/issues/174) via [**ZenHub**](https://www.zenhub.com/)
