### ISSUE TITLE
Donations over $999.99

### ISSUE THREAD

**Issue by mzak** [WordImpress/Give#21]
Decimals seem to get misplaced on donations over $999.99.  

$1,000.00 process a donation of $1.00 - http://www.screencast.com/t/cWm0LPxYcq
$10,000 process a donation of $10.00 - http://www.screencast.com/t/RC7KpDFd
etc.

Donation history confirms the incorrect dollar amounts, so it doesn't appear to be a problem with how the receipt is generated: http://www.screencast.com/t/KnZPfS96cql

**Comment by DevinWalker** [comment]
Your testing rocks. +1 - we're going to check into wth is going on here

**Comment by DevinWalker** [comment]
Working on this today
