### ISSUE TITLE
Give_Notices: Non-dismissible notices shouldn't have "x" icon 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2100]
## Issue Overview
If you create a non-dismissible notice the "x" icon appears. Clicking it removes the notice but on page reload the notice reappears. 

![2017-09-20_15-41-07](https://user-images.githubusercontent.com/1571635/30671111-2a80fca2-9e1a-11e7-8dd6-4c32aec1de8b.gif)

See how Gift Aid adds a notice: 

```
Give()->notices->register_notice( array(
				'id'          => 'gift-aid-country-notice',
				'type'        => 'error',
				'description' => sprintf(
					__( 'The United Kingdom must be set as the base country within Give\'s <a href="%s">General Settings</a> in order to collect Gift Aid.', 'give-gift-aid' ),
					admin_url( 'edit.php?post_type=give_forms&page=give-settings&tab=general' )
				),
				'show'        => true,
			) );
```

## Expected Behavior
- Non-dismissible notices don't have an "x" icon

## Current Behavior
A dismiss icon appears

**Comment by raftaar1191** [comment]
## Customize Give_Notices API

1. Deprecate auto_dismissible option with backwards compatibility

2. Create new dismissible option to replace it with the following options:
        - auto - notices are removed automatically like with auto_dismissible set to true
         - false no “x” icon at all, non-dismissible
         - dismissible is set to true by default

**Comment by DevinWalker** [comment]
Reopening because @mehul0810 found an annoying bug that should be resolved:

![](http://g.recordit.co/97TnvrWd9r.gif)

When clicking the dismiss icon the `give-message` query arg should be removed in the URL.
