### ISSUE TITLE
Error when viewing Preview Email in New Donor Register and Donor Register

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2102]
## Issue Overview
Getting error when user click on the Preview Email button in Preview Email and New Donor Register Email form in version 2.0 https://github.com/WordImpress/Give/tree/release/2.0

Please video the video for more information: `http://screencast-o-matic.com/watch/cbQr2wI05V`

## Expected Behavior
Should display Email Preview 

## Current Behavior
Getting PHP Warning 

## Steps to Reproduce (for bugs)
See the Video

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@raftaar1191 this issue occurring because `customer ---> donor` renaming without backward compatibility. To resolve this issue we have to work on backward compatibility.

For Ref: https://github.com/ravinderk/Give/commit/d9380e18de6b1861c9f419da44f1f893e3037724

**Comment by raftaar1191** [comment]
Working on this
