### ISSUE TITLE
New Donor Register in preview is not visible

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2104]
## Issue Overview
There is no preview HTML that is visible 
Video Link: http://screencast-o-matic.com/watch/cbQrFOI0RN

## Version
2.O

## Expected Behavior
There should an email preview of the email that is going to send

## Current Behavior
No preview of the email

## Screen Short
![image](https://user-images.githubusercontent.com/22215595/30711674-192e0536-9f27-11e7-8ece-23ac0785fcc6.png)

## Steps to Reproduce (for bugs)
See the Video for the step to reproduce 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by raftaar1191** [comment]
https://github.com/raftaar1191/Give/commit/86d7e8120d5e87744ca645b2f0a7b0c3fe14ce9f

**Comment by raftaar1191** [comment]
Closing the issues because have left the Message body Fields empty

![image](https://user-images.githubusercontent.com/22215595/30717866-d51579aa-9f3b-11e7-8c44-2310b890d8c3.png)

**Comment by DevinWalker** [comment]
That happens... 😆
