### ISSUE TITLE
User Roles and Capabilities need to be cleaned up a bit

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2112]
## Issue Overview
Some Give user roles have abilities they shouldn't, some don't have abilities they should. We also need to give some of the custom Give capabilities to the default user roles.

### Updates to Give Worker
The Give Worker should be able to view all donations, but not edit them. Currently, there is a capability called `view_give_private_payments` but that alone does not allow the Give Worker to view and NOT edit the donations. There's one of two options:

1. Either update that existing capability to function as intended or create `view_give_payments` and have the donation details screen respect that.
2. Update the donation details screen to respect that capability as intended

Or maybe both.

### Updates to Accountant
If we add a new capability `view_give_payments` it needs to be added to the Give Accountant as well.

### Updates to Give Manager
The Give Manager has some capabilities that go outside the scope of Give which I believe are unexpected. Like:
* Editing, Deleting all pages and posts
* Importing/Exporting content via the WordPress Import/Export tools

To fix this, we should remove the following capabilities from the Give Manager:
* `delete_others_pages`
* `delete_others_posts`
* `edit_others_pages`
* `edit_others_posts`
* `manage_categories`
* `import`
* `export`

### Updates to Core Author
The Author expects to be able to contribute content to the website. Give Forms are also content since they have unique slugs. We should add the following capabilities to the Author role:
* `delete_give_forms`
* `delete_published_give_forms`
* `edit_give_forms`
* `edit_published_give_forms`

**NOTE:** I didn't give them `publish_give_forms`. They should be able to author, but a Give Worker, Manager, or Editor needs to approve those posts since they do have a donation form as well.

### Updates to Core Editor
Similarly to the Author, the Editor expects to be able to edit all content on the site. Currently, the Editor role cannot even view Give forms. That is unexpected. We should add the following capabilities to the Editor role:
* `delete_give_forms`
* `delete_others_give_forms`
* `delete_private_give_forms`
* `delete_published_give_forms`
* `edit_give_forms`
* `edit_others_give_forms`
* `edit_private_give_forms`
* `edit_published_give_forms`
* `publish_give_forms`
* `read_private_give_forms`

**Comment by mehul0810** [comment]
@mathetos I've created a screen which shows how to restrict donation detail pageI when a user role doesn't have capability `view_give_payments` 
 
![image](https://user-images.githubusercontent.com/1852711/32109195-9e9ed60a-bb51-11e7-85a7-a246e1ca4e0c.png)

Also, directly visiting the donation detail page will not be accessible and an error is shown.

Please let me know if any further details needs to be changed or made inaccessible to that user role.

**Comment by mathetos** [comment]
@mehul0810 That looks great. The fact that they can view the amount the email address, the form, and even resend the receipt is perfect for users with that role. 

Thanks!

**Comment by DevinWalker** [comment]
Does having access to the payments listing page without `view_give_payments` capability defeat the purpose? Seems that if a user lacks the `edit_give_payments` capability then their view would be the one we see above. Not having `view_give_payments` would prevent the payments listing screen and single view from even being seen.

**Comment by mehul0810** [comment]
Does having access to the payments listing page without view_give_payments capability defeat the purpose? 
**- Yes, without `view_give_payments` we cannot restrict user to just view the donation listing page.**

Seems that if a user lacks the edit_give_payments capability then their view would be the one we see above. Not having view_give_payments would prevent the payments listing screen and single view from even being seen.
**- Not having `edit_give_payments` will restrict whole donation listing page as well as donation detail page from the user. But, we need to show donation listing page with some restriction. Hence we need to have an additional capability `view_give_payments`**

**Comment by DevinWalker** [comment]
@mehul0810 ping me when you come online to review this together.

**Comment by mathetos** [comment]
I noticed a couple issues with this as-is in 1.8.17. 

1) When on the Give Worker or Give Manager Roles, the last column, the "Eye" icon, it has a PHP Notice:
`Notice: Undefined variable: value in ...\wp-content\plugins\give\includes\admin\payments\class-payments-table.php on line 486`

2) This might be a Tributes issue, but the "Preview eCard" is visible, but does not work for this user role. Go to "Donations > Reports > Tributes > eCard" then click the "Preview eCard" and it takes you to the homepage with no error message or anything. The intended behavior is the email preview page. It does work for the Give Manager role. 

3) The Core Author cannot view Give Forms AT ALL now, that is not intended. They should be able to write new Give Forms but not publish them.

4) The Core Editor also cannot view Give Forms AT ALL now, that is also not intended. They should be able to both edit existing, create new, and publish, just like they can for Posts and Pages.

**Comment by mathetos** [comment]
@DevinWalker Informed me of a previous decision about the Core Author and Editor and not assuming capabilities for post types. I can go either way on that idea, so we can ignore items 3 & 4 for now.

1) PHP Notice
2) Preview eCard -- which might be more of a Tributes issue than Give Core.

**Comment by DevinWalker** [comment]
Matt and I just got done discussing how Give's roles and WP Core should relate. Basically, we shouldn't assume that an admin wants the Core roles' capabilities also bestowed upon the Give CPT.   They would have to grant capabilities to those roles in order for the functionality (3-4 above). I'm taking a look at the other items on this issue.
