### ISSUE TITLE
Minor Alignment Issue on Add New Donation Page with Multi Levels

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2115]
## Issue Overview
On the `(-) Remove` icon for levels, there is an alignment issue and flashes on hover.
![GIF](http://g.recordit.co/YAgtTfIAr5.gif)

## Expected Behavior
It should be properly aligned as well as no flashes on hover.

## Current Behavior
Flashes and not properly aligned on hover.

## Possible Solution
Minor CSS change required

## Steps to Reproduce (for bugs)
1. Install Give
2. Add New Donation Form
3. Select Muli Level Donations
4. Add some more levels
5. Hover over `(-) icon` of any of these levels and see the difference.

**Comment by DevinWalker** [comment]
Good catch @mehul0810 - I've just confirmed and that's pretty annoying from the UX perspective.
