### ISSUE TITLE
Select All on Donations screen doesn't Select All, produces JS error

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2119]
## Issue Overview
Select All on Donations screen doesn't Select All, produces JS error

## Expected Behavior
You should be able to select all on this screen correctly.

## Current Behavior
Instead, clicking the Select All checkbox produces a JS error:
`Uncaught TypeError: Cannot read property 'indexOf' of undefined
http://giveplugin.dev/wp-content/plugins/give/assets/js/admin/admin-scripts.js?ver=1.8.13 line 1882`

As reported here:
https://wordpress.org/support/topic/javascript-error-in-admin/

**Comment by DevinWalker** [comment]
This has already been addressed in the `release/1.8.14` branch.
