### ISSUE TITLE
Custom Amount label in PayPal Standard is wrong

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#212]
See issue here: https://wordpress.org/support/topic/custom-amount-on-multi-level-donation-form-issue-with-paypal-description?replies=2#post-7340381

I tested locally and was able to reproduce the problem as well. Most likely just need some conditional logic to apply a default "Custom Amount" language when a Custom Amount is entered.

**Comment by DevinWalker** [comment]
@mathetos can you test with the latest master? Should be fixed now. I just test in both "Donation" and "Standard" modes:

![8-31-2015 7-29-16 pm](https://cloud.githubusercontent.com/assets/1571635/9594920/bcbc5250-5016-11e5-856b-55333999d9d5.png)
![8-31-2015 7-29-33 pm](https://cloud.githubusercontent.com/assets/1571635/9594918/bcb95dfc-5016-11e5-8856-535e2334b946.png)
![8-31-2015 7-30-02 pm](https://cloud.githubusercontent.com/assets/1571635/9594919/bcbb4da6-5016-11e5-8362-25838d773951.png)

**Comment by DevinWalker** [comment]
Plz reopen if able to reproduce issue

**Comment by DevinWalker** [comment]
I misunderstood this issue. Reopening

**Comment by DevinWalker** [comment]
OK just took another look at this and fixed the issue with custom amounts
