### ISSUE TITLE
Importer: After import - sort/insert multi-level amounts within donation forms

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2123]
## Issue Overview
**Problem 1:** Newly created donation forms - I noticed that when the importer creates multi-level donation forms the levels are not sorted by amount by default. Most of the donation forms I have seen users creating are sorted by least expensive level to most expensive. We should follow suit for newly created donation multi-level forms.

**Problem 2:** Already existing donation forms - If a level does not exists but is assigned within an import it is inserted at the end of the list. Often times the amount may be less than the final amount. We should insert them within into the appropriate order. For instance, if a form has $5, $10, $20 and I import a donation with level at $15 it's now the in the third position rather than last.

## Expected Behavior
Imported multi-level amounts are adding in a logical order.

## Current Behavior
They are often out of order.

## Related Issues and/or PRs
#1966

**Comment by mathetos** [comment]
Regarding **Problem 1** you probably want to ensure that the first level is set as the default as well. I could see an instance where no default was set for multi-level forms.
