### ISSUE TITLE
Allow thousands separator to be empty

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#213]
Apparently Canadians don't use a thousands separator at all. Currently if you remove the thousands separator it defaults to a comma. We need to remove that.

**Comment by DevinWalker** [comment]
Off the top of my head this would require removing the default value for:

https://github.com/WordImpress/Give/blob/master/includes/admin/register-settings.php#L248 and https://github.com/WordImpress/Give/blob/master/includes/admin/register-settings.php#L255

But we have to be sure that upon fresh install we have this field set here: https://github.com/WordImpress/Give/blob/master/includes/install.php#L100

There are other places too where the formatting takes place which need to be thoroughly tested:
https://github.com/WordImpress/Give/blob/master/includes/formatting.php

This function will also work:

```

/**
 * My custom Currency Format
 * 
 * @description Customize the currency format, pragmatically - CUSTOMIZE THE FUNCTION NAME
 * @param $formatted
 * @param $amount
 * @param $decimals
 * @param $decimal_sep
 * @param $thousands_sep
 *
 * @return string
 */
function my_give_custom_currency_format( $formatted, $amount, $decimals, $decimal_sep, $thousands_sep ) {

	$decimals      = 0;
	$thousands_sep = '';
	$formatted     = number_format( $amount, $decimals, $decimal_sep, $thousands_sep );

	return $formatted;

}

add_filter( 'give_format_amount', 'my_give_custom_currency_format', 10, 5 );
```
Quick fix: Add a documentation article with the above function

Better fix: Add an checkbox option to trigger the above functionality within the plugin's settings

"Remove thousands separator and decimals?" - if checked the "Thousands Separator" and "Decimal Separator" fields are hidden

**Comment by mathetos** [comment]
I don't think we need to hide the Decimal separate though. For the long-run, might be better to do the harder task rather than simply enable that function.

**Comment by DevinWalker** [comment]
You can tweak the function above to allow decimals. I think some admins may want no decimals.

**Comment by DevinWalker** [comment]
I'd rather keep this within a snippet. I don't think *all* "Canadians don't use a thousands separator at all". See: https://en.wikipedia.org/wiki/Decimal_mark - specifically "Canada"

I think the snippet will suffice. We need to add this to docs. EDD/Woo allows the field to be blank but still fallback to either "," or "."

**Comment by DevinWalker** [comment]
Clearing milestone and assigning to @mathetos to update Give's docs with snippet provided.

**Comment by mathetos** [comment]
Done!

https://givewp.com/documentation/developers/custom-currency-formatting/
