### ISSUE TITLE
Give Importer: Do not import option is shown twice in dropdown

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2134]
## Issue Overview
I have noticed that there is an option `Do not import` which is shown twice in the dropdown selection on `Step 2: Column Mapping` of importer.

![image](https://user-images.githubusercontent.com/1852711/30894733-20a8efd4-a363-11e7-9dd4-4592ba2d2366.png)

## Expected Behavior
`Do not import` should be displayed once in each dropdown.

## Current Behavior
Currently, `Do not import` is shown twice in each dropdown.

## Possible Solution
Removing `Do not import` under optgroup `Donation` would make sense.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Good catch 👍

**Comment by ravinderk** [comment]
Resolve in https://github.com/WordImpress/Give/commit/ddc381f88ada0d8fb2059083517a121c31961714

<img width="689" alt="screen shot 2017-09-27 at 3 57 21 pm" src="https://user-images.githubusercontent.com/1784821/30908867-9d0fac0a-a39c-11e7-9249-770693c05d60.png">

**Comment by raftaar1191** [comment]
@ravinderk 

Does it merge in the respected branch?

**Comment by ravinderk** [comment]
@raftaar1191 Yes. You can check commit link as weel

**Comment by raftaar1191** [comment]
Ya got it, Thanks @ravinderk
