### ISSUE TITLE
Settings Tabs needs UI/UX improvement for smaller devices

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2139]
## Issue Overview
With Resolutions below 600px, it is showing in a bit odd way which needs to be improved as a part of UX perspective.

## Expected Behavior
It should look something like this:
![image](https://user-images.githubusercontent.com/1852711/30906650-23191478-a396-11e7-8e65-71f3c68d68a9.png)

## Current Behavior
Currently, This is how it looks like:
![image](https://user-images.githubusercontent.com/1852711/30906541-c6d67642-a395-11e7-8cca-99725fdbd650.png)

## Possible Solution
Minor change in CSS.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
Resolve in https://github.com/WordImpress/Give/commit/b824b2e6fe88eee43ada3662ed767d2e804691a1

**Comment by ravinderk** [comment]
Close by mistake

**Comment by DevinWalker** [comment]
Also seeing issues on _Tools > System Report_ tab and other tabs:

**The dropdown doesn't display at all**
![2017-09-29_10-39-07](https://user-images.githubusercontent.com/1571635/31028477-fcc3f2de-a502-11e7-85d9-daf5dbf1ea93.png)

**Bottom line missing and no white background**
![2017-09-29_10-39-41](https://user-images.githubusercontent.com/1571635/31028480-ff01fdfc-a502-11e7-8cc3-e687b39704fd.png)

**Flash of content that is bad UX on page load**
![2017-09-29_10-43-58](https://user-images.githubusercontent.com/1571635/31028522-2a516560-a503-11e7-92cb-9ffeebd242de.gif)

**Comment by mathetos** [comment]
This is really sweet. Great work team!
