### ISSUE TITLE
Prevent download "System Info" window flash when loading tools 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2141]
## Issue Overview
When you're loading the tools screen the noticed jumps placement and it's bad a UX:

![2017-09-27_12-07-45](https://user-images.githubusercontent.com/1571635/30932548-a9c8db26-a37c-11e7-910a-c60e78574987.gif)

I also don't really like the use of a notice for it. It think it should look more like this:

![2017-09-27_12-11-24](https://user-images.githubusercontent.com/1571635/30932753-4a8ef504-a37d-11e7-95b5-9e9157af3c42.png)

Or:

![2017-09-27_12-13-04](https://user-images.githubusercontent.com/1571635/30932758-4d8779d4-a37d-11e7-90a0-dbd3c42bca21.png)

## Expected Behavior
The page loads smoothly

## Possible Solution
Move the notice below the tabs and prevent it from jumping

**Comment by mathetos** [comment]
Agree. I like the version without the white box better in this case.
