### ISSUE TITLE
Notices not showing in setting page

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2142]
## Issue Overview
Before it used to show the notices when the Success Page and Failed Donation Page is set to same page
![image](https://user-images.githubusercontent.com/22215595/30940580-241a644e-a3ff-11e7-8698-c912997bca7e.png)

## Expected Behavior
It should show notices that we can't set the Success Page and Failed Donation Page same

## Current Behavior
No notices come up

## Possible Solution
Alert message to Notices

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@raftaar1191 https://github.com/wordimpress/Give/commit/2c3997e642ffe61d6513a3c8a0d3dce4cd14504d commit cause of this bug

**Comment by raftaar1191** [comment]
@ravinderk 
The Above commit was for issues: https://github.com/WordImpress/Give/issues/2047

Fixing that
