### ISSUE TITLE
Reports: Headings and Text Modifications

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2144]
## Issue Overview
I have noticed that Reports page is having heading twice on each tab and there is no heading mentioning clearly that user is on Reports page unless user checks the sidebar or the contents of the page.

Even you can notice that the term of each tab like Income, Forms or Donation Methods comes thrice which is not good. 

## Expected Behavior
The change as per the below image will be more useful in case of user having the sidebar in collapsed mode or user accessing admin via smaller devices.

![image](https://user-images.githubusercontent.com/1852711/30948614-c3fbeab2-a42e-11e7-98a3-6937b9fa7ada.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/1852711/30948560-6618e986-a42e-11e7-9949-8f0b0fff8178.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by raftaar1191** [comment]
@mehul0810  @ravinderk 
I think we should also do this in the setting and tools pages as well


Setting: ![image](https://user-images.githubusercontent.com/22215595/31001138-2649c8d0-a4ff-11e7-882b-d24ccb9b8b69.png)

Tools: ![image](https://user-images.githubusercontent.com/22215595/31001153-4276d778-a4ff-11e7-8c8c-a5de2372eea6.png)

**Comment by DevinWalker** [comment]
Yes I agree @raftaar1191 - If setting pages were more like:

_If I'm on the currency options sub tab under settings the main heading will say_ 
"Settings - General - Currency"

**Comment by mathetos** [comment]
Totally agree. Good catch @raftaar1191

**Comment by DevinWalker** [comment]
@raftaar1191 I've reviewed and added comments on PR #2201 - I've added this as P1 for you on your board. This should be a quick fix pending my multiple depths question.

**Comment by mathetos** [comment]
This is a really nice improvement overall. Thanks!
