### ISSUE TITLE
API Enhancement: Populate Custom Meta Fields for Forms & Donations Endpoints

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#215]
Right now when a user creates a custom form field using this article: https://givewp.com/documentation/developers/how-to-create-custom-form-fields/

They are adding custom meta content to the `give_payments` CPT and often they want that content available in the API. For instance, imagine a form with a custom "Number of Guests" number field. Donors complete the donation and fill out that info where it's stored in payment meta. They then want to use Zapier to feed that content into another app. Right now that data isn't made available dynamically. 

@mathetos says Gravity Forms provides a dynamic API in this way. @pippinsplugins is there any reason why EDD/Give doesn't?

**Comment by pippinsplugins** [comment]
No reason aside from it hasn't been built in EDD.

**Comment by DevinWalker** [comment]
@pippinsplugins I can submit a PR if you're interested...

**Comment by pippinsplugins** [comment]
Certainly interested!

**Comment by DevinWalker** [comment]
This was released in 1.2.1
