### ISSUE TITLE
PDF of Donations and Income reports not support for various currencies

### ISSUE THREAD

**Issue by jaydeeprami** [WordImpress/Give#2152]
## Issue Overview

When we Download a PDF of Donations and Income reports for the various currency then it's not output properly.

## Expected Behavior
- It should display currency properly for all currencies.

## Current Behavior
- Currently, It does not display output for few currencies like below:
-  INR (Indian Rupee)
- Pound etc.

## Issue Screenshot
1. When INR Currency: 

![inr](https://user-images.githubusercontent.com/15060983/31013686-dc2d27e8-a534-11e7-9b1c-ae65bb5e95d8.png)

2. When Pounds Sterling (£),

![screenshot--2017-09-29-16-39-36-603](https://user-images.githubusercontent.com/15060983/31013723-0045c7f2-a535-11e7-8011-3755a5a2a952.png)

## Possible Solution
- We are using FPDF for generating PDF and used 'Helvetica' font. so that font not supported.
- For solution used 'dejavusans' font to support all currencies.
- For  'Iranian Rial', use 'CODE2000' font to support it.

## Steps to Reproduce (for bugs)

1. Go to Tools > Export > Click on Generate PDF (When Currency selected as USD it's work)
2. Go to Tools > Export > Click on Generate PDF (When Currency selected as INR it's not work)
3. Go to Tools > Export > Click on Generate PDF (When Currency selected as £ it does not display proper currency output)

@ravinderk, Do you want me to fix it and send PR?

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by jaydeeprami** [comment]
@DevinWalker, I have tried all the possible solution to achieve it but it does not work because of encoding not work for the font in FPDF.

I have tried all the below encoding to work currency proper:
http://www.fpdf.org/en/tutorial/tuto7.htm

I have also tried 'Dejavusans' with different encoding method by below link and load that font but it also not works:

http://www.fpdf.org/makefont/

I think We need to use different PDF library like TCPDF for the same. Please let me know your thoughts for the same.

Thanks,

**Comment by DevinWalker** [comment]
@jaydeeprami yes that may be the best option as of right now. Let's move forward with removing fpdf and implementing tcpdf in core. Then we can move on and use the core library within PDF Receipts and Tributes, etc.

**Comment by jaydeeprami** [comment]
Thanks @DevinWalker, I will move forward with implement TCPDF in the core.

**Comment by DevinWalker** [comment]
Useful issues that describes which fonts work for which languages: https://github.com/piwik/piwik-package/issues/33

This issue isn't yet resolve but I'm closing this due to the need to revamp this report in the future.
