### ISSUE TITLE
Save currency settings to payment for better currency formatting

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2153]
## Issue Overview

Currency formatting does not depend only on currency symbol. Number of decimal precision, Currency position, and number separators also affect currency formatting. So, I am suggesting store currency settings to donation. We help us to show better formatted number to admin or donor. 

For example:
I create a donation with `INR`.  See donation on history page:

Wrong formatting:
<img width="737" alt="screen shot 2017-09-29 at 7 27 46 pm" src="https://user-images.githubusercontent.com/1784821/31019253-ae30eb32-a54c-11e7-8ce5-b412ec1b11e0.png">
<img width="650" alt="screen shot 2017-09-29 at 7 27 52 pm" src="https://user-images.githubusercontent.com/1784821/31019252-ae305b04-a54c-11e7-93ef-5ae6df1a0d36.png">

Correct formatting
<img width="740" alt="screen shot 2017-09-29 at 7 28 23 pm" src="https://user-images.githubusercontent.com/1784821/31019251-ae2cf91e-a54c-11e7-9bdc-ad70950b35fc.png">
<img width="699" alt="screen shot 2017-09-29 at 7 28 35 pm" src="https://user-images.githubusercontent.com/1784821/31019254-ae3824d8-a54c-11e7-9b66-9b971e5ebb49.png">

## Expected Behavior

A donation amount should format correctly in any environment.

## Current Behavior

Donation amount is not formatting properly. It changes when currency or setting changes.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
I agree @ravinderk - this is especially important for the Currency Switcher add-on which is going to be releasing soon.

**Comment by ravinderk** [comment]
@DevinWalker Today I discussed challenge @emgk is facing while developing addon and I found that we have to make some changing to the core to support the dynamic currency https://github.com/WordImpress/Give/issues/2183.

@mehul0810 created pr for this issue but we still need to resolve another issue.
Can we bump up th8s issue to `1.8.15`?

**Comment by ravinderk** [comment]
@DevinWalker I am closing this issue because it is already completed.
For Ref: https://github.com/WordImpress/Give/issues/2197
