### ISSUE TITLE
Add ability to specify certain rows output by the [donation_history] shortcode

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#2156]
## Issue Overview
Users should be able to control `[donation_history]` similarly to `[give_receipt]` and specify which rows display.

## Expected Behavior
`[donation_history payment_method="false" payment_id="true"]` should do something. 
## Current Behavior
You can't pass any parameters to that shortcode, thus you can't hide any output. 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by mehul0810** [comment]
@DevinWalker @ravinderk Currently, There are 4 columns generated using `donation_history` shortcode as below:
- ID
- Date
- Amount
- Details

Also, we can add `Payment Method` as a column.

Now, what are the column to be made hidden and shown as per the parameter passed with shortcode?
My thought is to provide shortcode parameter for `Date` and `Payment Method`. Let me know your thoughts.

**Comment by ravinderk** [comment]
@DevinWalker Closing this issue, since it is already completed
