### ISSUE TITLE
Importer: "Postal Code" should auto-map to "Zip"

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2164]
## Issue Overview
It is universally understood that "Postal Code" is another term for "Zip". We should auto-map that.

## Expected Behavior
That "Postal Code" is auto-mapped to "Zip"

## Current Behavior
It currently isn't:
![image](https://user-images.githubusercontent.com/930724/31191661-b8796236-a8f3-11e7-8f10-c805c62d3fd9.png)

**Comment by BhargavBhandari90** [comment]
@mathetos 
Which csv do we need to import for this? Can you share file or something.

**Comment by mathetos** [comment]
@BhargavBhandari90 -- I'd suggest taking any CSV you have available, then change the header from "Zip" to "Postal Code" and test with that.

**Comment by DevinWalker** [comment]
@BhargavBhandari90 you can check out https://docs.google.com/spreadsheets/d/1ighe7VM6f8oVACjPlL12qB8LdKoneIgo4fEyYxeUOt8/edit?usp=sharing as well - it's an example import file

**Comment by BhargavBhandari90** [comment]
I saw this task is assigned to @raftaar1191. Should I continue on this?

**Comment by ravinderk** [comment]
@BhargavBhandari90 You can continue 👍

**Comment by ravinderk** [comment]
The solution provided by @BhargavBhandari90 was not flexible. As per discuss with @DevinWalker and @raftaar1191 we can improve this.

Image provided by @raftaar1191

![pasted image at 2017_10_17 11_45 am](https://user-images.githubusercontent.com/1784821/31650508-4144297a-b335-11e7-9541-2a3fcb1b883f.png)
