### ISSUE TITLE
fix(admin-tool): prevent duplicates if same date with different time

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2166]
## Issue Overview
Some platforms might put the time of the donation in a separate column from the date of the donation. If a donor donated multiple times in the same day to the same form, then those would be caught by our Importer as "duplicates" because we don't separate the time from the date.

See example here. These two highlighted donations would be flagged by our importer as duplicates, even though they are not.

![image](https://user-images.githubusercontent.com/930724/31192019-d86a6a12-a8f4-11e7-8ab5-53e0a8a7dbec.png)

**Comment by raftaar1191** [comment]
@mathetos we can pass the date and time on one cell.

See the latest sheet that has date and time in one column 

Google Sheet Link: https://docs.google.com/spreadsheets/d/1FZkxJDtvhAfUZYtL0HA2awfYvnuhOWbEcAK1egV0zxM/edit#gid=746278162


![image](https://user-images.githubusercontent.com/22215595/37337670-02eb3bea-26db-11e8-95a7-d9046a2c1335.png)

**Comment by raftaar1191** [comment]
Yes @mathetos @DevinWalker we can do that easily but I dont think separating the date and time in two diff cell is a good idea

Here is an example of this
Google Sheet Link: https://docs.google.com/spreadsheets/d/1-RB69kcxgsvXChhl_vRJHOMVOvo3NKnJLBj5Uw2LYa0/edit?usp=sharing

Updated Code for the above issues: https://github.com/raftaar1191/Give/tree/issues-2166


Video Link: https://screencast-o-matic.com/watch/cFeIXODrXa

**Comment by mathetos** [comment]
@raftaar1191 The goal of this issue is to ensure that donations that are made at different times of the same day don't get flagged as duplicates. Separating the time to a new cell might not be necessary, it was only a suggestion. As long as we can ensure that truly different donations that happened on the same day don't get flagged as duplicates; then this issue is resolved.

**Comment by raftaar1191** [comment]
As discussed with @ravinder over call creating new issues for the above [comment](https://github.com/WordImpress/Give/issues/2166#issuecomment-372900511) made by @mathetos

**Comment by raftaar1191** [comment]
@mathetos I have test issues properly and after merging the [PR ](https://github.com/WordImpress/Give/pull/2917) it working absolutely fine.

Can you please test this issues and closed if it's working fine 

I have created a new google sheet to check for the above mention issues 

Google Sheet Link: https://docs.google.com/spreadsheets/d/18AFqxipUgvkeDJ0uozzRCgJqKxH0WffVR7CzaUFpDmA/edit#gid=0

**Comment by kevinwhoffman** [comment]
I've assigned @ravinderk as Lead Developer to review the PR and confirm it's working as expected with the sample data sheet above. Ravinder, please work this into your sprint as you see fit.

**Comment by DevinWalker** [comment]
I reviewed the PR and it's working.
