### ISSUE TITLE
Make default Credit Card field one line, ala Stripe

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2167]
## Issue Overview
Look at this beautiful one-liner for a Credit Card field:
![image](https://user-images.githubusercontent.com/930724/31197617-887f9a60-a906-11e7-82e2-3226dbfdf273.png)

Would love this to be the default for all Give payment gateways that do credit cards.

**Comment by DevinWalker** [comment]
I don't think we're going to stray away from the traditional credit card field separation anytime soon. Maybe this will be an option once we refactor how Give forms are built but not before that. However, this option will be available in Stripe soon 👍
