### ISSUE TITLE
Modal loads ALL form data

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#217]
Currently, the Modal pop-up just loads the whole form. It would be better for it to load fields more strategically. This is particularly relevant when you create custom fields manually, and I'm sure it will impact the Form Field Manager as well.

@ibndawood Can you make sure to test Form Field Manager with the modal as well. Perhaps you'll have some insight on how we can load the fields in the modal more dynamically or conditionally.

**Comment by DevinWalker** [comment]
@mathetos please checkout branch issue/217 to verify fixed and I'll merge

**Comment by DevinWalker** [comment]
Merged
