### ISSUE TITLE
Fix currency code for "Iranian rial"

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2175]
## Issue Overview

The Currency code for  "Iranian Rial" is in code `RIAL` instead of `IRR `.
https://github.com/WordImpress/Give/blob/9fc6c7c583a7713914fd823935cab149a5e08c40/includes/misc-functions.php#L97

For Ref:
https://github.com/woocommerce/woocommerce/blob/fcb7da5599f85df37e423e8195810f1e81bbae83/includes/wc-core-functions.php#L360

https://en.wikipedia.org/wiki/Iranian_rial

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
We can not replace `RIAL` immediately with `IRR` because currency code attaches to many logic. In some case, we store it in the database also.

**Comment by raftaar1191** [comment]
Small issues need to fixed this as well 
http://screencast-o-matic.com/watch/cbliln2Cr4


I Have also check with **Euro** it's working fine for it

**Comment by ravinderk** [comment]
Opened by mistake, I will reopen this when @raftaar1191 will reconfirm issue.
