### ISSUE TITLE
Price formatting issue  with Iranian rial on multi type forms on form listing page

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2177]
## Issue Overview

<img width="1103" alt="screen shot 2017-10-10 at 8 32 18 pm" src="https://user-images.githubusercontent.com/1784821/31393801-31e58478-adfa-11e7-9834-a32915235f62.png">

Currency settings

<img width="608" alt="screen shot 2017-10-10 at 8 32 56 pm" src="https://user-images.githubusercontent.com/1784821/31393823-420c32c0-adfa-11e7-9148-f6d5e932ff4c.png">

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@raftaar1191 This will resolve problem

![image](https://user-images.githubusercontent.com/1784821/31395875-7954b644-adff-11e7-87c2-30eb6f5e94fa.png)

**Comment by jaydeeprami** [comment]
I got same issue with 'Moroccan Dirham (.د.م)' currency as well with same setting.

![screenshot-givewpcontribution dev-2017-10-11-00-18-01-981](https://user-images.githubusercontent.com/15060983/31404531-ecf5e16c-ae19-11e7-950b-f1b6a0bf4675.png)

**Comment by ravinderk** [comment]
This has been fixed.

Latest screenshots

<img width="1080" alt="screen shot 2017-10-11 at 9 45 17 am" src="https://user-images.githubusercontent.com/1784821/31422095-3c6b0f98-ae69-11e7-8c82-fb2b95ee0f5b.png">
<img width="1093" alt="screen shot 2017-10-11 at 9 45 41 am" src="https://user-images.githubusercontent.com/1784821/31422096-3cc680c6-ae69-11e7-8082-bdb350918183.png">
