### ISSUE TITLE
Session Issues with Pantheon and Possibly PHP 5.6+

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#218]
Debug session issues on Pantheon and PHP 5.6+ reported issues.

**Comment by DevinWalker** [comment]
Related: https://wordpress.org/support/topic/donation-confirmation-page-error-message?replies=6#post-7321161

**Comment by DevinWalker** [comment]
Related: https://wordpress.org/support/topic/problem-identifying-donation-error-on-all-donation-form-submits/page/2?replies=36#post-7370061

**Comment by DevinWalker** [comment]
Note: I've been working with Pantheon and have helped uncovered an issue within their Sessions plugin. Patch will be out soon for that from them.

I'm testing PHP 5.6 here now

**Comment by evok3d** [comment]
Has anyone been able to resolve this issue? I am having the same problem and really dont want to have a static address for people to donate to.

**Comment by DevinWalker** [comment]
@evok3d yes. It's been resolved. They have a PR in waiting here: https://github.com/pantheon-systems/wp-native-php-sessions/pull/17

They are looking for testers... perhaps you could help them out? I've tested and it's working on my end. I think they're just looking for more confirmation prior to rolling out the new version.

**Comment by DevinWalker** [comment]
Once https://github.com/pantheon-systems/wp-native-php-sessions/pull/17 is merged and released I'll close out this issue.

**Comment by DevinWalker** [comment]
Closing this one out since the ball is in their court to push to wp.org now
