### ISSUE TITLE
Donation form section title should be in proper alignment.

### ISSUE THREAD

**Issue by emgk** [WordImpress/Give#2187]
## Issue Overview
Fieldset legend has unnecessary padding, It breaks the layout ( see screenshot )

![screenshot-givecurrencyswitch dev-2017-10-12-11-25-12-259](https://user-images.githubusercontent.com/14994452/31481264-2161a0b8-af40-11e7-8617-0a0a072b2252.png)

## Expected Behavior
'legend' should be in proper alignment.

## Current Behavior
Section title does not look in proper alignments.

## Possible Solution
In https://github.com/WordImpress/Give/blob/89e8b3046f8356571a7e2eca886a5a78db6d5f96/assets/scss/frontend/forms.scss#L174 change this line to `padding: 5px 0;` but it still needs some testing.

## Steps to Reproduce (for bugs)
- Open any donation form in the front end.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@emgk did you face this issue with all default WordPress theme?

**Comment by emgk** [comment]
Yes @ravinderk, I was facing this issue in all of the default themes came with latest WordPress.

**Comment by raftaar1191** [comment]
@emgk 

I had details look into the issues but not able to generated the issues 

[Version 1.8.13](https://github.com/WordImpress/Give/) -> Not Issues
[Version 1.8.14](https://github.com/WordImpress/Give/tree/release/1.8.14) -> Not Issues
[Version 1.8.15](https://github.com/WordImpress/Give/tree/release/1.8.15) -> Not Issues

Have tried with two themes `Twenty Seventeen` and `Twenty Sixteen`


Can you send the Give Version and the themes in which you are testing and also the plugin list that is being activated in your sites 

1>WordPress Version
2> Give PLugin Version
3> List of all the plugin that is activated in the sites
4> Themes Name and it's version too

**Comment by emgk** [comment]
Hi @raftaar1191 It works fine in 1.8.13 but then I move to the 1.8.14 branch this issue occurs.

WordPress: 4.8.2
Give: 1.8.14 ( git )
Plugins: No other plugin active except Give.
Theme: Twenty Seventeen 1.3

PS: try to disable or enable `SCRIPT_DEBUG` or it may be caching issue.

**Comment by raftaar1191** [comment]
Thanks for your reply @emgk Checking

**Comment by raftaar1191** [comment]
Thanks, @emgk, 
Yup Was able to regenerate the issues.
Fixing it.

Version 1.8.13
![image](https://user-images.githubusercontent.com/22215595/31485952-5624a576-af53-11e7-8797-79d1ab000b6f.png)



Version 1.8.14
![image](https://user-images.githubusercontent.com/22215595/31485964-641c5f16-af53-11e7-8e4d-f80496ae6ca6.png)
