### ISSUE TITLE
Not able to upload CSV in Multi-Sites for importing the donations

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2188]
## Issue Overview
Not able to upload the CSV in Give > Tools > Import > Donation Import 

See the GIF: http://recordit.co/Hnsk6uLASr

## Expected Behavior
Should be able to upload the CSV in WordPress Media

## Current Behavior
Permission Error 

## Possible Solution
Add some Filter and allow some files type to be upload 

## Steps to Reproduce (for bugs)
1. Setup Multi-Sites
2. Try to add CSV from Give > Tools > Import > Donation Import

**Comment by raftaar1191** [comment]
Here is the Setting in which the SUper admin set the allow upload type file extensions 
![image](https://user-images.githubusercontent.com/22215595/31490136-941493d4-af60-11e7-881e-1cac084ea836.png)

**Comment by DevinWalker** [comment]
Good catch @raftaar1191 - is this something on our end or rather simply a setting the super admin needs to set to allow the `.csv` extension?

**Comment by raftaar1191** [comment]
There is a setting where super User need to Add CSV and TSV file type
