### ISSUE TITLE
give_profile_editor shortcode styling issue 

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2190]
## Issue Overview

![image](https://user-images.githubusercontent.com/22215595/31496430-e66dda6a-af78-11e7-9a63-030b687d0d81.png)

Give Version: 1.8.14 
https://github.com/WordImpress/Give/tree/release/1.8.14

## Expected Behavior
Border All over the Box Should not ger break

## Current Behavior
Top Border is getting Break

## Possible Solution
CSS FIXED

## Steps to Reproduce (for bugs)
1. Create a Page and paste the [give_profile_editor] Shortcode 
2. See that page in the frontend 

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by kevinwhoffman** [comment]
Note that some of the front-end form styles are shared across donation forms and profile forms, so we make sure that fixing one does not negatively affect the other.

**Comment by raftaar1191** [comment]
Thanks @kevinwhoffman
