### ISSUE TITLE
Tools > Data: Confirmation Checkbox and Submit button needs to be in sync

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2195]
## Issue Overview
I've noticed that selecting `Delete Imported Donors and Payments` under `Tools > Data` then it asks user to confirm that `Are you sure you want to delete` using a checkbox. But, for the first user is asked for confirmation and then user is able to click submit for deletion as many times user wants.
Please refer the attached GIF.

![gif](http://g.recordit.co/Bb2MkZwppJ.gif)

**P.S:** while capturing GIF, there is no imported data so it is showing `No Data Found` everytime. However, there is no issue.

## Expected Behavior
User should be asked for confirmation each time user clicks on submit for deleting any sensitive data.

## Current Behavior
Currently, user is asked for confirmation for deleting sensitive data for the first time.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by BhargavBhandari90** [comment]
@mehul0810 I would say form should be reset after submit each time.
