### ISSUE TITLE
Export > Donation History: Margin and Spacing issue for progress bar

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2196]
## Issue Overview
I've noticed that there is not proper spacing with progress bar and the fields of the `Export Donation History` as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/1852711/31528314-2f96491c-aff0-11e7-8ea0-5eaf2b3c6fde.png)

## Expected Behavior
There should be proper spacing between progress bar and `Export Donation History` Fields

## Current Behavior
Currently, No Proper Spacing

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@mehul0810 We will update UI on this page.

**Comment by DevinWalker** [comment]
Closing, looks good to me now.
