### ISSUE TITLE
Duplicate Form ID when Same Form Multiple time

### ISSUE THREAD

**Issue by jaydeeprami** [WordImpress/Give#2200]
## Issue Overview

Currently, If we put the same form multiple time on a page or in a widget then it will create Duplicate Form ID issue.

## Expected Behavior

`ID` should be Unique when the same Form multiple times.

## Current Behavior

Currently, It shows same Form ID multiple times which cause the error in W3C validator.

![screenshot-validator w3 org-2017-10-13-13-07-34-811](https://user-images.githubusercontent.com/15060983/31535653-7d4cd224-b019-11e7-9038-95b750e77a7c.png)

## Possible Solution
Need suggestion.

## Steps to Reproduce (for bugs)

1. Create Donation Form
2. Use same Form shortcode multiple times on a single page.
3. Check in https://validator.w3.org/
4. It shows Duplicate ID Error.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
I'm guessing the best workaround is to append `give-form-145-1-wrap`, `give-form-145-2-wrap` to them to prevent this from happening.

**Comment by ravinderk** [comment]
@jaydeeprami We will refactoring donation form in `2.1` then we will take this in our consideration.

**Comment by mehul0810** [comment]
This issue is a duplicate for issue https://github.com/WordImpress/Give/issues/3139 and also the referenced issue is having more inputs. Hence, closing this issue for now.
