### ISSUE TITLE
Conflict with EDD when updating donor's meta using Give_Donor class instance.

### ISSUE THREAD

**Issue by emgk** [WordImpress/Give#2202]
## Issue Overview
When updating donor's metadata through below code,

```
$donor = new Give_Donor( $payment->customer_id );
$donor->update_meta( 'cs_currency', sanitize_text_field( $_POST['cs_currency'] ) );
```
either storing the meta value into the `wp_give_customermeta` table, it store the this data into the `wp_edd_customermeta` when the EDD plugin is activated.

## Expected Behavior
It should update Give's donor meta instead of EDD customer's data.

## Current Behavior
Currently, it's conflicting with EDD when updating the donor's meta using Give_Donor() class.

## Steps to Reproduce (for bugs)
1. Create an instance of `Give_Donor()` with using existing user id.
2. Try to update metadata of this user `$donor->update_meta( 'any_unique_key', 'value' );`
3. Search that `'any_unique_key'` word in whole phpmyadmin database.

## Additional details
Plugin: Easy Digital Downloads (2.8.6)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@emgk Donor tables already renamed https://github.com/WordImpress/Give/issues/1960 which will fix this issue in `2.0`.
