### ISSUE TITLE
PayPal Standard back button issue

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#221]
This is an edge-case but feasibly users could do this. The scenario is that the donor chooses a level and gets directed to the PayPal site. Then they change their minds about which level and hit the back button on the screen. If PayPal ISN'T the default payment gateway then even though the form shows that PayPal is selected, it will process the form with the default gateway instead. Here's how to reproduce:

1) Have Test Payment Gateway and PayPal Standard as your Gateways
2) Make Test Payment the default gateway
3) Do a donation with PayPal Standard selected
4) instead of completing the donation at PayPal.com hit the back button.
5) Choose a different level or amount and hit submit again
6) It will complete the donation with the Test Payment Gateway instead of PayPal, even though PayPal is selected in the form.

The only way around that is after hitting "back" you switch the Payment Gateway back and forth.

**Comment by DevinWalker** [comment]
@mathetos can you verify this is fixed in https://github.com/WordImpress/Give/tree/issue/221 and I'll merge to master?

**Comment by DevinWalker** [comment]
Sorry I was commenting on wrong issue. I meant to comments on https://github.com/WordImpress/Give/issues/217
