### ISSUE TITLE
UI issues in Export - Export Donation History

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2210]
## Issue Overview
Add padding and place drop-down in new line 

## Expected Behavior
![image](https://user-images.githubusercontent.com/22215595/31573329-19824468-b0d7-11e7-85b3-d9810bc3fa75.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/22215595/31573298-b4e987dc-b0d6-11e7-81e6-6f047806b7b4.png)

## Possible Solution
CSS fixed

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@raftaar1191 We will revamp export screen after `2.0` then we will take in our consideration.

**Comment by raftaar1191** [comment]
Okay @ravinderk
