### ISSUE TITLE
Update Copyright Year in all files every year 

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2216]
## Issue Overview
I've noticed that we have outdated year set in copyright for all files of the Give Core.
https://github.com/WordImpress/Give/blob/master/includes/class-notices.php#L7

@DevinWalker Is it necessary to update Copyright Year of the plugin? If Yes, we should create a new issue every year when we update Copyright Year in all files.

## Expected Behavior
Copyright year should reflect current year in all files.

## Current Behavior
Currently, Copyright year is `2016` in all files which is not reflecting the current year.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
It would be nice to have a gulp task that updated them all.

**Comment by DevinWalker** [comment]
See: https://www.npmjs.com/package/gulp-string-replace

**Comment by kevinwhoffman** [comment]
I think it is standard to maintain the original year of publication in OSS. Having researched this before and looking around at a lot of plugins on GitHub, I've not seen any that remove in the original copyright year in favor of the current year.

**Comment by DevinWalker** [comment]
Yeah I'm not too concern about it updating too.
