### ISSUE TITLE
Add additional .give-active-level class to multi-level buttons and radios field types

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#2217]
## Issue Overview
User was confused as to what class is used for active buttons because `.give-default-level` doesn't clearly communicate its purpose.

## Expected Behavior
Class names should accurately reflect their purpose. `.give-active-level` makes sense for styling both the default level and the currently active button.

## Current Behavior
When selecting level buttons in multi-level donation forms, the `.give-default-level` class is used to denote the active class, even though it's not necessarily the default.

## Possible Solution
Rename `.give-default-level` to `.give-active-level`.

## Steps to Reproduce (for bugs)
1. Open multi-level donation form.
2. Inspect buttons.
3. Watch the default class get passed around as buttons are clicked.

**Comment by mathetos** [comment]
Maybe there is backward-compatibility issues with a simple renaming. In that case, just adding `.give-active-level` as a new class name and toggling that instead of `.give-default-level` would avoid potential issues with addons that reference the levels at all.

**Comment by kevinwhoffman** [comment]
@mathetos Good point re: backwards compatibility. Assuming a user has customized the active button style, the only way to preserve it would be to continue to pass around the `.give-default-level` class. At that point it seems counterproductive to add a redundant class on top of it.  It may be best to just leave it as is.

**Comment by mathetos** [comment]
I think Recurring Donations might also look for that class name... I could be wrong, just seems like that might be often referred to in our Add-ons.

**Comment by kevinwhoffman** [comment]
Closing since changing this class could possibly break styling for existing users who have targeted `.give-default-level` in their custom styles. We'll improve class naming when we introduce the Forms API in a future release.
