### ISSUE TITLE
Network activating plugin in WP multisite results in "This plugin generated extra chars"

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2224]
## Issue Overview
Network activating the plugin causes this issue:
![2017-10-18_16-31-32](https://user-images.githubusercontent.com/1571635/31747470-e96e8f54-b421-11e7-8251-eb40a5410177.png)

## Expected Behavior

No unexpected error notice 

## Possible Solution

I believe this is the activation screen redirect causing this message. I suggest skipping the redirect and output if the plugin is network activated.

## Steps to Reproduce (for bugs)

1. Multisite install Give
2. Network activate

**Comment by mehul0810** [comment]
@DevinWalker I'm unable to reproduce the issue. I've checked with following scenario's:
- Existing MultiSite Instance and then Network activating Give Plugin (Ver. 1.8.15).
- New MultiSite Instance and then Network activating Give Plugin (Ver. 1.8.15).

Can you check and let me know whether the issue still persists at your end?

**Comment by DevinWalker** [comment]
Hmm, I just tested as well and was unable to reproduce in a new environment. Strange. Closing this one out.
