### ISSUE TITLE
Address Fieldset: "State/Province/County" should not go before "City"

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2226]
## Issue Overview
We need to rearrange the fields so that "State/Province/County" appears next to "Postal/Zip" and "City" takes it's place for improved UX and ease of filling out form:

![2017-10-19_14-11-59](https://user-images.githubusercontent.com/1571635/31794542-838244a4-b4d7-11e7-9ab6-43b8499bc680.png)

## Expected Behavior
Naturally completed an address field would have the fields in proper order.

## Current Behavior
State is before city, which is not normal UX.

## Possible Solution

Rearrange fields as described.

**Comment by raftaar1191** [comment]
@DevinWalker 
There is some country who does not have states init Like: Afghanistan
![image](https://user-images.githubusercontent.com/22215595/31839164-931358dc-b5fd-11e7-9235-c04fa862dbcc.png)


After I change the place of city to state and state to city and then select the country `Afghanistan`
![image](https://user-images.githubusercontent.com/22215595/31839259-f11942fc-b5fd-11e7-91bb-cd1ab4771402.png)


Will it be okay if it's appeared like this?

**Comment by DevinWalker** [comment]
@raftaar1191 yes that looks good that the field goes full width if there is no state for the country.

**Comment by raftaar1191** [comment]
@DevinWalker Thanks 
Will start working on this ASAP

**Comment by raftaar1191** [comment]
Related to issues: https://github.com/WordImpress/Give/issues/2037

**Comment by raftaar1191** [comment]
Related issues:
https://github.com/WordImpress/Give-Gift-Aid/issues/68
https://github.com/WordImpress/Give-Manual-Donations/issues/78
https://github.com/WordImpress/Give-Manual-Donations/issues/78
