### ISSUE TITLE
Give Importer: Error Message if Donor Email has not been submitted

### ISSUE THREAD

**Issue by johnpcarty** [WordImpress/Give#2227]
## Issue Overview
When importing donations and on the Column Mappings page, the submit button should give an error if a field has not been mapped to the Donor Email.

## Expected Behavior
There is a similar check for a Donation Form Title.  If the form can't be identified, the user can't proceed.  The same thing should happen with for the Donor Email.

## Current Behavior
The import proceeds, but nothing gets imported. 

## Steps to Reproduce (for bugs)
I ran an import using these mappings from one system into Give.
1. ReceiptNumber => Donation ID
2. SentBy => Donor ID
3. ReceiptDate => Donation Date
4. TotalAmount => Donation Amount
5. Description => Notes
6. FirstName => Donor First Name
7. LastName => Donor Last Name
8. FormName => Donation Form Title
But I forgot to map my user_email field to the Donor Email.

## Todos
- [ ] Update code

**Comment by DevinWalker** [comment]
Good catch. Thanks @johnpcarty - I've placed this on the next release.

**Comment by DevinWalker** [comment]
@johnpcarty we've reviewed this issue and had a discussion. We decided that at the time of mapping the columns one of the following two fields, `Donor Id` or `Donor Email Id`,  is required.

If both the fields are not mapped then an error displays:

![gzs2slb0t-yy90bjm_cmig](https://user-images.githubusercontent.com/1571635/32746440-79d1b4d4-c86a-11e7-816b-c57c80b856dc.png)
 
If any of the fields is present in the CSV column then no error message will display. 

If the `donor id` is mapped then the importer will fetch data from the Give donor table  by donor id to populate the donor fields. If donor email ID is mapped then it will attempt to fetch the donor data from the donor table by donor email id. If the donor is not found within the database, the importer will use the data provided from the CSV.

Please let me know if you have any questions regarding this or if we missed anything.
