### ISSUE TITLE
fix(form): exclude honeypot field from floating labels js

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2230]
## Issue Overview
The floating labels feature adds markup to the labels and inputs on our form. While I haven't been able to replicate this perfectly, I can see that floating labels makes changes to the honeypot markup when activated. I'd strongly suggest we somehow exempt the honeypot from the floating labels JS completely just to avoid potential false flags with the honeypot.

## Steps to Reproduce (for bugs)
1. Enable floating labels on a form
2. Check the markup, it should look something like this: 
![image](https://user-images.githubusercontent.com/930724/31919500-bef3e09a-b817-11e7-8218-0dd95cc753b8.png)
3. Disable floating labels on the same form
4. The markup should now look something like this: 
![image](https://user-images.githubusercontent.com/930724/31919514-db3b7024-b817-11e7-93de-07f068eddc9f.png)

It should look like the second screenshot regardless of the floating labels being enabled or not.

**Comment by mathetos** [comment]
It's also very awkward that floating labels ends up adding a `<div>` inside of a `<span>` -- that's not appropriate markup. It's probably more advisable that the honeypot element wrapper should itself be a div instead of a span.

**Comment by tw2113** [comment]
Should probably add `.give-honeypot` to this found in `assets/js/frontend/give.js`:

```
give_float_labels = new FloatLabels( '.float-labels-enabled', {
	exclude: '#give-amount, .give-select-level, [multiple]',
	prioritize: 'placeholder',
	prefix: 'give-fl-',
	style: 'give',
} );
```
