### ISSUE TITLE
[give_form] ShortCode should support Featured Image

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2231]
## Issue Overview
It seems that featured image of donation form is display as a part of CPT single page. But, not as a part of ShortCode.

![gif](http://g.recordit.co/LdlwrBtiha.gif)

## Expected Behavior
Featured Image of the donation form should be displayed in shortcode as well.

## Current Behavior
ShortCode doesn't display featured image.

## Possible Solution
Adding support of featured image to `give_get_donation_form` function.

## Steps to Reproduce (for bugs)
1. Install Give (Latest Version)
2. Create New Donation Form
3. Add Featured Image to Donation Form
4. Create New Page 
5. Add Newly Created Donation Form ShortCode to the Page
6. Open the Page in Front End.
7. You'll notice there is no featured image.

## Related Issues and/or PRs
https://github.com/WordImpress/Give/issues/1414

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
Hmm, we sometimes get this question about why the feature image isn't displaying within the shortcode. I've mostly just said that you can easily add the image _next_ to where you are embedding the shortcode or display it using the donation form content editor. 

The featured image seems better off remaining with the single post page template for now unless there's a great outline of how it could be used within the shortcode.
