### ISSUE TITLE
Add-on activation banners aren't displaying anymore

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2241]
## Issue Overview
When I activate an add-on on a fresh install it isn't appearing:

![2017-10-25_15-59-46](https://user-images.githubusercontent.com/1571635/32027392-a33d75c8-b99d-11e7-801e-9472be3cbde0.gif)

## Expected Behavior
Activation banners display

## Current Behavior
They are not displaying

## Steps to Reproduce (for bugs)

1. Fresh WP
2. Install Give
3. Install Add-on
4. Activate Add-on

**Comment by ravinderk** [comment]
Cause of this issue:https://github.com/WordImpress/Give/pull/2204 https://github.com/WordImpress/Give/pull/2211
