### ISSUE TITLE
CC fields incorrectly marking as invalid on page load

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2244]
## Issue Overview
I've seen this on multiple websites now:

![2017-10-26_00-17-13](https://user-images.githubusercontent.com/1571635/32039598-337343ee-b9e3-11e7-8b39-0cc4d1bd4467.png)

See: http://plf.org/give/give-form/
And HeroPress:  https://heropress.com/give/form/

## Expected Behavior
CC fields should not be highlighted if not completed incorrectly

## Current Behavior
On page load CC fields are highlight causing distraction and confusion

## Possible Solution
Review payment gateway, and attempt to reproduce the issue with same setup.

## Steps to Reproduce (for bugs)
Unknown. - Attempt to reproduce the issue.

**Comment by mehul0810** [comment]
@DevinWalker @ravinderk I'm unable to reproduce this issue on local. However, Here are my findings.

## My Findings
1. Issue mentioned sites, on page load automatically adds `placeholder` and `error` class to the `input` of Card Number, CVC and Expiration which is not replicating on local.
2. Error is triggered with CSS on `forms.scss` file with `.give-do-validate input.error` which is only validation if the `error` class comes up. and on local `error` class comes up only if we focusout, change or keyup
3. Both the reference sites using different payment gateways (Authorise and Stripe) and different themes as well.
4. CC fields for form using Authorise is coming from Give Core. However, CC fields for form using Stripe is coming from Stripe Addon.
5. Both the reference sites are using Recurring Addon. However, I don't think Recurring Addon is a culprit. 
**Reason:** If recurring addon was culprit the the normal multi-level form shouldn't had the issue.
Multi-Level Form: http://plf.org/give/give-form/
Multi-Level Recurring Form: https://heropress.com/give/form/
Multi-Level Recurring Form: http://plf.org/give/give-monthly/

Let me know, if you need any further help.

**Comment by ravinderk** [comment]
@DevinWalker I found the cause of this issue. plf and heropress both sites is using `placeholder` polyfill which fire `blur` event immediately which cause an error in cc fields.

http://plf.org/wp-content/themes/plf/js/scripts.js
https://heropress.com/wp-content/plugins/postmatic-premium/vendor/prompt/prompt-core/js/subscribe-form.js?ver=2.0.14

**Solution**
We can add event to cc field after window load which will fix issue.

**Comment by raftaar1191** [comment]
@ravinderk that really nice
