### ISSUE TITLE
Issue with give_mark_abandoned_donations() not marking abandoned

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2251]
## Issue Overview
It appears `give_mark_abandoned_donations()` is not working as expected.

Reported here: https://wordpress.org/support/topic/pending-donations-not-being-abandoned/

## Expected Behavior
Payments older than 1 week get marked as abandoned.

## Current Behavior
They are not getting marked as abandoned

## Steps to Reproduce (for bugs)
1. Created some payments older than 1 week and set them to pending
2. Manually run `give_mark_abandoned_donations()`
3. Payments will not be marked as abandoned

**Comment by raftaar1191** [comment]
@DevinWalker 

I just had a look into this is working fine for me. I am adding a Donation where gateway was `Test Donations` and from the backend change the date of the donation and then run `give_mark_abandoned_donations` manually. It working fine for me 


I also test this issues with `Give - Manual Donations` Addon, by adding a donation then running `give_mark_abandoned_donations` manually it working fine for me in this case also 


@DevinWalker can you please have a look into this again as it's working fine for me

**Comment by DevinWalker** [comment]
Seems working on my end too upon testing again. Closing and we'll keep an eye out for issues.
