### ISSUE TITLE
Bug when attempting to view single donation history issue

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#226]
When clicking the link here:

![9-2-2015 1-01-02 pm](https://cloud.githubusercontent.com/assets/1571635/9642749/d9f48b6e-5172-11e5-9512-0145e30a9d26.png)

One is brought to the homepage with a link like so: `http://givedev.dev/?payment_key=14a99f0762921329445367a3cc4566b3`

![9-2-2015 1-01-24 pm](https://cloud.githubusercontent.com/assets/1571635/9642760/e46151d6-5172-11e5-8991-57ed5c560ab7.png)

... rather than being able to view the donation. Fix coming

**Comment by DevinWalker** [comment]
Looks like this only happens when the user hasn't properly set a "Success Page" for donations.

**Comment by mathetos** [comment]
That's a weird instance though. Why is the Use History page connected to the Success page at all?

**Comment by DevinWalker** [comment]
Because the single donation history information is output using the donation `[give_receipt]` shortcode.
