### ISSUE TITLE
Donation History Admin Page should follow default WP List Structure

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2265]
## Issue Overview
There should not be any separate column to manage `View` link for donations as per default WP List Structure.

![image](https://user-images.githubusercontent.com/1852711/32170114-54aa6646-bd99-11e7-9e3b-866507a578f0.png)

## Expected Behavior
`View` link for donations must be managed using row actions.

## Current Behavior
Currently, managed using separate column which consumes additional space of columns which doesn't make sense as a part of UX.

## Possible Solution
Remove Column and add `View` link using row actions

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by raftaar1191** [comment]
Nice catch @mehul0810

**Comment by DevinWalker** [comment]
I disagree that we should have to follow it 100% like WP does. I actually got this format from WooCommerce and I think it makes it more obvious that you can view the details more so than a hidden "view" link that reveals itself upon hover.
