### ISSUE TITLE
Question: Convert WP_List_Table to Give_List_Table to improve flexibility

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2266]
## Overview
I've noticed in the [Codex](https://codex.wordpress.org/Class_Reference/WP_List_Table) that every plugin developer should never use existing `WP_List_Table` function, rather we should use it by copying it in the plugin core and extending it as required.

Also, I've seen that the [Codex](https://codex.wordpress.org/Class_Reference/WP_List_Table) is having that message which defines that we need to use WP_List_Table by copying it in plugin core. However, I've not noticed it in [Developer Docs](https://developer.wordpress.org/reference/classes/wp_list_table/)

**Message written in Codex:**
This class's access is marked as private. That means it is not intended for use by plugin and theme developers as it is subject to change without warning in any future WordPress release. If you would still like to make use of the class, you should make a copy to use and distribute with your own project, or else use it at your own risk.

## Questions
1. Should we need to convert WP_List_Table to Give_List_Table?
2. I agree that converting it will help us improve extendability. Let me know your thoughts?

**Comment by DevinWalker** [comment]
Summary of conclusion from Slack convo:

I agree with the discussion had by @mehul0810 @ravinderk and @kevinwhoffman 

@ravinderk said:

> If we make our own class then we have to maintain it. All other plugin like EDD and Woo use this directly if something happen with this `class` then it will be big new in WordPress community and will be catch in beta release :smile:.

As @kevinwhoffman says:

> That warning was made in 2012 and it says no breaking changes have been made since then. I think we’re good.
