### ISSUE TITLE
Licensing for individual addons that were upgraded are reflecting their original subscriptions, not the upgraded ones

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2268]
## Issue Overview
Scenario:

1) Customer purchases an individual addon on September 1, 2016
2) Instead of renewing that, they let it expire, but then on October 1, 2017 they renew it and upgrade to a Bundle
3) Their license key for the individual addon doesn't change at all because it's an upgrade
4) But in Give settings, the license has an alert that says their license expired on September 1, 2017 because -- I'm assuming -- it's somehow looking for the original individual subscription, not the new updated Bundle subscription.

## Expected Behavior
The license alerts should always only reflect the current active subscription regardless of whether it was an upgrade or not.

## Current Behavior
Upgraded licenses aren't connected to their correct subscription.

**Comment by mathetos** [comment]
@DevinWalker I think this is related to the license activation issue we chatted about in Slack today. Any chance we can push this back to 1.8.17?

**Comment by DevinWalker** [comment]
This is the issue I resolved within 885a69cd6b0b130420a2cc29f49b8c5139a49c61 and within d46eaf4a6fd38f785954ad8026fe7423fedc2070
