### ISSUE TITLE
Wrong input type field

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2269]
## Issue Overview

<img width="895" alt="screen shot 2017-10-31 at 4 57 29 pm" src="https://user-images.githubusercontent.com/1784821/32221753-b1e2170a-be5c-11e7-919e-c4bec35c2192.png">

## Expected Behavior

Input type `text`.

## Current Behavior

Input type set to `tel`.

## Todos
- [x] Tests
- [x] Documentation

**Comment by ravinderk** [comment]
Summary of slack conversion

> `tel` is used so that it triggers the large number inputs on mobile.  You can get a similar result with `type="number" pattern="[0-9]*"` which is more semantically correct. https://www.filamentgroup.com/lab/type-number.html

> The one difference is that the number field shows the arrow spinners when you focus the input on the desktop.

> I think it’s fine to leave it as `tel`. Stripe uses it for all of their number fields. So does YouCaring. The reason it is used is that it triggers the large number inputs on mobile but it does not enforce any validation (since phone numbers can vary so widely). My vote is to leave it as `tel`.

Recommendation from Stripe: https://github.com/stripe/jquery.payment#mobile-recommendations

**Comment by DevinWalker** [comment]
@ravinderk did you close because this is a duplicate of #1310?

**Comment by ravinderk** [comment]
@DevinWalker No. On basis of @kevinwhoffman suggestion and research on the stripe, it is good to keep it as tel.
