### ISSUE TITLE
Add support for middle initial / name

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2277]
## Issue Overview
A request came it to add middle initial / name support to Give. This issue is open to discuss that addition.

WP.org ticket: https://wordpress.org/support/topic/add-middle-initial-name/

My first inclination is this should be a snippet. However, it's more complex than that because this needs to be attached to the donor meta and also specifically the donors full name thoughout Give core and it's add-ons.

--- 

### Questions and Considerations

1. Is this commonly supported for other donation and eCommerce platforms?
2. How common a request is this?
3. How this field be added to the form in a visually appealing way?
4. How do we differentiate between middle initial and name? Some may want just the initial while others the name.

**Comment by kevinwhoffman** [comment]
If we were to add it, I think it should be functionality added to the plugin, disabled by default. Considering the code to display the field on the front-end, style it, save it, and display it on the back-end, that seems like it would be a complex snippet.

**Comment by raftaar1191** [comment]
Yes @kevinwhoffman I agreed with your point it should be disabled by default

Code must be in Give Core, Not in a snipped

**Comment by DevinWalker** [comment]
I haven't heard the feature requested since so I'm closing this one out.
