### ISSUE TITLE
Create filter for plugins listing page to only list Give and its add-ons 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2278]
## Issue Overview
It would be useful to have a filter within the plugins listing page:

![2017-11-01_22-20-57](https://user-images.githubusercontent.com/1571635/32310975-4dae0b5c-bf53-11e7-851d-72ebdd8fcfb1.png)

See how Caldera has one:

![2017-11-01_22-22-54](https://user-images.githubusercontent.com/1571635/32310982-526e5b10-bf53-11e7-91ee-91611fdc761d.png)

**Comment by raftaar1191** [comment]
I really Like it @ravinderk @DevinWalker I was also thinking of this

**Comment by ravinderk** [comment]
@raftaar1191 This is not working addons enabled network wide. Can you fix it?
