### ISSUE TITLE
Multi-level should be the new default donation form type when adding new

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2281]
## Issue Overview
Most people prefer the multi-level donation form type. We should make this the default type rather than the set donation:

![2017-11-01_23-41-09](https://user-images.githubusercontent.com/1571635/32313075-2e38f218-bf5e-11e7-92b3-125205485d2d.png)

**Comment by raftaar1191** [comment]
@mehul0810 @DevinWalker 
This featured is getting break after the post is publish for the first time 

See the Video for more description of the issues that I am facing

Video Link: http://screencast-o-matic.com/watch/cbXj1m2XAT

**Comment by raftaar1191** [comment]
As discuss over the call with @mehul0810 this issues is not related to https://github.com/WordImpress/Give/issues/2281#issuecomment-342726313


This issue is being moved to https://github.com/WordImpress/Give/issues/1688

**Comment by Benunc** [comment]
I just now saw this issue, and I really disagree. I don't think most people want multilevel. But if they do, we should default to having multiple levels by default. 

The current implementation makes a new user at least two steps further from creating their first form. Before it was "name it, and save it" Now it's "name it, name the level, add a new level, name that level, and save it" Here's a video:

https://youtu.be/2CwRP0E_odw

**Comment by DevinWalker** [comment]
The majority of donation forms I see from customers are multi-level. We want to promote giving various donation options to your potential donors. 

The placeholder will not default to `0` since we resolved that in another issue. I'm open to discuss providing 3 default levels with pre-filled amounts ($10, $25, $50), but still the admin has to do _some_ work to get the plugin running.

In order to drink a coke you have to open the bottle. The same is true for our plugin. You need to do a minimal amount of work to get a powerful donation form setup. We can reduce the work, for instance by adding new default levels, but still the admin should review the basics at least.
