### ISSUE TITLE
Improve donor detail page heading

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2286]
## Issue Overview

We can show donor name on donor detail page instead of donor ID.

**Donor detail page:**
<img width="530" alt="screen shot 2017-11-03 at 1 50 37 pm" src="https://user-images.githubusercontent.com/1784821/32365034-18a95abe-c09e-11e7-8a06-06a032485ff6.png">

**WordPress user edit page**
<img width="594" alt="screen shot 2017-11-03 at 1 50 27 pm" src="https://user-images.githubusercontent.com/1784821/32365033-1837de20-c09e-11e7-82a9-e31a3ae7fc2d.png">

## Todos
- [ ] Development
- [ ] Review Heading

**Comment by ravinderk** [comment]
@DevinWalker @mathetos 

Slack conversion summary:

> ‘Edit Donor’ would follow suit with the rest of WP admin. Typically the title of the page reflects the action being taken. It doesn’t include specifics.

> I liked your suggestion @ravinder. I think that ID is of no importance for a user. But, change it to `Edit Donor: Mehul Gohil` will make a difference to a user. The user will immediately know that he is accessing the donor profile of so and so person and we all know that bigger heading will attract eyesight more easily.

So New heading will look like `Edit Donor: {firstname} {lastname}`.

**Comment by DevinWalker** [comment]
The ID is of some importance. I'd like to see it updated as:

`Edit Donor #123: {firstname} {lastname}`

**Comment by raftaar1191** [comment]
Okay @DevinWalker
