### ISSUE TITLE
Run flush_rewrite_rules after editing category/tag settings in display options

### ISSUE THREAD

**Issue by tw2113** [WordImpress/Give#2291]
## Issue Overview
Enabled category/tag support for give_forms post type, added one of each to a Give form, but frontend archives for each category/tag gave a 404 error

## Expected Behavior
Should ideally automatically take new taxonomies into account with fresh rewrite rules and displayed results.

## Current Behavior
User needs to visit the permalinks settings page to get rewrite rules regenerated to account for the new taxonomies.

## Possible Solution
When saving the settings, run `flush_rewrite_rules()` after successfully saving.

**Comment by raftaar1191** [comment]
@tw2113 
Thanks for reporting.

## Able to regenerate this issues:
**Step to Reproduct in New Sites**

1. Install & activate Give Plugin in new Sites 
2. Go to Dashboard > Donations > Settings > Display Options > Taxonomies and Enable `Form Categories` 
3. A new `Categories` Submenu will be added inside Donation Main Menu
4. Add new Categories and then link on link `View` the Categories

**Step to Reproduct in Old Sites**

1. Deactivate Give Plugin and there Add-on 
2. Go to Dashboard > Settings > Permalinks > and click on `Save Changes`
3. Activate Give Plugin and there Add-on  
4. Go to Dashboard > Donations > Settings > Display Options > Taxonomies and Enable `Form Categories` 
5. A new `Categories` Submenu will be added inside Donation Main Menu
6. Add new Categories and then link on link `View` the Categories

**Notes:** Give `Form Archives` page is also not displaying Page not Found unless reset permalink

**Comment by raftaar1191** [comment]
@ravinderk Need you help with this

**Comment by mehul0810** [comment]
I'm able to reproduce this issue. I've tested this with a new WP instance in which i've enabled and disabled `Categories` and `Tags` and created one test category and tag to check its URL in front end. The URL for test category and tag both goes 404.

**Comment by mehul0810** [comment]
As discussed over call with @ravinderk, this issue is working fine, got confusion due to donation form not assigned to a category or tag which showed a message `Nothing Found`
