### ISSUE TITLE
Text Change in Donations Tools Submenu

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2299]
## Issue Overview
Text Change in Dashboard > Donations > Tools > Data after selecting the value as `Recalculate Income Amount and Donation Counts for a Form` a new drop-down come up 

## Expected Behavior
![image](https://user-images.githubusercontent.com/22215595/32482624-89dd2328-c3be-11e7-9c15-7eaba60ee640.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/22215595/32482318-2974e648-c3bd-11e7-9cf4-74d3dbedbc5d.png)

## Related Issues and/or PRs
https://github.com/WordImpress/Give/issues/2235

## Todos
- [x] Tests
- [x] Documentation

**Comment by raftaar1191** [comment]
This Issues PR will be send from this branch https://github.com/raftaar1191/Give/tree/issues-2235

**Comment by ravinderk** [comment]
As per @DevinWalker comment, we are changing text to `Select Form`
For ref: https://github.com/WordImpress/Give/pull/2303#discussion_r150654993

**Comment by raftaar1191** [comment]
@ravinderk 

Can you please reopen this issues as can this commit that you add is not being solved yet completely 
https://github.com/WordImpress/Give/pull/2303#issuecomment-343127610

**Comment by ravinderk** [comment]
@raftaar1191 As discussion over the call, let's do not worry about this for now. If single form downdown menu is hiding after ajax complete then it is good.

Wait for @DevinWalker response here: https://github.com/WordImpress/Give/pull/2303/files#r150781867

**Comment by raftaar1191** [comment]
Sure @ravinderk
