### ISSUE TITLE
Data Tool: Reset the dropdown properly on Recalculate Income Amount and Donation Count for a form

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2301]
## Issue Overview
Dropdown for `Recalculating Income Amount and Donation Count for a form` is resetting without hiding the dropdown containing forms.

![gif](http://g.recordit.co/xgUvw755JZ.gif)

## Expected Behavior
Dropdown of `Donation Forms` should get hidden when the `Recalculate Income Amount and Donation Count for a form` completes successfully.

## Current Behavior
Currently, the donation forms dropdown doesn't gets hidden. However, the toll selection dropdown gets reset which make the Tool not usable.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by raftaar1191** [comment]
@mehul0810 @ravinderk 

This issue is being fixed in the following PR https://github.com/WordImpress/Give/pull/2303

Gif: http://recordit.co/o1aLuy2enR

**Comment by raftaar1191** [comment]
I am able to regenerate the issues http://screencast-o-matic.com/watch/cbliYH2CLn

@DevinWalker can you please open this issues

**Comment by DevinWalker** [comment]
@raftaar1191 please tag your new issue as related to this one so there's a cross reference.

**Comment by raftaar1191** [comment]
Creating a new issue for comment https://github.com/WordImpress/Give/issues/2301#issuecomment-350089925
issues link: https://github.com/WordImpress/Give/issues/2475

Thanks @DevinWalker for this out
