### ISSUE TITLE
Create WordPress environment section in Github issue and PR template

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2310]
## Issue Overview

Woocomerce has this in their issue template and the better part of this is it is close by default and we can collect more information about the issue.
For ref: https://github.com/woocommerce/woocommerce/blob/master/.github/ISSUE_TEMPLATE.md#wordpress-environment

## Expected Behavior

The issue must contain WordPress Environment information.

## Current Behavior

We do not have any section where the user can add WordPress Environment information.

**Comment by raftaar1191** [comment]
Issue relate to https://github.com/WordImpress/Give-Manual-Donations/issues/82

**Comment by raftaar1191** [comment]
Add/updating the issues and PR template of GitHub in add-on as well
