### ISSUE TITLE
Add helper function to get total donation amount of donor

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2315]
## Issue Overview

Ref: #2309

**Comment by DevinWalker** [comment]
We need to ensure that PR #2309 has backwards compatibility for the changed method name. I know add-ons like recurring use the old method name.

**Comment by ravinderk** [comment]
@DevinWalker FYI

@emgk Added a new function `get_total_donation_amount` and update this in Give core plugin but `$purchase_value` donor class property will work as intended.

Do you have any thought on this?

**Comment by DevinWalker** [comment]
I'm not sure I get what you're saying. Let's do a call later to discuss.

**Comment by DevinWalker** [comment]
After call with @ravinderk the new method `$donor->get_total_donation_amount()` will provide a useful filter rather than directly accessing the value itself.
