### ISSUE TITLE
Give PDF Receipt - Create an End Of Year Report with Donation Details

### ISSUE THREAD

**Issue by johnpcarty** [WordImpress/Give#2321]
## Issue Overview
I would think other non-profits are looking for an easy way to get an end of year report that include the details of each donation.

I've been helping a non-profit move from an old system to the Give plugin.  One thing they had in the old system was an ability to print an end of year donor letter that included all the donations the donor made for a given time frame.  

They asked for a work-around so they could do it in Give.  I created a mail merge using Word, an ODBC data source and some MySQL views.  I created two sets of views that they could have used in a mail merge.  One set of views creates the data for this year.  The other set creates the data for last year.  However, it is too complicated to get the data source setup.  They are not very technical.  I'm wondering if the donation details could be built into the Give PDF Receipt add-on.  

## Expected Behavior
I think an end of year report would work somewhat similarly to the individual donation report.  It should contain the donor name, address, list of donations, and totals.

They did want two options.  The first option is for the date range.  The second option is to create the pdf's for one donor or all donors.

## Current Behavior
Based on the web page for the PDF Receipts add-on, it looks like it can only generate a pdf for each individual donation.  

Another option mentioned on givewp.com is to use give and mailchimp.  Unfortunately, all of their donors don't have an email address.  Also, it does not look like the export includes the details of each donation.

## Possible Solution
One of the pieces to the puzzle is putting the donation list into one field.  This is how I did it when I created the mail merge.  The Group_Concat mysql function combines rows of strings together.  I use the concat function inside of it to combine the donation date, the tab character, and the payment total.  In the group_concat, I separate rows by two angle brackets.  The outside of the group_concat, I replace the angle brackets with a carriage return and line feed.

REPLACE(
GROUP_CONCAT(
CONCAT(DonationDate,' ',CAST(CHAR(9) AS CHAR),'$', FORMAT(give_payment_total,2)) 
ORDER BY DonationDate ASC SEPARATOR '<>')
,'<>',CAST(CHAR(13,10) AS CHAR)) AS DonationField

I'm pretty sure the client is alright with me providing the full set of views that I created for the mail merge.  Let me know if you want them.

## Related Issues and/or PRs
I could not find a related issue.

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
My client is not running MySQL 5.7.  In 5.7, a view can contain derived tables.  To get the mail merge working, I had to create multiple views to piece together the information.

I stripped out the references to their site as a security precaution.

### WordPress Environment ###
Home URL: https://.org
Site URL: https://.org
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: Home (#9)
Page for Posts: Unset
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: 
TLS Connection: Connection uses TLS 1.2
TLS Connection: Bad
Server Info: Apache
PHP Version: 7.0.23
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
PHP Max Upload Size: 2 MB
cURL Version: 7.54.0, OpenSSL/1.0.2k
SUHOSIN Installed: –
MySQL Version: 5.6.36
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 1.8.15
Upgraded From: 1.8.13
Test Mode: Disabled
Currency Code: USD
Currency Position: After
Decimal Separator: .
Thousands Separator: ,
Success Page: https://.org/donation-confirmation/
Failure Page: https://.org/donation-failed/
Donation History Page: https://.org/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Offline Donation, Stripe - Credit Card
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Admin Email Notifications: Disabled
Donor Email Access: Disabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Email Reports: ✔ Licensed – by WordImpress – 1.0.1
Give - Form Field Manager: ✔ Licensed – by WordImpress – 1.2.3
Give - MailChimp: ✔ Licensed – by WordImpress – 1.3.6
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.1.1
Give - PDF Receipts: ✔ Licensed – by WordImpress – 2.0.7
Give - Recurring Donations: ✔ Licensed – by WordImpress – 1.3.1
Give - Stripe Gateway: ✔ Licensed – by WordImpress – 1.5

### Other Active Plugins ###

Akismet Anti-Spam: by Automattic – 4.0
Duplicate Post: by Enrico Battocchi – 3.2
PDF Embedder: by Dan Lester – 3.0.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
SiteOrigin Widgets by CodeLights: by CodeLights – 1.2
Slider Revolution: by ThemePunch – 5.4.1
SSL Insecure Content Fixer: by WebAware – 2.4.0
UKUU PEOPLE: by UkuuPeople – 1.6.2
UKUU PEOPLE GIVE: by UkuuPeople – 1.0.4
UKUU PEOPLE Import Add-on: by UkuuPeople – 1.0.4
Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.10
UpSolution Header Builder: by UpSolution – 1.0.3
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Yoast SEO: by Team Yoast – 5.4.1

### Inactive Plugins ###

WooCommerce: by Automattic – 3.1.2

### Theme ###

Name: Zephyr Child
Version: 1.0
Author URL: http://us-themes.com/
Child Theme: Yes
Parent Theme Name: Zephyr
Parent Theme Version: 4.2
Parent Theme Author URL: http://us-themes.com/
</details>

**Comment by DevinWalker** [comment]
This is a good request. I'm moving it to the PDF Receipts repo.

**Comment by DevinWalker** [comment]
Issue moved to [WordImpress/Give-PDF-Receipts #113](https://github.com/WordImpress/Give-PDF-Receipts/issues/113) via [**ZenHub**](https://www.zenhub.com/)
