### ISSUE TITLE
When viewing donations filtered by donor performing bulk actions causes to lose filter

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2334]
## Issue Overview
When you're viewing a donor's donations within wp-admin and perform a bulk action you lose the donor filtered view you were on prior to the action:

![2017-11-13_15-00-10](https://user-images.githubusercontent.com/1571635/32753867-6abfc1c0-c883-11e7-897e-337910aacb28.gif)

## Expected Behavior
Filter remain through actions.

## Current Behavior
The donor filter is lost.

## Steps to Reproduce (for bugs)
1. Enter a donor filtered view `/wp-admin/edit.php?post_type=give_forms&page=give-payment-history&donor=4`
2. Change a donation status
3. You'll see all recent payments and your filter is no longer active

**Comment by raftaar1191** [comment]
Will fixed this once the below mentions issues resolved: https://github.com/WordImpress/Give/issues/2683
