### ISSUE TITLE
Force select field height to prevent theme conflicts

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2340]
## Issue Overview
Some themes force a height on select or input fields. This can cause problems with Floating Labels.

## Expected Behavior
The floating labels inside the fields should always be visible.

## Current Behavior
Theme's add something like `height: 35px` to a select and/or input field and it looks like this:
![image](https://user-images.githubusercontent.com/930724/32811216-60ef14b8-c953-11e7-8d3b-6227bdd377e0.png)

## Possible Solution
```
[id*=give-form] .fl-form.fl-style-give select.fl-select {
    height: auto;
}
```

Probably want to apply it to floating label INPUTS as well so that they are all the same height.

## Steps to Reproduce (for bugs)
1. Add this into your child-theme styles.css file:
`* select, * input {height: 15px; padding: 15px;}`
2. Enable floating labels, confirm that the label is no longer visible
3. Add the CSS snippet in the "Possible Solution" above into the Give CSS, confirm it's fixed

## Related Issues and/or PRs

May be related:
https://github.com/WordImpress/Give/issues/1511

**Comment by DevinWalker** [comment]
Related to #1453
