### ISSUE TITLE
Floating labels don't work in modal or button display mode

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2341]
## Issue Overview
Floating labels don't work in modal or button display mode
As reported here: https://wordpress.org/support/topic/floating-labels-not-working/#post-9683703

## Expected Behavior
Floating labels SHOULD work in both modal and button display mode

## Current Behavior
Currently, floating labels don't work in modal or button display mode.

The user has a test form live at the moment where floating labels has been enabled, but you can clearly see that they are not triggering in the modal at all:
https://www.earthmedresearch.org/donations/floating-labels-test-1/

## Possible Solution
Potentially just a markup issue where FL can't find our fields. The "reveal" mode works just fine so it doesn't seem like it's because the form is hidden first... could be wrong though. Because both are done with manifiq it's possibly related to that as well.

## Steps to Reproduce (for bugs)
1. Create a form that has both the Modal display mode, and Floating labels
2. Test it on the frontend and you'll see that floating labels aren't applied
3. Test another form that uses reveal mode or all fields mode and you'll see floating labels working fine.

**Comment by raftaar1191** [comment]
https://wordpress.org/support/topic/floating-labels-not-working/#post-9680121

The Bug was introduced in Give Core Version `1.8.13` 
-> Checked Perfect the issues start from Give Core version `1.8.13`

**Comment by ravinderk** [comment]
@raftaar1191 I push some commits to your repo.
https://github.com/raftaar1191/Give/tree/issues/2341

Please review it and create PR.

@DevinWalker @mathetos Space after form id selector was issue: https://github.com/ravinderk/Give/commit/8926269d45b044076b4e44784a8d1f7d0a3d47a6#diff-92d269e641185ced61bf5b96e8930477R56

**Comment by raftaar1191** [comment]
Checking @ravinderk

**Comment by raftaar1191** [comment]
Thanks @ravinderk for the quick fix 

It's working absolutely fine
