### ISSUE TITLE
Plain text email template doesn't support links

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2346]
## Issue Overview
This might be by design, but it becomes impractical with add-ons like PDF Receipts which automatically add links into the email body.

The issue is that when you select "No template, Plain Text" as your email template, and your email body copy has links in it, they do not render at all. 
![image](https://user-images.githubusercontent.com/930724/32867197-a6d4cd7e-ca20-11e7-9b2e-9286cf4ae943.png)

## Expected Behavior
Links should be output in one way or another.

## Current Behavior
Links simply aren't present at all.
![image](https://user-images.githubusercontent.com/930724/32867249-e6a9d192-ca20-11e7-95ad-d9cd1c10c20b.png)

## Possible Solution
I don't think we should necessarily support live hyperlinks, but the link should be automatically output next to the word that is hyperlinked.

I believe this is what MailChimp and other email services do with their plain-text emails.

## Steps to Reproduce (for bugs)
1. Go to "Donations > Settings > Emails > Donation Notification" and add a hyperlink into the email via the text editor.
2. Switch the Email template to "No template, plain text"
3. Click the "Send Test Email" and check the output. Link text will be present, but it will not be a hyperlink and the url will not be output anywhere.

**Comment by raftaar1191** [comment]
@mehul0810 

Small bug See the video for the informations http://screencast-o-matic.com/watch/cbloDC272X

**Comment by raftaar1191** [comment]
@ravinderk @DevinWalker can you please reopen this issues I am facing an issue in this 

[Issues link](https://github.com/WordImpress/Give/issues/2346#issuecomment-352053246)
