### ISSUE TITLE
refactor(donor): create singular method to delete donor

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2347]
## Issue Overview
Currently, there are many different ways used to delete donor. However, to overcome this issue we require a unified function with which donor deletion can be managed and made extensible.

**Check Document for more details:** https://docs.google.com/document/d/1opVjPivmtxHk-MTSw39WDFma3PgQetoTVRt-4FciB5w/edit#

## Expected Behavior
Create an extensible and unique function to manage donor deletion process.

## Current Behavior
Managed via multiple functions.

## Todos
- [x] Investigate
- [x] Fix
- [ ] Write post on developers.givewp.com

**Comment by raftaar1191** [comment]
Nice suggestion @mehul0810

**Comment by DevinWalker** [comment]
@mehul0810 can you draft a post on developers.givewp.com and I'll review - then we can close this one out.
