### ISSUE TITLE
Give 1.8.17 issue with upgrade routine 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2356]
## Issue Overview
I haven't run the upgrade routine yet and cannot access donations even as `administrator`. 

![2017-11-18_21-49-39](https://user-images.githubusercontent.com/1571635/32987863-b44dc8c4-ccab-11e7-971c-ba290d27ad5b.png)

If I switch to the `master` branch I can see the single donations:

![2017-11-18_21-58-27](https://user-images.githubusercontent.com/1571635/32987867-cca84f5c-ccab-11e7-8f2e-4ebfc65b48a3.png)

## Expected Behavior
The `administrator` should always have access to the donations.

## Current Behavior
An upgrade needs to run first (assuming).

![2017-11-18_21-49-39 copy](https://user-images.githubusercontent.com/1571635/32987901-bef61104-ccac-11e7-8ffb-a0cd878f6ace.png)

## Steps to Reproduce (for bugs)
1. Switch from `release/1.8.17` to `master` without doing the upgrade

## Related Issues and/or PRs
https://github.com/WordImpress/Give/issues/2112

**Comment by DevinWalker** [comment]
Thanks @mehul0810 it works nicely.

**Comment by raftaar1191** [comment]
@mehul0810

Let me know if this is an issues or not 
http://screencast-o-matic.com/watch/cblf0B2gQ4

**Comment by DevinWalker** [comment]
That appears to be an issue still per @raftaar1191's video. Reopening.
