### ISSUE TITLE
Consider showing goal without decimal places

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2372]
## Issue Overview
Showing the goal with decimal places is a bit awkward. We should either just ignore decimal places completely on goals, or provide an option to enable/disable decimals within the form edit screen.

See here:
![image](https://user-images.githubusercontent.com/930724/33044893-986fdc78-cdff-11e7-805c-711ad31647f5.png)

<details>
Customer request here:
https://secure.helpscout.net/conversation/471518666/11857?folderId=672199
</details>

**Comment by DevinWalker** [comment]
I agree, easy fix.
