### ISSUE TITLE
QUESTION: Investigate how the Dashboard Widgets store data

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2373]
## Issue Overview
We had two customers report that the WP-Admin/index.php (aka Dashboard) is being extremely slow for them -- even doing a 503 Gateway error.

In troubleshooting this I found that removing the Activity Dashboard widget, refreshing Give reports and data with our tools, and deleting all transients generally cleared up the issue. It raises the question about how we are storing the data that is presented in those dashboard widgets and whether we can improve their performance.

**Comment by raftaar1191** [comment]
Related PR: https://github.com/WordImpress/Give/issues/2383

**Comment by DevinWalker** [comment]
Yes this is resolved now as of `1.8.17` - you can see the dashboard on https://givewp.com/wp-admin/ loads much faster now because of the work done in the PR above.
