### ISSUE TITLE
Consider updating MXN currency symbol to "MXN $"

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2390]
## Issue Overview
A customer in Mexico mentioned that they wanted to make it clear that their donors were paying in Pesos and not US Dollars since they use the same currency symbol (i.e. "$"). He asked that the abbreviation prefix the symbol, like so: `MXN $`. 

Customer ticket as reference: https://secure.helpscout.net/conversation/469620207/11821/?folderId=672199

## Possible Solution
Update the Mexican Peso currency as follows:

```
$currencies['MXN'] = array(
		'admin_label' => __( 'Pesos Mexicanos ($)', 'give' ),
		'symbol'      => 'MXN &#36;',
		'setting'     => array(
			'currency_position'   => 'before',
			'thousands_separator' => ',',
			'decimal_separator'   => '.',
			'number_decimals'     => 2,
		),
	);
```

The results:
![image](https://user-images.githubusercontent.com/930724/33150110-012139aa-cf87-11e7-9ed4-1f0ba713ad53.png)

![image](https://user-images.githubusercontent.com/930724/33150120-06f3c8d4-cf87-11e7-9113-be1cace1a45c.png)

![image](https://user-images.githubusercontent.com/930724/33150127-0c20d36a-cf87-11e7-82c0-e528678f5459.png)

**Comment by DevinWalker** [comment]
Is this how Mexican Pesos should be formatted? What does Woo, Shopify and Magento do?

**Comment by raftaar1191** [comment]
In WooCommerce it handles the same way as dollar like here I have set 
![image](https://user-images.githubusercontent.com/22215595/33961729-1f04b862-e075-11e7-8eab-45680acfebef.png)

Product Order Page:
![image](https://user-images.githubusercontent.com/22215595/33961713-0c8ec920-e075-11e7-8f38-544a5d6f4f9d.png)

Not check with Shopify and Magento  will do an notify you soon

**Comment by DevinWalker** [comment]
I think a snippet would work better to resolve this issue:

```
/**
 * Output a custom currency symbol prefix. 
 * 
 * This example places "MXN" before "$". 
 *
 * @param $symbol
 * @param $currency
 *
 * @return string
 */
function my_custom_currency_prefix($symbol, $currency ){
	switch ( $currency ) :
		case 'MXN' :
			$symbol = 'MXN &#36;';
			break;
	endswitch;

	return $symbol;
}

add_filter('give_currency_symbol', 'my_custom_currency_prefix', 10, 2);
```
