### ISSUE TITLE
[1.8.17] Give_Donors_Query related notices

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2391]
## Issue Overview

When you will search for a donor name on donor listing admin page if starts from `s`, `d` and `f`. you will get a PHP notice and warning.

![screen shot 2017-11-23 at 11 06 16 am](https://user-images.githubusercontent.com/1784821/33159957-6ff38466-d03e-11e7-8f06-4aa75e04f801.png)

## Expected Behavior

Zero notice and warning

## Current Behavior

Getting notice and warning

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by raftaar1191** [comment]
I also face this issue once.

Nice finding @ravinderk
