### ISSUE TITLE
Donation statuses not following sort applies on donation listing page.

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2400]
## Issue Overview

For example: if you sort donation listing page by `form_id` then donation listing page will sort by `form_id` but donation statuses link still contains URL to the main donation listing page [sort only with status]

<img width="1084" alt="e5835c62613bf84aa8acb60aea077c1e" src="https://user-images.githubusercontent.com/1784821/33198545-af61a1e0-d111-11e7-9836-457e844dbde8.png">

## Expected Behavior

Donation status link must obey donation listing page sorting

## Current Behavior

Not working, takes to main donation listing page which sorts by status.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
@raftaar1191 if you can get this into 2.0 that would be great. Otherwise, 2.0.1

**Comment by raftaar1191** [comment]
Sure @DevinWalker Will fixed this in Give Core Version 2.0

**Comment by ravinderk** [comment]
@DevinWalker I made a direct commit to `release/2.0`. Can you review this?

For ref: https://github.com/WordImpress/Give/compare/e3275cc816d0...876a5a54dfb4

**Comment by DevinWalker** [comment]
Looks good @ravinderk
