### ISSUE TITLE
Donations should be easily identified for form with Set Donation Method

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2401]
## Issue Overview
I've created a donation form with custom amount enabled and performed 2 different donations with it. Then, checking the donations section it is not easily identified whether which donation is of regular amount and which is of custom amount.

Areas to add the possible solution:
- Donation Listing page in admin.
- Donation Detail page in admin.
- Donation Receipt in front end.

**Note:** I can reproduce this issue with `release 1.8.17` as well as `release 2.0`

## Expected Behavior
![image](https://user-images.githubusercontent.com/1852711/33202810-e4765238-d123-11e7-8e8b-6515f04bd09b.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/1852711/33202750-aae21bc4-d123-11e7-81e5-b134d6b3fc3f.png)

## Possible Solution
Adding a text `Custom Amount`, in similar way of multi level forms will make this more effective.

## Steps to Reproduce (for bugs)
1. Create a donation form with `Set Donation` Method and Custom Amount enabled
2. Create 1 donation with actual amount of that form and create another donation with random amount.
3. Check both the donations in admin
4. You won't be easily identifying which one is the actual amount of the donation form, unless you check the amount in donation form.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by DevinWalker** [comment]
I agree. The "Custom Amount" label should also display for set donation forms as well. That's a bug.
