### ISSUE TITLE
Goal Amount Placeholder and field should be 1.00, not 0

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2402]
## Issue Overview
While creating a new donation form,

Go to:
- Add New Donation Form
- Click on `Donation Goal` Tab.
- Click on `Enabled` to enable goal for the donation form
- You'll see the `Goal Amount` set as `0` instead of `1.00`

**Note:** I can reproduce this issue for `release 1.8.17` as well as `release 2.0`

## Expected Behavior
Default `Goal Amount` should be `1.00`

## Current Behavior
![image](https://user-images.githubusercontent.com/1852711/33203791-444f3276-d127-11e7-9a2b-bfcaebdf30e8.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by raftaar1191** [comment]
Nice Catch @mehul0810 

One more thing it should be greate then minimum donation amount if the minimum donation amount is set

**Comment by ravinderk** [comment]
@DevinWalker  @mehul0810 closing it because we will resolve this in https://github.com/WordImpress/Give/issues/2425#issuecomment-347637138
