### ISSUE TITLE
`Change Donor` chosen list hidden while open on donation detail page

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2412]
## Issue Overview

![image](https://user-images.githubusercontent.com/1784821/33262150-54066cf0-d38b-11e7-99a2-c6cb4c1c0286.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
Edit in globally used css selector: https://github.com/WordImpress/Give/pull/2288/files#diff-5efc276ea8cc0d35625695868a23be87R888

**Comment by emgk** [comment]
I think I have already created this issue #2378
