### ISSUE TITLE
Licenses not being deleted after deactivating

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2418]
## Issue Overview
I'm a bit stumped as to why the license data isn't being deleted. It appears `give_delete_option( "{$this->item_shortname}_license_key" );` correctly runs within the `unset_license()` method found within `class-give-license-handler.php` but it isn't updating in the UI:

![2017-11-27_16-57-08](https://user-images.githubusercontent.com/1571635/33297102-1d6eabe0-d394-11e7-80a3-013f9adcc912.gif)

## Expected Behavior
The license field is empty after deactivating.

## Current Behavior
The license field contains the deactivated license key

**Comment by mathetos** [comment]
This looks really solid now. Great work!
