### ISSUE TITLE
IMPORTER: Donations are being inaccurately marked as duplicates

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2420]
## Issue Overview
Donations are being inaccurately marked as duplicates.

## Expected Behavior
When a CSV file is imported, and the donations are from the exact same donor but on different dates, they should all be imported.

## Current Behavior
Currently, it appears only the FIRST donation from a donor is imported and all others are treated as duplicates even though the donations occured on different dates.

## Possible Solution
I believe these lines here are either malforming or misconstruing the date formats for imported donations: https://github.com/WordImpress/Give/blob/release/1.8.17/includes/import-functions.php#L684-L685

## Steps to Reproduce (for bugs)
1. Ask me for the CSV file I've been working from
2. Map the fields like so:
![givewp-mapped-fields](https://user-images.githubusercontent.com/930724/33297304-1bbf69be-d395-11e7-91bb-62226423bd61.jpg)
3. Run the import
4. You'll get around 129 duplicates when there are only 22 duplicates total.

**Comment by raftaar1191** [comment]
https://givewp.slack.com/files/U064V9KDJ/F865UL2JF/pawm-import-edited.csv
