### ISSUE TITLE
IMPORTER: Investigate ways to increase speed of the Importer

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2427]
## Issue Overview
When importing 1000+ donations, the importer timed out locally. Importing 500+ donations took around 30 minutes. There should be smart ways to increase the speed of the imports, or even set an amount of donations to import at a time.

I have a couple CSV files available for testing purposes.

**Comment by raftaar1191** [comment]
@mathetos 

Should I add an input box in which admin can set the number of donation to process at one time and also and filter to over writer that setting 

Example:
![image](https://user-images.githubusercontent.com/22215595/33401689-23948470-d580-11e7-91c0-eade89ee5b5e.png)

**Comment by DevinWalker** [comment]
I would say a setting like that works nicely. Make it more like 100 by default. Also it should be titled:

> Process Rows Per Batch

Description:
> Determine how many rows you would like to import per cycle. 

Also make the input a number field and much small in width. It's too wide there.

**Comment by raftaar1191** [comment]
Okay @DevinWalker doing that

**Comment by raftaar1191** [comment]
@DevinWalker 

I would suggest the default per page should be 25 as there are many websites which is being hosted on Share server. I think processing 100 donations per batch will result in time out for Share Server as they have low memory and processing power

**Comment by raftaar1191** [comment]
@DevinWalker 

I have sent a PR in which per page is set to **25** let me know if I need to change it
