### ISSUE TITLE
Improve sql query for give_get_purchase_id_by_key fn

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2443]
## Issue Overview

`give_get_purchase_id_by_key` will search for donation purchase key without specifying any order which increasing query time.

**Before order clause:**
![screen shot 2017-11-30 at 5 10 31 pm](https://user-images.githubusercontent.com/1784821/33429190-cb9319b8-d5f1-11e7-90dd-e29ffdaa088a.png)

**After order clause:**
![screen shot 2017-11-30 at 5 09 40 pm](https://user-images.githubusercontent.com/1784821/33429188-cb5a0a1a-d5f1-11e7-9879-a78138d4077a.png)

**Comment by DevinWalker** [comment]
Can we rename it as well to `give_get_donation_id_by_key`?

**Comment by ravinderk** [comment]
@DevinWalker Agreed
