### ISSUE TITLE
design(gutenberg): give gutenberg block concept

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2456]
## Issue Overview

Give needs to design how the Gutenberg block is going to look.

- [x] Determine UI/UX objectives
- [x] Design Gutenberg Concept
- [x] Iterate and agree

**Comment by kevinwhoffman** [comment]
Here's an idea of what a Give Donation Form block could look like in Gutenberg. The general idea is to adapt the existing functionality of the [Shortcode Generator](https://givewp.com/documentation/core/shortcodes/give_form/) while capitalizing on the advantages that Gutenberg offers, such as real-time form previews.

## Give Gutenberg Block Concept

In Gutenberg, the functionality of the existing Shortcode Generator can be split amongst the Block and the Inspector. I have demonstrated how this Block/Inspector combination can work below.

![give-gutenberg-concept-v01](https://user-images.githubusercontent.com/1938671/33928506-1e6487dc-dfb4-11e7-8916-137c4d5a9a72.png)

### Block Controls

- Select a Give Donation Form... (select)

### Inspector Controls

- Presentation (panel)
    - Format (select)
        - Full Form (option)
        - Modal (option)
        - Reveal (option)
        - One-button Launch (option)
- Form Components (panel)
    - Show Title (toggle)
    - Show Goal (toggle)
    - Form Content (toggle)
    - Content Position (radio - only appears if Form Content === On)
        - Above Fields
        - Below Fields

**Comment by mathetos** [comment]
Note that to have full parity with our existing shortcode, we'll also need this:
- Presentation (panel)
    - Format (select)
        - Reveal (option)
            - Continue Text (text input) _Only appears if "Reveal" is chosen_

Ref: https://givewp.com/documentation/core/shortcodes/give_form/

**Comment by PareshRadadiya** [comment]
I just wanted to show the progress done so far on Gutenberg Donation Form Block.
Here is the screencast of Donation Form Block:
http://recordit.co/myIknPX61I

The Donation Form Block embed the form preview base on the parameters selected in Block Control panel. The embedding technique to preview the form will ensure consistent preview as there might have been add-on plugins which would have been hooking custom fields in the donation from. The preview will get refreshed each time when user change the form settings from the Block Control.

**Comment by DevinWalker** [comment]
Looks great @PareshRadadiya

**Comment by DevinWalker** [comment]
I just updated this issue to be more design focused and part of the larger epic of creating our first Gutenberg block. As we've completed the design process I'm closing it out.
