### ISSUE TITLE
Add Screen Options to WP-Admin Donation Pages

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2457]
## Issue Overview
Add Screen Option in All Donation Page in Dashboard

## Expected Behavior
![screenshot-give17 local-2017-12-06-01-06-52-830](https://user-images.githubusercontent.com/22215595/33626909-f83e0232-da21-11e7-8272-ed91cb9f4d77.png)

## Current Behavior
No option to disable some table and reselect per page donation

**Comment by DevinWalker** [comment]
Personally I'm not a huge fan of the "Screen Options" tab as it's very hidden. I agree we should allow to customize the table columns that appear on screens like the donation listing page but it should be more obvious that that hidden tab WP provides.

**Comment by raftaar1191** [comment]
Yes @DevinWalker I agree it's kind of hidden, But that the standard with WordPress and all the other Plugins


If a user is using WordPress he will definitely know where s/he will have the option to show/hide the table columns

**Comment by DevinWalker** [comment]
True it's the standard for WP core but it's definitely not the standard for "all the other Plugins". 

I also don't believe this is true as well:

> If a user is using WordPress he will definitely know where s/he will have the option to show/hide the table columns

Many times I've had to direct users to the Screen Options tab to change various settings in WP core. I remember receiving many feedback of "Oh wow, I didn't even see that".

Avoid using words like "definitely" and "all" unless it's 100% true. If it's 99.9% then it's "most". 50% = "some". 😉

**Comment by raftaar1191** [comment]
Agreed with you @DevinWalker 

What about adding a setting page Call **Per Page** in Donation Form > Settings  > Display Options 

And adding this two settings on that page
![image](https://user-images.githubusercontent.com/22215595/33957129-bbfa5974-e066-11e7-86da-9abc7093c821.png)

**Comment by malayladu** [comment]
@raftaar1191 It's good to have a flexible system but at the same time we have to keep the things simple too.

Too many setting options would make user overwhelm.

So, it's better to have minimal settings and add settings only if it's most require. 

I don't think this is necessity. User can still see the other donations by visiting 2nd page. So, in my perspective it's ok to have a default(hardcoded) value of per page count.

**Comment by raftaar1191** [comment]
@malayladu yes that sounds cool to me too But I will like to add a filter at least that can control the **per page** option 

@DevinWalker what are your thoughts on this?

**Comment by ravinderk** [comment]
@raftaar1191 Closing this issue because it is not necessary.
