### ISSUE TITLE
Reports JS Uncaught Error: Time mode requires the flot.time plugin.

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#246]
Looks like recent changes borked the JS for Reports.

**Comment by DevinWalker** [comment]
I think this is related to https://github.com/WordImpress/Give/pull/236

**Comment by mathetos** [comment]
I like the use of the word "borked" here. Though I don't like what it represents. If it's urgent, we should send a hotfix rather than wait for 1.3.

**Comment by DevinWalker** [comment]
It's not in the released version currently.

**Comment by DevinWalker** [comment]
This is fixed but now the individual stats are on top of one another: 
![9-14-2015 9-40-56 am](https://cloud.githubusercontent.com/assets/1571635/9855680/cff58bb2-5ac4-11e5-975f-11fe9b1c7102.png)

**Comment by DevinWalker** [comment]
Creating a separate issue for that
