### ISSUE TITLE
Reports bar graphs incorrectly overlaid on eachother

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#248]
Related to #246 and #247 

![9-14-2015 9-40-56 am](https://cloud.githubusercontent.com/assets/1571635/9855716/0127194e-5ac5-11e5-8e46-99e49d4de9df.png)

**Comment by DevinWalker** [comment]
The image above is what is *should* look like

**Comment by pryley** [comment]
I think I know what's causing it. I'll have a look.

**Comment by DevinWalker** [comment]
Looks great now.
