### ISSUE TITLE
 [Give 2.0] Clicking Email Notification Tab under New Donation Form goes blank

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2489]
## Issue Overview
When we create a new donation form and click on the Email Notifications tab (parent tab), then there is no settings into it. Hence, it is blank which is not good UX.

Please check below screenshot:
![image](https://user-images.githubusercontent.com/1852711/33771164-0ade7026-dc56-11e7-9e7e-1f1dd49dcca3.png)

## Expected Behavior
It should directly show content of first sub-tab.

## Current Behavior
Email Notifications tab show empty content.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
Duplicate https://github.com/WordImpress/Give/issues/2368
