### ISSUE TITLE
`give_require_billing_address` filter is always set to `false`

### ISSUE THREAD

**Issue by pryley** [WordImpress/Give#249]
The `give_require_billing_address` filter (`/includes/process-purchase.php:275`) is `true` by default, but will always be set to `false` because of `give_manual_no_cc_validation()`.

Here is a alternate way to write the function that allows other functions to modify the filtered value:
```
/**
 * Manual Gateway does not need CC billing address validation, so remove it.
 *
 * @since 1.0
 *
 * @param bool $bool
 *
 * @return void
 */
function give_manual_no_cc_validation( $bool ) {
	if ( isset( $_POST['give-gateway'] ) && $_POST['give-gateway'] == 'manual' ) {
		$bool = false;
	}

	return $bool;
}

add_filter( 'give_require_billing_address', 'give_manual_no_cc_validation' );
```

Since the default filtered value is `true`, you will need to add a similar function to any gateways that do not require billing address validation (i.e. PayPal Standard, Offline, etc.).

---

There is also an issue with the Braintree gateway plugin where form validation is not performed via ajax, making it impossible to use the single Form Payment Field `Reveal Upon Click / Modal Window Upon Click` options successfully.

I mention this here because I am sending you an email with a preliminary fix for the Braintree plugin, but it is not complete without being able to also validate the billing address fields.

**Comment by DevinWalker** [comment]
Hmm, I'm going to dig into this one. Seems alarming off the bat.

**Comment by DevinWalker** [comment]
@pryley how about we simply remove `give_manual_no_cc_validation()` it seems entirely unnecessary?

**Comment by DevinWalker** [comment]
I'm trying to wrap my head around this... 

I have removed `give_manual_no_cc_validation()` but now currently PayPal and Manual (Test) are broken because of the true value returned here: https://github.com/WordImpress/Give/blob/master/includes/process-purchase.php#L281

Perhaps we can write a function similar to `give_is_cc_verify_enabled()` that checks whether or not the current gateway has CC fields enabled then return true/false dynamically depending on the chosen gateway.

**Comment by DevinWalker** [comment]
@pryley we're getting close here. The only issue now that I can see is with `give_is_field_required` here https://github.com/WordImpress/Give/blob/master/includes/forms/functions.php#L206 when there's no `$_POST` available the fields required labels don't display properly.

**Comment by pryley** [comment]
Currently gateways determine whether or not they include the CC fields by including a gateway specific hook (`has_action( 'give_' . $payment_mode . '_cc_form' )`). This hook allows you to override the default `give_cc_form` hook which displays the CC fields.

Since the form ID is passed to these hooks, you could pass it through to the `give_field_is_required()` which in turn can send it to `give_require_billing_address()`. If the $form_id exists, then address fields are required by default, if not, they aren't.

And of course gateways can override through the `give_require_billing_address` hook.

**Comment by DevinWalker** [comment]
I've almost got nearly what you described working. Give me a sec to commit

**Comment by DevinWalker** [comment]
@pryley if you have a moment can you check out what I did here: 15cf87d511c84a02f1d087871a2f3c9cb4d07430

It seems to be functioning nicely upon initial testing. Here's the branch: https://github.com/WordImpress/Give/tree/issue/249

**Comment by pryley** [comment]
@DevinWalker Oh I didn't see this, I also just made a commit. :)
I'm heading to bed now so I'll have a look tomorrow.
