### ISSUE TITLE
perf(admin-setting): optimize loading of options

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2491]
## Issue Overview
If you run the following SQL query:

`SELECT * FROM wp_options WHERE option_name LIKE '%give_%' AND autoload='yes'`

… Then you will find that there is certain data that we are storing in option table that has autoload set to true. This means that it will load on each page even we do not need it:

![image_1](https://user-images.githubusercontent.com/1571635/33784222-e0e536a6-dc14-11e7-8dbd-3681482baf04.png)

**The `get_option()` function internally caches all autoload options, so Give options will load only the first time.**

### The Issue with Autoload

* It adds unwanted weight for first the get all options query.

* We are storing all core settings in a serialize array. So every time we have to get all core setting even if we only need:

    * Page related setting

    * Currency related setting

    * Email setting

    * Advance setting etc.

## Solution

To resolve above issue we can do following:

* Stop setting autoload to true for all core options.

* Group similar settings into their own groups. For example:

    * Currency settings

    * Page settings

    * Payment gateway setting ( per payment gateway )

    * Email setting

To achieve this we have to do following this:

1. Develop a Core setting upgrade routine:
This will restore setting according to their `setting_page[section][tab][setting_name1]`, `setting_page[section][tab][setting_name2]`, etc.

2. Update admin core render and save logic with backward compatibility:

![image_2](https://user-images.githubusercontent.com/1571635/33784254-f217b21e-dc14-11e7-9460-fb75a1babcc5.png)

3. Update `give_get_option` to get setting by each section, tab or all with backward compatibility

#### Related Links:

* [https://wordpress.stackexchange.com/a/83776/29439](https://wordpress.stackexchange.com/a/83776/29439)

**Comment by ravinderk** [comment]
Slack Chat Summary

Participants: @DevinWalker Ravinder Kumar
Topic: Scope of this issue
Result:  Set `autoload` to `no` for most of Give settings.
