### ISSUE TITLE
Disabling "Anyone can register" doesn't stop user to create an account.

### ISSUE THREAD

**Issue by emgk** [WordImpress/Give#2499]
## Issue Overview

Disabling "**Anyone can register**" option from the `Setting > General > Membership` is not works and donation form _( If it requires registration )_ still allow the user to create an account.

![screenshot-wpgivetest20 dot-2017-12-11-19-37-39-431](https://user-images.githubusercontent.com/14994452/33834930-c7402be6-deaa-11e7-90f7-8fc04dd6fbe5.png)

## Expected Behavior

Not sure its okay or not but it should obey WP setting field.

## Current Behavior

Donation form allows creating an account even if "**Anyone can register**" setting is disabled.

## Steps to Reproduce (for bugs)

1. Goto Add Donation.
2. `Form Display` > `Registration` choose `Registration` field and save.
3. Go front end (as non-logged in ) and make the donation with registration.
4. It will create the new user in the backend.

## Related Issues and/or PRs

https://github.com/woocommerce/woocommerce/issues/13676

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Copy and paste the system Info report from **Donations > Tools > System Info** in WordPress admin here.
```
</details>

**Comment by DevinWalker** [comment]
I don't think it's a problem. We will reopen if customer confusion arises.
