### ISSUE TITLE
Hard to map a field to correct column on large screen. 

### ISSUE THREAD

**Issue by emgk** [WordImpress/Give#2507]
## Issue Overview

Currently, in `Tools > Import`  page in backend there is no horizontal line between the row field, so it makes confusion for admin to map a column to correct field.

![screenshot-givecache20 local-2017-12-12-18-55-17-638](https://user-images.githubusercontent.com/14994452/33887400-a9ea08e4-df6f-11e7-9642-ba3b82f595f0.png)

## Possible Solution

Add horizontal lines between table row.

## Steps to Reproduce (for bugs)

1. Goto  Tools >  Import 
2. Choose CSV to import and hit next button.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by akashsonic** [comment]
@DevinWalker @raftaar1191 

After adding a horizontal line between the settings, it looks not so good. Screenshot is available on http://nimb.ws/6Q7YG5

But if we adding background color in row odd/even then all settings looking more separately and clearly, You can check that on http://nimb.ws/gj18En

Let me know which design looks good here, I will send PR as per that.

Thanks.

**Comment by raftaar1191** [comment]
I like the background color option @akashsonic let also @DevinWalker comment on this

**Comment by DevinWalker** [comment]
I also like the varying background color option. @akashsonic's concept is a little bolder than I'd like to see the colors but still it looks nice. If we could tone down and soften those colors a bit I think it would look much improved.

**Comment by emgk** [comment]
@DevinWalker It looks good but how about if we use the default WordPress table row alternative CSS color? So, it makes more consistencies with WordPress. 

![screenshot-localhost-2018-01-05-19-16-23-642](https://user-images.githubusercontent.com/14994452/34611798-f1df5876-f24c-11e7-901b-ee4d5a8f68f2.png)

**Comment by kevinwhoffman** [comment]
I think the WordPress alternating row styles work fine here. The main issue is proximity, not contrast. The field labels are currently much closer to each other than they are to the inputs they are labeling.

The first column could be given a `max-width` in order to keep the second column closer in proximity and therefore the relationship between label and input would be clarified.

**Comment by DevinWalker** [comment]
I agree with both @kevinwhoffman and @emgk - Let's use the WP colors and also tighten up that first column width.

**Comment by akashsonic** [comment]
@DevinWalker Okay, I am working on that. I will do WP colors and also tighten up that first column width in the setting option.

**Comment by akashsonic** [comment]
@DevinWalker I do WP colors and also tighten up that first column width 250px in the setting option. It's looking good check here http://nimb.ws/y0o8ix

Let me know if design looks good here, I will send PR as per that.

Thanks.

**Comment by DevinWalker** [comment]
Yeah that looks good @akashsonic thanks 👍

**Comment by ravinderk** [comment]
@akashsonic You can direct post image to github comment. Please follow it.

**Comment by akashsonic** [comment]
@ravinderk @DevinWalker I have resolved this issue in PR #2640

Thanks.

**Comment by akashsonic** [comment]
@DevinWalker I have updated my PR with only scss files changes, You can check that on #2645
