### ISSUE TITLE
WP cache variable for unread notifications is not correctly unset

### ISSUE THREAD

**Issue by mqudsi** [WordImpress/Give#2517]
With WordPress object caching enabled and an appropriate object caching backend such as memcached or redis installed, WP-Give inserts an item into the cache representing the read status of "important announcements"/"notifications", but does not correctly unset them, leading to their persistence until the cache is flushed or the item is eventually evicted from the cache/expired.

**Comment by DevinWalker** [comment]
Hey @mqudsi is this the current `master` branch of in `release/2.0`?

**Comment by mqudsi** [comment]
Running `1.8.17`, actually.

**Comment by DevinWalker** [comment]
Got it. Thanks. We'll check into it asap.

**Comment by mqudsi** [comment]
I appreciate the crazy fast response :)

**Comment by mqudsi** [comment]
Actually, can you table this for now? I'm noticing a few other object cache oddities that have persisted after flushing the cache, resetting the cache salt key, and changing the key name prefix. I think there's something else at play here.

**Comment by DevinWalker** [comment]
Yep, let me know if you find anything else out.
