### ISSUE TITLE
Minimum amount incorrect with changed decimal and thousands separators.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#2526]
## Issue Overview
If you change the thousands and decimal separators, the minimum amount gets messed up.

## Expected Behavior
You should be able to use commas as the decimal separator, and periods as the thousands separator.

## Current Behavior
You can't do that right now, on a custom amount form with a minimum. 

## Steps to Reproduce (for bugs)
1. Make the decimal separator a comma, and the thousands separator a period, like this: ![image](https://user-images.githubusercontent.com/9629102/34010584-45afde22-e0db-11e7-96f1-30c33a14d7de.png)
2. create a form with custom amount enabled, and a minimum of 1.00
3. attempt to give $3.00 on the front end.
4. You'll get an error saying that the minimum is 100.00

**Comment by Benunc** [comment]
Related: if you make the form admin-defined recurring with that decimal configuration, and a multilevel form, you get this monstrosity just below the levels:

![screen shot 2017-12-14 at 5 20 48 pm](https://user-images.githubusercontent.com/9629102/34017308-3b659278-e0f3-11e7-9eec-95b466077d91.png)

**Comment by DevinWalker** [comment]
I think that may be an issue with Recurring there @Benunc - we'll fix that up too.
