### ISSUE TITLE
Create new page for Give Profile Editor on Fresh install

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2552]
## Issue Overview
Create a new page called `Give Profile Editor` when Give on freshly installed like we do it from 

- Donation Confirmation — Donation Success Page
- Donation Failed — Donation Failed Page
- Donation History — Donation History Page

![image](https://user-images.githubusercontent.com/22215595/34203772-4aa8fdd4-e5a2-11e7-9379-f2d6f3b521ed.png)

![image](https://user-images.githubusercontent.com/22215595/34203836-75e4a412-e5a2-11e7-8658-85f4734c62f4.png)

![image](https://user-images.githubusercontent.com/22215595/34203852-86537684-e5a2-11e7-9e1f-97f126975ddb.png)

**Comment by akashsonic** [comment]
Working on this functionality.

**Comment by DevinWalker** [comment]
@akashsonic this is still up for debate whether we're going to create this page. I'm leaning towards no because most sites don't register users when donating therefore creating a default page wouldn't be applicable to most of our users.

**Comment by akashsonic** [comment]
@DevinWalker Okay no problem, checking on other issues.

**Comment by kevinwhoffman** [comment]
Closing for now as I agree with @DevinWalker's rationale. We should only add the minimum pages necessary to make Give functional and allow the user to add further pages to their site based on their needs.
