### ISSUE TITLE
Admin Column: If no goal is set for form show "n/a" rather than "0.00"

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#256]
It's better to show "n/a" aka "Not applicable" rather than "0.00" if a form doesn't have a set goal.

![9-16-2015 3-09-17 pm](https://cloud.githubusercontent.com/assets/1571635/9919951/133cfe98-5c85-11e5-90be-41b88c32d9f7.png)

**Comment by mathetos** [comment]
I'd even just say "No Goal". We have the space for it. I always feel that N/A isn't descriptive enough.

**Comment by DevinWalker** [comment]
Oh you one upper you... :+1:

**Comment by DevinWalker** [comment]
Oops, don't close!
