### ISSUE TITLE
[Give 2.0] Timeouts on Donations Listing Page with Caching Disabled

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2566]
## Issue Overview
I tested the caching option within my local dev environment and the results were varying. With caching enabled things to work pretty quickly but with it disabled you receive timeouts and errors loading.

**See video:** https://goo.gl/J9oRq1

![2017-12-21_01-17-55](https://user-images.githubusercontent.com/1571635/34248977-cdd03d72-e5ec-11e7-9506-32623202510b.png)

## Expected Behavior
Caching works either enabled or disabled. In 1.8.* with _no caching_ the plugin loads these pages on PHP 5.3 - 7.1.

## Current Behavior
 If you upgrade to Give 2.0 and disable caching they no longer load.

**Comment by ravinderk** [comment]
@DevinWalker Let do call regarding this.
