### ISSUE TITLE
Disable Payment Gateway Settings when Payment Gateways are disabled.

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2576]
## Issue Overview
I've noticed that, if the default payment gateways are disabled then also, we can still access those payment gateway settings. This issue is with default payment gateways only and not with addon gateways.

Please check the below screenshot for more info.
![image](https://user-images.githubusercontent.com/1852711/34332701-086450fc-e95a-11e7-96a7-75b7d12e6f8e.png)

## Expected Behavior
Payment Gateway Settings tab should not load if payment gateway is disabled.

## Current Behavior
Payment Gateway Settings tab is loaded which is of no use even when the payment gateway is disabled.

## Steps to Reproduce (for bugs)
1. Install Give Core 
2. Go to Donations > Settings > Payment Gateways
3. Disable Offline Donation and PayPal Standard
4. You will notice that Offline Donation and PayPal Standard settings are still visible, editable and can be saved.

## WordPress Environment
<details>

### WordPress Environment ###

Home URL: http://give20.local
Site URL: http://give20.local
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Inaccessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give20.local
TLS Connection: 
TLS Connection: 
Server Info: nginx/1.10.1
PHP Version: ❌ 5.3.29 - We recommend a minimum PHP version of 5.6. See: PHP Requirements in Give
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.2h - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instruction✔New Donor Register✔Donor Register✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give20.local/donation-confirmation/
Failure Page: http://give20.local/donation-failed/
Donation History Page: http://give20.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Admin Email Notifications: Disabled
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.3.5
Give - Per Form Emails: ❌ Unlicensed – by WordImpress – 1.0.2
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.5

### Other Active Plugins ###

Give - Payfast Payment Gateway: by WordImpress – 1.0

### Inactive Plugins ###

Give - PayPal Pro Gateway: by WordImpress – 1.1.4
Give - Stripe Gateway: by WordImpress – 1.5.1
WooCommerce PayFast Gateway: by WooCommerce – 1.4.7

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by raftaar1191** [comment]
Nope, I don't think so. It's good like it is

**Comment by DevinWalker** [comment]
I don't think we want to toggle the gateway settings based on whether it's enabled or not. This would mean users would have to enable the gateway in order to configure it. I think rather having the ability to enable/disable the gateway _beneath_ its settings would be helpful. Closing this one out. Thanks for the suggestion.
