### ISSUE TITLE
refactor: Improve give_locate_template

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2577]
## Issue Overview

In `give_get_template` fn we are passing `$template_path` and `$default_path` path to `give_locate_template` fn but it only accept `boolean` as second and third param.We can improve this fn to handle default path logic. 

This will be helpful to Give addon developers if this `give_locate_template` fn locates and load template on basis of fn arguments.

For ref: https://github.com/WordImpress/Give/blob/f5bc216de9a8fb778014ab2b9e6e8dea22580d9b/includes/template-functions.php#L54

**Comment by DevinWalker** [comment]
@ravinderk which milestone?

**Comment by raftaar1191** [comment]
milestone 2.0
