### ISSUE TITLE
User link on Transactions Page Should goto Donor's Page

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#258]
*Not sure how long this has been there, but noticed as of https://github.com/WordImpress/Give/commit/45936cac9193e1c883d176d1152fa57acacf8495*

When clicking the "guest" link on a transaction apparently it filters the Transaction view to show ONLY the donations made from that email address.

The problem is that there is no other visual cue that that's the behavior, and there is no intuitive way to go back to ALL Transactions except to click "Transactions" from the left-hand menu, which is really unintuitive.

I'd suggest one of the following:
* Change the title of the page when filtered to say "Transactions by email@address.com"
* Have that link just go directly to the Donor page of that user.

I think I prefer the second since clicking on a user name suggests wanting to see information about the user and all the transactions will show on the donor page as well.

**Comment by DevinWalker** [comment]
#2 sounds good to me

**Comment by mathetos** [comment]
Nice. I think that's a good move that EDD should follow.

**Comment by DevinWalker** [comment]
@mathetos they already had a PR for it actually.
