### ISSUE TITLE
[Give 2.0] WordPress Default Admin Email Goes Blank

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2581]
## Issue Overview
I've noticed that on performing new donation with create an account option selected, admin receives a WordPress default email which is empty.

![image](https://user-images.githubusercontent.com/1852711/34356013-dc41c516-ea5f-11e7-8a29-93844080f797.png)

## Expected Behavior
New User Registration email should have some content.

## Current Behavior
Currently, there is no content in New User Registration email which sends out to admin.

## Steps to Reproduce (for bugs)
1. Create a Donation Form with Registration Enabled.
2. Perform a donation by checking `Create an Account` checkbox.
3. Check email with subject `New User Registration`
4. You will notice the email is empty

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>

### WordPress Environment ###

Home URL: http://give20.local
Site URL: http://give20.local
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Inaccessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give20.local
TLS Connection: 
TLS Connection: 
Server Info: nginx/1.10.1
PHP Version: ❌ 5.3.29 - We recommend a minimum PHP version of 5.6. See: PHP Requirements in Give
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.2h - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instruction✔New Donor Register✔Donor Register✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give20.local/donation-confirmation/
Failure Page: http://give20.local/donation-failed/
Donation History Page: http://give20.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Admin Email Notifications: Disabled
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Per Form Emails: ❌ Unlicensed – by WordImpress – 1.0.2
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.5

### Inactive Plugins ###

Give - Fee Recovery: by WordImpress – 1.3.5
Give - Payfast Payment Gateway: by WordImpress – 1.0
Give - PayPal Pro Gateway: by WordImpress – 1.1.4
Give - Stripe Gateway: by WordImpress – 1.5.1
Redis Object Cache: by Till Krüss – 1.3.5
WooCommerce PayFast Gateway: by WooCommerce – 1.4.7

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by mehul0810** [comment]
I have investigated more into this issue and noticed that there is some confusion with the email subject naming and the email notification type naming. Please check below screenshot for more details.

![image](https://user-images.githubusercontent.com/1852711/34356896-1cb1c0a8-ea68-11e7-9f9f-a73d0e68c413.png)

**Comment by DevinWalker** [comment]
It looks like that email is missing default content in 2.0+ 

Nice catch @mehul0810

**Comment by akashsonic** [comment]
@DevinWalker I have fixed this issue in PR [#2590](https://github.com/WordImpress/Give/pull/2590)
