### ISSUE TITLE
Admin should able to restart the upgrade if it's get fail 

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#2585]
## Issue Overview
Admin Must able to reset the upgrade if for some reason the upgrade gets fails  in 2.0 Version

**Comment by DevinWalker** [comment]
@raftaar1191 with the background updates now merged were you able to get them to stop? I think you need to provide more info for this issue. Like a video on how you were able to get the upgrade to fail. Please provide that and I'll reopen if need be.
