### ISSUE TITLE
Improve "Goal" column on form listing page

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2586]
## Issue Overview
Right now the goal field isn't very informative. It would be more informative to display the goal progress for the form:

![goal-progress-column](https://user-images.githubusercontent.com/1571635/34366576-4faa4acc-ea52-11e7-893e-74c5fc6dc9b4.png)

## Feature Request
1. Change "Goal" column to "Goal Progress"
2. Forms with goals will display a progress bar based on amount raised _or_ total donations received. As well as percentage.
3. Sorting the column will need to be refactored to be based on the goal _percentage_ achieved. Meaning, regardless of the goal display type (amount, number of donations, or percentage) all forms will be sorted by percentage completed.

**Comment by raftaar1191** [comment]
Related Issues: https://github.com/WordImpress/Give/issues/2586

**Comment by kevinwhoffman** [comment]
I really like this idea and have a few suggestions:

- **Reduce the height of the progress bar.** The bar feels too chunky. It is a relatively heavy visual element already given its accent color, and with several goals lined up, the progress bars could begin to dominate the page. My adjusted height in the mockup below is `8px` tall.
- **Right-align the goal column.** By aligning this column to the right as shown in the mockup below, the progress numbers become easier to scan and compare goal progress from one form to the next.
    - Side note: We should consider right-aligning all numerical columns for easier scanning (while accounting for RTL settings).
- **Keep the "Goal" column name.** With these updates, it's very clear that this column shows goal progress so lengthening the column name to display "Goal Progress" is not necessary.
- **Do not include suffixes (e.g. raised, donations, etc.).** Whether it's percentage, currency, or number of donations, the type of goal can be inferred by the `%` symbol, `$` currency symbol, or lack of symbol. By removing the suffixes, we keep the numbers aligned flush right and users can more easily scan the column with less clutter.
- **Link the goal total (e.g. $5,000) to the Donation Goal tab of the form editor.** Other columns in the table such as Donations and Income are linked to relevant destinations, so it follows that clicking the goal total would lead to the Donation Goal tab where that total is set. This can be accomplished by adding `give_tab=donation_goal_options` to the edit post URL.

![2586-goal-column](https://user-images.githubusercontent.com/1938671/34544647-8b004e14-f0b5-11e7-87e3-a3cf4967ba56.png)
