### ISSUE TITLE
Offline Donation Enhancement

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#26]
ENVIRONMENT:

__________________________________________
FEATURE REQUESTS:
On the offline donation option it would be nice to collect the donors address, email, and phone number so we can follow-up with the donor as a reminder about sending their donation or if the check get's lost.
__________________________________________
GENERAL FEEDBACK:

REF:345giveReagan!fgh15

**Comment by mathetos** [comment]
___________________________________
This was generated by our feedback form. 
____________________________________

I think this is already in the works including customizing the email in one form or another, correct @DevinWalker ?

**Comment by DevinWalker** [comment]
I'm committing code that provides an option for you to include the billing information fieldset within offline donations. This includes all applicable information (besides phone #) and satisfies this enhancement request.
