### ISSUE TITLE
images not showing in pdf and email receipts

### ISSUE THREAD

**Issue by fatsandrew7** [WordImpress/Give#2601]
when using the give wp settings to select a logo to appear in the email and pdf receipts, the logo is omitted and does not show.

normally, this is a limitation of email clients not being able to read the sourced image, however, in this case the code is completely omitted where the image is placed.

**Comment by DevinWalker** [comment]
Hey @fatsandrew7 this may be due to a server configuration that the images are not rendering. Please contact support for additional assistance unless you have more specifics on this being a bug: https://givewp.com/support/

**Comment by fatsandrew7** [comment]
@DevinWalker thanks for the reply. it actually turns out to be the lack of an ssl certificate on the dev site.

i did submit a ticket -- thanks.
