### ISSUE TITLE
feat(admin-form): copy form shortcode to clipboard via button

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2602]
## User Story

As a user, I want a quick and clean way to copy a shortcode so that the UI is less cluttered and it's easier to copy the shortcode in a single click.

## Acceptance Criteria
- [x] clipboard.js has been registered as an npm dependency.
- [x] A `ShortcodeButton` JS class has been created which imports `ClipboardJS` as a module.
- [x] The button text reads `Copy Shortcode`.
- [x] The tooltip reads `[give_form id="#"]`.
- [x] On click, the shortcode is copied to clipboard and the tooltip text is updated to read `Copied!`.
- [x] One mouseout, the button resets to its initial state.
- [x] The shortcode field in the admin forms table has been replaced with the new button.
- [x] The shortcode field in the single form edit screen has been replaced with the new button.

## Visuals 

Visual reference of the shortcode button in WPBR:

![image](https://user-images.githubusercontent.com/1938671/42069626-cd7dd39c-7b20-11e8-9be0-c57301110d0e.png)

Replace these shortcode fields with new shortcode button:

![image](https://user-images.githubusercontent.com/1852711/34511079-26180dec-f07f-11e7-9284-5e52cb59a880.png)

![image](https://user-images.githubusercontent.com/1852711/34511163-9f504b48-f07f-11e7-8d7a-f5c48b6add89.png)

## Related

https://clipboardjs.com/

**Comment by kevinwhoffman** [comment]
@Sidsector9 I have implemented this functionality in WP Business Reviews using clipboard.js and Hint.css. Use the work done in WPBR as your starting point.

- [PHP to generate the button](https://github.com/WordImpress/wp-business-reviews/blob/develop/includes/admin/class-admin-review-columns.php#L161-L167)
- [ShortcodeButton JS class](https://github.com/WordImpress/wp-business-reviews/blob/develop/assets/src/js/shortcode-button.js)

Let's do a call on this when you are ready to begin.
