### ISSUE TITLE
[Give 2.0] Email send on page refresh

### ISSUE THREAD

**Issue by jaydeeprami** [WordImpress/Give#2606]
## Issue Overview

- Email notification sends when refreshing browser.

See video: https://screencast-o-matic.com/watch/cFVfXYoe7q

## Expected Behavior

- Email should not sent on page refresh

## Current Behavior

- Email sent on page refresh after sending test email.

## Steps to Reproduce (for bugs)

1. Go to Settings > Email Settings >
2. Send Test email
3. Refresh same page
4. Check email

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Copy and paste the system Info report from **Donations > Tools > System Info** in WordPress admin here.
```
</details>

**Comment by DevinWalker** [comment]
Good find and fix @jaydeeprami
