### ISSUE TITLE
[Give 2.0] Upgrade routine stuck at 0%

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2610]
## Issue Overview
@Benunc has provided us with a database he was unable to upgrade. I was able to reproduce as well:

![2018-01-04_11-16-34](https://user-images.githubusercontent.com/1571635/34580159-cdc28290-f140-11e7-9b63-535a6d1f6f6f.gif)

## Expected Behavior
Upgrade routines don't get stuck, ever.

## Current Behavior
This upgrade routine is stuck.

## Possible Solution
We should provide a way that admins can escape getting stuck like this if it happens. @ravinderk I'd like to discuss with you.

## Steps to Reproduce (for bugs)
* I will provide you the duplicator package

**Comment by ravinderk** [comment]
@DevinWalker 
Ajax secure does not work on `local by flywheel`. Please read this thread http://local.getflywheel.com/community/t/make-https-work-from-locals-localhost/327/3

I am getting this response when doing db upgrade ajax post request.
```
WP_Error Object
(
    [errors] => Array
        (
            [http_request_failed] => Array
                (
                    [0] => cURL error 7: Failed to connect to collegiateabbey.test port 443: Connection refused
                )

        )

    [error_data] => Array
        (
        )

)
```

But I added a fix to prevent DB upgrade from running by cron.

@Benunc Can you reproduce this on live staging site with or without SSL.

@DevinWalker @Benunc Cron will work fine now but make sure ajax mus work fine too.

**Comment by Benunc** [comment]
On a live staging site the update runs as expected.

**Comment by DevinWalker** [comment]
@ravinderk I think to close this one out then we have to check that Admin AJAX is accessible before allowing to run the upgrade:

![2018-01-05_09-35-49](https://user-images.githubusercontent.com/1571635/34620897-e689d9e8-f1fb-11e7-98f8-503869a7bca6.png)

Otherwise the site gets stuck updating at 0% and we don't want that to happen.
