### ISSUE TITLE
[Give 2.0] Adding additional parameter with ID returns error in /donations/ endpoint

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2633]
## Issue Overview
I've noticed that /donations/ endpoint returns error when an additional parameter with name `id` is passed. I've tried passing any other additional parameter with different name but that doesn't return any error. Only the parameter with name `id` returns error.

If `id` is not the supported parameter with /donations/ endpoint then it should show proper message so wherever the endpoint is used, developer can show appropriate message based on the response.

![image](https://user-images.githubusercontent.com/1852711/34673313-d3a627ec-f4a7-11e7-922e-be7cf537e37b.png)

## Expected Behaviour
There should not be any error.

## Current Behaviour
Displays error which can disturb any existing functioning with api endpoint.

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>

### WordPress Environment ###

Home URL: http://give20.test
Site URL: http://give20.test
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Inaccessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give20.test
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: ❌ 5.3.29 - We recommend a minimum PHP version of 5.6. See: PHP Requirements in Give
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.2h - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New Donor Registration✔Donor Register✔Email access
Upgraded From: 2.0.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give20.test/donation-confirmation/
Failure Page: http://give20.test/donation-failed/
Donation History Page: http://give20.test/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, PayPal Standard
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: IPN received for #54 ( 75L63342RL5674944 ) on 01/03/2018 at 10:44. Status VERIFIED
Admin Email Notifications: Disabled
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.2.4

### Inactive Plugins ###

Give - Currency Switcher: by WordImpress – 1.0.0
Give - Email Reports: by WordImpress – 1.0.2
Give - Fee Recovery: by WordImpress – 1.3.7
Give - Gift Aid: by WordImpress – 1.1
Give - PayFast Payment Gateway: by WordImpress – 1.0
Give - PDF Receipts: by WordImpress – 2.2.2
Give - Recurring Donations: by WordImpress – 1.5.2
Give - Tributes: by WordImpress – 1.3.3
Gutenberg: by Gutenberg Team – 1.9.1

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment]
@mehul0810 This will generate a warning in `debug.log` if `xdebug` is not enabled.

Thank you for catching that.

For ref: https://github.com/WordImpress/Give/commit/75e7e6c1c8c73d648267b2078ec04316ba489d6d
