### ISSUE TITLE
Server side validation errors don't reopen modal or slide down panel 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#264]
_Scenario:_ If a user attempts to donate using a Give form in modal view and there is an error returned back from the payment gateway 

_Problem:_ The user has no idea the error occurred without clicking back into the modal

![9-16-2015 5-53-48 pm](https://cloud.githubusercontent.com/assets/1571635/9922375/7ea433a6-5c9c-11e5-8c5e-bcb4e90e07b5.png)
![9-16-2015 5-53-42 pm](https://cloud.githubusercontent.com/assets/1571635/9922374/7ea0a042-5c9c-11e5-82ae-4c052ce58f56.png)

**Comment by pryley** [comment]
Related: Perhaps it would be helpful to perform additional initial cc validation (cvv/exp/name) on the client side using the stripe.payments script.

Another thing I've noticed on server validation is when actionable errors are returned, it blanks out the entire form so you have to re-enter everything again.

**Comment by DevinWalker** [comment]
I noticed the same issue with blanking fields. That can be annoying for users. I agree we need some client side validation. Is stripe payments script you mentioned something specific only to the Stripe gateway or can that be used cross-gateway?

**Comment by DevinWalker** [comment]
Bumping milestone...

**Comment by pryley** [comment]
Oh, I meant the jquery.payment script (it's by the stripe team) that Give uses to validate the CC number also offers basic validation logic for cvc and expiry.

E.g. http://stripe.github.io/jquery.payment/example/

**Comment by DevinWalker** [comment]
Gotcha

**Comment by DevinWalker** [comment]
Reported here as well: https://givewp.com/support/ticket/reveal-upon-click-modal-window-upon-click-hide-errors/#post-5231

**Comment by DevinWalker** [comment]
@pryley  "Perhaps it would be helpful to perform additional initial cc validation (cvv/exp/name) on the client side using the stripe.payments script." 
- I totally agree...

**Comment by DevinWalker** [comment]
I'm going to see if I can get this into 1.3.1
