### ISSUE TITLE
Quick Enable/Disable of new Email API not working properly

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2649]
## Issue Overview
I've noticed that enabling/disabling emails for more than one email using Quick Enable/Disable option under `Settings > Emails` is not working properly.

**Please check the GIF for more details:** ![Gif](http://g.recordit.co/FGEpj2HNm8.gif)

**Note:** I think this issue is a minor one. Hence, we can solve it after 2.0 release. 

## Expected Behavior
Quick enabling and disabling for more than one email using new email api should work properly.

## Current Behavior
Quick enabling and disabling more than one email is not working properly.

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>

### WordPress Environment ###

Home URL: http://give20.test
Site URL: http://give20.test
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give20.test
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: ❌ 5.3.29 - We recommend a minimum PHP version of 5.6. See: PHP Requirements in Give
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.2h - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New Donor Registration✔Donor Register✔Email access✔Daily Email Report❌Weekly Email Report✔Monthly Email Report
Upgraded From: 2.0.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give20.test/donation-confirmation/
Failure Page: http://give20.test/donation-failed/
Donation History Page: http://give20.test/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, PayPal Standard
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: IPN received for #54 ( 75L63342RL5674944 ) on 01/03/2018 at 10:44. Status VERIFIED
Admin Email Notifications: Disabled
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Email Reports: ❌ Unlicensed – by WordImpress – 1.0.2
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.2.3

### Inactive Plugins ###

Give - Currency Switcher: by WordImpress – 1.0.0
Give - Fee Recovery: by WordImpress – 1.3.7
Give - Form Field Manager: by WordImpress – 1.2.4
Give - Gift Aid: by WordImpress – 1.1
Give - Manual Donations: by WordImpress – 1.2.2
Give - PayFast Payment Gateway: by WordImpress – 1.0
Give - Recurring Donations: by WordImpress – 1.5.3
Give - Tributes: by WordImpress – 1.3.4
Gutenberg: by Gutenberg Team – 1.9.1
Ninja Forms: by The WP Ninjas – 3.2.8

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment]
@mehul0810 Ajax response will be quick because there is now heavy calculation exist. You will get the result in `200 ms`.

You are able to produce this issue because of this https://github.com/WordImpress/Give-Email-Reports/pull/25#issuecomment-356895681. Let me know if you can reproduce this now.

**Comment by DevinWalker** [comment]
Yeah I don't think this is a big issue. Why does it take so long @ravinderk? What's the heavy calculation? Shouldn't it just be toggling an enable/disable option?

**Comment by mehul0810** [comment]
@ravinderk I can't reproduce this issue now. I've tested on local as well as using Live Link and it is processing much faster. 

@DevinWalker The heavy calculation is in https://github.com/WordImpress/Give-Email-Reports/pull/25#issuecomment-356895681 due to which the current issue got reproduced which is not sorted.
