### ISSUE TITLE
Remove custom amount label from set donation {donation} tag

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#2653]
## Issue Overview

Related to #2161 

The custom amount level should not be appended to a set donation's `{donation}` tag in emails, or in the Donation Receipt shortcode output.

## Expected Behavior
Unless customized, I wouldn't want to display the text on the front end of a site at all (current behavior), and I don't think there should be any reason that it is ever appended to the donation title in a tag, or in the Donation receipt shortcode.

## Current Behavior
The custom amount text is appended to the Form title on the {donation} tag, if it has been customized, and just the words "Custom Amount" if it hasn't been customized.
![screen shot 2018-01-11 at 5 57 32 pm](https://user-images.githubusercontent.com/9629102/34851688-2d40fad6-f6f9-11e7-929b-136a260bdc37.png)
(name of the form is "set with Custom Amount")

![screen shot 2018-01-11 at 5 57 22 pm](https://user-images.githubusercontent.com/9629102/34851696-3f119a36-f6f9-11e7-8ff2-1e059a2aaa2a.png)
There's no need to put "custom amount" on that table. I don't even think it needs to be put there for customized text.

## Possible solution

If it is a set donation form, the {donation} tag always and only gets the Form Title on the {donation} tag, and in the shortcode output.

## Steps to Reproduce (for bugs)
1. Create a set level donation form
2. Enable custom amounts
3. Ensure that the {donation} tag is in use on the email receipt
4. Submit a test donation and check the email.

On both the donation receipt {give_receipt] shortcode, and the email, the form title has either "custom amount" (if it's not custom text added) or the custom message that users can add on the back end of the site. 

## Related Issues and/or PRs
#2161 

## Todos
- [ ] Tests

**Comment by Benunc** [comment]
User following up on this issue.

**Comment by DevinWalker** [comment]
@Benunc scheduled this one for the next point release
