### ISSUE TITLE
Currency Position dosn't update when you change Currency (you have to save)

### ISSUE THREAD

**Issue by gingerling** [WordImpress/Give#2667]
## Issue Overview
On General > Currency menu page, if you change the currency from eg. Dollars to Pounds, the currency mentioned in the Currency Position dropdown below does not update until you save the page.

## Expected Behavior

You change currency and the currency position dialogue changes to correct currency right away

## Current Behavior

It dosn't change

## Steps to Reproduce (for bugs)
1. Go to On General > Currency menu page
2. Change the currency from eg. Dollars to Pounds
3. Check currency in currency position is still $ not £ (Even if you click on the dialogue)
4. Save page
5. It is now £ as is correct.

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Copy and paste the system Info report from **Donations > Tools > System Info** in WordPress admin here.
```
</details>

**Comment by raftaar1191** [comment]
Working on this
