### ISSUE TITLE
[give_receipt] attributes do not work as expected

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#267]
The following attributes do not work as expected. They each show on the receipt regardless of adding them as true/false

- [x] price 
- [x] date 
- [x] payment_key
- [x] payment_method
- [x] payment_id

**Comment by mathetos** [comment]
Tested locally, on latest from Github (not repo version 1.2). Did a test donation to view receipt. Changed the attributes then did another test donation. All while logged in. Didn't test from the email receipt link.

**Comment by DevinWalker** [comment]
Bumped up to 1.3.1 milestone

**Comment by mathetos** [comment]
Nice!
