### ISSUE TITLE
Fix stalled upgrade process

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2671]
## Issue Overview

We found that in some cases upgrade getting remove from background process batch without setting itself to complete. It will create an issue when another upgrade depends on it. We can prevent stalled updates by handle this case in the core.

## Expected Behavior

The upgrade process should run without stalling.

## Current Behavior

Sometimes upgrade stalled.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by lunarthegrey** [comment]
@ravinderk I ran into this issue when updating the database for 2.0. What would be the proper solution for this? Wait until a fix is released and update the plugin? Mine is currently stuck at 72%.

**Comment by ravinderk** [comment]
@lunarthegrey Thank you for reaching us. We are developing a new feature for upgrading process, so you will not face this kind of issue in future. Wait for `2.0.1`. We will release it soon.

If you have staging site then please check the latest code (https://github.com/WordImpress/Give/archive/release/2.0.1.zip) and let us know

For ref: https://github.com/WordImpress/Give/issues/2676

**Comment by DevinWalker** [comment]
Similar issue as above. - This was closed as the pause / restart feature is now implemented. It's not recommended to actually _use_ at all unless you are _positive_ there's an issue with the update. If there is an issue with the update please implement your backup and contact us on https://wordpress.org/support/plugin/give
