### ISSUE TITLE
fix(notice): notify donor if form is submitted with unchecked Terms

### ISSUE THREAD

**Issue by marutim** [WordImpress/Give#2684]
## Issue Overview
If you have terms and condition enabled and an user tries to donate without checking the checkbox. It does not throw an alert. The donation button freezes and donation does not go through but this should also throw an alert suggesting the user to check the checkbox to continue the donation.

## Related helpscout issue
https://secure.helpscout.net/conversation/508615593/13300/?folderId=1457790

## WordPress Environment
<details>
### WordPress Environment ###

Home URL: http://wp-give.test
Site URL: http://wp-give.test
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: wp-give.test
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Flywheel/4.1.0
PHP Version: 5.6.20
PHP Post Max Size: 1,000 MB
PHP Time Limit: 300
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.2k - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.36
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: 1.8.19
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://wp-give.test/donation-confirmation/
Failure Page: http://wp-give.test/donation-failed/
Donation History Page: http://wp-give.test/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card, PayPal Standard
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.4
Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.2.5
Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.3
Give - PayPal Pro Gateway: ❌ Unlicensed – by WordImpress – 1.1.4
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.2.4
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.5.4
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 1.5.2
Give - Tributes: ❌ Unlicensed – by WordImpress – 1.3.6
Give - Zapier: ❌ Unlicensed – by WordImpress – 1.1.2

### Other Active Plugins ###

Debug Bar: by wordpressdotorg – 0.9
Debug Bar Post Meta: by whyisjake – 0.5.4
Duplicate Post: by Enrico Battocchi – 3.2.1
Email Cop: by Ashfame – 0.1.1
Give - Hook Helper: by Ravinder Kumar – 1.0

### Inactive Plugins ###

Automatic Responsive Tables: by Andrew Rockwell – 1.2
Give - AmeriCloud Payments: by AmeriCloud Solutions, Inc. – 1.2.0
Give - Authorize.net Gateway: by WordImpress – 1.3.3
Give - Braintree Gateway: by WordImpress – 1.1.1
Give - CCAvenue Gateway: by WordImpress – 1.0
Give - Constant Contact: by WordImpress – 1.2.1
Give - ConvertKit: by WordImpress – 1.0.1
Give - CSV Toolbox: by WordImpress – 1.0
Give - Email Reports: by WordImpress – 1.0.2
Give - GoCardless Gateway: by WordImpress – 1.1.1
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.1
Give - MailChimp: by WordImpress – 1.3.6
Give - Per Form Emails: by WordImpress – 1.0.2
Give - Per Form Gateways: by WordImpress – 1.0.1
Give - Per Form User Role Assigner: by Matt Cromwell – 1.0
My Custom Functions: by Arthur Gareginyan – 4.12
WP Filters Extras: by BeAPI – 1.0.2

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by mathetos** [comment]
@marutim Can you still replicate this issue with Give 2.0.6? Please confirm when you can.

**Comment by marutim** [comment]
@mathetos Tested it with Give 2.0.6. I can not replicate it. It works as intended.

**Comment by ravinderk** [comment]
@DevinWalker closing this issue in favor of https://github.com/WordImpress/Give/issues/2684#issuecomment-374512317

**Comment by mathetos** [comment]
Awesome, thanks for the confirmation @marutim
