### ISSUE TITLE
Custom Slug

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#27]
ENVIRONMENT:

__________________________________________
FEATURE REQUESTS:
I know we can customize the end of the slug (e.g. domain.com/donation/custom-slug), but it wwould be nice if in the general settings or upon activation we could customize the /donation/ part or choose from a preset list. Some of the preset options could be.

donation
give
donate
support
fundraiser
fundraising
fundraise
fund
__________________________________________
GENERAL FEEDBACK:

REF:345giveReagan!fgh15

**Comment by DevinWalker** [comment]
Hmm. This is possible right now, but having them change the slug at activation is maybe going too far.

**Comment by mathetos** [comment]
I don't think he means the form slug, which is accessible, but the root `/donation/` url. Meaning instead of `\donation\form-slug` they could have `\campaigns\form-slug`

**Comment by DevinWalker** [comment]
@mathetos that's possible right now, there's just no convenient UI. It's done programmatically.

**Comment by DevinWalker** [comment]
I don't like the idea of adding a UI for this... would cause more support and programmatically is cleaner.

**Comment by DevinWalker** [comment]
@mathetos assigning to you for the doc

**Comment by mathetos** [comment]
OK, I want to write a doc on "Give Globals" with this one included.

**Comment by DevinWalker** [comment]
Here's a good reference from EDD https://easydigitaldownloads.com/docs/section/developer-api/php-constants/

**Comment by mathetos** [comment]
:+1:

**Comment by mathetos** [comment]
Done: https://givewp.com/documentation/developers/give-php-constants/

Looks as if we don't currently have `GIVE_MENU_POSITION` . I like the way we implemented that in Maps Builder, with an additional setting in the Advanced tab. Might be nice to do that with Give as well.
