### ISSUE TITLE
Don't use price fallback for amounts because often it's confusing and redundant

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2700]
## Issue Overview
Most often I see admin create price based multi-level forms. The usage of `give_get_price_option_name()` within `give_get_donation_form_title()` uses the "fallback" of appending the donation level price to various places:

1.  On the donation receipt

![2018-01-23_16-54-48](https://user-images.githubusercontent.com/1571635/35308784-26f922a2-005e-11e8-9332-4517b0805154.png)

2. In the email to donors

![2018-01-23_16-59-10](https://user-images.githubusercontent.com/1571635/35308908-be448b92-005e-11e8-94ae-6bbfe89153a5.png)

3. In wp-admin
![2018-01-23_16-53-08](https://user-images.githubusercontent.com/1571635/35308746-083fec1a-005e-11e8-99cb-b7fead0a3d2d.png)

With additional add-ons like Fee Recovery and FFM, and now Currency Switcher there are additional pricing fields added. Having this field displayed can become confusing:

![2018-01-23_16-58-48](https://user-images.githubusercontent.com/1571635/35308894-b16fc738-005e-11e8-82eb-8c8531bf4df4.png)

## Possible Solution
I suggest we only display the content if the field label has text like for that level. For instance if I gave "Save the Whales - Captain Level" that would be more relevant.

Cleaner wp-admin:

![2018-01-23_16-52-51](https://user-images.githubusercontent.com/1571635/35308951-e93d767e-005e-11e8-99b3-944bbb8f6b0b.png)

Better receipts:

![2018-01-23_17-11-12](https://user-images.githubusercontent.com/1571635/35309272-6f19ebb4-0060-11e8-956f-eada5814bee6.png)

**Comment by mathetos** [comment]
I think you're touching on a real pain-point here. I don't get a lot of feedback on this in Support; but every time I do a multi-level donation myself I get confused by the results on the receipt page. 

Early on with Give, users continually told us that they wanted to know what level the donor picked. We got that feedback continually. So I don't think we should make it harder to show the level in any way. But the examples you show above are pure confusing. Did the donor give $50 or $51.80? It's hard to tell...

The total amount donated has to be primary, that's what is tax deductible. That's what donors care about. Everything else is extra and should be given less attention.

Just chiming in with agreement that it's a problem. Your solution works I think.

**Comment by DevinWalker** [comment]
This is definitely just a "quick fix" before we rethink how to really improve the receipt page, and entire system as a whole, in future versions.
