### ISSUE TITLE
Resolve failing unit tests in 2.0.1

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2702]
## Issue Overview
![2018-01-23_17-54-37](https://user-images.githubusercontent.com/1571635/35310485-820dabce-0066-11e8-8867-6024d6eb4477.png)

## Expected Behavior
Unit tests pass

## Current Behavior
They are not passing

## Possible Solution
Resolve array string conversion error:
![2018-01-23_17-50-02](https://user-images.githubusercontent.com/1571635/35310497-95740ed8-0066-11e8-944f-1cc4f587add0.png)

**Comment by ravinderk** [comment]
Fixed: https://github.com/WordImpress/Give/compare/13518527d887...24e204a9273e
