### ISSUE TITLE
Don't burden websites that have already updated fine with another db upgrade routine

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2703]
## Issue Overview

On several websites I noticed that upgraded fine via 2.0.0 I noticed that in 2.0.1 we are asking for more upgrade routines to correct past issues. The problem is these issues are not present on this site. 

We should not burden sites that have already upgraded properly with the process of performing another backup and clicking upgrade again if their site has pass all the "health checks".

We need to always be thinking about our users perception of our plugin and delight them rather than present them with multiple upgrade routines asking for backups if it's not required.

## Expected Behavior
Users who upgraded fine are not burdened with an upgrade routine again.

## Current Behavior
In 2.0.1, an upgrade routines is asked even if the db upgraded fine. 

## Possible Solution

Check the status of the website upgrades. If an issue is detected then show the upgrade process. Otherwise skip it.

## Steps to Reproduce (for bugs)
1. Install 2.0.0 and add some forms and donations
2. Update to 2.0.1
3. Upgrade routines are shown

![2018-01-23_21-52-18](https://user-images.githubusercontent.com/1571635/35316668-c7199c34-0087-11e8-8703-ce5d91f9f65d.png)

**Comment by ravinderk** [comment]
@DevinWalker Most users did not take a backup before updating there plugin. After updates broke in `2.0`, instead of backup old data they started using `2.0` data with `1.8.19` which leads to storing data in the old table instead of new. We also have to take his into consideration, so in `2.0.1` we need DB updates.

**Comment by DevinWalker** [comment]
Thanks for explanation @ravinderk - closing
