### ISSUE TITLE
{billing_address} showing up blank on PDF Receipts

### ISSUE THREAD

**Issue by mjmiller21** [WordImpress/Give#2707]
## Issue Overview
Billing address tag has recently started showing up blank on the PDF Reciepts using Paypal Standard. This is a new issue as the billing address tag was populating receipts on a transaction dated Jan 6 2018

## Expected Behavior
Billing address tag should populate billing address on PDF Receipts

## Current Behavior
Currently Billing address is populated as blank on the PDF reciepts. 

## Steps to Reproduce (for bugs)
WWW.LAYUP.CA/DONATE
- I've enabled test donations to allow testing &r a dummy receipt to be created. 

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Home URL: |   | http://www.layup.ca
-- | -- | --
Site URL: |   | http://www.layup.ca
WP Version: |   | 4.9.2
WP Multisite: |   | –
WP Memory Limit: |   | 768 MB
WP Debug Mode: |   | –
WP Cron: |   |  
Language: |   | en_US
Permalink Structure: |   | /%year%/%monthnum%/%day%/%postname%/
Show on Front: |   | page
Page on Front: |   | Home (#7)
Page for Posts: |   | Unset
Table Prefix Length: |   | 5
Table Prefix Status: |   | Acceptable
Admin AJAX: |   | Accessible
Registered Post Statuses: |   | publish, future, draft, pending, private, trash, auto-draft, inherit, flamingo-spam, refunded, failed, revoked, cancelled, abandoned, processing, preapproval


```
</details>

**Comment by Benunc** [comment]
Hi @mjmiller21 

Can you please use our Priority support form at https://givewp.com/support for support for this issue?  

We're happy to help over there. Thanks!

**Comment by ravinderk** [comment]
@Benunc Can you confirm this is working fine for you in upcoming release `2.0.1`

**Comment by Benunc** [comment]
I am still unable to populate the {billing_address} tag on 2.0.1

**Comment by ravinderk** [comment]
@Benunc As we discuss this email tag is working fine in an email in `2.0.1`. Let me check it with pdf addon too.

**Comment by ravinderk** [comment]
@Benunc Closing this issue as you confirmed it is working fine.
For ref: https://github.com/WordImpress/Give/commit/4b95307886ec8760b46177277969165d3d5c60bf
