### ISSUE TITLE
Form sales does not update when change donation status {complete} --> {abandon}

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2708]
## Issue Overview

If admin changes completed donation to any status then form sale count must reduce.

## Expected Behavior

Form sale count must reduce.

## Current Behavior

Form sale count does not affect.

## Steps to Reproduce (for bugs)

Change completed donation to abandon.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by raftaar1191** [comment]
Video for the above issues: https://screencast-o-matic.com/watch/cFVTqFoOyI
