### ISSUE TITLE
Floating Labels Get Messed Up with Multiple Donation Forms on a Single Page

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#271]
When multiple forms are on a single page the floating labels get messed up.
![9-22-2015 3-06-33 pm](https://cloud.githubusercontent.com/assets/1571635/10033009/933148b0-613b-11e5-8c56-4e76c3cb1c04.png)
![9-22-2015 3-06-25 pm](https://cloud.githubusercontent.com/assets/1571635/10033010/9331a152-613b-11e5-9561-9893231badb2.png)

**Comment by DevinWalker** [comment]
@pryley would you mind taking a look at this? We can't ship the floating labels without support for textareas, select fields, and multiple forms embedded on a single page.

**Comment by DevinWalker** [comment]
It appears it's working for select fields for the most part. I only see them doubling up with multiple per page. Textareas seem not to work though...

**Comment by DevinWalker** [comment]
https://github.com/geminilabs/float-labels.js/issues/1

**Comment by pryley** [comment]
having a look now

**Comment by DevinWalker** [comment]
Cool, LMK if you have any questions... I'll be on for another hour or so...

**Comment by pryley** [comment]
@DevinWalker I'm guessing this is with the Form Field Manager plugin.
Do you use Slack?

**Comment by DevinWalker** [comment]
Yeah I do... want an invite to our team?

**Comment by pryley** [comment]
Yes please. Also I had a quick look:
When multiple forms are on the same page, the labels are all repeated on the last form. This is because form element IDs are being duplicated. IDs should always be unique.

**Comment by DevinWalker** [comment]
Are they being duplicated?! I didn't notice that... we don't want that.

**Comment by pryley** [comment]
IDs should probably be suffixed by the form_id, and some logic added to allow for it.

**Comment by pryley** [comment]
Floatlabels uses the element ID to locate the label it is bound to. If it can't find an ID, it checks the name as sometimes people write incorrect form structure (although maybe it should just skip the element by default if there is no ID/label pair).

**Comment by pryley** [comment]
I've updated float-labels to v1.0.6 (skip a form element if related label is not found, adjusted SCSS variables).
Run `bower update` and then `gulp`.

**Comment by DevinWalker** [comment]
Thanks I'll update now

**Comment by DevinWalker** [comment]
Just updated and am still seeing the issue with duplicate floating labels

**Comment by pryley** [comment]
https://github.com/WordImpress/Give/issues/272#issuecomment-142949254
