### ISSUE TITLE
perf(admin-setting): cache queries used in page settings

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#2718]
## User Story
As an admin, I want to admin general setting page to load fast. Currently, success/failed/history page setting shows page list without caching. We can cache this page query and improve page loading performance.

For Ref:
https://github.com/WordImpress/Give/issues/2699
https://github.com/WordImpress/Give/issues/2445

**Comment by DevinWalker** [comment]
I think if we simply show the latest `30` pages created and then allow them to search I think it's fine. @ravinderk please reopen if you disagree.
