### ISSUE TITLE
feat(admin-setting): clear Give Cache from within Advanced tab

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2719]
## Issue Overview

Add Clear Give_Cache Button in "Donations > Settings > Advanced" 

We have a Give_Cache now, and it is relatively smart about clearing at the right times; but for peace of mind and troubleshooting purposes, we should add the ability to force clear it.

## Tasks
- [x] Add setting to delete cache via ajax
- [x] Test it with some caching system like Redis and Memcached.

**Comment by kevinwhoffman** [comment]
Reopening this to address @mathetos's question in Slack:

> The second task I listed here wasn't checked. Have we thoroughly tested the clear Give Cache button against various types of caching? Specifically server-side caching like memcache and object caching?

@ravinderk @DevinWalker Please confirm whether this has been tested against the different types of caching.

**Comment by ravinderk** [comment]
@kevinwhoffman I test this issue against `Redis` cache and it is working fine for me.

**Comment by Sidsector9** [comment]
@kevinwhoffman This works fine with memcached + W3 Total Cache

**Comment by kevinwhoffman** [comment]
Closing as @ravinderk and @Sidsector9 have tested with Redis and Memcached.
