### ISSUE TITLE
Floating Labels Clashing with Custom Fields

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#272]
When a field is added programatically it appears the floating labels is not working properly. See this textarea I added: 

![9-22-2015 3-06-44 pm](https://cloud.githubusercontent.com/assets/1571635/10033040/bad969d8-613b-11e5-87d2-a9700bd0b6b1.png)

**Comment by pryley** [comment]
https://github.com/geminilabs/float-labels.js/issues/1#issuecomment-142511445

**Comment by pryley** [comment]
This is happening because the textarea has no placeholder. 

This is fixed in float-labels.js [v1.0.7](https://github.com/geminilabs/float-labels.js#changelog)

I also made some changes in the give scripts, will do a pull request shortly.

**Comment by DevinWalker** [comment]
Fixed by @pryley https://github.com/WordImpress/Give/issues/275
