### ISSUE TITLE
Import doesn't import Donations or Donors in version 2.0.1

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2725]
## Issue Overview
Import doesn't import Donations or Donors in version 2.0.1

## Expected Behavior
Importer should import all donations and donors

## Current Behavior
It creates the form correctly, but not any donations or donors.

## Steps to Reproduce (for bugs)
1. Install 2.0.1 from wordpress.org
2. Import using this CSV file: https://drive.google.com/file/d/10pw7q_0l02Rg6MvErXsAnYJ_OFOaYAIf/view?usp=sharing
3. Everything maps automatically. I removed the "Form ID" from being mapped
4. Run the import and you'll get a success message:
![image](https://user-images.githubusercontent.com/930724/35463804-61c3aa60-02a7-11e8-8984-46b19343de0a.png)

5. But then navigate to Donations and/or Donors and nothing will be there
6. Navigate to All Forms and one form will have been created successfully

**Comment by mathetos** [comment]
I actually tested this problem with version 1.8.19 and 2.0.1. I'm assuming 2.0.0 is also a problem.

**Comment by raftaar1191** [comment]
I am able to regenerate this issues with 1.8.19 as well as with 2.0.2. The problem was with Donation status parameter it only used to work when proper status key is pass to it 

![image](https://user-images.githubusercontent.com/22215595/35509907-0706b21c-051c-11e8-8206-4e393f734f23.png)

![image](https://user-images.githubusercontent.com/22215595/35509951-3151ac02-051c-11e8-8b65-ec4f9db2c7a1.png)

Fixing this issue and sending the PR. For now, admin can pass status key as well as status name

**Comment by ravinderk** [comment]
@mathetos This issue auto close. Reopen if you are able to reproduce this  issue.

**Comment by mathetos** [comment]
This doesn't seem to have been resolved. 

## Steps to Reproduce

* Be on any Give version from 1.8.19 - 2.0.6
* Try to import this CSV file : https://drive.google.com/open?id=11mOVzYqonrb_965EgSF_9jcTwn3odeAl
* It should import TWO unique donors, with TWO unique donations, and create TWO different Forms and associate those donations with those forms.
* Instead it only imports the donors with NO donations and NO forms. This success message is accurate, notice it does not mention donations or forms:
![image](https://user-images.githubusercontent.com/930724/37842256-dd4d2672-2e7e-11e8-9b37-1b2d07cfcec9.png)

I've tried this in many different environments, and mapping the fields in different ways. Same result every time.

**Comment by mathetos** [comment]
Just tested on the 2.0.7 branch and all is well. Thanks!
