### ISSUE TITLE
Consider having ajax issue admin notice link open in new tab/window

### ISSUE THREAD

**Issue by tw2113** [WordImpress/Give#2727]
![screenshot from 2018-01-27 14-16-08](https://user-images.githubusercontent.com/484075/35475939-e7379eb6-036c-11e8-9d20-8b6b57a4e090.png)

Potentially contentious with accessibility and whatnot, but may not be a bad idea to leave users in their admin dashboard with the learn more link from this admin notice.

**Comment by DevinWalker** [comment]
Yeah I think that's a good idea.
