### ISSUE TITLE
Shortcode generator issue with inserting Donation Form goal

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2728]
## Issue Overview
The "Donation Form Goal" shortcode generator option is not querying donation forms properly. Even if you have forms with goals enabled you will see:

![2018-01-27_19-24-33](https://user-images.githubusercontent.com/1571635/35478649-b9bda36a-0397-11e8-955e-0f8a44860cf8.png)

Reported here: https://wordpress.org/support/topic/give-shortcodes-menu-erroneously-says-no-forms-found-under-donation-form-goal/

**Comment by ravinderk** [comment]
Reopening this issue because I am able to reproduce it in 2.0.7
