### ISSUE TITLE
Prevent importer modifying existing form settings

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#2737]
## Issue Overview
The donation importer is currently modifying existing form settings, instead of simply pulling in the donations.

## Expected Behavior
Donations should be imported without modifying existing form settings.

## Current Behavior
I made a video to demonstrate the current issues.
https://screencast-o-matic.com/watch/cFVUDhovou

## Steps to Reproduce (for bugs)
Customer provided great PDF explaining the setup: [Note-Manual-Donations.pdf](https://github.com/WordImpress/Give/files/1674278/Note-Manual-Donations.pdf)

1. Create a multilevel form
2. modify the attached CSV by making the form ID match the id of the form you created in step 1 https://drive.google.com/file/d/1BoI488ny-uGfPPN5RdwLG2pSSxOsY2c8/view?usp=sharing
3. Import this csv to the site
4. Check the form you created in step one. It will be a set form now.

## Related Issues and/or PRs
Potentially related, the customer mentions this bug: https://github.com/WordImpress/Give-Tributes/issues/238

## WordPress Environment
<details>
### WordPress Environment ###

Home URL: http://localgive.local
Site URL: http://localgive.local
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: localgive.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 5.6.20
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.1
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://localgive.local/donation-confirmation/
Failure Page: http://localgive.local/donation-failed/
Donation History Page: http://localgive.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card, PayPal Standard, Offline Donation
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ❌ Unlicensed – by WordImpress – 1.3.3
Give - CSV Toolbox: ❌ Unlicensed – by WordImpress – 1.0
Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.2.5
Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.3
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.2.4
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 1.5.2

### Other Active Plugins ###

Ben's Helper Functions: by BenUNC –
User Switching: by John Blackbourn – 1.3.0

### Inactive Plugins ###

Better Search Replace: by Delicious Brains – 1.3.1
Debug Bar: by wordpressdotorg – 0.9
Debug Bar Post Meta: by whyisjake – 0.5.4
Duplicate Post: by Enrico Battocchi – 3.2.1
Elegant Themes Support: by Elegant Themes – 1.3
Give - 2Checkout Gateway: by WordImpress – 1.0.2
Give - Braintree Gateway: by WordImpress – 1.1.1
Give - Constant Contact: by WordImpress – 1.2.1
Give - ConvertKit: by WordImpress – 1.0.1
Give - Dwolla Gateway: by WordImpress – 1.1.2
Give - Email Reports: by WordImpress – 1.0.2
Give - Fee Recovery: by WordImpress – 1.4
Give - Form Countdown: by WordImpress – 1.0
Give - Gift Aid: by WordImpress – 1.1
Give - GoCardless Gateway: by WordImpress – 1.1.1
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.1
Give - Hook Helper: by Ravinder Kumar – 1.0
Give - iATS Payment Solutions: by WordImpress – 1.0.2
Give - MailChimp: by WordImpress – 1.3.6
Give - Old Meta Switcher: by WordImpress – 1.0
Give - Paymill Gateway: by WordImpress – 1.1
Give - PayPal Pro Gateway: by WordImpress – 1.1.4
Give - PayUmoney: by WordImpress – 1.0.1
Give - Per Form Gateways: by WordImpress – 1.0.1
Give - Razorpay: by WordImpress – 1.1.1
Give - Recurring Donations: by WordImpress – 1.5.4
Give - Recurring Helper: by WordImpress – 1.0
Give - Tributes: by WordImpress – 1.3.6
Give - Update Goal Progress: by Matt Cromwell – 1.0
Give - WePay Gateway: by WordImpress – 1.3.1
Give - WP All Import Addon: by Ben Meredith – 1.0
Give - Zapier: by WordImpress – 1.1.2
Give Stripe Cleanup.: by BenUNC –
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.1.2.3
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.6
Query Monitor: by John Blackbourn – 2.17.0
WPBakery Page Builder: by Michael M - WPBakery.com – 5.3
WP Crontrol: by John Blackbourn & contributors – 1.6.2
Yoast SEO: by Team Yoast – 5.9.1

### Active MU Plugins ###

hide-give-license-warning.php: by  –
Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by raftaar1191** [comment]
@Benunc it was really nice video and great catch thanks working on this

**Comment by DevinWalker** [comment]
Yeah really good catch @Benunc
