### ISSUE TITLE
feat(form): set roadmap for Gutenberg integration

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#2748]
## Issue Overview

The purpose of this issue is to discuss big-picture ideas regarding the transition of Give into the Gutenberg era.

Since we're beginning to explore block concepts and implementations in #2456, it would be helpful to discuss a long-term vision. In doing so, we can better ensure that the work being done today builds toward that vision.

## Relationship Between the Post Edit Screen and Blocks

Of all the challenges we face, the relationship between the Post Edit screen and Blocks feels like one of the most crucial challenges that we need to get right in order to create a great user experience. I've outlined my ideas for handling this relationship in the video below.

[View video](https://kevinwhoffman.wistia.com/medias/7qbbvge2s0)

![image](https://user-images.githubusercontent.com/1938671/35591471-0b1b5652-05d8-11e8-9883-9cc4c2c2344a.png)

## Related Issues and/or PRs

- Gutenberg: Create a donation form block #2456

**Comment by Benunc** [comment]
Very very good stuff, @kevinwhoffman 

I definitely agree with separating out Presentation and configuration whenever possible. Looking forward to my front row seat to watching this take shape.

**Comment by kevinwhoffman** [comment]
@raftaar1191 I agree we need to keep the Classic Editor in mind.

## Thinking It Through

With that said here's my current state of mind (which is different from the video). The more I learn about Gutenberg and what Blocks are capable of, the more I feel that Blocks are not an ideal solution for form-building. There is a lot of minutia involved with form-building (setting labels, tooltips, field widths, etc.) that doesn't mesh well with Gutenberg's approach to controls. My initial attempt in the video to marry a Gutenberg Block with our existing form editor shows that controls would be scattered across the screen in an unintuitive manner.

So here's where I stand now...

## Building Forms

We create our own visual form builder that's used to create the form and set defaults (much like we do today). In doing so, we can create a the best possible UI for form-building that is free from the constraints of Blocks. It also would have the added bonus of working for all users, whether they have adopted Gutenberg or are still in the Classic Editor.

## Displaying Forms

Gutenberg blocks would be used primarily to display forms that were already created in our custom form builder described above. Controls in the inspector would allow form defaults to be overridden at the block level much like the Block in #2456 is already doing. So I think we're on the right track in that regard.

**Comment by DevinWalker** [comment]
Closing this out as we've decided that's @kevinwhoffman approach above is the way we're going.
