### ISSUE TITLE
Format INR currency with { precision: 0 } returns not correct amount.

### ISSUE THREAD

**Issue by emgk** [WordImpress/Give#2758]
## Issue Overview

When formatting INR amount with the using argument as `{ precision: 0, currency: 'INR' }` return ( . ) dot at the end of the amount.

Try out this snippet (edit the form selector)

```
var amount = Give.fn.formatCurrency( 123456, { precision: 0, currency: 'INR' });
console.log( amount ); // it will return "1,23,456."
```

## Expected Behavior

- Should return proper value _( without any dot at the end of the amount )_ 

## Current Behavior

- Return amount with ( . ) dot as post-fix with amount.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by raftaar1191** [comment]
@emgk 

Also have to check for the below thing:


var amount = Give.fn.formatCurrency( 123456.13, { precision: 0, currency: 'INR' });
console.log( amount ); // it will return "12,34,56,.13"
