### ISSUE TITLE
Conditional floating labels not respecting switching payment gateways

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#278]
**Scenario:** A user has floating labels enabled globally, but disables them for a specific form:

![9-29-2015 1-29-54 pm](https://cloud.githubusercontent.com/assets/1571635/10177321/69ea0ae6-66ae-11e5-9d6c-dfb6dd17c544.png)

**Problem:** When the page first loads the gateway respects the disabled floating labels option, but when the user switches gateways kablamo (as @mathetos would say)! Floating labels!

![9-29-2015 1-30-15 pm](https://cloud.githubusercontent.com/assets/1571635/10177405/e5b64b9e-66ae-11e5-899e-76d9a383926c.png)

![9-29-2015 1-30-31 pm](https://cloud.githubusercontent.com/assets/1571635/10177406/e5b973be-66ae-11e5-823a-cf005e2fd103.png)

**Comment by mathetos** [comment]
Actually, this is happening even if you disable the Global setting AND disable it directly in the form as well. So, something about switching the payment gateway is triggering the Floating Labels to be applied after switching.
