### ISSUE TITLE
fix(compat): resolve conflict with Polylang plugin

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#2784]
## Issue Overview
The Polylang plugin languages revert to English on switching between payment gateways.

## Expected Behavior
If the language for a form is set at the form level, switching between payment gateways should not trigger a different language.

## Current Behavior
![polylang](https://user-images.githubusercontent.com/9629102/35935874-b77ae1c8-0c0f-11e8-95e2-1c480466043f.gif)

## Steps to Reproduce (for bugs)
On Local By Flywheel:
1. Download this zip file, and drag/drop it onto local by flywheel. https://drive.google.com/file/d/1lxJLvFbfWyk0T3ikZnzzLAEhfBIJWksh/view?usp=sharing
2. Log into the site with username ben and password 1
3. Navigate to http://polylang.local/fr/donations/french/
4. toggle between the donation forms. 

Or the long way:
1. Install Give and polylang. ( https://wordpress.org/plugins/polylang/ )
2. Set up two languages, english and French in the polylang settings.
3. create two forms, one in each language. Make the second one a translation of the first.
4. Navigate to the French version.
5. switch the payment gateway.

## WordPress Environment
<details>
### WordPress Environment ###

Home URL: http://polylang.local
Site URL: http://polylang.local
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: polylang.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.2
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://polylang.local/donation-confirmation/
Failure Page: http://polylang.local/donation-failed/
Donation History Page: http://polylang.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Other Active Plugins ###

Polylang: by Frédéric Demarle – 2.3

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by Benunc** [comment]
I did find that hard-coding a snippet like this "fixes" it:
```
function my_give_text_switcher( $translations, $text, $domain ) {
		if ( get_locale() === 'fr_FR' ) {
			if ( $domain == 'give' && $text == 'First Name' ) {
				$translations = __( 'Prénom', 'give' );
			}
		}
		return $translations;
	}

add_filter( 'gettext', 'my_give_text_switcher', 10, 3 );
```
But obviously having to hardcode all the French strings in the ajaxified fields is not a good solution.

**Comment by ravinderk** [comment]
@DevinWalker Bumping up this issue because we need to do research on `plolylang` plugin to fix the issue.

**Comment by raftaar1191** [comment]
Slack Call Summary

Participants: @raftaar1191, @ravinderk
Topic: What Can be Done to fixed this
Result: Had an call with @ravinderk to decision what we can do to fixed this issue, Other then chaining the priority of the hook.

**Comment by raftaar1191** [comment]
My finding for the above issues

Polylang used `plugin_load` hook to load his file and the priority  of the hook is setup **1**
```
add_action( 'plugins_loaded', array( $this, 'init' ), 1 );
```

Give load all it file class and text domain with the same hook but the priority is set is **0**
```
add_action( 'plugins_loaded', array( $this, 'init' ), 0 );
```


So here you can see the Give load it text domain before the Polylang load so that was the reason it was not working.

then I had a test on how WooCommerce does it and then I come to know it load all it function class before the `plugin_load` hook but it load the text_domain in **init** hooks which fire after the `plugins_loaded` so there was no issues as the Text Domain is getting load after the Polylang functions are loaded so it can easily check and update for the language

**Comment by DevinWalker** [comment]
@ravinderk can we do the same as Woo and increase our compatibility?
