### ISSUE TITLE
fix(admin-email): format address elements in the correct order

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2790]
## Issue Overview
See issue here:
![image](https://user-images.githubusercontent.com/930724/35999173-c8fec652-0cd3-11e8-94ea-fb1c7735b90f.png)

This address should instead be formatted as so:
Billing Address:
123
SD, CA 92101
US

Or:
{street_address}
{city}, {state} {postal_code}
{country}

If there are other formats for other countries, we should take that into account as well, but this one is clearly wrong for the majority of our users in the US.

**Comment by ravinderk** [comment]
@mathetos An address filter makes sense to me in core means different countries have different address format.

For example:
```
      /**
	 * Get formatted address.
	 *
	 * @return string Formatted address.
	 */
	function get_formatted_address( $address = array() ) {
                // code: set default address.

                $address_format = apply_filters( 'give_address_format', "{street_address}\n{city}, {state} {postal_code}\n{country}"

                // code: use str_replace to update address tag values.

		return apply_filter( 'give_get_fomatted_address', $address, $address_format, $address );
	}
```

User request: https://github.com/WordImpress/Give/commit/89f785e0e5e3eddcc6c376e2dee674380702e346

**Comment by mathetos** [comment]
@ravinderk I agree that a filter is useful for this. But the default should be what I outlined above, not what it currently is.

**Comment by mathetos** [comment]
@ravinderk Apologies, i didn't look closely at your code example. That format looks great.
