### ISSUE TITLE
fix(tooltip): remove HTML from tooltips

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#2796]
## Issue Overview
I've noticed that there is a tooltip in FFM addon which has HTML content as tooltip which is not displaying content properly.

![image](https://user-images.githubusercontent.com/1852711/36024837-fdaff39c-0db6-11e8-824a-17625518c26e.png)

This is the one scenario I've noticed and I'm not sure of any other scenario. It might be possible that with `qTip` it has always supported HTML Tooltips and we didn't face this scenario.

However, if we think to add support for HTML Content. Then, we can add support for it using [HTML HINT](https://github.com/istarkov/html-hint) Library

@DevinWalker @ravinderk Let me know your thoughts on this.

**Comment by kevinwhoffman** [comment]
Links in tooltips are not a great experience. In addition, Hint.css does not support HTML in tooltips. It's not worth changing tooltip libraries again for what seems one instance of HTML inside of a tooltip.

# Recommended Solution

- [ ] Review other FFM fields and remove HTML from all tooltips
- [ ] Move date formatting info to Give documentation for Date fields.

**Comment by raftaar1191** [comment]
Thanks, @kevinwhoffman for your comment. It's really very helpful and clarifies that what I have to do to fixed this issues.


Just one question  **Move date formatting info to Give documentation for Date fields.** can you please let me know that this documentation is already been add or I need to create an issue for this in https://github.com/WordImpress/Give-Docs/. As can see there is a check mark on that

![image](https://user-images.githubusercontent.com/22215595/37335131-b4763f20-26d3-11e8-842c-c7b713cca009.png)

**Comment by raftaar1191** [comment]
To fix this issues I have to move this issues in https://github.com/WordImpress/Give-Form-Field-Manager/ as this issue exists in that Add-on


Issues Link: https://github.com/WordImpress/Give-Form-Field-Manager/issues/236


**Issues Move to https://github.com/WordImpress/Give-Form-Field-Manager/issues/236**

**Comment by kevinwhoffman** [comment]
@raftaar1191 I already took care of the documentation update. So you only need to update the `Date Format` tooltip and remove HTML from any remaining tooltips.

Closing this issue since it was moved to https://github.com/WordImpress/Give-Form-Field-Manager/issues/236.

**Comment by raftaar1191** [comment]
Thanks @kevinwhoffman
