### ISSUE TITLE
build(composer): streamline local development setup

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#2798]
Instead of having to run `npm install` separately, we can hook it to composer's `post-update-cmd` event. This can simplify the setting up of the development environment for contributors.

This will also help setting up git's pre-commit hooks that is currently under development since npm will install eslinter and the pre-commit hooks will lint JS files before committing. 

What will be required from contributors is that they already have the following installed:

- Git
- Composer
- NPM
- PHPCS

@kevinwhoffman @ravinderk let me know your thoughts on this.

**Comment by kevinwhoffman** [comment]
Closing as this was merged in #2893
