### ISSUE TITLE
AddOn for Events

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#28]
ENVIRONMENT:

__________________________________________
FEATURE REQUESTS:
I would like to suggest an AddOn for events.

This AddOn could facilitate the selling of tickets. I wouldn't go so far as to do things like letting users choose seating in real-time, but they could choose the ticket type, maybe the level of seating, etc.
__________________________________________
GENERAL FEEDBACK:

REF:345giveReagan!fgh15

**Comment by DevinWalker** [comment]
I definitely like that idea for an Add-on.

**Comment by DevinWalker** [comment]
@mathetos please add this to GiveWP for voting and close this issue

**Comment by mathetos** [comment]
Done: https://givewp.com/coming-soon/
