### ISSUE TITLE
fix(donor): allow multiple search queries

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#2807]
## Issue Overview
When a search is conducted for a donor in the Donors admin section it returns accurate results. When you hit the clear "x" at the end of the field, or if you delete the entry and search again. It returns with "no items found."

## Expected Behavior
The user should have the ability to make a search query, and then be able to make another query without having to reload the page.

## Current Behavior
When a query is executed the results return fine. If you make another query it returns with "no items found." This is also the case if I try to search within the results that have already been returned.

![gif-test](https://user-images.githubusercontent.com/20672471/36165270-fa103446-10bc-11e8-996c-a8314dbd9e25.gif)

## Steps to Reproduce (for bugs)

1. Install Give
2. Go to the admin panel and select donations.
3. Search for a donor within the system.
4. Once the results return, delete the entry, or hit the clear and attempt to make another search.
5. Confirm that "no items found" displays.

## WordPress Environment
<details>

WordPress Environment
--
Home URL: |   | http://pumpscenario.local
Site URL: |   | http://pumpscenario.local
WP Version: |   | 4.9.4
WP Multisite: |   | –
WP Memory Limit: |   | 256 MB
WP Debug Mode: |   | –
WP Cron: |   |  
Language: |   | en_US
Permalink Structure: |   | /%year%/%monthnum%/%day%/%postname%/
Show on Front: |   | posts
Table Prefix: |   | wpv0_
Table Prefix Length: |   | 5
Table Prefix Status: |   | Acceptable
Admin AJAX: |   | Accessible
Registered Post Statuses: |   | publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

Server Environment
Hosting Provider:		DBH: localhost, SRV: pumpscenario.local
TLS Connection:		Connection uses TLS 1.2
TLS Rating:		Probably Okay
Server Info:		Apache/2.4.10 (Debian)
PHP Version:		7.0.3
PHP Post Max Size:		1,000 MB
PHP Time Limit:		900
PHP Max Input Vars:		3000
PHP Max Upload Size:		1,000 MB
cURL Version:		 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed:		–
MySQL Version:		5.6.34
Default Timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
gzip:		
GD Graphics Library:		
Multibyte String:		
Remote Post:		
Remote Get:		

WordPress Environment
--
Home URL: |   | http://pumpscenario.local
Site URL: |   | http://pumpscenario.local
WP Version: |   | 4.9.4
WP Multisite: |   | –
WP Memory Limit: |   | 256 MB
WP Debug Mode: |   | –
WP Cron: |   |  
Language: |   | en_US
Permalink Structure: |   | /%year%/%monthnum%/%day%/%postname%/
Show on Front: |   | posts
Table Prefix: |   | wpv0_
Table Prefix Length: |   | 5
Table Prefix Status: |   | Acceptable
Admin AJAX: |   | Accessible
Registered Post Statuses: |   | publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

</details>

**Comment by ravinderk** [comment]
@samsmith89 This has been fixed. Please review it in `release/2.0.3` branch.

![dne0szfzmv](https://user-images.githubusercontent.com/1784821/36166297-03a3b1bc-1118-11e8-8bbd-4735850201e0.gif)

**Comment by samsmith89** [comment]
@ravinderk I was able to test it and everything is working great. Thank you.
