### ISSUE TITLE
String not translatable

### ISSUE THREAD

**Issue by chantalcoolsma** [WordImpress/Give#2811]
I am working on the Dutch translation and I noticed that the day of the week in the dashboard widget isn't translatable. It is just shown as the English day of the week:

`<p class="give-dashboard-happy-day"><?php
	printf(
	/* translators: %s: day of the week */
		__( 'Happy %s!', 'give' ),
		date( 'l', current_time( 'timestamp' ) )
	);
?></p>`

includes/admin/dashboard-widgets.php

**Comment by DevinWalker** [comment]
Thanks for reporting, I've fixed this issue in the PR above and it will be released today.
