### ISSUE TITLE
fix(ffm): prevent Form Field Manager from affecting other dropdown menus

### ISSUE THREAD

**Issue by alexsgithubusername** [WordImpress/Give#2827]
## Issue Overview

Just updated Give and all related plugins. Had to disable Form Field Manager as it disables all my drop down menus.

**Comment by ravinderk** [comment]
@alexsgithubusername
Thank you for reporting the issue. We will reply back after testing.

**Comment by mehul0810** [comment]
@alexsgithubusername 
I have tried to reproduce the issue you are facing with Form Field Manager Ad-don and added some mega menu plugins to create drop-down menu to reproduce the issue. But, it is working fine.

However, if you would provide us the system info then that would be really helpful to reproduce it at our end and help you at our best.

**Comment by kevinwhoffman** [comment]
Closing. If steps are provided to recreate, we can reopen.
