### ISSUE TITLE
Removing addon and then adding same addon bug?

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#283]
Hey

I am on Chrome.
I just now added Stripe to the cart and then removed it again. I then tried adding it again, but the page only says checkout and I am not able to add it my shopping cart...

![skjermbilde 2015-09-30 kl 12 28 12 pm](https://cloud.githubusercontent.com/assets/5323259/10199440/be9bf7e6-676e-11e5-99ad-fc20f14532b3.png)

**Comment by mathetos** [comment]
Hay Paal, please use our Contact Form on our website. This Repo is not for our website, but for building and developing the Give plugin. Thanks!
