### ISSUE TITLE
bug(downloads): Percentage value is not computed correctly in the admin page goal column

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#2835]
## Issue Overview
Percentage value is not computed correctly on the forms listing page in the admin dashboard 

## Expected Behavior
Compute percentages correctly

## Steps to Reproduce (for bugs)
1. Create a new Donation Form (custom amount, percentage)
2. Set the Goal amount to $250
3. Donate $135
4. Go to the forms listing page, the percentage displayed under the **goal** column should be **54%**, but is shows **135%**

It shows correctly on the front end though.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ravinderk** [comment]
@Sidsector9 i am unable to reproduce this in `release/2.0.5`
