### ISSUE TITLE
Where is the shopping cart?

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#284]
Hey

Ok I go to add an addon and add it to the cart. I go to another place on the web site and it seems the only way to get back to the shopping cart is by selecting an addon and then clicking the cart on the addon page. The shopping cart needs to be in general more visible on the site.

**Comment by DevinWalker** [comment]
Oh on our Give site? That's a good point!

**Comment by paaljoachim** [comment]
Yup...:)
