### ISSUE TITLE
Purchase confirmation?

### ISSUE THREAD

**Issue by paaljoachim** [WordImpress/Give#285]
I tried purchasing the Stripe addon with the code that I have. The code worked but clicking purchase using Paypal the button spun for a moment and nothing else happened.
I missed having a confirmation message coming up....

Not sure what is going on here...

**Comment by DevinWalker** [comment]
I just tested and it worked fine for me. What browser are you using?

**Comment by paaljoachim** [comment]
Chrome. I sent you and Matt an e-mail that also includes a video. So that we can move the discussion over to e-mail instead. It might just be my computer and Chrome being weird today....
