### ISSUE TITLE
feat(admin-tool): Add button to automate creating API key for current user

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2855]
## Issue Overview
Since our Give Gutenberg block will require that the user has an API key, making that process as painless as possible is important.

If a site has a ton of users, then finding your own user can be a little troublesome with the current Select2 field. I suggest just a one-click button for the current logged in user, like so:

![image](https://user-images.githubusercontent.com/930724/36817107-d7db3da6-1c94-11e8-8c29-8948490ddb00.png)

If the current user already has an API key generated, then this button would NOT appear.

**Comment by DevinWalker** [comment]
I like this button here, but I don't think our Gutenberg block should be using this API but rather a custom WP REST API endpoint. That way no key needs to be generated.

**Comment by mathetos** [comment]
That's definitely preferrable for sure. Glad to hear that's an option.

**Comment by kevinwhoffman** [comment]
@DevinWalker I agree. Regarding the Gutenberg block, my first impression was it is an awkward experience to be kicked out of the post editor to create the key and then find your way back into it. If we can use the REST API, that is best.

Regarding this issue, my recommendation would be to default the user select box to the current user and not add an additional button. That would accomplish the goal of quickly generating a key for oneself without increasing UI complexity.
