### ISSUE TITLE
fix(form): allow amount to be changed multiple times

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#2861]
## Issue Overview
when the amount is changed more than once on a multilevel drop-down form, it is not reflected in the bottom Donation Total box.

## Expected Behavior
A donor should be able to change the amount as much as they want.

## Current Behavior
https://screencast-o-matic.com/watch/cFen2xDjVR
Forgot to check the console on the video: here's the output of that: 
```
Uncaught TypeError: e.replace is not a function
    at Object.unFormatCurrency (give.all.min.js:8)
    at Object.autoSetMultiLevel (give.all.min.js:8)
    at HTMLSelectElement.<anonymous> (give.all.min.js:8)
    at HTMLDocument.dispatch (jquery.js:3)
    at HTMLDocument.r.handle (jquery.js:3)
```
...so it appears to be related to currency switching changes.

## Steps to Reproduce (for bugs)
1. Fresh install of 2.0.5
2. Multilevel form displayed as drop-down
3. change the level multiple times on the front end.
4. It will only change once. 

## WordPress Environment
<details>
### WordPress Environment ###

Home URL: http://powpow.local
Site URL: http://powpow.local
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: powpow.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.5
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: 2.0.4
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://powpow.local/donation-confirmation/
Failure Page: http://powpow.local/donation-failed/
Donation History Page: http://powpow.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by DevinWalker** [comment]
Possibly related to #2860

**Comment by DevinWalker** [comment]
Issue is due to @ravinderk's commit coming post Gulp run. We'll resolve this by running gulp prior to release.
