### ISSUE TITLE
give ffm using 'startsWith' function

### ISSUE THREAD

**Issue by datesss** [WordImpress/Give#2873]
## Issue Overview
The give ffm addon uses the .startsWith string function, which is unavailable in IE11 (or atleast some versions of IE11)

## Possible Solution
I'm currently polyfilling to fix the issue, maybe y'all could use a different function or include the polyfill in the script, so it doesn't break other peoples sites 
````
if (!String.prototype.startsWith) {
  String.prototype.startsWith = function(searchString, position) {
    position = position || 0;
    return this.indexOf(searchString, position) === position;
  };
}
````

## Steps to Reproduce (for bugs)
1. Include give-ffm-frontend.js on a page
2. open developer tools in ie11 (i tested with windows 7 / 8 tru browserstack)

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>
```
Copy and paste the system Info report from **Donations > Tools > System Info** in WordPress admin here.
```
</details>

**Comment by DevinWalker** [comment]
Issue moved to [WordImpress/Give-Form-Field-Manager #233](https://github.com/WordImpress/Give-Form-Field-Manager/issues/233) via [**ZenHub**](https://www.zenhub.com/)

**Comment by DevinWalker** [comment]
Thanks for the issue and polyfill - I'm moving this to the FFM repo.
