### ISSUE TITLE
fix(gutenberg): prevent fatal error if Gutenberg not activated

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#2891]
## User Story

As a developer, I want check if Gutenberg plugin is activated so that when I use functions such as `register_block_type`, it does not throw fatal error if the plugin is not activated.

I disabled Gutenberg and **[this](https://github.com/WordImpress/Give/blob/feature/gutenberg-donation-form-block/blocks/donation-form/class-give-donation-form-block.php#L83)** line caused an error because the function is defined inside Gutenberg.

## Current Behavior
Throws fatal error that function `register_block_type` is underfined.

## Expected Behavior
Error should not be thrown if Gutenberg is deactivated.

## Possible Solution
Check if Gutenberg is active before implementing blocks

## Steps to Reproduce
1. Checkout to `feature/gutenberg-donation-form-block` branch
2. Disable Gutenberg
3. Go to Home Page

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.3
PHP Version: 5.6.33-3+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
PHP Max Upload Size: 100 MB
cURL Version: 7.47.0, OpenSSL/1.0.2g
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: PayPal Standard, Offline Donation
Default Payment Gateway: PayPal Standard
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Other Active Plugins ###

Gutenberg: by Gutenberg Team – 2.3.0
Nginx Helper: by rtCamp – 1.9.10

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.2
Hello Dolly: by Matt Mullenweg – 1.6

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Linux Ubuntu</li>
        <li>Version: 16.04</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
        <li>Version: 64.0.3282.167 (Official Build) (64-bit)</li>
    </ul>
</details>

**Comment by ravinderk** [comment]
Closing this issue because it has been fixed in https://github.com/WordImpress/Give/pull/2856
