### ISSUE TITLE
Remove usage PHP 5.4+ bracket array declarations

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#290]
Unfortunately, we can't declare arrays using bracket notation because many folks use PHP 5.3 for WordPress. @pryley please take note. 

```
<?php
$array = array(
    "foo" => "bar",
    "bar" => "foo",
);

// as of PHP 5.4
$array = [
    "foo" => "bar",
    "bar" => "foo",
];
?>
```

http://php.net/manual/en/language.types.array.php

Reported here: https://givewp.com/support/ticket/v1-3-breaks-wp-mail-function/#post-5533

User is on PHP 5.3.3

**Comment by mathetos** [comment]
Nice catch Devin. I wish we could follow the trend like other WP Plugins and just support 5.4+, but many non-profits are on older systems and we don't have enough general adoption yet to be strict on that.

**Comment by pryley** [comment]
Oops! Muscle memory...thought I had caught of of them.

**Comment by DevinWalker** [comment]
I mean... it's unfortunate we can't use some of PHP better syntax but that's the nature of the beast.
