### ISSUE TITLE
refactor(admin-plugins): combine notices to singular tabbed interface

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2903]
## Tasks

- [x] Determine the best solution from the two below via call between @DevinWalker and @emgk   (2 storypoints)

**From @emgk's research:**

> ### Solution 1 ( Using Global Variable )
> In this solution we can declare a global variable `$give_plugins_info`. This variable contains the banner information of all Give's activated add-ons passed from each of the add-ons itself.
> 
> All of the new add-ons will then have a code to add information inside this global variable, instead of initialization of the `Give_Addon_Activation_Banner` class.      
> 
> For backward compatibility, Inside https://github.com/WordImpress/Give/blob/release/2.0.7/includes/admin/class-addon-activation-banner.php#L39 Instead of assigning the add-on banner details to it's class variable assign them to the global  $give_plugins_info['plugin-slug'] = $_banner_args; variable.
> 
> Then use this global variable to list out the activated add-on in tabbed view.
>  
> ### Solution 2 ( Static variable )
> We have already done in Give-Recurring to register the new gateway as recurring. We are assigining gateway recurring class to the `Give_Recurring::$gateway`.
> 
> https://github.com/WordImpress/Give-Mollie/blob/master/give-mollie.php#L199-L201 
> 
> Inside the Give_Addon_Activation_Banner declare new static array variable which will then store the add-on banner informations. 
> 
> After that, We can use this variable anywhere we want to get the list of banner information of all of the activated add-ons.

 
- [x] Develop solution using design created. 

Requirements:

1. The solution should is backwards compatibility so that we don't have to update each add-on class individually

**Comment by emgk** [comment]
@DevinWalker I am working on this enhancement, by tomorrow i will finalize it.

![ezgif-3-d678d2d04e](https://user-images.githubusercontent.com/14994452/37467685-f5909dca-2886-11e8-8bc2-8dccaad89030.gif)
