### ISSUE TITLE
build(webpack): Bundle SVG files inside correct folder

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#2907]
## User Story

As a developer, I want svg files to be bundled in the `dist/images` folder.

## Current Behavior
Currently webpack bundles SVG files inside both `dist/fonts` and `dist/images` folder as evident [here](https://github.com/WordImpress/Give/blob/release/2.1/webpack.config.js#L81) and [here](https://github.com/WordImpress/Give/blob/release/2.1/webpack.config.js#L95)

## Expected Behavior
SVG files should be bundled only inside the `dist/images` folder.

## Possible Solution
Remove `svg` from [line 81](https://github.com/WordImpress/Give/blob/release/2.1/webpack.config.js#L81)

## Tasks

- [x] Fix module bundler to bundle SVG files in dist/images folder

**Comment by DevinWalker** [comment]
@Sidsector9 next time you create an issue be sure you estimate it on the right hand side. Also, when you submit a PR like you did above make sure you check of your "Tasks" so I know what you've done. You see the issue is left un-estimated and checkboxes not checked.

**Comment by Sidsector9** [comment]
@DevinWalker After having that discussion the other day I did not realise I was granted permission to edit these. Henceforth I will keep this in mind.
