### ISSUE TITLE
PHP 5.2 Issue with anonymous function / Closure used in new shortcode generator

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#291]
The problem is that folks using PHP 5.2 can't have fancy stuff... Unfortunately, a lot of people are using that oldddd version so we have to fix this: https://github.com/WordImpress/Give/blob/1.3/includes/admin/shortcodes/abstract-shortcode-generator.php#L304

**Comment by pryley** [comment]
PHP 5.2? yikes!

**Comment by DevinWalker** [comment]
@pryley yeah man... so many crappy hosting companies still setup WordPress on it. We should have not allowed that when we launched. There's not much we can do about it now.

**Comment by DevinWalker** [comment]
This is fixed though so no worries on it.
