### ISSUE TITLE
Offline Donations Gateway Needs Documentation

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#292]
There's no docs and some people are confused at how exactly it works: 

**Needs Docs**: https://givewp.com/documentation/

**Reported From**: https://wordpress.org/support/topic/is-there-a-way-to-include-offline-donations?replies=4#post-7490816

**Comment by mathetos** [comment]
We actually don't have docs for ANY of the Core payment gateways. So I created a parent page for all of them to have their own article underneath. And "Offline" is there already:

https://givewp.com/documentation/core/payment-gateways/
