### ISSUE TITLE
fix(admin-donation): Allow saving donation details

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#2928]
## User Story
As a user, I want save the details on the donations details page so that I can update them if needed.

## Current Behavior
Unable to update the details on the donation's details page.

## Expected Behavior
I expect it to save the changes I made.

## Possible Solution
This is related to caching. Setting `GIVE_CACHE` to `false` allows to update the details

## Steps to Reproduce
Go to **Donations > Donations > View Donation xx**

## Visuals
![give_cache](https://snag.gy/NdLkMS.jpg)

## Tasks
- [ ] Discuss with @ravinderk to determine if this issue is valid.

## Environment
<details>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.3
PHP Version: 5.6.33-3+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
PHP Max Upload Size: 100 MB
cURL Version: 7.47.0, OpenSSL/1.0.2g
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Other Active Plugins ###

Nginx Helper: by rtCamp – 1.9.10

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.2
Hello Dolly: by Matt Mullenweg – 1.6

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Linux</li>
        <li>Version: 16.04</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
        <li>Version 64.0.3282.186 (Official Build) (64-bit)</li>
    </ul>
</details>

**Comment by ravinderk** [comment]
> Slack Chat Summary
> 
> Participants: @Sidsector9 , @ravinderk
> Topic: Testing Fix
> Result: Working fine.


For Ref: https://github.com/WordImpress/Give/commit/ef3fcfd76da8b04078717362a92924a5980dcfa9
