### ISSUE TITLE
The label for the "Transaction Types" just says "PayPal" right now. It should say "PayPal Transaction Type".

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#293]
The label for the "Transaction Types" just says "PayPal" right now. It should say "PayPal Transaction Type".

![paypal-transaction-types](https://cloud.githubusercontent.com/assets/930724/10210089/8220054a-6797-11e5-878a-5aca8e8a9029.jpg)

**Comment by DevinWalker** [comment]
Again... vague title, hard to understand.
