### ISSUE TITLE
Form Contents does not show in Single Form

### ISSUE THREAD

**Issue by farookibrahim** [WordImpress/Give#294]
![image](https://cloud.githubusercontent.com/assets/10401366/10219247/ed45ed3a-685a-11e5-8c68-8451e1672452.png)

![image](https://cloud.githubusercontent.com/assets/10401366/10219261/059d9054-685b-11e5-8daa-5a1d48d95520.png)

**Comment by pryley** [comment]
I got this.
It was introduced with the shortcode attributes feature because I neglected to test the single-forms (they were disabled in options), only the widgets and pages with a form shortcode.
