### ISSUE TITLE
Can't add a new custom currency with My Custom Functions

### ISSUE THREAD

**Issue by itanhduy** [WordImpress/Give#2944]
## User Story
As an admin, I want to add a new currency to the plugin so that I can display my country currency to users

## Current Behavior
I currently can't add a new currency to the plugin. When I'm using this code with the plugin "My Custom Functions"

```
/* Enter your custom functions here */
/**
 * Adds a new Currency symbol and name to Give payment options.
 *
 * @since 1.0
 *
 * NOTE: Give supports all currencies that PayPal Standard offers
 * See here: https://developer.paypal.com/docs/classic/api/country_codes/
 *
 * Get the Unicode for Currencies here:
 * https://www.w3schools.com/charsets/ref_utf_currency.asp
 *
 * This adds the currency as an option in your currency settings
 * and will output in your front-end forms. But it is up to your
 * Payment Gateway to handle that currency correctly.
 * This means that even though the form will show your currency, and
 * you'll see the reports with this currency, your Payment processor
 * may reflect something different.
 */
/**
 * Adds Costa Rican Colon currency to your Give settings
 * it's required Give minimum Version 1.8.15
 *
 * @since 1.8.15
 *
 * @param $currencies
 *
 * @return mixed
 */
function give_adding_vietnam_currencies_support( $currencies ) {
	$currencies['VND'] = array(
			'admin_label' => __( 'Vietnamese đồng (₫)', 'give' ),
			'symbol'      => '&#8363;',
			'setting'     => array(
				'currency_position'   => 'after',
				'thousands_separator' => '.',
				'decimal_separator'   => ',',
				'number_decimals'     => 2,
			),
		),
	return $currencies;
}	
add_filter( 'give_currencies', 'give_adding_vietnam_currencies_support' );
```

![screen shot 2018-03-23 at 11 16 13 am](https://user-images.githubusercontent.com/10527554/37811333-1c1cedc6-2e8c-11e8-9277-2cfacbac13fe.png)
![screen shot 2018-03-23 at 11 16 26 am](https://user-images.githubusercontent.com/10527554/37811334-1c4f2354-2e8c-11e8-9f07-9e6e49d1abb0.png)
![screen shot 2018-03-23 at 11 16 33 am](https://user-images.githubusercontent.com/10527554/37811335-1c82063e-2e8c-11e8-9e9a-4662e33d6bae.png)

## Expected Behavior
I expect the new currency was added by me should show in the list currencies.

## Possible Solution
I can go to plugin folder and hard code new currency but with a new update, it will be lost.

**Comment by ravinderk** [comment]
@itanhduy There is a typo in your code. Can you fix it and test aging?

![image](https://user-images.githubusercontent.com/1784821/37812849-2a16cc98-2e88-11e8-8d3e-5af10ea7c17e.png)

After fix, it si working fine for me:
![screen shot 2018-03-23 at 10 51 59 am](https://user-images.githubusercontent.com/1784821/37812866-4a87560a-2e88-11e8-9bbc-d1d757d1dd7a.png)

**Comment by ravinderk** [comment]
@itanhduy I proposed to add support for this currency in core https://github.com/WordImpress/Give/issues/2945

**Comment by itanhduy** [comment]
OMG! I was mistaken. Thanks a lot, @ravinderk.

**Comment by itanhduy** [comment]
Hi @ravinderk . It's so weird. It didn't work on my side. I'm using child-theme. Has it made the issue?

**Comment by ravinderk** [comment]
@itanhduy In which file did you add this code, `functions.php`?

**Comment by itanhduy** [comment]
@ravinderk 
I'm using plugin My Custom Functions:
GiveWP's version: 2.0.6
Wordpress: 4.9.4


![screen shot 2018-03-23 at 12 47 33 pm](https://user-images.githubusercontent.com/10527554/37813614-70b11630-2e98-11e8-85be-f1a22d93d3e3.png)
![screen shot 2018-03-23 at 12 45 40 pm](https://user-images.githubusercontent.com/10527554/37813621-751718a0-2e98-11e8-9835-d0dbd91747f3.png)
![screen shot 2018-03-23 at 12 45 55 pm](https://user-images.githubusercontent.com/10527554/37813639-87f500d6-2e98-11e8-9d4b-2007b07d43b4.png)

**Comment by ravinderk** [comment]
@itanhduy It is working fine for me.

![image](https://user-images.githubusercontent.com/1784821/37813936-8865d6ea-2e8d-11e8-9327-4642d08c7b6a.png)
![image](https://user-images.githubusercontent.com/1784821/37813948-90ce0b86-2e8d-11e8-9c87-11529c42afd1.png)

**Comment by ravinderk** [comment]
@itanhduy Please fix typo in your code.

![image](https://user-images.githubusercontent.com/1784821/37814009-be5d8f5e-2e8d-11e8-95d3-4b21836f2bc4.png)

**Comment by itanhduy** [comment]
@ravinderk 
It worked. Thank you ;)
I would like to share my mistake. I forgot to enable this plugin. change STOP to START.


![screen shot 2018-03-23 at 1 08 29 pm](https://user-images.githubusercontent.com/10527554/37814180-550e5098-2e9b-11e8-9e5f-abe67ff6337e.png)
![screen shot 2018-03-23 at 1 04 54 pm](https://user-images.githubusercontent.com/10527554/37814182-56558020-2e9b-11e8-8b69-78beed03ac9d.png)

**Comment by ravinderk** [comment]
@itanhduy Glad, it worked.
