### ISSUE TITLE
fix(admin-plugins): correct number of plugins for Give filter

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#2953]
## User Story

As a `user`, I want be sure that the `number of plugins` for Give specifically appears accurately so that I know which plugins are only Give-related.

## Current Behavior
The number is incorrect next to the filter:

![2018-03-27_00-55-17](https://user-images.githubusercontent.com/1571635/37954514-de9c501e-315a-11e8-8abc-f017c896b3dd.png)

**Comment by raftaar1191** [comment]
## Finding 

[Here](https://github.com/WordImpress/Give/blob/release/2.1/includes/admin/plugins.php#L153) we were not looking for the author name so I add a new condition that will also check for the author name with the Plugin name 


So now it will look for two thing on for **Plugin Name** and the Second one is for **Author Name** 



**Notes: Some Give Add-on has Author name as `WordImpress, LLC` and some have Author name as  ``WordImpress`` so overcome this I am checking for string position in Author name**
