### ISSUE TITLE
fix(i18n): Avoid Concatenating substrings

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#2958]
## User Story
As a non-English speaking Give Admin, I want to be able to translate all Give strings so that Give looks and feels native in my local language.

## Current Behavior
I currently am struggling with these lines here: https://github.com/WordImpress/Give/blob/release/2.0.7/includes/admin/emails/class-email-setting-field.php#L236-L241

They have broken up the sentence in a way that will not sound natural in Swedish (for example). As reported here:
https://wordpress.org/support/topic/avoid-concatenating-substrings/

## Expected Behavior
I expect to be able to translate that string with complete flexibility, not have to translate it in parts.

## Possible Solution
We could just link the whole sentence. 
```
sprintf(
	'<br><a href="%1$s" target="_blank">%2$s</a> %3$s',
	esc_url( 'http://docs.givewp.com/meta-email-tags' ),
	__( 'See our documentation for examples of how to use custom meta email tags to output additional donor or donation information in your Give emails.', 'give' )
)
```

Or make the opening anchor tag and closing anchor tag the variables.

## Tasks
- [ ] Update the string so it's all one sentence.
- [ ] Test the translation in at least one other language other than English

**Comment by kevinwhoffman** [comment]
@ravinderk Please confirm whether this has been fixed or not. Thanks.

**Comment by ravinderk** [comment]
@kevinwhoffman It is completed.
for ref: https://github.com/WordImpress/Give/blob/release/2.1.5/includes/admin/emails/class-email-setting-field.php#L248-L275
