### ISSUE TITLE
test(phpunit): fix broken tests in 2.1

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#2959]
## User Story

As a `<type of user>`, I want `<some goal>` so that `<some reason>`.

## Current Behavior

I currently...

## Expected Behavior

I expect to...

## Steps to Reproduce

1.
2.
3.

## Related

- 
- 
- 

## Tasks

- [ ] Enter at least one task to be completed in the [imperative mood](https://chris.beams.io/posts/git-commit/#imperative).

**Comment by kevinwhoffman** [comment]
@DevinWalker Can you fill in the details of this issue regarding the broken unit tests? Thanks.

**Comment by DevinWalker** [comment]
@ravinderk resolved the issue with unit tests last week: e9b6ac39f1c98f21a261d43e00e56764fe296622
