### ISSUE TITLE
fix(gutenberg): ensure Give Form Grid block can be inserted

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#2960]
## User Story

As a Gutenberg user, I want to insert a Give Donation Form Grid block so that I can use the form grid in a Gutenberg post.

## Current Behavior

I currently cannot insert the `Give Donation Form Grid` block in Gutenberg. The loading animation never ends and I can see an error in dev tools regarding the shortcode name.

![image](https://user-images.githubusercontent.com/1938671/38122709-9a7dcb28-33a4-11e8-94fa-74fd86d27b0f.png)

## Expected Behavior

I expect the block to insert the form grid without error.

## Possible Solution

The name of the shortcode has changed since the original implementation, so the fix may be as easy as correcting the shortcode name that the block is calling.

## Steps to Reproduce

1. Install WP with Give and Gutenberg.
2. Create a few donation forms.
3. Create a new post in Gutenberg, and attempt to insert the form grid block. The loading animation will loop endlessly.

## Visuals

![image](https://user-images.githubusercontent.com/1938671/38122597-fb780dcc-33a3-11e8-9058-2dd88f1337d0.png)

## Tasks

- [x] Correct the name of the function from `give_donation_grid_shortcode` to `give_form_grid_shortcode`

**Comment by Sidsector9** [comment]
@kevinwhoffman The shortcode was fine, the callback function name was incorrect. This has been fixed.
