### ISSUE TITLE
fix(admin-tool): Fix JS error caused while importing Give Settings

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#2972]
## User Story
As a user, I want successfully import Give Settings so that I can copy give settings from one site to another.

## Current Behavior
Importing give settings from a JSON file throws JS error in console.

## Expected Behavior
I expect it to import settings without any errors

## Steps to Reproduce

1. Go to _**Donations > Tools > Import > Import Give Settings**_
2. Upload a JSON file
3. Click Submit

## Visuals
![importererror](https://snag.gy/GN5r2F.jpg)

## Tasks

- [ ] Locate the cause of error and fix it
## Environment
<details>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.3
PHP Version: 5.6.33-3+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
PHP Max Upload Size: 100 MB
cURL Version: 7.47.0, OpenSSL/1.0.2g
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Other Active Plugins ###

Nginx Helper: by rtCamp – 1.9.10

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.2
Hello Dolly: by Matt Mullenweg – 1.6

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Linux</li>
        <li>Version: 16.04</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
        <li>Version 64.0.3282.186 (Official Build) (64-bit)</li>
    </ul>
</details>

**Comment by raftaar1191** [comment]
Slack Call Summary

Participants: @devinwalker, @ravinderk @kevinwhoffman, and @raftaar1191
Topic: WebPack affecting functions Scope 
Result: Had a discussion with all the above mention people and come to a concussion we have to remove all the script Tag that are inside PHP file Example: Donation Importer, Core Setting Importer. 

And the old function that used to have global scope  and it being used by Add-on it already being taken care

**Comment by raftaar1191** [comment]
PR link to fix the above issues https://github.com/WordImpress/Give/pull/2995
