### ISSUE TITLE
How can I remove Credit Card Info form on my website?

### ISSUE THREAD

**Issue by itanhduy** [WordImpress/Give#2974]
## User Story
As an admin. I want to remove Credit Card Info form.

## Current Behavior
Currently it has been showing Credit Card Info form.

## Expected Behavior
I expect to remove this from on my website

## Possible Solution
Go to source code for removing it.

**Comment by DevinWalker** [comment]
Hi @itanhduy - please use our Support forum on WP.org for non-code support related questions like this: https://wordpress.org/support/plugin/give
