### ISSUE TITLE
fix(compat): correctly display Give Shortcode generator on category archive editor.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#2980]
## User Story

As an `admin`, I want `to be able to edit the category archive page when using the Genesis framework` so that `my readers see custom text on category archive pages.`.

Genesis adds a TinyMCE editor to individual category archive pages so that admins can create custom archives.

## Current Behavior
Currently, I navigate to Posts > Categories > _{some category}_ and the Give Shortcode generator is persistently expanded, covering part of the editor.

## Expected Behavior
I expect the shortcode generator to not cover the editor.

## Steps to Reproduce

1. Install the Genesis theme framework. https://drive.google.com/open?id=1KurDSWFvV8s0pvhcFbfTN7kfKGTzBiLz
2. Install and activate the Genesis child theme https://drive.google.com/open?id=1VZP3GZAJBaFnLubDrld1cBahrjlaQiWy
3. With Give active, navigate to Posts > Categories > Uncategorized (or any individual category in the list)
4. Scroll to the Archive Intro Text section.

The Give Shortcode generator is persistently displayed.

## Visuals

![screen shot 2018-04-02 at 11 28 52 am](https://user-images.githubusercontent.com/9629102/38202278-2f547406-3669-11e8-98fe-99511c9dbec4.png)

## Tasks
- [ ] 

## Help Scout issue
https://secure.helpscout.net/conversation/552264102/16202/

**Comment by mathetos** [comment]
I think this issue is more about preventing our Give Shortcode generator from appearing in unexpected TinyMCE editors. I believe there's a way to ensure it only appears on Post/Page edit screens, then we could add a filter for adding to CPTs as well. This probably needs some research.

**Comment by Benunc** [comment]
More insight from StudioPress support, if it is helpful:

> From troubleshooting, it seems that the plugin loads it's "Give Shortcodes" button on all admin pages where the visual editor is used. But it's necessary styles are not loaded on all those pages.
> 
> Specifically, the file "shortcodes.scss" ( /wp-content/plugins/give/assets/scss/admin ) is loaded on the post edit screen, but not on the category edit screen. If that code is included, issue is fixed.

**Comment by ravinderk** [comment]
@mathetos we already have a filter in core:[ `give_shortcode_button_pages`](https://github.com/WordImpress/Give/blob/36231565464706a8ebc00156ed1ab705c04b97fb/includes/admin/shortcodes/class-shortcode-button.php#L125) that ensure that shortcode feature will load only on allowed screens.

**Comment by mathetos** [comment]
@ravinderk Good to know. But in looking at that function, the shortcodes.css that @Benunc points out in his comment above isn't referenced in that function directly, which suggests it's entirely possible for the button to be output somewhere WITHOUT the corresponding stylsheet. So I guess the FIX for this issue is to enqueue the shortcodes.css file within that function so that the styles are ALWAYS output whenever the button is output as well.

**Comment by ravinderk** [comment]
@mathetos this issue has been resolved. If you want to show shortcode builder button then you can use filter hooks mentioned in https://github.com/WordImpress/Give/issues/2980#issuecomment-379626145

```
function give_add_button_on_cat_page( $pages ){
	$pages[] = 'term.php';

	return $pages;
}
add_filter( 'give_shortcode_button_pages', 'give_add_button_on_cat_page', 10 );
```

**Comment by mathetos** [comment]
Thanks @ravinderk I added that to our Snippet Library:
https://github.com/WordImpress/Give-Snippet-Library/blob/master/admin-functions/add-give-shortcode-builder-button.php
