### ISSUE TITLE
fix(admin-donation): Updating donor information does not update display on donations admin page

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#2985]
## User Story

As a site admin, I want to be able to update a donors information and when I view it from the donations page I am looking at the updated accurate information.

## Current Behavior
When a donors email address is changed the old email address still displays on the Donations admin page.

## Expected Behavior
I expect to update information on a donor and those changes be reflected when viewing the Donations page.

## Steps to Reproduce

1. Fresh install of Give in local.
2. Submit a donation with the wrong email address.
3. In the backend add the new (correct) email address and delete the old one.
4. Recalculate the information in Donations >> Tools >> Data.
5. In the Donations admin page, you will see the old email address displayed.
6. Generate a CSV export of the donation and the old email address will be output.

## Visuals
Incorrect email address on the Donations page:
![screen-shot-2018-04-02-at-2-54-39-pm](https://user-images.githubusercontent.com/20672471/38251142-a16fe5a6-371e-11e8-9288-f00982605536.png)

When donation is selected the email address is correct within the donation:
![screen-shot-2018-04-02-at-3-26-34-pm](https://user-images.githubusercontent.com/20672471/38251161-aac7b840-371e-11e8-8f4d-6159aea735e3.png)

## Related
- https://secure.helpscout.net/conversation/551334662/16142?folderId=1823994

## Environment

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: https://holtcommunityfoundation.local
Site URL: https://holtcommunityfoundation.local
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: page
Page on Front: Home (#7)
Page for Posts: Blog (#10)
Table Prefix Length: wp_xedw8t_
Table Prefix Length: 10
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: holtcommunityfoundation.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.6
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information❌Email access
Upgraded From: 2.0.3
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://holtcommunityfoundation.local/donate/donation-confirmation/
Failure Page: https://holtcommunityfoundation.local/donate/donation-failed/
Donation History Page: https://holtcommunityfoundation.local/donate/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Offline Donation, PayPal Standard, Test Donation
Default Payment Gateway: Offline Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Disabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Other Active Plugins ###

Transients Manager: by Pippin Williamson – 1.7.4

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.2
Duplicator: by Snap Creek – 1.2.34
Give - CSV Toolbox: by WordImpress – 1.0
Give - Form Field Manager: by WordImpress – 1.2.8
Give - PayPal Pro Gateway: by WordImpress – 1.1.4
Hello Dolly: by Matt Mullenweg – 1.6
My Custom Functions: by Arthur Gareginyan – 4.13
Page Links To: by Mark Jaquith – 2.9.10
Post SMTP: by Jason Hendriks, Yehuda Hassine – 1.8.3
Stop Signup Spam: by Leland Fiegel – 1.1.0
WordPress Force HTTPS: by A. Kai Armstrong – 0.1.3
WPForms: by WPForms – 1.4.5.2

### Theme ###

Name: Twenty Sixteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by ravinderk** [comment]
@samsmith89 
I think this is confusion from admin side basically ( information presentation issue). There is no way to change donation history and same for donation donor email.

Currently, we are showing donor primary email under donor information meta box on donation detail page instead of donation donor email which is creating confuse.

In above scenario admin just changed donor primary email and it is automatically appearing on donation detail page which is creating confusion for admin. Because on donation listing page, we are showing donation donor email but on donation detail page we are showing the primary email of the donor.

**Suggestion:**
1. Always show donation donor email on donation detail page and if different from donor primary email then show donor primary email in the bracket.

**Current**
![image](https://user-images.githubusercontent.com/1784821/38429974-983aaaf4-39dd-11e8-8efb-b41a2c6a7fa0.png)

**Suggestion**
![image](https://user-images.githubusercontent.com/1784821/38429919-7906aa0c-39dd-11e8-836d-30596ed4fc43.png)

2. It is possible that donor can type their personal information wrong which is first name, last name, and email, so we must give the option to edit donation history if donor request admin.

@DevinWalker let me know what do you think.

**Comment by DevinWalker** [comment]
## Response

I agree with @ravinderk - The donor's email entered on the donation payment should be there for historical purposes. If the donor later updates it, then display it in parenthesis like Ravinder has it shown.
