### ISSUE TITLE
Receipts Need More Details Specifically for Canadian Receipt Requirements

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#299]
This is also relevant for PDF Receipts, but we have some users who really need more detailed info on the receipts in order for their donors to have an official tax-deductible receipt. Specifically, this is the guideline for Canada:

http://www.cra-arc.gc.ca/chrts-gvng/chrts/prtng/rcpts/whtnf-eng.html

Since we don't require the donor address, the receipts by default wouldn't work for Canadian donors.

**Comment by mathetos** [comment]
Here's also a sample receipt:

http://www.cra-arc.gc.ca/chrts-gvng/chrts/pbs/rcpts-eng.html

**Comment by DevinWalker** [comment]
@mathetos please make sure the issues you create have more descriptive titles. This title `Receipts Need Attention` doesn't provide any meaningful info regarding to the exact issue with the receipts.

**Comment by mathetos** [comment]
Updated the title to more directly reflect the detailed info I provided in the above two comments.

**Comment by DevinWalker** [comment]
With the new version of PDF receipts coming out the objective is to have this type of capability easily achievable. I've created this issue over there here: https://github.com/WordImpress/Give-PDF-Receipts/issues/2

This is nearly achievable except for "Date receipt issued"

**EXAMPLE:**

```
Official Donation Receipt for Income Tax Purposes

Receipt # {payment_id}

Charity name
Charity address
Charity BN/Registration #123456

Date donation received: {date}

Donated by: {fullname}

Donor address:
{billing_address}

Eligible amount of gift for tax purposes:

Date receipt issued:______________________________________________________

Location receipt issued: Quebec, Canada
Authorized signature: LEAVE BLANK TO SIGN, ADD IMAGE or DIGITAL SIGNATURE JOHN DOE

For information on all registered charities in Canada under the Income Tax Act please visit: Canada Revenue Agency www.cra-arc.gc.ca/charitiesandgiving
```
