### ISSUE TITLE
feat(admin-tool): maximize extensibility of reports and exports pages/functionality

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#2996]
## User Story

As a `financial administrator`, I want `a single export that I can customize in whatever way I see fit, based on the add-ons I use, and the data that is most important to me` so that `I can save hours per report piecing together various information`.

Here's an actual email from an organization to their designer/implementor:

> One of the highest priorities with regard to the website right now is the need to have the Give plugin communicate more info to the gateways. Is this something you can request of the developers? This is really critical for us. Right now we have to pull at least 3 or 4 different reports in order to get all of the info we need (Give does not have fees, donation designations, or recurring gifts processed all on one report so we are forced to pull reports from 3 areas and piece them together using Excel formulas. It is literally costing us *hours* of work every time we want to enter data into our boxes. The solution is for Give to communicate to the gateways all important information such as:
> 
> 1) Fee paid by donor
> 
> 2) Designation of donation
> 
> 3) Recurring or not
> 
> If that could be sent directly to PayPal as a custom field, that would save us a lot of wasted effort and time. Is that something you can bring up to them?
> 
> One other critical piece of info is the donation ID. Some Give reports have it and some don't. You can imagine that when we're trying to pull info from multiple reports, it is extremely difficult when there is no unique identifier that is common on reports. The donation ID (not donor ID, but the ID for each specific transaction) would ideally be sent to the gateway along with the other info I listed below.

## Current Behavior
There are various reports that need to be pulled to integrate with other systems, and add-on-gathered data is not easily added to a report or export.

## Expected Behavior
They should be able to customize the reports in such a way as to get whatever they want, from tribute information, to fee recovery, to custom fields, to addresses, etc.

## Possible Solution
The client email above seeks to resolve the problem by sending all of the data to the payment gateway. I think the problem can be resolved by making the export functionality a bit more flexible and thorough. 

This is being handled in other issues, to be sure. For this issue my main concern is to audit the exports and the reports pages to ensure that they are extensible for use with all the add-ons, and the data that they collect. 

The user insight above is majorly helpful in getting to that end. Also, note that part of their frustration is related to Zapier being broken currently. All of the above can be done with a Zap, for sure, once that's resolved. 

Again, the main point of this issue is extensibility of reports and exports, not resolving her specific issues.

## Related
- https://github.com/WordImpress/Give-Tributes/issues/209
- https://github.com/WordImpress/Give/pull/2975

## Tasks
- [ ] check the exports and reports code to ensure that all necessary hooks and filters are there to allow for our add-ons or any others to add functionality and features as necessary. 

## Original Help Scout ticket
https://secure.helpscout.net/conversation/554917358/16433/

**Comment by DevinWalker** [comment]
Closing in favor of the epic: #3058
