### ISSUE TITLE
Odd donation total formatting

### ISSUE THREAD

**Issue by rosswintle** [WordImpress/Give#30]
Seen this in a couple of places and with different themes:

![screen shot 2015-03-16 at 18 59 23](https://cloud.githubusercontent.com/assets/1532368/6674041/ffb6d0da-cc0e-11e4-9f58-5421d5844304.png)

**Comment by DevinWalker** [comment]
Just wondering, which theme are you using?

**Comment by rosswintle** [comment]
Aaah. Are you using Bootstrap?

I was using a plain, un-customized [roots-sass](https://github.com/roots/roots-sass/tree/7.0.1) (now deprecated in favour of "Sage").

But here's the same in Twenty Fifteen:

![screen shot 2015-03-16 at 20 55 45](https://cloud.githubusercontent.com/assets/1532368/6676339/e33a3608-cc1e-11e4-8c92-bbd24006ffc5.png)
