### ISSUE TITLE
fix(i18n): Miscellaneous string updates based on translator feedback

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#3013]
## User Story

As an international Give user who translates the Give plugin strings, I want the English sentences to be constructed in a way that makes translations more correct and effective. 

As reported here:
https://wordpress.org/support/topic/questions-about-translation/

## Current Behavior
I currently struggle with the following strings:

[Text ID without group already exist](https://github.com/WordImpress/Give/blob/master/includes/class-give-translation.php#L144)
Should be:
> Text ID without a group already exists.

[Text ID with in group already exist](https://github.com/WordImpress/Give/blob/master/includes/class-give-translation.php#L153)
Should instead be:
> Text ID within a group already exists.

[There %1$s %2$s Give %3$s that %4$s to be updated](https://github.com/WordImpress/Give/blob/36231565464706a8ebc00156ed1ab705c04b97fb/includes/admin/upgrades/views/upgrades.php#L143)
Not sure exactly how to make this more translateable generally speaking, but it's currently basically impossible to do so reliably.

**Comment by ravinderk** [comment]
@mathetos what do you think about providing filter?

```
<?php
/**
* Filter the message
* 
* @since 2.0.1
*/
echo apply_filters(
	'give_plugin_update_now_notice',
	sprintf(
		__( 'There %1$s %2$s Give %3$s that %4$s to be updated. <a href="%5$s">Update now</a>', 'give' ),
		_n( 'is', 'are', $plugin_updates, 'give' ),
		$plugin_updates,
		_n( 'add-on', 'add-ons', $plugin_updates, 'give' ),
		_n( 'needs', 'need', $plugin_updates, 'give' ),
		$plugin_update_url
	),
	$plugin_updates,
	$plugin_update_url
);
?>
```

**Comment by mathetos** [comment]
@ravinderk No, it really needs to be available for translators to create .po files.

I'm wondering if the plurals can be handled like this: https://codex.wordpress.org/I18n_for_WordPress_Developers#Plurals
