### ISSUE TITLE
Change labels to "Donation Form" within admin

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#303]
Usability wise do you think it would be better to say "Donation Form" / "Donation Forms" in the admin like we did on the WP menus https://github.com/WordImpress/Give/issues/196? 

![10-6-2015 6-49-48 pm](https://cloud.githubusercontent.com/assets/1571635/10327339/13900a62-6c5b-11e5-975c-29f40dd157ff.png)

**Comment by pryley** [comment]
I would suggest just changing the label page titles and view button:

```
'name'               => __( 'Donation Forms' ),
'singular_name'      => __( 'Donation Form' ),
'add_new_item'       => __( 'Add New Donation Form' ),
'edit_item'          => __( 'Edit Donation Form' ),
'view_item'          => __( 'View Donation Form' ),
'not_found'          => __( 'No Donation Forms found' ),
'not_found_in_trash' => __( 'No Donation Forms found in Trash' ),
```
![image](https://cloud.githubusercontent.com/assets/134939/10335228/8d541aa0-6d19-11e5-99f3-a40de4474aca.png)

![image](https://cloud.githubusercontent.com/assets/134939/10335215/72bbdaf2-6d19-11e5-95ef-1cb0c5578de2.png)
