### ISSUE TITLE
Divi Theme and New Shortcode Builder Conflict

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#304]
**Reported:** https://wordpress.org/support/topic/give-plugin-messing-with-wordpress-text-editor?replies=2#post-7513446

**Screenshots:**

![unnamed 1](https://cloud.githubusercontent.com/assets/1571635/10329435/512833f2-6c76-11e5-9b55-0088e4e3774c.png)
![unnamed](https://cloud.githubusercontent.com/assets/1571635/10329436/51286a3e-6c76-11e5-89a1-db08c4b705b3.png)

**Comment by pryley** [comment]
From the screenshots it looks like a css rule conflict with the divi theme. I would have a look if I had access to the theme...

**Comment by DevinWalker** [comment]
I can send it to you for testing purposes

**Comment by pryley** [comment]
Great. I'm out right now, will take a look later today.
