### ISSUE TITLE
fix(donation): donation number on donation history page should not have # as prefix

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#3044]
## User Story
As a user, I want `#` as a prefix should be removed from donation number so that it looks consistent everywhere.

## Current Behavior
I currently have `#` as a prefix on donation number when viewed using donation history page.

## Expected Behavior
I expect to remove `#` as a prefix to donation number 

## Visuals
![image](https://user-images.githubusercontent.com/1852711/38792001-833bad00-4168-11e8-9e2e-bef192088e2b.png)

## Related
https://github.com/WordImpress/Give/issues/2977

## Tasks
- [ ] Remove `#` from donation id on donation history page.
- [ ] Testing ( on donation history page and email access page )

**Comment by ravinderk** [comment]
@mehul0810 This has been fixed.

For Ref: https://github.com/WordImpress/Give/compare/6df0ffb60a15...ae961363da30
