### ISSUE TITLE
feat(admin-exports): add "Currency Code" and "Currency Symbol" column to donation exports

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#3048]
@samsmith89 commented on [Wed Apr 11 2018](https://github.com/WordImpress/Give-Currency-Switcher/issues/106)

## User Story
As a site admin, I want to be able to export a CSV file with the donation amounts in the currency the donor gave in. Not just the Give base currency.

**Plan of Action**:

Add two columns "Currency Code" and "Currency Symbol"

Currency code is the 3-letter name of the currency such as USD or IND.

Currency symbol is the sign itself. For instance, "$".

## Current Behavior
I am currently only able to export in the base currency. When this is attempted with CSV Toolbox the original currency that the donor gave in is exported, but there is no indication which currency that is.

## Expected Behavior
I expect to have the ability to export in either the base currency or the donor selected currency.

## Related
https://secure.helpscout.net/conversation/558494575/16741?folderId=672194

---

@emgk commented on [Thu Apr 12 2018](https://github.com/WordImpress/Give-Currency-Switcher/issues/106#issuecomment-380748589)

## Call Summary
**Participants:** @emgk and @ravinderk 
**Topic:** Show currency in exported CSV.
**Result:** @ravinderk suggesting to make the change in Give Core to accomplish this issue, by adding a new standard column on export page _"Currency"_ so that if Admin wants to get the currency of each donation in CSV he will check this option. 

@DevinWalker @samsmith89 Let me know your thought on this.

---

@emgk commented on [Mon Apr 16 2018](https://github.com/WordImpress/Give-Currency-Switcher/issues/106#issuecomment-381860568)

@DevinWalker I need your reply on this so that I can fix this today.

---

@DevinWalker commented on [Mon Apr 16 2018](https://github.com/WordImpress/Give-Currency-Switcher/issues/106#issuecomment-381863968)

@emgk - yes I like your suggesting of adding a "Currency" column to the export. That's the best solution here is to resolve it in core.

**Comment by raftaar1191** [comment]
@DevinWalker @ravinderk @emgk 

## Summary 
As I read the call summary from @emgk between him and @ravinderk so I am only adding a **Currency** column, not the `Currency Symbol` column

**Comment by raftaar1191** [comment]
This issues will get fixed with #3047 

So the PR for the #3047 and https://github.com/WordImpress/Give/issues/3048 will be same 

Here is the PR link: https://github.com/WordImpress/Give/pull/3066

**Comment by raftaar1191** [comment]
Removing code related to issues https://github.com/WordImpress/Give/issues/3048 from PR https://github.com/WordImpress/Give/pull/3066 and sending a new PR for the issues

**Comment by raftaar1191** [comment]
This issues will get fixed with #3047

So the PR for the #3047 and #3048 will be same

Here is the PR link: #3066
