### ISSUE TITLE
fix(donation): prevent donation/donor spamming using minimal form data

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#3050]
## User Story
As a user, I want to prevent donation/donor spamming so that I don't get confused with actual and spam donations/donors.

## Current Behavior
I currently can see that donation/donor spamming can be easily performed by compromising the WordPress nonce as it has the validity of 24 hours.

## Expected Behavior
I expect to prevent donation/donor spamming

## Possible Solution
- Don't return gateway while validating donation form under fn `give_donation_form_validate_gateway`
- Add option to admin settings to limit the nonce lifetime

## Visuals
**Video:** https://drive.google.com/open?id=1-yPQNiFAzyb7Tt57HOWhahtpmWO5SK2B

## Related
- https://github.com/WordImpress/Give/issues/2930

## Tasks
- [x] Don't return gateway while validating donation form under fn `give_donation_form_validate_gateway`
- [ ] Add option to admin settings to limit the nonce lifetime
- [ ] Testing

**Comment by mathetos** [comment]
Since this is related to how we create sessions, I'm wondering if this is a related issue:
https://github.com/WordImpress/Give/issues/1630

**Comment by mehul0810** [comment]
@mathetos This is not related to Session Lifetime. We can have the nonce lifetime to reset the nonce on the specified interval. The default interval for the nonce to reset is 24 hours.

@DevinWalker I have already implemented the first task of this issue within #3035. Also, I had a discussion with @ravinderk over the call and we have decided to add a `Nonce Lifetime` setting under `Settings > General > Access Control`. However, can you let me know what are the lifetime values we need to provide such as 1 hour, 2 hours, 4 hours and so on? so that I can implement those values in a drop-down similar to Session Lifetime. Let me know your thoughts.

**Comment by mehul0810** [comment]
Closing this issue as per the discussion over the call with the team as `Nonce Lifetime` option is not useful to prevent spam and the `give_donation_form_validate_gateway` task is already completed within issue #3035 

However, we will keep an eye on the tickets related to donation/donor/user spam and make sure that, if required, we can implement the change in user workflow with Form API.
