### ISSUE TITLE
fix(admin-plugins): map_meta_cap notice on plugin disablement

### ISSUE THREAD

**Issue by squarecandy** [WordImpress/Give#3052]
## User Story

As a `developer`, I want `to alert you of this very minor bug` so that `you can fix it`.

## Current Behavior

When the plugin is enabled and then disabled the following notices are produced (showing on screen if WP_DEBUG is enabled).

> Notice: map_meta_cap was called incorrectly. The post type give_payment is not registered, so it may not be reliable to check the capability "read_post" against a post of that type. Please see Debugging in WordPress for more information. (This message was added in version 4.4.0.) in /var/www/[path_to_site]/wp-includes/functions.php on line 4147

## Expected Behavior

I expect to... have a clean set of user capabilities when the plugin is disabled.

## Possible Solution

Make sure to cleanup user roles and capabilities that require the give_payment custom post type in the deactivation routine.

## Steps to Reproduce

1. Install Give
2. Disable Give
3. Note error logs or see Dashboard meta box w/ WP_DEBUG turned on

## Environment

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: https://testwp.sqcdy.com
Site URL: https://testwp.sqcdy.com
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: Home (#3)
Page for Posts: News (#4)
Table Prefix Length: wp_aSpE_
Table Prefix Length: 8
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, acf-disabled, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: testwp.sqcdy.com
TLS Connection: Connection uses Err 0 The website calling howsmyssl.com's API has been making many calls and does not have a subscription. See https://subscriptions.howsmyssl.com/signup for how to get one.
TLS Connection: Notice:  Undefined property: stdClass::$rating in /var/www/testwp.sqcdy.com/public_html/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 199
Server Info: Apache/2.4.29 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/5.4.16
PHP Version: 5.6.32
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
PHP Max Upload Size: 128 MB
cURL Version: ❌ 7.29.0, NSS/3.28.4 - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.6
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information❌Email access
Upgraded From: 2.0.6
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://testwp.sqcdy.com/donation-confirmation/
Failure Page: https://testwp.sqcdy.com/donation-failed/
Donation History Page: https://testwp.sqcdy.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Offline Donation
Default Payment Gateway: Offline Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Disabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Other Active Plugins ###

Advanced Custom Fields: Font Awesome: by mattkeys – 2.1.2
Advanced Custom Fields PRO: by Elliot Condon – 5.6.10
Square Candy ACF Projects: by Peter Wise – 0.1
Square Candy Better YouTube: by Peter Wise – 0.1
Square Candy TinyMCE Reboot: by Peter Wise – 1.2

### Inactive Plugins ###

AJAX Thumbnail Rebuild: by junkcoder – 1.12
Classic Editor: by WordPress Contributors – 0.2
Disable Comments: by Samir Shah – 1.7.1
Give - Simple - Extra Email Fields: by Square Candy – 1.0
Give - Simple Anonymous Field: by Square Candy – 1.0
Give - Simple Candy Mail Checkbox: by Square Candy – 1.0
Give - Simple Note Field: by Square Candy – 1.0
Give - Stripe Gateway: by WordImpress – 1.5
Gutenberg: by Gutenberg Team – 2.6.0
Square Candy ACF Events: by Peter Wise – 0.1
Square Candy ACF SEO Plugin: by Square Candy Design – v1.1.0
Square Candy ACF Works: by Peter Wise – 0.1
SquareCandy Google Calendar: by Peter Wise (squarecandy) – 1.0.2
Square Candy VoteBuilder Events: by Peter Wise – 1.1
The Events Calendar: by Modern Tribe, Inc. – 4.6.13
TTT Crop: by 33 Themes UG i.Gr. – 1.0
WooCommerce: by Automattic – 3.3.5
WooCommerce Stripe Gateway: by WooCommerce – 4.1.0
Wordfence Security: by Wordfence – 7.1.2
WP Super Cache: by Automattic – 1.5.9

### Theme ###

Name: Twenty Sixteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment]
@DevinWalker I research on the issue and find it can not be fixed because of comment attached to `give_payment` post type. 
I did not find a reason why plugin user will want to deactivate plugin after running some campaigns.
If you do not want to use the plugin then take a DB backup and uninstall the plugin.

For Ref:
https://github.com/nanodesigns/nanosupport/issues/52
https://github.com/woocommerce/woocommerce/issues/9757
https://wordpress.org/support/topic/php-error-notices-on-main-dashboard-page/
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5808

**Comment by DevinWalker** [comment]
Thanks for researching @ravinderk
