### ISSUE TITLE
fix(donation): php warning on 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#3059]
## User Story

As a `admin`, I want `error free giving` so that `my error log is error free` and I can `trust the plugin devs`.

Currently there is an error displaying on donation forms:

`( ! ) Warning: Division by zero in /app/public/wp-content/plugins/give-recurring-donations/includes/give-recurring-helpers.php on line 1061`

![2018-04-17_21-45-05](https://user-images.githubusercontent.com/1571635/38912155-9fbc8b18-4288-11e8-9805-064d8539d4f3.png)

![2018-04-17_21-45-14](https://user-images.githubusercontent.com/1571635/38912156-a1149dc0-4288-11e8-8595-aeac41957313.png)

**Comment by ravinderk** [comment]
Issue moved to [WordImpress/Give-Recurring-Donations #582](https://github.com/WordImpress/Give-Recurring-Donations/issues/582) via [**ZenHub**](https://www.zenhub.com/)
