### ISSUE TITLE
feat(admin-email): improve management of contact info in emails

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#3070]
## User Story

As someone who builds many sites with Give, I want an easier way to define contact info across all email templates so that I don't have to update hard-coded information across several templates.

This user story is based on some excellent feedback from @slewisma:

> I've mentioned this one before but it bears repeating -- the placeholder offline mailing address lives in several places. It'd be nice to be able to change that once and have it correctly appear in both the email and on-screen instructions. Even more importantly though, it'd be really nice to have the updated versions become the starting point for any new forms where we need to customize the offline instructions on a per form basis. If all I need to change is what to write in the memo line on the check, it is inconvenient and a waste of time to have to also fix the address for each new form.

> Give takes the site URL and admin email as defaults during installation and puts them in email templates. More often than not I install on a temporary domain name to do development and design reviews with the client before launching live. I then have to remember all the places that this content has been used and go fix it. Site name behaves properly in that it gets the current name dynamically but links embedded in email template bodies and subject line, in one case for the email access template, use the original site URL and admin email until manually updated. This also dramatically lowers the productivity gain of using a site template system to create new sites. Additionally, it is hard to remember to check all these things and erroneous / donor-off-putting info may be in the email messages for weeks or months if we missed something during launch. Even changing from http to https at launch is affected by this issue!

> Since the email address that should be used for donations is often not that of the admin anyway, I suggest the best solution may be to ask for the correct address during setup and use it throughout (and if it is later changed, in one place, use the new address throughout). For the site URL, just use a template tag like you do for sitename. That will solve the problem and still let me replace it with a link to a specific page by removing the tag and adding my own link when needed.

## Acceptance Criteria

- [x] I can define the offline mailing address in one location within Give settings, and it is referenced within any email template or on-screen instructions that require it.
- [x] I can start a site locally and deploy it to a new URL without having to update every instance of the site URL within email templates.

## Related

- https://secure.helpscout.net/conversation/564771395/17221/?folderId=672199

**Comment by kevinwhoffman** [comment]
@slewisma Thanks again for the great feedback. I tried to distill it down into Acceptance Criteria. We'll move forward on this in an upcoming sprint.

**Comment by slewisma** [comment]
You're welcome. It is probable that some use scenarios will need different mailing addresses for offline for different forms so, to be clear, it is the default address when creating new offline directions for a new form that needs to inherit from the global settings. The person creating the form then still needs to be able to overwrite it. To that end, I might phrase "... and it is referenced within any email template or on-screen instructions that require it" in your acceptance criteria as "... and any new form's custom offline donation instructions will inherit the address as its default address. The user can then overwrite the address if necessary for the new form."
