### ISSUE TITLE
fix(admin-tool): removed currency html code from export column head

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#3072]
## User Story

As a `admin`, I don't want to see a `strange code` within my "Donation Total" column because it confuses me .

## Acceptance Criteria

- [x] I can see the "Donation Total" column head without the parenthesis and code

**Comment by raftaar1191** [comment]
This issues will get fixed with #3047

So the PR for the #3047 and #3072 will be same

Here is the PR link: #3066
