### ISSUE TITLE
fix(db-update): disable db upgrade notice on fresh install

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#3074]
## User Story
As an admin, I want to automatically perform database upgrades on a fresh install so that to improve UX.

## Current Behavior
I currently see a database upgrade notice on a fresh install in Give 2.1

## Expected Behavior
I expect to automatically run the DB upgrade on a fresh install.

## Possible Solution
Missed to add `v210_verify_form_status_upgrades` to `install.php`

## Visuals
![image](https://user-images.githubusercontent.com/1852711/39031622-02a1272a-4487-11e8-818e-f8ff31d6febf.png)

## Related
- https://github.com/WordImpress/Give/issues/2250

## Tasks
- [ ] add `v210_verify_form_status_upgrades` to `install.php` to run DB upgrade automatically on fresh install.

**Comment by raftaar1191** [comment]
## Finding 

@ravinderk 

Getting AJAX does not appear accessible error on frest install 
![image](https://user-images.githubusercontent.com/22215595/39497692-26e92fd0-4dc2-11e8-8f11-443caceaa63a.png)


Video Link: https://screencast-o-matic.com/watch/cFhV0ibqRn

**Comment by raftaar1191** [comment]
Slack Chat Summary

Participants: @devinwalker, @raftaar1191
Topic: Issues reason 
Result: We can close as this is not related to the server is because of the flywheel 
Chat Link: https://givewp.slack.com/archives/C0FAGC83C/p1525216116000221
