### ISSUE TITLE
Fatal error on list forms screen

### ISSUE THREAD

**Issue by rosswintle** [WordImpress/Give#31]
Created a form. Went off and did some other stuff. Came back to forms list. Saw this:

![forms_ _oikos_dev_ _wordpress](https://cloud.githubusercontent.com/assets/1532368/6674130/95e0a748-cc0f-11e4-97eb-63b62b72d39a.png)

You may want to note that I'm testing this on 4.2 latest nightly build. Don't know if that's having an impact here.

**Comment by rosswintle** [comment]
Apologies - it's a catchable fatal error - of course. A fatal one would have killed the rest of the page off. Still an error to be dealt with though!

**Comment by DevinWalker** [comment]
Related to #5

**Comment by DevinWalker** [comment]
This was resolved along with #20 with the taxonomy permission bug fix
