### ISSUE TITLE
Multiple billing fields being output when multiple forms on a single page

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#310]
**Scenario:** User has multiple donation forms on a page all with `Offline Donations` set as default gateway

**Problem:** Multiple `Billing Fields` are being output - super lame 

**SEE:**

https://wordpress.org/support/topic/billing-details-field-is-echoed-after-one-of-the-latest-updates?replies=3

![10-7-2015 5-20-01 pm](https://cloud.githubusercontent.com/assets/1571635/10354729/e83fec2a-6d17-11e5-92e6-3c94dc443e78.png)
![10-7-2015 5-20-16 pm](https://cloud.githubusercontent.com/assets/1571635/10354730/e8415ccc-6d17-11e5-8a24-8708f176b677.png)

**Comment by DevinWalker** [comment]
This doesn't seem to be happening with other gateways such as PayPal Pro and Stripe

**Comment by DevinWalker** [comment]
Ok this is fixed

**Comment by mathetos** [comment]
Super weird. Nice sleuthing on this one.
