### ISSUE TITLE
fix(admin-setting): Make Next Donation Number update in Live Preview immediately like other settings

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#3116]
## User Story

As a Give admin, I want to see my "Next Donation Number" update correctly in the sequential ordering settings so that I know what to expect for my donation IDs.

## Current Behavior
Currently, the "Next Donation Number" only updates in the preview if you force an update in another setting. See here:
![givewp-so-preview-bug](https://user-images.githubusercontent.com/930724/39254839-f255931a-485f-11e8-9dc8-4cb4771eb525.gif)

## Expected Behavior

I expect it to update immediately like the other settings do.

## Steps to Reproduce

1. Enable Sequential Ordering
2. Update the "Next Donation Number" and confirm that the preview doesn't update
3. Update the Prefix and you'll see the Next Donation now reflected in the preview correctly.

**Comment by ravinderk** [comment]
@mathetos Can you test `release/2.1` again?

![efhlstdtrv](https://user-images.githubusercontent.com/1784821/39259698-c0f51dde-48d4-11e8-92fb-8a40ecabfd0b.gif)

**Comment by mathetos** [comment]
@ravinderk No change. Downloaded lastest from 2.1 branch, ran composer/npm, run dev, same result.

**Comment by kevinwhoffman** [comment]
Closing as @ravinderk has addressed @mathetos original concerns.
