### ISSUE TITLE
fix(admin-tool): fix typo in filter declaration  

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#3120]
## User Story
As a `Developer`, I want to replace all the custom string with donor string 

## Current Behavior
I currently see the customer word in the filter 

## Expected Behavior

I expect the filter name should contain donor not customer 

## Screenshot 

Video Link: https://screencast-o-matic.com/watch/cFfO1kbIrE

How it used to be in 
![image](https://user-images.githubusercontent.com/22215595/39289524-298aace0-494a-11e8-8285-2d13cbf34c2b.png)

how it is in Give Core 2.1
![image](https://user-images.githubusercontent.com/22215595/39289589-64f357aa-494a-11e8-9d69-147197fefc3d.png)

**Comment by ravinderk** [comment]
@raftaar1191 issue is with the placement of a deprecated filter in an array, so by logic deprecated filter name will be in value and new filter name will be set as key in the array.

for ref: https://github.com/WordImpress/Give/blob/release/2.1/includes/deprecated/deprecated-filters.php#L22
