### ISSUE TITLE
Break up actual form HTML into template files

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#313]
Right now we have a lot of HTML within https://github.com/WordImpress/Give/blob/master/includes/forms/template.php that needs to be broken down into separate form template parts which can be overwritten as expected. 

The only way currently to edit the html within now is via filters which is cumbersome and hard to work with at best.

**Comment by mathetos** [comment]
Agree strongly!

**Comment by DevinWalker** [comment]
One issue I'm running into is how to properly pass variables into the template files

**Comment by DevinWalker** [comment]
We were talking about this and are still in discussion as to whether it would be a good idea to actually break up the sensitive field markup for donation forms.

**Comment by DevinWalker** [comment]
Rather than breaking these up into templates I'd rather pass content through the necessary hooks with usable variables and provide tutorials. It's too easy to break Give in it's current form if we allow template customizations when we haven't made made a11y changes and theme rollouts (still in discussion). Closing this issue until future discussions.
