### ISSUE TITLE
feat(form): ensure w3c validations for donation forms' <form> ID to resolve Stripe Elements issue

### ISSUE THREAD

**Issue by mehul0810** [WordImpress/Give#3139]
## User Story
As a developer, I want to have donation forms to be w3c validated so that forms are developed with best practices and can show the quality.

## Current Behavior
I currently can see there are lots of w3c validation issues with donation forms when there are multiple forms on a single page. 

## Expected Behavior
I expect to see w3c validated donation forms.

## Possible Solution
In General, all the id's should have `-<type>-<form_id>` appended. In this way, we can deal with the situation where there are same forms multiple times on a single page.

For example,
1. Shortcode can have ids like `give-form-shortcode-1192`
2. Widgets can have ids like `give-form-widget-1192`
3. Single pages can have ids like `give-form-<form_id>`

## Related
- https://github.com/WordImpress/Give/issues/2905
- https://github.com/wordimpress/give/issues/1570
- https://github.com/wordimpress/give/issues/1457

## Tasks
- [ ] Reproduce issue after adding multiple donation forms on a single page
- [ ] Find the area of improvements and fix it
- [ ] Testing

**Comment by DevinWalker** [comment]
We have lots of duplicate IDs which is what we're going to address in the new forms API when it's fully planned. Prior to that and to resolve https://github.com/wordimpress/give-stripe/issues/178 I like the possible solution by @mehul0810 - if it's not possible to detect shortcode vs widget then we can simplify the IDs like `give-form-123-1`, `give-form-123-2`. However, it would be much more useful to have more specific IDs. I also don't want to break our current CSS in core. We will likely break some user's CSS targeting specific IDs but that's just what we have to do to get more compliant and ensure Stripe Elements works properly.

**Comment by slewisma** [comment]
Making the ID form-instance specific should be fine. As @DevinWalker said, some user CSS might get broken but they can fix this pretty easily since the form id is also in the class. I'm commenting only to point out that the class should stay as it is now while the id changes to become form-instance specific. That way the user can target all instances of the form with CSS by using the class. Very similar to how WP adds attachment id as a class on images (but without the image size part). 

To expand on Devin's example:
`<form id="give-form-123-1" class="give-form give-form-123 give-form-type-multi" .....`

**Comment by ravinderk** [comment]
@DevinWalker I found `26`  duplicated ids in HTML of the donation form.
I think we can set up only one unique id (highlighted in below image) and update js API to access any field selector or information for any specific form.

![image](https://user-images.githubusercontent.com/1784821/39853221-7d6c38fc-543e-11e8-919f-873101f3aba7.png)

**Comment by mehul0810** [comment]
@DevinWalker @ravinderk I've created a PR (i.e. https://github.com/WordImpress/Give/pull/3209) for solving Stripe Elements issue. So, don't close this issue as the main goal of this issue is not fully achieved yet.

**Comment by DevinWalker** [comment]
Closed this so we can shift focus soon to the new form builder + API

**Comment by raftaar1191** [comment]
@mehul0810 I can still see duplicate ID attribute when testing by calling the same shortcode 3 times on the same page.
But I guess  this we will taken care when updating the form API


![image](https://user-images.githubusercontent.com/22215595/40435157-ad4f3418-5ecd-11e8-9ba0-6c86bcf8e796.png)

![image](https://user-images.githubusercontent.com/22215595/40435169-b5c93bac-5ecd-11e8-9bfa-e4b2118df9ac.png)
