### ISSUE TITLE
Add Form Name or ID to CSV Export

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#314]
Currently, CSV exports only support "Name", "Email", "Total Donations", and "Total Donated". It would be useful to add either Form ID or Form Name.

![csv-report-missing-form-name-id](https://cloud.githubusercontent.com/assets/930724/10358341/0767d1d8-6d42-11e5-96cd-c8cc28b66012.jpg)

**Comment by mathetos** [comment]
Mentioned in this ticket:
https://givewp.com/support/ticket/issue-w-reports-request-for-new-one/#post-5974

**Comment by DevinWalker** [comment]
:+1:

**Comment by DevinWalker** [comment]
The form ID or title can't be output on the report you show because it displays "Total Donations" - however, the report it can be output on is the  "Export Donation History - Download a CSV of all donations recorded." report

**Comment by DevinWalker** [comment]
Ok I've fixed up this export so it's much nicer now and includes form ID and form title:

![10-16-2015 10-48-19 am](https://cloud.githubusercontent.com/assets/1571635/10549044/7ce40ad2-73f3-11e5-91ca-1505fb818d4d.png)
