### ISSUE TITLE
fix(admin-plugins): display activation banner immediately upon activation refresh

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#3153]
## User Story

As a `admin`, I want when I `activate an addon` that I `see the activation banner immediately` so that I `can quickly access settings`. Right now it's not displaying until I `manually refresh` the plugin listing page.

## Acceptance Criteria

- As an `admin` I can activate the plugin and 

## Visuals

See video: https://goo.gl/eevv6v

**Comment by raftaar1191** [comment]
## Finding 
When activating the Give Add-on one by one it does not show me the message activation banner for both in fact it hides the last one and show the latest add-on notices which are been activated 


Video link: https://screencast-o-matic.com/watch/cFhf0sbZIn


Example: In Give  Core 2.0 it used to show Activation banner for all the add-on 
![image](https://user-images.githubusercontent.com/22215595/39657261-e8b818ca-5023-11e8-9292-59f4f134c6dc.png)


Expected in Give Core 2.1.2
![image](https://user-images.githubusercontent.com/22215595/39657321-6d3b1d68-5024-11e8-9488-91aac30ca655.png)

**Comment by DevinWalker** [comment]
Yeah that's intentional @raftaar1191 - no need to reopen.

**Comment by raftaar1191** [comment]
Slack Chat Link: https://givewp.slack.com/archives/C0FAGC83C/p1525478063000074

**Comment by DevinWalker** [comment]
Reopening pending ongoing review after speaking with @raftaar1191
