### ISSUE TITLE
fix(form): allow set donations with custom amount disabled

### ISSUE THREAD

**Issue by kevinwhoffman** [WordImpress/Give#3178]
## User Story

As a donor, I want to complete a form with a single set donation option so that my donation completes.

## Acceptance Criteria

- [x] I can make a donation to a form with set donations and custom amount disabled.
- [x] This solution does not negatively affect other form settings.

## Current Behavior

I currently cannot donate on any form in `2.1.1` that has a single set donation with custom amount disabled.

## Expected Behavior

I expect to complete the donation.

## Steps to Reproduce

1. Create a new form in Give `2.1.1`.
2. `Donation Option`: `Set Donation`
3. `Custom Amount`: `Disabled`
4. Attempt to donate.

### Settings to Recreate the Issue
![image](https://user-images.githubusercontent.com/1938671/39646914-02671128-4fab-11e8-90f5-e585080b0587.png)

## Related

- #3159 
- #3160 
- #3174

**Comment by DevinWalker** [comment]
This has been resolved in https://github.com/WordImpress/Give/pull/3174
