### ISSUE TITLE
fix(donation): auto select the default level when donation form load for the first time 

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#3184]
## User Story

As a `donor`, I want the default level that is being set from the admin dashboard should be selected when the window loads up for the first time.

## Current Behavior

I currently not see any default level selected when donation form loads up  

## Expected Behavior

I expect that default level should be selected when donation form load up for the first time 

## Steps to Reproduce
1. Create a donation form with donation option as multi-select 
2. view the donation form in frontend you will see the default level that was being selected from the backend was not getting high lighted 

## Visuals
![image](https://user-images.githubusercontent.com/22215595/39654913-b0c3e426-5014-11e8-8542-a2c2faa70d38.png)

![image](https://user-images.githubusercontent.com/22215595/39654936-ce111076-5014-11e8-9d0b-c1e447d15df5.png)

**Comment by DevinWalker** [comment]
@raftaar1191 we're just going to allow themes to handle this with the `give-default-class`. I don't think your PR addresses it correctly using CSS which can cause lots of issues with themes.
