### ISSUE TITLE
Integrate "Send System Info" into our "System Status" tab

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#319]
This plugin does the same basic things our "System Status" tab does, but adds two unique features that would be VERY beneficial:
1. Allows the user to email the system info directly from that page (I'd suggest we hardcode our support email address rather than ask them to type it in)
2. Provides a public link to view the system info from instead of Emailing it.

We should dig into how secure that public link is, but these would both help our Support setup a lot.

https://wordpress.org/plugins/send-system-info/screenshots/

**Comment by DevinWalker** [comment]
I'm bumping this up because this can be really helpful for support

**Comment by DevinWalker** [comment]
Bah, I just looked at it and it's a bit more complicated... bumping back.

**Comment by mathetos** [comment]
Ha! I did the same thing... I thought, Oh I'll just grab some of those functions... nope.

**Comment by DevinWalker** [comment]
@mathetos what's the plan on preventing spam submissions? I suggest we ask for people to enter an email that we provide them. Any other ideas?

**Comment by mathetos** [comment]
Well, with our current setup, if we provide the email sending method in general, then it'll always be separated from the actual support request. So I'm now not a big fan of the email option. I'd rather encourage just the download or the static link. I like the static link a lot because they can easily disable it later so it's not public on the .org Support Forum.

**Comment by DevinWalker** [comment]
With the latest update to our system info by @kevinwhoffman in `release/1.8` it's much easier to copy and paste into the support request form:

![2016-11-16_14-50-08](https://cloud.githubusercontent.com/assets/1571635/20369108/19fb683c-ac0c-11e6-810b-4b28504c4fcb.png)
