### ISSUE TITLE
fix(give-api): Make Earnings and Donations Types Respect Daterange as intended

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#3191]
## User Story

As a `Give Admin`, I want to pull data from Give over the API within a specific range. Currently, according to the [online documentation](https://givewp.com/documentation/developers/give-api-reference/), I should be able to do that with the `stats` endpoint, and either the `donations` or `earnings` types. 

But that doesn't seem to be the case currently. 

## Current Behavior
I currently am trying to get that information with the following URL:

https://givewp.com/give-api/v1/stats/?key=<my_key>&token=<my_token>&form=173418&date=range&startdate=20180504&enddate=20180506&type=earnings

But this is the result:
```
{
    "earnings": [
        {
            "multiple-payment-gateways": "3410"
        }
    ],
    "request_speed": 0.017750024795532
}
```

Here's the form in the Admin:
![image](https://user-images.githubusercontent.com/930724/39728089-2fa44b68-520a-11e8-8d0c-5ca86a593e38.png)

You can see that the API response is just giving me the TOTAL earnings, not the earning respective of the daterange I entered. 

## Expected Behavior
I expect to be able to query a specific form, and for a specific date-range, get the following information:
* The income raised during that date range
* The number of donations received in that date range
* Potentially a list of donors who gave to that form in that date range.

It's possible all those things are already possible with the API, and our Documentation is just wrong -- but I don't believe so because I inspected the code pretty closely too. 

## Steps to Reproduce
1. #GiveTeam members can use their Givewp.com account to query that URL above with their own unique key and token.
2. Try different query parameters according to the code.

## Related
_Internal links for #GiveTeam members only_
- Customer report: https://secure.helpscout.net/conversation/575937874/18018/

**Comment by ravinderk** [comment]
Reopening this issue because in ` Donations` Types  date range not working as intended
