### ISSUE TITLE
feat(admin-form): Ability to toggle a per form Test Mode 

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3196]
## User Story
As a site admin, I want to put a particular form into Test Mode so that I can troubleshoot Give issue while leaving my other forms in Live mode and able to take donations.

## Current Behavior
I currently have to put the whole installation in Test Mode.

## Expected Behavior
I expect to switch to Test Mode on one form.

## Related
https://secure.helpscout.net/conversation/576446410/18068/

**Comment by mehul0810** [comment]
I'm linking the existing duplicate issue https://github.com/WordImpress/Give/issues/2254 for reference which is now closed due to major changes in Give core and all the add-ons.

**Comment by DevinWalker** [comment]
Closing as duplicate. While seemingly it would be helpful, it's just a major undertaking and we can rather use staging/dev sites.
