### ISSUE TITLE
Various fails with out-of-the-box settings

### ISSUE THREAD

**Issue by rosswintle** [WordImpress/Give#32]
So, I'm kinda testing what could be an "edge case" of just install the thing, don't do any settings or config, and just go ahead and create a form.

I think there's numerous bugs in the area. I'm not sure how you want to handle this. Refuse to display any forms until settings are done? Or catch the errors as and when they occur.

For this one I created a simple form with a set donation that could be customised by the user.  I've got "Offline donation" and "Test donation" payment methods set up. Here's the top part of the form:

![screen shot 2015-03-16 at 19 13 27](https://cloud.githubusercontent.com/assets/1532368/6674333/cd8cfeac-cc10-11e4-92b2-d3d623e24553.png)

I filled in the form and clicked donate and I got sent to `/donations/set-donation/?payment-mode=offline` which gave me a screen showing this:

![screen shot 2015-03-16 at 19 15 37](https://cloud.githubusercontent.com/assets/1532368/6674351/e2ad53fe-cc10-11e4-88c3-581bb8f30a2f.png)

That looks like a var_dump to me. Debug info? Possibly printing the post ID of the donation?  Looks like it - the details link for the donation is: `http://plugindev.localnet/wp-admin/edit.php?post_type=give_forms&page=give-payment-history&view=view-order-details&id=60`

Here's my settings screen - I suspect it's related!

![screen shot 2015-03-16 at 19 17 40](https://cloud.githubusercontent.com/assets/1532368/6674391/2925db6c-cc11-11e4-9901-96dd6d2f53cc.png)

**Comment by DevinWalker** [comment]
Yup definitely a debug still in there... Thanks again for the excellent description. This immediately let's me know how to go about tackling the bug.

**Comment by rosswintle** [comment]
Great working with other dev's, huh?

Probably would have been quicker to submit a patch! :wink:

**Comment by DevinWalker** [comment]
Fix for this coming now.
