### ISSUE TITLE
$0.00 Donations are going through when Display Method is "Show on Page"

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#320]
Even though the Amount field properly shows an error when "$0" is entered as a Custom Amount, when the form is set to show the payment fields directly on the page, the donation can still go through successfully. 

When the display method is set to "Reveal upon Click" or "Modal Window Upon Click" the payment fields DO NOT trigger. 

Reported here: https://wordpress.org/support/topic/minimum-donation-requirement-or-invalid-submission?replies=1#post-7524905

Verified locally with the following Gateways: "Test Donation", "Offline Donation", "Dwolla", "Stripe"

**Solution:**
Add error checking for the minimum $1 amount to the "Donation Complete" button in addition to the Modal/Reveal trigger button.

**Comment by DevinWalker** [comment]
**Solution Proposal:**

- [x] Add server side validation for amount on frontend donation form validation
- [ ] Help users out an set amount to 1.00 for new form creation
- [ ] Add admin validation that amount is above 0.00 for forms

... Anything else I'm missing?

**Comment by DevinWalker** [comment]
Are there any considerations you can think of that would make this added validation undesirable for a large portion of users?

**Comment by mathetos** [comment]
I think as long as this functionality is also relatively easily overwriteable with actions/filters then we're good. There's a use case for asking for an "optional" donation. That's a totally separate issue, but I hope what is done here doesn't complicate that down the line.

**Comment by DevinWalker** [comment]
Ok here's how it works:

* Default amount for new forms in 1.00
* 0.00 donation amounts will ***not*** go through in LIVE mode
* 0.00 donation amounts ***will go*** through in TEST mode
* 0.00 amounts CAN still be saved in the admin - reason below

I don't this it's a good idea to prevent users from saving forms as 0.00 because it can get complicated with varying currency formats and some users may want to test with 0.00 amounts for various reasons. LMK what you think about this

**Comment by DevinWalker** [comment]
![10-14-2015 8-05-26 pm](https://cloud.githubusercontent.com/assets/1571635/10503857/04bf4e26-72af-11e5-9e26-d0d3be0bad5f.png)

**Comment by mathetos** [comment]
So, in summary, the solution is that donations done in TEST mode (meaning Offline, Stripe, Test Donations, etc) can go through at 0.00, but LIVE donations will NOT go through for $0.00. But why would we allow the default amount to be $0.00 for live donations then?

**Comment by DevinWalker** [comment]
0.00 won't go through on live donations - see validation screenshot above

If a transaction is 0.00 is test mode it will automatically be marked as manual/test gateway - nearly all payment gateways won't allow you to test with 0.00 amounts so they're bypassed entirely

**Comment by DevinWalker** [comment]
Fixed as of 1.3.1
