### ISSUE TITLE
fix(donations): resolve often reported "Error: Nonce verification has failed."

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#3200]
## User Story

As a `donor`, I want `give` without seeing a `nonce verification` error.

## Current Behavior

This has been reported often on WP.org

https://wordpress.org/support/topic/error-nonce-verification-has-failed-4/

## Steps to Reproduce

I'm not sure at the moment. More info is needed. @mathetos do you know how we can reproduce this issue?

## Possible Solution

Caching issues.

**Comment by mathetos** [comment]
We've been getting these regularly since 2.1 was released, and I have not been able to replicate. The only one we fixed so far was the one where they had pasted the form html directly into a page builder text module.

**Comment by DevinWalker** [comment]
We've been getting them a lot since it was introduced within pre-2.1. I've seen more than a couple of support requests started on WP.org about it: https://wordpress.org/search/nonce+intext%3A%22Plugin%3A+Give+-+Donation+Plugin+and+Fundraising+Platform%22/?forums=1

@ravinderk please review the support requests and attempt to reproduce on your end. If you can't within a reasonable amount of time then we can move on.

**Comment by mehul0810** [comment]
I'm facing `Nonce verification failed` issue with latest release 2.1.3 which is resetting the nonce every couple of minutes.

![image](https://user-images.githubusercontent.com/1852711/40172706-144a753c-59ed-11e8-9a7a-121354e39fe2.png)

**Comment by mehul0810** [comment]
Closing this issue as it is working fine for me now.

**Comment by jb510** [comment]
I'm still seeing this problem with GiveWP forms on a site hosted on WP Engine.

Excluding the pages from the cache individually (WPE Portal > Advanced Utilities (not available in all accounts but you can contact support and they'll put in cache exclusion rules for you).

Usually on WPE DONOTCACHEPAGE works...  I see the code is at least trying to set that, not sure if it's not working or something else is going on.

![2018-12-10 at 4 59 pm](https://user-images.githubusercontent.com/801241/49767163-10663980-fc9d-11e8-8d0e-baa511c134cc.png)

**Comment by ravinderk** [comment]
@jb510 We added a fix for that issue in `release/2.3.1` and planning to release it soon. for ref: https://github.com/impress-org/give/issues/3820
