### ISSUE TITLE
fix(currency-switcher): amount should be formatted based on the currency I switched into.

### ISSUE THREAD

**Issue by emgk** [WordImpress/Give#3203]
## User Story
As a `Developer`, I want `to use the form's currency format setting to format the various amount inside the verify min/max amount and when displaying the amount in the price level element` so that `I can see the correct donation amount in the currency I have switched into`.

NOTE: Related to currency-switcher.

## Current Behavior
1. When verifying the min/max amount it is sanitizing the amount based on the Give's base currency. 
2. If the currency is auto-switched to another preferred currency then the amount is appearing in Give's base currency format.

## Expected Behavior 
1. min/max amount should be sanitized from the switched currency.
2. If the currency is auto-switched to another currency then, the variable amount should appear in that switched currency.

## Related
- https://github.com/WordImpress/Give-Currency-Switcher/issues/137

## Tasks
- [x] Pass the currency when displaying the variable amount.
- [x] Add new filter to the verify min/max amount to re-verify the amount through any add-on.

**Comment by mehul0810** [comment]
I'm facing a minimum amount for this form issue as shown in the screenshot. So, reopening this issue.
![image](https://user-images.githubusercontent.com/1852711/40170533-432543c0-59e6-11e8-9bbe-435eed314aa0.png)

**Comment by emgk** [comment]
The logic of verifying the min/max amount isn't correct. re-opening.
