### ISSUE TITLE
fix(compat): beaver builder conflict preventing from seeing page builder element on backend.

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#3207]
## User Story

As a `admin`, I want to use `give alongside beaver builder` so that `I can build my site`.

## Current Behavior

**Give Activated**
![with-give](https://user-images.githubusercontent.com/1571635/39896508-38d65efa-5463-11e8-8f93-a9ff80828e5f.png)

**Give Deactivated**

As reported here: https://wordpress.org/support/topic/beaver-builder-conflict-3/#post-10267960

**Comment by raftaar1191** [comment]
Beaver Builder Plugin Link: https://wordpress.org/plugins/beaver-builder-lite-version/

Slack Chat summary: https://givewp.slack.com/archives/C0FAGC83C/p1527056672000318
