### ISSUE TITLE
Fatal error when accessing donate page with theme that includes CMB2.

### ISSUE THREAD

**Issue by wesleycole** [WordImpress/Give#321]
We are building a theme that has CMB2 installed as a plugin and receive the following fatal error when trying to access a page that has a Give form shortcode on it. 

Fatal error: Cannot redeclare cmb2_dir() (previously declared in /Volumes/Seagate Backup Plus Drive/MAMP/htdocs_academy/wp-content/plugins/cmb2/includes/helper-functions.php:18) in /Volumes/Seagate Backup Plus Drive/MAMP/htdocs_academy/wp-content/plugins/give/includes/libraries/cmb2/includes/helper-functions.php on line 20

**Comment by DevinWalker** [comment]
Hey @wesleycole - can you let me know how your theme is including CMB2?

**Comment by wesleycole** [comment]
Ah yes, sorry for not including that. 

It is installed as a plugin, version 2.1.2.

Thanks!
-- 
Wes Cole

On October 12, 2015 at 4:02:29 PM, Devin Walker (notifications@github.com) wrote:

Hey @wesleycole - can you let me know how your theme is including CMB2?

**Comment by wesleycole** [comment]
@DevinWalker that fixed it up. Thanks for the help!

**Comment by DevinWalker** [comment]
Hey no problem! Thanks for reporting it :+1:
