### ISSUE TITLE
Add a setting to cap total amount one donor can give per calendar year

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#322]
Political campaigns have strict limits on how much one donor can give to a campaign per calendar year. It would be useful for them if we had the ability to add a setting that would do this. Something to this effect:

1. Donation form requires a login (the feature doesn't work without requiring a login)
2. When the donor is logged in, they would see an alert at the top of the form saying:
* "You have currently donated [$2,000 of the $5,000] you are legally allowed to donate for the [2015] calendar year."
* Or... "You have donated $5,000 this calendar year already. You legally cannot donate any more to our campaign. We appreciate your generosity greatly"
And the form would then be greyed out.

This would be enabled per form with the following options:
* Enable Annual Donor Cap? True/False
* If "True" then show a text field: "Enter the Annual Donor Cap amount:
* If "True" then also show a textarea to customize the "Capped" alert text.

This could be Addon territory just because the majority of users won't need it.

**Comment by DevinWalker** [comment]
I agree this should be add-on territory

**Comment by DevinWalker** [comment]
Closing until we can figure this out in Add-on territory ;)
