### ISSUE TITLE
Need HTML for Terms&Cond Agreement Label for GDPR

### ISSUE THREAD

**Issue by Champdor** [WordImpress/Give#3225]
## User Story
For GDPR compliance I have to get consent from the donor to handle his/her personal data. According to GDPR guidelines I have to include a link of our Privacy Policy as close to the checkbox as it can be. The simplest way for it would be Terms & Conditions tab / Agreement label would accept HTML code, not just plain text. This way I could include the link in the label.
(Please be graceful if mix up something, this is my first GitHub post ever.)

## Current Behavior
Currently I have to include the link in the Show Terms text which is one more click away from the checkbox. I'm afraid it is too far and does not comply with GDPR. Besides it is not good for UX if it's opening upwards (confusing).

## Expected Behavior
I expect the following:
1. Terms & Conditions tab / Agreement label: accepts HTML
2. Have an option to enable/disable Show Terms link.

## Possible Solution
Develop the above functions.

## Steps to Reproduce
1. Open page:  https://alapitvany7618.positivedesign.hu/en/help-us/donation/
2. Click on 'Show Terms'

## Tasks
1. Terms & Conditions tab / Agreement label: accepts HTML
2. Have an option to enable/disable Show Terms link.

**Comment by mathetos** [comment]
Hi @Champdor -- congrats on your first Github issue, we're honored it's for Give!

We are working on a comprehensive strategy for addressing GDPR in Give and this will definitely be part of that strategy as well. In the short-term, we'll look into a workaround for this feature for you as well. 

We'll be updating our Github repo with GDPR issues soon as well.

Thanks!

**Comment by mathetos** [comment]
Another report of this here:
https://wordpress.org/support/topic/gdpr-opt-in-check-boxes/
