### ISSUE TITLE
Defaulting to 0.00? 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#323]
Verify default level isn't defaulting to 0.00 for multi-level donations:

![10-13-2015 8-48-03 pm](https://cloud.githubusercontent.com/assets/1571635/10474466/e9d32a10-71eb-11e5-8cb1-9fde0e0b4b19.png)

**Comment by mathetos** [comment]
Duplicate of #320

**Comment by DevinWalker** [comment]
I can't reproduce the default amount not being set by default - will keep an eye out for it. Not totally related to #320 but close

**Comment by mathetos** [comment]
Ah... I think I misunderstood this issue. Those are two different issues. Got it.
