### ISSUE TITLE
Custom Fields data isn't saving to the Database since version 1.3

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#324]
Most likely this is just a matter of updating our Docs with current information so that the API picks up the data correctly, but as of the 1.3 update Custom Field data is no longer passed to the API.

I have a feed I can show, but won't do that publicly here since it holds names and email addresses and donation data. But it clearly shows that a custom field, created based on our docs, was sending the data to the API correctly, up until the latest update.

Here's a modified example:
**CORRECT BEFORE THE UPDATE:**
`"payment_meta": {
                "currency": "USD",
                "guests": "Guest1 Guest2 Guest3"
            }`

**INCORRECT AFTER THE UPDATE**
`"payment_meta": {
                "currency": "USD",
                "guests": ""
            }`

**Comment by mathetos** [comment]
Actually, just checked the Database and the issue is that Custom Fields (according to our docs) aren't being saved correctly anymore since the update. So that data is just not in the database at all. 

@DevinWalker Do you have any insight on what changed that would prevent the custom data from saving to the database? 

This is the code based on our documentation:

```
function give_myprefix_store_custom_fields( $payment_meta ) {
	$payment_meta['referral'] = isset( $_POST['give_referral'] ) ? implode( "n", array_map( 'sanitize_text_field', explode( "n", $_POST['give_referral'] ) ) ) : '';

	return $payment_meta;
}

add_filter( 'give_payment_meta', 'give_myprefix_store_custom_fields' );```

**Comment by DevinWalker** [comment]
I just tested an see it's working with the plugin code you provided:

![10-14-2015 10-48-40 am](https://cloud.githubusercontent.com/assets/1571635/10492481/3d4216e6-7261-11e5-9542-7b67309e84a0.png)

**Comment by mathetos** [comment]
OK, I'll have to do deeper testing of my environment. The thing is that nothing changed in my code. The only thing that changed was that I updated Give Core. Still... I'll circle back on this and either close it out or create an updated ticket with the specific issue.

**Comment by DevinWalker** [comment]
Ok cool

**Comment by DevinWalker** [comment]
Just double-checked that the fields were also showing in the API: 

![10-14-2015 11-00-12 am](https://cloud.githubusercontent.com/assets/1571635/10492820/d445122c-7262-11e5-8bff-6e5af38fc496.png)

**Comment by mathetos** [comment]
I found the problem in my case. The other thing that changed with that version was Floating Labels, which I enabled on that form. But that meant the label for the custom field disappeared completely and so the Donors weren't entering ANY information in that field at all because they didn't know they should.

This is no valid and resolved. Thanks!
