### ISSUE TITLE
fix(donation): set minimum amount as the donation amount if it is less than the min amount, when saving the donation.

### ISSUE THREAD

**Issue by emgk** [WordImpress/Give#3249]
## User Story
As an `Admin`, I don't want `minimum amount more than the donation amount at all` so that `the donor cannot proceed the donation with the less amount than the actual minimum amount`.

## Current Behavior
I currently can make the donation if the donation amount is less than the minimum amount and if I don't change the amount field on the front-end. 

## Expected Behavior
When saving the donation form in the backend and if the set donation amount is less than the minimum amount then make the minimum amount same as the actual donation amount.

## Possible Solution
Make the minimum amount same as the donation amount if the donation amount is less than the donation minimum amount.

## Visuals
![screenshot-cs test-2018 05 23-12-16-40](https://user-images.githubusercontent.com/14994452/40407814-41c35098-5e83-11e8-928d-ef14c263b99a.png)

**Comment by raftaar1191** [comment]
## Finding 

This is not working when the **Donation Option** is set as **Multi-level Donation** 
![image](https://user-images.githubusercontent.com/22215595/40746757-e4c5319e-6478-11e8-84da-edc33a2ae90b.png)


We can used give_get_lowest_price_option function to get he lowest price

**Comment by ravinderk** [comment]
@raftaar1191 It is fine. Multi level does not follow this minimum donation rule. You can set level with donation amount minimum then custom donation amount.
We follow same rule in js also. You can process donation whatever set as level.

**Comment by emgk** [comment]
Re-opening this issue because: 

1. Minimum amount must set to the donation amount only if the donation doesn't support the multi-level.
2. found `!empty( $post_data['give-price-id'] )` which is wrong so need to test it.
