### ISSUE TITLE
Front end validation issues when Form Field Manager being used

### ISSUE THREAD

**Issue by 61pixels** [WordImpress/Give#3271]
## User Story
It appears there are a few front-end validation issues using Give 2.1.3 with Form Field Manager 1.3 (FFM). 

## Expected Behavior
When clicking the submit button. Any fields that ware marked as required which do not have any input should be highlighted in some fashion so the user can easily see what needs to be fixed (or use HTML5 methods).

## Current Behavior
Upon submission, none of the missing required fields show any indication in the standard form fields or from Form Field Manager except a select dropdown added from FFM. Inspecting elements shows that many of the fields do in fact have the proper give-has-error class applied, but the styles from (give.min.css) are overwriting the red border color from (give-ffm-frontend.min.css) to the #333 default since it is a more specific declaration.

Part two after further digging shows that the email and phone field types from FFM do not even receive the give-has-error class. The same applies to the default Personal Info and Credit Card Info fields when FFM fields are present. Creating a dummy form with no FFM fields, the personal info fields do in fact show HTML 5 validation error popups on First Name and Email fields.

## Possible Solution
Make sure the CSS for the error border color are more specific than the default colors, or use !important (cringe). I added an !important and custom error color myself for now via CSS. Look into why default HTML5 field validations don't work when FFM fields are being used.

## Steps to Reproduce
1. Create a form
2. Add some text/random fields using FFM and mark as required
2. View form on front-end
3. Click Submit button to see lack of validation on most fields(HTML 5 errors don't work at all, red borders are overwritten by default Give CSS)

## Environment
<details>
<summary>WordPress System Info</summary>

Home URL: https://regionalrace.deltagamma.org
Site URL: https://regionalrace.deltagamma.org
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%category%/%postname%/
Show on Front: page
Page on Front: Home (#35)
Page for Posts: News (#37)
Table Prefix Length: px_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, acf-disabled, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: WP Engine
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache
PHP Version: 7.0.30-0ubuntu0.16.04.1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
PHP Max Upload Size: 50 MB
cURL Version: 7.47.0, OpenSSL/1.0.2g
SUHOSIN Installed: –
MySQL Version: 5.7.21
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.3
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: 2.0.4
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://regionalrace.deltagamma.org/donation-confirmation/
Failure Page: https://regionalrace.deltagamma.org/donation-failed/
Donation History Page: https://regionalrace.deltagamma.org/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - CSV Toolbox: ❌ Unlicensed – by WordImpress – 1.0
Give - Form Field Manager: ✔ Licensed – by WordImpress – 1.3
Give - Google Analytics Donation Tracking: ✔ Licensed – by WordImpress – 1.1.2
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4
Give - Stripe Gateway: ✔ Licensed – by WordImpress – 2.0.4

### Other Active Plugins ###

Admin Menu Editor: by Janis Elsts – 1.8.4
Advanced Custom Fields PRO: by Elliot Condon – 5.6.10
Disable Comments: by Samir Shah – 1.7.1
Disable XML-RPC Pingback: by Samuel Aguilera – 1.1
Duplicate Post: by Enrico Battocchi – 3.2.2
Instagram Feed Pro Personal: by Smash Balloon – 2.6.1
Nested Pages: by Kyle Phillips – 3.0.1
Yoast SEO: by Team Yoast – 7.5.1

### Inactive Plugins ###

Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.0.6

### Active MU Plugins ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
Stop long comments: by WPEngine – 0.0.4
WP Engine System: by WP Engine – 3.2.1

### Theme ###

Name: Delta Foundation Gamma Regional Race 2018
Version: 1.0
Author URL: http://www.61pixels.com
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Microsoft Windows </li>
        <li>Version: 10</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Edge</li>
        <li>Version: latest</li>
    </ul>
</details>

**Comment by mehul0810** [comment]
@61pixels We've investigated this issue and noticed that the validations are not working properly in the way it should work. However, we won't be supporting HTML5 validations in FFM add-on. Also, we're working on refactoring the Form API for Give Core so all the validation related issues in Give Core and related add-ons will be taken care of within that update.
Also, as this issue is related to FFM, we're moving the issue to FFM repository.

**Comment by mehul0810** [comment]
Issue moved to [WordImpress/Give-Form-Field-Manager #264](https://github.com/WordImpress/Give-Form-Field-Manager/issues/264) via [**ZenHub**](https://www.zenhub.com/)
