### ISSUE TITLE
perf(sessions): research use of PHP sessions throughout Give

### ISSUE THREAD

**Issue by joehoyle** [WordImpress/Give#3272]
Almost a duplicate of https://github.com/WordImpress/Give/issues/521, which was fixed but appears to be back. 

Specifically it was fixed by this commit https://github.com/WordImpress/Give/pull/552/files#diff-d3edc19fec3fdac5e9147093267b2515R109, but then this was essentially reverted on https://github.com/WordImpress/Give/commit/243c02563dd90aecdeaa43c4e9d8a3b2bb258d9a which brought back the problem.

https://github.com/WordImpress/Give/issues/1630 also looks like potentially a dupe, but not sure if that's more about how the sessions are stored.

The main issue here is that each page load on the front end causes a `setcookie` which means you pretty much can't cache any page, as every request will then have a wp_session cookie. From what I can see (please correct me if I'm wrong) it's not really possible to use Give in a high traffic environment, as this pretty much necessities multiple web servers (therefore needing to use cookie sessions) and each request causes a cache bypass due to sessions being initiated for every visitor of the WordPress site.

**Comment by kevinwhoffman** [comment]
@joehoyle Thanks for taking the time to detail the issue and potentially related ones. I've assigned @ravinderk to look into this further.

@ravinderk Please review the behavior Joe is describing and the related issues. Then post your recommended solution here. Thanks!

**Comment by vinnygreen** [comment]
@ravinderk @kevinwhoffman  Any progress on this issue? Is there anything you need from us?

**Comment by mathetos** [comment]
Hey @vinnygreen We're putting the research into this to find the right approach to it. We'll report on our approach on it early next week.

**Comment by vinnygreen** [comment]
Thanks for the update!

**Comment by ravinderk** [comment]
@joehoyle @vinnygreen We researched the session issue and found that  `Woocommerce` already has a session solution which is tested it on wootheme.com before merging to `Woocommerce` plugin.

We are going to use `Woocommerce` sesison codebase as intial. 

Ref: https://woocommerce.wordpress.com/2015/10/07/new-session-handler-in-2-5/

**Comment by ravinderk** [comment]
Closing this issue in favor of https://github.com/WordImpress/Give/issues/3386
