### ISSUE TITLE
id="give-form-{ID}"is output twice on the page, once as a div, once as the form ID

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#329]
## A11Y Report Notes
http://b8d.3e8.myftpupload.com/donations/basic-form-with-custom-amount-enabled/
**Basic Form with Custom Amount Enabled**
* Error /  priority 65%
* Duplicate ID found
* (line: 107, 2)

```<div id="give-form-10" class="post-10 give_forms type-give_forms status-publish"> <div id="give-sidebar-left" class="give-sidebar give-single-form-sidebar-left"><div class="images"> 
<img src="http://placehold.it/300x300&amp;```

**Web Content Accessibility Guidelines (WCAG) 2.0, Level A: 4.1.1 Parsing**
An ID attribute value has been used more than once. In cases where the ID is used to reference a UI control this is likely to cause issues for users of assistive technologies

## Possible Solutions
* Change div ID to be `give-wrapper-form-{ID}`
* Change form ID to be `give-form-element-{ID}`
* Make both changes
* Determine whether one of those IDs is unnecessary

**Comment by DevinWalker** [comment]
There are actually a lot of IDs that are repeated on page if you have multiple forms embedded - we should ensure ALL ids have the form ID appended

**Comment by mathetos** [comment]
Yes, but in this case there was just ONE form on the page and there was still multiple IDs. I'll update the demo site and see if https://github.com/WordImpress/Give/commit/2359ae37e2ad5eb0384a78f4484db628e3d847c4 resolved this issue or not.

**Comment by mathetos** [comment]
OK, PR submitted for this issue. Simply changes the DIV ID from:

`<div id="give-form-<?php the_ID(); ?>" <?php post_class(); ?>>`

to

`<div id="give-form-<?php the_ID(); ?>-content" <?php post_class(); ?>>`

That DIV wraps both the Sidebar and the Form Summary DIV and Form Element so I thought "content" was the best descriptor.

**Comment by TheGeniusWM** [comment]
This is a good way to fix this, that way IDS are dynamic instead of hard-coded, thus less possibility of duplicate IDS on any 1 page. PERFECT!

**Comment by mathetos** [comment]
@TheGeniusWM  :+1: thanks!

**Comment by DevinWalker** [comment]
Looks good thanks :+1:
