### ISSUE TITLE
fix(admin-tool): exporting donor information doesn't include addresses

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3290]
## User Story
As a site admin, I want to export donor information with addresses for use elsewhere.

## Current Behavior
I currently get empty sections in the CSV export on donors that have billing addresses saved in Give.

## Expected Behavior
I expect to be able to use the tools without issue.

## Steps to Reproduce
1. Create donations with addresses.
2. Export the donor information using the Export Donors section, not the Donation History.
3. View the CSV and see the address fields are blank.

## Visuals
With the Export Donor Section:
![screen shot 2018-05-30 at 9 36 33 am](https://user-images.githubusercontent.com/20672471/40723621-495f3f0a-63ed-11e8-83d0-aa01d7a28cf4.png)

Same donors with the Donation History Section:
![screen shot 2018-05-30 at 9 38 28 am](https://user-images.githubusercontent.com/20672471/40723642-5461681a-63ed-11e8-8948-be861ea53bf3.png)

## Related
https://secure.helpscout.net/conversation/590723782/19299/

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.3
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email
Upgraded From: 2.0.6
Test Mode: Enabled
Currency Code: GBP
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, PayPal Payments Pro, Authorize.net eCheck (ACH), Stripe + Plaid, Braintree, Offline Donation, Stripe - Credit Card
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - 2Checkout Gateway: ❌ Unlicensed – by WordImpress – 1.1.1
Give - Authorize.net Gateway: ❌ Unlicensed – by WordImpress – 1.4.2
Give - Braintree Gateway: ❌ Unlicensed – by WordImpress – 1.2.1
Give - Donation Plugin: ❌ Unlicensed – by WordImpress – 2.1.3
Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.6
Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.3
Give - Gift Aid: ❌ Unlicensed – by WordImpress – 1.1.2
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by WordImpress – 1.1.4
Give - MailChimp: ❌ Unlicensed – by WordImpress – 1.4.1
Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.4
Give - PayPal Pro Gateway: ❌ Unlicensed – by WordImpress – 1.1.5
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.3
Give - Per Form Gateways: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.6.1
Give - Sofort Payment Gateway: ❌ Unlicensed – by WordImpress, CoachBirgit – 1.0
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 2.0.4
Give - Tributes: ❌ Unlicensed – by WordImpress – 1.4.2

### Other Active Plugins ###

Autoptimize: by Frank Goossens (futtta) – 2.3.4
Better Click To Tweet: by Ben Meredith – 5.5
Duplicate Post: by Enrico Battocchi – 3.2.2
Give - Hook Helper: by Ravinder Kumar – 1.0
Health Check: by The WordPress.org community – 1.0.1
Popup Maker: by WP Popup Maker – 1.7.19
Sam's Helper Function: by WordImpress – 1.0
Slider Revolution: by ThemePunch – 5.2.4.1
Transients Manager: by Pippin Williamson – 1.7.4
User Role Editor: by Vladimir Garagulya – 4.40.3
WP Auto Login: by Ren Ventura – 1.0.1
WP Rollback: by WordImpress – 1.5

### Inactive Plugins ###

Email Cop: by Ashfame – 0.1.1
GEO my WP: by Eyal Fitoussi – 3.0.4
Give - CSV Toolbox: by WordImpress – 1.0
Give - Currency Switcher: by WordImpress – 1.1
Give - Custom Field Integration: by WordImpress – 1.0
Give - PayFast Payment Gateway: by WordImpress – 1.0.1
Give - Paymill Gateway: by WordImpress – 1.1
Gutenberg: by Gutenberg Team – 2.9.2
My Custom Functions: by Space X-Chimp – 4.16
WP Google Maps: by WP Google Maps – 7.0.02
WP Google Maps - Pro Add-on: by WP Google Maps – 5.73
WP Mail SMTP: by WPForms – 1.2.5
WPML String Translation: by OnTheGoSystems – 2.7.3

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0
Health Check Disable Plugins: by  – 1.3

### Theme ###

Name: Twenty Seventeen
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by mathetos** [comment]
@samsmith89 this is because the information collected during donation is the BILLING ADDRESS, not the address connected to the Donor (which would be a physical mailing address). If you add information into the Donor address field on the Donor Detail screen, the export will export that correctly. This is part of why we have been working to separate donation_meta from donor_meta and then to map those fields correctly.

So this isn't technically a bug but a feature request -- the ability to collect the mailing address during donation in addition to the billing address. This is a known issue, but I can't find an existing issue on it at the moment.

@kevinwhoffman -- what's your call on this one? Should we close in favor of a new issue that is more descriptive of the solution that we need (namely collecting mailing address during donation in addition or with a checkbox saying "Same as billing?" and mapping donor meta from the form correctly), or just update this issue?

**Comment by kevinwhoffman** [comment]
@mathetos Create a new issue describing the need to collect a mailing address. Label it `needs-feedback`. List this issue as related.

Conventionally a mailing address appears before billing, so I think the form should be ordered as follows:

First Name | Last Name
Email
Mailing Address
Billing Address (with checkbox for "Same as Mailing Address" possibly pre-checked to avoid a super long form)
