### ISSUE TITLE
fix(shortcode): give_totals should output the correct donation total

### ISSUE THREAD

**Issue by marutim** [WordImpress/Give#3291]
## User Story
As a user when I would use the `give_totals` shortcode, I accept it to show the correct total which should be the sum of all the donations for the donation forms included.

For example: If you have a donation form in English which is translated in French and have donated 11 USD in the form in English and 22 USD in the form in French.

Now if you use the `give_totals` shortcode and include the IDs of this two form.

In the page which is using the shortcode, It will display the total as 11 USD for English and 22 USD for French instead of 33USD.

## Current Behavior
It should display the correct donation total.

## Steps to Reproduce
I have created a doc which explains in details how to replicate this issue 
https://docs.google.com/document/d/1-xeTxHn5K9yeYbRniV7T5BT6mYq_v3WG9BHehivBa8Y/edit

## Related
Link to the HS ticket: https://secure.helpscout.net/conversation/574804454/17963?folderId=1457790

## Environment
<details>
 ### WordPress Environment ###

Home URL: http://give-wpml.local
Site URL: http://give-wpml.local
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give-wpml.local
TLS Connection: Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 188

Warning: file_get_contents(): Failed to enable crypto in /app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 188

Warning: file_get_contents(https://www.howsmyssl.com/a/check): failed to open stream: operation failed in /app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 188
TLS Connection: 
Server Info: nginx/1.10.1
PHP Version: 7.1.7
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.2l - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.37
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.3
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give-wpml.local/donation-confirmation/
Failure Page: http://give-wpml.local/donation-failed/
Donation History Page: http://give-wpml.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Other Active Plugins ###

WPML Multilingual CMS: by OnTheGoSystems – 3.7.1

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by raftaar1191** [comment]
WPML plugin link: https://github.com/wp-premium/wpml-translation-management
