### ISSUE TITLE
fix(admin-shortcode): get JS error in console of file not found 

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#3292]
## User Story

As an `Admin` I do not want to see any error in the console 

I am getting this error in Give Core 2.1.4

## Current Behavior

I currently not able to used give shortcode button because of JS error in the console 

## Expected Behavior

I expect to work as it used to work 

## Steps to Reproduce
1. Take a fresh install and file Give Core Branch 2.1.4
2. Activate the Give Core plugin 
3. Go to any pages and open the console you will see the error 

## Visuals
![image](https://user-images.githubusercontent.com/22215595/40747390-c360237c-647a-11e8-8ec9-9e569044b2d5.png)

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://givewplocal.local
Site URL: http://givewplocal.local
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givewplocal.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: GBP
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://givewplocal.local/donation-confirmation/
Failure Page: http://givewplocal.local/donation-failed/
Donation History Page: http://givewplocal.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, PayPal Standard
Default Payment Gateway: PayPal Standard
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Gift Aid: ✔ Licensed – by WordImpress – 1.1.3

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.7
Beaver Builder Plugin (Lite Version): by The Beaver Builder Team – 2.1.2.2
BuddyPress: by The BuddyPress Community – 3.0.0
Charitable: by WP Charitable – 1.6.1
Debug Bar: by wordpressdotorg – 0.9
Debug Bar Console: by koopersmith – 0.3
Debug Bar Cron: by Zack Tollman, Helen Hou-Sandi – 0.1.2
Debug Bar Extender: by Thorsten Ott, Automattic – 0.5
Developer: by Automattic – 1.2.6
Duplicate Post: by Enrico Battocchi – 3.2.2
Elementor: by Elementor.com – 2.0.14
Email Cop: by Ashfame – 0.1.1
Give - 2Checkout Gateway: by WordImpress – 1.1
Give - Authorize.net Gateway: by WordImpress – 1.3.3
Give - AWeber: by WordImpress – 1.0.2
Give - Braintree Gateway: by WordImpress – 1.2.1
Give - CCAvenue Gateway: by WordImpress – 1.0.1
Give - Constant Contact: by WordImpress – 1.2.1
Give - ConvertKit: by WordImpress – 1.0.1
Give - Currency Switcher: by WordImpress – 1.1
Give - Development Plugin: by Raftaar1191 – 1.0.0
Give - Display Donors: by WordImpress, LLC – 1.0
Give - Dwolla Gateway: by WordImpress – 1.1.2
Give - Email Reports: by WordImpress – 1.1.1
Give - Fee Recovery: by WordImpress – 1.6
Give - Form Countdown: by WordImpress – 1.0
Give - Form Field Manager: by WordImpress – 1.3
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.4
Give - MailChimp: by WordImpress – 1.4
Give - Manual Donations: by WordImpress – 1.4
Give - Mollie Gateway: by WordImpress – 1.1
Give - Mollie Gateway: by WordImpress – 1.1
Give - Paymill Gateway: by WordImpress – 1.1
Give - PayPal Pro Gateway: by WordImpress – 1.1.4
Give - PDF Receipts: by WordImpress – 2.3
Give - Recurring Donations: by WordImpress – 1.6.1
Give - Stripe Gateway: by WordImpress – 2.0.4
Give - Tributes: by WordImpress – 1.4.2
Give - Zapier: by WordImpress – 1.2
Gravity Forms: by rocketgenius – 2.2.6
Gravity Forms Signature Add-On: by Rocketgenius – 3.4
Loco Translate: by Tim Whitlock – 2.1.4
Log Deprecated Notices: by Andrew Nacin – 0.4
Log Viewer: by Markus Fischbacher – 14.05.04
Monster Widget: by Automattic – 0.3
Polylang: by Frédéric Demarle – 2.3.6
Query Monitor: by John Blackbourn & contributors – 3.0.1
Restrict Content Pro: by Restrict Content Pro Team – 2.9.12
Rewrite Rules Inspector: by Daniel Bachhuber, Automattic – 1.2.1
User Switching: by John Blackbourn & contributors – 1.3.1
WooCommerce: by Automattic – 3.4.1
WordPress Beta Tester: by Peter Westwood – 1.2.2
WP Hide & Security Enhancer: by Nsp Code – 1.4.9.1
WPide: by Simon @ WPsites – 2.4.0
WPS Hide Login: by WPServeur, NicolasKulka, tabrisrp – 1.3.4.2

### Theme ###

Name: Twenty Sixteen
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by Sidsector9** [comment]
@raftaar1191 Have you tried running `npm run dev`?

**Comment by raftaar1191** [comment]
Slack Call Summary

Participants: @Sidsector9  @raftaar1191
Topic: How to fix the issues 
Result: Had a call with @sid and after the call was not able to regenerate the issues

I was using `webpack --watch --progress` to run the webpack and we should used `npm run dev` to do that
