### ISSUE TITLE
Personalise tooltips

### ISSUE THREAD

**Issue by rosswintle** [WordImpress/Give#33]
I'd like to be able to personalise the tooltips that pop up on forms when you hover over the question-mark help symbols. This will be especially key when using add-ons like MailChimp where "We will use this to personalize your account experience" won't be enough.

If complete control is not possible then can we at least have a UK translation with "personalise"?

I'm sorry. That's so picky! :)

**Comment by DevinWalker** [comment]
Not picky at all! Great enhancement idea that wouldn't be too difficult to implement

**Comment by rosswintle** [comment]
I suppose the issue is that you could end up with a mass of tooltip-customisation options.

Are they hookable?

**Comment by DevinWalker** [comment]
Option 1: No backend customization, only hookable - Downside of this is that it isn't very easy for non-developers, and we want the plugin to be very easy to use.

Option 2: Implement a Global and per-form tooltip customization metabox. The global settings would be under "Display Options" and could customize ALL forms. If you then wanted customization per form, you would customize it in the form metabox. - Downside: Depending on how it was implemented it runs the risk of further cluttering the UI with a lot of text fields for tooltip content. 

@mathetos what's your opinion here?

**Comment by rosswintle** [comment]
I don't feel like I'd need per-form customisations. Or would I??  Hmm...

The form-edit screen is pretty big as it is.

**Comment by mathetos** [comment]
I think 90% of Ross' concern would be resolved with a solid UK localization .po file. @rosswintle as we get close to launch on the Repo, would you be open to creating that file? There's simple instructions on creating localized translations here: https://wordimpress.com/docs/languages/

**Comment by rosswintle** [comment]
I think there's two things.  One is localisation (where I'm being picky, really).

The other is wanting to correctly inform end-users of what their data will be used for. So if I add the MailChimp extension then:

    "We will use this to personalize your account experience"

Should become 

    "We will use this to personalize your account experience and occasionally email you about our work"

Or something. And that could be different. For a church it could be:

    "We will use this to personalize your account experience and occasionally email you about events, services and prayer reqeusts"

But I also totally appreciate that you're NOT building Gravity forms here so you don't want individual tooltip options for every possible form field.

In terms of translating - it depends when launch is. I've put quite a lot of time in today and I'm about 120% booked for the rest of this week (and month).

Happy to have a go if I get some down time though. I'd say localisation was a minor thing that could be wrapped up in a point release. I can see the changelog now:

"Added UK English translation. Drank tea. Ate fish and chips in the rain on a beach." ;)

**Comment by mathetos** [comment]
Changelog: Perfect. That's what we'd love ;-)

With proper localization, and using Codestyling Languages (per the link above) users could change those tooltips to whatever they like. But that would be global, nor per form. But like you said, not sure we want to bulk up the form like that. Will be discussing further for sure.

**Comment by DevinWalker** [comment]
@mathetos - not for the docs - you can also use a plugin like "Say Anything" to change the strings to whatever text you'd like...

**Comment by DevinWalker** [comment]
I think in the future this can be an Add-on (free or cheap) to customize the tooltips. For now, we need docs. I don't think this needs to be in core.

**Comment by DevinWalker** [comment]
@mathetos close due to inactivity. Please verify you have no more stale tickets assigned.
