### ISSUE TITLE
id="give-amount" is output twice on the page, once as an input, once as a span

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#330]
## A11Y Report Notes
http://b8d.3e8.myftpupload.com/donations/basic-donation-form/
**Basic Donation Form**
* Error /  priority 65%
* Duplicate ID found
* (line: 127, 3)

`<input id="give-amount" class="give-amount-hidden" type="hidden" name="give-amount" value="5.00" required="" style="">`

**Web Content Accessibility Guidelines (WCAG) 2.0, Level A: 4.1.1 Parsing**
An ID attribute value has been used more than once. In cases where the ID is used to reference a UI control this is likely to cause issues for users of assistive technologies.

## Possible Solutions
* Change the input ID to `give-amount-input`
* Change the span ID to `give-amount-text`
* Determine whether either is necessary.

**Comment by TheGeniusWM** [comment]
your possible solutions are valid fixes, go with it,

**Comment by mathetos** [comment]
The span ID was necessary for styling of the fixed amount field. So I changed it to `give-amount-text` and added the styling to that new ID as well.
