### ISSUE TITLE
feat(admin-form): give users ability to clone forms

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3331]
## User Story
As a site admin, I want to be able to clone donation form without having to install a third-party plugin.

## Current Behavior
I currently. have to download another plugin to accomplish this.

## Expected Behavior
I expect to be able to do this in the core plugin.

Related https://github.com/WordImpress/Give/issues/2009#issuecomment-332397398

**Comment by ravinderk** [comment]
@samsmith89 Can you explain it more. Do you want to clone form on the same site or you want to export and import for on another site or both.

**Comment by samsmith89** [comment]
Sure. The customer wanted to clone forms on the same site without having to download and use a third-party plugin.
