### ISSUE TITLE
fix(admin-setting): display warning if user changes base currency

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3332]
## User Story
As a site admin, I want to see a warning if I change the base currency in Give if I already have donations so that reporting won't display incorrectly.

## Current Behavior
I currently can change with base currency without knowing the issues that may arise from doing so.

## Expected Behavior
I expect to be told if the setting I am changing may come with unintended consequences.  

## Steps to Reproduce
1. Set a base currency with Give
2. Submit donations in the original currency
3. Change the base currency
4. Make donations in the new currency. 
5. View Reports and Statistics Widget in the dashboard and you will see that both currencies are added without conversion.

## Visuals
Donations made with 20,000 INR and 300 Swiss Fr.
![screen shot 2018-06-06 at 4 29 53 pm](https://user-images.githubusercontent.com/20672471/41063555-f9fa46c0-69a6-11e8-8c34-91c83a2d84ab.png)

## Related
https://secure.helpscout.net/conversation/594197296/19612?folderId=1823994

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: https://give.local
Site URL: https://give.local
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Inaccessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email
Upgraded From: 2.0.6
Test Mode: Disabled
Currency Code: GBP
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://give.local/donation-confirmation/
Failure Page: https://give.local/donation-failed/
Donation History Page: https://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card, PayPal Standard, 2Checkout
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - 2Checkout Gateway: ❌ Unlicensed – by WordImpress – 1.1.1
Give - Authorize.net Gateway: ❌ Unlicensed – by WordImpress – 1.4.2
Give - Currency Switcher: ❌ Unlicensed – by WordImpress – 1.1
Give - Donation Plugin: ❌ Unlicensed – by WordImpress – 2.1.4
Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.6
Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.3
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by WordImpress – 1.1.4
Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.4
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.3
Give - Per Form Gateways: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.6.1
Give - Sofort Payment Gateway: ❌ Unlicensed – by WordImpress, CoachBirgit – 1.0
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 2.0.5
Give - Zapier: ❌ Unlicensed – by WordImpress – 1.2.1

### Other Active Plugins ###

Duplicate Post: by Enrico Battocchi – 3.2.2
Give - Hook Helper: by Ravinder Kumar – 1.0
Health Check: by The WordPress.org community – 1.0.1
Popup Maker: by WP Popup Maker – 1.7.19
Sam's Helper Function: by WordImpress – 1.0
Slider Revolution: by ThemePunch – 5.2.4.1
Transients Manager: by Pippin Williamson – 1.7.4
User Role Editor: by Vladimir Garagulya – 4.40.3
WP Auto Login: by Ren Ventura – 1.0.1
WP Rollback: by WordImpress – 1.5

### Inactive Plugins ###

Autoptimize: by Frank Goossens (futtta) – 2.3.4
Better Click To Tweet: by Ben Meredith – 5.5
Email Cop: by Ashfame – 0.1.1
GEO my WP: by Eyal Fitoussi – 3.0.4
Give - Braintree Gateway: by WordImpress – 1.2.1
Give - CSV Toolbox: by WordImpress – 1.0
Give - Custom Field Integration: by WordImpress – 1.0
Give - Gift Aid: by WordImpress – 1.1.2
Give - MailChimp: by WordImpress – 1.4.1
Give - PayFast Payment Gateway: by WordImpress – 1.0.1
Give - Paymill Gateway: by WordImpress – 1.1
Give - PayPal Pro Gateway: by WordImpress – 1.1.5
Give - Tributes: by WordImpress – 1.4.2
Gutenberg: by Gutenberg Team – 2.9.2
My Custom Functions: by Space X-Chimp – 4.16
WP Google Maps: by WP Google Maps – 7.0.02
WP Google Maps - Pro Add-on: by WP Google Maps – 5.73
WP Mail SMTP: by WPForms – 1.2.5
WPML String Translation: by OnTheGoSystems – 2.7.3

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0
Health Check Disable Plugins: by  – 1.3

### Theme ###

Name: Twenty Seventeen
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by mathetos** [comment]
I believe a better solution than a warning is that the currency the donation was made in must be saved in the donation meta and not changed at all. Essentially, if a $100 donation was made, then the currency was changed to Euros, that donation should always still be reflected as $100 regardless. No warning necessary, no conversion necessary, just accurately reporting exactly what was received.

Reporting then should be able to report income in multiple currencies. This is a tricky situation but considering our Currency Switcher Addon and the many users we have who collect donations in several different currencies, I think that's the best way forward.

**Comment by ravinderk** [comment]
@mathetos we are saving currency in donation meta.
@samsmith89  changing currency will only affect report/stats which can not resolve by currency switcher immediately because currency switcher stores few extra data to calculate stats. So if you want to accept donation in multicurrency then must install currency switcher from beginning otherwise stats will not be correct.

![image](https://user-images.githubusercontent.com/1784821/43318715-77eaf418-91bf-11e8-8cb3-8149034f1338.png)

**Comment by DevinWalker** [comment]
Closing in favor of https://github.com/WordImpress/Give/issues/2889 which will have an option to switch report based on currency.
