### ISSUE TITLE
fix(shortcode): exclude fee-recovery income from give_totals

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3339]
## User Story
As a site admin, I want to display the income of multiple forms without the fee-recovery income so that I can depict how much is going to the cause.

When using form goals normally the income excludes what is brought in from fee-recovery.

## Current Behavior
I currently get the donation amount combination of multiple forms plus fee-recovery.

## Expected Behavior
I expect to exclude fee-recovery income because it doesn't accurately depict how much donation income is needed.

## Steps to Reproduce
1. Set up two forms with fee-recovery.
2. Make a donation in each with fee recovery selected.
3. Make a [give_totals] shortcode with both forms.
4. See that the amounts totaled include fee-recovery.

## Visuals
Form with $4.27 in fee recovery, but is only showing the $20 donation:

![screen shot 2018-06-08 at 9 26 58 am](https://user-images.githubusercontent.com/20672471/41160601-39160cd8-6afe-11e8-95a7-22de28c43606.png)

[give_totals] shortcode only supposed to be showing $60 in donations:

![screen shot 2018-06-08 at 9 27 22 am](https://user-images.githubusercontent.com/20672471/41160637-56b6d2b8-6afe-11e8-84c5-c29ed86bcdaa.png)

## Related
https://secure.helpscout.net/conversation/597186692/19901?folderId=672194

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: https://givewp.gsamsmith.com
Site URL: https://givewp.gsamsmith.com
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wpk1_
Table Prefix Length: 5
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givewp.gsamsmith.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache
PHP Version: 7.0.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
PHP Max Upload Size: 128 MB
cURL Version: 7.59.0, OpenSSL/1.0.2k
SUHOSIN Installed: –
MySQL Version: 5.6.36
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://givewp.gsamsmith.com/donation-confirmation/
Failure Page: https://givewp.gsamsmith.com/donation-failed/
Donation History Page: https://givewp.gsamsmith.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: PayPal Standard, Test Donation, Razorpay, Stripe - Credit Card, 2Checkout
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: IPN received for #198 ( 1BT53766KU136061A ) on 05/17/2018 at 16:31. Status N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - 2Checkout Gateway: ❌ Unlicensed – by WordImpress – 1.1.1
Give - CSV Toolbox: ❌ Unlicensed – by WordImpress – 1.0
Give - Currency Switcher: ❌ Unlicensed – by WordImpress – 1.2
Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.6.1
Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.3
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by WordImpress – 1.1.4
Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.4
Give - PayFast Payment Gateway: ❌ Unlicensed – by WordImpress – 1.0
Give - Razorpay: ❌ Unlicensed – by WordImpress – 1.1.3
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.6.1
Give - Sofort Payment Gateway: ❌ Unlicensed – by WordImpress, CoachBirgit – 1.0
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 2.0.5
Give - Tributes: ❌ Unlicensed – by WordImpress – 1.4
Give - Zapier: ❌ Unlicensed – by WordImpress – 1.2.1

### Other Active Plugins ###

Duplicate Post: by Enrico Battocchi – 3.2.2
Duplicator: by Snap Creek – 1.2.36
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.0.6
Jetpack by WordPress.com: by Automattic – 6.1
Loginizer: by Raj Kothari – 1.3.9
My Custom Functions: by Space X-Chimp – 4.16
SG Optimizer: by SiteGround – 4.0.5
WP Rollback: by WordImpress – 1.5

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.0.3
Email Cop: by Ashfame – 0.1.1
Give - Gift Aid: by WordImpress – 1.1.1
Hello Dolly: by Matt Mullenweg – 1.6

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by ravinderk** [comment]
Issue moved to [WordImpress/Give-Fee-Recovery #208](https://github.com/WordImpress/Give-Fee-Recovery/issues/208) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Gecrator996** [comment]
@ravinderk @samsmith89 i would like to participate, have similar problem, wonder do you guys found workaround?

Thanks in advance for any information.

**Comment by kjohnson** [comment]
@Gecrator996 this issue was resolved in Fee Recovery `v1.7.3`.

## Fee Recovery v1.7.3 Release Notes

| Issue Number | Issue Title |
| :-- | :-- |
| #208 | fix: exclude fee-recovery income from `[give_totals]` |
| #240 | fix: fee and donation fee format for donation Listing, donation Detail and donation success and history page. |
| #241 | fix: support fee recovery + currency switcher for zero decimal currency |
| #245 | fix: store the total donation in `data-total` attribute in non formatted way |

**Comment by Gecrator996** [comment]
@kjohnson So glad you answered, just checked - i am on version 1.9.8, so interesting i have lifetime tendency on stepping on bugs wherever i go, its my luck, i guess that's what led me into Development,

So yeah i am telling you i have this issue in version 1.9.8, let's dig in, who knows how many people have it as well, hope it's just device specific.

**Comment by Gecrator996** [comment]
`### WordPress Environment ###

WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: page
Page on Front: Home page (#73)
Page for Posts: Blog (#100)
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, hidden, expired, preview, spam, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, new, interviewed, offer, hired, rejected, archived

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: [redacted for privacy]
TLS Connection: Connection uses TLS 1.3
TLS Connection: Probably Okay
Server Info: LiteSpeed
PHP Version: 8.1.9
PHP Post Max Size: 64 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
PHP Max Upload Size: 64 MB
cURL Version: 7.81.0, OpenSSL/3.0.2
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.23.2
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Updates: All Database Migrations Completed.
Database Tables: ✔ wp_give_donors✔ wp_give_donormeta✔ wp_give_comments✔ wp_give_commentmeta✔ wp_give_sessions✔ wp_give_formmeta✔ wp_give_sequential_ordering✔ wp_give_donationmeta✔ wp_give_revenue✔ wp_give_migrations✔ wp_give_log
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report
Upgraded From: 2.23.2
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://visionecorp.com/donation-confirmation/
Failure Page: https://visionecorp.com/donation-failed/
Donation History Page: https://visionecorp.com/donor-dashboard/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Apple Pay, Stripe - Google Pay, Stripe - Checkout
Default Payment Gateway: Stripe - Apple Pay
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: December 6, 2022 3:50 am

### Active GiveWP Add-ons ###

Give - Annual Receipts: ✔ Licensed – by GiveWP – 1.1.0
Give - BitPay: Free addon – by GiveWP – 1.0.0
Give - Currency Switcher: ✔ Licensed – by GiveWP – 1.5.2
Give - Email Reports: ✔ Licensed – by GiveWP – 1.1.4
Give - Fee Recovery: ✔ Licensed – by GiveWP – 1.9.8
Give - Form Field Manager: ✔ Licensed – by GiveWP – 2.0.3
Give - Funds and Designations: ✔ Licensed – by GiveWP – 1.1.0
Give - Google Analytics Donation Tracking: ✔ Licensed – by GiveWP – 2.1.0
Give - Manual Donations: ✔ Licensed – by GiveWP – 1.6.1
Give - PayPal Pro Gateway: ✔ Licensed – by GiveWP – 1.3.0
Give - PDF Receipts: ✔ Licensed – by GiveWP – 2.3.13
Give - Per Form Gateways: ✔ Licensed – by GiveWP – 1.0.2
Give - Stripe Gateway: ✔ Licensed – by GiveWP – 2.5.0
Give - Text-to-Give: ✔ Licensed – by GiveWP – 1.0.2

### Other Active Plugins ###

Akismet Anti-Spam: by Automattic – 5.0.2
Breadcrumb NavXT: by John Havlik – 7.1.0
Burst Statistics - Privacy-Friendly Analytics for WordPress: by Really Simple Plugins – 1.3.1
CMB2: by CMB2 team – 2.10.1
CMB2 Field Slider: by Matt Krupnik – 1.1.2
Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: by SeedProd – 6.15.6
Contact Form 7: by Takayuki Miyoshi – 5.6.4
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.2
Elementor: by Elementor.com – 3.8.1
Envato Market: by Envato – 2.0.7
Jetpack: by Automattic – 11.6-a.5
LiteSpeed Cache: by LiteSpeed Technologies – 5.3
MAS Companies For WP Job Manager: by MadrasThemes – 1.0.6
MAS Company Reviews For WP Job Manager: by MadrasThemes – 1.0.2
Purethemes.net CPT: by Purethemes.net – 1.1
Regions for WP Job Manager: by Astoundify – 1.18.2
Slider Revolution: by ThemePunch – 6.5.31
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com, DavidAnderson – 2.22.23.1
WorkScout-Core - WorkScout WPJM Plugin by Purethemes: by Purethemes.net – 1.5.11
WorkScout Activator: by purethemes – 1.0
WorkScout Elementor: by Purethemes.net – 1.0.6
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.94.0
WP File Manager: by mndpsingh287 – 7.1.6
WPForms: by WPForms – 1.7.8
WP Job Manager: by Automattic – 1.38.1
WP Job Manager - Alerts: by Automattic – 1.5.4
WP Job Manager - Application Deadline: by Automattic – 1.2.5
WP Job Manager - Applications: by Automattic – 2.5.2
WP Job Manager - Bookmarks: by Automattic – 1.4.2
WP Job Manager - Job Tags: by Automattic – 1.4.2
WP Job Manager - Resume Manager: by Automattic – 1.18.4
WP Job Manager - WooCommerce Paid Listings: by Automattic – 2.9.4
WP Mail SMTP Pro: by WPForms – 3.6.1

### Inactive Plugins ###

All-in-One WP Migration: by ServMask – 7.68
All in One SEO: by All in One SEO Team – 4.2.7.1
Complianz - Terms and Conditions: by Really Simple Plugins – 1.1.3
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 6.3.5
DoLogin Security: by WPDO – 3.5.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.10.1
Hello Dolly: by Matt Mullenweg – 1.7.2
RafflePress Lite: by RafflePress – 1.11.0
Really Simple SSL: by Really Simple Plugins – 6.0.11
WooCommerce: by Automattic – 7.1.0
WPForms Lite: by WPForms – 1.7.8

### Theme ###

Name: WorkScout
Version: 3.0.11
Author URL: http://purethemes.net/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
`

**Comment by Gecrator996** [comment]
Currently have 3 donations - for 1$ + 34 cents (fees) and it shows:
`Hey! We've raised $4.02 of the $25,000.00 we are trying to raise for this campaign! `

But it suppose to be just $3.00, correct me if i am wrong.

Will provide best of my knowledge and assistance, if you have any ideas let me know,

**Comment by Gecrator996** [comment]
Reopening issue in different ticket [6620](https://github.com/impress-org/givewp/issues/6620).

For those who have similar issue follow 6620 ticket.
