### ISSUE TITLE
feat(donor-wall): add Load More button 

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#3340]
## User Story
As a `developer`, I want `Load More` button with minimalistic design.

![sgjuvqfroq](https://user-images.githubusercontent.com/1784821/41212148-7e744aee-6d59-11e8-8263-97564ccfc16e.gif)

**Comment by kevinwhoffman** [comment]
Let's use the loading state that is part of Give core when you submit a donation. That functionality is already in place and it will create a consistent UX on the front-end.

![image](https://user-images.githubusercontent.com/1938671/41212401-9d72fb5a-6d0b-11e8-8c4d-0fd0cdc474f5.png)

**Comment by ravinderk** [comment]
@kevinwhoffman Current loading animation is hard coupled with donation form that why it is good to create new simple loading animation


![image](https://user-images.githubusercontent.com/1784821/41212532-39c07104-6d5c-11e8-871b-10c67f92be23.png)

**Comment by kevinwhoffman** [comment]
These three lines are responsible for creating the icon and spinning it. They can be used anywhere via `@extend`. Please use them as the basis for what you need in the donor wall.

```
@extend iconstyle();
@extend .give-icon-spinner2;
@extend .fa-spin;
```

I am closing this so we can continue with our assigned issues in this sprint. I agree that a more reusable button would be nice, but that can be addressed with the Form API later.
