### ISSUE TITLE
compat(muffin-builder): ensure compatibility with BeTheme's MuffinBuilder

### ISSUE THREAD

**Issue by davidkahn** [WordImpress/Give#3353]
## User Story

As a `admin`, I want `to fully utilize Muffin Builder` so that `I can create content` using BeTheme's Muffin Builder.

## Current Behavior

I currently unable to interact with the Muffin Builder if GiveWP is activated. See below.
![screenshot-2018-6-12 add new page the fort wordpress 6](https://user-images.githubusercontent.com/826721/41291936-9dbe507c-6e83-11e8-8f89-6a0012601b11.png)

## Expected Behavior
I expect to be able to interact with Muffin Builder like below (only works if GiveWP is deactivated):
![screenshot-2018-6-12 add new page the fort wordpress](https://user-images.githubusercontent.com/826721/41291337-04de54f2-6e82-11e8-87ec-8238b5287a83.png)
![screenshot-2018-6-12 add new page the fort wordpress 1](https://user-images.githubusercontent.com/826721/41291737-1a3984d8-6e83-11e8-866d-ce220c68b4e8.png)
![screenshot-2018-6-12 add new page the fort wordpress 2](https://user-images.githubusercontent.com/826721/41291741-1dcc2844-6e83-11e8-9d09-12448fc72251.png)

## Steps to Reproduce

1. Install BeTheme
2. Install GiveWP
3. Create a New Page (do not use the Wordpress content builder, but use Muffin Builder below in Page Options)

## Tasks

- [ ] Enter at least one task to be completed in the [imperative mood](https://chris.beams.io/posts/git-commit/#imperative).

## Environment

<details>
    <summary>WordPress System Info</summary>
    
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: x.x.x</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: x.x.x</li>
    </ul>
</details>

**Comment by Sidsector9** [comment]
**Call Summary**
---
**Participants**: @ravinderk and @sidsector9
**Topic**: Significance of using `jQuery.noConflict()` in Give's JS files
**Result**: As discussed with @ravinderk , we concluded that since we are already using IIFE in many files and scoping `$`, we don't need to use the `noConflict()` method.

CC: @kevinwhoffman
