### ISSUE TITLE
fix(Donation-goal): Goal amount should not change on re-saving the settings

### ISSUE THREAD

**Issue by marutim** [WordImpress/Give#3373]
## User Story
As a user, I do not want the donation amount to change on re-saving the donation form details.

With dot as the thousand separator and comma as the decimal separator, when you save a donation goal of 600123 ( 6 digits ) and save it, it saves as 600.123 but when you save it again it is then reduced to 600

This does not happen if the donation goal is a 7 digit number like 6001234.

## Steps to Reproduce
1. Set the currency settings as per the screenshots
2. Then add a 5 or 6 digit donation goal and save it twice.
3. You will see the donation amount reduced.

## Visuals
![image](https://user-images.githubusercontent.com/3498917/41430545-e9915ec6-702d-11e8-915e-5e5a7cff6c17.png)

![image](https://user-images.githubusercontent.com/3498917/41430591-08375efc-702e-11e8-80b9-fff900f79d0c.png)

## Related
- HS link: https://secure.helpscout.net/conversation/597881115/19967/
- https://github.com/WordImpress/Give/issues/3238

## Tasks
- [ ] Make sure this fixes for any number of digits as donation goal. I have tested it for 5 and 6 digit donation amounts.

## Environment
<details>
### WordPress Environment ###

Home URL: http://give-copy.local
Site URL: http://give-copy.local
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give-copy.local
TLS Connection: 
TLS Connection: 
Server Info: Flywheel/4.1.0
PHP Version: 5.6.20
PHP Post Max Size: 1,000 MB
PHP Time Limit: 300
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.2k - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.36
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email
Upgraded From: 1.8.19
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: ,
Thousands Separator: .
Success Page: http://give-copy.local/donation-confirmation/
Failure Page: http://give-copy.local/donation-failed/
Donation History Page: http://give-copy.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card, Offline Donation, Mollie Gateway
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ✔ Licensed – by WordImpress – 1.4.2
Give - Currency Switcher: ✔ Licensed – by WordImpress – 1.2
Give - Fee Recovery: ✔ Licensed – by WordImpress – 1.6.1
Give - Form Field Manager: ✔ Licensed – by WordImpress – 1.3
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4
Give - Mollie Gateway: ❌ Unlicensed – by WordImpress – 1.1.1
Give - PayPal Pro Gateway: ✔ Licensed – by WordImpress – 1.1.5
Give - PDF Receipts: ✔ Licensed – by WordImpress – 2.3
Give - Per Form Gateways: ✔ Licensed – by WordImpress – 1.0.1
Give - Recurring Donations: ✔ Licensed – by WordImpress – 1.6.1
Give - Stripe Gateway: ✔ Licensed – by WordImpress – 2.0.5
Give - Tributes: ✔ Licensed – by WordImpress – 1.4.2

### Other Active Plugins ###

Debug Bar: by wordpressdotorg – 0.9
Debug Bar Post Meta: by whyisjake – 0.5.4
Duplicate Post: by Enrico Battocchi – 3.2.2
Email Cop: by Ashfame – 0.1.1
User Switching: by John Blackbourn & contributors – 1.3.1

### Inactive Plugins ###

Automatic Responsive Tables: by Andrew Rockwell – 1.2
Give - AmeriCloud Payments: by AmeriCloud Solutions, Inc. – 1.2.0
Give - Braintree Gateway: by WordImpress – 1.1.1
Give - CCAvenue Gateway: by WordImpress – 1.0
Give - Constant Contact: by WordImpress – 1.2.1
Give - ConvertKit: by WordImpress – 1.0.1
Give - CSV Toolbox: by WordImpress – 1.0
Give - Email Reports: by WordImpress – 1.1.1
Give - Form Countdown: by WordImpress – 1.0
Give - GoCardless Gateway: by WordImpress – 1.2
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.1
Give - Hook Helper: by Ravinder Kumar – 1.0
Give - MailChimp: by WordImpress – 1.4.1
Give - Paytm Gateway: by WordImpress – 1.0
Give - Per Form User Role Assigner: by Matt Cromwell – 1.0
Give - Recurring Helper: by WordImpress – 1.0
Give - Zapier: by WordImpress – 1.2.1
My Custom Functions: by Space X-Chimp – 4.18
WP Filters Extras: by BeAPI – 1.0.2

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
   
</details>

**Comment by ravinderk** [comment]
@raftaar1191 I am able to reproduce the issue with `Euro`
