### ISSUE TITLE
fix(admin-tool): ensure the level title in the exported CSV reads custom on custom donations

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3380]
## User Story
As a site admin, I want to export a CSV file that shows that a donor gave a custom amount in the Level Title when they give a custom amount.

## Current Behavior
I currently get an export that marks custom donations with the default Level Title of the form.

## Expected Behavior
I expect to have the level read as "custom" with custom donations.

## Steps to Reproduce
1. Make a donation form with two levels and custom amounts enabled
2. Make the first level the default level
3. Generate three donations, two using the levels and one as a custom donation
4. Generate a CSV file, and see that the custom level will inherit the default level "Level Title"

## Visuals
See the Level ID shows as a "custom" amount, but the Level Title shows the default level:
![screen shot 2018-06-18 at 4 39 45 pm](https://user-images.githubusercontent.com/20672471/41560929-8e00e5d6-7316-11e8-88de-8d4b9f6ba175.png)

## Related
https://secure.helpscout.net/conversation/603510382/20341?folderId=1823994

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: https://give.local
Site URL: https://give.local
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email
Upgraded From: 2.0.6
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://give.local/donation-confirmation/
Failure Page: https://give.local/donation-failed/
Donation History Page: https://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card, Authorize.net, PayPal Payments Pro
Default Payment Gateway: Test Donation
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - 2Checkout Gateway: ❌ Unlicensed – by WordImpress – 1.1.1
Give - Authorize.net Gateway: ❌ Unlicensed – by WordImpress – 1.4.2
Give - Currency Switcher: ❌ Unlicensed – by WordImpress – 1.2
Give - Donation Plugin: ❌ Unlicensed – by WordImpress – 2.1.4
Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.6.1
Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.3
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by WordImpress – 1.1.4
Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.4
Give - PayPal Pro Gateway: ❌ Unlicensed – by WordImpress – 1.1.5
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.3
Give - Per Form Gateways: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Razorpay: ❌ Unlicensed – by WordImpress – 1.1.4
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.6.1
Give - Sofort Payment Gateway: ❌ Unlicensed – by WordImpress, CoachBirgit – 1.0
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 2.0.5
Give - Zapier: ❌ Unlicensed – by WordImpress – 1.2.1

### Other Active Plugins ###

Duplicate Post: by Enrico Battocchi – 3.2.2
Give - Hook Helper: by Ravinder Kumar – 1.0
Health Check: by The WordPress.org community – 1.0.1
Popup Maker: by WP Popup Maker – 1.7.19
Sam's Helper Function: by WordImpress – 1.0
Slider Revolution: by ThemePunch – 5.2.4.1
Transients Manager: by Pippin Williamson – 1.7.4
User Role Editor: by Vladimir Garagulya – 4.40.3
WP Auto Login: by Ren Ventura – 1.0.1
WP Rollback: by WordImpress – 1.5

### Inactive Plugins ###

Autoptimize: by Frank Goossens (futtta) – 2.3.4
Email Cop: by Ashfame – 0.1.1
GEO my WP: by Eyal Fitoussi – 3.0.4
Give - Braintree Gateway: by WordImpress – 1.2.1
Give - CSV Toolbox: by WordImpress – 1.0
Give - Custom Field Integration: by WordImpress – 1.0
Give - Gift Aid: by WordImpress – 1.1.2
Give - MailChimp: by WordImpress – 1.4.1
Give - PayFast Payment Gateway: by WordImpress – 1.0.1
Give - Paymill Gateway: by WordImpress – 1.1
Give - Tributes: by WordImpress – 1.4.2
Gutenberg: by Gutenberg Team – 2.9.2
My Custom Functions: by Space X-Chimp – 4.16
WP Google Maps: by WP Google Maps – 7.0.02
WP Google Maps - Pro Add-on: by WP Google Maps – 5.73
WP Mail SMTP: by WPForms – 1.2.5
WPML String Translation: by OnTheGoSystems – 2.7.3

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0
Health Check Disable Plugins: by  – 1.3

### Theme ###

Name: Twenty Seventeen
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by DevinWalker** [comment]
## Resolve By Doing

The "Level Title" column header text should be "Customer". Leave the Level ID column as it is.

**Comment by raftaar1191** [comment]
@DevinWalker did not get you https://github.com/WordImpress/Give/issues/3380#issuecomment-398280931

but I guess you mean **Custom** not **Customer**

Example: 
![image](https://user-images.githubusercontent.com/22215595/41596357-b87da6e2-73e7-11e8-87c1-dbfe154e4b93.png)
