### ISSUE TITLE
fix(db-upgrade): research DB upgrade issues

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#3383]
## User Story
As an `admin`, I want hassle free DB upgrades in any server environment.

### Matt's Comment
Call Summary
Participants: @ravinderk @mathetos

Consensus is that the current error message is the only place in which we can ensure that there is an actual problem. It is a vague error simply because we don't yet have enough information to know with certainty exactly why the DB update fails; it could be a lot of different things. In order to add better logic we need more information. We can't yet perfectly replicate DB update problems with Memcache for example. We can't yet perfectly replicate DB update problems with admin-ajax exactly as it happens in some of these environments. We don't know what types of server security prevents the database tables from being created. Without this information we can't have logic in the plugin that checks for these problems and gives better error messages.

To that end:

Matt will provide better wording for the existing error message, which will link to documentation that @Benunc is currently writing.
Matt will connect with Support and Devs at WooCommerce to see whether they face similar issues and what they do about it.
Ravinder will research the issue more in terms of how Woo/EDD deal with these from a code perspective.
For the next couple weeks, whenever @Benunc gets a DB update issue he should first ping Ravinder to work on it so Ravinder can see more environments with as many different scenarios as possible.
That's our plan moving forward. For this issue, let's keep it focused on a better error message that points to existing docs (that are not yet finished).

Ref https://github.com/WordImpress/Give/issues/3267#issuecomment-395290498

**Comment by Benunc** [comment]
The document is published here now: https://givewp.com/documentation/core/frequent-troubleshooting-issues/handling-database-update-issues/ and the short URL is http://docs.givewp.com/troubleshooting-db-updates

**Comment by ravinderk** [comment]
We found that reason of most of DB update issue was that Ajax was inaccessible. In that case, background update is not possible. Since we can fire local ajax (on the page), so we can run completely update with local Ajax.

check this link for more information: https://github.com/wordimpress/give/issues/3420
