### ISSUE TITLE
fix(admin-tool): ensure when importing offline donations they aren't marked test

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3388]
## User Story
As a site admin, I want to import Offline donations from a CSV.

## Current Behavior
I currently import donations marked as "offline" in the payment gateway column and they are marked as Test.

## Expected Behavior
I expect to import Offline donations and they mark as Offline.

## Steps to Reproduce
1. Create 2 donations, one Test and one Offline.
2. Generate an export of the two donations, and confirm they have two different gateways
3. Import the CSV file that was just created.
4. Navigate to the Donations page and see that they are both marked as Test.

## Visuals
![screen_shot_2018-06-20_at_9_55_04_am](https://user-images.githubusercontent.com/20672471/41682381-918e106c-74a5-11e8-8e1b-67724c7d217c.png)

Both donations marked as Test:
![screen shot 2018-06-20 at 4 19 07 pm](https://user-images.githubusercontent.com/20672471/41682448-bcbdbb5c-74a5-11e8-8ce2-a472b67cb951.png)

## Related
https://secure.helpscout.net/conversation/596179244/19798?folderId=1823994

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.5
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email
Upgraded From: 2.1.5
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card, Authorize.net, PayPal Payments Pro, Offline Donation, Braintree
Default Payment Gateway: Test Donation
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - 2Checkout Gateway: ❌ Unlicensed – by WordImpress – 1.1.1
Give - Authorize.net Gateway: ❌ Unlicensed – by WordImpress – 1.4.2
Give - Braintree Gateway: ❌ Unlicensed – by WordImpress – 1.2.1
Give - CSV Toolbox: ❌ Unlicensed – by WordImpress – 1.0
Give - Currency Switcher: ❌ Unlicensed – by WordImpress – 1.2.1
Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.7.0
Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.3
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by WordImpress – 1.1.4
Give - MailChimp: ❌ Unlicensed – by WordImpress – 1.4.1
Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.4
Give - PayFast Payment Gateway: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Paymill Gateway: ❌ Unlicensed – by WordImpress – 1.1
Give - PayPal Pro Gateway: ❌ Unlicensed – by WordImpress – 1.1.5
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.3
Give - Per Form Gateways: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Razorpay: ❌ Unlicensed – by WordImpress – 1.1.4
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.6.1
Give - Sofort Payment Gateway: ❌ Unlicensed – by WordImpress, CoachBirgit – 1.0
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 2.0.5
Give - Tributes: ❌ Unlicensed – by WordImpress – 1.4.2
Give - Zapier: ❌ Unlicensed – by WordImpress – 1.2.1

### Other Active Plugins ###

Give - Custom Field Integration: by WordImpress – 1.0
Give - Hook Helper: by Ravinder Kumar – 1.0

### Inactive Plugins ###

Autoptimize: by Frank Goossens (futtta) – 2.3.4
Duplicate Post: by Enrico Battocchi – 3.2.2
Email Cop: by Ashfame – 0.1.1
GEO my WP: by Eyal Fitoussi – 3.0.4
Give - Gift Aid: by WordImpress – 1.1.2
Give - WooCommerce: by WordImpress – 1.0.0
Gutenberg: by Gutenberg Team – 2.9.2
Health Check: by The WordPress.org community – 1.0.1
LearnPress: by ThimPress – 3.0.9
My Custom Functions: by Space X-Chimp – 4.16
Popup Maker: by WP Popup Maker – 1.7.19
Sam's Helper Function: by WordImpress – 1.0
Slider Revolution: by ThemePunch – 5.2.4.1
Transients Manager: by Pippin Williamson – 1.7.4
User Role Editor: by Vladimir Garagulya – 4.40.3
WooCommerce: by Automattic – 3.4.2
WordPress Importer: by wordpressdotorg – 0.6.4
WP Auto Login: by Ren Ventura – 1.0.1
WP Google Maps: by WP Google Maps – 7.0.02
WP Google Maps - Pro Add-on: by WP Google Maps – 5.73
WP Mail SMTP: by WPForms – 1.2.5
WPML String Translation: by OnTheGoSystems – 2.7.3
WP Rollback: by WordImpress – 1.5

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0
Health Check Disable Plugins: by  – 1.3

### Theme ###

Name: Twenty Seventeen
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by raftaar1191** [comment]
Closing this issues PR for the issues already being merged in Give Core 2.2


PR link: https://github.com/WordImpress/Give/pull/3414
