### ISSUE TITLE
fix(admin): DB Update notice appears on fresh install

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#3390]
## User Story

As a brand new Give user, I don't expect to be notified of the need to update my database on activation of the plugin for the first time. It should work out of the box immediately after activation.

## Current Behavior

Currently, new Give users see the DB Update notice immediately after activating the plugin for the first time.

## Expected Behavior

I expect that all new DB tables are created silently as soon as Give is activated for the first time.

## Possible Solution

Create the new tables silently without a notification.

## Steps to Reproduce

1. Create a fresh install
2. Install Give from "Plugins > Add New" (not Github)
3. Activate and confirm that the DB notice is there.

**Comment by kevinwhoffman** [comment]
@ravinderk I confirmed the DB notice is present on a fresh install of Give `2.1.5`. Please let us know why this might be happening and move it to the top of your priority list so we can get a `2.1.6` patch out as soon as possible. Thanks.

**Comment by ravinderk** [comment]
Closing in favor of https://github.com/WordImpress/Give/commit/7a17b22af6e8497be25bc33e6bcaf69c10adcc60
