### ISSUE TITLE
Does `give_payment_delete` ever get triggered?

### ISSUE THREAD

**Issue by macbookandrew** [WordImpress/Give#3391]
https://github.com/WordImpress/Give/blob/16421a289684055aa6b411a629b4e7eb7e08696d/includes/admin/payments/actions.php#L342

I can’t find any time when `give_payment_delete` would fire.

**Comment by ravinderk** [comment]
@macbookandrew Yes.

In Give core, we have logic to dynamically fire hooks on the basis of `give_action` in `$_POST` or `$_GET`

https://github.com/WordImpress/Give/tree/master/includes/actions.php#L43
https://github.com/WordImpress/Give/tree/master/includes/actions.php#L76

These are the file where we are creating hooks
https://github.com/WordImpress/Give/blob/16421a289684055aa6b411a629b4e7eb7e08696d/includes/admin/payments/view-payment-details.php#L139
https://github.com/WordImpress/Give/blob/16421a289684055aa6b411a629b4e7eb7e08696d/includes/admin/payments/class-payments-table.php#L602

**Comment by macbookandrew** [comment]
@ravinderk Ah…thanks 👍
