### ISSUE TITLE
fix(admin-donation): ensure users can edit company name

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3413]
## User Story
As a site admin, I want to be able to edit the company name so that I can make changes.

## Current Behavior
I currently can't edit the company name.

## Expected Behavior
I expect to be able to change this.

## Acceptance Criteria

- [ ] I can edit the company name in the Donor Details screen.
- [ ] I can add a company name when making a manual donation as described in https://github.com/WordImpress/Give-Manual-Donations/issues/125.

## Steps to Reproduce
1. View a donation where a company name has been submitted.
2. See that the company name can't be edited from the admin donation page.

## Visuals
![screen shot 2018-06-27 at 4 45 52 pm](https://user-images.githubusercontent.com/20672471/41998942-0499fe0c-7a2a-11e8-837e-a333e18f358e.png)

## Related
https://secure.helpscout.net/conversation/609844111/20704?folderId=1823994
https://secure.helpscout.net/conversation/612029892/20876?folderId=672197

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.6
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email
Upgraded From: 2.1.5
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card, Authorize.net, PayPal Payments Pro, Offline Donation, Braintree
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - 2Checkout Gateway: ❌ Unlicensed – by WordImpress – 1.1.1
Give - Authorize.net Gateway: ❌ Unlicensed – by WordImpress – 1.4.2
Give - Braintree Gateway: ❌ Unlicensed – by WordImpress – 1.2.2
Give - Constant Contact: ❌ Unlicensed – by WordImpress – 1.2.1
Give - CSV Toolbox: ❌ Unlicensed – by WordImpress – 1.0
Give - Currency Switcher: ❌ Unlicensed – by WordImpress – 1.2.1
Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.7.0
Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.3
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by WordImpress – 1.1.4
Give - MailChimp: ❌ Unlicensed – by WordImpress – 1.4.1
Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.4
Give - PayFast Payment Gateway: ❌ Unlicensed – by WordImpress – 1.0.2
Give - Paymill Gateway: ❌ Unlicensed – by WordImpress – 1.1
Give - PayPal Pro Gateway: ❌ Unlicensed – by WordImpress – 1.1.5
Give - PDF Receipts: ❌ Unlicensed – by WordImpress – 2.3
Give - Per Form Gateways: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Razorpay: ❌ Unlicensed – by WordImpress – 1.1.4
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.6.1
Give - Sofort Payment Gateway: ❌ Unlicensed – by WordImpress, CoachBirgit – 1.0
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 2.0.5
Give - Tributes: ❌ Unlicensed – by WordImpress – 1.4.2
Give - Zapier: ❌ Unlicensed – by WordImpress – 1.2.1

### Other Active Plugins ###

Duplicate Post: by Enrico Battocchi – 3.2.2
Email Cop: by Ashfame – 0.1.1
Give - Custom Field Integration: by WordImpress – 1.0
Give - Hook Helper: by Ravinder Kumar – 1.0
Health Check: by The WordPress.org community – 1.0.1
Hustle Pro: by WPMU DEV – 3.0.3
Sam's Helper Function: by WordImpress – 1.0
WP Auto Login: by Ren Ventura – 1.0.1

### Inactive Plugins ###

Give - Gift Aid: by WordImpress – 1.1.2
Give - WooCommerce: by WordImpress – 1.0.0
Gutenberg: by Gutenberg Team – 2.9.2
My Custom Functions: by Space X-Chimp – 4.16
Transients Manager: by Pippin Williamson – 1.7.4
User Role Editor: by Vladimir Garagulya – 4.40.3
WooCommerce: by Automattic – 3.4.2
WordPress Importer: by wordpressdotorg – 0.6.4
WP Rollback: by WordImpress – 1.5

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0
Health Check Disable Plugins: by  – 1.3

### Theme ###

Name: Twenty Seventeen
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by kevinwhoffman** [comment]
@raftaar1191 @ravinderk Please review the Acceptance Criteria and discuss the best way to approach this.

- I think we should definitely allow editing of the `Company Name` within the **Donor** Details screen.
- I am not sure if we should allow `Company Name` to be edited from the **Donation** Details screen as shown in the visual above. That would involve editing donation meta, which I'm not sure we should allow without maintaining a snapshot of the original.

Also note that @samsmith89 created a related issue in https://github.com/WordImpress/Give-Manual-Donations/issues/125 that I think we can solve here.

Let me know what you decide. Thanks.

**Comment by raftaar1191** [comment]
Got it, So now I am allowing admin to edit the company name fields without maintaining any snapshots of the previous company name.


But if we want to maintain it then we can add a note that company name is being updated from old to new


@ravinderk @kevinwhoffman

**Comment by ravinderk** [comment]
@raftaar1191 No. I did not say that. Allow admin to edit company name from donor profile for now.

**Comment by kevinwhoffman** [comment]
@ravinderk I agree. Let's only allow the company to be edited in donor profile. This is consistent with the behavior necessary for an admin to edit first name, last name, or email. Since we display all of this information together in donation details page, it makes sense that it would be edited in the same place (the donor profile).

**Comment by raftaar1191** [comment]
Okay got it @ravinderk @kevinwhoffman 


I am only going to allow the company name to be updated in donor profile page
