### ISSUE TITLE
fix(admin-plugins): REST endpoint doesn't respond to requests

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#3436]
## User Story

As a `developer, I want rest endpoints to respond to requests to `http://survey.givewp.com` so that Give core can send feedback to the site through the endpoint.

## Current Behavior
I currently can access the posts JSON object by appending `/wp-json/wp/v2/posts/` to `https://givewp.com` but I cannot do the same with `http://survey.givewp.com`

## Expected Behavior
I expect to append `/wp-json/wp/v2/posts/` to `http://survey.givewp.com` and access posts JSON object.

**Comment by Sidsector9** [comment]
@DevinWalker I finally got it to work. The issue was with the permalink structure. I set it to `Month and Name` on survey.givewp.com and it is working now. Data is correctly received, I tested it with multiple options.

**Comment by ravinderk** [comment]
Closing in favor of https://github.com/wordimpress/give/issues/3436#issuecomment-403388854
