### ISSUE TITLE
Support multiple currencies on site

### ISSUE THREAD

**Issue by rogercoathup** [WordImpress/Give#344]
We have a site that serves an international audience.

We want to be able to offer donations in multiple currencies (GBP, USD and EUR). 

Looking at Give, it seems I can only set one currency for the site - is that correct?

Do you have plans to allow the currency to be chosen on a per form basis?

**Comment by DevinWalker** [comment]
Yes only one currency for now. We may have a multi-currency Add-on in the future but that's still in the planning stages. Thanks for putting in your vote for this.
