### ISSUE TITLE
feat(admin-plugins): do not deactivate the add-on if the PHP or Give Core minimum version does not match

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#3440]
## User Story
As an `Admin` I do not like it when Core deactivates add-ons automatically.

It should be activated and should show me a message that you need to update to Give Core Version `2.1.7` to use this add-on.

Video displaying issue: https://screencast-o-matic.com/watch/cFi1lwFvSb

## Current Behavior

I currently see add-on is getting deactivate if Give Core Minimum version or PHP minimum version is not match

## Expected Behavior

I expect to show display an Admin notices to update the Give Core or PHP version  

## Add-ons Updated to Not Deactivate if Requirement Not Met

The following add-ons have been updated to _not deactivate_ but rather _disable_ themselves until the Give Core version requirement is met.

- [x] Tributes
- [x] 2Checkout
- [x] Americloud Payments
- [x] Authorize Gateway
- [x] Aweber
- [x] Braintree Gateway
- [x] CCAvenue
- [x] Constant Contact
- [x] Convertkit
- [x] Currency Switcher
- [x] Email Reports
- [x] Fee Recovery
- [x] Form Countdown
- [x] Form Field Manager
- [x] Gift Aid
- [x] GoCardless
- [x] Google Analytics
- [x] iATS
- [x] MailChimp
- [x] Manual Donations
- [x] Mollie
- [x] PayFast
- [x] PayPal Pro
- [x] Paytm
- [x] PayUmoney
- [x] PDF Receipts
- [x] Per Form Gateways
- [x] Razorpay
- [x] Recurring Donations
- [x] Sofort
- [x] Square
- [x] Stripe
- [x] WooCommerce
- [x] Zapier

... @raftaar1191 will update with a complete list of add-ons.

**Comment by raftaar1191** [comment]
@kevinwhoffman what's your suggestion on this

**Comment by DevinWalker** [comment]
@raftaar1191 yeah I agree it shouldn't deactivate the add-on but rather leave it activated but _disabled_ until the core requirement is met.

> Activation Error: Please update Give core to version `2.1.7+` to use the `Add-on Name` add-on.

**Comment by raftaar1191** [comment]
Slack Chat Link: https://givewp.slack.com/archives/D6NDNRU75/p1531265020000080

**Comment by raftaar1191** [comment]
## Finding 
We need to consider the scenario where the activation hook

**Comment by kevinwhoffman** [comment]
As discussed on dev team call, @raftaar1191 estimates another 8-10 hours to complete updates of the remaining add-ons.

**Comment by raftaar1191** [comment]
This issue is being fixed have sent the PR of this in all the Add-on. So closing this issue for now if found any bug then please reopen this issue
