### ISSUE TITLE
Renewal donations for recurring donations are not associated with the correct payment level

### ISSUE THREAD

**Issue by mqudsi** [WordImpress/Give#3443]
After a renewal donation (Give 2.1.7, Recurring Donations 1.7.1, and Stripe Gateway 2.0.7) the renewal transaction does not have the correct payment level associated with it. In the list of donations, it appears as if it were the first level in the list and when viewing the donation details page for the renewal it is clear that it has no donation/payment level assigned to it (no item selected in the dropdown).

The remainder of the payment information is correct (including the amount).

This is probably because the renewal itself isn't explicitly associated with a form submission in give-wp; the right approach is probably to display some sort of "not applicable" instead of defaulting to the first payment level in the overview of donations.

**Comment by DevinWalker** [comment]
@raftaar1191 can you replicate this?

**Comment by raftaar1191** [comment]
Yes, @DevinWalker I can replicate this issues. This issue exist in https://github.com/WordImpress/Give-Recurring-Donations Add-on 


Can you move this issues to https://github.com/WordImpress/Give-Recurring-Donations and assign me so that I can work on this issues

**Comment by DevinWalker** [comment]
Issue moved to [WordImpress/Give-Recurring-Donations #694](https://github.com/WordImpress/Give-Recurring-Donations/issues/694) via [**ZenHub**](https://www.zenhub.com/)
