### ISSUE TITLE
fix(compat): resolve conflict with Give 2.2 and Fee Recovery 1.7

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3455]
## User Story
As a Site Admin, I want to use dropdowns, shortcode builders, and page functionality so that it works.

## Current Behavior
I currently have Give 2.2 and Fee Recovery 1.7.0 installed and I get a give-ajax error. 

## Expected Behavior
I expect to use the two plugins together

## Steps to Reproduce
1. Activate both plugins
2. Try and move donation levels around in a form
3. Try to use the Shortcode generator
4. Inspect and see the error in the console

## Visuals
![screen shot 2018-07-10 at 4 36 42 pm](https://user-images.githubusercontent.com/20672471/42536233-74049358-845f-11e8-9c8a-4a9538b0696d.png)

Link to the Screencast:
https://screencast-o-matic.com/watch/cFi6YyFaok

## Related

https://github.com/WordImpress/Give-Fee-Recovery/issues/214

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://betagive.local
Site URL: http://betagive.local
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: betagive.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.2.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://betagive.local/donation-confirmation/
Failure Page: http://betagive.local/donation-failed/
Donation History Page: http://betagive.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Currency Switcher: ❌ Unlicensed – by WordImpress – 1.2.1

### Other Active Plugins ###

Email Cop: by Ashfame – 0.1.1
Give - Authorize.net Gateway: by WordImpress – 1.4.2
Give - Email Reports: by WordImpress – 1.1.2
Give - Fee Recovery: by WordImpress – 1.7.0
Give - Form Field Manager: by WordImpress – 1.4
Give - Gift Aid: by WordImpress – 1.1.4
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.4
Give - Hook Helper: by Ravinder Kumar – 1.0
Give - MailChimp: by WordImpress – 1.4.1
Give - Manual Donations: by WordImpress – 1.4.1
Give - PayPal Pro Gateway: by WordImpress – 1.1.6
Give - PDF Receipts: by WordImpress – 2.3
Give - Per Form Gateways: by WordImpress – 1.0.1
Give - Recurring Donations: by WordImpress – 1.7.1
Give - Stripe Gateway: by WordImpress – 2.0.7
Give - Tributes: by WordImpress – 1.4.2
Give - Zapier: by WordImpress – 1.2.1

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0
Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by kevinwhoffman** [comment]
@raftaar1191 Please look into this and determine whether the conflict can be fixed in Give core or whether it requires a change in Fee Recovery. Ideally we can fix it in core before the 2.2.0 release.

**Comment by raftaar1191** [comment]
Sure @kevinwhoffman looking into this issues

**Comment by DevinWalker** [comment]
I believe this has to do with how `Core 2.2.0` has changed to db sessions rather than PHP sessions.

**Comment by raftaar1191** [comment]
Yes @DevinWalker you are right 

Fixing it

**Comment by jaydeeprami** [comment]
@raftaar1191 ,

In Fee recovery, we using `give_global_vars` in https://github.com/WordImpress/Give-Fee-Recovery/blob/master/assets/js/give-fee-recovery-common.js file for the `fee` formatting. 

We have made this common file to access common js function which are used in Fron-end as well as in Backend. We need these function for make `Fee recovery` compatible with `Manual donation` plugin.

**Comment by raftaar1191** [comment]
This issue exists in [Give Fee Recovery Add-on](https://github.com/WordImpress/Give-Fee-Recovery)

PR link: https://github.com/WordImpress/Give-Fee-Recovery/pull/220


So closing this issues and creating a new one in https://github.com/WordImpress/Give-Fee-Recovery


New Issue Link: https://github.com/WordImpress/Give-Fee-Recovery/issues/217
