### ISSUE TITLE
fix(form): 2.2 ensure name title prefix field doesn't wrap to new line on button display

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3465]
## User Story
As a donor, I want all the fields to display correctly so that it looks professional.

## Current Behavior
I currently have the name title prefix field getting shoved to another line on the button and modal display modes.

## Expected Behavior
I expect to have all fields on one line.

## Steps to Reproduce
1. Create a form with name title prefix enabled
2. Put the form into modal or button display mode
3. See the field get pushed down.

## Visuals
![screen shot 2018-07-12 at 4 39 46 pm](https://user-images.githubusercontent.com/20672471/42658614-d8e36d9a-85f3-11e8-81ab-550409d7ba17.png)

## Related
Found during testing Give 2.2

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://betagive.local
Site URL: http://betagive.local
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: betagive.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.2.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://betagive.local/donation-confirmation/
Failure Page: http://betagive.local/donation-failed/
Donation History Page: http://betagive.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, PayPal Standard, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Currency Switcher: ❌ Unlicensed – by WordImpress – 1.2.1

### Other Active Plugins ###

Email Cop: by Ashfame – 0.1.1
Give - Authorize.net Gateway: by WordImpress – 1.4.2
Give - Email Reports: by WordImpress – 1.1.2
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.4
Give - Hook Helper: by Ravinder Kumar – 1.0
Give - MailChimp: by WordImpress – 1.4.1
Give - Manual Donations: by WordImpress – 1.4.1
Give - PayPal Pro Gateway: by WordImpress – 1.1.6
Give - PDF Receipts: by WordImpress – 2.3
Give - Per Form Gateways: by WordImpress – 1.0.1
Give - Recurring Donations: by WordImpress – 1.7.1
Give - Stripe Gateway: by WordImpress – 2.0.7
Give - Tributes: by WordImpress – 1.4.2
Give - Zapier: by WordImpress – 1.2.1

### Inactive Plugins ###

Give - Fee Recovery: by WordImpress – 1.7.0
Give - Form Field Manager: by WordImpress – 1.4
Give - Gift Aid: by WordImpress – 1.1.4

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0
Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by DevinWalker** [comment]
I think the best solution would be to slightly increase the size of the modal window CSS to account for that new field. @Sidsector9
