### ISSUE TITLE
fix(donation): fix js error on donation confomration page with out login

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#3470]
## User Story
As an `Admin` I do not want any JS error in the console 

## Current Behavior

I currently getting a JS error in the console

## Expected Behavior

I expect to see donation receipt 

## Steps to Reproduce
1. Make a donation without creating an account 
2. After payment done, it will redirect to donation confirmation page first you won't see any donation receipt and after reloading you will see an error in the console

## Visuals
![image](https://user-images.githubusercontent.com/22215595/42675234-c584d458-8690-11e8-8974-644628b28227.png)

**Comment by ravinderk** [comment]
@raftaar1191 did you run `npm run dev` after taking latest pull

**Comment by raftaar1191** [comment]
Yes @ravinderk I tryed that too

**Comment by raftaar1191** [comment]
Slack Chat Link: https://givewp.slack.com/archives/C0FAGC83C/p1531462019000077

**Comment by ravinderk** [comment]
@raftaar1191 fixed

**Comment by raftaar1191** [comment]
Tested @ravinderk 

Working perfectly now
