### ISSUE TITLE
For deprecating tx

### ISSUE THREAD

**Issue by michaelbeil** [WordImpress/Give#348]
Are you all using Transifex still?

**Comment by DevinWalker** [comment]
Nope never even used it before...

On Friday, October 16, 2015, Michael Beil <notifications@github.com> wrote:

> Are you all using Transifex still?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WordImpress/Give/issues/348>.
>


-- 

Devin Walker

Founder & Lead Developer

P:

858-449-6460 <8584496460>

W:

http://wordimpress.com

433 G Street #201
San Diego, CA 92101 <https://goo.gl/maps/BePgp>
<https://www.facebook.com/wordimpressive>  <https://twitter.com/wordimpress>
  <https://plus.google.com/u/0/b/117062083910623146392/+Wordimpress/about>
<http://wordimpress.com/>

**Comment by michaelbeil** [comment]
Just submitted a PR to remove those references in Give as originated via EDD.

**Comment by DevinWalker** [comment]
Nice use of emojis :) thanks
