### ISSUE TITLE
fix(form): ensure that leaving thousand separator blank won't result in a space

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3487]
## User Story
As a donor, my currency doesn't use a thousand separator, but there is a space where one would be. I want this changed so that it will align with the way my currency is supposed to display.

Customer states it's this way for Hungarian Forint.

## Current Behavior
I currently have a space where a thousand separator would be in other currencies. 

## Expected Behavior
I expect to have the option to not have a space display.

## Steps to Reproduce
1. Set Give currency to have an empty thousand separator.
2. Configure an amount that would typically have a thousand separator.
3. See that there is a space where it is supposed to be.

## Visuals
![screen shot 2018-07-16 at 4 09 49 pm](https://user-images.githubusercontent.com/20672471/42781465-37fef010-8914-11e8-87b0-e0f90b1d1570.png)

![screen shot 2018-07-16 at 4 09 56 pm](https://user-images.githubusercontent.com/20672471/42781470-3bbd11aa-8914-11e8-918c-9d1500d02519.png)

## Related
https://secure.helpscout.net/conversation/620996696/21497?folderId=1823994

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.7
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: 
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card, PayPal Standard, Authorize.net
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ❌ Unlicensed – by WordImpress – 1.4.2
Give - CCAvenue Gateway: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Fee Recovery: ❌ Unlicensed – by WordImpress – 1.7.0
Give - Form Field Manager: ❌ Unlicensed – by WordImpress – 1.3
Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.4.1
Give - PayPal Pro Gateway: ❌ Unlicensed – by WordImpress – 1.1.6
Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.7.1
Give - Stripe Gateway: ❌ Unlicensed – by WordImpress – 2.0.7
Give - Tributes: ❌ Unlicensed – by WordImpress – 1.4.2

### Other Active Plugins ###

Sam's Helper Function: by WordImpress – 1.0

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by ravinderk** [comment]
@DevinWalker we can no save `' '` value in setting field, that's why we cannot save `' '` as thousand separator. According to logic when we find empty value as thousand separator then we set ` ` as thousand seperator instead of empty value. 

ref: https://github.com/WordImpress/Give/blob/release/2.2/includes/formatting.php#L56

To overcome this logic we have to choose a symbol as space thousand separator for example `||` or `#`, so when admin save this as thousand separator then we will translate that as `' '` Let me know what do you think.

**Comment by Champdor** [comment]
I'm a Hungarian customer as well (not the one mentioned above). I firmly believe that the customer is WRONG. According to Hungarian grammar a thousand separator of ' ' (space) is needed. Yes, there is a case of 4 figure numbers (10,000 > n > 999) where thousand separator is not needed but I think it's only making things complicated and most Hungarian will understand the number shown with separator.

**Comment by DevinWalker** [comment]
I agree, let's not overcomplicate things.
