### ISSUE TITLE
fix(admin-setting): show realtime number formatting

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#3490]
## User Story
As an `admin`, I want to see how donation amount will be a format with a current set of currency formatting setting.

![image](https://user-images.githubusercontent.com/1784821/42795137-44215b3a-89a0-11e8-80ee-a035c674a972.png)

**Comment by kevinwhoffman** [comment]
@Sidsector9 Let's follow the same approach as we used in https://github.com/WordImpress/Give/issues/244 to reflect a realtime preview of sequential ordering settings.

@ravinderk I think it would be helpful if you and Sid met briefly so we can borrow as much logic as possible from the sequential ordering functionality that you wrote.

**Comment by ravinderk** [comment]
@Sidsector9 reopening this issue because are loading `give.js` in the backend which can break functionality. Use `Give` global object instead.
