### ISSUE TITLE
doc(composer): Update composer instructions in README 

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#3495]
## User Story
As a `product manager`, I want the correct composer command so that only necessary dependencies are installed for production.

## Current Behavior
No documentation is provided in the README file.

## Expected Behavior
I expect the README to provide me with the composer command necessary for production.  

## Tasks

- [x] Update the README file with the correct composer command necessary for the release of Give production version.

**Comment by ravinderk** [comment]
We will take care this #3482
