### ISSUE TITLE
Change name of "History" menu item

### ISSUE THREAD

**Issue by rosswintle** [WordImpress/Give#35]
Further to issue #34 ... I'm not sure that I like the menu option being "History". If it contains pending or failed transactions then it's NOT historical, it's actually LIVE information.

Can this be "Donations" or "Transactions" or something?

I bet you've spent hours discussing this already, right! ;)

**Comment by DevinWalker** [comment]
@mathetos I like "Transactions" - doesn't that sound better than "History"?

**Comment by rosswintle** [comment]
"Transactions" sounds more like somewhere I would go to change something from pending to complete.  I'm happy with that.

**Comment by mathetos** [comment]
@DevinWalker I think "Transactions" works, but it feels a little "product" oriented. Maybe "Records"?

**Comment by DevinWalker** [comment]
This is all updated now. Happy transacting!
