### ISSUE TITLE
PayPal Standard Language Select Enhancement

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#350]
"The locale of the login or sign-up page, which may have the specific country's language available, depending on localization. If unspecified, PayPal determines the locale by using a cookie in the subscriber's browser. If there is no PayPal cookie, the default locale is US.
The following two-character country codes are supported by PayPal:"

https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/

I'm going to research whether including this option would have any downsides. It looks pretty handy to include a dropdown so the user can select country.

Suggested here: https://wordpress.org/support/topic/wrong-language-on-paypal-donate-page?replies=8#post-7562114

**Comment by DevinWalker** [comment]
@pippinsplugins I'm mixed on your exact thoughts on this... Did you say this is a GOOD or BAD idea?

**Comment by DevinWalker** [comment]
@mathetos thoughts?

**Comment by mathetos** [comment]
I could imagine plenty countries/languages in which their default cookies method wouldn't work and end up putting their donors to an English-only page. I think our default for a setting like this should be OFF, but giving the user the ability to choose to enforce the language is a good idea I think.

**Comment by pippinsplugins** [comment]
Personally I'd let PayPal control it.

**Comment by DevinWalker** [comment]
I'm also leaning towards @pippinsplugins recommendation. I also checked out Woo's PayPal Standard implementation and they don't provide language support. I'm assuming they have gotten the request at least a few times and considered it.

**Comment by Benunc** [comment]
I tend to agree with @mathetos on this, and we at least should have a checkbox on the paypal gateway settings tab for folks who are reporting this issue. I do have a snippet that I can give people who ask, but I think a checkbox to enforce `get_locale()` (as opposed to a country dropdown, because then we'd have to only list countries paypal supports) would be helpful.

**Comment by mathetos** [comment]
@Benunc Can you link to that HelpScout ticket as a reference? I think that showed a good justification for this.
