### ISSUE TITLE
Customize HTML5 Alert Messages

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#351]
The HTML5 alerts are not specific to the field that is missing at all. They can be customized per field. I tested this code and it works great:
http://blog.thomaslebrun.net/2011/11/html-5-how-to-customize-the-error-message-for-a-required-field/#.ViVY_tKrSUl

### Considerations
* The JS would have to be localized (meaning wp_localize_script() -- not internationalization) in order to pass the string dynamically
* Not sure there's a reliable way to get_text JS reliably so that local translations can be provided via the local .po file

**Comment by ramiy** [comment]
I agree, `wp_localize_script()` is the common way to pass translation strings to JS.

**Comment by DevinWalker** [comment]
I'm bumping this to 1.7
