### ISSUE TITLE
fix(admin-setting): Old version of admin scripts load on clicking save

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#3513]
## User Story
As a `developer`, I want the latest JS script to load so that I get the correct values of localised variables.

If you change an admin setting, for example `Currency Position`, and click Save, the localised variable `give_vars.currency_pos` does not get updated. It takes another refresh for the correct values to load.

## Current Behavior
Currently, it takes 2 refreshes to pull the correct values.

## Expected Behavior
I expect to pull the correct localised values in a single refresh.

## Steps to Reproduce
1. Go to the Give's Settings Page.
2. Modify a setting, for example change the currency position from `before` to `after`.
3. Open your developer tools to keep an eye on the HTML
4. Click Save
5. Check for `currency_pos` under `give_vars`

## Tasks

- [ ] Investigate why this is happening and fix the issue.

**Comment by ravinderk** [comment]
@Sidsector9 this issue appears because we save admin setting after localized data generated. To permanently fix this issue we have to save setting earlier which maybe break few add-ons.

**Comment by Sidsector9** [comment]
@ravinderk Have you fixed this? Because I'm not able to reproduce the issue anymore

**Comment by Sidsector9** [comment]
Closing this as per [discussion](https://givewp.slack.com/archives/C0FAGC83C/p1536471308000100).
