### ISSUE TITLE
CC field auto-formatting not working as expected in Modal while another form is on the page with a different display method

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#352]
### How to Duplicate
* Have Stripe enabled and set to default Gateway
* Have one form on the page with the Display mode set to "Show on Page"
* Have another form in the sidebar with Display mode set to "Modal Window Upon Click"
* Use the form in the sidebar, fill out the CC fields and you'll see that the spaces aren't added in the CC # and the expiration date is not auto-formatted.

**Comment by DevinWalker** [comment]
@mathetos can you close this?

**Comment by mathetos** [comment]
Yep. Looks like it was just a mix up between different/outdated Stripe/Give Core and/or Form Field Manager at play.
