### ISSUE TITLE
 Increase donors table email column length

### ISSUE THREAD

**Issue by andreasnrb** [WordImpress/Give#3525]
## User Story

As a developer, I want an increase of the email column length of donors table so that I can store larger values such as a hashed email. Bcrypt uses 60 chars.

## Current Behavior
Strings longer than 50 causes errors. 

## Expected Behavior

I expect to store emails larger than 50 characters.

## Possible Solution
Change the email column length to varchar(100) or varchar(255)

## Tasks

- [ ] Increase donors table email column length

**Comment by raftaar1191** [comment]
## Finding
Email column length is not getting updated when setting up a fresh sites 

![image](https://user-images.githubusercontent.com/22215595/43488126-5022fa0a-9536-11e8-9bf6-59ffa4cf37d4.png)


Video Link: https://screencast-o-matic.com/watch/cFiwrZF99j

**Comment by andreasnrb** [comment]
Alter the create table instead since dbDelta handles that automatically.
