### ISSUE TITLE
fix(donor-wall): donors display incorrect amounts when giving multiple times 

### ISSUE THREAD

**Issue by michelleames** [WordImpress/Give#3532]
## User Story

As a site admin, I want donor wall to display correct amounts.

## Current Behavior
I'm trying the donor wall on my church site so I can answer questions about it. But nothing showed up even though I made a new not-anonymous donation until I enabled comments. (Shouldn't it display even without a comment?) When I enabled comments it shows up BUT - I donated $1 and it's showing $2. AND the comment isn't showing up.

https://pcfministries.com/test-2/

**Comment by ravinderk** [comment]
@michelleames 
1. how many donations you made before testing donor wall?
2. did you set form id in the shortcode to get donor stat only for specific donation form?

**Comment by michelleames** [comment]
1. Just one, although this form has been live for awhile with previous donations. This one was a new donation.
2. I used the shortcode builder and chose the form from the list.
