### ISSUE TITLE
No Cardholder Name Requested - Stripe

### ISSUE THREAD

**Issue by michelleames** [WordImpress/Give#3533]
https://wpfanatic.com/donations/support-this-blog/ 

Upgraded to Give 2.2.0 and all of the add-ons. 

Cardholder name is not requested on the form (using Stripe add-on). So the following error is occurring: Error: Please enter a name for the credit card.

**Comment by mehul0810** [comment]
Issue moved to [WordImpress/Give-Stripe #293](https://github.com/WordImpress/Give-Stripe/issues/293) via [**ZenHub**](https://www.zenhub.com/)
