### ISSUE TITLE
fix(compat): resolve issue with the enfold theme on give 2.2

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#3545]
## User Story
When I update the Give plugin to 2.2 on enfold them with the aria builder, there are errors on the back end and the page builder doesn't work.

## Expected Behavior
I expect Give to work with enfold

## Possible Solution
https://github.com/WordImpress/Give/blame/2f78feb7f5807d28deb7b16daf87334b1851f89d/assets/src/js/frontend/give-ajax.js#L14

## Steps to Reproduce
I've only been able to reproduce on a clone of a customer site. ZIP provided in comment on this issue in Slack.
1. install duplicator file
2. create a new page.
3. attempt to toggle between the visual editor and the text editor on that page.

I've attempted deactivating all plugins, and switching to a non-child theme of enfold, and the error persists.

## Related
- https://secure.helpscout.net/conversation/631296893/22579/

## Tasks
- [ ] find out the cause of the conflict
- [ ] if the conflict is Give's fault, provide a workaround in the meantime for the customer.

## Environment
<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: http://fapefoundation.local
Site URL: http://fapefoundation.local
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_qcpod1f2nn_
Table Prefix Length: 14
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: fapefoundation.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: –
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://fapefoundation.local/confirmation/
Failure Page: http://fapefoundation.local/donation-failed/
Donation History Page: http://fapefoundation.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Authorize.net
Default Payment Gateway: Authorize.net
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ✔ Licensed – by WordImpress – 1.4.2
Give - Email Reports: ✔ Licensed – by WordImpress – 1.1.2
Give - Fee Recovery: ✔ Licensed – by WordImpress – 1.7.0
Give - Form Field Manager: ✔ Licensed – by WordImpress – 1.3
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4.1
Give - Recurring Donations: ✔ Licensed – by WordImpress – 1.7.1

### Other Active Plugins ###

All In One SEO Pack: by Michael Torbert – 2.7.2
Duplicate Post: by Enrico Battocchi – 3.2.2
Duplicator: by Snap Creek – 1.2.40
Instagram Feed Pro Personal: by Smash Balloon – 2.11
MapifyLite: by Josh Sears – 1.0.6
MapifyPro: by Josh Sears – 3.0.10
Monarch Plugin: by Elegant Themes – 1.4.3
Plugin Detective - Troubleshooting: by N Squared – 1.1
Redirection: by John Godley – 3.4
Typekit Fonts for WordPress: by OM4 – 1.9.0
WP Media folder: by Joomunited – 4.5.9
WP Simple Anchors Links: by Kilukru Media – 1.0.0

### Inactive Plugins ###

Instagram Feed: by Smash Balloon – 1.9

### Theme ###

Name: Enfold
Version: 4.4.1
Author URL: https://kriesi.at
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by kevinwhoffman** [comment]
@ravinderk This was the line triggering the console error which mentioned `give_global_vars` not being set: https://github.com/WordImpress/Give/blame/2f78feb7f5807d28deb7b16daf87334b1851f89d/assets/src/js/frontend/give-ajax.js#L14

It looks like that line was introduced just prior to 2.2 release, so I'm assigning to you in case that helps you diagnose the issue.

**Comment by ravinderk** [comment]
@Benunc This issue appears because of fee recovery addon which we already resolved. Please ask the user to update fee recovery to `1.7.1`.

![image](https://user-images.githubusercontent.com/1784821/43498557-1ab0d746-9565-11e8-9da7-3dd52a886f0f.png)
