### ISSUE TITLE
fix(login): ensure user can submit an email address to access Donation History page

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3553]
## User Story
As a donor, I want to go to the Donation History page and log in using my email address so that access my past donations.

## Current Behavior
I currently go to the Donation History page and the link to submit my email doesn't work. It appears to be disabled.

## Expected Behavior
I expect to sign in with my email.

## Steps to Reproduce
1. Attempt to sing in with an email that has past donations
2. See that you can't click the submit link

## Visuals
![screen shot 2018-08-01 at 5 46 37 pm](https://user-images.githubusercontent.com/20672471/43551055-99c9721a-95b3-11e8-9b09-e6d981311494.png)

![screen shot 2018-08-01 at 5 50 54 pm](https://user-images.githubusercontent.com/20672471/43551059-9d6ca298-95b3-11e8-92a8-b052ccce0c3d.png)

## Related
https://secure.helpscout.net/conversation/632788239/22781?folderId=1823994

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: https://givewp.gsamsmith.com
Site URL: https://givewp.gsamsmith.com
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wpk1_
Table Prefix Length: 5
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givewp.gsamsmith.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache
PHP Version: 7.0.31
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
PHP Max Upload Size: 128 MB
cURL Version: 7.59.0, OpenSSL/1.0.2k
SUHOSIN Installed: –
MySQL Version: 5.6.40
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://givewp.gsamsmith.com/donation-confirmation/
Failure Page: https://givewp.gsamsmith.com/donation-failed/
Donation History Page: https://givewp.gsamsmith.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card, CCAvenue, Razorpay, Stripe + Plaid, PayPal Standard
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: IPN received for #370 ( N/A ) on 08/01/2018 at 07:25. Status N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - 2Checkout Gateway: ✔ Licensed – by WordImpress – 1.1.1
Give - Authorize.net Gateway: ✔ Licensed – by WordImpress – 1.4.2
Give - AWeber: ✔ Licensed – by WordImpress – 1.0.3
Give - Braintree Gateway: ✔ Licensed – by WordImpress – 1.2.2
Give - CCAvenue Gateway: ✔ Licensed – by WordImpress – 1.0.1
Give - Constant Contact: ✔ Licensed – by WordImpress – 1.2.1
Give - ConvertKit: ✔ Licensed – by WordImpress – 1.0.2
Give - CSV Toolbox: ❌ Unlicensed – by WordImpress – 1.0
Give - Currency Switcher: ✔ Licensed – by WordImpress – 1.2.2
Give - Dwolla Gateway: ✔ Licensed – by WordImpress – 1.1.2
Give - Email Reports: ✔ Licensed – by WordImpress – 1.1.2
Give - Fee Recovery: ✔ Licensed – by WordImpress – 1.7.1
Give - Form Field Manager: ✔ Licensed – by WordImpress – 1.3
Give - GoCardless Gateway: ✔ Licensed – by WordImpress – 1.2
Give - Google Analytics Donation Tracking: ✔ Licensed – by WordImpress – 1.1.4
Give - iATS Payment Solutions: ✔ Licensed – by WordImpress – 1.0.3
Give - MailChimp: ✔ Licensed – by WordImpress – 1.4.1
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4.1
Give - PayFast Payment Gateway: ❌ Unlicensed – by WordImpress – 1.0.2
Give - PayPal Pro Gateway: ✔ Licensed – by WordImpress – 1.1.6
Give - Paytm Gateway: ✔ Licensed – by WordImpress – 1.0
Give - PayUmoney: ❌ Unlicensed – by WordImpress – 1.0.1
Give - PDF Receipts: ✔ Licensed – by WordImpress – 2.3
Give - Per Form Gateways: ✔ Licensed – by WordImpress – 1.0.1
Give - Razorpay: ❌ Unlicensed – by WordImpress – 1.2.0
Give - Recurring Donations: ✔ Licensed – by WordImpress – 1.7.2
Give - Sofort Payment Gateway: ❌ Unlicensed – by WordImpress, CoachBirgit – 1.0
Give - Stripe Gateway: ✔ Licensed – by WordImpress – 2.0.9
Give - Tributes: ✔ Licensed – by WordImpress – 1.5.0
Give - Zapier: ✔ Licensed – by WordImpress – 1.2.1

### Other Active Plugins ###

All-in-One WP Migration: by ServMask – 6.73
Duplicate Post: by Enrico Battocchi – 3.2.2
Duplicator: by Snap Creek – 1.2.40
Give - Paymill Gateway: by WordImpress – 1.0.2
SG Optimizer: by SiteGround – 4.0.7
Transients Manager: by Pippin Williamson – 1.7.5
WP Rollback: by WordImpress – 1.5.1
WP Updates Notifier: by Scott Cariss – 1.4.4

### Inactive Plugins ###

Email Cop: by Ashfame – 0.1.1
Give - AmeriCloud Payments: by AmeriCloud Solutions, Inc. – 1.2.0
Give - Gift Aid: by WordImpress – 1.1.5
Give - Mollie Gateway: by WordImpress – 1.1.1
Give - Stripe Gateway: by WordImpress – 2.0.4

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by raftaar1191** [comment]
Working nicely @ravinderk
