### ISSUE TITLE
fix(forms): Uncomment action hook

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#3566]
## User Story
As a `developer`, I want to `give_checkout_login_fields_before` hook to be uncommented so that I can hook a function to it.

## Current Behavior
Currently the hook is commented.

## Expected Behavior
I expect the hook to be uncommented.

## Tasks

- [x] Uncomment the hook.

**Comment by ravinderk** [comment]
Slack Discussion: https://givewp.slack.com/archives/C0FAGC83C/p1533293560000215
