### ISSUE TITLE
Improve extension license key activation and add weekly status checks

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#357]
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3889

**Comment by DevinWalker** [comment]
YES :+1:

**Comment by DevinWalker** [comment]
I would love to see this in 1.5

**Comment by DevinWalker** [comment]
@ravinderk https://github.com/WordImpress/Give/pull/836 is much improved over our current licensing. As we spoke about today:

**Overview:**
- All purchases *now* made on givewp.com are yearly subscriptions. Customers must create an account at checkout and their user is give an "EDD Subscribers" role.
    - This means that their licenses will auto-renew unless the customer cancels their subscription
    - In the past, customers made 1 time purchases and then had to *manually* renew their licenses. The current code in the PR works for this customer group.

**What we need:**
- We need for the EDD Software Licensing API on givewp.com to return the customer's role, whether they are a subscriber or not to differentiate whether they are a manual or auto-renewal
      -  The status of the subscription needs to also be returned `active` or `cancelled`. For example, even though a customer is a subscriber they may have cancelled their subscription.
- The messaging to the user needs to change based on the type of customer they are
      - Active subscribers should not receive a message asking them to renew their license since it auto-renews. Rather, it should say "Your license will renew in x days".
      - Cancelled subscribers and non-subscriber manual renewers should receive the current message of "You license will expire in x days, click here to renew your license."

Please let me know if you need any clarification of the above.

**Comment by DevinWalker** [comment]
Unfortunately, looks like we're going to have to bump this off 1.6

**Comment by DevinWalker** [comment]
I'm reopening this because we need to double-check and be absolutely positive that the upgrade process from `1.6` to `1.7` is seamless. Licenses should not "disappear" in the input fields when upgrading at all:

![wttwocartf](https://cloud.githubusercontent.com/assets/1571635/19377013/933dd1ce-9197-11e6-9bfb-dd7e298baaf3.gif)

## Steps to Replicate
1. Switch to master branch
2. Activate any license
3. Switch to `release/1.7` branch
4. Refresh - notice the license field is empty
5. Save the Settings - license appears fine

Am I missing something obvious like an upgrade routine? I feel that @ravinderk and I have spoken about this a few times. I just don't want to *ever* deactivate licenses and/or confuse users on their licenses due to an update.

**Comment by ravinderk** [comment]
@DevinWalker Before switching to `version 1.7` , can you confirm that `give_version` was `1.6` or minimum?

**Comment by DevinWalker** [comment]
Ok, after a call with Ravinder he explained:

1. When you switch to `1.7` branch the `give_version` option is updated
2. The license upgrade only runs once when the `give_version` option is updated
3. Subsequent branch switches from `master` to `release/1.7` won't be accurate as the option is already update

To truly test you will need to update `give_version` to less than `1.7` and then test as I have shown above. 

Closing again 👍

**Comment by ravinderk** [comment]
@DevinWalker Please also check `New licensing UI updates and code review` pr against `release/1.8` because license page tab has different dom structure than `release/1.7`. We developed new license page ( `release/1.8`) with new setting API.

**Comment by DevinWalker** [comment]
@ravinderk that's taken care of now in `release/1.8` 👍
