### ISSUE TITLE
fix(shortcode): ensure the donors are showing on the donor wall when they submit a donation

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3581]
## User Story
As a site admin, I want the shortcode for the Donor Wall to function so that it can be used on the front-end of the site.

## Current Behavior
I currently have the shortcode on a page, and nothing is displaying. This functionality was working and now isn't.

## Expected Behavior
I expect to have the shortcode function without issue.

## Steps to Reproduce
1. Submit a few donations after the release of 2.2
2. Place the shortcode on a page linking it to the form you submitted the donations to
3. View the page where the donors are supposed to be displaying and see nothing. 

## Visuals
Here is the donor wall when it was functioning, see that the last on was on the 31st:
<img width="990" alt="screen shot 2018-08-07 at 8 40 13 am" src="https://user-images.githubusercontent.com/20672471/43776348-893190ea-9a1d-11e8-967e-a8a95dd3674e.png">

Here is a donation to the same form that isn't showing up:
<img width="873" alt="screen shot 2018-08-07 at 8 45 55 am" src="https://user-images.githubusercontent.com/20672471/43776604-5adb982a-9a1e-11e8-859b-606f38bb1257.png">

## Related
https://secure.helpscout.net/conversation/632665703/22737?folderId=1823994

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: https://givewp.gsamsmith.com
Site URL: https://givewp.gsamsmith.com
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wpk1_
Table Prefix Length: 5
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givewp.gsamsmith.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache
PHP Version: 7.0.31
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
PHP Max Upload Size: 128 MB
cURL Version: 7.59.0, OpenSSL/1.0.2k
SUHOSIN Installed: –
MySQL Version: 5.6.40
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.2
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://givewp.gsamsmith.com/donation-confirmation/
Failure Page: https://givewp.gsamsmith.com/donation-failed/
Donation History Page: https://givewp.gsamsmith.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card, Test Donation
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: IPN received for #370 ( N/A ) on 08/01/2018 at 07:25. Status N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - 2Checkout Gateway: ✔ Licensed – by WordImpress – 1.1.1
Give - Authorize.net Gateway: ✔ Licensed – by WordImpress – 1.4.2
Give - AWeber: ✔ Licensed – by WordImpress – 1.0.3
Give - Braintree Gateway: ✔ Licensed – by WordImpress – 1.2.2
Give - CCAvenue Gateway: ✔ Licensed – by WordImpress – 1.0.2
Give - Constant Contact: ✔ Licensed – by WordImpress – 1.2.1
Give - ConvertKit: ✔ Licensed – by WordImpress – 1.0.2
Give - CSV Toolbox: ❌ Unlicensed – by WordImpress – 1.0
Give - Currency Switcher: ✔ Licensed – by WordImpress – 1.2.2
Give - Dwolla Gateway: ✔ Licensed – by WordImpress – 1.1.2
Give - Email Reports: ✔ Licensed – by WordImpress – 1.1.2
Give - Fee Recovery: ✔ Licensed – by WordImpress – 1.7.1
Give - Form Field Manager: ✔ Licensed – by WordImpress – 1.3
Give - GoCardless Gateway: ✔ Licensed – by WordImpress – 1.2
Give - Google Analytics Donation Tracking: ✔ Licensed – by WordImpress – 1.1.4
Give - iATS Payment Solutions: ✔ Licensed – by WordImpress – 1.0.3
Give - MailChimp: ✔ Licensed – by WordImpress – 1.4.1
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4.1
Give - PayFast Payment Gateway: ❌ Unlicensed – by WordImpress – 1.0.2
Give - PayPal Pro Gateway: ✔ Licensed – by WordImpress – 1.1.6
Give - Paytm Gateway: ✔ Licensed – by WordImpress – 1.0
Give - PayUmoney: ❌ Unlicensed – by WordImpress – 1.0.1
Give - PDF Receipts: ✔ Licensed – by WordImpress – 2.3
Give - Per Form Gateways: ✔ Licensed – by WordImpress – 1.0.1
Give - Razorpay: ❌ Unlicensed – by WordImpress – 1.2.0
Give - Recurring Donations: ✔ Licensed – by WordImpress – 1.7.2
Give - Sofort Payment Gateway: ❌ Unlicensed – by WordImpress, CoachBirgit – 1.0
Give - Stripe Gateway: ✔ Licensed – by WordImpress – 2.0.10
Give - Tributes: ✔ Licensed – by WordImpress – 1.5.0
Give - Zapier: ✔ Licensed – by WordImpress – 1.2.1

### Other Active Plugins ###

All-in-One WP Migration: by ServMask – 6.73
Duplicator: by Snap Creek – 1.2.40
Give - Paymill Gateway: by WordImpress – 1.0.2
SG Optimizer: by SiteGround – 4.0.7
Transients Manager: by Pippin Williamson – 1.7.5
WP Rollback: by WordImpress – 1.5.1
WP Updates Notifier: by Scott Cariss – 1.4.4

### Inactive Plugins ###

Duplicate Post: by Enrico Battocchi – 3.2.2
Email Cop: by Ashfame – 0.1.1
Give - AmeriCloud Payments: by AmeriCloud Solutions, Inc. – 1.2.0
Give - Gift Aid: by WordImpress – 1.1.5
Give - Mollie Gateway: by WordImpress – 1.1.1

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

**Comment by Sidsector9** [comment]
Hi @samsmith89 , can you tell me what shortcode are you using?

For me `[give_donor_wall form_id="584" only_comments="false"]` works perfectly.

Are you passing the `only_comments="false"` parameter as well?

**Comment by samsmith89** [comment]
@Sidsector9 No, I'm passing in just the shortcode:
[give_donor_wall form_id="186"]

**Comment by Sidsector9** [comment]
@samsmith89 Do you have any donors who have made a comment while donation? And also make sure that anonymous donation is disabled. For me `[give_donor_wall form_id="584"]` works if there are comments made by donors.


@DevinWalker , I think `only_comments` should be `false` by default. In case of anonymous donations, the admin won't know the internal parameters and would think the donor wall shortcode isn't working.

**Comment by DevinWalker** [comment]
I agree @Sidsector9 - can you update that default?

**Comment by Sidsector9** [comment]
Sure @DevinWalker :+1:
