### ISSUE TITLE
compat(form): resolve error with popular GDPR plugin

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#3587]
## User Story

As a `give admin`, I want `to use Give alongside the GDPR Framework plugin` so that `my site is both GDPR compliant and able to accept donations.`.

## Current Behavior
Since Give 2.2 and anonymous donations/comments, we are now including comments, and apparently a comment within a donation flags their "consent error" so after a donation, the donor is directed to an ERROR page. The donation still happens and is recorded at the gateway, but the donor does not know that. 

## Expected Behavior
I expect to be able to donate with no issue.

## Possible Solution
This might be more on their end than ours, but it's worth bringing up here.

## Steps to Reproduce
1. Install https://wordpress.org/plugins/gdpr-framework/ and activate it
2. auto-install the pages in the prompt after activating it.
2. submit a donation in 2.2 of Give with comments active (test gateway is fine, and you don't even have to fill out the comment)
3. errors

## Related
- https://secure.helpscout.net/conversation/634306057/0/?folderId=848135
- https://secure.helpscout.net/conversation/640800506/23464?folderId=1823994
- https://secure.helpscout.net/conversation/640764578/23445?folderId=1823994
- https://secure.helpscout.net/conversation/642222136/23572/

## Tasks

- [ ] Ensure that donations don't result in the consent error

**Comment by kevinwhoffman** [comment]
@ravinderk Please prioritize this one.

**Comment by samsmith89** [comment]
Another plugin is having this issue with comments.
http://www.wpbruiser.com/

Let me know if this needs a separate issue, but I believe they are related. 
https://secure.helpscout.net/conversation/642921006/23651

**Comment by DevinWalker** [comment]
Resolved in https://github.com/WordImpress/Give/issues/3627
