### ISSUE TITLE
fix(comment): exclude Woocommerce comment count from WordPress comments

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#3589]
## User Story
As an `admin`, I want do not want to see woocomerce comments in total comment count on comment listing page.

ref: https://github.com/WordImpress/Give/issues/3588

Give and Woocomerce both hide there comments from comment count, so whose filter run late will overwrite others change.

**Comment by DevinWalker** [comment]
Resolved via https://github.com/WordImpress/Give/issues/3627
