### ISSUE TITLE
[UK-specific] Gift Aid extension

### ISSUE THREAD

**Issue by rosswintle** [WordImpress/Give#36]
Don't know why I didn't think about this before. It's REALLY important.

[Note: this is a vastly simplified explanation of how tax works in the UK, I've given you only the facts that you need to know in order to understand Gift Aid]

In the UK we have a system called "Gift Aid".  This scheme is based on the fact that giving to charity is tax-exempt.

Now, unlike in the US, where I think everyone pays tax at the end of the year, we effectively have a "pay-as-you-go" system for tax on salary/earnings. Your tax is estimated up-front and spread throughout the year. It's deducted from your salary each month. So Gift Aid is a special system for dealing with the fact that everyone has ALREADY paid all their income tax by the end of the year.

Now...our tax rate is (for the purposes of Gift Aid) 20%. So if I earn £1.25 then I pay £0.25 in tax. Because donations are tax-exempt I'm allowed to give that £0.25 to the charity rather than to the government.  But rather than me claim it back and pay it to the charity (or pay it to the charity and then claim it back), the CHARITY claims that 25p from the government.

So when you make a charitable donation in the UK you are asked if you pay tax and if the charity can claim that from you.  The charity then send a report to the government of all Gift Aid'ed donations to claim their extra money.

Probably the best starting point for finding out about Gift Aid is the [government's own website](https://www.gov.uk/claim-gift-aid/overview).

Probably the most important section of information is [How to Claim section](https://www.gov.uk/claim-gift-aid/how-to-claim)

So...if Give wants to support this it will need to do two things.

1) It will need to collect additional information from donors:
 - Title
 - First name or Initial
 - Last name
 - Building/house name or number
 - Postcode (UK equivalent of zip code)

Exact details of what is needed is [here](https://www.gov.uk/schedule-spreadsheet-to-claim-back-tax-on-gift-aid-donations)

2) It will need to provide reporting functionality.  Again the link immediately above tells you what you need to submit.  More importantly there are downloadable spreadsheets that you can fill in. Find them at the bottom of [this page](https://www.gov.uk/schedule-spreadsheet-to-claim-back-tax-on-gift-aid-donations)

I've not looked into it much but there are also [approved software tools for making submissions](https://www.gov.uk/government/publications/charities-online-commercial-software-suppliers) and presumably an API for doing so (start investigating that [here](https://www.gov.uk/government/collections/charities-online-support-for-software-developers))

I totally appreciate that this is a complex addition. But, for manual, spreadsheet-based submission, maybe not TOO complex. It would be a massive thing to add for the UK market.

Happy to discuss more.

**Comment by DevinWalker** [comment]
@mathetos can you add this to the add-on voting on givewp.com/addons/ and close out?

**Comment by mathetos** [comment]
Done: https://givewp.com/coming-soon/
