### ISSUE TITLE
Give donation form shortcode not respecting show_goal="false" 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#360]
Reported here: https://github.com/WordImpress/Give/issues/new

Using a shortcode such as `[give_form id="114" show_title="false" show_goal="false" show_content="none" display_style="reveal" float_labels="enabled"]` will result in the goal still being output incorrectly.

**Comment by kjbrum** [comment]
Any idea on when the next release will be that includes this fix?

**Comment by DevinWalker** [comment]
I'm pushing to get it out this week :)

**Comment by kjbrum** [comment]
Awesome! :+1:
