### ISSUE TITLE
fix: allow 8 number of decimal position for bitcoin

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#3602]
## User Story
As an `admin`, I want to the donor to allow donor to donate in bitcoin but it need 8 number of decimal precision.

Currently, we can only set < 8 number of decimal precision because 8 is preserved for core amount formatting, which allows to easily sanitize formatted or unformatted number.

Source: https://wordpress.org/support/topic/error-btc-currency-always-defaults-to-5-digits-even-when-setup-8-digits/

**Comment by ravinderk** [comment]
@DevinWalker Bumping up this issue because it can break a few addons because it is directly related to amount formatting.

**Comment by raftaar1191** [comment]
@ravinderk will test this PR with other add-on and will let you know

**Comment by raftaar1191** [comment]
Slack Chat: https://givewp.slack.com/archives/C0FAGC83C/p1535517757000100

**Comment by ravinderk** [comment]
This issue still opens because my review is pending
