### ISSUE TITLE
fix(compat): resolve error with Mojo Marketplace plugin.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#3604]
## User Story

As a `donor`, I want `to be able to know my donation went through when Mojo Marketplace is installed.`

## Current Behavior
Currently, with Mojo Marketplace installed (it's there by default in Bluehost installs) every donation in 2.2.x of Give returns `Blocked as suspected bot` when the Marketplace plugin is active. The donation still goes through, but there is no indication to the donor that it did.

## Expected Behavior
I expect the plugins to play nicely together. 

## Possible Solution
This might need a patch on their end.

## Steps to Reproduce
1. Download the production branch here: https://github.com/mojoness/mojo-marketplace-wp-plugin/tree/production
2. Install and activate it.
3. Submit a test donation on any form. 

"Blocked as suspected Bot" will display, yet the donation still goes through.

## Related
- https://secure.helpscout.net/conversation/640603127/23410?folderId=848135
- https://secure.helpscout.net/conversation/652084645/24328/
- https://github.com/WordImpress/Give/issues/3587

## Tasks

- [ ] ensure that donations can be accepted with the Mojo Marketplace active.

**Comment by kevinwhoffman** [comment]
@ravinderk Assigning this one to you as it might be related to https://github.com/WordImpress/Give/issues/3587 regarding the possibility of comments triggering the bot detection in Give v2.2.X.

**Comment by DevinWalker** [comment]
Resolved via https://github.com/WordImpress/Give/issues/3627
