### ISSUE TITLE
Update Give form interface

### ISSUE THREAD

**Issue by ShaoboZhangProduction** [WordImpress/Give#3616]
I am updating an old website. The whole website needs to be updated. I already updated the plugin. Now, I am trying to change the interface style. 

<Currently Situation/Problem>
I am using "Addition CSS" in the theme to update the interface. I want to change the whole interface to transparent. I already changed the form background, First Name input box and Last Name input box. However, I am struggling to update the amount input box and amount display box. I just can't make them transparency. 

<My Code>
I am using ID attribute rather than the Class. 

#give-amount{
 background: rgba(255,255,255,0.4);
  border: none;
}

This code works in the Name boxes. I also tried class attribute. However, it is not working.

<Any solutions? Also, do they have any fool tool to edit it?>
Or
<Do you have any better plugin for recommendation? (Must be free)>

<Thank you>

**Comment by mathetos** [comment]
Hi @ShaoboZhangProduction 

Please use our free Support Forum for questions of this nature:
https://wordpress.org/support/plugin/give

Thank you!
