### ISSUE TITLE
feat(shortcode): ensure user can set the display order of the donor wall

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3622]
## User Story
As a `site admin`, I want `to set the order of the donor wall` so that `it doesn't only display randomly`.

## Current Behavior
I currently have the donor wall displaying donations at random.

## Expected Behavior
I expect to set this to at least a chronological order.

## Related
https://secure.helpscout.net/conversation/644292068/23754

**Comment by samsmith89** [comment]
@raftaar1191 @kevinwhoffman @DevinWalker 
There still isn't a way to set the order of donors on the donor wall. Could this have been closed by mistake?

![screen shot 2018-09-20 at 2 06 48 pm](https://user-images.githubusercontent.com/20672471/45837948-89797480-bcde-11e8-922d-71c4e51f2c7c.png)

Is there something that can be passed to the shortcode to control this? 
Let me know if I need to create another issue.

**Comment by kevinwhoffman** [comment]
This is still an unresolved issue as the user has no way to set the order. We will resolve in https://github.com/impress-org/give/issues/3745.
