### ISSUE TITLE
doc(jest): add UI testing instructions

### ISSUE THREAD

**Issue by Sidsector9** [WordImpress/Give#3625]
## User Story
As a developer, I want to update the README file with testing Front End UI instructions so that other developers can perform testing.

## Current Behavior
Currently README doesn't have any instructions for Front End UI testing.

## Expected Behavior
I expect the README to have clear instructions regarding Front End UI testing.

## Tasks
- [x] Update README file

**Comment by kevinwhoffman** [comment]
@Sidsector9 Let's add the testing instructions to a `README.md` within the tests folder. It does not need to be part of the main `README.md` for the entire plugin.
