### ISSUE TITLE
"GitHub Plugin URI" Plugin Header causes problems for users with GitHub Updater installed; missing Dist Files

### ISSUE THREAD

**Issue by d4mation** [WordImpress/Give#3635]
## User Story

As a developer, I want some changes to the Tags/Releases for this repository so that it is more compatible with [GitHub Updater](https://github.com/afragen/github-updater).

[This is only a problem if `wp-config.php` contains `define( 'GITHUB_UPDATER_OVERRIDE_DOT_ORG', true );` ](https://github.com/afragen/github-updater/wiki/WordPress.org-Directory#overriding-wporg-directory-updates)

Because the 'GitHub Plugin URI' Plugin Header is defined, GitHub Updater will try to use GitHub for updates. This would normally be fine, but since the `/assets/dist/` directory is not included in the repository those are not downloaded and causes issues.

## Current Behavior

I currently am unable to update the Plugin without SFTP-ing the updates in manually since I am using GitHub Updater with `define( 'GITHUB_UPDATER_OVERRIDE_DOT_ORG', true );` set.

## Expected Behavior

I expect to be able to update normally without unsetting `define( 'GITHUB_UPDATER_OVERRIDE_DOT_ORG', true );` from my `wp-config.php`

## Possible Solution

There are a few ways around this:

1. Include `/assets/dist/` in the repository. I can understand not wanting to do this.
2. Create Releases attached to each Tag and upload a Release ZIP including the `/assets/dist/` directory and use the [`Release Asset`](https://github.com/afragen/github-updater/wiki/Settings#release-assets) Plugin Header.
    - This makes it impossible to switch Branches with GitHub Updater for this Repository as it cannot grab those missing files still
3. Remove the `GitHub Plugin URI` Plugin Header to prevent this issue.

## Steps to Reproduce

1. Set `define( 'GITHUB_UPDATER_OVERRIDE_DOT_ORG', true );` in `wp-config.php`
2. Change branches/update Give
3. Try to Edit a Post or otherwise access a page where Give's JS/CSS would need to load.

## Visuals

Causes a lot of Scripts and Styles to not load. Example:

![image](https://user-images.githubusercontent.com/7770631/44732651-c2457580-aab3-11e8-9eda-ad1fd9bc3098.png)

## Tasks

- [ ] One of the suggested solutions from above needs implemented.

**Comment by ravinderk** [comment]
@d4mation You cannot update your plugin with Github updater because it is not complete release repo. We have to run release script on `master` branch which will remove a few files and make sure its production ready.

for ref: https://github.com/WordImpress/Give/blob/release/2.2.4/package.json#L10

**Comment by d4mation** [comment]
@ravinderk Unfortunately, with the listed settings that I gave above, GitHub Updater will forcefully try to use this repo to update because of the Plugin Header here: https://github.com/WordImpress/Give/blob/release/2.2.4/give.php#L11

If this Repo should not be used with GitHub Updater it should probably be removed to avoid conflict.

**Comment by ravinderk** [comment]
Closing this with https://github.com/WordImpress/Give/commit/dc14d10b25a016cab49e3933ac3d8221ec4a4f11
