### ISSUE TITLE
qa(give): ensure quality of Give Fee Recovery 2.2.4

### ISSUE THREAD

**Issue by raftaar1191** [WordImpress/Give#3642]
## Acceptance Criteria
- [x] Test with Add-on
- [x] Give has been tested with PHP version 5.3 to PHP version 7.2

## Related
- [x] https://github.com/WordImpress/Give/issues/3636
- [x] https://github.com/WordImpress/Give/issues/3633
- [x] https://github.com/WordImpress/Give/issues/3631
- [x] https://github.com/WordImpress/Give/issues/3622
- [x] https://github.com/WordImpress/Give/issues/3628
- [x] https://github.com/WordImpress/Give/issues/3619
- [x] https://github.com/WordImpress/Give/issues/3617
- [x] https://github.com/WordImpress/Give/issues/3575
- [x] https://github.com/WordImpress/Give/issues/3611
- [x] https://github.com/WordImpress/Give/issues/3603
- [x] https://github.com/WordImpress/Give/issues/3597
- [x] https://github.com/WordImpress/Give/issues/3599
- [x] https://github.com/WordImpress/Give/issues/3606

**Comment by raftaar1191** [comment]
Tested and ready for release 


Google Sheet Link: https://docs.google.com/spreadsheets/d/1qP42uP2UNdKnx90hzfQ0GXMsyuOfZHWgcjt53JuNucw/edit#gid=827144806

**Comment by DevinWalker** [comment]
Issue moved to [WordImpress/Give-Fee-Recovery #235](https://github.com/WordImpress/Give-Fee-Recovery/issues/235) via [**ZenHub**](https://www.zenhub.com/)
