### ISSUE TITLE
feat(admin-gateway): give users ability to pass Form Field Manager data to PayPal Standard

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3645]
## User Story
As a `site admin`, I want `to pass Form Field Manager data to PayPal Standard` so that `the information will be recorded`.

## Current Behavior
I currently see none of this information associated with the payment in the PayPal Standard account.

## Expected Behavior
I expect to have this information passed to the gateway.

## Related
https://secure.helpscout.net/conversation/653827082/24538

This customer would like the Form Field Manager data to be passed to the receipt email from PayPal if possible.

**Comment by DevinWalker** [comment]
Unfortunately this is not possible with PayPal Standard.

**Comment by samsmith89** [comment]
I appreciate the fast response.
