### ISSUE TITLE
feat(paypal): send more actionable info to Paypal to differentiate transactions that originated through Give

### ISSUE THREAD

**Issue by jaydeeprami** [WordImpress/Give#3651]
## User Story
As a `Give_Admin`, I want `to pass Invoice ID Prefix` with Invoice key so that `I can differentiate transactions `.

## Current Behavior
I currently not differentiate transactions that originated through Give

## Expected Behavior
I expect to differentiate transactions that originated through Give

## Possible Solution
- Use Invoice Prefix

## Steps to Reproduce
- Send info to PayPal from test transactions from both Give and WooCommerce
- Export a report from within PayPal. 

## Related
https://github.com/WordImpress/Give-PayPal-Pro/issues/15

## Tasks

- [x] Fix

## Environment

<details>
    <summary>WordPress System Info</summary>
   ### WordPress Environment ###

Home URL: http://1b3c390e.ngrok.io
Site URL: http://1b3c390e.ngrok.io
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.test
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information❌Email access❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email❌Subscriptions Email Access
Upgraded From: 2.2.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://1b3c390e.ngrok.io/donation-confirmation/
Failure Page: http://1b3c390e.ngrok.io/donation-failed/
Donation History Page: http://1b3c390e.ngrok.io/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, PayPal Standard, PayPal Website Payments Pro (NVP API), PayPal Website Payments Pro (REST API), PayPal Payments Pro
Default Payment Gateway: PayPal Standard
PayPal IPN Verification: Enabled
PayPal IPN Notifications: IPN received for #1002 ( N/A ) on 09/04/2018 at 04:46. Status VERIFIED
Donor Email Access: Disabled

### Active Give Add-ons ###

Give - Recurring Donations: ❌ Unlicensed – by WordImpress – 1.8.0

### Other Active Plugins ###

Give - PayPal Pro Gateway: by GiveWP – 1.2.0
PayPal for WooCommerce: by Angell EYE – 1.4.14
WooCommerce: by Automattic – 3.4.3

### Inactive Plugins ###

Advanced Custom Fields: by Elliot Condon – 4.4.12
CCAvenue Payment Gateway for WooCommerce: by Nilesh Chourasia – 2.3
Give - Authorize.net Gateway: by WordImpress – 1.4.2
Give - CCAvenue Gateway: by WordImpress – 1.0.1
Give - Currency Switcher: by WordImpress – 1.2.2
Give - Donation Upsells for WooCommerce: by WordImpress – 1.0.2
Give - Fee Recovery: by GiveWP – 1.7.2
Give - Form Field Manager: by WordImpress – 1.4.0
Give - Gift Aid: by WordImpress – 1.1.4
Give - GoCardless Gateway: by WordImpress – 1.2
Give - Manual Donations: by WordImpress – 1.4.1
Give - Mollie Gateway: by WordImpress – 1.1.2
Give - PDF Receipts: by WordImpress – 2.3.0
Give - Stripe Gateway: by GiveWP – 2.1.0
Give - Tributes: by WordImpress – 1.5.0
Gravity Forms: by rocketgenius – 2.1.1
Gutenberg: by Gutenberg Team – 3.3.0
Gutenberg: by Gutenberg Team – 3.3.0
Magic-fields: by Hunk – 1.7.3
WooCommerce Gutenberg Products Block: by Automattic – 1.1.0
WooCommerce Quick Checkout: by WordImpress – 1.9.7
WooCommerce Services: by Automattic – 1.15.1
WooCommerce Subscriptions: by Prospress Inc. – 2.3.4

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: x.x.x</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: x.x.x</li>
    </ul>
</details>

**Comment by ravinderk** [comment]
@jaydeeprami @DevinWalker Add few commit to improve code https://github.com/WordImpress/Give/compare/6a44ef774798...a5c1b59d49ae
