### ISSUE TITLE
fix(admin-add-on): remove the text that is being displayed at top of the Addons page

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3668]
## Current Behavior
I currently see text displayed on the Addons page in the admin side of the site

<img width="343" alt="screen shot 2018-09-10 at 3 57 26 pm" src="https://user-images.githubusercontent.com/20672471/45321044-41a26280-b512-11e8-83fa-276269f9c6b4.png">

## Expected Behavior
I expect to not see this text.

## Steps to Reproduce
1. Load the Addons page in the admin panel
2. See the text at the top of the page

## Visuals
![screen shot 2018-09-10 at 3 54 18 pm](https://user-images.githubusercontent.com/20672471/45321094-63034e80-b512-11e8-90df-50c21e6bb74a.png)

## Related
https://secure.helpscout.net/conversation/659822763/25174

## Acceptance Criteria

- [ ] Something is true.
- [ ] Something happens when I do this.

## Environment
<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome 
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
   ### WordPress Environment ###

Home URL: http://give.local
Site URL: http://give.local
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.2.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report✔Renewal Receipt Email✔Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.2.3
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.local/donation-confirmation/
Failure Page: http://give.local/donation-failed/
Donation History Page: http://give.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card, PayPal Standard, Test Donation
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ✔ Licensed – by WordImpress – 1.4.3
Give - Braintree Gateway: ✔ Licensed – by WordImpress – 1.2.2
Give - CCAvenue Gateway: ✔ Licensed – by WordImpress – 1.0.2
Give - Donation Upsells for WooCommerce: ❌ Unlicensed – by WordImpress – 1.0.3
Give - Email Reports: ✔ Licensed – by WordImpress – 1.1.2
Give - Form Field Manager: ✔ Licensed – by WordImpress – 1.3
Give - MailChimp: ✔ Licensed – by WordImpress – 1.4.1
Give - Manual Donations: ✔ Licensed – by WordImpress – 1.4.1
Give - Paytm Gateway: ✔ Licensed – by WordImpress – 1.0
Give - PDF Receipts: ✔ Licensed – by WordImpress – 2.3
Give - Razorpay: ❌ Unlicensed – by WordImpress – 1.2.0
Give - Recurring Donations: ✔ Licensed – by WordImpress – 1.8.0
Give - Tributes: ✔ Licensed – by WordImpress – 1.5.0

### Other Active Plugins ###

Give - Fee Recovery: by GiveWP – 1.7.2
Give - Google Analytics Donation Tracking: by GiveWP – 1.2.1
Give - Hook Helper: by Ravinder Kumar – 1.0
Give - PayPal Pro Gateway: by GiveWP – 1.2.0
Give - Stripe Gateway: by GiveWP – 2.1.0
Sam's Helper Function: by WordImpress – 1.0
WooCommerce: by Automattic – 3.4.5
WordPress Importer: by wordpressdotorg – 0.6.4
WP Business Reviews: by Impress.org – 1.0.0

### Inactive Plugins ###

All-in-One WP Migration: by ServMask – 6.73
Duplicate Post: by Enrico Battocchi – 3.2.2
Indeed Ultimate Affiliate Pro: by indeed – 1.5
Mailgun: by Mailgun – 1.5.11
Page Builder by SiteOrigin: by SiteOrigin – 2.7.3
The7 Elements: by Dream-Theme – 1.11.0.1
The7 Ultimate Addons for WPBakery Page Builder: by Brainstorm Force – 3.16.24
ThemeREX Addons: by ThemeREX – 1.6.24
User Role Editor: by Vladimir Garagulya – 4.44
WooCommerce Paytm Payment Gateway: by Paytm – 0.2
WooCommerce Paytm Payment Gateway: by FTI Technologies – 1.0
WP Courseware: by Fly Plugins – 4.4.4
WPML Media: by OnTheGoSystems – 2.3.5
WPML Multilingual CMS: by OnTheGoSystems – 4.0.5
WPML Sticky Links: by OnTheGoSystems – 1.4.4
WPML String Translation: by OnTheGoSystems – 2.8.5
WPML Translation Management: by OnTheGoSystems – 2.6.5

### Active MU Plugins ###

Bypass Login: by Stephen Carnam – 1.1.0
Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment]
@samsmith89 This has been resolved https://github.com/WordImpress/Give-Website/issues/295#issuecomment-420092349
