### ISSUE TITLE
Email templates cannot be customized within theme like other templates

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#368]
Following our templating structure for overriding Give template, this seemingly cannot be done for email templates at the moment.

I tried placing the `emails\header-default.php` into each of the following theme folders and each one did not work:

* twentytwelve\give\emails\header-default.php
* twentytwelve\give\templates\emails\header-default.php
* twentytwelve\give\templates\header-default.php
* twentytwelve\give\header-default.php

The expected behavior is to be able to copy the `header-default.php` file directly from the Give plugin and paste it into `twentytwelve\give\templates\emails\header-default.php` and be able to customize it directly there and see those changes reflected when previewing the email through the "Donations > Settings > Emails" section.

**Comment by DevinWalker** [comment]
:+1:

**Comment by DevinWalker** [comment]
I just tested and it's working in my child theme - please verify

**Comment by mathetos** [comment]
Worked locally here. Will have to test at home again to see why it didn't work on my laptop. But will close for now.
