### ISSUE TITLE
fix: formatCurrency fn throw JS error for INR

### ISSUE THREAD

**Issue by jaydeeprami** [WordImpress/Give#3683]
## Current Behavior
I currently see JS error in Console when INR is set.

## Expected Behavior
I expect to no JS error

## Steps to Reproduce
1. Give version 2.3.0
2. Set Default Currency as INR
3. Create Multi-level donation form and change donation level

## Visuals
![format_currency](https://user-images.githubusercontent.com/15060983/45544628-775a8a80-b835-11e8-8ade-cbf62cd3c17e.png)

## Acceptance Criteria

- [ ] Fix
- [ ] Test

## Environment
<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: x.x.x</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: x.x.x</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: http://give.test
Site URL: http://give.test
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.test
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.2.4
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note❌Email access
Upgraded From: 2.2.0
Test Mode: Enabled
Currency Code: INR
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give.test/donation-confirmation/
Failure Page: http://give.test/donation-failed/
Donation History Page: http://give.test/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, PayPal Standard
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: IPN received for #1025 ( 45L229017A462301L ) on 09/05/2018 at 05:35. Status VERIFIED
Donor Email Access: Disabled

### Other Active Plugins ###

PayPal for WooCommerce: by Angell EYE – 1.4.14
WooCommerce: by Automattic – 3.4.3

### Inactive Plugins ###

Advanced Custom Fields: by Elliot Condon – 4.4.12
CCAvenue Payment Gateway for WooCommerce: by Nilesh Chourasia – 2.3
Give - Authorize.net Gateway: by WordImpress – 1.4.2
Give - CCAvenue Gateway: by WordImpress – 1.0.1
Give - Currency Switcher: by WordImpress – 1.2.2
Give - Donation Upsells for WooCommerce: by WordImpress – 1.0.2
Give - Fee Recovery: by GiveWP – 1.7.2
Give - Form Field Manager: by WordImpress – 1.4.0
Give - Gift Aid: by WordImpress – 1.1.4
Give - GoCardless Gateway: by WordImpress – 1.2
Give - Manual Donations: by WordImpress – 1.4.1
Give - Mollie Gateway: by WordImpress – 1.1.2
Give - PayPal Pro Gateway: by GiveWP – 1.2.0
Give - PDF Receipts: by WordImpress – 2.3.0
Give - Recurring Donations: by WordImpress – 1.8.0
Give - Stripe Gateway: by GiveWP – 2.1.0
Give - Tributes: by WordImpress – 1.5.0
Gravity Forms: by rocketgenius – 2.1.1
Gutenberg: by Gutenberg Team – 3.3.0
Gutenberg: by Gutenberg Team – 3.3.0
Magic-fields: by Hunk – 1.7.3
WooCommerce Gutenberg Products Block: by Automattic – 1.1.0
WooCommerce Quick Checkout: by WordImpress – 1.9.7
WooCommerce Services: by Automattic – 1.15.1
WooCommerce Subscriptions: by Prospress Inc. – 2.3.4

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment]
@jaydeeprami  It was fixed by @Sidsector9 but appear due to the wrong resolve of merge conflict: https://github.com/WordImpress/Give/pull/3514
