### ISSUE TITLE
Split (aka A/B) testing

### ISSUE THREAD

**Issue by rosswintle** [WordImpress/Give#37]
Sorry - I'm at it again.

Advanced feature here. Possibly extension-worthy.

Would be great to be able to do split-testing (A/B testing) experiments. So we serve one form to a percentage of users, another form to a percentage of users, and see which performs best.

One simple way that you could do this is to build two separate forms, and have the shortcode for inserting the form (or the widget settings, or whatever) allow you to specify the forms and percentages. e.g.

[give_split_form form1="57,60" form2="58,40"]

You might want to store session IDs so that the user experience doesn't change while a person is navigating the site.

**Comment by mathetos** [comment]
Added this to our Voting page, we'll see how folks respond: https://givewp.com/coming-soon/
