### ISSUE TITLE
WordPress 4.4 bug and Give Tabs

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#377]
With the change of h1 primary titles our h2 tag shows an obvious error:

![10-28-2015 5-32-35 pm](https://cloud.githubusercontent.com/assets/1571635/10807178/03b89a82-7d9a-11e5-8e4f-0178a3c2a586.png)

**Comment by DevinWalker** [comment]
It's also appearing under Downloads > Reports, Tools, anywhere where tabs are used with h2s

**Comment by mathetos** [comment]
I think we just have to add an H1 to the top of the page and it'll be fine right?

**Comment by DevinWalker** [comment]
Just wrap it in an h2
