### ISSUE TITLE
Incorrect donation notification - or possible email settings issue

### ISSUE THREAD

**Issue by rosswintle** [WordImpress/Give#38]
I seem to get the wrong email back to admin when I make a donation.

Donation notification settings:

![screen shot 2015-03-16 at 21 39 31](https://cloud.githubusercontent.com/assets/1532368/6677136/181adab6-cc25-11e4-97ff-4b4cbc51cf34.png)

Donation email:

![screen shot 2015-03-16 at 21 40 54](https://cloud.githubusercontent.com/assets/1532368/6677148/2fbca672-cc25-11e4-9985-acc6dcc769b1.png)

Is this because I'm using "Default template" rather than "No template, plain text only"?  And if so, should the fields for entering content be disabled if a template is selected rather than "No template, plain text only"?

**Comment by DevinWalker** [comment]
Related to #40 - once the default settings are being appropriately save on install this shouldn't be an issue. I've also updated the text within the default email so it's more aligned with donations.

**Comment by DevinWalker** [comment]
Fixed with latest commit from 9c27c72
