### ISSUE TITLE
feat: provide option to have sequential ordering on per-form basis

### ISSUE THREAD

**Issue by samsmith89** [WordImpress/Give#3824]
# Feature Request

## User Story

As a site admin, I want each form to have its own type of sequential ordering because I have a multilingual site where there is a form for each language. This way there aren't any gaps in the order of donations for better organization.

## Related

https://secure.helpscout.net/conversation/698762296/28390

## Acceptance Criteria

- [ ] There is an option to have sequential ordering on a per-form basis.

**Comment by kevinwhoffman** [comment]
This isn't possible with our current approach to sequential ordering. The the `wp_give_sequential_ordering` table uses the `PRIMARY` index of the MySQL table as a basis for ordering, and the `PRIMARY` index requires the value of each row to be unique. It is this functionality that ensures the sequence increments without overlap.

Leaving open for feedback in case there's a solution I'm overlooking.

**Comment by ravinderk** [comment]
@kevinwhoffman @DevinWalker With current table schema we can not do that. If we want to add perform basis sequential id feature then we have to update the table schema of `wp_give_sequential_ordering `.
