### ISSUE TITLE
{receipt_link} markup stripped in text-only emails

### ISSUE THREAD

**Issue by andrejcremoznik** [WordImpress/Give#384]
When sending text e-mails instead of html, `{receipt_link}` markup gets stripped only leaving *"View it in your browser."* plain text behind. This results in a useless e-mail notification without a working receipt link.

Check for email content type in `give_email_preview_template_tags()` when doing `str_replace` for `{receipt_link}`.

**Comment by mathetos** [comment]
Thanks for reporting this, we should be able to work this into Milestone 1.3.2
