### ISSUE TITLE
Conflicts with WP Geo

### ISSUE THREAD

**Issue by konus1** [WordImpress/Give#386]
If I create a form with the setting "Yes, display content ABOVE the form fields" and put this form in a widget, I get a map from the plugin WP Geo https://wordpress.org/plugins/wp-geo/ It looks like it triggers the shortcut [wp_geo_map].
It does not happen on a single page.

**Comment by mathetos** [comment]
HI Conrad,

I'll need to dig into that a bit more to understand what's happening. Here's what I'd suggest:

Try going to "Donations > Settings" then the Advanced tab and enable the setting "Disable the_content filter"

If that doesn't resolve it, please follow-up on this at our support forum:
https://wordpress.org/support/plugin/give

And provide details about what happened after you disabled `the_content` filter, and provide a link to your site so I can see what's going on.

Thanks!
