### ISSUE TITLE
Goal formatting is not easily filterable

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#387]
You can see this support request, which is a reasonable request:
https://wordpress.org/support/topic/progress-bar-percent-rather-than-amount?replies=1#post-7637862

Digging into that function we can see that filtering the output of that markup would require basically swapping out the entire function. 

## Suggestions
* Add a filter to each element of the goal
* Add a new setting that allows users to display the goal as Amount or Percentage

**Comment by ibndawood** [comment]
@mathetos - You can assign this to me as well.

**Comment by DevinWalker** [comment]
The following filters are now present:

`give_goal_amount_raised_output`

`give_goal_amount_target_output`

and `give_goal_output`

You can use these filters to modify the output and have more control. I also like allowing to show the goal as a percentage rather than amount. I will add that too.
