### ISSUE TITLE
fix: show donation start date instead of completed date on donor wall

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#3891]
# Bug Report

## User Story

As a site admin, I want donations added manually to show the date of donation, not the date they were manually added.

## Current Behavior
When I add donations manually, the donor wall displays the date I added them, not the date I selected as donation date in the settings. It shows up in the correct _order_ just not with the correct date:

<img width="760" alt="screen shot 2018-12-05 at 8 23 11 am" src="https://user-images.githubusercontent.com/9629102/49516222-1c9a6300-f867-11e8-9e13-0b128b7b107d.png">

## Expected Behavior
I expect the date to be correct on the front end.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Place donor wall on a page
2. manually add a donation, and be sure to select a donation date other than the current date
3. check the donor wall: it will show today's date, but display the donations in the correct order.

## Related
https://secure.helpscout.net/conversation/724157666/30557/
https://secure.helpscout.net/conversation/733126665/31206/
#3816

## Acceptance Criteria
- [ ] donations added manually display donation date, not date they were added. 

## Environment
<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: https://livegive.wpsteward.com
Site URL: https://livegive.wpsteward.com
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_8138bfdc07_
Table Prefix Length: 14
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: livegive.wpsteward.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.37 (Unix) OpenSSL/1.0.1f
PHP Version: 7.0.32
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
PHP Max Upload Size: 512 MB
cURL Version: ❌ 7.35.0, OpenSSL/1.0.1f - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.62 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. PayPal IPN won't work with your server. Contact your hosting provider. Error: cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received
Remote Get: ✔

### Give Configuration ###

Give Version: 2.3.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note❌Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email❌Subscriptions Email Access
Upgraded From: 2.2.1
Test Mode: Enabled
Currency Code: USD
Currency Position: After
Decimal Separator: .
Thousands Separator: ,
Success Page: https://livegive.wpsteward.com/donation-confirmation/
Failure Page: –
Donation History Page: https://livegive.wpsteward.com/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card, PayPal Payments Pro, Authorize.net, PayPal Standard
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Disabled
PayPal IPN Notifications: IPN received for #1084 ( 8H4629943X7440214 ) on 09/04/2018 at 15:46. Status VERIFIED
Donor Email Access: Disabled

### Active Give Add-ons ###

Give - Authorize.net Gateway: ✔ Licensed – by WordImpress – 1.4.3
Give - Email Reports: ✔ Licensed – by WordImpress – 1.1.2
Give - Form Field Manager: ❌ Unlicensed – by GiveWP – 1.4.1
Give - Google Analytics Donation Tracking: ❌ Unlicensed – by GiveWP – 1.2.2
Give - MailChimp: ❌ Unlicensed – by GiveWP – 1.4.2
Give - Manual Donations: ❌ Unlicensed – by GiveWP – 1.4.2
Give - PayPal Pro Gateway: ❌ Unlicensed – by GiveWP – 1.2.1
Give - PDF Receipts: ❌ Unlicensed – by GiveWP – 2.3.1
Give - Recurring Donations: ❌ Unlicensed – by GiveWP – 1.8.2
Give - Stripe Gateway: ❌ Unlicensed – by GiveWP – 2.1.2
Give - Tributes: ❌ Unlicensed – by GiveWP – 1.5.1
Give - Zapier: ✔ Licensed – by WordImpress – 1.2.1

### Other Active Plugins ###

Ben's Helper Functions: by BenUNC –
Better Click To Tweet: by Ben Meredith – 5.6.3
Email Cop: by Ashfame – 0.1.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.3.2
NEX-Forms - Ultimate: by Basix – 7.2.3
Query Monitor: by John Blackbourn & contributors – 3.1.1
User Switching: by John Blackbourn & contributors – 1.4.0
WP Crontrol: by John Blackbourn & contributors – 1.6.2

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.1
Give - Currency Switcher: by GiveWP – 1.3.0
Give - Database HealthCheck: by WordImpress – 0.0.2
Give - Fee Recovery: by GiveWP – 1.7.2
Give - Mollie Gateway: by WordImpress – 1.1.1
Gutenberg: by Gutenberg Team – 4.6.1
Hello Dolly: by Matt Mullenweg – 1.6
Page Builder by SiteOrigin: by SiteOrigin – 2.9.2
RegistrationMagic Premium: by Registrationmagic – 3.8.1.7
Restrict Content Pro: by Restrict Content Pro Team – 2.9.10
Series Engine: by Eric Murrell (Volacious) – 2.6.1
SiteOrigin Widgets Bundle: by SiteOrigin – 1.13.3
The GDPR Framework: by Data443 – 1.0.20
WonderPlugin Tabs: by Magic Hills Pty Ltd – 5.8

### Active MU Plugins ###

api-hacks.php: by  –

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by ravinderk** [comment]
@kevinwhoffman @Benunc Currently we are showing donation complete date instead of donation creation date: 

https://github.com/impress-org/give/blob/1508ffb1cbd7c59df32a08dfc99e2255de834dd6/templates/shortcode-donor-wall.php#L49
