### ISSUE TITLE
Per-form email settings

### ISSUE THREAD

**Issue by rosswintle** [WordImpress/Give#39]
Would love to see form-specific emails.  Use case: church is having a specific fundraising campaign for a building project, this is separate from their main fundraising activity. The user should get a custom message for that campaign.

Two options for implementation:
1) Create "Template sets" in the email settings, and then allow a template set to be selected in the form settings.  This keeps form settings to a minimum, but is potentially more complex.

2) Have custom email settings in the form settings itself.  You could probably hide these and then have a "Use custom email content" checkbox that reveals them.

**Comment by mathetos** [comment]
Makes a lot of sense. Might make more sense as an "Email Routing" add-on. @DevinWalker what's your take on this?

**Comment by DevinWalker** [comment]
Yeah definitely room here for an Add-on

**Comment by mathetos** [comment]
Thinking through this one a bit, and I'm a little hesitant to get into that. I see this more as MailChimp territory, especially with their new Web Hooks feature. Of course that assumes the charity is using MailChimp.

@rosswintle Can you elaborate a little, or @DevinWalker what do you think?

**Comment by rosswintle** [comment]
I'm not quite sure what you want me to elaborate on? I can't think of many sites I work on where I'd want the SAME email confirmation text sent to a donor on every donation form.

In many cases charities run campaigns for specific things, have separate funds for different activities, and so on.  These would require different email confirmation texts. A church, for example, might need to say:
 - "Thanks for donating to out building fund..."
 - "Thanks for supporting our youth worker..."
 - "Thanks for your donation to the work of the church..."

etc.

It's possible that Web Hooks in MailChimp would help, but I've not looked into it and that would require MailChimp integration, which may be overkill or not required.

A simple override field on each form may be enough to achieve this.

**Comment by tintomatoes** [comment]
I like this idea very much. And I agree that MailChimp integration is not necessary. The need is custom email templates per form, not so much mailing lists.

**Comment by DevinWalker** [comment]
This Add-on has been added to this: https://givewp.com/coming-soon/

It's not going to be a core functionality so I'm closing this issue.
