### ISSUE TITLE
Ability to set a minimum donation amount 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#390]
**Problem:** Can I set the minimum price for a donation? For example, I want the min donation at $5 and they also can donate custom amount but not below $5.

Reported via Help Scout request. I think it's an interesting request that we should consider adding to the form functionality. @mathetos what do you think?

**Comment by mathetos** [comment]
I agree that it would be useful. But there should be an alert of some sort to alert the donor that a minimum is in place. Perhaps just a small description under the amount field. 

We get this request often enough I think it would be valuable.

**Comment by pryley** [comment]
This is an important feature. Sometime a donation form will be used to test multiple credit card numbers, each time attempting to process a tiny donation (i.e. $3-$5). The problem with PayPal Pro (and maybe other gateways?) is when these transactions are appealed, flagged as fraudulent and then reversed, Paypal adds a $20 reversal processing fee. Having a minimum donation amount discourages this type of behaviour.

**Comment by mathetos** [comment]
That's a really good point @pryley particularly since we have heard reports from a few users saying they are getting those kinds of automated attacks on their forms. Combining this with a honeypot for security should be a priority for a near-future version I think.

**Comment by pryley** [comment]
A couple articles about this:

https://philanthropy.com/article/Fraud-Alert-Criminals-Test/233197
http://www.bankinfosecurity.com/stolen-cards-tested-on-charity-sites-a-7608/op-1

**Comment by DevinWalker** [comment]
This has been merged via https://github.com/WordImpress/Give/pull/498
