### ISSUE TITLE
Make Payment Gateways Drag/Drop Reorderable

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#391]
This would be a global feature. On the "Donations > Settings" page under the Payment Gateways tab, allow users to drag-drop the existing Payment Gateways to whatever order they want and have that reflected on their forms.

**Comment by ibndawood** [comment]
@mathetos - assign this to me. I'd like to work on this.

**Comment by DevinWalker** [comment]
Works well. I added a handle for dragging and some CSS touch ups
