### ISSUE TITLE
New Troubleshooting Give Doc Article

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#398]
We should have a documentation article that helps folks troubleshoot common issues. I just had a guy asking about JS issues on a page with the Give shortcode. Of course, he had the shortcode wrapped in another `<form>` tag within a `<p>` and another `<strong>` tag... the shortcode won't work when wrapped in a bunch of garbage HTML like that. But that's just one of the common issues people have who don't really know "advanced" stuff. So... let's create a doc dedicated to this that's ongoing with common issues.

**Comment by DevinWalker** [comment]
@mathetos do you think this is still necessary or should be closed?

**Comment by mathetos** [comment]
I think there's too many variables, and this is what Support is for.
