### ISSUE TITLE
CSS conflicts with Twenty Sixteen

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#401]
I noticed twenty sixteen has some interesting styles in place that Give should be sure to be compatible with prior to it's release:

![11-11-2015 12-42-07 pm](https://cloud.githubusercontent.com/assets/1571635/11102494/c184fe7a-8871-11e5-9212-ebfc04fefee1.png)

**Comment by mathetos** [comment]
I'll work on that for sure.

**Comment by DevinWalker** [comment]
The buttons are messed up too: 
![11-11-2015 1-47-35 pm](https://cloud.githubusercontent.com/assets/1571635/11103966/d4620b42-887a-11e5-9753-dec8d2ebf936.png)
