### ISSUE TITLE
Can't get earnings for specific form (unfinished code)

### ISSUE THREAD

**Issue by andrejcremoznik** [WordImpress/Give#408]
In case `$form_id` is passed to `get_earnings` returned value is always 0.

If you look here `$earnings` doesn't get increased.
https://github.com/WordImpress/Give/blob/master/includes/payments/class-payment-stats.php#L176

**Comment by DevinWalker** [comment]
Thanks for reporting this... I definitely see what you're saying and have a fix ready.
