### ISSUE TITLE
Consistency in Language

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#41]
I know we're still having discussions on what to call the "History" page (via #35 ), but currently the page that is auto generated upon install is also called "Purchase History". But that name is for the user, not the admin. So we have a couple things to clarify. This is my proposal:
1. Menu Item should be called Transactions, since it's an admin facing item
2. The user "history" page should be called "Donation History" (currently says Purchase History). I really think that is the most obvious term for what that is, and does not sound like a product or cart feature.
![purchase-history-page-name](https://cloud.githubusercontent.com/assets/930724/6702311/e5b3d948-cce6-11e4-9fc7-a0b838f65cae.png)

**Comment by mathetos** [comment]
Same issue with "Reports". My suggestions:

1. "Report Type" stays
2. "Earnings" changes to "Income"
3. "Customers" changes to "Donors"
4. "Payment Method" stays.

![report-types](https://cloud.githubusercontent.com/assets/930724/6702355/b5868aa8-cce7-11e4-893e-93e32d354372.png)

**Comment by DevinWalker** [comment]
Good news on your first comment, I already committed that when working on another install issue #40 

As for your second finding:

1. agree
2. agree
3. agree
4. agree
