### ISSUE TITLE
Remove custom user roles upon plugin deletion

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#410]
Per this ticket, we should be removing custom user roles when the plugin is deleted:

https://wordpress.org/support/topic/user-role-garbage?replies=1#post-7674383

**Comment by DevinWalker** [comment]
They are removed: https://github.com/WordImpress/Give/blob/master/uninstall.php#L79-L82

**Comment by mathetos** [comment]
Yep. Hasty ticket creation. Apologies.
