### ISSUE TITLE
Prevent 500 Server Error when changing status of Offline transactions

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#413]
Details here: https://wordpress.org/support/topic/cant-edit-donations?replies=4#post-7684067

We'll have to dig into whether this is necessary or not or exactly what the core problem is and whether that solution is best.

**Comment by DevinWalker** [comment]
He's referencing a core file there... not sure what that's all about. I'm going to close this until we see another report. Probably an isolated case.

**Comment by mathetos** [comment]
He's suggesting to require the core file (which I agree is weird) but in our plugin in the `class.metaboxes.php` file.

**Comment by DevinWalker** [comment]
That sounds like a CMB2 file
