### ISSUE TITLE
Goals

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#42]
ENVIRONMENT:

__________________________________________
FEATURE REQUESTS:
Is there a way to have a goal for the giving? In my case, we have many individuals who are trying to each raise 150 for their classroom. Parents/friends/strangers donate to each project individually (kind of like donorschoose.org) I didn't see one out of the box and it could be a neat functionality even on a big level. Church A wants to build a new THINGY and they have a goal of 10,000 -- people who donate can see they are half way there and get inspired to donate -- kind of thing?
__________________________________________
GENERAL FEEDBACK:
You guys rock. Thanks for the opportunity to beta test! Everything is looking great on my local install. Will do a push to live soon!

REF:345giveJason!fgh15

**Comment by DevinWalker** [comment]
@mathetos I want this to be a core feature, not an Add-on.

**Comment by mathetos** [comment]
And the world of Give will celebrate!

**Comment by DevinWalker** [comment]
@mathetos please test out the "Give" branch and report back if you find any bugs

**Comment by DevinWalker** [comment]
Goals has been merged into master - thanks @ibndawood
