### ISSUE TITLE
Switch a transaction to a different form

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#429]
Currently if a donation is made to the wrong form, the Admin has no recourse except changing the database values (not for the faint of heart). 

## Suggestion
Make the Form Title of the transaction be a dropdown of all forms to allow the Admin to change which form that donation applies to.
![give-change-transaction-to-different-form](https://cloud.githubusercontent.com/assets/930724/11729515/896f5f14-9f44-11e5-8764-f4e02cf37392.png)

Naturally, there will be some re-calculations that have to happen when that transaction is saved. A major additional feature would be giving the Admin the ability to change forms using the Bulk Options as well.

**Comment by DevinWalker** [comment]
Good request, I was just thinking about this the other day.

**Comment by DevinWalker** [comment]
- [ ] Use `give_get_form_dropdown` to output a searchable dropdown https://github.com/WordImpress/Give/blob/master/includes/class-give-html-elements.php#L36
- [ ] Recalculate the statistics for both the form the transaction was attached to prior and after the change was made 
- [ ] Unit test ensuring the switch and recalculation is working
- [ ] QA pass

**Comment by mathetos** [comment]
@DevinWalker what's your thoughts on allowing Bulk change of forms for this?

**Comment by DevinWalker** [comment]
Let's complete changing it on the per-transaction level then look into changing it via the bulk options.

**Comment by ravinderk** [comment]
@DevinWalker @mathetos 

On payment detail page, User is allow to add any amount on payment detail page that is fine for single donation form but for multi donation form user can add a amount which may not be present in donation level or if multi donation form set to custom and if this form has custom minimum amount then this is also possible that new amount may not follow minimum custom amount user case.

<img width="1061" alt="screen shot 2016-07-14 at 6 08 20 pm" src="https://cloud.githubusercontent.com/assets/1784821/16839707/28675f6e-49ee-11e6-9152-d97f942bbbee.png">





**Possible solution:** To fix this issue, we can show user a notification  ( when he is editing payment amount) that he can only add these amounts ( also with custom amount minimum limit if any ) or discard any amount related changes if user does not follow user cases with a WordPress notification.

**Comment by mathetos** [comment]
@ravinderk Generally, we think the site Admins should have the flexibility to change those amounts however they need to. No need to limit their ability to manage their donors based on the form specifications.

**Comment by ravinderk** [comment]
@mathetos Alright
