### ISSUE TITLE
give_receipt not passing Form title properly

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#443]
A user contacted us saying the donation receipt has an issue. I tested locally and duplicated the issue. Basically, upon donation the confirmation page with the [give_receipt] shortcode does not display the Form title or donation key, and the donation total is always $0.00. The payment does go through correctly and appear in the Transactions screen correctly.

Nothing appears in the logs regarding this at all.

With WP_DEBUG set to true, the following notice is passed:
`Undefined index: form_title in ...\wp-content\plugins\give\templates\shortcode-receipt.php on line 19`

Here's a screenshot of the results:
![give_receipt-problem](https://cloud.githubusercontent.com/assets/930724/11942090/8196cc70-a834-11e5-95d6-2906b5fcdf21.png)

**Comment by DevinWalker** [comment]
Did you just run a test transaction through?

**Comment by DevinWalker** [comment]
Ah, I see... `[give_receipt price="true" date="true" payment_key="true" payment_method="true" payment_id="true"]` has to be the shortcode

**Comment by DevinWalker** [comment]
Ok I believe I have it fixed

**Comment by DevinWalker** [comment]
Confirmed fixed
