### ISSUE TITLE
Guest Donors should be able to access their donation history if they later create an account

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#446]
Pippin and the EDD team handled this here:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/issues/3877

This same function for Give could be read this way:
> If a donor makes a donation as a guest, their email address is still associated with that donation.  If a donor then creates an account with the same email address, they'll be asked to verify their account via email, so that their Donation History may be associated with their new account.

That would be a very nice feature to have.

**Comment by DevinWalker** [comment]
:+1:

**Comment by DevinWalker** [comment]
@mathetos moving to next release 1.3.6

**Comment by DevinWalker** [comment]
Related to #496
