### ISSUE TITLE
Improve description of one donation price vs multiple levels

### ISSUE THREAD

**Issue by getresults** [WordImpress/Give#45]
For someone using give the very first time the "multiple levels" is a little confusing.  Even though it becomes clear the moment they select "multiple levels" it would be worth improving the description to remove any initial confusion.  Perhaps something similar to: 

Do you want this form to have one set donation price or multiple levels (for example, $10 silver, $20 gold, $50 platinum)?

**Comment by DevinWalker** [comment]
Thanks - I've improved the description for this field
