### ISSUE TITLE
"Sorry — your last action could not be completed" when directed to PayPal on Safari/Mac

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#453]
Reported by a user, here's the summary:

> On a side note, we’ve noticed a fairly high abandonment rate when it comes to transactions from our Donation form (http://gbcancersupportcentre.ca/donate-today) .  We’ve inquired to a few of these potential donors as to what the issue was, and they say that they received an error.  We happened to be able to reproduce this issue using Safari on a Mac.  Upon clicking the Donate Now button, PayPal loads up and gives an error titled:  Sorry — your last action could not be completed
 
> When I look up that error on Google, it seems to be related to Cookies and generally people clear their cookies or try another browser and it then it works.  We were also able to try another browser on the same computer (Chrome) and it worked fine.

Needs testing and confirmation.

**Comment by DevinWalker** [comment]
Interesting...

**Comment by DevinWalker** [comment]
Tested on my test site on Mac + Safari and PayPal Sandbox and it worked fine:

![screen shot 2016-04-07 at 2 56 14 pm](https://cloud.githubusercontent.com/assets/1571635/14368166/0625f3c6-fcd1-11e5-8eb2-dfc250d95464.png)

I also tested on the http://gbcancersupportcentre.ca/donate-today site and seems to be working (I tried several times):

![screen shot 2016-04-07 at 3 03 43 pm](https://cloud.githubusercontent.com/assets/1571635/14368360/1c45aa56-fcd2-11e5-86cd-165bb01ae839.png)

This appears to have to do with cookies... there are a ton of posts on this... I pretty sure this doesn't have anything to do with Give.
