### ISSUE TITLE
Documentation to create add-on

### ISSUE THREAD

**Issue by peterpham** [WordImpress/Give#455]
I want to use Give on my site but using my local bank-payment gateway. 
Just wonder if there is any documentation/guideline on how to create an add-on for additional payment gateway?

**Comment by DevinWalker** [comment]
Hey @peterpham sorry not right now but I can provide you access to a few gateways for code reference if you'd like...

**Comment by peterpham** [comment]
@DevinWalker Thanks, can you show me some sample code for reference?
The payment gateway that I intended to use is pretty much basic (similar to paypal). I will redirect my donor to bank's checkout page where he/she will enter credit card info. 
i think I can work out the integration, but just not sure hoe to make this payment gateway appeared as additional option along with PayPal Standard, Test Payment, Offline Payment.

Thank you in advance.

**Comment by DevinWalker** [comment]
If it's supposed to work like PayPal then WePay is a good example of another offsite gateway. I'll provide you access to that. Also, check out: https://github.com/WordImpress/Give/blob/master/includes/gateways/paypal-standard.php

**Comment by peterpham** [comment]
Very much appreciated.
