### ISSUE TITLE
Improve "Display Style" description

### ISSUE THREAD

**Issue by getresults** [WordImpress/Give#46]
As developers we know what "radios" and "dropdowns" are.  Many end users will not. 

Putting a small image of what each option will look like underneath would be very helpful for clarity

**Comment by DevinWalker** [comment]
I'm going to push back on this one and say that most users DO know what these fields mean (i hope...). I mean, they are the admin of a WordPress site. They use each field extensively to just login to WordPress and click around. I think users who are confused can experiment with selecting different field types, viewing them on the frontend, and then adjusting them to suit their needs.
