### ISSUE TITLE
Currency Symbols don't output reliably

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#461]
I've seen this happen a few times, here's the latest example:
https://wordpress.org/support/topic/strange-characters-instead-of-e-sign?replies=2#post-7885517

We're using HTML entities to output the currency symbol, but according to this StackExchange ticket that's not the most reliable way of doing it:
http://stackoverflow.com/questions/1385835/euro-sign-in-html

Also this Google HTML Style Guide says to never use Entity references but output the symbol directly from the font:
https://google.github.io/styleguide/htmlcssguide.xml#Entity_References

## Suggestions

* Reliably reproduce this problem either with the theme or in Dutch
* Try to swap out the entity with € instead
* Set the font-family of the currency symbol to always be something very universal, like Arial or Verdana

**Comment by DevinWalker** [comment]
Nice issue! I like :+1:

**Comment by DevinWalker** [comment]
I like the idea of setting the font family but that could bump heads with theme compatibility. For instance, if we set it as Arial, and a theme uses another font by default then it may clash with the design.

**Comment by mathetos** [comment]
In this case, I'd be willing to add inline styles just to the currency symbol. Maybe not ideal, but reliable.

**Comment by DevinWalker** [comment]
This is a really good site for currencies & their font equivalents: http://www.xe.com/symbols.php
