### ISSUE TITLE
Payment Gateway - Ability to rename gateway title

### ISSUE THREAD

**Issue by RaDragon** [WordImpress/Give#464]
Hello! I searched this Issues db and didn't find this; apologies if it was already considered in the past. This is not an issue, but minor feature request -- it would be cool if we can assign an alias/different name to the label of Payment Gateway choices on the front end.

So, on the front end display for Payment Method, instead of showing "Paypal" and "Offline Donation" labels, it could read "Credit Card" and "In Person Donation" instead (or any other wording). It would still be the actual Paypal gateway, but a little bit more descriptive.

Thanks for your consideration! This plugin is truly sweet. ^_^

**Comment by mathetos** [comment]
This can be done via filters. We have a snippet here that you can use for that:

https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/customize-payment-gateway-labels.php

Thanks!
