### ISSUE TITLE
The plugin overwrites other styles and breaks them

### ISSUE THREAD

**Issue by moldcraft** [WordImpress/Give#466]
https://github.com/ThemeFuse/Unyson/issues/1210

Can we delete [this file](https://github.com/WordImpress/Give/blob/3eafebbfc912cd861e4a0b6645a6039bfe4ef643/assets/css/jquery-ui-fresh.css#L68) or make a cleanup and leave only the needed styles that will not affect others?

**Comment by moldcraft** [comment]
We made a temporary fix in our theme

```php
/**
 * fixes https://github.com/WordImpress/Give/issues/466
 */
function _filter_theme_fix_give_plugin_assets() {
	if (function_exists('give_is_admin_page') && give_is_admin_page()) {
		wp_dequeue_style('jquery-ui-css');
	}
}
add_action('admin_enqueue_scripts', '_filter_theme_fix_give_plugin_assets', 101);
```

**Comment by moldcraft** [comment]
For all our qtips we added our unique class and use css selectors link `.qtip.qtip-fw { ... }` but [you change all qtips styles](https://github.com/WordImpress/Give/blob/3eafebbfc912cd861e4a0b6645a6039bfe4ef643/assets/css/give-admin.css#L58) and break our styles

**Comment by moldcraft** [comment]
We can't do `wp_dequeue_style('give-admin');` because it contains not only qtip styles but a lot of other required styles.

**Comment by moldcraft** [comment]
I think the below code fixes the problem with `.qtip`

```php

function _action_theme_fix_give_plugin_hooks() {
	if (function_exists('give_is_admin_page')) {
		remove_action( 'admin_enqueue_scripts', 'give_load_admin_scripts', 100 );

		// enqueue before all, so other assets will be enqueued later and will overwrite bad Give styles
		add_action( 'admin_enqueue_scripts', 'give_load_admin_scripts', 9 );
	}
}
add_action('init', '_action_theme_fix_give_plugin_hooks');
```

**Comment by DevinWalker** [comment]
Thanks for reporting this... I'm going to take a look.

**Comment by DevinWalker** [comment]
I just cleaned up a bunch of the unused styles. Now it's only using the necessary datepicker styles.
