### ISSUE TITLE
Problem give_format_amount_decimals return always 2 decimals

### ISSUE THREAD

**Issue by NicolasKulka** [WordImpress/Give#467]
Hello,

File assets/js/give-checkout-global.js l.177 : give_global_vars.number_decimals doesn't exist
but give_scripts.number_decimals exist.

Or

File /include/scripts.php : $localize_give_checkout
Add l.60 in this array.

Problem with hook filter "give_format_amount_decimals" which return always 2 decimals.

**Comment by DevinWalker** [comment]
Thanks for reporting! I'll take a look.

**Comment by DevinWalker** [comment]
@NicolasKulka I'm having a hard time understanding the issue... would you mind clarifying?

**Comment by NicolasKulka** [comment]
I used the filter to be no decimal. Except that the filter always returns 2 decimal minimum
