### ISSUE TITLE
Revisit Floating Labels for Password & Additional Input Types

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#468]
Particularly with Recurring Donations out now, we need to revisit floating lables and make sure they are consistently added. Here's one problem at the moment:

Recurring requires the login/register fields. But floating labels is applied to the Username, but not the password fields. 

![floating-labels-on-login-fields](https://cloud.githubusercontent.com/assets/930724/12600985/957014ec-c452-11e5-89b5-d44774b2e596.png)

**Comment by DevinWalker** [comment]
@pryley have you gotten floating labels working with password input types?

**Comment by pryley** [comment]
They don't work? I'll check it out in a couple days. At Sundance.


Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1]
On Tue, Jan 26, 2016 at 6:33 p.m., WordImpress/Give
<reply@reply.github.com>
wrote:
@pryley [https://github.com/pryley] have you gotten floating labels working with password input types?

—
Reply to this email directly or view it on GitHub
[https://github.com/WordImpress/Give/issues/468#issuecomment-175332504] .[https://github.com/notifications/beacon/AAIPG2Sedh_hCtND587BUPH0C1QEqtPaks5peBXwgaJpZM4HNCtI.gif]

**Comment by pryley** [comment]
Floating labels supports the input password type as it's included in the default regex option. You can also support additional input types by passing in a custom regex string as explained in the plugin readme.

Example:
```
jQuery( 'form' ).floatlabels({
    regex      : /text|password|email|number|search|url|tel/,
    exclude    : [],
    priority   : '',
    customEvent: function(){},
    customLabel: function(){},
});
```

I suspect the reason it's not working is because you need to create/listen for an event that re-initializes floating labels. An example from give.js:
```
doc.on( 'give_checkout_billing_address_updated', function( ev, response, form_id )
{
   // here we run floating labels.
});
```

**Comment by DevinWalker** [comment]
Thanks, @pryley I just got the time to look into it and it appears that if the label has an inaccurate `for` attribute then it doesn't get hidden. It still appropriately sets the floating label but the label is also shown. I've fixed this for the password fields.
