### ISSUE TITLE
Per form confirmation messages

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#469]
I think adding per form confirmation messages would be a good core feature candidate. It could be an almost duplicate of the form content fields. But instead of hooking into the before/after content hooks, we can hook into the `give_payment_receipt_before` and 'give_payment_receipt_after' hooks in the `[give_receipt]` shortcode.

![per-form-custom-receipt-message](https://cloud.githubusercontent.com/assets/930724/12681245/745dc6e8-c662-11e5-81b6-f39b134c5e1f.jpg)

**Comment by mathetos** [comment]
@DevinWalker would love your thoughts on this idea.

**Comment by mathetos** [comment]
Ping @DevinWalker again. What say you to this idea?

**Comment by DevinWalker** [comment]
I've created a new repo for this future Add-on: https://github.com/WordImpress/Give-Per-Form-Confirmation-Messages
