### ISSUE TITLE
Give Core shows Constant Contact forms without add on enabled

### ISSUE THREAD

**Issue by mlbanddrb** [WordImpress/Give#473]
Had a chat with a potential customer that uses Constant Contact already. Clark #4379. He was testing the free GiveWP plugin with no add-ons.

Emailed a copy of the transcript to Matt. #

Customer could see and use the Custom Contact form within the add form of Give. He gets the drag and drop form builder but if he edits the content it doesn't work. It also appears as a separate form to submit alongside the donation submit button.

She sent a screencast of what he could see. http://screencast.com/t/BxosTz6M

**Comment by DevinWalker** [comment]
@mlbanddrb which plugin is this?

**Comment by mlbanddrb** [comment]
This customer has the traditional Constant Contact and uses the Give Core plugin. He is not using the constant contact add-on. He can see and use the constant contact form within the add form of Give core.

**Comment by DevinWalker** [comment]
@mathetos can you help shed light on this? I'm confused as to what the screenshot is showing and need to know how to reproduce.
