### ISSUE TITLE
Donation total does not show the currency sign when changing custom amount

### ISSUE THREAD

**Issue by pryley** [WordImpress/Give#485]
![image](https://cloud.githubusercontent.com/assets/134939/13233992/503336f6-d96b-11e5-840e-3af3575aa6f4.png)

**Comment by DevinWalker** [comment]
Thanks @pryley 

Good to see you again. I'll check this out ASAP

**Comment by DevinWalker** [comment]
Issue found:

![2-25-2016 3-37-04 pm](https://cloud.githubusercontent.com/assets/1571635/13338351/af492472-dbd5-11e5-9588-819b96338320.png)

**Comment by pryley** [comment]
Strange, it doesn't happen here and I'm using my fork with the 3 pull requests
on a live site. Maybe it has to do with the recurring addon, I was having issues
with it so I disabled the addon so did not test it with that.
All the pull request does is set the missing currency symbol in the
give_format_currency() function.
I will look at it again later today.

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1]
On Thu, Feb 25, 2016 at 3:37 p.m., Devin Walker <notifications@github.com>
wrote:
Issue found:

2-25-2016 3-37-04 pm
[https://cloud.githubusercontent.com/assets/1571635/13338351/af492472-dbd5-11e5-9588-819b96338320.png]
[https://cloud.githubusercontent.com/assets/1571635/13338351/af492472-dbd5-11e5-9588-819b96338320.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/WordImpress/Give/issues/485#issuecomment-189035830] .[https://github.com/notifications/beacon/AAIPG5dqQjQd16QedwwtSD7mUuRtfskCks5pn4e9gaJpZM4HgBMB.gif]

**Comment by DevinWalker** [comment]
Don't worry I got it working

**Comment by DevinWalker** [comment]
See 5ae9a3987bf7592a4ff8fccddd503b2b33109ce8

**Comment by pryley** [comment]
👍🏼

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1]
On Thu, Feb 25, 2016 at 4:05 p.m., Devin Walker <notifications@github.com>
wrote:
Don't worry I got it working

—
Reply to this email directly or view it on GitHub
[https://github.com/WordImpress/Give/issues/485#issuecomment-189045368] .[https://github.com/notifications/beacon/AAIPGyS-ijd_zkhB-Ec5RxHlqfsgRE7Cks5pn44wgaJpZM4HgBMB.gif]
