### ISSUE TITLE
One function for give_get_payment to hold all meta info?

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#488]
Currently, in the [give_receipt] shortcode there's the following variables:

```
$meta     = give_get_payment_meta( $payment->ID );
$donation = $meta['form_title'];
$user     = give_get_payment_meta_user_info( $payment->ID );
$email    = give_get_payment_user_email( $payment->ID );
$status   = give_get_payment_status( $payment, true );
```

Wouldn't it be a bit more dev-friendly to have one function called `give_get_payment` with an array of all of those variables? That would potentially be better for the API endpoints as well, right?

Or I might be totally off-point. Mostly a question.

**Comment by DevinWalker** [comment]
See #504 - the class will create an object containing methods to perform different payment functions and an object containing payment information
