### ISSUE TITLE
Card type image not showing when floating-labels is enabled

### ISSUE THREAD

**Issue by pryley** [WordImpress/Give#490]
![image](https://cloud.githubusercontent.com/assets/134939/13263041/c724e244-da1c-11e5-93bc-16e9ee067890.png)

**Comment by DevinWalker** [comment]
Is this an issue with CSS mainly?

**Comment by pryley** [comment]
No, I think it was introduced in the recent ally changes to remove duplicate ID's.

Floating labels changed the dom, so it needs a custom event to re-add the card-type span which is used to show the card image. The event used to check for the card number input ID, but since the ID changed it was no longer finding the element to append the span after.

**Comment by DevinWalker** [comment]
This has been fixed with https://github.com/WordImpress/Give/pull/499
