### ISSUE TITLE
Update icon in dashboard widget

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#492]
This should be the Give logo:

![2-24-2016 10-41-32 pm](https://cloud.githubusercontent.com/assets/1571635/13311995/c7d09ad6-db47-11e5-92d8-c127e4a9afd7.png)

**Comment by mathetos** [comment]
The icon is there now, but it no longer links to the Give Forms edit page like the Post/Pages does in that same widget.

**Comment by DevinWalker** [comment]
Fixed!
