### ISSUE TITLE
Refresh Sessions or Login Functionality when expired sessions for receipt links & r

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#496]
**Scenario:** A donor receives the confirmation email with the receipt link and clicks it after the expired time.

**Problem:** The donor sees the error message: 

```
Sorry, it appears the viewing window for this donation receipt has expired or you do not have the permission to view this donation receipt.
```

This isn't very user friendly at all and is confusing and frustrating for donors. We need to give the donor the option to either log in or receive an updated link via the email used when they gave. Once they login, they should be properly redirected back to the receipt page.

**Comment by DevinWalker** [comment]
See: https://github.com/FacetWP/edd-no-logins for item 1 on the task list

**Comment by DevinWalker** [comment]
This feature is ready for testing.

How to tests:

1. Enable the featured under Settings > Advanced
2. Access the donation history page or receipt in a browser you are not logged in
3. You should see the email form "Access Your Account" above.. enter your email
4. You should receive an email with the access link, click it in the same browser you're not logged in
5. You should see donation history and individual donation details

**Comment by DevinWalker** [comment]
@mathetos see above

**Comment by mathetos** [comment]
Just tested, one issue: when clicking on the donation history page where the form is, it immediately refreshes to a 404 and adds "undefined" into the URL. So far that is preventing me from testing further.

**Comment by DevinWalker** [comment]
Another issue:

- [ ] Links should always redirect to the Donation History URL to ensure there's always a `payment_key` when viewing the specific donation's details
