### ISSUE TITLE
Add New Form Category link doesn't work

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#5]
Add New Form Category link doesn't work

**Comment by DevinWalker** [comment]
Again, most likely due to #7

**Comment by DevinWalker** [comment]
Closing this out - likely fixed

**Comment by mathetos** [comment]
No, just tested again with the latest commit. Now the link to add a category doesn't even appear. See here:
![no-add-category-link](https://cloud.githubusercontent.com/assets/930724/6610251/e181aade-c819-11e4-8316-731a3890a064.png)

It throws the following error in admin-forms.min.js:
`Uncaught ReferenceError: handle_status_switch is not defined`

No other plugins active at all. WP 4.1.1, running TwentyFifteen.

**Comment by DevinWalker** [comment]
Yup got it!
