### ISSUE TITLE
Improve "Register / Login Form" description

### ISSUE THREAD

**Issue by getresults** [WordImpress/Give#50]
My first thought was along the lines of "does this setting force users to register and / or login at checkout?".   

I'm guessing it simply displays / hides the registration / login forms on the checkout page but it may be worth expanding the description to be more specific about this.  i.e.: 

"Note: this will not require users to register or log in but simply determines whether the login and/or registration form are displayed on the checkout page. "

**Comment by DevinWalker** [comment]
The field description now reads "Display the registration and login forms in the checkout section for non-logged-in users. Note: this option will not require users to register or log in prior to completing a donation. It simply determines whether the login and/or registration form are displayed on the checkout page."
