### ISSUE TITLE
Add a cancel/back button to the optional login form

### ISSUE THREAD

**Issue by pryley** [WordImpress/Give#500]
**Problem:** When a potential donor clicks the login link without having an account, they have to refresh the page in order to enter their personal info.

**Solution:** Add a cancel/back button to reload the personal info fields, hide the login fields, and re-show the login link.

![image](https://cloud.githubusercontent.com/assets/134939/13542198/f6d17ab0-e215-11e5-884a-4d4c25430a2a.png)

**Comment by DevinWalker** [comment]
This is fixed, along with a bunch of other fixes with the login / register fields - needs a bit more testing. @pryley @mathetos I'd love if you could test it out with various configurations like modal / slide down / etc.

**Comment by pryley** [comment]
Tested it just now. 

Re-opening this because it doesn't re-trigger float-labels if the option is enabled for the form.

![image](https://cloud.githubusercontent.com/assets/134939/14405323/2934716e-fe5a-11e5-98be-c77b0759fd8b.png)

**Comment by DevinWalker** [comment]
Just making some minor changes / updates to the JS - there's a console log in there and also the tooltips aren't refreshing
