### ISSUE TITLE
New Payments Class

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#504]
The way of handling payments is out of date. I propose a new class to handle payments like they are doing in EDD. In response to #488

**Comment by cklosowski** [comment]
@DevinWalker There have been quite a few fixes and enhancements to `EDD_Payment` over the last couple months that extension developers have found. I think using it as a basis would work just fine in the Give-ecosystem.

**Comment by DevinWalker** [comment]
@cklosowski totally! I'm chomping at the bit on this one.

**Comment by DevinWalker** [comment]
Note to self: Need to figure out the discrepancies between `price_id` and `level_id` as failing in `test_remove_with_multi_price_points_by_price_id`

**Comment by DevinWalker** [comment]
- [ ] ensure compatibility with old `payment_meta` array

**Comment by DevinWalker** [comment]
This is closed with the merge 93536f8a6050263641a38ac80b4fc0aebff5395e into release/1.5 branch
