### ISSUE TITLE
New Form:  Is Excerpt used? 

### ISSUE THREAD

**Issue by getresults** [WordImpress/Give#51]
At the bottom of the New Form page it has an excerpt field.  However, it doesn't explain if or where the excerpt will be used.

**Comment by DevinWalker** [comment]
The excerpt is mainly used for use with custom queries or theme usages. For instance, if you wanted to query all forms, similar to a "Shop" page in WooCommerce, the excerpt could be very useful. Know what I mean? Regardless, perhaps we should add some text below with explanation. @mathetos whatcha think?

**Comment by getresults** [comment]
Yeah, a description along those lines would be great:

"Most Give users won't use the Excerpt field. If you don't know what it is you can safely ignore it.  Developers can use it with custom queries or theme usages. " etc

The main thing is not to leave a confusing, unexplained field for non-technical users.

**Comment by DevinWalker** [comment]
Hey @getresults I'm pushing some updates to address the excerpt field. There's now an option to disable the admin field within Give > Settings > Display Options - I've also added this Core doc: https://givewp.com/documentation/core/give-forms/form-excerpts/ which explains the use cases for the excerpt and instructions to disable.
