### ISSUE TITLE
Alternatives for allow_url_fopen or fail gracefully

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#511]
Related to #506 two users have reported being unable to generate a PDF export from our Export tools because they don't have allow_url_fopen enabled in their stack. One is a Media Temple customer so I don't think this is unusual. 

We use allow_url_fopen to add our logo into the PDF report on the fly. I've emailed Eugene at MT for insight into this and possible alternatives. But wonder if @DevinWalker has other thoughts for how we can insert our logo into the Report without using allow_url_fopen

If we don't have an alternative, then it would be better to allow that generation to fail more gracefully, checking for whether it's enabled or not and pre-emptively disabling the generate button with a notice for why they can't generate PDF reports.

**Comment by mathetos** [comment]
I reached out to Media Temple (since one support ticket is hosted there) about this issue. They have this documentation on why they don't support `allow_url_fopen` here:
https://mediatemple.net/community/products/grid/204643900/why-is-allow_url_fopen-disabled-on-the-grid

They also suggested cURL as an alternative with this just as an idea (without even looking at our code):

```
$ch = curl_init('http://example.com/image.php');
$fp = fopen('/my/folder/flower.gif', 'wb');
curl_setopt($ch, CURLOPT_FILE, $fp);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_exec($ch);
curl_close($ch);
fclose($fp);
```

I think it's reasonable for us to consider this seriously and abandon allow_url_fopen for our PDF export feature.

**Comment by DevinWalker** [comment]
Nice, thanks for the research. I'll add this to the next minor release.
