### ISSUE TITLE
You have to ( save + reload ) after enabling a gateway in order to select it as the default

### ISSUE THREAD

**Issue by pryley** [WordImpress/Give#512]
**Problem:** When enabling a gateway, you have to reload the page after saving the settings in order to select it in the `Default Gateway` select dropdown. Same goes for when you disable a gateway, once you save the settings the gateway is still in the `Default Gateway` select dropdown until you refresh the page.

![image](https://cloud.githubusercontent.com/assets/134939/13643317/1186be3e-e5d5-11e5-876c-9868ddb4efef.png)

**Comment by mathetos** [comment]
Yep, this has bothered me for a while. I think though that this might get resolved via #494

**Comment by DevinWalker** [comment]
This is larger issue with how CMB2 works natively
