### ISSUE TITLE
Add deployment script to WordPress.org from Github

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#513]
I'm tired of manually deploying to WordPress.org - there's a better way: http://mikejolley.com/2015/11/26/github-to-wordpress-org-deploy-script/

**Comment by mathetos** [comment]
Now I remember. Yep, that's the one.

There's also this one:
http://blog.wppusher.com/video-releasing-a-product-for-wordpress-org-with-git/

**Comment by DevinWalker** [comment]
Pippin just recommend this one from Mike Jolly - looks pretty nice too except it doesn't verify versions for you... https://github.com/mikejolley/github-to-wordpress-deploy-script

**Comment by DevinWalker** [comment]
I just Mike's script and it worked nicely

**Comment by afragen** [comment]
FWIW I use https://github.com/GaryJones/wordpress-plugin-git-flow-svn-deploy the develop branch.

**Comment by afragen** [comment]
Only works for local git repo though.
