### ISSUE TITLE
Transactions with a "cancelled" status are not shown in the wp-admin Transactions table

### ISSUE THREAD

**Issue by pryley** [WordImpress/Give#514]
The `cancelled` status was introduced I think in preparation for the recurring donations addon.

**What it looks like:**

![image](https://cloud.githubusercontent.com/assets/134939/13657688/f721cc2c-e625-11e5-8d8f-ead615ed5931.png)

**What it _should_ look like:**

![image](https://cloud.githubusercontent.com/assets/134939/13657706/22190e86-e626-11e5-8b8d-e218081da48b.png)

**Comment by DevinWalker** [comment]
We are currently registering the `cancelled` status in Recurring - https://github.com/WordImpress/Give-Recurring-Donations/blob/master/give-recurring.php#L360 

How is it that you're seeing cancelled transactions without Recurring enabled? Or do you have Recurring transactions cancelled and they aren't appropriately displaying?

**Comment by pryley** [comment]
The cancelled status can be selected on the `View Donation Details` page, that's why I assumed it added for the recurring donations addon.

`give_get_payment_statuses() -> Give/includes/payments/functions.php:592`

![image](https://cloud.githubusercontent.com/assets/134939/13660489/4d73bae0-e63f-11e5-96aa-fd5955fc28a8.png)

**Comment by DevinWalker** [comment]
You're right. I just confirmed on my end. Let's merge your PR and then remove it from Recurring. I'll test for conflicts.
