### ISSUE TITLE
Supporting Asian languages

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#518]
We keep having issues with Asian languages in different areas of the plugin. It's hard to reproduce or understand what the trouble really is. Here's a good example though:

**Thai language:**
![screenshot2559-03-11at09 41 25](https://cloud.githubusercontent.com/assets/930724/13712015/409d5dac-e776-11e5-8937-b7b00f542dc4.png)

**Relevant ticket:**
https://wordpress.org/support/topic/unread-font?replies=3

**Comment by mathetos** [comment]
Some notes on this from @pippinsplugins 

> Looks like utf8 issues. it’s either caused by the way you’re saving input data or the way you’re outputting the data
> I would look in the DB first and see if the data is stored fine there. If it is, that tells you the problem s due to how its output

**Comment by tonsung** [comment]
Hello it's my issue.
which table name i will show .


```
/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');
```

**Comment by mathetos** [comment]
Hi @tonsung Are you saying that defining your database as utf8 solved the issue for you?

**Comment by tonsung** [comment]
Hi Mathetos
sorry i mean that  @pippinsplugins wrote : I would look in the DB first and see if the data is stored fine there. If it is, that tells you the problem s due to how its output

my database already utf8.


well i couldn't see give database table. i will check.

**Comment by mathetos** [comment]
Perfect. Thanks. Keep us posted.

**Comment by DevinWalker** [comment]
Here's some helpful info in the Codex about converting database charsets https://codex.wordpress.org/Converting_Database_Character_Sets

**Comment by DevinWalker** [comment]
I've researched this issue and I don't think it's due to our plugin. I think it's due to likely db charset issues or the font being used.

**Comment by DevinWalker** [comment]
Please reopen if we can get steps to reproduce.
