### ISSUE TITLE
New Form:  Are form categories / tags any use?

### ISSUE THREAD

**Issue by getresults** [WordImpress/Give#52]
Users entering a new form have the option to select & enter categories or tags.   It's not clear if this is useful in any way. 

If so, perhaps add a description area at the bottom of the form to remind users to do so and why.  If categories / tags are not useful for forms, is it possible to hid the categories / tags options to prevent confusion?

**Comment by stegosource** [comment]
Agreed. This could be useful on the admin side of things, but does not seem to serve a function on the front end side. Would be nice to see it on the front end. Maybe just stick to categories and remove tags.

**Comment by DevinWalker** [comment]
The plugin's taxonomies are for users and theme authors to for both front and backend functionalities. Just like any CPT, you should be able to categorize or tag your posts, or in this case forms. For instance, if you have "Holiday" specific donations, or want to tag posts for "conservation" etc. How about if we include an option under Settings > Display Options to toggle them on or off?

**Comment by getresults** [comment]
@DevinWalker - the display option sounds great.  That way it's hidden from the typical end user who be unlikely to use categories / tags on forms but available for advanced users & theme authors etc.

**Comment by DevinWalker** [comment]
By default, I think the taxonomies should be enabled. Thoughts?

**Comment by bryanmonzon** [comment]
I don't know. The use cases for categorizing and tagging forms seems limited. If the organization created campaigns, however, categorization makes perfect sense. For forms, I'm not sure on the front end there's much use for it.  The form is the mechanism to collect money. It's the primary interaction point between the user giving their cash and the org receiving it. Once the donor is compelled to give, they should only have to think about "how much?" and "where do I enter my card?". Beyond that, you're decreasing the possibility of a conversion. Also, even though it's set up as a CPT, it doesn't mean it has to operate like one. Just my initial thoughts.

**Comment by DevinWalker** [comment]
Hey Guys - I'm committing code that makes the plugins taxonomies option. By default, they are not enabled. If the user wishes to use them they can easily enable either taxonomy now under Settings > Display Options
