### ISSUE TITLE
New Shortcode attribute: button_only=true

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#520]
Users often request the ability to have just a "Donate" button that opens the whole form in a modal rather than choosing the amount first. This could be achieved by adding an attribute to the shortcode called `button_only`
## CONSIDERATIONS

This would conflict with the existing attribute display_mode. To compensate for that we should do the following:
- button_only should have a default of false
- If button_only is true it overrides whatever might be in display_mode
- Naturally, the shortcode generator will need to output these correctly, but the generator form itself should disable the display mode option if button_only is enabled.

**Comment by mathetos** [comment]
@DevinWalker We are still getting this request regularly. Can we add it to an upcoming milestone?

Most recent request: https://wordpress.org/support/topic/only-donate-button-to-open-form?replies=1#post-8806415

**Comment by DevinWalker** [comment]
I added it to 1.8

**Comment by DevinWalker** [comment]
@ravinderk I just noticed we're missing the option from the single donation form admin page:

![button-option](https://cloud.githubusercontent.com/assets/1571635/20575126/d3a7aad8-b16c-11e6-86a9-891f590fbea4.png)

Can you work that in there too?

**Comment by DevinWalker** [comment]
@ravinderk I'm seeing some incompatibility with recurring donations:

![2016-12-07_15-52-29](https://cloud.githubusercontent.com/assets/1571635/20991785/2edf2c2c-bc95-11e6-91f3-e0ce0bc227e7.png)

## Steps to Reproduce
1. Create a Admin Choice recurring donation form
2. Set the form display option as "Button"
3. View the form on the page
