### ISSUE TITLE
"Custom Amount Text" should not show if the field is left blank

### ISSUE THREAD

**Issue by pryley** [WordImpress/Give#522]
**Expected behaviour:**
Leaving the _Custom Amount Text_ field blank is supposed to prevent it from being displayed.

![image](https://cloud.githubusercontent.com/assets/134939/13719618/765eae8c-e7ad-11e5-8ab5-4b51e454c593.png)

**Actual behaviour:**
If the _Custom Amount Text_ field is left blank, it falls back to showing the placeholder text.

![image](https://cloud.githubusercontent.com/assets/134939/13719619/80b08018-e7ad-11e5-97a9-efe6e51e79dd.png)

**Comment by DevinWalker** [comment]
I should have read those instructions clearer. I just did work on that here: https://github.com/WordImpress/Give/issues/462

You're right, it makes sense that if it's blank it should *not* display.
