### ISSUE TITLE
When "custom donation" is enabled it's not obvious to the end user

### ISSUE THREAD

**Issue by getresults** [WordImpress/Give#53]
Turning on "custom donation" allows end users to enter a custom amount, but visually there is no indication until they mouse over the amount field and click into it.  It will be very easy for visitors to miss that entering a custom amount is possible.  

Suggestion:  Add "Or enter a custom amount" message below the donation options to help users realise that custom donations are accepted.  Possibly activate cursor in amount field so flashing cursor draws attention?

**Comment by DevinWalker** [comment]
Agreed. This is also an issue with multi-level donations. This is mentioned in #43 - I'm going to close that one out and work from this one.

**Comment by DevinWalker** [comment]
We have added the "Custom Amount Text" option. The field's text appears as a label next to the custom amount field for single level forms. For multi-level forms the text will appear as it\'s own level (ie button, radio, or select option). You can also leave this field blank to prevent it from displaying within your form.
