### ISSUE TITLE
Add a link to settings page from the plugin listing page

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#531]
Right now we don't have any link to go quickly to the settings page from the plugin listing page. We should add a "Settings" link here:

![screen shot 2016-03-21 at 3 44 44 pm](https://cloud.githubusercontent.com/assets/1571635/13936574/db623d3c-ef7b-11e5-982d-45ca4e8ac23d.png)

**Comment by mathetos** [comment]
@DevinWalker while you're there a link to Documentation might be nice as well.

**Comment by DevinWalker** [comment]
@mathetos I added that and a link to the addons

**Comment by mathetos** [comment]
Just downloaded the latest from the Master branch. Only the "Settings" link exists and it's wrong.

It currently links to:
...wp-admin/edit.php?post_type=give&page=give-settings

But it should link to:
...wp-admin/edit.php?post_type=give_forms&page=give-settings
