### ISSUE TITLE
Blurry Single Donation Form Featured Image

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#535]
We are getting multiple people saying that the featured image is blurry and I was able to reproduce.

**Comment by mathetos** [comment]
I think I'd like to see a setting for this. Basically, in the "Display Options" panel we can output a list of all current registered image sizes including those generated by the theme using [get_intermediate_image_sizes](https://codex.wordpress.org/Function_Reference/get_intermediate_image_sizes). Then allow the user to choose which image size they want to use.

For example, the last comment on this thread:
https://wordpress.org/support/topic/blurry-featured-image-with-give-plugin?replies=6

That theme uses a very large custom image size generated from the theme. If the user could just select that size from a drop-down his issue would be resolved easily.
