### ISSUE TITLE
formatCurrency is missing space between number and symbol

### ISSUE THREAD

**Issue by flack** [WordImpress/Give#5367]
## User Story

As a user, I want to see the properly formatted amount so that I can be sure about what I'm about to donate.

## Details

In PHP, all currencies that are not explicitly listed get a space between the amount and the symbol:

https://github.com/impress-org/givewp/blob/194015ed4583da3fa84c7fe9be21a156649edd95/includes/currency-functions.php#L309

So when I open a donation form `give-final-total-amount` contains a string like this (because it's rendered by PHP):

> 50,00 CHF

when I click a donation level or manually enter a sum, the display changes to this (because it's rendered by JS):

> 50,00CHF

which is ugly and inconsistent

## Expected Behavior

The amounts should be rendered consistently throughout the site, the JS and PHP renderer should produce the same result

## Steps to Reproduce

1. Go to any form (the prefilled donation amount will be rendered correctly)
2. enter a manual amount or click a donation level
4. the whitespace between the amount and the symbol is now missing

## Visuals

rendered by PHP:

![Screenshot_20201013_164942](https://user-images.githubusercontent.com/425166/95877232-2d299780-0d74-11eb-9e7f-437c9934d22d.png)

rendered by Javascript:

![Screenshot_20201013_165000](https://user-images.githubusercontent.com/425166/95877254-331f7880-0d74-11eb-81c9-08638fb21158.png)

## Acceptance Criteria

-   [ ] Changes to the donation render the currency in the same format as was originally rendered by the server.

**Comment by karlsauter** [comment]
Hi, this is my first time trying to contribute to Open Source and this seems like a good bug to start. If no one is working on this, can I take it on?

**Comment by kjohnson** [comment]
@karlsauter please feel free to open a Pull Request. We will happy review and consider the change.

**Comment by karlsauter** [comment]
Hey @kjohnson, I found the code, made the change and it works. But different countries and regions format currency differently, some add spaces, other's don't.
A better solution would be to use the [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) function, and ask the user their locale settings.

Any thoughts?

**Comment by flack** [comment]
@kjohnson Maybe I'm missing something, but this ticket is about JS not rendering correctly, i.e. this function:

https://github.com/impress-org/givewp/blob/62b2716bd069a3e83bebe692e376f5f4cc28a6ec/assets/src/js/plugins/give-api/api.js#L42

So removing `includes/` won't change the issue
