### ISSUE TITLE
Featured image displays in preview, but not when form inserted into a page

### ISSUE THREAD

**Issue by getresults** [WordImpress/Give#54]
When adding a new form it's possible to select a feature image. 

When clicking on "Preview Form" it shows the featured image (or a placeholder image if no image is selected).

However, when adding the form to the page no featured image is shown.

This is confusing.

**Comment by stegosource** [comment]
The featured image acutally does show on the Form custom post type, but yes it does not show up as a shortcode. 

Personally, I would remove the CPT options, keep it as just a shortcode option, and remove support for Featured image.

**Comment by DevinWalker** [comment]
Some sites may have a lot of use for the single views. For instance, one of our clients has a donation site setup with many single views: https://citygospelmission.org/donate/hot-meals-donation/ https://citygospelmission.org/donate/job-readiness-donation/

The same functionality should be easy to implement in Give. We will most likely make an option under Settings > Display Options to enable or disable the single view, which will effectively disable the featured image as well.

**Comment by DevinWalker** [comment]
Circling back to this one: So I've reviewed this and it's resolved because --

* Disabling single views in now possible
* Featured images should only display in single view and not within shortcode embeds
