### ISSUE TITLE
Possible conflict with Quotes Collection plugin

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#543]
Reported here: https://wordpress.org/support/topic/conflict-with-quotes-collection-plugin-1?replies=2

**Comment by DevinWalker** [comment]
https://wordpress.org/plugins/quotes-collection/

**Comment by mathetos** [comment]
I duplicated this error. Looks related to how we allow the Give Accountant to see the sub-menu items of the Donations root menu item. But it's unclear to me why that happens only with the Quotes Collection plugin activated -- so it could be related to how THEY do capabilities.

**Comment by mathetos** [comment]
Here's what I found:

* The Quotes Collection plugin root menu is added via add_menu_page(), not via registering a Post Type
* When the errors appear, the Quote Collections menu item actually links to the Give Transactions page.
* The Quote Collections menu viewing capability is assigned as "edit_posts". If I give the "Give Account" that capability then the errors go away.

**Comment by DevinWalker** [comment]
It appears this plugin is no longer on the repo: https://wordpress.org/plugins/quotes-collection/
