### ISSUE TITLE
Member-only donation forms don't display member-only validation responses properly

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#551]
Scenario: When "Disable Guest Donations" is enabled and "Register / Login Form" set to None for a particular donation form and a guest attempts to make a donation - this is called a "Member-only" donation form.

![screen shot 2016-03-30 at 10 47 43 am](https://cloud.githubusercontent.com/assets/1571635/14152025/ca99c31c-f665-11e5-8219-d2deeaa3f914.png)

Problem: The form just reloads without any indication that it's only a members donation form

How to fix? Options:

1. Close the form entirely and display a message above that the form is for member donations only
2. Don't close the form at all, when a guest tries to donate display an error message that indicates it's only for members 

@mathetos thoughts?

**Comment by mathetos** [comment]
Hmmm... I really don't like putting the burden of discovering a setting problem on the DONOR instead of on the Admin. The error should appear in the Form Edit screen so that the Admin can fix it before it's live for donors.

**Comment by DevinWalker** [comment]
What do you mean setting problem? It's not a problem. It's creating a member-only donation form that can be used for various reasons. If the admin places it publicly and non-logged in users can access it then this is where error appears

**Comment by mathetos** [comment]
Yes, which means that a non-logged in donor attempts to donate and only after filling in all the information gets a message that tells them they can't donate. Not a good donor-experience.

**Comment by DevinWalker** [comment]
So... #1 Close the form entirely and display a message above that the form is for member donations only

**Comment by mathetos** [comment]
Ya, I think that's far better for the donor overall. And I can see that if the Admin is using a membership plugin of some sort then the combo of "Disable Guest Donations" and "No login/registration" form would actually be beneficial for them.
