### ISSUE TITLE
Validation conflicts with MemberPress

### ISSUE THREAD

**Issue by jimwebb** [WordImpress/Give#568]
The JavaScript credit card validation routines are looking for inputs via `.card-number, .card-cvc, .card-expiry` -- that's pretty general, and it turns out MemberPress uses `.card-cvc` for its own thing. Because the Give validation doesn't do any further checking, it throws a JavaScript error. I think in some circumstances this is mucking with the MemberPress functionality, and regardless it's worth a fix. Submitting a PR shortly.

**Comment by jimwebb** [comment]
#569

**Comment by DevinWalker** [comment]
Bah! How could I have overlooked that...
