### ISSUE TITLE
login/cancel/register checkout form links don't trigger float-labels, and it has problems when changing gateways

### ISSUE THREAD

**Issue by pryley** [WordImpress/Give#574]
#500 

Login link doesn't re-trigger float-labels if the option is enabled for the form:

![slack-imgs com](https://cloud.githubusercontent.com/assets/134939/14405717/aa316abc-fe62-11e5-9914-45d28cf90922.png)

Actually this isn't the only problem.

1. Enable Offline Donation gateway and a gateway with a creditcard form
2. Make the Creditcard gateway the default payment method
3. Enable both registration and login on the form
4. View the donate form and select the Offline Donation method
5. Click "Login" (first make sure you are not already logged in) 
6. Click "Cancel"

**Expected result:**

- Login form disappears and the "Create an account" form reappears
- The payment form is still the "Offline donation" form 
- The offline text is above the "Donate now" button.

**Actual results:**

The login/register forms toggle correctly, however...

- The "Offline Donation" method is still selected but the payment form is now the default credit card method form.
- The offline text is below the "Donate Now" button

**Comment by pryley** [comment]
Actually this isn't the only problem.

1. Enable Offline Donation gateway and a gateway with a creditcard form
2. Make the Creditcard gateway the default payment method
3. Enable both registration and login on the form
4. View the donate form and select the Offline Donation method
5. Click "Login" (first make sure you are not already logged in) 
6. Click "Cancel"

**Expected result:**

- Login form disappears and the "Create an account" form reappears
- The payment form is still the "Offline donation" form 
- The offline text is above the "Donate now" button.

**Actual results:**

The login/register forms toggle correctly, however...

- The "Offline Donation" method is still selected but the payment form is now the default credit card method form.
- The offline text is below the "Donate Now" button

**Comment by DevinWalker** [comment]
I was just able to reproduce this. I appreciate you reporting the bug and submitting the PR!
