### ISSUE TITLE
Fill form fields with previously entered validated values on give_send_back_to_checkout()

### ISSUE THREAD

**Issue by pryley** [WordImpress/Give#576]
When a guest user fills out the payment form and the transaction fails with a soft error (e.g. country validation, card is declined, bad cvc, etc.), it redirects them back to the form and shows the transaction error notice. However, because the user is a guest and has not logged in or created an account, they have to fill out the entire form all over again for a second attempt.

I suggest sending validated values back to the form and have the form template functions use the $_REQUEST field values if they exist.

```
give_send_back_to_checkout( '?' . http_build_query( $validated_form_values ) );
```

**Comment by DevinWalker** [comment]
This would be very nice indeed. 👍
