### ISSUE TITLE
Some Give settings don't have defaults

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#577]
If a theme or plugin author wanted to create a coditional based on a Give setting, they'd get PHP notices for some settings. Here's an example:

Let's say you want to display the tag of a form on the archive page. But you only want that markup to appear if tags are enabled, so you do something like this:

```
$give_options = give_get_settings();

if( $give_options['enable_tags'] == 'on' ) {
		$givetag = get_the_terms($post->id, 'give_forms_tag');
		$taglink = get_term_link($givetag[0]->term_id);
	}
```

The problem is that if tags are NOT enabled, the "enable_tags" setting simply doesn't exist in the database, which means you'll get a notice like this in the frontend:

`Notice: Undefined index: enable_tags in /.../plugins/beyond-2016-ecommerce/integrations/give/templates/template-parts/archive-content.php on line 18`

## SUGGESTION
To avoid this, all settings have to have defaults that are saved regardless of their state.

**Comment by DevinWalker** [comment]
Hey there,

I would suggest that rather than using `give_get_settings` to get a specific setting use `give_get_option('enable_tags')` which will pull in that specific option and return false if not set to prevent PHP warnings.
