### ISSUE TITLE
Support multiple colors.

### ISSUE THREAD

**Issue by stegosource** [WordImpress/Give#58]
Right now, removing the CSS is supported, but what about offering some simple colors or skins. I know a lot of plugins offer this as a paid for add-on, but something like this should probably come out of the box or as a free add-on if it only changes the color of the buttons.

**Comment by mathetos** [comment]
We have several different ideas for handling that. Right now, you can do templates just like woocommerce does, but we'll need to finalize the docs on that so folks have a leg up on how to make that happen.

**Comment by DevinWalker** [comment]
I'm removing this from the 1.1 milestone

**Comment by DevinWalker** [comment]
I'm closing this out. We don't have any plans to add any theming options within the plugin. We're really leaning towards theme authors to present our plugin in the best way possible. Also, we are including code to be compatible with some of the most popular themes like Avada, X, Flatsome, Divi, etc. See: https://github.com/WordImpress/Give/issues/55
