### ISSUE TITLE
Need a {receipt_link_url} email tag for easier styling

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#581]
Currently we have a {receipt_link} email tag which outputs a hard-coded <a> tag with the url automatically generated. The major limitation to this is if you are styling your email template you do not have the ability to control the color of that link at all.

Adding a {receipt_link_url} email tag will allow people to do something like this in their email template:

`<a href="{receipt_link_url}" style="background: green; color: white; padding: 4px;">See your receipt online here</a>`

**Comment by ramiy** [comment]
@mathetos 

Just started to work on this enhancement, and then I found the `{receipt_link}` email tag:

https://github.com/WordImpress/Give/blob/master/includes/emails/class-give-email-tags.php#L334

**Comment by DevinWalker** [comment]
@ramiy it outputs a full anchor tag though, https://github.com/WordImpress/Give/blob/master/includes/emails/class-give-email-tags.php#L573

Matt is asking for just the raw URL

**Comment by ramiy** [comment]
![receipt_link_url](https://cloud.githubusercontent.com/assets/576623/17930506/3e815a2a-6a0f-11e6-9d2d-d35b176fd203.png)

Has PR. Needs Testing. @mathetos

**Comment by DevinWalker** [comment]
Tested, works, added a preview code in e7fa158c33bbc7059e3fa1ec93566687ac81e327

Closing
