### ISSUE TITLE
Optional login is not optional

### ISSUE THREAD

**Issue by stegosource** [WordImpress/Give#59]
I tested the "optional" login form during a donation and it did not allow the donation to go through without being logged in.

![login error](https://cloud.githubusercontent.com/assets/11436569/6743905/bddea826-ce5d-11e4-9ebf-c28fbaac895f.jpg)

**Comment by mathetos** [comment]
Good catch.

**Comment by DevinWalker** [comment]
Good catch indeed.

**Comment by DevinWalker** [comment]
@stegosource can you pull the latest and test to see if this is fixed on your end? I tested pretty darn thorough but another set of eyes on this would be great. Try to break it the best you can if you have the time.

**Comment by DevinWalker** [comment]
Closing this out @stegosource - if you notice anything quirky LMK but all should be good now.
