### ISSUE TITLE
Allow Login via Email

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#590]
WordPress 4.5+ allows login by email now so we should as well:

![screen shot 2016-04-20 at 11 36 22 am](https://cloud.githubusercontent.com/assets/1571635/14686079/1f086d18-06ec-11e6-9b6a-8dcc044f5663.png)

**Comment by DevinWalker** [comment]
This may already work, I haven't tested it yet.

**Comment by ravinderk** [comment]
@DevinWalker I checked and confirming that give login form is working fine with email and username.

![give-login-shortcode](https://cloud.githubusercontent.com/assets/1784821/16677252/74e3af48-44f1-11e6-8758-ffe5fabaad7e.gif)

**Comment by DevinWalker** [comment]
@ravinderk perfect, thanks

**Comment by DevinWalker** [comment]
Thanks for confirming - I've bumped it off the milestone and closing this out.
