### ISSUE TITLE
Front-end notice if no payment gateway is enabled

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#593]
Per this ticket here:
https://wordpress.org/support/topic/give-plugin-not-working?replies=3#post-8330759

Perhaps when no gateway is enabled at all, we should have a front-end notice saying:
"This form currently cannot accept payments. Please contact the site administrator".

**Comment by ramiy** [comment]
I've started working on this ticket.

Seems like when you remove all the gateways, it return "paypal" by default...

Tried everything to remove all the gateways, am I missing something? Do we set some kind of default in the code?

**Comment by ramiy** [comment]
@mathetos 

See this line: https://github.com/WordImpress/Give/blob/master/includes/gateways/functions.php#L98

Why does the plugin sets "**paypal**" as a default gateway? What is the logic behind this?

**Comment by DevinWalker** [comment]
This has been resolved in `release/1.8` in the admin by preventing admins from disabling all gateways:

![2016-12-21_12-29-03](https://cloud.githubusercontent.com/assets/1571635/21405082/38e79a9e-c779-11e6-9ca7-367403f27fd1.gif)
