### ISSUE TITLE
Latest Give Plugin Makes Admin Pages Unresponsive

### ISSUE THREAD

**Issue by manyoso** [WordImpress/Give#599]
At the top of the wordpress admin I see this message when activating the Give plugin:

**Warning: Error while sending QUERY packet. PID=37690 in /path/to/wordpress/wp/wp-includes/wp-db.php on line 1803**

Additionally, the site becomes unresponsive for tens of seconds upon each navigation around the admin area.  I have the latest version of the **Give plugin (1.4.2)** installed as well **version (4.5.0) of Wordpress.**

I also see the message "**Your site appears to be blocking the Wordpress ajax interface**", but we've gone through all the recommendations here and can find nothing wrong.

I've attached my wordpress installation and activated plugin information files as well as a note from my ISP detailing what they have done trying to resolve this.  We would love to use the Give plugin and are open to purchasing the Pro version, but it would be hard to justify if we can't get the Core plugin working.

Thank you.
[isp_email.txt](https://github.com/WordImpress/Give/files/238932/isp_email.txt)
[server_info.txt](https://github.com/WordImpress/Give/files/238933/server_info.txt)

**Comment by DevinWalker** [comment]
Does the previous version work fine for you?

**Comment by manyoso** [comment]
The previous version also displayed the problem.  I saw the new version today and thought it might fix the issue but it does not.

**Comment by DevinWalker** [comment]
It seems to be pretty specific to your setup. I haven't seen any other reports of this... could you email me at devin (at) givewp.com and we'll see if we can work it out off of Github?
