### ISSUE TITLE
No Editor Toolbar in Visual Mode

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#6]
WYSIWYG doesn't have full toolbar when in Visual mode. So no Content or Terms of Service available.

**Comment by DevinWalker** [comment]
@mathetos is this just on the give form post type or all of them? A screenshot may help me to reproduce

**Comment by DevinWalker** [comment]
This is probably due to the JS error in #7 - can you try pulling the latest version and testing again to confirm?

**Comment by DevinWalker** [comment]
@mathetos closing this out - should be fixed now
