### ISSUE TITLE
Registration form on lightbox appearance

### ISSUE THREAD

**Issue by stegosource** [WordImpress/Give#60]
The password confirmation field looks a bit off when the registration form is displayed in the lightbox popup form. Perhaps putting each input on their own line would solve this. 

![pass confirm error](https://cloud.githubusercontent.com/assets/11436569/6743942/561b65ac-ce5e-11e4-9402-dbeb4913bfe2.jpg)

**Comment by ibndawood** [comment]
Hello @DevinWalker, Can I make the 3 columns in individual rows and submit a PR ?

**Comment by DevinWalker** [comment]
@ibndawood can you make it responsive so they are only 3-column within the modal or at that width which is displayed in the screenshot showing the label bump to 2 lines? That would be awesome.

**Comment by mathetos** [comment]
@ibndawood Devin and I would like to chat with you in detail. Can I get your email address? Or simply email me at matt@givewp.com Thanks!

**Comment by ibndawood** [comment]
Hello @mathetos , I have sent you an email. Looking forward to your discussion.
