### ISSUE TITLE
Error Related to minimum donation amount.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#610]
How to reproduce:

1. Create a form with multi-level donation with one level of anything greater than $5, and the custom amount option "yes" selected. Give the form a minimum amount of $5.
2. Publish the form.
3. On the front end, select the custom amount but don't enter anything, then select the set level.

You should see this:
![screen shot 2016-05-05 at 6 37 01 am](https://cloud.githubusercontent.com/assets/9629102/15041684/d95db862-128b-11e6-9e17-1e867b0da8f3.png)

The fix could be that the placeholder/value on the custom amount input defaults to the form minimum. Somewhere in or around line 242 of assets/js/frontend/give-checkout-global.js is my 2-minute stab at it.

**Comment by DevinWalker** [comment]
Thanks for reporting

**Comment by DevinWalker** [comment]
Setup like this? 

![screen shot 2016-05-05 at 10 07 15 am](https://cloud.githubusercontent.com/assets/1571635/15050517/2bdf892c-12a9-11e6-9f2b-269ffcd6d9df.png)

**Comment by DevinWalker** [comment]
Fixed https://github.com/WordImpress/Give/pull/612
