### ISSUE TITLE
Do string_replace for all registered email tags, not just {email}

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#611]
Currently, when working with the email templates, we have a function to render the Donation Receipt text with a string_replace that looks for the {email} tag. 

But if I were to take another registered email tag, like {fullname} and put it in my HTML email template outside of the {email} tag, it won't be rendered at all.

I think it would provide a lot more flexibility for custom email templates to be able to render any of the registered email tags anywhere throughout the HTML email template.

**Comment by DevinWalker** [comment]
Closed in favor of #1346
