### ISSUE TITLE
Version 1.4.3 breaks modal popup display method

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#615]
## STEPS TO RECREATE
* Update to version 1.4.3
* Create a form using the modal popup method
* Try to donate and the "Donate Now" button won't open the modal as intended

**Comment by DevinWalker** [comment]
Fixed - somehow our Gulp task didn't compile right... maybe I ended it prematurely. Either way, not good but at least it's been caught within a few hours. Releasing 1.4.4 now.
