### ISSUE TITLE
Typo in help text

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#617]
Don't know if we want to fix it because it'll need re-translating, but in

`includes/gateways/offline-donations.php:267`

The word "forms" should be singular.

**Comment by Benunc** [comment]
also in `includes/admin/forms/metabox.php:284`

"click" should be singular in 

> places a button below the donation fields and upon clicks slides into view the rest of the fields

**Comment by DevinWalker** [comment]
That's OK, we should fix typos
