### ISSUE TITLE
Undefined Index "page_success" when Page is null in settings

### ISSUE THREAD

**Issue by bryanmonzon** [WordImpress/Give#62]
This is probably related to Issue #40. 

The problem is that my settings are saved, just without a success page set. 

![image](https://cloud.githubusercontent.com/assets/237399/6746930/7bc6d1b2-ce8e-11e4-9ae6-eb6e115b3430.png)

**Comment by DevinWalker** [comment]
I just saw this a second ago as well. Definitely related to #40 thanks for the cross-ref

**Comment by DevinWalker** [comment]
Fixed as of 9c27c72
