### ISSUE TITLE
Need to Remove shortcode generator when visual editor disabled in user settings

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#638]
This is a bug.

### Steps to replicate:
1. Disable visual editor for current user (self) in Users --> Your Profile (check box and save settings.)
1. Add new post or page.
1. Attempt to use the shortcode generator.

The options will show up, but there's no way to select them. The console will show an error "tinymce is not defined." 

### Potential fix:
add a check for `user_can_richedit()` in https://github.com/WordImpress/Give/blob/master/includes/admin/shortcodes/abstract-shortcode-generator.php#L95 

also submitted a PR for this

**Comment by DevinWalker** [comment]
Closed with this merge https://github.com/WordImpress/Give/pull/637
