### ISSUE TITLE
When Form Single view is disabled in settings, a "View Form" link shows on Publish/Update

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#646]
If a user has disabled Single form views in Settings > Display options, we should change the "Form Published. View Form" link that WordPress shows, because the link is busted.

<img width="385" alt="screen shot 2016-06-15 at 9 46 43 pm" src="https://cloud.githubusercontent.com/assets/9629102/16102994/b81175a4-3342-11e6-91ef-1834a1e2ac18.png">

**Comment by DevinWalker** [comment]
Hmm, interesting. That seems to be more of a bug with how WordPress core handles CPTs with no single pages. Good call.

**Comment by DevinWalker** [comment]
I'm curious, did you try refreshing permalinks after

**Comment by Benunc** [comment]
No, but I just tried flushing permalinks and it didn't work there either.
