### ISSUE TITLE
Add a way to make large goals (and progress) more readable.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#650]
We need a way to make these types of goals prettier:
![screen shot 2016-06-23 at 8 55 37 pm](https://cloud.githubusercontent.com/assets/9629102/16324720/ed563108-3984-11e6-8a9d-c36803d5d829.png)

User suggested:
https://secure.helpscout.net/conversation/218601651/2573/?folderId=672199

>Our team doesn't like the decimals being there and all the zeroes for the amount to raise. makes it look too big and the two decimals are really unnecessary. Can't find a setting to disable decimals.
Ultimately we want it to look like this as it is much easier for people to read and wrap their minds around:
$1,935,860 of $15 million raised to date

Let me know how we can accomplish this.

I found this function in some PHP docs that does something like we'd want: http://php.net/manual/en/function.number-format.php#89888

**Comment by DevinWalker** [comment]
That's a pretty handy function @Benunc

**Comment by ravinderk** [comment]
@DevinWalker I have few questions :

1. Are we planning to give option to user to **disable decimal formation setting**  in both edit form (local) and global give setting?
2. Are we planning to disable decimal formatting for both raised money and goal money or only one of them or user have that option to set to which we can apply formatting?
3. Are we planning to give option in  edit form (local) and global give setting to set minimum criteria to user means after which minimum amount we can start formatting like after thousand,  ten thousand etc. ?

**Comment by DevinWalker** [comment]
Hey 

1. Not right now - it's an interesting idea though to consider
2. For both - no user option
3. Good question. I don't think we need another option. Let's start formatting at the millionth and provide a filter to disable the functionality entirely.

**Comment by DevinWalker** [comment]
Fixed with merge above #763
