### ISSUE TITLE
Duplicate "Save Settings" buttons

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#651]
once a user has generated API keys, the settings pages all have two "Save Settings" links at the bottom.

Steps to reproduce.

1. Activate Give Plugin (1.5 release branch) 
1. generate API keys in Users > Your Profile
1. visit the give settings page and scroll to the bottom.

![screen shot 2016-06-24 at 6 07 39 am](https://cloud.githubusercontent.com/assets/9629102/16340238/f323a3c0-39f4-11e6-92ae-0a3bc2cda3eb.png)

Tested creating a new user without API keys, and the new user also has duplicate Save Settings buttons.

**Comment by DevinWalker** [comment]
Good catch, fixed
