### ISSUE TITLE
Introduce Customer Meta Table & Class w/ CRUD Methods

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#653]
We need a better way to store customer data than usermeta. Same reasons as EDD See: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4311

**Comment by DevinWalker** [comment]
See: https://github.com/easydigitaldownloads/easy-digital-downloads/pull/4535/files

**Comment by DevinWalker** [comment]
I'm bumping this back to 1.6 because I see it as a pretty high priority

**Comment by mathetos** [comment]
@DevinWalker I read through that ticket, and this stuck out as potentially important too:
https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4311#issuecomment-221715890

I know it's tangential to this, but what's your thoughts on that? Should we do upgrade routines when the GIVE_VERSION constant is changed?

**Comment by DevinWalker** [comment]
@mathetos absolutely. I don't think users should need to click a button to run an upgrade for most cases.
