### ISSUE TITLE
give_forms doesn't register correctly on new installs

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#671]
AS reported here:
https://wordpress.org/support/topic/the-add-forum-tab-not-showing?replies=4#post-8587308

Occasionally, the "All Forms" and "Add Form" menu items don't appear at all on a fresh install of Give. I haven't been able to duplicate it in a way that is reliable, but I did have it happen once on a new local install.

**Comment by DevinWalker** [comment]
Do they display after refreshing permalinks? I'll see if I can replicate it

On Wednesday, June 29, 2016, Matt Cromwell <notifications@github.com> wrote:

> Assigned #671 <https://github.com/WordImpress/Give/issues/671> to
> @DevinWalker <https://github.com/DevinWalker>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/WordImpress/Give/issues/671#event-708663382>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABf7MzLY71dwwXmjmVc7YPNPpkFPJFdRks5qQ0XJgaJpZM4JBynE>
> .
>


-- 

Devin Walker

Founder & Lead Developer

P:

858-449-6460 <8584496460>

W:

http://wordimpress.com

433 G Street #201
San Diego, CA 92101 <https://goo.gl/maps/BePgp>
<https://www.facebook.com/wordimpressive>  <https://twitter.com/wordimpress>
  <https://plus.google.com/u/0/b/117062083910623146392/+Wordimpress/about>
<http://wordimpress.com/>

**Comment by mathetos** [comment]
See additional comments on that thread. It seems it's unique to a brand new install of version 1.5, basically, NOT upgrading.

**Comment by michaelalhilly** [comment]
I just experienced this too. Is there a workaround for now? I'm stuck.

**Comment by mathetos** [comment]
Hi @michaelalhilly read the comments on this thread:
https://wordpress.org/support/topic/the-add-forum-tab-not-showing?replies=4#post-8587308

The way they got it to work is to install our WP-Rollback plugin, roll back to 1.4.5, then upgrade to 1.5 again.  Let us know how that goes.

**Comment by DevinWalker** [comment]
Appears there are some lingering issues still as @Benunc mentions:

>confirmed. fresh install. give core plugin by itself version 1.4.5. create a form. update through plugin updater. view All Forms. no edit option on hover.

**Comment by DevinWalker** [comment]
Related to #662

**Comment by DevinWalker** [comment]
OK, so the issue is basically the install process is not run for plugin updates 
see: https://codex.wordpress.org/Function_Reference/register_activation_hook
>3.1 : This hook is now fired only when the user activates the plugin and not when an automatic plugin update occurs (#14915).

**Comment by mathetos** [comment]
So just hook the CPT registration to a new hook that applies to installation and update?

**Comment by michaelalhilly** [comment]
@mathetos Thanks! That worked for me!
