### ISSUE TITLE
Integrate with Akismet for added spam filtering

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#673]
Besides our Honeypot, we could lean on Akismet to help filter more spam donations out. Here's how Contact Form 7 does it:

http://contactform7.com/spam-filtering-with-akismet/

Here's their source:
https://github.com/wp-plugins/contact-form-7/blob/ba71e5ba72764dc08c4987f76d135d1ef19bd9a7/modules/akismet.php

**Comment by Benunc** [comment]
Can we investigate false positives flagged by akismet? this is not as big of a deal for comments, but if donations are being blocked two things are true:

1. Donors are the only ones who see the error and have to report them to site admins.
2. the organization is losing money, not just comments.

It needs to be something that also alerts the admin of the "spam"
