### ISSUE TITLE
Improve Scrutinizer Score

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#675]
They provide a lot of great code improvement fixes that we should be completing ongoing as we can on Scrutinizer: https://scrutinizer-ci.com/g/WordImpress/Give/code-structure/master/hot-spots

**Comment by ramiy** [comment]
Interesting read about globals and how to remove them from your code: https://core.trac.wordpress.org/ticket/37699

**Comment by DevinWalker** [comment]
@ravinderk let me run this idea by you. We're getting hit pretty hard on Scrutinizer due to the code complexity "Conditions" and "Paths":

![2016-12-07_21-10-23](https://cloud.githubusercontent.com/assets/1571635/20998309/b70dfebc-bcc1-11e6-98b7-8fe1257df6a2.png)
![2016-12-07_21-10-23](https://cloud.githubusercontent.com/assets/1571635/20998311/b8383d0c-bcc1-11e6-9cdb-1e9fa1e5c420.png)
 
For the "Paths" it's likely due to checking if `isset()` in a ternary conditional. Why don't we create a function that we could pass all these conditonals through, or does one already exist in Core that I'm unaware of? We are mainly doing all these `isset()` and `empty()` conditionals to prevent PHP notices.

**Comment by DevinWalker** [comment]
Closing this old issue out as it's an ongoing effort.
