### ISSUE TITLE
Donation amount and count get reduced when delete pending donation

### ISSUE THREAD

**Issue by farookibrahim** [WordImpress/Give#677]
When we delete the placed donation even it is pending/cancelled. The donation count and amount get reduced.

Here i have added some screenshots:

![give-issue-1 1](https://cloud.githubusercontent.com/assets/10401366/16518540/09b89dbe-3fa1-11e6-8420-3579f6e13edd.png)

![give-issue-1 2](https://cloud.githubusercontent.com/assets/10401366/16518541/09bc0184-3fa1-11e6-8905-0f51c3839cd6.png)

![give-issue-2 1](https://cloud.githubusercontent.com/assets/10401366/16518542/09c06792-3fa1-11e6-8665-efaa6468c21d.png)

![give-issue-2 2](https://cloud.githubusercontent.com/assets/10401366/16518543/09c555e0-3fa1-11e6-8d7f-f58a037d0b28.png)

![give-issue-2 3](https://cloud.githubusercontent.com/assets/10401366/16518544/09c6879e-3fa1-11e6-9e11-3c3630c9190b.png)

**Comment by DevinWalker** [comment]
Thanks I'll look into this asap
