### ISSUE TITLE
Create Global Terms and Conditions setting

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#679]
Similarly to how we implemented Offline Donations, allow users to set the T&C globally, but override it per form if necessary.

Requested here:
https://wordpress.org/support/topic/terms-conditions-page-1?replies=3#post-8593885

**Comment by ravinderk** [comment]
@DevinWalker @mathetos 

Can i add **Terms and Conditions** global setting section to general tab after **Currency setting section** inside give plugin setting or do i have to create separate setting tab for this?

**Comment by mathetos** [comment]
@ravinderk I think it would be best for it to be its own section inside the "Display Options" tab.

**Comment by DevinWalker** [comment]
I disagree. I think it should be under "General" within it's own section at the bottom called "Terms". There should only be one field, a WYSIWYG editor, with default terms in place that each form will inherit when they elect to turn on terms for that form.

**Comment by DevinWalker** [comment]
Ok, @mathetos and I discussed this and there are a few items we need to clear up before moving forward with this.

**Comment by ramiy** [comment]
In my opinion **Terms and Conditions** should be a separate Add-on. It's not a must-have functionality, and you don't have to use it in every form. It's a "nice to have" extension.

Moving the **Terms and Conditions** to an add-on has it's own benefits.

**Comment by DevinWalker** [comment]
It's already in core and people are actively using it. It's a basic functionality not in need of an Add-on.

**Comment by mathetos** [comment]
I don't think this implementation is what we need. I think this will create more confusion than benefit like this.

1) There's a global setting, but per form there's just a "Yes/No" for adding the terms. 
2) When the Admin chooses "Yes" they are shown the T&C title and description WITHOUT the global being preset. 
3) If they don't put anything in the title/description then the global is inherited but that's not obvious from a user perspective at all.

In discussing with @DevinWalker more, this needs to be reverted and a different approach taken.

**Comment by mathetos** [comment]
Here's the approach I would take:

## In the Settings
* The new settings that were added in #980 is fine

## Per Form
* The first question needs to be "Add Terms and Conditions Requirement?"
* If "Yes" is chosen, the next option appears with "Use Global Terms and Conditions?".
* If "Yes" is chosen, the form inherits the T&Cs from give_settings (not saved to post_meta)
* If "No" is chosen, then the next two options open -- WITH the Global T&C content pre-populated -- to be customized and saved to post_meta.

Here's a (sloppy) mock-up:
![terms-and-conditions-mockup](https://cloud.githubusercontent.com/assets/930724/18152707/cd1d44f4-6fac-11e6-9693-d0c2b49d1dfb.png)

**Comment by DevinWalker** [comment]
This should actually follow suit to what we are doing in 1.8 with the other various global options. For new forms the option defaults to the global option, which can be then toggled.
