### ISSUE TITLE
Payment date details

### ISSUE THREAD

**Issue by Rahe** [WordImpress/Give#687]
Hello,

In the payment admin page there is a metabox for the payment metadate like the date, the status and such.
But the date displayed is at the format m/d/Y wich in french can be very disturbing because '06/30/2016' is not a valid date in France, for us this will be '30/06/2016'.

Can you consider using https://jqueryui.com/datepicker/#alt-field with a filter for the displayed date ? So you can keep the mm/dd/YY format and display the user friendly localized date ?

**Comment by DevinWalker** [comment]
Hey @Rahe I was just thinking about how we need to standardize the date format throughout the plugin.  What the best was to do that for all the various date formats is that we use the WordPress default date setting found under WP-Admin > Settings > General:

<img width="750" alt="screen shot 2016-07-04 at 4 38 14 pm" src="https://cloud.githubusercontent.com/assets/1571635/16570946/c506b20c-4205-11e6-88ee-066abfd0c7b2.png">

**Comment by Rahe** [comment]
Hi @DevinWalker,

this was my first idea too, but this setting is for dispalying a date on the frontend and it's not really usefull to have a "Wednesdays, 2 april" displayed at this place, this is most usefull to have a "normal" date format at this place but i18n.

I think a setting into the plugin like a "display date format" not bound to the save format. I have seen the date used is the WordPress post_date field, so this is easy to format it into an another format.

Rahe

**Comment by ramiy** [comment]
@DevinWalker, date formats is a known issue.

Only the US and it's  uses the **mm/dd/yy** format. Most of the world (including Europe) uses **dd/mm/yy**. For more info see this link: https://en.wikipedia.org/wiki/Date_format_by_country

Last year WordPress core changed the way they handle dates in the admin.

In the past core used the `get_option('date_format')` function. But it was changed in favor of local translation strings. See this changeset: https://core.trac.wordpress.org/changeset/35811

Now, each language can use https://translate.wordpress.org/ to set it's preferred date format. Much simpler solution.

I guess adding a filter will be a good idea.

**Comment by DevinWalker** [comment]
How about a function like `give_date_format()` that passes `get_option('date_format')` through a filter called `give_date_format` like Woo's:

<img width="711" alt="screen_shot_2016-07-19_at_10 09 09_pm" src="https://cloud.githubusercontent.com/assets/1571635/16958561/db584d86-4d95-11e6-94ba-f7ceeb124489.png">

The confusing thing though is the various date formats found throughout Woo. For example, here is the frontend checkout page which respects my date option in WP-admin:

![screen shot 2016-07-19 at 9 55 29 am](https://cloud.githubusercontent.com/assets/1571635/16958834/17dfb1bc-4d97-11e6-961a-7c104432f9d5.png)

![screen shot 2016-07-19 at 9 56 56 am](https://cloud.githubusercontent.com/assets/1571635/16958851/2820dbfa-4d97-11e6-93f9-c02cf944cd62.png)

And here in wp-admin on Woo's transaction edit screen and on the reports page the date is `yyyy-mm-dd`:

![screen shot 2016-07-19 at 9 55 48 am](https://cloud.githubusercontent.com/assets/1571635/16958875/40521928-4d97-11e6-9226-9197e8e10d4a.png)

![screen shot 2016-07-19 at 9 55 18 am](https://cloud.githubusercontent.com/assets/1571635/16958879/45ef2204-4d97-11e6-84e3-b42320b8df66.png)

Where it appears hardcoded as this format: `<?php echo date_i18n( 'Y-m-d', strtotime( $post->post_date ) ); ?>`: https://github.com/woothemes/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-order-data.php#L200

What went into this decision by the Woo team and should we follow suit? I'm guessing that the `Y-m-d` is the most internationally recognized format.

**Comment by DevinWalker** [comment]
@ravinderk please paste your `give_get_date` function here when you get a chance! 😄

**Comment by ravinderk** [comment]
@DevinWalker Here is function which I proposed. 

```
/**
 * Get date format string on basis of given context
 * @param  string $date_context    Date format context name.
 * @return string                  Date format string
 */
function give_date_format ( $date_context='') {
      // Date format context.
      // You can add your context or use already exist context.
      $date_format_contexts = apply_filter(
        'give_date_format_contexts'
        array(
          'checkout' => 'F j, Y',
          'report'   => 'Y-m-d',
          'email'    => 'm/d/Y',
        )
      );
      
      // Set date format to default date format.
      $date_format = get_option('date_Format');


      // Update date format if we have non empty date format context and non empty date format string for that context.
      if( $date_context && array_key_exists( $date_format_context, $date_format_contexts ) ) {
        $date_format = ! empty( $date_format_contexts[ $date_context ] )
          ? $date_format_contexts[ $date_context ]
          : $date_format;
      }
​      
      // Result.
      return apply_filters( 'give_date_format', $date_format );
   }
```

**Comment by DevinWalker** [comment]
Thanks @ravinderk
