### ISSUE TITLE
Provide Importable Sample Content

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#689]
We should provide users and easy way to get setup with multiple donation form examples and

Questions/Considerations:
- How does Woo do this exactly? It's been awhile since I've looked. Last time I remember it used their own importer rather than WP- Importer plugin (which many people don't like using a different plugin)
- Should this be a .sql file or csv?
- How can we integrate with Recurring Donations and display Set & Multi-level Admin/Donor's Choice Recurring-enabled forms, sample subscriptions & donor's with active subscriptions, etc.

**Comment by DevinWalker** [comment]
After discussion with @ravinderk 

1. Woo uses both csv & xml - xml is imported via the WP importer - the csv files include products and other data - see https://github.com/woothemes/woocommerce/tree/master/dummy-data
2. no sql file 
3. We should include a separate xml file in that plugin

Thoughts? @Benunc @mathetos

**Comment by mathetos** [comment]
@DevinWalker I believe you wanted to bump this to 2.1 or so, right?

**Comment by ravinderk** [comment]
Closing this issue in favor of #2065
