### ISSUE TITLE
Custom field tooltip

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#69]
The custom amount field might be a little confusing for some users. Typically when you click inside a field the placeholder text disappears. The input mask on that field is definitely useful, but there needs to be some indication to the user that they can type and don't need to delete the numbers that are in there. Perhaps if the placeholder is first greyed out.

**Comment by DevinWalker** [comment]
I'm removing this from the 1.0 milestone because I think it needs to be discussed more and it's a bit vague as to what the actual problem is.

**Comment by DevinWalker** [comment]
I feel that with our latest updates in 1.2 to the custom amount validation that there's no tooltip needed. It's pretty intuitive how it is now.
