### ISSUE TITLE
Need to add better support for the use of a space as thousands separator value

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#696]
In many cultures/currencies, a space is used as the value separator for thousands. In order to enter a space in Give, users have to know the HTML entity code of `&#32;` 

Can we create a way for that input to not sanitize out the space?

Further, once you use that in the settings field, it breaks the layout by wrapping the text on especially large _donation amounts_ (which I realize is an edge case). This would be related to #693 and #650 

<img width="578" alt="screen shot 2016-07-07 at 6 06 03 am" src="https://cloud.githubusercontent.com/assets/9629102/16649857/ed5cf16c-4408-11e6-9baf-6bf763f88e46.png">

**Comment by Benunc** [comment]
break/wrapping issue can be fixed by making the width of that span "auto" instead of "125px"

**Comment by DevinWalker** [comment]
I did not know so many nations use a space for large numbers. https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

@ravinderk I assume Woo supports a space? If so, how does they do it?

**Comment by ravinderk** [comment]
@DevinWalker They store space in database for thousand separator if user want to and use this value in price formatting in `number_format` function
https://github.com/woothemes/woocommerce/blob/master/includes/wc-formatting-functions.php#L419

<img width="842" alt="screen shot 2016-07-08 at 9 12 41 pm" src="https://cloud.githubusercontent.com/assets/1784821/16693005/d884dcc0-4550-11e6-9126-036f210e327f.png">

**Comment by DevinWalker** [comment]
This is resolved with https://github.com/WordImpress/Give/pull/734

**Comment by ravinderk** [comment]
@DevinWalker I found one issue if you check ben's screenshot you will see that if we set larger donation amount without having any custom donation then donation amount breaks in design.

<img width="717" alt="screen shot 2016-07-20 at 5 06 54 pm" src="https://cloud.githubusercontent.com/assets/1784821/16985200/9f894e06-4e9c-11e6-858a-807a86ad095a.png">

Pull request to fix this issue : https://github.com/WordImpress/Give/pull/777
