### ISSUE TITLE
Maintain completed form fields for users when switching gateways

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#697]
Auto pop form entires for logged in user works well. Can we make it work for guest user also? 

![an7iqw4e3m](https://cloud.githubusercontent.com/assets/1784821/16651323/ce61e7f6-4460-11e6-9c67-2ac2c5af6e7a.gif)

**Comment by DevinWalker** [comment]
I agree this is an issue. Do you have an idea on how to resolve it? Keep in mind with form field manager users can include a lot of additional form fields.

- How will it preserve field entries for custom fields via FFM? More "advanced" fields like checkbox groups, select fields, etc. 
- What about CC info? Will that be necessary?
- Most users make their payment gateway selection prior to filling the form fields. Is it necessary that we support this? @mathetos correct me if I'm wrong, but we haven't seem many support requests for this, right?

**Comment by mathetos** [comment]
Custom fields and Form Field Manager fields are the big concern here. But I could see it as very valuable. But no, there have been little to no actual requests for this specifically.

**Comment by ravinderk** [comment]
@DevinWalker @mathetos I agreed with both of you that it is valuable but currently it does not have much priority. We can put this in bucket list.

**Comment by DevinWalker** [comment]
@ravinderk it would be helpful to hear how you would approach tackling this issue. I did some quick googling and couldn't find any definitives.

**Comment by ravinderk** [comment]
@DevinWalker I will check FFM give plugin addon first and then i will update on my approach.

**Comment by Benunc** [comment]
User request for this today.

**Comment by DevinWalker** [comment]
Closing this as:

1. FFM supports preserving fields when changing gateways 
2. I'd like to remove the AJAX loading of gateway fields it's adding more complication that it's worth and it's old legacy way of handling per gateway required fields
3. We're moving to refactor the donation form building experience in an upcoming milestone and this serves the old way forms
