### ISSUE TITLE
Admin-footer.php Fatal Error

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#7]
Maybe this is what's creating some bugs: Fatal error: Call to undefined function wc_enqueue_js() in E:\give.dev\wp-content\plugins\Give-master\includes\admin\admin-footer.php on line 30

**Comment by DevinWalker** [comment]
Looks like that function was improperly brought over when forking the footer code. I've reworked the enqueue process and it should work fine now as of the previous commit.
