### ISSUE TITLE
Dedicated Funds for donations

### ISSUE THREAD

**Issue by Asparagirl** [WordImpress/Give#701]
Hi there. For bookkeeping purposes, non-profits generally need a way to segregate their general donations ("unrestricted") from any donations made to a specific narrowly-tailored project or fund ("restricted", i.e. the new roof fund, the tutoring after school fund, etc.).

Can we create separate funds in Give, sort of like a taxonomy or category, and can the admin then designate which fund each form's donations will go towards, with "unrestricted" as the default site-wide setting?

And when we export donation information into a CSV file, can we please access this data as a new column on every row, to help us when we import the data into accounting software? For example, $250 through form A for the general/unrestricted fund, $35 through form B earmarked for the restricted/new roof fund, $90 through form C earmarked for the restricted/tutoring fund?

Ideally, a donor could make multiple donations through one form on one page, i.e. general donation to the non-profit, plus an optional add-on on the same form for a specific fund/project.  For example, "donate $25 now to help these school kids! optional: would you like to add on another $5 to the library fund to be used for new books? [radio button yes/no]"

Thanks...

**Comment by Asparagirl** [comment]
To clarify: yes, I know Give already allows for tags and categories to organize multiple donation forms within a website, but that seems to be just a front-end UI thing, as opposed to a way to segregate and track where the money collected is meant to go.

**Comment by DevinWalker** [comment]
Hey @Asparagirl thanks for your thorough feature request. It does seem like your request would partly be fulfilled with the taxonomy feature (donation form tags & categories). Essentially, you would create the categories like you specified: "unrestricted" and "restricted" and then add each donation form into their respective categories.

The exporting of the data would be where there would be a need to have some development work done. There would need to be a column for categories and tags. Where it can get complicated is if you're categorizing forms into multiple categories and tags.

**Comment by Asparagirl** [comment]
Well, those can just be comma-delimited within the column, right?

**Comment by DevinWalker** [comment]
@Asparagirl yes they can - but won't that be cumbersome to sort by?

**Comment by Asparagirl** [comment]
Not if we don't assign our forms to multiple categories or tags.  :-)

**Comment by DevinWalker** [comment]
I created a separate issue for the ability to export donations based on category or tag term: https://github.com/WordImpress/Give/issues/867

Closing this out in favor of that one. Thanks for your input!
