### ISSUE TITLE
Prevent user to save non numeric or negative amount

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#705]
Currently user is able to save non numeric number in give form settings.

<img width="755" alt="screen shot 2016-07-13 at 6 47 08 pm" src="https://cloud.githubusercontent.com/assets/1784821/16804606/3fb30142-492a-11e6-9b56-a3418124b1da.png">

<img width="745" alt="screen shot 2016-07-08 at 6 44 29 pm" src="https://cloud.githubusercontent.com/assets/1784821/16688533/1cf4a99a-453c-11e6-9921-172a66228617.png">

<img width="720" alt="screen shot 2016-07-08 at 6 46 53 pm" src="https://cloud.githubusercontent.com/assets/1784821/16688614/704fda92-453c-11e6-850a-d427876aa45c.png">

**Comment by DevinWalker** [comment]
Closing this because this has been fixed with #693 and PR #734
