### ISSUE TITLE
Auto populate state list is not working on transaction detail page

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#715]
![payment-detail-page-state-setting](https://cloud.githubusercontent.com/assets/1784821/16764299/ead89c5c-484a-11e6-86cb-9b2bdeaa19e1.gif)

**Comment by mathetos** [comment]
Hmmm... I'll try to replicate that. Haven't seen that happen before. Are you on the current latest Master branch or the current live version (1.5.2)?

Do you have other Give Addons active?

I'll circle back after I replicate.

**Comment by mathetos** [comment]
@ravinderk I was able to duplicate that behavior both on the latest Master and on the 1.5.2 tag with no other Addons enabled at all. Thanks for reporting that.
