### ISSUE TITLE
Form stats increase each time the payment status changes from revoked to complete

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#722]
As discussed with @mathetos, he confirmed that he was able to replicate same issue.

**Quick solution:**
As @mathetos suggested anybody who is facing this issue can use give tool to fix this issue.
Go to **Reports > Tools** and try the "recalculate" feature.

<img width="669" alt="screen shot 2016-07-13 at 10 17 18 pm" src="https://cloud.githubusercontent.com/assets/1784821/16811785/9e6fecdc-4947-11e6-97ce-6b5e5ceba93f.png">

**Comment by DevinWalker** [comment]
See: https://github.com/WordImpress/Give/blob/master/includes/payments/class-give-payment.php#L625

**Comment by ravinderk** [comment]
@DevinWalker are we increasing stat when payment status change from pending/refund/cancelled/failed to revoked?

**Comment by DevinWalker** [comment]
We shouldn't be, no

**Comment by mathetos** [comment]
The recalculate helps the user reset the stats, but this is still a bug that should be resolved.
