### ISSUE TITLE
Categories and Tags are registering incorrectly on a fresh install

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#725]
## Replication Steps
* Install the latest version of Give on a brand new WP install
* Enable Categories and/or Tags
* Save permalinks
* Go to Add New Form

You'll see the metabox but not the ability to add new categories.

You'll also NOT see the sub-menu items for Categories or Tags under Donations.
![](https://givewp.com/wp-content/uploads/2016/07/Screen-Shot-2016-07-12-at-19.31.23.png)

**Comment by DevinWalker** [comment]
Most likely the capabilities or user roles is missing due to our cleanup in v 1.5 of the user roles - see #662

**Comment by DevinWalker** [comment]
Fixed in merge #793
