### ISSUE TITLE
Auto populate correct donation level when user adds a matching custom amount

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#730]
**Form setting:**
Create a multi donation form with following settings:

1. Donation levels:
             i. Small     : 10$
            ii. Medium : 20$

2. Set custom amount to yes

**Issue:**
When I go to this donation form and donate 20$ successfully with offline payment gateway. It is showing me small donation level select even if i have amount equal to medium donation level. This is happing to frontend and backend both.

**Comment by Benunc** [comment]
Here are the steps I used to successfully replicate:

1. Create donation of $20 by manually typing it in.
2. Backend (and front end) donation confirmation will show donation level for the button (or dropdown or radio button depending on form configuration) I last selected, or the default level if I did not select one.

**Comment by DevinWalker** [comment]
Fixed with a61bdf45ee6c321dea1a2b5b2cfee3623fbeb4a2 merge
