### ISSUE TITLE
Add setting to set number of decimal points shown and saved in prices

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#738]

**Comment by mathetos** [comment]
@ravinderk Would this feature resolve a known issue somehow? Can you clarify a bit how this benefits users in general?

**Comment by ravinderk** [comment]
@mathetos This does not resolve any issue. This is a feature which i am suggesting. This will give ability to user to set number of decimal point from plugin setting (without code) and he can add more precise donation prices to donation forms.

**Comment by DevinWalker** [comment]
I think it's smart to do... like Woo:

![screen shot 2016-07-18 at 11 44 16 am](https://cloud.githubusercontent.com/assets/1571635/16926322/05a7367e-4cdd-11e6-83dc-ecbba696435b.png)
