### ISSUE TITLE
All Levels set to "Default"

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#74]
When creating a multi-level form, each level created is set as the Default. Changing that is impossible.

![screenshot4](https://cloud.githubusercontent.com/assets/930724/6879181/4c0f9ed6-d4ab-11e4-9721-7dabd68d25d2.png)

**Comment by DevinWalker** [comment]
How can I reproduce this?

On Friday, March 27, 2015, Matt Cromwell <notifications@github.com> wrote:

> Assigned #74 <https://github.com/WordImpress/Give/issues/74> to
> @DevinWalker <https://github.com/DevinWalker>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WordImpress/Give/issues/74#event-267406873>.
>


-- 

Devin Walker

Founder & Lead Developer

P:

858-449-6460 <8584496460>

W:

http://wordimpress.com

433 G Street #201
San Diego, CA 92101 <https://goo.gl/maps/BePgp>
<https://www.facebook.com/wordimpressive>  <https://twitter.com/wordimpress>
  <https://plus.google.com/u/0/b/117062083910623146392/+Wordimpress/about>
<http://wordimpress.com/>

**Comment by DevinWalker** [comment]
@mathetos - I can't reproduce this...

**Comment by DevinWalker** [comment]
Closed as per @mathetos request
