### ISSUE TITLE
Stripe live_publishable_key error

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#75]
When activating Stripe Gateway, and inserting the test keys (NOT the live ones), there's a notice on the front-end. Perhaps we could wrap this variable in a conditional check for the test key, then put a notice in the checkout to say "These Payments will not be processed".

`Notice: Undefined index: live_publishable_key in ...\wp-content\plugins\give-stripe\give-stripe.php on line 1501`

**Comment by DevinWalker** [comment]
This has been fixed
