### ISSUE TITLE
Add grumphp development workflow

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#750]
I want to suggest that we can add [grumphp](https://github.com/phpro/grumphp) to our workflow and with this tool we can maintain code quality.

**For example:**
I am using it and I saw WordPress Coding Standard violation in most of file. If you setup php code_sniffer with Grumphp then Grumphp automatically start sniffing every file in commit and notify you if any violation occur.

![grump-php-code-sniffer](https://cloud.githubusercontent.com/assets/1784821/16938413/462c5a18-4d95-11e6-8aa0-69bc98514286.gif)

**Comment by ravinderk** [comment]
**Steps to setup Grumphp**
I am assuming that you already installed composer

1. Install grumphp by composer (globally)
`composer require --dev phpro/grumphp`
https://github.com/phpro/grumphp

2. Install php_codesniffer (globally)
`composer global require "squizlabs/php_codesniffer=*"`

3. Install Wordpress Coding Standard
This blog post has all step to install composer, php_codesniffer and wordpress coding standard https://tommcfarlin.com/php-codesniffer-with-composer/

4. After finishing above steps then you have create `grumphp.yml` file in root directory where you installed git. You can also run `grumphp configure` which will ask you few questions to create your `grumphp.yml` file.
You can check demo `grumphp.yml`  file here:
https://github.com/phpro/grumphp#configuration
This is my `grumphp.yml` file: https://gist.github.com/ravinderk/ac4a733bc7ed01ce8d1a3f1f3c0b3fbd

5. After creating grumphp file , you have to run `grumphp git:init` command to complete setup.
After this grumphp will start sniffing your each commits and run tasks which you setup in `grumphp.yml` file.

**Note** If want to ignore grumphp tasks for any commit then you have to append `-n` or `--no-verify` to git commit command `git commit -m "your_message" -n `

**Comment by DevinWalker** [comment]
@ravinderk for number 4 above - can we include the `gumphp.yml` file in Give's root directory?

**Comment by ravinderk** [comment]
As discuss with @DevinWalker we can also use [`codeclimate`](https://codeclimate.com/oss) which is free for open source projects and have large list of integration with other tools.
https://docs.codeclimate.com/docs

**Comment by DevinWalker** [comment]
We're already using Travis-CI - We are also using Scrutinizer and WordPress Coding Standards. We can add in code climate, but I don't think it's a must have since it reports similar issues to Scrutinizer: https://codeclimate.com/github/woocommerce/woocommerce/issues
