### ISSUE TITLE
Export Donation History no longer has Form Title and also has unnecessary columns

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#757]
Somehow this commit: https://github.com/WordImpress/Give/issues/414 reverted the improvements to the Export made in this commit: https://github.com/WordImpress/Give/issues/314 

Just tested from version 1.3.1 until 1.4.5 the Form Title appeared correctly with the "Export Donation History - Download a CSV of all donations recorded" report. But with 1.5 and the new Date Range feature, the Form Title.

**VERSION 1.4.5**
![export-history-1-4-5-correct](https://cloud.githubusercontent.com/assets/930724/16960954/499ca21a-4da0-11e6-89d5-97db8b3a3862.png)

**VERSION 1.5+**
![export-history-1-5-3-wrong](https://cloud.githubusercontent.com/assets/930724/16960957/4ddbb7c6-4da0-11e6-9ead-e43274021180.png)

**Comment by Benunc** [comment]
I was about to repot that I had a "products" column that seemed out of place.
