### ISSUE TITLE
Bug related to i18n esc_attr__ usage

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#759]
This link tag is displaying incorrectly:

![screen shot 2016-07-19 at 11 15 02 am](https://cloud.githubusercontent.com/assets/1571635/16961390/2381f5c4-4da2-11e6-97c6-5b92c724c585.png)

![screen shot 2016-07-19 at 11 14 54 am](https://cloud.githubusercontent.com/assets/1571635/16961387/2020ed5e-4da2-11e6-9a0f-1a931793427c.png)

**Comment by ramiy** [comment]
Fix: https://github.com/WordImpress/Give/pull/760
