### ISSUE TITLE
Input mask for credit card fields

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#76]
Would be nice to do an input mask for the credit card number and CVV fields for the Gateway add-ons.

**Comment by DevinWalker** [comment]
@mathetos got any library recommendations? This one looks good but would require us to do some more significant changes to how the CC js is handled https://github.com/jondavidjohn/payform#api

**Comment by DevinWalker** [comment]
Removing the 1.1 milestone from this one

**Comment by mathetos** [comment]
Actually, went down a bit of a rabbit hole just now and found this repo that says two things:
1) Don't use input masks AT ALL because they are horrible for accessibility (makes sense). See their links for references
2) Instead, do auto-spaces, which is what this repo is all about. Worth looking into for sure:
https://github.com/filamentgroup/politespace

**Comment by mathetos** [comment]
Sorry, related and perhaps a much leaner alternative: https://github.com/bradfrost/labelmask

**Comment by pryley** [comment]
What about something like this: http://jessepollak.github.io/card/

**Comment by DevinWalker** [comment]
Woah that's pretty awesome. I think that should be an Add-on... it's not really applicable for everyone. Some may like that eye candy while others may not. Also, how's it perform cross-device/mobile?

**Comment by pryley** [comment]
While it works on mobile, you probably wouldn't the card image to display on smaller screens. 
Also it looks like it is only IE10+

However, the input mask functionality could probably be replicated fairly easily.

**Comment by pryley** [comment]
Stripe has a general purpose library for building credit card forms, validating inputs and formatting numbers. https://github.com/stripe/jquery.payment

http://jessepollak.github.io/card/ uses a forked version of that library that converts it to vanilla javascript. 
https://github.com/jessepollak/payment
