### ISSUE TITLE
Link the donation # for period to the log for easy user viewing of actual donations for specified period

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#774]
This will be the good feature from the user perspective if **Total donations for period shown**  count link to a query which will take the user to a page ( donations page ) where the user can view total transaction in that period.

<img width="545" alt="screen shot 2016-07-20 at 11 10 47 am" src="https://cloud.githubusercontent.com/assets/1784821/16976186/b50a9230-4e6a-11e6-8a35-fa479ca7f433.png">

**Comment by DevinWalker** [comment]
Yeah that's a nice feature

**Comment by ravinderk** [comment]
Closing this issue in favor of https://github.com/WordImpress/Give/issues/1527 (redesign Report UI)
