### ISSUE TITLE
esc_html doesn't expect a textdomain

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#781]
The WP core function `esc_html` only expects one parameter yet we are passing two with the text domain here: https://github.com/WordImpress/Give/blob/release/1.6/includes/scripts.php#L254%23L271

I believe https://codex.wordpress.org/Function_Reference/esc_html_2 should be used in place.

Please check uses of `esc_html` due to merge of #776

**Comment by ramiy** [comment]
Good catch!

**Comment by DevinWalker** [comment]
Resolved with PR merge #811
