### ISSUE TITLE
Transaction Status Bulk Change not reflected

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#79]
I changed these statuses with the "Bulk Action" tool, the icon went grey and there is no Status text now. And when I click on "View Details" it shows the old status but the icon is grey.
![transactions-bulk-change-no-status](https://cloud.githubusercontent.com/assets/930724/6972437/9149bc2a-d938-11e4-9ca2-91843a759460.png)

**Comment by DevinWalker** [comment]
@mathetos I just tried to reproduce this and was not able to. Can you please pull down the latest code and try to reproduce again in at least two separate environments?

**Comment by DevinWalker** [comment]
Closing until @mathetos can reproduce

**Comment by mathetos** [comment]
Just emailed you another example of this after I reproduced it on a live site.

**Comment by DevinWalker** [comment]
@mathetos for some reason I still can't reproduce this anywhere. I want to get this issue closed out so let's see if we can figure this out ASAP - if you could take a stab at it, even better.

**Comment by DevinWalker** [comment]
I'm going to move this from the 0.9 Milestone until we can figure out how to reproduce it.

**Comment by DevinWalker** [comment]
Assigning back to you @mathetos until you can reproduce it :+1:
