### ISSUE TITLE
mod_security flagging our icomoon font

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#794]
Not clear whether this is a real issue or not yet. We'll need to replicate an environment with mod_security and get the ruleset that includes this trigger, but see details reported by this user here:
https://wordpress.org/support/topic/give-plugin-with-icomoon-triggers-modsecurity?replies=1

**Comment by DevinWalker** [comment]
I've seen several reports and I'm looking into this.

**Comment by DevinWalker** [comment]
It looks like this issue cropped up again because the `ttf` font was brought back in when we updated our icon fonts.
