### ISSUE TITLE
Include the Icomoon JSON file in Github repo

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#795]
We need to include the JSON file for our icomoon icons so that we can easily update the iconset whenever we need to.

**Comment by mathetos** [comment]
But I think it should be excluded from distribution.

**Comment by DevinWalker** [comment]
@mathetos do you have that file handy?

**Comment by mathetos** [comment]
Sorry, thought I updated this ticket. We don't actually need the JSON file. You can upload directly to Icomoon with the SVG file: /give/assets/fonts/icomoon.svg
