### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error (/libraries/cmb2/)

### ISSUE THREAD

**Issue by cmwwebfx** [WordImpress/Give#80]
Hi Devin,

Went to install this morning, and received a fatal warning when trying to activate.

Warning: require_once(__DIR__/libraries/cmb2/init.php) [function.require-once]: failed to open stream: No such file or directory in /home/a-web/ac/9c/foundationbarossa.org.au/public/www/wp-content/plugins/Give-master/includes/admin/register-settings.php on line 813

Fatal error: require_once() [function.require]: Failed opening required '__DIR__/libraries/cmb2/init.php' (include_path='.:/usr/local/lib/php/__applications/:/home/chroot_bind/php/php5/usr/local/lib/php/') in /home/a-web/ac/9c/foundationbarossa.org.au/public/www/wp-content/plugins/Give-master/includes/admin/register-settings.php on line 813

plugins that are active at the time of installation in Screenshot below.

![screen shot 2015-04-07 at 9 09 09 am](https://cloud.githubusercontent.com/assets/1312880/7014585/dafd1a08-dd05-11e4-9ab1-c12e64e1668e.png)

**Comment by DevinWalker** [comment]
@cmwwebfx thanks for reporting - I believe I know the issue here... will be coming out with a commit soon to patch it up :]

**Comment by cmwwebfx** [comment]
Thank s Devin, I will continue to feed any bug reports or feedback once I can get this going on the site. Do you need live login details of the site to help in troubleshooting?

**Comment by DevinWalker** [comment]
Hey @cmwwebfx are you using PHP 5.2? Looks like your fatal error is due to "__DIR__" magic constant - which was added in PHP 5.3. I'm updating the code now, because a lot of people are using PHP 5.2 still - but I just want to confirm that's the version you are using.

**Comment by DevinWalker** [comment]
Ok @cmwwebfx as of 38307a49cde08b2dfb47c0b24a890d0d712635d8 you should be all set... would you mind confirming?

**Comment by DevinWalker** [comment]
Closing this out for now - will reopen if @cmwwebfx confirms issue is not fixed

**Comment by cmwwebfx** [comment]
Hi Devin

Appologies for delay. Was in weekly WIP. Yes the version of PHP on this host is 5.2 unfortunately.

I have amended the line 813 as directed, and this allows for the plugin to be activated. 

The site now throws a new warning message.

Warning: is_readable() [function.is-readable]: open_basedir restriction in effect. File(/languages/en_US.mo) is not within the allowed path(s): (VIRTUAL_DOCUMENT_ROOT:/home/chroot_bind/php/php5/usr/local/lib/php/) in /home/a-web/ac/9c/foundationbarossa.org.au/public/www/wp-includes/l10n.php on line 476

Screenshots attached.

![screen shot 2015-04-07 at 1 00 52 pm](https://cloud.githubusercontent.com/assets/1312880/7016601/cc1ee978-dd26-11e4-942c-244ef9659da2.png)

![screen shot 2015-04-07 at 1 00 13 pm](https://cloud.githubusercontent.com/assets/1312880/7016607/d7210540-dd26-11e4-93ae-62e3827659ec.png)

![screen shot 2015-04-07 at 1 03 03 pm](https://cloud.githubusercontent.com/assets/1312880/7016604/cf6c39f0-dd26-11e4-8838-4423441d8872.png)

**Comment by DevinWalker** [comment]
Yikes - looks like some pretty restrictive hosting there... I did some research and it looks like it's primarily hosting related: https://wordpress.org/support/topic/warning-is_readable-functionis-readable-open_basedir-restriction-in-effec

https://wordpress.org/support/topic/plugin-google-maps-via-store-locator-plus-warning-is_readable-functionis-readable-open_basedir-restriction-in-effec

https://theme-fusion.com/knowledgebase/getting-php-is_readable-warning/

Do you have any idea if this is an MS IIS server? If this is a plugin related issue I'd love to resolve it, I'm just not sure how as I've never seen it before and all Google seems to be saying is it's the host. Any insight is appreciated.

**Comment by cmwwebfx** [comment]
Very likely it is a hosting issue as it is on an old server. Then again, many sites are sitting on old servers like this one.

The server is not an MS IIS setup. Here is the text clip of the server settings using Gravity Forms Server Tool:


[OK]     BackupBuddy Version   =   5.2.0.5
[OK]     WordPress Version   =   4.1.1
[OK]     MySQL Version   =   5.5.39
[OK]     AddHandler in .htaccess   =   none, n/a
[OK]     PHP Version   =   5.2.17-pl0-gentoo
[OK]     PHP max_execution_time (server-reported)   =   30
[OK]     PHP Memory Limit   =   256M
[OK]     PHP Error Logging (log_errors)   =   enabled [Test]
[OK]     PHP Error Log File (error_log)   =   /var/log/php_log
[OK]     PHP Display Errors to Screen (display_errors)   =   enabled
[WARNING]     Zip Methods   =   ziparchive, pclzip  
[OK]     Database Dump Methods   =   php
[OK]     Site Size   =   Unknown  
[OK]     Site Size (Default Exclusions applied)   =   Unknown  
[OK]     Site number of files   =   Unknown  
[OK]     Site number of files (Default Exclusions applied)   =   Unknown  
[OK]     Database Size   =   0 MB  
[OK]     Database Size (Default Exclusions applied)   =   0 MB  
[OK]     Average Write Speed   =   2.49 MB/sec
[OK]     Guesstimate of max ZIP size   =   74.62 MB
[WARNING]     Http Loopbacks   =   disabled (enable alternate cron) Hover for details
[OK]     wp-cron.php Loopbacks   =   enabled Hover for details
[OK]     Loopback Domain & IP   =   foundationbarossa.org.au => 117.104.160.130
[OK]     WordPress Cron   =   enabled
[OK]     WordPress Alternate Cron   =   disabled (default)
[OK]     Disabled PHP Functions   =   (none)
[FAIL]     PHP Register Globals   =   enabled
[WARNING]     PHP Magic Quotes GPC   =   enabled
[OK]     PHP Magic Quotes Runtime   =   disabled
[OK]     PHP Safe Mode   =   disabled
[OK]     PHP API   =   apache2handler
[OK]     PHP Architecture   =   64-bit
[OK]     Http Server Software   =   Apache
[OK]     Server Load Average   =   0
[OK]     PHP SSH2, SFTP Support   =   no, no
[OK]     WordPress ABSPATH   =   /home/a-web/ac/9c/foundationbarossa.org.au/public/www/
[OK]     Operating System   =   Linux (Linux n3-sac1.ilisys.net 3.8.13-gentoo #9 SMP Fri Jul 12 17:18:03 EST 2013 x86_64)
[OK]     Active WordPress Plugins   =   gravityforms/gravityforms.php, Give-master/give.php, backupbuddy/backupbuddy.php, better-wp-security/better-wp-security.php, contact-form-7-autoresponder-addon-plugin/cf7_autoresponder_addon.php, contact-form-7/wp-contact-form-7.php, genesis-simple-edits/plugin.php, gravityformsmailchimp/mailchimp.php, gravityformspaypal/paypal.php, many-tips-together/many-tips-together.php, new-royalslider/newroyalslider.php, pixgridder-pro/pixgridder.php, wordpress-seo/wp-seo.php
[OK]     PHP Process User (UID:GID)   =   www (80:80)

**Comment by DevinWalker** [comment]
@cmwwebfx very good point. Is this a test server I could get in and debug on? Otherwise I'll have to spin up a vm with php 5.2

**Comment by DevinWalker** [comment]
The log is helpful BTW

**Comment by cmwwebfx** [comment]
Unfortunately this is a live site and the client was adamant that it was to go on this server.

**Comment by DevinWalker** [comment]
Ok I'll see what I can do about this... I've created a new issue for this: https://github.com/WordImpress/Give/issues/82
