### ISSUE TITLE
Allow developers to add a custom logo image to "Export PDF of Donations and Income"

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#802]
We can add filter to code to add custom image, x axis position and y axis position.

<img width="815" alt="screen shot 2016-07-26 at 10 34 20 am" src="https://cloud.githubusercontent.com/assets/1784821/17126886/efcd9698-531e-11e6-8883-c691b57e36ba.png">

<img width="1221" alt="screen shot 2016-07-26 at 10 50 14 am" src="https://cloud.githubusercontent.com/assets/1784821/17126872/c49ba74e-531e-11e6-9c58-13c5d0551aaa.png">

**Comment by DevinWalker** [comment]
This is a simple filter addition so I'm adding it to 1.6 release
