### ISSUE TITLE
Encoded HTML and long form titles are going outside of select field in shortcode generator panel

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#804]
<img width="589" alt="screen shot 2016-07-26 at 12 34 56 pm" src="https://cloud.githubusercontent.com/assets/1784821/17128951/b31904d0-532d-11e6-8c9e-7c4342f4f5b7.png">

**Comment by DevinWalker** [comment]
Encoded HTML is also displaying: 
![screen shot 2016-07-28 at 3 56 08 pm](https://cloud.githubusercontent.com/assets/1571635/17232296/dd04abb4-54db-11e6-9f41-4b987d18453c.png)
