### ISSUE TITLE
Allow developers to skip gateways by filter when changing pending payments to abandon payments

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#809]
Currently we are only skipping `offline` donation status and it is hard coded in give core while marking `pending` payment status as `abandoned` (for any payment gateway except `offline` ). We can add a `filter` here to allow developers to add there own payment status to skip
https://github.com/WordImpress/Give/blob/release/1.6/includes/payments/actions.php#L215

As discussed with @DevinWalker filter name will `give_mark_abandoned_donation_gateways`

**Comment by DevinWalker** [comment]
@ravinderk can you make it  `give_mark_abandoned_donation_statuses` (minus an s)

**Comment by DevinWalker** [comment]
Fixed with merge above.
