### ISSUE TITLE
Add check for TLS 1.2 support 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#810]
## Issue Overview

TLS 1.2 support is being required by a lot of gateways now and we need to add a check to our system status.

*\* Links of Interest **
- SSL and TLS Protocol versions: https://www.wolfssl.com/wolfSSL/Blog/Entries/2010/10/7_Differences_between_SSL_and_TLS_Protocol_Versions.html
- WordPress TLS 1.2 Compatibility Test: https://wordpress.org/plugins/tls-1-2-compatibility-test/

**Comment by amjad** [comment]
This is required by our gateway as well. Before Oct 2017.
