### ISSUE TITLE
Css conflict appear when users see receipt in browser & admins preview emails in wp-admin

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#818]
I have `twentyfifteen` theme activated and when i saw donation receipt in browser then css conflict appear and also we are using `wp_head` and `wp_footer` function on this template which cause of loading extra css and js files which we do not need.
We only need `give.css` file on this template. Instead of using `wp_head` and `wp_footer`, we can add  custom action hook `do_action('give_receipt_head')` `do_action('give_receipt_footer');`

**Before:**
<img width="587" alt="screen shot 2016-07-28 at 6 54 22 pm" src="https://cloud.githubusercontent.com/assets/1784821/17214088/eb505bd2-54f4-11e6-9021-7447885c6c61.png">

<img width="1156" alt="screen shot 2016-07-28 at 6 49 45 pm" src="https://cloud.githubusercontent.com/assets/1784821/17213952/50304518-54f4-11e6-99b6-a664d552b35c.png">

**After**
<img width="581" alt="screen shot 2016-07-28 at 6 55 40 pm" src="https://cloud.githubusercontent.com/assets/1784821/17214096/f144cadc-54f4-11e6-8709-76deac6f25dd.png">

<img width="1136" alt="screen shot 2016-07-28 at 6 49 17 pm" src="https://cloud.githubusercontent.com/assets/1784821/17214028/aa2d08bc-54f4-11e6-904c-7bd4b74e2f1e.png">

**Function after update**
```
/**
 * Render Receipt in the Browser.
 *
 * A link is added to the Donation Receipt to view the email in the browser and
 * this function renders the Donation Receipt in the browser. It overrides the
 * Purchase Receipt template and provides its only styling.
 *
 * @since  1.0
 */
function give_render_receipt_in_browser() {
	if ( ! isset( $_GET['payment_key'] ) ) {
		wp_die( esc_html__( 'Missing donation payment key.', 'give' ), esc_html__( 'Error', 'give' ) );
	}

	$key = urlencode( $_GET['payment_key'] );

	ob_start();
	//Disallows caching of the page
	header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
	header("Cache-Control: no-store, no-cache, must-revalidate"); // HTTP/1.1
	header("Cache-Control: post-check=0, pre-check=0", false);
	header("Pragma: no-cache"); // HTTP/1.0
	header("Expires: Sat, 23 Oct 1977 05:00:00 PST"); // Date in the past
	?>
	<!DOCTYPE html>
	<html lang="en">
		<head>
			<title><?php esc_html_e( 'Donation Receipt', 'give' ); ?></title>
			<meta charset="utf-8" />

			<!-- Further disallowing of caching of this page -->
			<meta charset="utf-8" />
			<meta http-equiv="cache-control" content="max-age=0" />
			<meta http-equiv="cache-control" content="no-cache" />
			<meta http-equiv="expires" content="0" />
			<meta http-equiv="expires" content="Tue, 23 Oct 1977 05:00:00 PST" />
			<meta http-equiv="pragma" content="no-cache" />
			<meta name="robots" content="noindex, nofollow" />
			<link rel="stylesheet" href="<?php echo esc_url( give_get_stylesheet_url() ); ?>?ver=<?php echo GIVE_VERSION; ?>">

			<?php do_action('give_receipt_head'); ?>
		</head>
		<body class="<?php echo apply_filters( 'give_receipt_page_body_class', 'give_receipt_page' ); ?>">

			<div id="give_receipt_wrapper">
				<?php do_action( 'give_render_receipt_in_browser_before' ); ?>
				<?php echo do_shortcode( '[give_receipt payment_key=' . $key . ']' ); ?>
				<?php do_action( 'give_render_receipt_in_browser_after' ); ?>
			</div>

            <?php do_action('give_receipt_footer'); ?>
        </body>
	</html>
	<?php
	echo ob_get_clean();
	die();
}
```

**Comment by DevinWalker** [comment]
The same should also be done for previewing emails https://github.com/WordImpress/Give/blob/master/includes/emails/template.php#L285

**Comment by DevinWalker** [comment]
Sorry, that's actually one in the same...

**Comment by DevinWalker** [comment]
Fixes as of 11214baa66142f0a4f800c20bd913af46ecafd9d

**Comment by ravinderk** [comment]
@DevinWalker did you enqueue give stylesheet [ I suggested custom function for that `give_get_stylesheet_url()` ]

`<link rel="stylesheet" href="<?php echo esc_url( give_get_stylesheet_url() ); ?>?ver=<?php echo GIVE_VERSION; ?>">`

**Comment by DevinWalker** [comment]
Good call @ravinderk

**Comment by DevinWalker** [comment]
@ravinderk check out https://github.com/WordImpress/Give/pull/838 and specifically: https://github.com/WordImpress/Give/blob/release/1.6/includes/scripts.php#L146
