### ISSUE TITLE
Accessibility Headings

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#820]
See: https://make.wordpress.org/plugins/2015/08/03/4-3-change-to-plugin-dashboard-pages/
and: https://core.trac.wordpress.org/ticket/31650

We need to update give.

**Comment by ramiy** [comment]
https://github.com/WordImpress/Give/pull/819/commits/ab453d70389bdb45f1decb3cb5ddb895e6e1f825
https://github.com/WordImpress/Give/pull/819/commits/feb0cc86ff565aaddc87c276e8e9167d6a759d29

**Comment by ramiy** [comment]
Also, at the end of the year, we will need to apply this change: https://core.trac.wordpress.org/ticket/37257

**Comment by ramiy** [comment]
@DevinWalker, you can tag this as `a11y` and `UI/UX`. Add 1.6 milestone. And close the issue. PR https://github.com/WordImpress/Give/pull/819 was merged.

**Comment by DevinWalker** [comment]
Yep, thanks for the reminder @ramiy
