### ISSUE TITLE
Add more context to system info page

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#826]
When a user submits a system info file, it would be great to get significantly more information from them.

Useful bits we could add:

Is Email access enabled?
Are Admin donation notification emails disabled?
Have license Keys been entered in for Add-ons?

**Comment by Benunc** [comment]
Also, adding in the error logs (which the user can see at Donations > Reports > Logs would be HUGE.

**Comment by mathetos** [comment]
@Benunc I like the idea of making it easier for users to provide us with details about their setup. But cramming that all into the System Info text file is a bit much I think.

What if we did this instead:
1) Provide a "Import/Export Settings" function -- this would also be great for them to be able to duplicate their settings on another site.
2) Provide an "Export Logs" function on the Logs tab as well.

I know that means they have to do multiple exports and uploads to the ticket, but I think the separation, keeping each text file focused on its core purpose is important.

@DevinWalker what's your thoughts?

**Comment by DevinWalker** [comment]
I like what WooCommerce does. Here is a screenshot of their "System Settings":

![woocommerce status give development wordpress](https://cloud.githubusercontent.com/assets/1571635/19788573/f654ce40-9c5d-11e6-986c-8d0e141343a8.png)

Notice there are sections in metaboxes nicely laid out for:

- WordPress Environment
- Server Environment
- Active Plugins
- Settings (not all of them)
- API
- Template overrides

Also, when you click on the "Get System Report" you can copy and paste it in a ticket:

![2016-10-27_15-57-48](https://cloud.githubusercontent.com/assets/1571635/19788579/0a164bc0-9c5e-11e6-9522-8d7747eadd70.png)

**Comment by DevinWalker** [comment]
## NEW System Status Fields

**WordPress Environment**

All the ones from Woos minus the ones that are specific to Woo like "Log Directory Writable" 

Be sure to merge in our additional WP specs like "Permalink Structure",  "Registered Post Stati", "Admin AJAX", etc.

**Server Environment**
All of Woos, plus add ours in there.

- [ ] Remove "User Browser" section and corresponding library we are using for it: https://github.com/WordImpress/Give/blob/master/includes/libraries/browser.php

**Comment by mathetos** [comment]
Would love to see that and even add admin alerts for things like PHP versions that are less than 5.3, or cURL less than 7.40 since those always create trouble.

Also really like having it look nice and presentable rather than the plain text.
