### ISSUE TITLE
Feature Request: Private Donation Checkbox

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#83]
Add a checkbox during donation payment process that requests a donation be private (not displayed at all on frontend). 

1. Need conditional function to return true/false whether user has selected option

- Ensure User info ie, name, Gravatar, etc. is never shown on frontend.

**Comment by cmwwebfx** [comment]
Good work team.

**Comment by DevinWalker** [comment]
:+1: thank you!

**Comment by BoweFrankema** [comment]
Great to see this make it into the plugin!  When I did a crowdfunding project I was surprised to see over 25% of the donations were anonymous. It's an important thing to add!

**Comment by ibndawood** [comment]
:+1. This is definitely a must for charities. A lot of people do not want their left hands know what their right hand is doing.

@DevinWalker , Is there a method already to display the donor's list in the front end (like for example: http://www.gofundme.com/uenr3b2a )  ? I don't see a requirement for this feature unless we are displaying the donors list in the front-end.

**Comment by DevinWalker** [comment]
We have a Gravatar list functionality that I want to expand into a widget similar to: 

Check out https://github.com/WordImpress/Give/blob/a2213463b45e6eba71086ab430154278d1a25d5b/includes/payments/class-donators-gravatars.php

![donation-widget](https://cloud.githubusercontent.com/assets/1571635/7755122/c804655a-ffa6-11e4-9e2a-5505bafba469.png)

So this feature will definitely be a requirement

**Comment by DevinWalker** [comment]
I'm removing this from the 1.0 milestone and adding it to the 1.1

**Comment by DevinWalker** [comment]
Pushing out again to 1.2

**Comment by mathetos** [comment]
Let's make this a priority soon. Really very often requested.

**Comment by DevinWalker** [comment]
Yeah I agree it needs to be out soon.

**Comment by DevinWalker** [comment]
Hate to do this... but I gotta push this milestone again.

**Comment by DevinWalker** [comment]
Duplicate, closing in favor of #17
