### ISSUE TITLE
Thumbnail Display Options

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#833]
We need to add display options for the donation form thumbnail.

Two options I want to see:
- **Display Thumbnail** - to show / hide the thumbnail.
- **Thumbnail Location** - Left Side, Right Side, Top (above the form)

Currently, the plugin forces me to use the default display. With the new options, the user will have more control over the donation page.

**Comment by mathetos** [comment]
@ramiy You mean per form options? We do have Global options to show/hide and to choose the thumbnail size. But we don't have any options at all for the location.

**Comment by ramiy** [comment]
Yes @mathetos, I was talking per form.

I was thinking to add a new metabox for the Thumbnail Settings.

When creating new donation forms, the metabox will use the default setting defined in **Settings** > **Display Options** > **Disable Form Featured Image**. If the user changes the global settings, it wont affect the existing forms. The global display settings affect only new donation forms.

**Comment by mathetos** [comment]
Sounds great! But I wouldn't add a new metabox to the Form edit screen. Instead I would add your thumbnail settings into the exiting "Form Content" metabox. Currently it only has options for the text content, but the thumbnail is technically also "content".

Ideally though, it would be BEST to add those settings into the Featured Image metabox directly. But I've never seen a best practices way to add additional settings into an existing Core metabox. But from a user perspective, they are already thinking about the featured image when in that box, so adding the settings there would be ideal.

**Comment by ramiy** [comment]
I agree, its better to add those new fields directly to the **Featured Image** metabox. It's not hard. We can add new fields to the metabox using **admin_post_thumbnail_html** filter. And save the custom field data using **save_post** action.

I think I'll write a post about this. With screenshots. :-)

**Comment by mathetos** [comment]
That'd be great!

**Comment by ramiy** [comment]
![give-featured-image](https://cloud.githubusercontent.com/assets/576623/17453324/d0704d56-5b82-11e6-957b-b8472c5482a3.png)

feedback?

**Comment by ramiy** [comment]
I created two fields (checkbox and select). The second has 3 options: Right, Left, Above.

Maybe we can combine the two fields into one?

**Display Featured Image**: None, Left, Right, Above

**Comment by ramiy** [comment]
![give-featured-image2](https://cloud.githubusercontent.com/assets/576623/17453753/e1327bda-5b89-11e6-8b61-8f08302cf4a6.png)

**Comment by ramiy** [comment]
Here is the code to add custom fields to metabox:

```
function add_featured_image_display_settings( $content, $post_id ) {

	// Make sure we affect only 'give_forms' post type
	if ( 'give_forms' != get_post_type( $post_id ) )
		return $content;

	// Add 'featured_image_display' field
	$field_id    = 'featured_image_display';
	$field_value = esc_attr( get_post_meta( $post_id, $field_id, true ) );
	$field_text  = esc_html__( 'Display featured image.', 'give' );
	$field_state = checked( $field_value, 1, false);
	$field_label = sprintf(
	    '<p><label for="%1$s"><input type="checkbox" name="%1$s" id="%1$s" value="%2$s" %3$s> %4$s</label></p>',
	    $field_id, $field_value, $field_state, $field_text
	);
	$content = $content . $field_label;

	// Add 'featured_image_location' field
	$field_id    = 'featured_image_location';
	$field_value = esc_attr( get_post_meta( $post_id, $field_id, true ) );
	$field_text  = esc_html__( 'Display Image:', 'give' );
	$field_label = '<p>';
	$field_label .= '<label for="' . $field_id . '">' . $field_text . '</label> ';
	$field_label .= '<select id="' . $field_id . '" name="' . $field_id . '">';
	$field_label .= '<option value="" '      . selected( $field_value, '',      false ) . '> ' . esc_html__( 'Hide Image',        'give' ) . '</option>';
	$field_label .= '<option value="right" ' . selected( $field_value, 'right', false ) . '> ' . esc_html__( 'Right Side',        'give' ) . '</option>';
	$field_label .= '<option value="left" '  . selected( $field_value, 'left',  false ) . '> ' . esc_html__( 'Left Side',         'give' ) . '</option>';
	$field_label .= '<option value="above" ' . selected( $field_value, 'above', false ) . '> ' . esc_html__( 'Above the Content', 'give' ) . '</option>';
	$field_label .= '</select>';
	$field_label .= '</p>';
	$content     = $content . $field_label;

	// Return content
	return $content;

}
add_filter( 'admin_post_thumbnail_html', 'add_featured_image_display_settings', 10, 2 );



function save_featured_image_display_settings( $post_ID, $post, $update ) {

	// Make sure we affect only 'give_forms' post type
	if ( 'give_forms' != get_post_type( $post_ID ) )
		return;

	// Update 'featured_image_display' field
	$field_id    = 'featured_image_display';
	$field_value = isset( $_REQUEST[ $field_id ] ) ? 1 : 0;
	update_post_meta( $post_ID, $field_id, $field_value );

	// Update 'featured_image_location' field
	$field_id    = 'featured_image_location';
	$field_value = isset( $_REQUEST[ $field_id ] ) ? $_REQUEST[ $field_id ] : '';
	update_post_meta( $post_ID, $field_id, $field_value );

}
add_action( 'save_post', 'save_featured_image_display_settings', 10, 3 );
```

**Comment by mathetos** [comment]
That looks great. Agree that one option instead of two is better. With the "none" option they an still have a featured image for social media purposes, but not have to display it on the page (fringe case, but I can see some people appreciating that capability).

Let's do it!

**Comment by ramiy** [comment]
https://generatewp.com/add-custom-fields-to-featured-image-meta-box/

**Comment by ravinderk** [comment]
@DevinWalker @mathetos 
Can you explain following questions:

1. Currently, Featured image is directly connected to `Give sidebar` which means featured image will not show on frontend and form will contain full width if `Single Form Sidebar` disabled even if `Form Featured Image` is enabled which can confuse the user.

2. If we implement new settings then what will happen to `Give Sidebar`, if user select:
    1. `Right` featured image position.
    2. `Above The Form` featured image position.

**Comment by DevinWalker** [comment]
@ravinderk I've thought about this more and now feel it's best to leave this option out. The ability to adjust placement of the featured image is entirely possible if you customize the template files. That's why we have the template files overrides. If we start going down the road of allowing users to adjust layouts within the form creation experience, where does it end?  This functionality is better as a snippet or small feature plugin: https://github.com/WordImpress/Give-Snippet-Library
