### ISSUE TITLE
Multiple donations don't display in reports or on the forms fields

### ISSUE THREAD

**Issue by natewilldo** [WordImpress/Give#85]
See screenshots below. 3 donations have been made but none are showing up on the form and only 1 is showing up on the report.
![image](https://cloud.githubusercontent.com/assets/5235216/7073321/dee3c1ac-deaf-11e4-881f-5dbf93aa593e.png)
![image](https://cloud.githubusercontent.com/assets/5235216/7073335/fa1521a0-deaf-11e4-8aa4-f5be7d2fd6a5.png)
![image](https://cloud.githubusercontent.com/assets/5235216/7073357/1631412a-deb0-11e4-91f0-447cd79f565b.png)

**Comment by DevinWalker** [comment]
Hey @natewilldo the reports store a temporary transient to store the report data. Quick question, how long did you wait before checking the reports? Can you try installing - https://wordpress.org/plugins/artiss-transient-cleaner/

**Comment by natewilldo** [comment]
As of right now it's been over an hour with the same results. I'll try the plugin you are suggesting.

**Comment by natewilldo** [comment]
That seemed to correct the report issue but the form is still showing 0 transactions and $0.00 income.

**Comment by DevinWalker** [comment]
Thanks for checking, reviewing now

**Comment by DevinWalker** [comment]
Ok here's what I'm thinking - You're testing the plugin in test mode:

1. Right now the columns only display LIVE transactions - test donations will not display here
2. Reports WILL show the test donations 

... this is a bit confusing. The reports and columns need to update completely when switching from test mode to live.

**Comment by natewilldo** [comment]
That sounds like what could be happening

**Comment by mathetos** [comment]
Maybe we should consider a "Test Donation" status for this purpose?

**Comment by ibndawood** [comment]
Hello @DevinWalker ,

Thank you for your wonderful plugin. I encountered this issue and was stuck for 2 hours digging into the code till I came across this post. From what I've seen in the code, here is what I propose:

We can have 2 additional meta fields for all `_give_form_sales_test` and `_give_form_earnings_test` that would save when test mode is enabled. 

Do you think it is a proper approach ? I am willing to make contributions if you are OK with this approach.

**Comment by DevinWalker** [comment]
Hey @ibndawood - can you further describe the issue you encountered? I just want to full understand the problem here and your proposed solution. Thanks, looking forward to hearing back!

**Comment by ibndawood** [comment]
Hey @DevinWalker,

This is what I did:

1. I installed the plugin, created a form and made a donation using Test Gateway. It was in **test mode**.
2. When I clicked on "All Forms", the Income was $0.00 and Donations was 0 but I saw the *Transactions* page list my transaction. The *Log* too didn't have the transaction, even though the *Report* had the income registered. It was very confusing.
3. I went through the issue and I noticed you mentioned that only "LIVE" transactions appear in *All Forms* and *Log* page. 

It is confusing to have conflicting data on Transaction and Reports page. I believed it was a bug and went through issues and code base only to notice your comment as well as this piece of code : https://github.com/WordImpress/Give/blob/282ed0cfd775739e6a2a9f7790a947335759cfa7/includes/payments/actions.php#L55

My proposal would be to save the test sales and earnings as a separate meta data. The `Give_Donate_Form` class has methods to increment sales and earnings, we can check for test mode here and increment/decrement to the appropriate meta data.

Let me know what you think.

**Comment by DevinWalker** [comment]
Hey @ibndawood -

Thank you for taking the time to explain the issue to me. Would you be willing to take a stab at that? I'm not sure how soon we could take this on but it is on our radar for 1.1 - your contribution would be greatly appreciated.

**Comment by DevinWalker** [comment]
Also, FYI - @mathetos and me were also talking about how we need to ensure a "Test mode" notice displays on all Give admin pages when the plugin is in test mode. We were going to take care of that this week.

**Comment by ibndawood** [comment]
Thanks @DevinWalker for the info. Yes, I can contribute to this issue with a PR.

**Comment by DevinWalker** [comment]
@ibndawood that would be most appreciated :)

**Comment by mathetos** [comment]
Another place that Test/Live donations need to be separated out:

![2015-07-13 12_57_44-donors give wordpress](https://cloud.githubusercontent.com/assets/930724/8659436/c92b2cf6-295f-11e5-9d06-a67221dd740b.png)

**Comment by DevinWalker** [comment]
Pushing this milestone

**Comment by DevinWalker** [comment]
@mathetos seems like this is related to the transient caching reports. I bet this would be resolved with #210 

...unless there's something else I'm missing here?

**Comment by mathetos** [comment]
Potentially, but it is a bit bothersome overall that Reports and numbers in the backend have a lag like this in general. I understand the performance reasons, just wish this could be automated a bit more.

**Comment by DevinWalker** [comment]
This was fixed with the merge of #210
