### ISSUE TITLE
New decimal option should be a number field with a max of 3

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#862]
Regarding #738 

This setting should instead be a number field with a max of 3. CMB2 doesn't have a number field by default, so we should probably add our own custom field to support the following:
* step
* min
* max

https://www.w3.org/TR/html-markup/input.number.html

**Comment by DevinWalker** [comment]
Hey @mathetos I agree, I would also like to add a password field type. I think this is part of our larger issue to deprecate CMB2 and take control of our fields via https://github.com/WordImpress/Give/issues/991 and shouldn't hold up 1.6.1
