### ISSUE TITLE
Make transaction columns "Donation Form" and "Status" sortable

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#866]
These two columns need to be sortable:

![screenshot at aug 10 16-46-43](https://cloud.githubusercontent.com/assets/1571635/17574966/3c7922c6-5f1a-11e6-9163-a6d700bd88da.png)

**Comment by ramiy** [comment]
You have **Status Links** above the table... :-)

**Comment by ramiy** [comment]
I've played around with the UI, and it looks like it's a very simple fix - only 2 lines of code to add the sorting functionality.

![sorting](https://cloud.githubusercontent.com/assets/576623/17648542/2a58a9e4-6222-11e6-8326-c64585fdc056.png)

**Comment by DevinWalker** [comment]
@ravinderk is saying this isn't working for him, so we're going to QA it together before closing again.
