### ISSUE TITLE
Shorten description strings and link out to documentation

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#876]
The plugin has 1473 translations strings and it's not easy to translate all those strings to other languages. We need to make shorter strings so it's easier to translate.

The field description strings are very long and we can make them shorter and link to our docs for full information.

**Comment by ramiy** [comment]
Making them shorter will help. But still, we have over a thousand strings! It's too much strings. We need to think out-of-the-box.

If you ask me, we need to break the plugin to smaller components. For example, move the **Terms and Conditions** functionality to a separate free addon. Same for the **Taxonomies**, move the  functionality to a separate addon.

The will be a basic CORE plugin. And extra functionality will be available through addons. Less core functionality, faster plugin, less strings.

**Comment by mathetos** [comment]
@ramiy I totally LOVE consolidating the strings so we have less of them, shorter strings and whatnot. But I don't yet agree that having 1000+ strings is automatically a bad thing. Just scanning a few similar plugins, here's the counts:

EDD = 1704
Gravity Forms = 2338
WooCommerce = 4541

While Give is relatively "simple" for a user, it's a very robust plugin and having a good user experience sometimes requires good in-app docs so the user doesn't HAVE to go to our online docs for everything.

Just to re-emphasize. I love efficiency and want better strings and less of them, but not to judge our plugin based on an artificial number of strings.

**Comment by ramiy** [comment]
:-) I'm not judging... constructive criticism.

**Comment by mathetos** [comment]
Appreciate the feedback for sure! It's important, and you're putting us on a great path going forward. Just giving my own perspective as well.
