### ISSUE TITLE
Merge similar translation strings

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#879]
We have over 1000 translation string. Many similar strings can be merged.

**Comment by ramiy** [comment]
![status1](https://cloud.githubusercontent.com/assets/576623/17608500/8d73e474-6035-11e6-8332-4fb421b73f46.png)
![status2](https://cloud.githubusercontent.com/assets/576623/17608507/929dddce-6035-11e6-9730-2108dc2f34e2.png)
![status3](https://cloud.githubusercontent.com/assets/576623/17608517/9e8f1008-6035-11e6-9d8d-aa1323b95a07.png)
![status4](https://cloud.githubusercontent.com/assets/576623/17608519/a208ef88-6035-11e6-91ec-34bff108e49b.png)
![status5](https://cloud.githubusercontent.com/assets/576623/17608521/a48edf74-6035-11e6-851c-f546feaaf9fb.png)

**Comment by ramiy** [comment]
![test-mode](https://cloud.githubusercontent.com/assets/576623/17608529/b605b016-6035-11e6-9266-a8ec34ae0c3a.png)
![total](https://cloud.githubusercontent.com/assets/576623/17608532/b9a1b1c0-6035-11e6-9b2b-56c5ac5801d2.png)
![view](https://cloud.githubusercontent.com/assets/576623/17608533/bc335128-6035-11e6-9a83-541782d41ec1.png)
![optional](https://cloud.githubusercontent.com/assets/576623/17608535/c27ebcfc-6035-11e6-8c71-ffa6f80706fb.png)
![go-back](https://cloud.githubusercontent.com/assets/576623/17608537/c5f08866-6035-11e6-80c9-ac90eba43a38.png)
![getting-started](https://cloud.githubusercontent.com/assets/576623/17608542/c947a328-6035-11e6-9aa3-cd8f8bcef421.png)

**Comment by ramiy** [comment]
![dash1](https://cloud.githubusercontent.com/assets/576623/17608553/e7e4b564-6035-11e6-8782-866a251f4506.png)
![dash2](https://cloud.githubusercontent.com/assets/576623/17608558/eb60117a-6035-11e6-987d-6fa4ae7909d5.png)
![dash3](https://cloud.githubusercontent.com/assets/576623/17608560/ed946ce8-6035-11e6-8a48-a2681672a35b.png)

**Comment by ramiy** [comment]
![amount1](https://cloud.githubusercontent.com/assets/576623/17608567/fde237e2-6035-11e6-9bf8-557eb434e54b.png)
![card](https://cloud.githubusercontent.com/assets/576623/17608569/01823974-6036-11e6-97f7-cfe631b47ed6.png)
![cheating](https://cloud.githubusercontent.com/assets/576623/17608571/03a1003c-6036-11e6-8cd4-f1d33cc14da3.png)
![custom](https://cloud.githubusercontent.com/assets/576623/17608572/067b78aa-6036-11e6-96de-82ca3a401107.png)
![no](https://cloud.githubusercontent.com/assets/576623/17608573/0d8c37ba-6036-11e6-912d-70096adef1d5.png)

**Comment by ramiy** [comment]
![address1](https://cloud.githubusercontent.com/assets/576623/17608577/1690d4ba-6036-11e6-8130-07b86279c4d1.png)
![address2](https://cloud.githubusercontent.com/assets/576623/17608580/1978dc04-6036-11e6-8809-8f7d0435f0f6.png)

**Comment by ramiy** [comment]
![234](https://cloud.githubusercontent.com/assets/576623/17608588/26618d76-6036-11e6-8f63-179f7fd69556.png)
![238](https://cloud.githubusercontent.com/assets/576623/17608592/28dde7e8-6036-11e6-98f7-88e8391c11a9.png)
![245](https://cloud.githubusercontent.com/assets/576623/17608595/2b1affa0-6036-11e6-8896-f013784e1488.png)
![252](https://cloud.githubusercontent.com/assets/576623/17608598/2d2a8126-6036-11e6-9da8-09e9241639f5.png)

**Comment by ramiy** [comment]
![00](https://cloud.githubusercontent.com/assets/576623/17609858/6172ec2e-6041-11e6-9836-76dfdb70a21d.png)
![11](https://cloud.githubusercontent.com/assets/576623/17609861/64bbd742-6041-11e6-8cbb-a6c7039ce405.png)

**Comment by ramiy** [comment]
![select](https://cloud.githubusercontent.com/assets/576623/17610012/b7b6da9a-6042-11e6-90c0-65583c2d060c.png)

**Comment by DevinWalker** [comment]
Yes!!! 👍

**Comment by ramiy** [comment]
@DevinWalker  What do you think about this change:

![screenshot 2016 08 12 14 41 49 png 1920x1080](https://cloud.githubusercontent.com/assets/576623/17621384/975535b8-609b-11e6-9986-3db34fb63e1e.png)

Merging similar translation strings and making the strings shorter to fit the shortcode popup.

**Comment by mathetos** [comment]
@ramiy I think that works great. I don't see that in the PR above.

**Comment by DevinWalker** [comment]
Looks good to me

**Comment by ramiy** [comment]
![address1](https://cloud.githubusercontent.com/assets/576623/17608577/1690d4ba-6036-11e6-8130-07b86279c4d1.png)
![address2](https://cloud.githubusercontent.com/assets/576623/17608580/1978dc04-6036-11e6-8809-8f7d0435f0f6.png)

Fix in https://github.com/WordImpress/Give/pull/883/commits/d46d150245b419885ee21d8bba5be1292bb0f231.

Results:

![address4](https://cloud.githubusercontent.com/assets/576623/17643063/aaaf6180-6166-11e6-8b20-1d0903ad9e13.png)
![address3](https://cloud.githubusercontent.com/assets/576623/17643061/a65444b6-6166-11e6-9f9d-63a8559ba01d.png)
![address5](https://cloud.githubusercontent.com/assets/576623/17643064/aee7e3ee-6166-11e6-903a-1ebc64a94e4b.png)

**Comment by ramiy** [comment]
Found one more string that can be merged:

![floating-labels](https://cloud.githubusercontent.com/assets/576623/17649929/c6643f30-6248-11e6-958b-ef6ef209bf5a.png)
