### ISSUE TITLE
Donation amount not restored when clicking option after selecting custom amount

### ISSUE THREAD

**Issue by pippinsplugins** [WordImpress/Give#88]
If you have a form that has `Multi-level Donation` enabled and `Custom Amount` is enabled, there is a minor bug with the amount field when switching between options.

1. Click on an option. The amount updates
2. Click on Custom. The amount field gets focus
3. Click on an option. The amount field shows in read and the ajax message shows the amount is updating, but amount stays 0.
4. Click any option again and now the amount is properly populated.

![screen shot 2015-04-09 at 3 30 47 pm](https://cloud.githubusercontent.com/assets/1034109/7076257/b57d3f28-decd-11e4-9362-cb71a3914235.png)

![screen shot 2015-04-09 at 3 32 50 pm](https://cloud.githubusercontent.com/assets/1034109/7076256/b57bf56e-decd-11e4-96e1-1d285b652880.png)
![screen shot 2015-04-09 at 3 32 45 pm](https://cloud.githubusercontent.com/assets/1034109/7076265/d08d3a3e-decd-11e4-877e-834ef9dd5a29.png)

![screen shot 2015-04-09 at 3 32 35 pm](https://cloud.githubusercontent.com/assets/1034109/7076255/b57be7b8-decd-11e4-8b2c-13fa50fdea00.png)

**Comment by DevinWalker** [comment]
Heya @pippinsplugins - I'm glad you're getting hands on with the plugin! I believe I understand the issue you're talking about... but I haven't seen the amount not updating. I have seen the "flash" of red validation error, but not the amount getting stuck. Are you able to reproduce on the demo forms? http://givewp.com/demo 

I'm going to take a hard look at that today

**Comment by DevinWalker** [comment]
Specifically, this form https://givewp.com/demo/#forms-multi

**Comment by pippinsplugins** [comment]
This is happening because `var value_now = $( this ).val();` returns the value of the current amount field, which is 0.00

**Comment by pippinsplugins** [comment]
@DevinWalker I don't see it happening there but it is happening on my local.

**Comment by DevinWalker** [comment]
Any time for a pull request? I'd love to see you on the contributors list (although you're already a HUGE part of the plugin already).

**Comment by pippinsplugins** [comment]
Yep, I'm trying to track it down now.

**Comment by DevinWalker** [comment]
Cool - I'd also like to help fund the brewery :+1:

**Comment by pippinsplugins** [comment]
I saw wrong, it's this line `$( this ).next( '.give-updating-price-loader' ).stop().fadeIn().fadeOut();` (line 152.

**Comment by pippinsplugins** [comment]
I think the problem is that `update_multiselect_vals()` is running multiple times and stepping on its own toes.

**Comment by pippinsplugins** [comment]
Scratch that.

The animations all appears to work fine even with line 152 commented out, so something must be running twice.

Do you see an issue with removing that line?

**Comment by DevinWalker** [comment]
Checking now

**Comment by pippinsplugins** [comment]
Might try it on Twenty Fifteen. That's what I'm using.

**Comment by DevinWalker** [comment]
@pippinsplugins yep - Twenty Fifteen is having issues. I just switched from Twenty Twelve over and was able to reproduce

**Comment by DevinWalker** [comment]
Our templating system is also being bunched up within Twenty Fifteen - Separate issue there...
