### ISSUE TITLE
 PHP Notice:  Undefined variable: unlimited

### ISSUE THREAD

**Issue by sumobi** [WordImpress/Give#89]
When saving a transaction you get:

     PHP Notice:  Undefined variable: unlimited in /wp-content/plugins/Give/includes/admin/payments/actions.php on line 148

There's no reference to `_give_payment_unlimited_downloads` anywhere in the codebase so I'm going to assume that this is unused and should be removed.

**Comment by DevinWalker** [comment]
Yep that was brought over incorrectly. Thanks for your help!

**Comment by DevinWalker** [comment]
@sumobi looks like the line above can be removed as well
