### ISSUE TITLE
Convert all Doc links to Shortened URLs for better management

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#890]
Using shortlinks allows us to both track clicks better, but more importantly, manage the redirection better  so that we don't have to make plugin updates to fix links to documentation if urls change at all.

We can do this in a couple different ways:

1) Use a third party service like WordPress.com's (through Jetpack) or Bit.ly
2) Use YOURLS and we can create our own domain redirect, like give.xyz and own all our own data.

I prefer #2

**Comment by mathetos** [comment]
Some short domains that are available:
* gwp.press
* gwp.rocks
* gwp.fyi

**Comment by mathetos** [comment]
Bitly supports free branded domains for your shorter, and has tons of analytics. I suggest we set that up with docs.gives

**Comment by mathetos** [comment]
@DevinWalker I'm thinking to work on this for 1.8 since that's where the new Settings API is being implemented. Would you agree this should be on 1.8?

**Comment by DevinWalker** [comment]
If you can get it in 1.8 that'd be great. I think it's more of an ongoing task. Do you think you can get it in by 1.8 release?

**Comment by mathetos** [comment]
Yes, that's my intention.

**Comment by mathetos** [comment]
@DevinWalker What do you think of this for the Docs format in the Form Edit Screen:

![new-docs-links-give-1-8](https://cloud.githubusercontent.com/assets/930724/21415376/0561c772-c7be-11e6-92c8-7f8f50a5eb11.png)

**Comment by mathetos** [comment]
And here's the same in the Settings page:

![new-docs-links-settings-give-1-8](https://cloud.githubusercontent.com/assets/930724/21415504/628d1004-c7bf-11e6-94f6-e1436901e0aa.png)

**Comment by mathetos** [comment]
Let's get the format of these links straight first, then I can create them and implement them. Thanks!

**Comment by mathetos** [comment]
After some discussion with @DevinWalker we're going to go with just ONE doc link per section on the Form Edit screen. Bottom right aligned:

![image](https://cloud.githubusercontent.com/assets/930724/21416596/eebf0f9c-c7c8-11e6-8d81-658e1d9b47af.png)

**Comment by mathetos** [comment]
And here's settings:

![image](https://cloud.githubusercontent.com/assets/930724/21416804/aabd5d38-c7ca-11e6-8654-321c40a50bab.png)

**Comment by DevinWalker** [comment]
@mathetos I see privacy issues when clicking on doc links:
![2016-12-28_21-56-12](https://cloud.githubusercontent.com/assets/1571635/21537598/a854cf6c-cd48-11e6-9810-c5f327d47439.png)

**Comment by mathetos** [comment]
@DevinWalker I see. They all need to be HTTP instead of HTTPS. Easy fix.

**Comment by mathetos** [comment]
@DevinWalker new PR to address HTTP/S issue. #1375

**Comment by mathetos** [comment]
PR #1375 is merged. Closing.

**Comment by ravinderk** [comment]
@mathetos 
Can you reconfirm that all docs link are working or not because I found one.

<img width="1169" alt="screen shot 2017-01-17 at 11 08 36 am" src="https://cloud.githubusercontent.com/assets/1784821/22008903/61efd3ca-dca5-11e6-889e-44380347088b.png">
<img width="1182" alt="screen shot 2017-01-17 at 11 05 12 am" src="https://cloud.githubusercontent.com/assets/1784821/22008905/6474ef40-dca5-11e6-8060-d97cb92e95b6.png">
