### ISSUE TITLE
Support donor paying CC fees

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#892]
Many organizations want to give donors the ability to pay the credit card fees themselves rather than have the organization absorb the fee directly. This isn't so straight-forward. Currently only WePay provides this by default.

If we wanted to make this an option across all Gateways, we'd have to do some complex math based on either the exact amount each Credit Card is charging, or allow the organization to just set a percentage themselves per form, or per gateway.

Stripe explains how the math behind it really isn't so straight forward:
https://support.stripe.com/questions/can-i-charge-my-stripe-fees-to-my-customers
![https://media.stripe.com/uploads/c3cfe023ed78a4d9438184901986d87506c43132.png](https://media.stripe.com/uploads/c3cfe023ed78a4d9438184901986d87506c43132.png)

Here's a few ideas on how we could do this:
## Admin Setting

Add a Global setting in "Settings > Payment Gateways" to enable a checkbox on all forms that says "Want to donate the credit card fees as well?" Then per form there's a setting to allow the admin to determine how much to charge additionally between 2-5%.

Alternatively, we'd offer no global at all, and just do it all per form.
## Per Gateway Options

In Give Core we create an advanced `Give_CC_Fees` class which could be extended per Gateway. The goal of this class would be to apply the exactly correct fee amount to the total donation based rather than a simple percentage increase. 

The math on this would really have to be spot-on and would definitely take a lot of testing to get it right.

**Comment by DevinWalker** [comment]
We're going to make this into an Add-on

**Comment by DevinWalker** [comment]
https://github.com/WordImpress/Give-Gateway-Fees
