### ISSUE TITLE
Dynamic Hooks

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#897]
I think we should gradually adopt wordpress core standards.

Dynamic hooks like:

`do_action( 'give_hook_name_' . $dynamic_field );`

Should be replaced with:

`do_action( "give_hook_name_{$dynamic_field}" );`

One more step to **Give Developer Resources**, just like **[WordPress Code Reference]( https://developer.wordpress.org/?s=%7B&post_type%5B%5D=wp-parser-hook)**.

**Comment by DevinWalker** [comment]
Sounds good. I'm fine with that.

**Comment by ramiy** [comment]
@DevinWalker,

You closed the issue before I had the chance to commit the fix.

**Comment by DevinWalker** [comment]
It's not in here? https://github.com/WordImpress/Give/pull/899/files

**Comment by DevinWalker** [comment]
More PRs, reopening

**Comment by ramiy** [comment]
All actions and filters updated.
