### ISSUE TITLE
Currency icon css issue for money field

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#902]
**How to reproduce issue:**
To reproduce this issue, set currency position to after in give plugin settings and then go to form edit screen.

**Issue screenshot:**
<img width="784" alt="screen shot 2016-08-17 at 10 11 37 am" src="https://cloud.githubusercontent.com/assets/1784821/17724855/3e77ab44-6463-11e6-8a0c-0b1dcc3342a5.png">
<img width="768" alt="screen shot 2016-08-17 at 10 11 51 am" src="https://cloud.githubusercontent.com/assets/1784821/17724856/3ec26b98-6463-11e6-9484-82f87e738eeb.png">

**Comment by DevinWalker** [comment]
After merging #908 I'm seeing a CSS bug:

![screenshot at aug 17 13-00-44](https://cloud.githubusercontent.com/assets/1571635/17751155/b85e8fec-647a-11e6-905e-2b6302d8fbc6.png)
