### ISSUE TITLE
Property of non-object on Forms Report

### ISSUE THREAD

**Issue by pippinsplugins** [WordImpress/Give#91]
When loading the Forms report page, I'm seeing this error:
```

Notice: Trying to get property of non-object in /Users/pippin/Sites/edd/wp-content/plugins/give/includes/class-give-html-elements.php on line 169
```

**Comment by pippinsplugins** [comment]
This is happening because there are no categories for forms. This appears to be left over from EDD.

**Comment by pippinsplugins** [comment]
Ah, I see that categories need to be enabled.

get_terms() is returning a WP_Error since the taxonomy isn't registered:
```
object(WP_Error)#542 (2) { ["errors"]=> array(1) { ["invalid_taxonomy"]=> array(1) { [0]=> string(16) "Invalid taxonomy" } } ["error_data"]=> array(0) { } }
```

**Comment by DevinWalker** [comment]
@pippinsplugins great PR - I'm wondering why I haven't stumbled upon this PHP error yet... I'm running WP_DEBUG and I believe error reporting is set to strict... Thanks for the PR!

**Comment by pippinsplugins** [comment]
It only happens when the taxonomy hasn't been registered before.

**Comment by DevinWalker** [comment]
Ok that explains it.
