### ISSUE TITLE
Thousands separator doesn't respect apostrophe's

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#913]
As reported here:
https://wordpress.org/support/topic/amount-on-page-is-only-showing-the-30-day-total-and-not-the-full-amount-raised?replies=12#post-8768575

And tested locally, our amounts get badly output if an apostrophe is used as the thousands separator, which apparently is what is used for the Swiss Franc in Switzerland.
![core-thousands-separator-apostrophe-bug](https://cloud.githubusercontent.com/assets/930724/17757815/e49c41f2-649e-11e6-9a19-7ee390974abf.png)

**Comment by DevinWalker** [comment]
This is fixed:

![screen shot 2016-08-22 at 3 48 52 pm](https://cloud.githubusercontent.com/assets/1571635/17874456/9aa605c0-6880-11e6-8498-18c6c9731e11.png)
