### ISSUE TITLE
a11y: newsletter form

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#924]
In the about page we have a newsletter form. The `<input>` fields in the form use `placeholder` attributes to display the fields.

We need to add `<label>` fields above each input field, add `for` attributes to reference to the field, and hide the labels using WordPress `screen-reader-text` class. This way only screen-readers will "see" the labels.

![newsletter-form](https://cloud.githubusercontent.com/assets/576623/17841573/9d40b5ea-6822-11e6-909b-fc350e37d595.png)

**Comment by DevinWalker** [comment]
Sounds good.
