### ISSUE TITLE
PHP warning when exporting PDF

### ISSUE THREAD

**Issue by sumobi** [WordImpress/Give#93]
When there's no categories or tags and you try and export a PDF you receive a couple of these errors:

    PHP Warning:  strip_tags() expects parameter 1 to be string, object given in /wp-content/plugins/Give/includes/admin/reporting/pdf-reports.php on line 112

Changing 

    $categories = $categories ? strip_tags( $categories ) : '';
    $tags = $tags ? strip_tags( $tags ) : '';

to

    $categories = ! is_wp_error( $categories ) ? strip_tags( $categories ) : '';
    $tags = ! is_wp_error( $tags ) ? strip_tags( $tags ) : '';

will fix this

**Comment by DevinWalker** [comment]
:+1: love it. At the last minute we decided form taxonomies would be disabled by default... we didn't realize the can of worms it would open having them unregistered. Thanks for the PR.
