### ISSUE TITLE
Donation Notes & Donor Notes

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#933]
Both the **Donor** and the **Donation** have notes functionality.

BUT, they have different UI, and not consistent functionality.

![donors-notes](https://cloud.githubusercontent.com/assets/576623/17853149/89f6337e-6873-11e6-9adb-f0d7e5864c77.png)

![donations-notes](https://cloud.githubusercontent.com/assets/576623/17853156/919a51f0-6873-11e6-9560-7475cf45d3eb.png)
- One has "delete" link, the other has not.
- One shows the "user", the other don't.
- One has textarea before the notes, the other after.
- One shows notes in one line, the other in two.

Also, considering a11y, we can use tables to display the notes. Currently those are DIVs with lots of CSS. We can use the builtin WordPress table css, reducing custom css to the minimum.

**Comment by DevinWalker** [comment]
Closing in favor of: https://github.com/WordImpress/Give/issues/1206 which addresses the larger issue of the donor UI in general.
