### ISSUE TITLE
Give tabs

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#936]
In the admin area, the plugin has 3 admin screens using tabs:
* Settings
* Reports
* Donor Profile

The first two screens use WordPress `nav-tab-wrapper` class. The "donor" screen use custom CSS generated by Give plugin. That is why it looks different.

In my opinion, we should remove all the custom tab CSS, replacing it with `nav-tab-wrapper` class. 

This way we are unifying the look&feel, reducing the give css and using wordpress built-in classes.

**Comment by DevinWalker** [comment]
@ramiy can we keep the dashicons in use?

**Comment by ramiy** [comment]
@DevinWalker Yes of course.

**Comment by ramiy** [comment]
BTW, while we where discussing about `.nav-tab-wrapper` class, my first wp core commit for 4.7 was just accepted. Improving the `.nav-tab-wrapper` class. https://core.trac.wordpress.org/ticket/37257

**Comment by DevinWalker** [comment]
Nice! Let's do it then. The less CSS in our plugin, the better. Congrats on the 4.7 commit. One thing that bothers me about the tabs is how they stack when there are too many.

**Comment by ramiy** [comment]
OLD:

![donor-tabs-before](https://cloud.githubusercontent.com/assets/576623/17872845/bd3745e6-68ca-11e6-8f05-dfeea48aa017.png)

NEW:

![donor-tabs-after](https://cloud.githubusercontent.com/assets/576623/17872857/cfdc6c62-68ca-11e6-8492-4e76aa356d29.png)

**Comment by ramiy** [comment]
I don't like the result. The icons are not align properly.

**Comment by DevinWalker** [comment]
Looks OK minus the icon alignment

**Comment by DevinWalker** [comment]
This is fixed
