### ISSUE TITLE
Pre-populate First and Last name in PayPal Standard

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#945]
PayPal has documentation on how to pre-populate fields in their payment form from your own payment form:
https://www.paypal.com/cgi-bin/webscr?cmd=_pdn_xclick_prepopulate_outside

Currently, we are passing the email address to PayPal Standard correctly, but not the first/last name. See here:

![paypal-after-hitting-donate-fields-empty](https://cloud.githubusercontent.com/assets/930724/17903089/09488fd6-691f-11e6-9352-02c0bce7c631.png)

## Recommendation

1) Make sure at minimum the First/Last names and emails are always populated correctly
2) We have a snippet to ask the donor for address information as well. That should be updated to pass the information correctly as well. https://github.com/WordImpress/Give-Snippet-Library/issues/4
3) We should consider adding a "Ask for Mailing/Billing Address" option to PayPal Standard as well.

**Comment by Benunc** [comment]
do we send billing info (per the second Point in the original post's recommendation?) have a customer asking about that.

**Comment by DevinWalker** [comment]
@Benunc if they add the fields to PayPal standard you mean?

**Comment by Benunc** [comment]
correct. if they add billing info fields, are those passed on to PayPal?

**Comment by DevinWalker** [comment]
Yes they are, it looks like `address1`, `address2`, `city`, `country`, current is passed but for some reason not `state`... I'll add that now.
