### ISSUE TITLE
a11y: View Details

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#946]
Some links need contextual clarification. Links like "**View Details**".

Regular people see the context. They have visual aids. For blind people we use `aria-label` tags with more clarification.

Also, we need to replace the generic "**View Details**" string with a specific strings: "**View Donation**", "**View Donor**", "**View Form**", "**View Receipt**" etc.

**Comment by ramiy** [comment]
![view-reciept](https://cloud.githubusercontent.com/assets/576623/17914161/7fd022d4-69a8-11e6-8223-dd33bf1b4424.png)

![view-donor](https://cloud.githubusercontent.com/assets/576623/17914164/86279a04-69a8-11e6-81b0-6c919909f155.png)

![view-donation](https://cloud.githubusercontent.com/assets/576623/17914172/90523dea-69a8-11e6-94c5-20e363521561.png)

**Comment by DevinWalker** [comment]
Thanks
