### ISSUE TITLE
Inconsistent UI when switching Report types

### ISSUE THREAD

**Issue by pippinsplugins** [WordImpress/Give#95]
The default view for the Reports page is the `Income` type. On this page, the `Report Type` drop down is on the right. When changing to the `Forms` or `Donors` report type, the drop down moves to the left:
![screen shot 2015-04-09 at 4 18 15 pm](https://cloud.githubusercontent.com/assets/1034109/7077132/11235488-ded4-11e4-9459-5e4b96105b3a.png)
![screen shot 2015-04-09 at 4 18 23 pm](https://cloud.githubusercontent.com/assets/1034109/7077131/11231284-ded4-11e4-951f-319b220ef911.png)

**Comment by pippinsplugins** [comment]
The search input on some reports does get in the way:
![screen shot 2015-04-09 at 4 19 50 pm](https://cloud.githubusercontent.com/assets/1034109/7077167/4dcfa738-ded4-11e4-9be8-b02d131dbb79.png)

Perhaps moving the report type all the way to the right and putting search to the left of type would work?

**Comment by DevinWalker** [comment]
Yeah good point. I just wanted to prevent them from bumping to two lines. Totally see what you are saying about it being inconsistent and thus confusing.
