### ISSUE TITLE
Notices generated when user submit donation form

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#954]
<img width="1203" alt="screen shot 2016-08-24 at 7 28 56 pm" src="https://cloud.githubusercontent.com/assets/1784821/17933288/25564cf0-6a31-11e6-9119-489e495365d9.png">

**Step to produce issue**
Set ' as thousand separator and . as decimal separator. Then submit any donation form with thousand or more then amount.

**Why this happen**
If you follow same step as i explained above then your donation amount for example `10'000.00` will be escape automatically in `$_POST` and you will get `10\'000.00` which will process issue because we are not handling this use case.

**Comment by DevinWalker** [comment]
Good catch
