### ISSUE TITLE
Fix pre-4.6 backwards compatibility which broke unit tests 

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#957]
The usage of 4.6 only functions, specifically `do_action_deprecated` from #950, is now breaking compatibility with pre-4.6 versions of WordPress as well as our unit tests.

**Option 1:**  We copy the function and wrap it in `if(!function_exists('apply_filters_deprecated')) { //function here }` until we're ready to bump our minimum to ver. 4.6

**Option 2:** We do similar to what we did with `_give_deprecated_function` https://github.com/WordImpress/Give/blob/master/includes/misc-functions.php#L515 and create a `_give_deprecated_action` which is essentially a copy of WP core's `_deprecated_hook` function.

---

I'm leaning on option 2 - @ravinderk let's discuss

**Comment by ravinderk** [comment]
@DevinWalker I like  second one.
