### ISSUE TITLE
Donor Profile - Donations History

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#959]
Why having two tables?

![donors-profile-donations-table](https://cloud.githubusercontent.com/assets/576623/17951804/bf0e7f0c-6a6d-11e6-9b23-f62f6c3e29af.png)

**Comment by DevinWalker** [comment]
Yeah I agree, it can improve:

![screen shot 2016-08-26 at 10 35 11 am](https://cloud.githubusercontent.com/assets/1571635/18014664/d30ed5b8-6b78-11e6-9eaa-2393a9c1b9f1.png)

**Comment by ramiy** [comment]
@DevinWalker  Ok, now I see the difference.

How about extending the "Completed Donations" table. To show the "Total Donated Amount" per form (per user), to show how much the donor donated totally to each form. And make the amount clickable, linking to the "donation" page filtered by user.

**Comment by DevinWalker** [comment]
I like the sound of that, a definite improvement. Do you think that the UI is confusing though? Most donors won't have nearly as many donations as I do... that's why you were confused it seems. I haven't heard any questions in support about that. Maybe a non-issue?

**Comment by ramiy** [comment]
Non-issue, enhancement...

**Comment by DevinWalker** [comment]
Let's leave this open and pivot it to improving the UI of this element

**Comment by DevinWalker** [comment]
Closing as we already have an open issue to address revamping this page's UI.
