### ISSUE TITLE
When exporting a report, apostrophe's are not correctly shown

### ISSUE THREAD

**Issue by sumobi** [WordImpress/Give#96]
When exporting a report, apostrophe's are not correctly shown:

![screen shot 2015-04-09 at 5 10 59 pm](https://cloud.githubusercontent.com/assets/52581/7078063/7e7a223a-dedb-11e4-8d7e-614fcb36c32d.png)

I looked at `$form` and it seems the post title is already there for the picking:

![screen shot 2015-04-09 at 5 12 47 pm](https://cloud.githubusercontent.com/assets/52581/7078079/b0b46d46-dedb-11e4-8152-f983575910a9.png)

I could be mistaken, but I think it makes sense to use `$form->post_title;` since WordPress has already properly decoded it.

And after:

![screen shot 2015-04-09 at 5 14 16 pm](https://cloud.githubusercontent.com/assets/52581/7078106/e31ea364-dedb-11e4-965b-225c87f4ac82.png)

**Comment by DevinWalker** [comment]
Thanks :+1:
