### ISSUE TITLE
Change some settings to properly reflect Enable/Disable Correctly

### ISSUE THREAD

**Issue by mathetos** [WordImpress/Give#962]
Throughout the plugin we often mixed the purposes of settings between Enable/Disable, or Show/Hide in ways that can cause confusion.

Here's one example:
![enable-disable-settings-confusion](https://cloud.githubusercontent.com/assets/930724/17985140/53f7cab4-6ac9-11e6-815e-603e708534e1.png)

Three different settings, checking one enables, while checking another disables. 

I propose something like the following instead:
![enable-disable-settings-suggestion](https://cloud.githubusercontent.com/assets/930724/17985261/e6a4b4da-6ac9-11e6-8ba3-8ffd02bae96a.png)

This would apply to every setting that uses language like True/False or On/Off, Show/Hide, Enable/Disable. Consistency in our settings is important to the user experience.

**Comment by DevinWalker** [comment]
What's the UI best practice here? I feel a checkbox is pretty easy to understand... but radios, makes sense too.

**Comment by mathetos** [comment]
I think if it's a checkbox it needs to ALWAYS be "Enable". To check it in order to "Disable" is counterintuitive. But I think the radio buttons make it all as obvious as possible and avoid any confusion because they show ALL the options directly.

**Comment by ramiy** [comment]
I agree with @mathetos.

Although check-boxes are simple operators, the current wording "**Enable this option if you would like to disable the ...**" can be very confusing. With radio button we remove the confusion factor from the equation.

**Comment by mathetos** [comment]
OK, here's a list of all the options on the "Donations > Settings" page tabs that need updating:

### Payment Gateways Tab
- [ ] Test Mode -- Enabled (default) | Disabled 
- [ ] "PayPal IPN Verification" -- Enabled (default) | Disabled (Enabled is default)
- [ ] "Collect Billing Details" (Offline Donations) -- Yes | No (default)

### Display Options Tab
- [ ] "Disable CSS" change label to "Native Give Styles" -- Enable (default) | Disable 
- [ ] "Enable Floating Labels" change to "Floating Labels" -- Enable | Disable (default)
- [ ] "Disable Welcome Screen" change to "Welcome Screen" -- Enable (default) | Disable
- [ ] "Disable Form Single Views" change to "Form Single Views" -- Enable (default) | Disable
- [ ] "Disable Form Archives" change to "Form Archives" -- Enable (default) | Disable
- [ ] "Disable Form Excerpts" change to "Form Excerpts" -- Enable (default) | Disable
- [ ] "Disable Form Featured Image" change to "Form Featured Image" -- Enable (default) | Disable
- [ ] "Disable Single Form Sidebar" change to "Single Form Sidebar" -- Enable (default) | Disable
- [ ] "Enable Form Categories" change to "Form Categories" -- Enable | Disable (default)
- [ ] "Enable Form Tags" change to "Form Tags" -- Enable | Disable (default)

### Emails Tab
- [ ] "Disable Admin Notifications" change to "Admin Notifications" -- Enable (default) | Disable

### Advanced Tab
- [ ] "Email Access" -- Enable | Disable (default)
- [ ] "Remove All Data on Uninstall" -- Yes | No (default)
- [ ] "Disable `the_content` filter" change to "Single Form Content Filter" -- Enable (default) | Disable
- [ ] "Load Scripts in Footer?" -- Yes | No (default)

### Add-ons
I'll make additional issues in the respective Addons that reference this issue, but from a quick review this would apply most often to the Payment Gateways.

**Comment by mathetos** [comment]
These were all addressed in this commit: https://github.com/WordImpress/Give/commit/190c40819103c6c9913217411f2dbf99e27d8c71#diff-6924b08d48020e0edf6de7c45b3a974b

But it raises a new issue which I'll create now.

**Comment by DevinWalker** [comment]
This is complete in `release/1.8`
