### ISSUE TITLE
PO/MO language files and i18n improvements in 4.6

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#967]
Now that we adopted the new translation standards using [translate.wordpress.org](https://translate.wordpress.org/) we can ditch our PO/MO files located in the `give/languages/` folder.

See i18n improvements in 4.6: https://make.wordpress.org/core/2016/07/06/i18n-improvements-in-4-6/

The plugin has two translation versions:
* `wp-content/plugins/give/languages/give-{lang}_{local}.mo` - provided by the plugin.
* `wp-content/languages/plugins/give-{lang}_{local}.mo` - translated by the community and downloaded automatically when new translations are available.

In the past, WordPress was searching for available translation files in the plugin-folder before checking the community-translations. Since 4.6 it checks the community-translations before checking the plugin-translations. The translation files attached to the plugin are absolute anyway. We can safely remove them. And reduce the plugin size.

The way the core is developed, I guess that in a few versions all the translations will be remove entirely from the plugin folder.

----

**Note 1:** We no longer need to call `load_plugin_textdomain()` but it's a good practice the remain this call for older WordPress versions.

**Note 2:** We no longer need the `Text Domain: give` header in `give.php` file, but it's a good practice the remain this for older WordPress versions.

----

As mentioned in #964, we should delete the entire CMB2 languages directory. It's useless, all the translation strings are loaded from Give language packs anyway. The CMB2 language files are just taking space, making the plugin much bigger than it is.

**Comment by ramiy** [comment]
@DevinWalker I should mention again that this applies to plugins hosted on wp.org. Plugins and Add-ons not on the repo have to remain the translation files.

Each Add-on should have a language folder.

**Comment by DevinWalker** [comment]
Yep, understood.
