### ISSUE TITLE
CSS sourcemaps are not working

### ISSUE THREAD

**Issue by ramiy** [WordImpress/Give#968]
The CSS source map adds `/*# sourceMappingURL=... */` to our `*.css` files. This allows the browser to map CSS files generated by SASS, and allows developers to update the SCSS files directly from the browser.

### The Issue
Our current gulp task adds the source mapping URL only to `*.css` file. But we never load them, we load only the minified css files.

### The Solution
We need to add source mapping URL to `*.min.css` css files.

**Comment by DevinWalker** [comment]
They should be working. The gulp task creates a `sourcemaps` directory:

<img width="244" alt="screenshot at aug 29 23-26-24" src="https://cloud.githubusercontent.com/assets/1571635/18078399/29711988-6e40-11e6-8884-01d22b44664d.png">

When I view source I see the path to the appropriate sass file:

<img width="443" alt="screen shot 2016-08-29 at 11 26 48 pm" src="https://cloud.githubusercontent.com/assets/1571635/18078410/3990b8f0-6e40-11e6-8703-1b22cb47090f.png">

It's not working that way for you?

**Comment by ramiy** [comment]
Not working for me....

![screenshot 2016-08-30](https://cloud.githubusercontent.com/assets/576623/18083266/121448e4-6eab-11e6-8809-b178e085eb6e.png)

**Comment by DevinWalker** [comment]
That's CMB2 - try an element that's Give related

**Comment by DevinWalker** [comment]
Did you also do this in Chrome: https://www.dannycroft.co.uk/enabling-source-maps-in-chrome/
