### ISSUE TITLE
Encode html link print for empty offline donation message

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#981]
<img width="421" alt="screen shot 2016-08-30 at 5 16 08 pm" src="https://cloud.githubusercontent.com/assets/1784821/18088038/cd903ee6-6ed5-11e6-857b-6175d91e38bc.png">

**Step to produce:**
1.  Set "**Customize Offline Donations**" to yes in any form setting.
2. Set "**Offline Donation Instructions**" to empty content.

**Comment by DevinWalker** [comment]
Thanks!
