### ISSUE TITLE
Donors unable to see certain transactions in history, depending on logged-in status.

### ISSUE THREAD

**Issue by Benunc** [WordImpress/Give#983]
If a donor makes a donation without logging in and before creating an account, when they later create an account, the donations show up on the donation-history page while logged in. But from then on (after creating the account), if they make a logged out donation using that email address, those donations will be correctly tied to the donor in the back end, but incorrectly displayed in the front end (sometimes). If it is the same browser the logged-out donation was just made in, the donor will be able to see their entire donation history on the donation-history page (including logged-in donations, and pre-account donations). If the user then goes and logs in, the donation-history page will only show the donations made while logged in or before creating the account.

Potentially related to #970 

## Steps to replicate: 

1. Create a form where logged out donations are permitted
1. Create a page named "Register" with a `[give_register]` shortcode
345. from a logged-out browser, submit a test donation using a simple email
23445. Go to the register page and create an account with the same email, and register and log in.
21. visit the donation history page. Transaction(s) made before account creation should appear correctly.
43. from a separate logged-out browser, submit a new donation with the same email.
32. before logging in, view the donation history page. All transactions should show up correctly.
22. log in to the same account again, and view the donation history page again. any logged-out donations no longer appear in the donation history. (but they are recorded to the correct donor on the back end).

**Comment by DevinWalker** [comment]
Thanks @Benunc - @ravinderk is looking into this today and will let us know what he finds out about this issue and #970
