### ISSUE TITLE
$decimals parameter in give_format_amount needed

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#985]
@ravinderk is this parameter is no longer needed here https://github.com/WordImpress/Give/blob/release/1.6.1/includes/formatting.php#L138 since your merge here right?  https://github.com/WordImpress/Give/commit/9dbd9205cba33bfb6e993659648b35a01fd7cb73#diff-2546a9acd2c7285ecc761a6547c886ff

**Comment by ravinderk** [comment]
@DevinWalker Yes. we need `$decimals` parameter for formatting. Somehow, I forget to use that. thanks for point out.
https://github.com/ravinderk/Give/commit/561d29465617446378cc420b074f3f70c5f291ad

Let me know in which branch I can do pull request.

**Comment by DevinWalker** [comment]
Hey @ravinderk please submit to `master`

**Comment by ravinderk** [comment]
@devin Alright
