### ISSUE TITLE
Readme.txt screenshot issues

### ISSUE THREAD

**Issue by DevinWalker** [WordImpress/Give#990]
Looking through the screenshots here: https://wordpress.org/plugins/give/screenshots/ it looks like the descriptions get mixed up: 

<img width="673" alt="screenshot at aug 30 21-36-10" src="https://cloud.githubusercontent.com/assets/1571635/18116108/dd7fad5e-6ef9-11e6-98e1-971fd026b0cc.png">

@mathetos do you think you could take care of this in the `master` branch?

**Comment by mathetos** [comment]
We can make this change in master without a version bump for sure. But looks like you already did that. Looks good!
