### ISSUE TITLE
Stop donor from saving empty email adress

### ISSUE THREAD

**Issue by ravinderk** [WordImpress/Give#999]
![btwgu3qjsf](https://cloud.githubusercontent.com/assets/1784821/18168076/89b3a6d4-7071-11e6-9ebf-440b0732712a.gif)

**How to produce**
1. Create a donor profile editor page using `[give_profile_editor]`. 
2. Goto this page and save empty email address.

**Comment by DevinWalker** [comment]
Good catch, there needs to be validation on that field for sure.
